### ISSUE TITLE
Future integrations: Datawrapper

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#100]
Need to explore more in the future, but Datawrapper is really cool for data visualization. This could be something we point to as opposed to have included natively as I don't know the full scope of the project when deployed locally but it's very cool if you play w/ their webservice / paid version -- https://github.com/datawrapper/datawrapper

**Comment by kfurst** [comment]
Whether native or add-on, it would be great to have this incorporate both with the data stored in the/a LRS and external sources.  Our student information systems do incorporate a dashboard type charting system yet it is based solely on data within that system which will always be limited in scope. I would love to assemble it visually via automation into the hub for learning (i.e. ELMS). They do have the capability to broadcast via xml syncs.

**Comment by btopro** [comment]
@heyMP tagging you to see if this project would be of interest. it's a chart making application; stand alone and not something we need to pull in but could be cool as part of interact if it's something useful
