### ISSUE TITLE
Possible Image Rendering Glitch

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1001]
I noticed that the page icon was showing up twice on the content outline as seen in the screenshot below. Not sure if that's intentional or not. 
![image_glitch](https://cloud.githubusercontent.com/assets/7243665/16587812/5da8a3a0-429a-11e6-8beb-3ced42a621a4.png)

**Comment by btopro** [comment]
it means you updated those pages and set the instructional significance. This isn't the image displaying twice so much as an intentional setting to hav ea page there. See if just saving another page brings about an icon (as this isn't the intention). If that happens, then we've got a bug cause it should only show a page icon if instructional significance has been set for the item to be reading / etc

**Comment by mmilutinovic1313** [comment]
If we don't want the default to be reading I can figure out how to change that - but I'm thinking it might be good to have that as the default setting -- since most things would be readings.

**Comment by btopro** [comment]
Hmm, well, on creation though it's not actually visualized so it's like setting a default after the fact but not respecting it initially. So it's a minor but annoying bug / confusing as to when it's doing it. I'd say let's default it to nothing.

**Comment by mmilutinovic1313** [comment]
I found where the default is being called. There is no `-None-` attribute in the `settings` array. Do we add a blank one then?

```
'settings' => array(
      'allowed_values' => array(
        'page' => 'Reading',
        'demonstration' => 'Demonstration',
        'interview' => 'Interview',
        'lecture' => 'Lecture',
        'exercise' => 'Exercise',
        'writing' => 'Writing',
        'assignment' => 'Assignment',
        'groupwork' => 'Group work',
        'finalproject' => 'Final project',
        'critique' => 'Critique',
        'speechballoons' => 'Discussion',
        'recitation' => 'Recitation',
        'seminar' => 'Seminar',
        'workshop' => 'Workshop',
        'quiz' => 'Quiz',
        'exam' => 'Exam / Mid-term',
        'final' => 'Final Exam',
      ),
      'allowed_values_function' => '',
      'cis_connector_access' => FALSE,
      'cis_connector_disable' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );
```

**Comment by mmilutinovic1313** [comment]
`-None-` exists in the choices -- I'm guessing this is just how dropdowns work by default however.

**Comment by btopro** [comment]
well, I'm guessing something on the saving side is going "if there's nothing, then make it a page". Keep digging :)

**Comment by mmilutinovic1313** [comment]
Default is now `-None-` and is working now in PR #1002

**Comment by btopro** [comment]
nice
