### ISSUE TITLE
Chrome Extension / Browser Shortcut for sending tincan statements to ELMSLN/Learning Locker

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1004]
Wouldn't it be cool to have students report to Learning Locker that they just read an article that is related to their current course by clicking a button? I saw a presentation where they demonstrated this https://youtu.be/TQpZ6JyluAE?t=12m1s
## Possible Scenario

I'm taking an Intro to Drupal course on ELMS:LN.  I'm browsing the web for Drupal resources and I see an interesting article talking about how to create a 'Views Relationship'.  I read through it and decide that I want to report that to my instructor that I read the article.  
- I click my browser extension that says "Save experience".
- I see a list of my courses listed in ELMS:LN, I select "Intro to Drupal"
- I can select what type of experience it was; I select "read"
- I select "save"

The browser extension sends POST to the following url `courses.college.edu/drupal101/api/tincan-remote-statement` with all of the data I submitted.  ELMS tacks on Learning Locker authentication, user information. etc and shoots it over to Learning Locker.

**Comment by btopro** [comment]
hmm... do you leave the page? Quickpost Bookmarklet (technically in core) has some capabilities like this (not same exactly but ballpark) https://www.drupal.org/project/quickpost_bookmarklet . It takes the approach of prepopulating node submission forms so that you drag the magic link on a node submit form up to the browser bar as a shortcut, go to any link, highlight some text and then click the bookmarklet it'll take you to the node submit form with title and body prepopulated with what was highlighted and where you were.

Love the idea either way, becomes a workflow / usability paradigm as opposed to a technical problem.

**Comment by btopro** [comment]
bringing to @rickhumphries @kfurst 's attention

**Comment by btopro** [comment]
@djfusco this also seems like an idea up your alley. Goal was a stand alone chrome extension, see any practical usage in classes here?

**Comment by djfusco** [comment]
Maybe you all saw this already, but this works pretty well.  Would this work for what you're trying to do?  RE: its use in class - definitely.  I've thought of having a way for students to build a 'resource repository' for other students to learn from what previous students found for a given class.  http://tincanapi.com/bookmarklet/ @btopro @rickhumphries @heyMP

**Comment by btopro** [comment]
@djfusco this is awesome! I wonder if we couldn't reverse engineer the output of this to make our own statement generators

**Comment by btopro** [comment]
```
javascript: function rbm()%7Bwindow.rbmAuth%3D"Basic ZDhlMjEzNGEyZWVkNzgxM2UxNzFjZTMyOWY2ZTk0Y2EzYjg5ZjE2ZDphNGRkMDM5YzhkZTY0MDNmMWI2ZDk1NDljOTEzZTUyMmE0OTA5NmFk",window.rbmEndpoint%3D"http://eli-ll.vmhost.psu.edu/data/xAPI/",window.rbmEmail%3D"bto108%40psu.edu",window.rbmName%3D"btopro"%3Bvar a%3Ddocument,b%3Da.createElement("sc"%2B"ript"),c%3Da.body,d%3Da.location%3Bb.setAttribute("src","https://tincanapi.com/wp-content/assets/Bookmarklet/3.4.0/bookmarklet-min.js")%3Bc.appendChild(b)%7Drbm()%3Bvoid 0
```

**Comment by btopro** [comment]
it's very clever because it base64 encodes your username/password and then stuffs it in as the headers it ships off to the LRS location and lets them pick between a few verbs to do the generation!

**Comment by rickhumphries** [comment]
@btopro @djfusco I love the idea of the resource repository - kind of like generating your own pinterest board for a particular course that you can share with, and remix from others students.

Just on the subject of other examples out there - I always used the following 'I did this' extension when testing my LRS setup:
https://chrome.google.com/webstore/detail/i-did-this/bnkehgbnnfgelmnfbjicdcicafoeogka?utm_source=chrome-app-launcher-info-dialog

**Comment by btopro** [comment]
Bookmarklet can provide this. Not sure this is in scope of elmsln at this time. the futuristic LMS-less stuff where elms has an accompanying browser plugin would be able to do this. Otherwise, cool discussion we can reopen at a later date if it becomes relevent
