### ISSUE TITLE
Gitbook.com Plugin for ELMS:LN

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1006]
We need a way to ingest Gitbook content into an ELMS:LN book for the course outline service. I'm thinking we need a gitbook plugin to automatically generate a file to describe to ELMS:LN how to ingest the content.

I'm specifically interested in ingesting this book (under heavy development): https://www.gitbook.com/book/dmd-program/dmd-course-materials/details

See this repo for a sample gitbook plugin: https://github.com/GitbookIO/plugin

**Comment by btopro** [comment]
#1243 is asking for the same thing
