### ISSUE TITLE
Future Integrations: Learning Locker

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#101]
https://github.com/LearningLocker/learninglocker

Learning Locker is a php based, open source Learning Record Store (LRS). @rickhumphries has it hooked up with their elmsln deployment and it's something that we should seriously consider coming up with an automated way of setting up in the future. It's simple, powerful, and uses TinCan / xAPI which from what I've seen is the right way to do something like this.

They will be contributing code from those developments in the future and there's some xAPI - drupal work that's in sandbox projects already.

**Comment by kfurst** [comment]
Cool. From the K-12 perspective, the focus on the analytics stored in an LRS are crucial. Our local move to standards based grading (SBG), mapping outcomes/learning goals to standards and so forth desperately needs an integrated tool like this where I can track progress at a very granular level across a spectrum of competencies over a 13 year period (which is a lot of data). 

(And to give a strong reason to dump the traditional gradebook as the only option internally in our org).

**Comment by btopro** [comment]
https://gist.github.com/btopro/3834948e2ccacd0a9583 install directions for RHEL/CentOS 7

**Comment by btopro** [comment]
I think we should come up with installation instructions and help streamline this but it's a mongodb based database system and it seems a bit silly to throw this into the core package; much like piwik for analytics, we'd be installing too many beefy systems in one place (or at least helping create that future) when really we should be making scripts and documentation and robots that help stitch it all together for people. This might be a good thing to consider automated support for in https://github.com/elmsln/Ulmaceae

Closing for now as we have 2 confirmed cases of integrating elmsln and learning locker so it is possible and we can help people through it though it's definitely still early :)
