### ISSUE TITLE
drupal 7.50 upgrade

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1010]
test heavily my friends

**Comment by mmilutinovic1313** [comment]
Alrighty, so I'm going to test out this upgrade as well. I will document all the issues I see with the update below. Any specific things to look for?

**Comment by bradallenfisher** [comment]
during the database updates you will get a ton of missing module messages and a db multi-byte warning. 

This module is super fast at fixing the errors drush throws when running updb
https://www.drupal.org/project/module_missing_message_fixer

**Comment by btopro** [comment]
I got a theme system function gone message on 7.45 yesterday :|

**Comment by mmilutinovic1313** [comment]
I've been working through the upgrade this evening and tonight and am compiling a list of things to fix. Testing on each system and then I am going to run the upgrade again on another clean vagrant instance to make sure its all working before committing and submitting a PR. I'll keep you all updated.

**Comment by btopro** [comment]
Cool, Make sure you roll the patches in the core PATCHES folder that I have and also need to work towards a solution or allowing Drupal to be displayed in frames which is something hey disabled by default
