### ISSUE TITLE
Hidden nodes enhancement

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1017]
https://www.drupal.org/node/2640002

Simple enough, just provides another place to select this.

**Comment by mmilutinovic1313** [comment]
Do we need this patch added in for documentation?

**Comment by btopro** [comment]
need to actually do it, we have authority over this project

**Comment by mmilutinovic1313** [comment]
I'll do it! lol

**Comment by mmilutinovic1313** [comment]
@btopro I kind of got stuck on this one...I had the button implemented, but couldn't get the hook to fire.

**Comment by btopro** [comment]
Let me know when you can get together in person or maybe @bradallenfisher can help give a second set of eyes to it.

**Comment by mmilutinovic1313** [comment]
Works for me. I'll ping Brad tomorrow and see if he has some insights. I'll send you a message on slack to come up with a time we can meet up next week in general.
