### ISSUE TITLE
Quiz Builder/Tool - Adding Images

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1027]
We are unable to add images directly to the text editor.  Please see the attached file. 
![screen shot 2016-07-13 at 11 02 09 am](https://cloud.githubusercontent.com/assets/12716869/16808179/674b8ab2-48e9-11e6-8d2e-5150ec8039d4.png)

**Comment by btopro** [comment]
Need to set `admin/config/media/imce` for all distros it seems...

**Comment by btopro** [comment]
- [ ] add IMCE configuration to `elmsln_core`
