### ISSUE TITLE
Quiz Builder/Tool - Adding Questions after a Preview

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1029]
After I created a portion of a quiz, I previewed it to see how it would look.  After the preview, I didn't have a path back to a page where I could add questions or edit questions to that same quiz.

**Comment by btopro** [comment]
- [ ] add a dashboard view / view with contextual filter similar to media / interact

**Comment by btopro** [comment]
once we merge i96 in this will be there too
