### ISSUE TITLE
Recommended procedure for setting up PWIK analytics

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#103]
Can @btopro help me fill in the blanks in the setup process. Things surrounded by question marks are what I'm confused about.

1. SSH into VM.
2. Create database username with a database (same name) by running the following:
  1. Create user: `CREATE USER 'analytics_db'@'localhost' IDENTIFIED BY 'password';`
  2. Create DB: ` CREATE DATABASE analytics_db;`
  3. Grant privileges:  `GRANT ALL PRIVILEGES ON analytics_db TO 'analytics_db'@'localhost';`
3. Go to **analytics.[domain]**, click **next**
4. Ignore system check file integrity warnings, click **next**
5. Fill out form with db settings.
  1. **Database Server:** ??localhost??
  2. **User name:** (same name as database)
  3. **Password:** (the one you generated previously)
  4. **Database name:** (same name as username)
  5. **Table Prefix:** piwik_
  6. **Adapter:** PDO\MYSQL

**Comment by btopro** [comment]
this looks reasonable. Unfortunately at this time there isn't a good automated install routine for piwik available or we'd do it in elmsln-install.sh during setup.

keep the DB value at 127.0.0.1 which it defaults to (this is the same as localhost but works better)

**Comment by btopro** [comment]
Please make a wiki page for this since we confirmed this is a reasonable series of steps for setting it up
