### ISSUE TITLE
Quiz Builder/Tool - Editing Questions

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1030]
I just made an edit to a question, and upon saving, the original question still showed up in the question bank.  In this case, it is the question that says "Delete if you can!"  instead of the text I replaced it with.  It also looks like I don't have the function to delete a question on this page, but it looks like that function should be there. 

![screen shot 2016-07-13 at 2 15 13 pm](https://cloud.githubusercontent.com/assets/12716869/16814531/417212d2-4904-11e6-908b-551ce2002698.png)

**Comment by btopro** [comment]
fixed
