### ISSUE TITLE
Idea: Document templating

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1033]
Syllabus, materialize letter, welcome letters, all kind of other documents can be generated by machine to ensure that all the parts that need to be there (legally) are, and all the variable parts are prepopulated / instructors given starting points as much as possible.  For example, a templated document would allow easily filling in the blanks and kicking out an accessible pdf (as one example of something useful).
- allow normal text area edit
- inserting tokens that equate to filling out responses
- button to generate the document at the end

It's possible that this could be something useful for interact since it's a weird document generation thing. It also could probably use something like well styled entity forms / webform or some kind of system where tokens are placed to add variable text / select fields directly into a document and something is produced at the end.

**Comment by rickhumphries** [comment]
Are you thinking of something like the fillPDF module? https://www.drupal.org/project/fillpdf

cause that would be cool. Would also be useful for things like allowing students to fill out online 'workbooks' or review forms where they need to (digitally) sign it at the end and it could automatically submit the document to the instructor

**Comment by btopro** [comment]
Oh now that's a cool module / way of accomplishing that.

well I think the way you are using H5P rick is basically a workbook for students to fill stuff out already :)

**Comment by rickhumphries** [comment]
Ha yeh that's true. I think the key is the 'signing' part really, and being able to populate a pre-existing template with values. Useful (for us at least!) for annoying things like 'paper trails' and working with other colleges who each have uber specific forms that need to be filled in for every student! That kind of thing can suck when you form partnerships with like 6 other colleges as we're starting to do! :)

**Comment by btopro** [comment]
yeah, and we were looking at templatizing the bulk of "Welcome to the course" emails / letters as well as Materials communication and syllabus generation

**Comment by btopro** [comment]
So I think H5P covers what I wanted from this and #1262 is a different issue Rick is still looking for
