### ISSUE TITLE
Idea: Time-based hiding of nodes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1034]
Really like the way you can show/hide nodes at the moment. Thought it would be neat to be able to control the release of some sections of the course outline so that certain lessons only appear between specific dates (and to specific sections). I feel like this idea might have already been noted down somewhere already though so apologies if it has.

**Comment by btopro** [comment]
https://www.drupal.org/project/scheduler has integration with hidden_nodes which provides that capability

**Comment by btopro** [comment]
it's also in the core of the project (available to all sites) but we haven't had time to implement. It is a common request

**Comment by rickhumphries** [comment]
I've turned both the scheduler module and hidden nodes scheduler sub-module on and also enabled scheduler on the container and page content types. I can see the settings to schedule a publish/unpublish, but can't see how to schedule a hide/unhide? Can you point me in the right direction?

**Comment by btopro** [comment]
I believe it'll use unhide state change but I haven't actually used it. Try setting it to hidden and then scheduling to see what happens

**Comment by rickhumphries** [comment]
Yeh so that worked. I set a page to hidden and scheduled it to 'publish' at a certain time, which made it unhidden. That's cool. I can't see the options to do that the other way round. I'm assuming that functionality isn't there yet?

**Comment by btopro** [comment]
I didn't write this just know someone had done so in contrib. Are you referring to published then moved to unpublished?

**Comment by rickhumphries** [comment]
Yeh - so scheduling it to hide at a certain time. At the moment, there's only the option to completely unpublish

**Comment by btopro** [comment]
@mmilutinovic1313 test this; it's in the i96 branch. Rick spells out a bit how to verify this. Enable scheduler module on a mooc course space and then try to schedule a node publishing at a certain time / date and another one unpublishing at a certain date / time. I modified the code block relating to both operations so both need tested even though rick said the original case (publishing) works.

**Comment by rickhumphries** [comment]
Yeh, but just to clarify. It's not publishing/unpublishing that's the problem. It's hiding/unhiding. Or rather it's just a scheduled hiding of a page that can't be done.

So setting a page as hidden (but still published) and then adding a date/time in the scheduler to publish will unhide the page.

However, it's just impossible to do it the other way around because if a page is unhidden and published, the only option is to set a schedule to unpublish. So doing that unpublishes the page, rather than just hiding it (but keeping it published)

**Comment by btopro** [comment]
correct, I just pushed a commit that makes that unimpossible which is what I want mark to test :)

**Comment by rickhumphries** [comment]
:) :)

**Comment by mmilutinovic1313** [comment]
Will do! Thanks for the update guys :)

**Comment by mmilutinovic1313** [comment]
Okay - so I have tested to see if the scheduling / unscheduling works. The updated code block gave me the message that it would both publish and unhide at a certain time, however it did not unhide after that time. I'm going to try this again and run cron again as I know cron triggers scheduler events and it may not have fired properly. 

![hidden_unhidden](https://cloud.githubusercontent.com/assets/7243665/17447551/0b38087c-5b1d-11e6-9593-4ab05b116169.png)

**Comment by mmilutinovic1313** [comment]
Additionally, I got a message when I manually unhid this node: 

`Notice: Undefined index: _class in include() (line 36 of /var/www/elmsln/core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/templates/book-sibling-nav.tpl.php).`

**Comment by mmilutinovic1313** [comment]
New error when I ran cron...`Warning: unlink(/var/www/elmsln/config/private_files/courses/fish100/feeds/lesson-based.xml): Permission denied in drupal_unlink() (line 2284 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/file.inc).`

**Comment by mmilutinovic1313** [comment]
Okay just re-tested this with a cron run and it looks like it is working. Perhaps we could add a GUI for hidden nodes scheduler at some point -- just so that you can customize hiding unhiding separate from scheduling.

**Comment by mmilutinovic1313** [comment]
So this looks good to go -- @btopro & @rickhumphries have you seen these errors before? I can make them their own issues and work on them if they are new ones to tackle.

**Comment by btopro** [comment]
@mmilutinovic1313 I would hope you've used this system long enough to realize these are completely unrelated to the hiding of content and so are bugs :p. the unlink error I don't care about that has to do with local development; if you run leafy and repair permissions that'll fix itself. the `mooc_helper_book_nav` error is probably legit and worth investigating on its own

**Comment by btopro** [comment]
@mmilutinovic1313 make an issue for `mooc_helper_book_nav` error and also make an issue about making a UI for scheduling of publish / unpublish; that one is a much larger issue and Rick was originally asking for it to be possible, not it be super easy to do ;)

Closing out, reference the two new issues off this one when you create them plz
