### ISSUE TITLE
review cachability of all views

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1036]
easy performance gain having this set correctly.

Mark this is higher priority then other past tasks. Find views in different distros and review their usage of caching in views. If they aren't being cached but seem like they could / should be (some data very static, other data incredibly dynamic; most static tho) then start busting out the PRs for feature revisions / update hooks to make it happen

**Comment by mmilutinovic1313** [comment]
Will start churning out the PRs today. Will Devel give me the caching information I need to make the determination if its being cached?

**Comment by btopro** [comment]
if you look in views it has cache output or cache query and lets you select how long for each (don't do authcache at this time if that setting is available). Open a view, hit advanced, it's near the bottom right corner of that list of things. Then figure out what's a good interval to cache (it has like an hour, 6 hours, a day, 6 days). Most likely, 6 days is good for both. Question to ask as to when it's ok to cache that long:
- Did students create it / will need to engage with it? (cache low, like an hour)
- Did staff create it / is it like content in the course itself (a video, a timeline, etc)? (cache high)
- Is it a display people will expect to be updated after they do something (media homepage for example) don't cache or cache very low (like an hour)

**Comment by mmilutinovic1313** [comment]
Studio Choices:

`Assignment bulk edit` = 6 days
`Assignments` = 6 hours
`CIS Section list` = 6 days
`CIS User list` = 6 days
`CLE my submissions` = 30 min
`CLE submission` =  30 min
`Critique - critiques received` = 30 min 
`Critique EVAs` = 30 min 
`Critique feedback given` = 30 min
`flag_bookmarks` = 1 hour
`My Submissions` = 30 min
`OG all user group content` = 1 hour
`OG content` = 1 hour
`OG members` = 6 days
`OG members admin` = 6 days
`OG User groups` = 6 days
`Submissions` = 5 min
`Submissions listing` = 5 min
`flag_bookmarks_tab` = 6 days

(There are also 1 min, 5 min, 30 min options)

**Comment by mmilutinovic1313** [comment]
Innovate Choices: 

`CIS Section list` = 6 days
`CIS User list` =  6 days
`OG all user group content` = 1 hour
`OG content` = 1 hour 
`OG members` = 6 days
`OG members admin` = 6 days
`OG User groups` = 6 days

**Comment by mmilutinovic1313** [comment]
Discuss Choices: 

`Administration: Posts` = 1 hour
`Administration: Threads` = 1 hour
`Category sub-category listing`= 1 hour
`CIS Section list` = 6 days
`CIS User list` = 6 days 
`Discuss My Posts`=
`OG all user group content` = 1 hour
`OG content` = 1 hour
`OG members` = 6 days
`OG members admin` = 6 days
`OG User groups` = 6 days
`Post revisions` = 30 min
`Post: Replies to post` = 5 min
`Thread listing` = 1 hour
`Thread: Administer posts` = 1 hour
`Thread: Posts listing` = 30 min

**Comment by mmilutinovic1313** [comment]
Courses Choices: 

`Book Search and Replace` = 6 days
`CIS Section list` = 6 days
`CIS User list` = 6 days
`Feeds log` = 6 days
`Feeds Node Helper Export` = 6 days
`MOOC book roots` = 6 hours
`OG all user group content` = 1 hour
`OG content` = 1 hour
`OG members` = 6 days
`OG members admin` = 6 days
`OG User groups` = 6 days

**Comment by mmilutinovic1313** [comment]
Blog Choices: 

`CIS Section list` = 6 days 
`CIS User list` = 6 days
`Editorial journal entries` = 1 hour
`editorial my posts` = 30 min
`Editorial story seeds` = 1 hour 
`Editorial Writing Exercises` = 1 hour
`OG all user group content` = 1 hour
`OG content` = 1 hour
`OG members` = 6 days
`OG members admin` = 6 days
`OG User groups` = 6 days

**Comment by mmilutinovic1313** [comment]
These are my recommendations after looking through each of the views present in each distro. @btopro let me know if any of these solutions are dangerously incorrect. If not I am going to then tackle these one distro at a time and fire off the PRs.

**Comment by btopro** [comment]
I removed all the OG ones since they ship w/ OG and we don't use them to my knowledge. Many of the rest of these look reasonable though I removed a few

**Comment by btopro** [comment]
you can export / start submitting these when your ready. Basically when we kick them out if there would be a complaint is when we can disable the caching but many of these are necessary. Start with Media / Interact (still need done) as they have the best chance of being static and getting hit a lot

**Comment by mmilutinovic1313** [comment]
Media Choices: 

`CIS Authority Courses` = 1 day
`CIS Section list = 1 day
 `CIS User list = 1 day`
`ELMS Media overview` = 1 hour
`Node results` = 1 hour
`User results` = 1 hour

**Comment by mmilutinovic1313** [comment]
`CIS Authority Courses` = 1 day
`CIS Section list` = 1 day
`CIS User list` = 1 day
`icor object lists` = 1 day
`ICOR Player EVA` = 30 min
`Timeline` = 30 min
`Timeline Content type` = 30 min

**Comment by mmilutinovic1313** [comment]
Media and Interact intervals have been added! I think they should be good, so I'll push those out first as you had mentioned!

**Comment by mmilutinovic1313** [comment]
#1055

**Comment by mmilutinovic1313** [comment]
Lot's of PRs submitted. This should be good to go after they get merged in!

**Comment by mmilutinovic1313** [comment]
Comply Choices:

- [ ] Audit = 6 days
- [ ] CIS Authority Courses = 1 day
- [ ] Compliance Overview = 6 days
- [ ] ECD Bulk Update = 6 days
- [ ] ECD Documentation = 6 days
- [ ] ECD Systems = 6 days
- [ ] EVA Systems = 6 days
- [ ] User Entity Forms = 6 days

**Comment by mmilutinovic1313** [comment]
This can be closed once the rest of the PRs go through! 😃
