### ISSUE TITLE
CIS 2.x UX

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#104]
menu items need to be in the left hand slide out as well as displays largely gutted from the original as we've simplified the scope drastically.

**Comment by michael-collins** [comment]
@btopro We probably shouldn't have menu items off screen. This type of thing makes sense when needing screen real estate for reading large amount of text, etc. If you look at the page.tpl for the Elmsmedia Foundation Access theme, you can see some code for a left sidebar menu. If you'd like to use that in the short time, that would make the most sense I think.

**Comment by btopro** [comment]
It'll be menu links in a block so they can be gotten to, you can clean up from there, need to at least make it functional

**Comment by btopro** [comment]
menu items in place, need to bundle in such a way that settings for them don't need an FR. As we're largely deemphasizing this system it certainly helps as the focus will be squarely on creating and then going elsewhere to build the course :)
- [ ] refactor menu items as they are exported currently
- [ ] dump "person" connotation
- [ ] clean up fields for all types
- [ ] logintoboggan on by default
- [ ] utilize the menu alter hook to mark certain tools as dev / alpha / beta. when they are rendered to the screen in the slide out menu (Courses/MOOC and CIS/online are only ones to NOT get these markers)
- [ ] verify network is building correctly and call er a 0.1.0 :)

**Comment by btopro** [comment]
Fedora project has a known outage making this difficult to test the networking capabilities because mcrypt won't build :)

**Comment by btopro** [comment]
Menu needs Courses list view / menu link. Refactoring them to be exported correctly is slightly pointless given that this is a temporary UX placement til @michael-collins can get a full review of it and all the interfaces. This is currently to a state where the 2.x application of the interface makes things usable; still need to test some more though. Data model of the core things that matter in CIS is the same (Course -> offering -> section, as well as services, resources and serivce_instances).

News, Person, and "College service" have been dropped, tons of views refactored, contexts gutted and permissions re-exported. If network is working soon we can try it out in vagrant and see but it's looking very promising.

**Comment by btopro** [comment]
@michael-collins please pull the latest of the repo and spin it up via vagrant and review what's currently there. We're still obviously working through workflow, interfaces, some positioning of things, etc. But from my perspective at least this is stable enough for a 0.1.0. release as per https://github.com/elmsln/elmsln/wiki/Project-Release-Cycle

Please review that wiki article as well. I'm going to create a new issue and will assign it to you
