### ISSUE TITLE
drop visual listing in CIS

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1049]
there's a view that has a 'visual' listing. this doesn't need to exist anymore.

Delete it from the view, reexport the view, make an update hook that reverts the view

**Comment by mmilutinovic1313** [comment]
I removed the visual listing itself. Writing the update hook now.

**Comment by mmilutinovic1313** [comment]
I removed the visual listing section from the view but this still shows up in the exported code: `$handler->display->display_options['menu']['title'] = 'Visual listing’;`. Would I unset that variable in the update hook / delete that line from the views export?

**Comment by btopro** [comment]
hmm... maybe it's in the master display then overriden in the non-visual one?

**Comment by mmilutinovic1313** [comment]
Okay cool - I'll see if I can find what else is setting that then!

**Comment by mmilutinovic1313** [comment]
Turns out that Drupal keeps the output you had in a menu even if you disable the menu. Removed those text fields and that seemed to take care of it. Submitting the PR now!

**Comment by mmilutinovic1313** [comment]
I believe my update hook should just focus on the views component. Let me know if you think it looks off.

**Comment by mmilutinovic1313** [comment]
Additionally, I noticed that `Visual Listing` is still present when you go to `Menus` in Drupal. Shall I delete the link from there as well?

**Comment by mmilutinovic1313** [comment]
Comment on PR: Syntax error on how I structured update hook. Need it to match this form. Forgot sandbox component. Will change this after submitting 1st #1036 PR

`/**
 * Implements hook_update_N().
 */
function cis_section_update_7001(&$sandbox) {
  features_revert(array('cis_section' => array('views')));
}

**Comment by mmilutinovic1313** [comment]
This should also be good pending merge
