### ISSUE TITLE
are we ready to call things 0.1.0

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#105]
- [x] review https://github.com/elmsln/elmsln/wiki/Project-Release-Cycle
- [x] review current state of the system via vagrant
- [x] create a basic demo / examples section on elmsln.org that either has links to demos of it running in the wild (like drupal.psu.edu/library) or screenshots from our own instances, or both. Increasingly I think it's important to show what it can be as well as what it is by default.

Please provide feedback that you would consider blockers for calling something a release, knowing we are still refining the interface, working on the other systems in the network, and cleaning up the UX across the board.  We've been running variously time-stamps of this system for some time and I feel we need to get onto a version'ed approach in order to better have conversations in queues and raise visibility / sanity of those instances.

After a release marker, we would upgrade all PSU instances to use that code base (ok well elijenkins would). Then we could proceed forward in a more logical manner and start to chart out a roadmap of what are blockers for additional releases in the release schedule.

**Comment by btopro** [comment]
@michael-collins Cough. see checklist above.

**Comment by michael-collins** [comment]
Blocker #1. There needs to be a left sidebar and right sidebar region. These sidebars are incredibly useful for basic flexibility in layouts. I would use these regions to temporarily hold the CIS tools instead of off canvas.

**Comment by btopro** [comment]
issue mentioned above is resolved.
The three issues above at least are starting to be addressed. More importantly, the youtube video I shot showing the state of the system has minimal hiccups and was completely off the cuff w/ no planning ahead of time. In the 40+ minutes of random walking the system there are only 2 notices present which have been squashed already and 1/2 page not founds on systems that are way down in the roadmap.

What I think we need is a formalized roadmap that starts to try and align release versions to what we'd expect to see in the roadmap. This has been asked for by vendors and will go a long way as people start to play with whats going on here. I'll close this for now, we're not ready to yell 0.1.0 as I'd like to polish up the MOOC page navigation UX still. We are starting to get to the point that I just want something perfect and that's not the expectation w/ a sub-1 release :).

Plan for now, wait till the staffing enhancements are announced. Get together and agree upon what a release would mean after we have the PGH sprints.
