### ISSUE TITLE
CIS Webcomponent dashboard pager

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1051]
Right now the dashboard executes a call for getting all the courses and all the sections at once. This works fine when in development but when in a production instance this will quickly blow up / overflow since it's Courses X offerings X sections as a single entity load / pull. For example, in my production box this doesn't complete as it would be about 60 courses x 50 offerings x 250(ish) sections.

Recommended actions
- [ ] display nothing by default or just the 1st course (sort by newest created)
- [ ] make a drop down to select the course in question (with Chosen JS filter applied so it can search within options)
- [ ] ajax call for new data / refresh the json source in the display
- [ ] make a pager for results
- [ ] make a filter for active vs. inactive sections (default to active only)
- [ ] make filters for year, semester, etc, anything that would make it easier to target what you are looking for.
- [ ] when displaying active and inactive sections we should group / order them active then inactive
  In the end, I should be able to answer "What courses are running this semester" and work on all of them as well as "How long has that 1 course been running" and see a more historical / all the sections (active and inactive) of just 1 course.

**Comment by btopro** [comment]
current name of the project supplying this is cis_dashboard
core/dslmcode/profiles/cis-7.x-2.x/modules/custom/cis_dashboard/

**Comment by rickhumphries** [comment]
Not sure if this is the right place to put this or not, but came across this open source angular dashboard template which seems cool:

https://akveo.github.io/blur-admin/

**Comment by btopro** [comment]
#1663 UI being built there is related to this one and will have a lot of pieces of it baked in probably

**Comment by btopro** [comment]
#1464 replaces the need for this. Burn a slow death angular based method of achieving this previously.
