### ISSUE TITLE
Implement puzzler once bug fixed

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1053]
https://www.drupal.org/project/puzzler

Sounds like #326 with the source we'd actually want which is wikipedia.

**Comment by btopro** [comment]
REALLY cool. #326

**Comment by btopro** [comment]
https://www.drupal.org/node/2770743

**Comment by mmilutinovic1313** [comment]
What is the status on this issue being fixed. I saw on d.o. it says that it is "works as intended"

**Comment by btopro** [comment]
@mmilutinovic1313 implement on a new copy of master and see if the notice shows up; I think the latest scrollspy work axed this

**Comment by mmilutinovic1313** [comment]
Need a win today - gonna rebuild vagrant with a new master copy to check

**Comment by mmilutinovic1313** [comment]
WOW! This module is amazing! I tried it out on master and the error message is gone. Used the dev version as you said. Putting in a PR now

**Comment by btopro** [comment]
Not enabled by default but this is a really good utility in the tool belt.
