### ISSUE TITLE
`CIS User List` Views Export Feature Missing

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1055]
The folder containing files for `CIS User List` are missing. This would impact issue #1036 as the view for `CIS User List` exists on the file system. But there has never been an export of this feature or the feature is missing.

**Comment by btopro** [comment]
Oh, like it's going to delete files? that's good

**Comment by mmilutinovic1313** [comment]
#1054 I believe it's more that the files never existed

**Comment by mmilutinovic1313** [comment]
This is good to be closed
