### ISSUE TITLE
xAPI tag for hypothesis for questions

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1056]
if the shortocode could add in hypothesis tags / tagging of the data being inserted we could flavor / provide different displays off the same questions.

**Comment by btopro** [comment]
next we need to allow for data-xapi-hypothesis to be set on the iframe. Maybe if our shortcodes can turn any data-*whatever* into an attribute on the item

**Comment by btopro** [comment]
!

**Comment by btopro** [comment]
now if we add `hypothesis=Things and stuff` to a shortcode that's going to render an iframe that has an h5p behind it we'll be able to pass along this item. Why this matters is that you could have 2 versions of a course being delivered to two different audiences. Audience 1 you have a different content outline for and have the hypothesis of `less video` or whatever, asking questions that have less video then group 2.

Similarly, this allows for mixing questions based on context. So you could be placing items in a course that are intentionally after videos that you think might be too long. You could ask the same question after every video but then have the hypothesis tag of `too long` after those you think might be. At the end, the data is all the same but you've just added a different dimension to it. So now you can go "well generally students think our videos are an appropriate length,.... but see how the average stacks up against these 3 we've drawn attention to in our data set"

@kat-wehr @kmiffitt @rickhumphries --^

**Comment by rickhumphries** [comment]
!!!

**Comment by btopro** [comment]
https://www.elmsln.org/blog/post/xapi-hypothesis-context-value
