### ISSUE TITLE
Lay out vision for each distribution and future ones not started yet

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1064]
What it should be

What it has

What it needs

Where it could go

**Comment by rickhumphries** [comment]
@btopro I just did something for the docs about the Media system. Can you check to see whether I've done that right, and whether it's the kind of thing you're after

**Comment by btopro** [comment]
Looks good and almost there on the commit. To get it into the project you need to do a pull request. Your change is to a repo you have that's  fork of the real one. Next step is hit pull request and pick the downstream as your fork on the master branch. Then it should say if it can be merged and if i can it'll kick a notice to me to check it out. If it looks right I hit accept, you get credit and the docs site will update itself shortly after that :)

**Comment by rickhumphries** [comment]
@btopro right - I get it now, cheers
