### ISSUE TITLE
Add additional info to leafy

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#107]
As we move towards a versioning system we should add a VERSION / obvious file to the project root which can then be tagged as part of releases. Leafy can then read this and report back on it when called upon.

We might want to do multiple versions in the version number or an extended version info thing to gain data about all the tools included or maybe just saying what tools are in which state of development.

**Comment by btopro** [comment]
@michael-collins thoughts on what would be useful to gain feedback wise from your instance w/ a command? Leafy comes installed OOTB now / after upgrading your instance to clear up that issue since yours doesn't have it yet (til I do it tonight).

**Comment by michael-collins** [comment]
Mostly just stats.

* total number of courses
* total sections in system
* total sections currently running
* active authority systems
* total number of students, instructors, admins, etc
* what's wrong? - leafy would tell me if the server isn't feeling well. IE - maxed processor, outta ram, hd full, something isn't running, etc.

**Comment by michael-collins** [comment]
Also, I want leafy to tell me if I can do something new. Like... We add major functionality (interact actually works now), and leafy tells me about my new super power. Maybe just authority systems that have never been created, not sure.

**Comment by btopro** [comment]
Ooo good request. I wrote https://www.drupal.org/project/drush_efq just for this kinda stuff :)

The "whats wrong" could maybe more so be a series of good heads up data.. @bradallenfisher do you know a good couple lines to see things like that on a server that could give you basic "health" info?

Last thing not sure *how* specific we could get but we could load something into CHANGELOG or something that could be read off I guess for stuff like that. I know what your saying though, this is kind of part of why I want to load in a bunch of semi-functioning systems so people see where it's going and the "super powers" turn on as we go instead of having to account for adding things after the fact outright :)

**Comment by btopro** [comment]
![2015-06-16_15-40-45](https://cloud.githubusercontent.com/assets/329735/8192706/1225978e-143e-11e5-932c-91df267cb945.png)

**Comment by btopro** [comment]
- [ ] ELMSLN Version
- [ ] total number of courses
- [ ] total sections in system
- [ ] total sections currently running
- [ ] active authority systems
- [ ] total number of students, instructors, admins, etc
- [ ] what's wrong? - leafy would tell me if the server isn't feeling well. IE - maxed processor, outta ram, hd full, something isn't running, etc.

**Comment by btopro** [comment]
"active" might be difficult to obtain, would have to think of the best way of keeping this info.

active authorities running,.... maybe just a list of the services and authorities that the system has?

totals of students, etc, will probably have to come from a cron job (atm) since the authorities (by previous design) don't have all the accounts in them.

"what's wrong" still need some details from @bradallenfisher as to how we could do that really. Maybe some kind of option that's like "yikes refresh!" that restarts apache / mysql and rebuilds permissions / user account's ability to do on system tasks? like a master uber bandaid @michael-collins
