### ISSUE TITLE
Content Layout Ideas to Blueprint/Template 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1074]
Just a couple examples and ideas for how they can be pieced together for education purposes. 

https://www.thinkwithgoogle.com/articles/digital-marketing-rethink-measurement-mobile-first-world.html
What is nice about this: Image thumbnails on the sidebar - would be cool for each lesson/page to have an associated image whose thumbnail follows it throughout the course (ie, table of contents, "What's Next" scroll spy on the sidebar, etc.) 
Header image w/ styled text, floats into a thin header that stays at the top when scrolling - would be cool to have a space for this that functions this way along with a set of textured background images that can be used as "defaults" unless users have their own (reminds me of Divi)

http://www.newyorker.com/
"The Latest" - really like this layout for a dashboard/landing page - courses with most recent updates, upcoming assignments due, discussion boards with recent posts, etc. 
*Dashboard should have the ability to sort most recent updates by course/date etc. 

http://www.newyorker.com/business/currency/can-an-addiction-memoir-help-us-understand-wall-street?intcid=mod-latest
I like the two column layout they've got going on here. This would be good for instances where larger previews of upcoming/related content are needed - example: assignments/discussion prompts previews in the content w/ button that allows students to "go to discussion"/"View more details" etc.

**Comment by btopro** [comment]
merging into #206
