### ISSUE TITLE
Materialize library not loading in Libraries API (master)

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1075]
**Version**
0.3.1x

**Steps to reproduce the bug**
1. Load online.elmsln.local
2. Go to libraries administration menu
3. Look for Materialize

**Expected behaviour**
Materialize should be visible in this menu. 

**Actual behaviour**
Libraries API states that Materialize cannot be found. I assume it is being loaded via CDN. 

**Additional information**
Materialize still appears to be working, but this could be screwing up some of the CSS in CIS-Dashboard.

**Comment by btopro** [comment]
good catch and description
