### ISSUE TITLE
Dialogue Journal 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1076]
Dialogue Journaling Tool - Reflective space for students and instructors. Students leave reflections, instructors can respond with their own reflections, feedback, comments, etc. 

This should be a super simple interface, sort of like an iMessage conversation or forum thread between two people - just text blurbs that float left/right depending on whether it's the student or instructor's note, just text and basic formatting, nothing crazy fancy. 

More notes: Should be a space that's about the process of reflection and the words on the screen, nothing else. Just the content editor on the bottom and reflections on the top. 

Should be private between each student and the instructor. Reflections/writings for wider audiences should be held in blogs. 

Background for anyone interested in the theory: http://rse.sagepub.com/content/19/1/32.abstract
https://en.wikipedia.org/wiki/Dialogue_journal

**Comment by btopro** [comment]
#1133 might be able to get rolled into this (in part) from discussions we've been having

**Comment by kat-wehr** [comment]
Hooray! That would be awesome. @heyMP's nifty little in-line commenting feature would be an awesome addition to this too.

**Comment by btopro** [comment]
#322
