### ISSUE TITLE
Firefox/H5P Display adds extra whitespace 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1079]
Too much whitespace beneath H5P displays - firefox not calculating correctly?

Example: 
<img width="939" alt="screen shot 2016-07-31 at 9 36 12 am" src="https://cloud.githubusercontent.com/assets/15616523/17276892/b00d2c1a-5703-11e6-9059-c818d8c6830e.png">

**Comment by btopro** [comment]
This has to do with the iframe claiming it isn't a trusted event. we'll need to account for doing a sub-domain preg match, yuck.
