### ISSUE TITLE
Quick User View

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1081]
![image](https://cloud.githubusercontent.com/assets/4973810/17276968/65aab99a-572f-11e6-80af-107740409936.png)

Build on the current masquerade flyout to enable an additional 'view user' action button which links to that users profile.

Also change 'Go' to 'Emulate' for the masquerade action.

May also want a 'back' arrow button here to return to the previous user settings, rather than having to close the flyout then click the user icon again (possibly a separate issue?)

Also change this:

![image](https://cloud.githubusercontent.com/assets/4973810/17276982/bba83d0e-572f-11e6-80b1-483dcc2fa743.png)

To say something else if we're applying more actions?

**Comment by btopro** [comment]
good idea @rickhumphries . View button in there now. To use it'll be a user name auto completed and then clicking the button
![2016-08-04_15-22-15](https://cloud.githubusercontent.com/assets/329735/17415300/427ae2c6-5a57-11e6-8c76-b525bab8c79f.png)
