### ISSUE TITLE
Add Media Button To Media Site

### ISSUE THREAD

**Issue by grshane** [elmsln/elmsln#1084]
**Version**
Found in 0.3.1  commit 42d4255722d59535995250ff64e8fe8e99f451a6
or at admin/status/report of media site in elmsln}} 

**Steps to reproduce the bug**
1. Navigate to media.elmsln.local
2. Look for media button

**Expected behaviour**
Add media button should be visible because adding media is important.

**Actual behaviour**
Add media button is nowhere to be found.

**Additional information**
OS: OSX 10.11.5
Browser: Chrome 51.0.2704.103 (64-bit)

<img width="1430" alt="screen shot 2016-07-31 at 11 00 40 am" src="https://cloud.githubusercontent.com/assets/1178060/17277314/13911af8-570e-11e6-9058-1c006ef0714f.png">

**Comment by btopro** [comment]
we need to revert this function or figure out wtf is wrong with it not forcibly reverting

**Comment by btopro** [comment]
going to have to spin up a fresh instance and see if this happens; it's so frigging annoying and so frequently all I have to do to resolve is revert the feature but we want perfect, damnit! :)

**Comment by btopro** [comment]
Appears to I finally got the features correct for doing this. stupid features + menu links
