### ISSUE TITLE
Clipboard.js namespace collision

### ISSUE THREAD

**Issue by grshane** [elmsln/elmsln#1085]
Version
Found in 0.3.1 commit 42d4255
or at admin/status/report of media site in elmsln}}

**Steps to reproduce the bug**
1. View Options > Image 
2. Click copy clipboard button

**Expected behaviour**
Tooltip should read "copy token" because it is copying the token.

**Actual behaviour**
Tooltip is displaying empty.

Additional information
OS: OSX 10.11.5
Browser: Chrome 51.0.2704.103 (64-bit)

<img width="719" alt="screen shot 2016-07-31 at 11 19 20 am" src="https://cloud.githubusercontent.com/assets/1178060/17277441/acaa5e64-5710-11e6-99ce-f5cb590ef90c.png">

**Comment by btopro** [comment]
What a stupid issue lol. thanks for reporting, just noticed this tonight and wow is it annoying.

**Comment by btopro** [comment]
This would help w/ usability in Media system as to what this icon means

**Comment by btopro** [comment]
last PR just fixed this. thx @heyMP

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/pull/1272
