### ISSUE TITLE
Bulleted Lists - New System

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1092]
The ability to make a bulleted list is no longer available for courses in the new system.  The list of "Safety Precautions" on the attached page used to be a bulleted list, but now it is not.  I also checked a few pages in ArtH111, and the bulleted lists are gone in that course as well. 

![screen shot 2016-08-02 at 3 29 12 pm](https://cloud.githubusercontent.com/assets/12716869/17342265/667ea014-58c6-11e6-8c99-1c4d9c812f61.png)

**Comment by btopro** [comment]
![2016-08-03_16-24-59](https://cloud.githubusercontent.com/assets/329735/17381041/0bd33fee-5998-11e6-82ab-429ccf6a30fa.png)

feedback on the cross-fade. I've fixed the bullets in some local work but would like to make some other options that are appealing looking beyond just traditional black circles.

**Comment by btopro** [comment]
fixed in i96 which needs tested more heavily after the media player makes its way in
