### ISSUE TITLE
OG confusion when adding user groups manually

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1093]
**Version**
0.3.1 

**Steps to reproduce the bug**
- Enable Access Denied Backtrace https://www.drupal.org/project/adb
- Create Assignment on studio
- log in as student
- visit the created assignment as student
- you should should see the following error.

```
Notice: Trying to get property of non-object in cle_submission_node_access() (line 92 of /var/www/elmsln/core/dslmcode/profiles/cle-7.x-1.x/modules/features/cle_submission/cle_submission.module).
Notice: Trying to get property of non-object in node_node_access() (line 3091 of /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/node/node.module).
Notice: Trying to get property of non-object in og_node_access() (line 491 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/og/og.module).
```

![screen shot 2016-08-02 at 4 06 55 pm](https://cloud.githubusercontent.com/assets/3428964/17344067/d1a65b40-58ce-11e6-94d6-4ebd050da790.png)

**Comment by heyMP** [comment]
Not sure if this is just on my setup or not. I have a feeling it revolves the section.

**Comment by mmilutinovic1313** [comment]
Testing this in vagrant to see if this is happening on more than just your install

**Comment by mmilutinovic1313** [comment]
I tested this in vagrant and the student was able to view the assignment by going to the `node/2`assignment page. However, the assignment did not display in the assignments page for the student. I'm wondering what permissions need to be set to see that page? 

Was your assignment public or private?

**Comment by btopro** [comment]
assignment needs associated with organic groups, then student needs to be in same group, not saying this resolves it just hunting down this rabbit hole a bit

**Comment by btopro** [comment]
unrelated; adb module sounds awesome and maybe we wnat to throw it in the stack

Also check on the status page about rebuilding node access permissions (also just do it anyway and see if the number of records changes.

**Comment by btopro** [comment]
well this was a pain in the butt to figure out but basically there was an issue with OG and setting someone's group access as an admin doing it brute force like we were in testing. https://www.drupal.org/node/2778559#comment-11472453
