### ISSUE TITLE
Book Copy Breaks Internal Links

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1094]
We recently had an instructor who was creating a lot of internal links which led to a major issue when we copied his book.  Stating the obvious but, once a book is copied, the internal links of the new book point to the old outline.  This isn't typically a problem since we have optionally two outline navigations on the page at any one time so it wasn't an issue that I considered.

Two things that I'm considering:
1.  Can the internal links be corrected by an automated procedure?
2.  How can we prevent this in the future?

**Comment by btopro** [comment]
#849 this is a duplicate. Kind of ironic, a duplicate detailing an issue with duplication.

**Comment by btopro** [comment]
we need to create a b-tree map kinda thing where we know all the nid's to copy, and keep a big ol' array of what it became after the copy. Then last minute after creation of the new outline, we need to do a preg replace of all `node/6` style things to `node/106`, etc. Closing as that node has this similar thread
