### ISSUE TITLE
Feature Request - Make UI for Hidden Node Scheduler

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1098]
We should have a UI for hidden node scheduler so that faculty and admins can select to hide and unhide their content during certain times of the semester without depending on the publish / unpublish functionality of the scheduler module as mentioned in #1034. This may take some time, but will be an excellent and useful contribution to the module.

**Comment by btopro** [comment]
outline designer rebuild as an angular app would help make this more visible.

**Comment by mmilutinovic1313** [comment]
^ Assuming this will become a WebComponent?

**Comment by btopro** [comment]
umm.. i mean it's a page that could be in stand alone drupal page
