### ISSUE TITLE
Error when running system setup from CIS

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#110]
Notice: Undefined index: instance in cis_helper_entity_update() (line 467 of /var/www/elmsln/core/dslmcode/profiles/cis-7.x-2.x/modules/custom/cis_helper/cis_helper.module).

Some content nodes were created, but no services were set up.

**Comment by btopro** [comment]
fixed; seems that the notice was preventing it from writing a job to the server; I have chem202 (which discovered this) building now. also cleaned up the creation form (a lot) so no longer require much to build stuff. updated language as well to start to make more sense w/ networks

**Comment by btopro** [comment]
#vacationcommits

**Comment by michael-collins** [comment]
@btopro Excellent vacation commits.

**Comment by michael-collins** [comment]
FYI - that build produces an access denied. Throws this error: Warning: call_user_func_array() expects parameter 1 to be a valid callback, function '_webaccess_call' not found or invalid function name in menu_execute_active_handler() (line 517 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/menu.inc).

**Comment by btopro** [comment]
nope, it worked; user error.
