### ISSUE TITLE
enable modernizr out of the box for elmsmedia

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1103]

**Comment by mmilutinovic1313** [comment]
Went to play around with `modernizr` before writing the update hook to add it to `elmsmedia`. When I enabled it I got this message basically disabling a bunch of our custom `elmsmedia` modules. Is this intended? Just double checking before I make the PR with the update hook. 

![ablemodule](https://cloud.githubusercontent.com/assets/7243665/17541672/a8324d52-5e8f-11e6-9219-d71b77083ca7.png)

**Comment by btopro** [comment]
Note the branch this is on

**Comment by mmilutinovic1313** [comment]
This is from the 0.4x branch

**Comment by mmilutinovic1313** [comment]
This is the 0.4x branch
