### ISSUE TITLE
Parallax Scrolling

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1104]
We're interested in applying some parallax scrolling effects to some of the course content we're making to make it come to life a bit more. Seen some pretty cool examples:
http://www.dementialab.org/discovery-lab/
http://benthebodyguard.com/index.php#home 

Noticed there was a parallax Drupal module that may come in useful https://www.drupal.org/project/parallax_bg

Wondered if this is anything other people might be interested in? And thoughts on the best ways to implement it if so?

**Comment by btopro** [comment]
hmm... never been sure of the best way to construct or store these. Often times these are just ripped straight into the theme layer which is problematic for a system type implementation. I guess it depends on how you'd want to implement but I'd almost think you'd make a stand alone parallax, upload it to interact (for weird stuff like this) as a zip file, it gets unpacked, then you embed it in a page or do an embedded modal pop up or something. These aren't easy to make regardless of how it's implemented :)

**Comment by heyMP** [comment]
There is a Parallax component in Materialize. We could potentially create a new view mode for the image content type within the media system. That would be easiest. 

If you wanted the ability to define more advanced settings then we would have to move it into its own content type like Bryan was saying. 

http://materializecss.com/parallax.html

**Comment by rickhumphries** [comment]
I like the idea of having a view mode available in Media. For the more advanced stuff yeh a modal or something would work after uploading to interact. Definitely not easy to implement but we have a guy who wants to give it a go!

**Comment by btopro** [comment]
@rickhumphries awesome! Maybe shoot for the display mode approach 1st and then the crazier stuff as a later issue. We could easily slot implementing Materialize Paralax into the roadmap here and then make another issue for those crazy demo type things you showed :)

**Comment by btopro** [comment]
tagging as 0.4.x because I'm already doing a lot of work with display modes and enhancements to the media system to get us onto #96

**Comment by btopro** [comment]
Ooo @heyMP what do you think of the idea of the banner image uploaded per unit of content / etc do the parallax thing?

**Comment by btopro** [comment]
alright, lets split this off into 2 other issues because we've got parallax support (easy form) out of the box and it auto applies to header images if they exist. The other two issues will be for the slightly more complicated and extremely complicated use-cases of image styling / presentation / view mode and then the stand alone amazing 1-page-app upload and it presents in a modal type of thing.
