### ISSUE TITLE
Discussion distribution

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#111]
Really cool discussion system... 100% open source. Perhaps this becomes the discuss distro? http://www.discourse.org/

**Comment by btopro** [comment]
while I agree in principle (it is cool) I've reviewed it before and wasn't impressed w/ the flexibility. As a "this is exactly the way to have a conversation" / traditional forum system, yes. It is very cool for that. As anything else or needing to modify it beyond where it is currently I wasn't excited.

Won't rule it out entirely but it doesn't have nearly the plugin support that drupal / wordpress have.
