### ISSUE TITLE
Students should not be allowed to submit assignments passed their due dates.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1113]

**Comment by michael-collins** [comment]
Disagree. It should be flagged as late, and graded accordingly if late submissions are accepted. Should be a configurable option.

**Comment by btopro** [comment]
I agree with @michael-collins , student can't be expected to abide by deadlines.

**Comment by btopro** [comment]
In fact, when a late submission is accepted, it should automatically email the instructor saying "Howdee doo -

You thought you were done grading those submissions. Have fun doing more work on a weekend because I chose not to.

Best regards"

**Comment by michael-collins** [comment]
Not really sure why @btopro is snarking out right now. It's a fairly common and legitimate way to run a course.

**Comment by btopro** [comment]
common yes... in residence. Almost none of our faculty do this who teach online.

**Comment by michael-collins** [comment]
Even Lore had this feature. Super useful.

**Comment by heyMP** [comment]
Makes sense as a configurable option on the assignment.
