### ISSUE TITLE
Instructors aren't able to critique assignments that are marked "no-critique"

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1115]
Instructors should be able to always submit critiques.

**Comment by btopro** [comment]
at some level I want to say Duh cause.... there's no critique... ;)

**Comment by heyMP** [comment]
lol... Well I guess this might be a configuration problem.  Would you be able to achieve that setup if you allowed critiques but made the submission private?

**Comment by michael-collins** [comment]
There might be a small difference between feedback and critique. Critiques are typically more formal, but in a classroom, you can give feedback at any point on someones work to help guide their choices or make improvements. It does sound appealing to be able to make comments on all the work students submit, whether part of a crit or not.

**Comment by michael-collins** [comment]
Perhaps that would happen in feedback on grading? The only downside there is guest lecturers or invited faculty/industry pros would not be able to comment on inprogress work.

**Comment by btopro** [comment]
Currently there's commenting and critiques. Comments are always there. Critiques are a more formal process so students know they are engaging in a critique. It's also so we can deliver someone a random thing to critique and in the case of blind or double-blind have more "open" feedback without fear of associations to the person saying it.

**Comment by btopro** [comment]
Maybe if we have something like a critique button and another that's Comment. Then if both buttons are there and the critique button is greyed out when there's no ability to critique that might help. Also an option to give private feedback by the instructor.

**Comment by michael-collins** [comment]
That sounds good. Conversation should be as fluid as possible without losing the structure. FutureLearn's discussion is totally unstructured, and I don't know that it's all the useful as a result.

**Comment by btopro** [comment]
exactly; I think this would be a really good student design project. Forums / FLearn / "Discussion boards" are ocmpletely worthless once more then 4 people use them bc of the threading

**Comment by heyMP** [comment]
Yeah, the ultimate goal for Critiques in my mind would be to choose between a few different critique methods, like inline critiquing, video response, screen capture, etc.

Then the instructor could make the decision between doing a formal critique or sending them a message.
