### ISSUE TITLE
Support one-page-app type parallax scrollers

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1120]
This would have to go into the interact system and most likely be an upload that unpacks it's assets. This is a continuation of the discussion started about parallax in #1104 and is the far more complicated use-case. First we need a working example of a stand alone (as a zip), then we can start getting into the details of unpacking the interaction into the interact system.

**Comment by btopro** [comment]
@mmilutinovic1313 actionable goal:
- [x] unzip stuff (interact does this already, hit add and do zip upload)
- [ ] look for a index.html/htm
- [ ] load an iframe pointing to this file

This will effectively support this while allowing us to do other things in the future (like just upload files and have them be unpacked so people can pull in older content / widgety stuff)

**Comment by mmilutinovic1313** [comment]
Looking into this

**Comment by mmilutinovic1313** [comment]
Okay so throwing out some logic stuff here -- 

1. Upload file works. 
2. Then we need to have logic to say what was in this zipped file. Basically search for file ending called index.html / index.htm 
3. If not found do nothing
4. If found load this html file somewhere (in an iframe)

Questions: How do we know where the iframe will load? Is it its own content type? Is it related to the upload itself (i.e. unpacking the zip creates a new iframe node?)

**Comment by btopro** [comment]
#1591 and yes that's what needs figured out; the question u have :)

**Comment by btopro** [comment]
This is actually the same thing as #1591 bc it'll be solved the same way. Closing this as duplicate of that since your last comment and the actions of 1591 are the same thing :)

Focus on this @mmilutinovic1313
