### ISSUE TITLE
Need snarky/cute/fun access denied messages.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1126]
It would be cool to have a standard access denied page with a custom message.
- [x] Design access denied page
- [x] Design 404 page
- [x] Implement design in foundation access.

**Comment by heyMP** [comment]
For example, this is what we have now to let students know that there are no assignments to critique in the studio:

![screen shot 2016-08-10 at 10 40 03 am](https://cloud.githubusercontent.com/assets/3428964/17558218/dd832000-5ee7-11e6-9838-0c70a4389770.png)


It would add gravitas if it were something like this

![screen shot 2016-08-10 at 10 46 41 am](https://cloud.githubusercontent.com/assets/3428964/17558234/eed8ecf4-5ee7-11e6-9d43-bcc76d7a3335.png)

**Comment by btopro** [comment]
Also 404 pages. Everyone needs an amazing 404 page if they are to have a successful community project.

**Comment by michael-collins** [comment]
Okay, I'll see what I can do.

**Comment by btopro** [comment]
@grshane fun one hanging out here if interested. at least way more fun then front end stack untangling ;)

**Comment by grshane** [comment]
Something like this?
<img width="515" alt="screen shot 2016-08-16 at 12 34 17 pm" src="https://cloud.githubusercontent.com/assets/1178060/17707304/cac0ba0c-63ad-11e6-9da2-2311436ab288.png">

**Comment by sugaroverflow** [comment]
Just wanted to say I love this issue

**Comment by btopro** [comment]
@michael-collins did you ever get anywhere with these while we were in VA?

**Comment by michael-collins** [comment]
Nope. In fact, you should just write "Nope." on the access denied screen.

Here is a mockup:

# Nope.

**Comment by btopro** [comment]
... i enjoyed your animation more

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=Ss5AVHZHBzA

**Comment by btopro** [comment]
![2016-11-26_16-42-12](https://cloud.githubusercontent.com/assets/329735/20644082/4bb68c42-b3f7-11e6-8ffa-94bb8f435c09.png)
Hal 9000 now appears on error pages and speaks in a slower, deeper voice then the normal voice over

**Comment by btopro** [comment]
- [ ] add support for custom voice commands to talk back
- [ ] use lines from 2001: A Space Oddesey

**Comment by btopro** [comment]
:) all your base are belong to us
