### ISSUE TITLE
List Indents - CIS 

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#113]
Hoping @michael-collins might be able to help me with this one :) It's just a slight styling issue I've been having when setting up my pages. I'm on CIS 1.x so still Foundation 4.

I can't seem to find the right CSS to remove the text-indent that's applied to list tags within the body field of a page. As I use Foundation lists (such as sidenav or block-grid) this will throw the styling off slightly. E.g. the side-nav here https://online.buttercupstraining.co.uk/apprenticeships-vacancies

I've tried things like:
`.field-name-body ul {
    list-style-position: inside;
    padding-left: 0;
    text-indent: 0;
    }` 

But can't seem to remove it. Have you come across this, or have any recommendations?

Thanks

**Comment by michael-collins** [comment]
You'll need to remove or override this `.node-page ul {
  margin-left: 2.5em;
}`

**Comment by rickhumphries** [comment]
Top bloke! That's sorted it now, thanks :)
