### ISSUE TITLE
Project Pipeline

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1133]
In creative production, the process, tools, and management of a project is called a pipeline. (The things that happen at the beginning affects the project later on.)

Studio has been a kind of catch-all for creative project management, but really it contains aspects of creative projects that are part of a pipeline. I'll soon need a specifically tailored pipeline that integrates the [double-diamond project workflow](https://medium.com/digital-experience-design/how-to-apply-a-design-thinking-hcd-ux-or-any-creative-process-from-scratch-b8786efbf812#.jy4du2x60). I'm working on some paper-prototypes that will inform aspects of the pipeline, but it would be pretty cool to have, possibly a new system designed for creating project pipelines according to specific needs. I'm teaching 3 levels of a similar class, so the instruction scaffolding of the pipeline will change for each course, but conceptually it's the same process. Hooking the pipeline deliverables up to grading system would be pretty necessary to scale the class, as is auto-managing/assigning crtis and discussions, submissions and the like, etc.

This would be VERY useful for all project based courses – not a one-off deal.

See an example pipeline built by a friend of mine: [Pipeline](http://pipeline.cc.gatech.edu/screenshots)

**Comment by michael-collins** [comment]
It is possible that pipeline could be a subset of studio, but they come in different forms depending on the class and sometimes the project. It seems like it might be too heavy to roll into studio.

**Comment by michael-collins** [comment]
A major feature of pipeline when used for team is that students would be assigned roles, sometimes equal contributors, sometimes managers, etc. I see this tool plugging into inbox, grading, assignments, discussions, etc.

**Comment by michael-collins** [comment]
Ultimately, it's hugely valuable for students to learn to develop their own pipelines. Having the ability to set it up and follow it would be very interesting. That is scoped for DMD 300, the second DMD course not due to run for a while.

**Comment by michael-collins** [comment]
Example professional software:

- https://www.shotgunsoftware.com

**Comment by btopro** [comment]
#1162
