### ISSUE TITLE
Data Reporting - Visualising Data

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1135]
We've already got some custom built student reporting functionality within the CIS using DataTables (https://www.datatables.net/). It works OK, but we're soon going to be looking at not only improving its usability but needing some form of visualising the data. That's because we're getting a lot of requests from companies who want their own 'managers portal', where for example, a regional manager can log in and compare the different areas within their region to see who's completed the training required, which stores are performing the best, that sort of thing.

I've seen a lot of work to use Angular recently, and following that trend it would be cool have something like D3.js part of core to be able to build this sort of thing. 

 This also sounds like it might be useful - http://krispo.github.io/angular-nvd3/ 

I imagine it could then be used to build reports from data coming from Learning Locker, as well as anything stored on a separate database?

**Comment by btopro** [comment]
#773 too

**Comment by btopro** [comment]
#900 

Yea these sounds like discussions we're just starting to have now. We've been waiting til we had data worth visualizing before making assumptions about what to show. I think data visualization will be a big push this Fall after we on-board...

**Comment by btopro** [comment]
Other issues have broken this out further and will use chart.js to handle
