### ISSUE TITLE
Ubuntu Issue

### ISSUE THREAD

**Issue by kfurst** [elmsln/elmsln#114]
Finally got ELMS running on Ubuntu 14.04. a week or so ago had an issue with a couple of errors coming out of Virtualbox regarding network settings. Tinkered with a couple of things in the network settings of VirtualBox and got it working. Now recently updated Ubuntu, noticed CentOS in the VM updated, and now I cannot connect... just spins in the browser. I got those error messages regarding port forwarding/network problems last night but had to run before I could troubleshoot. Now today, no error messages but same problems. 

I can SSH in. Restarted both Apache and MySQL in the VM. No change. etc/hosts file is still correct. Thinking I need to change something again in the Network settings of Virtual Box (which made it work the last time) just can't remember what. I have Adapter 1 and 2 available in the tabs.. what should the "attached to" have selected? I think that was what I changed the last time to get it working.(I had it going for over a week with no problems .... until the updates). Currently both are set as NAT (defaults).

**Comment by btopro** [comment]
What do you mean by "noticed CentOS in the VM updated"? You mean the VagrantFile updated to CentOS or your trying to manage the system in a base virtualbox instance that you installed into?

As for the Adapters this can be related to Wifi vs hardwire network as well as what "location" you are using (if on OSX, if not that part doesn't apply at least). I don't know how / if / why that would influence things in the way your describing though.

By upgrade, do you mean elmsln upgrade or the vagrant image?

**Comment by kfurst** [comment]
When first installed I believe it was on CentOS 6.5. It now gives 6.6 as the version during boot in VirtualBox. That's all. 

For the adapters... Using Ubuntu 14.04, hardwired. Set them both back to NAT which was the default. The only reason I asked was that after I installed Virtualbox the first time 2 weeks ago, when it was doing the vagrant install, Virtualbox errored out but gave info about what packages where missing and the specific sudo commands to install those packages. It worked then. 

I recently updated my local Ubuntu install which was when ELMS stopped working again (i.e. something probably got messed during that update uninstalling those extra packages I needed the first time.) This time though I don't get any error messages from 

(On a side note, it's super annoying because my Wine stopped working at the same time and is messed up thus I can't work on my Windows stuff either) X(

![screenshot from 2015-06-18 09 57 27](https://cloud.githubusercontent.com/assets/10422744/8234420/7aab63ec-15a1-11e5-8465-f8f8a1038592.png)

**Comment by btopro** [comment]
did you try `vagrant destroy` then `vagrant up` ? That'll rebuild the server; I haven't run this VM in Ubuntu so I'm not positive; there is the commented out line in the VagrantFile that can allow for 32 bit versions to build.

There was also a lot of issues with package managers in general about a week ago cause some linux mirrors were down for server enhancements. I had dozens of travis and local vagrant builds fail as a result of that global outage. Not saying that's it but, trying to rule things out.

**Comment by btopro** [comment]
Also, title is currently Ubuntu issue; do you mean the VM is ubuntu or the host environment is ubuntu?

**Comment by btopro** [comment]
@bradallenfisher added int he auto restarting of mysql / apache when spinning up the VM. hopefully this helps clear up this issue. if not please reopen
