### ISSUE TITLE
Students should be able to edit there submissions past due date.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1141]
We could probably put a "last updated" field on the submission display.  We could also allow instructors to see the revision history.

**Comment by btopro** [comment]
is there a way we could use the workflow status field to help only allow edit if it's kicked back to them w/ a status other then submitted?

**Comment by heyMP** [comment]
Yeah that's true.  the student can message the instructor to have them kick it back.  One question does arise with this though: what if the other students have critiqued the submission?

**Comment by btopro** [comment]
at least with what we do it becomes a different process.
Step 1, submit something
Step 2, get feedback
Step 3, remediate and submit another item
Step 4, instructor grades this

The original work doesn't get progressively enhanced ensuring that the instructor can also review the progression and modifications based on feedback.

**Comment by btopro** [comment]
merging into #1545
