### ISSUE TITLE
Domain name to be used for shared self-signed certs

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1149]
Basically the concept is to create a domain name that we can use to share certs so that we can create local https environments in which we don't get "are you sure" and "back to safety" errors.
- letsencrypt to create the intermediate pem file that all local cert and key files share
- automate the localhost.cert and localhost.key files
- local sites would use the public domain but switch hosts file to use vagrant environment

**Comment by btopro** [comment]
This would be extremely useful to pursue while getting our Dev / QA process in order. I think certs requested that are legit against a legit domain which would then be packaged into the Vagrant routine so we could install w/ HTTPS would be good

**Comment by btopro** [comment]
been over a year, no resolution, no traction on this. closing out.
