### ISSUE TITLE
Experiment with Docker Images

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1150]
Create Docker images to be used as in place of running bash on deployment. 
For example create a container that has php, mysql and apache installed. When running a one liner pull that docker image instead of running yum install or apt-get install.

**Comment by bradallenfisher** [comment]
So the big picture here is that we want to use Docker for gains in simplicity and speed to development.
Realistically we will only be shaving off 10-11 minutes of pre-install stuff if we do a combo of docker and elms-install.sh. After that infrastructure stuff is done, we will still need to install all the drupal sites and wait for that process. Installing elms takes a little less than half the time of the whole process. 

Looking at this differently, if we created an image for elmsln, we could literally use a set of docker containers/images for everything. The tricky part would be setting up the volumes on the host so that we can basically get elmsln in the state that is it in based on the branch that we want to work on, and then also be able to push, pull and commit changes to whatever branch we want to work on. 

The other question that needs to be thought about: do we still want to do this inside vagrant? 
With vagrant we could install a base box and have a startup.sh script that installs and kicks off docker. That way we could still use the Vagrantfile and people currently using that workflow wouldn't really notice a difference in (other than speed), and wouldn't have to change their software.  for more info on this see https://www.vagrantup.com/docs/provisioning/docker.html

**Comment by btopro** [comment]
Time off is great. Obviously the faster the better but I wonder how much faster that spin up will be when we get on Drush 7, PHP 7, and MariaDB / mysql (whatever their latest is).  Could we have a container for drush given the dependency BS that's been going on there (yet another thing we could shave time off w/ and improve consistency).

So, containers we'd have (unless i'm missing something):
apache
php
mariadb
drush
elmsln (which is kind of a blank shell that then starts itself)

I'd still prefer vagrant (at least for now). Vagrant calling docker is a pattern I've seen before like you said; mostly for simplicity / consistency w/ other provisioner users.

My other question; what happens w/ the elmsln/config directory which is built at run time? Do we need a separate container for the config so it could be pealed off and the "elmsln" container upgraded / modified / swapped out independently?

**Comment by btopro** [comment]
Experimentation complete for now; we'll revisit in another few months to see where it's at. Right now assessment proves it's not worth jumping on yet
