### ISSUE TITLE
noun project integration for journey mapping

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1157]
I have a visual mapping assignment for pipeline, where I want students to visually describe a journey, called journey mapping. It would be amazing to have access to auto pull from the noun project through their api, and drop the icons into a storyboard type of thing (a series of material cards that can be reordered). I can see this being used for other types of assignments as well. The paper version typically involves using a marker and drawing, which would be tedious for online. Perhaps a method for users to also upload phone images in addition to the icons, so that we can easily allow for custom drawings to be inserted.  Maybe an email or text message auto sends and uploads the image to the specific card?

A mapper will also write notes on each card that includes what is happening, and how it made  them feel, and if there was opportunity for design intervention (usually done after the map is completed and analyzed).

**noun project api**
http://api.thenounproject.com/
Sample PHP Code: https://gist.github.com/hirobert/710f2e22ed803dc34cc0

**What is journey mapping**
https://vimeo.com/78554759

**Ways of remixing the journey map cards for designing**
http://static1.squarespace.com/static/55ba4533e4b0cde7d7dd93ae/561bcf02e4b0bc599a39521e/561bcf0ae4b0bc599a395385/1444663050137/Design-Session-Poster-v-2.0.pdf?format=original

**Comment by btopro** [comment]
#1133
