### ISSUE TITLE
Javascript in CIS off-canvas menu seems to be broken

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#116]
The menu links in CIS off-canvas menu that contain sub-navigation items do not properly expand to show the sub-menu items (they do nothing). JQuery Update is on 1.10, so I'm not entirely sure what the issue is.

**Comment by btopro** [comment]
good question. noticed it on your deploy after the CIS 1.x to 2.x transition. haven't seen that in testing before. has something to do w/ the menu name rewriting (or lack there of) like a template file isn't loaded up. Not positive yet but there is something small there. the items are actually there, just the names reflected in the # are not the names in the menu itself

**Comment by btopro** [comment]
related to #143 which was fixed
