### ISSUE TITLE
Add American Sign Language Input Option

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1160]
This is a far-future task -- but allowing a sign input could allow for additional accessibility but also provide a platform for students to have a practice space for signing online. I know Penn State and other colleges offer sign language classes -- so this type of feature could allow students to practice online.

I would envision this as an alphabetical input rather than having the system need to read all gestures associated with the language. 

This is related to #947

**Comment by btopro** [comment]
I see, so you mean actually learning sign language through the system by practicing it in front of camera and having the JS library convert it into input. So a field is presented that has the letter J and a webcam canvas area. Then the user signs J and if the input field gets populated with the match it says they did it correctly.

is that the (ridiculously cool) idea?

**Comment by btopro** [comment]
I'm going to go out on a limb and say this would make sense in interact only because it's interactive and ridiculous

**Comment by mmilutinovic1313** [comment]
Correct! You could expand it to be an input field for text as well to have a user be able to sign to type. That makes it more crazy -- but yes interact would be a good place for it.

**Comment by btopro** [comment]
probably something that could be a total stand alone and then pass the "app" json or whatever as to what letters to practice or in what order.

**Comment by btopro** [comment]
related issue closed; this is a cool idea and i'm sure the HTML Canvas element will be able to suppor this at some point but nothing in sight. closing as inactive.
