### ISSUE TITLE
Add course offering and section separately

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#117]
Is it possible to add a course offering without an ANGEL string?

**Comment by btopro** [comment]
umm.... I believe you can do that right now, are you reporting that you can't cause in CIS 2.x there's now no requirement to add *any* logistical info from the system setup page.

**Comment by michael-collins** [comment]
Well, there used to be an offerings page, where I could add an offering. Since the UX is incomplete, I can't locate that interface anywhere.

**Comment by michael-collins** [comment]
I found a way. You have to go to the course node and edit the node :)

**Comment by michael-collins** [comment]
Actually... I created a semester offering, but cannot add a section now. Is there a way to do it?

**Comment by btopro** [comment]
Go to course in question, chevron, offerings, should be some stuff saying you can add. Also on the add offering page (left slide out) if you do an offering year / semester that it already knows about it'll just add the section under it.

**Comment by michael-collins** [comment]
@btopro I could not follow your directions. Closest I got was going to the CIS course and clicking on chevron --> edit, and then scrolled down to sections. Adding a semester is doable, but adding a section is not. Can you try it for Chem202 and tell me how you did it?

**Comment by btopro** [comment]
Ahh ok I see the issue. There was a View from 1.x marked as "charts" which was node%/offerings to administer this kind of stuff. Charts stuff has been largely removed in 2.x so this view got grouped in in error. Will need to port it over from 1.x (nbd). usually it would be at something like chem202/offerings

**Comment by btopro** [comment]
this has since been fixed; the view needed to be exported and pulled into the 2.x of the system; oversight on my part.
