### ISSUE TITLE
Review pathcache

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1172]
https://www.drupal.org/project/pathcache

**Comment by btopro** [comment]
Test plan:

- Make a site that has 300 nodes in an outline designer content outline (single outline, can be nested however)
- Enable Devel with the query / page timer / memory usage output appended to bottom of page
- blow caches away, see counts, then refresh and see counts. Go go next page in outline and see counts on initial vs next load.
- enable pathcache and repeat the previous step to see what the differences are if there are any

I've had a few people say this makes a difference but I'd like to know what difference and how significant. This could be something worth enabling on all systems but would like to get some data to support that move / upgrade path (cause we'd have to inject something into shared_settings.php in order to do it)

**Comment by mmilutinovic1313** [comment]
I'll work on this alongside the `hidden_nodes` patch tomorrow. I did find that devel started crashing my machine's vagrant when I was using more and more of its settings. I got a 503 error at one point.

**Comment by btopro** [comment]
@bradallenfisher would be the one to talk to about that but it might also be ur settings. only need memory / page time / query log

**Comment by mmilutinovic1313** [comment]
Will do -

**Comment by bradallenfisher** [comment]
The general rule with devel is turn it off when you aren't using it. So basically don't turn on the profiling stuff when you are doing things you aren't profiling. 

For instance, if you are spinning up courses and stuff, disable memory / page time / query log, until you actually want to look at that data.

**Comment by mmilutinovic1313** [comment]
Ah okay - that makes sense. It shouldn't really crash for this test then since the tests I was running last specifically focuses on caching when the content was updated / created. Thanks! I'll get working on this then. I'll probably use devel_generate to make those 300 nodes.

**Comment by mmilutinovic1313** [comment]
# Stats:

## Without Pathcache enabled

Initial Cache Clear:

> 1108 queries in 588.9 ms | Page execution time was 1912.97 ms. | Memory used at devel_boot()=0.83 MB, devel_shutdown =47.96, PHP peak=51.25 MB

Initial Refresh: 

> 246 queries in 105.74 ms | Page execution time was 227.34 ms. | Memory used at devel_boot()=1.01 MB, devel_shutdown =11.93, PHP peak=13 MB

Next Page Initial: 

> 391 queries in 400.88 ms | Page execution time was 647.36 ms. | Memory used at devel_boot()=1.01 MB, devel_shutdown =13.75, PHP peak=14.75 MB

Next Page Refresh: 

> 249 queries in 49.43 ms | Page execution time was 169.83 ms. | Memory used at devel_boot()=1.01 MB, devel_shutdown =12.06, PHP peak=13 MB

## With Pathcache enabled 

Initial Cache Clear: 

> 1235 queries in 944.5 ms | Page execution time was 2346.67 ms. | Memory used at devel_boot()=0.83 MB, devel_shutdown =48.79, PHP peak=52.25 MB

Initial Refresh:

> 244 queries in 84.76 ms | Page execution time was 210.88 ms. | Memory used at devel_boot()=1.11 MB, devel_shutdown =11.93, PHP peak=13 MB

Next Page Initial: 

> 395 queries in 119.95 ms | Page execution time was 302.1 ms. | Memory used at devel_boot()=1.01 MB, devel_shutdown =13.77, PHP peak=14.75 MB

Next Page Refresh: 

> 247 queries in 82.04 ms | Page execution time was 200.4 ms. | Memory used at devel_boot()=1.01 MB, devel_shutdown =12.06, PHP peak=13 MB

**Comment by mmilutinovic1313** [comment]
# With APDC Enabled

Initial Cache Clear: 

> 1271 queries in 732.8 ms | Page execution time was 2101.8 ms. | Memory used at devel_boot()=0.84 MB, devel_shutdown =49.24, PHP peak=52.5 MB

Initial Refresh:

> 238 queries in 42.83 ms | Page execution time was 167.07 ms. | Memory used at devel_boot()=1.11 MB, devel_shutdown =12.16, PHP peak=13.25 MB

Next Page Initial:

> 390 queries in 121.5 ms | Page execution time was 308.24 ms. | Memory used at devel_boot()=1.11 MB, devel_shutdown =13.93, PHP peak=15 MB

Next Page Refresh: 

> 241 queries in 72.06 ms | Page execution time was 193.78 ms. | Memory used at devel_boot()=1.11 MB, devel_shutdown =12.3, PHP peak=13.25 MB

**Comment by mmilutinovic1313** [comment]
This is working -- we will see a larger load for initial cache clear. Which makes sense because the it needs to clear more caches with the module installed...however for all other page loads we get significant speed increase, but no significant memory decrease. I can implement this in the 0.5.x branch if you would like.

**Comment by mmilutinovic1313** [comment]
Write update hook in elms_core to add this module.

**Comment by mmilutinovic1313** [comment]
@btopro is this elms_core.install? Or just a profile based .install file?

**Comment by mmilutinovic1313** [comment]
Found ulmus.install and added update there. Is that the correct file for the hook? And if so -- do I need to update the .info file to include pathcache as a dependency?

**Comment by btopro** [comment]
no elmsln_core.install

**Comment by mmilutinovic1313** [comment]
Hmmm okay - I'm having trouble finding the file. But I'll keep looking

**Comment by btopro** [comment]
elmsln_core.install where did u add the update hook then? lol

**Comment by btopro** [comment]
cis_connector/modules/features/elmsln_core

add to info and install files

**Comment by mmilutinovic1313** [comment]
Found it -- it was hidden in my sublime text dir

**Comment by btopro** [comment]
great work!
