### ISSUE TITLE
Independent study course scenario

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1173]
Independent studies are essentially courses custom tailored to a student's specific learning goals, where there is no existing class enabling them to earn credits towards their degree while honing in on niche mastery, typically a semester long project. This is really great in theory, however, many of these courses fail because some students struggle to structure their own learning and time given no scaffolding. When course loads get heavy, independent studies are the first to be de-prioritized, despite the grade being of equal weight. This happens particularly often for instructors who are too busy to track a student’s progress (ideally, students will report their progress). If the course seemed to have just as much "weight" as a traditional course, students would not de-prioritize it as readily.

Doing this in ELMSLN has a lot of advantages, the major one being Pipeline for creative projects.

Essentially, this is a hybrid-built course scenario, where students have content editor privileges and can edit assignments, as well as submit them. Their learning is self directed. The instructor is there for feedback, advice, and assessment of progress and to tweak the course as needed.

This may also be useful for flipped classroom teaching scenarios.

**Comment by btopro** [comment]
related / overlapping: #1133 #851

Once pipeline / studio 2.x flushes the branching paths off of this will become more clear
