### ISSUE TITLE
Digital Ocean Install

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#118]
Installed ELMSLN through digital ocean as per https://drupal.psu.edu/blog/post/install-elmsln-digital-ocean-one-line

All seems fine in general. Though did get the following error page when setting up a new course:

![elmsln error](https://cloud.githubusercontent.com/assets/4973810/8269734/e9168dc6-17ad-11e5-8025-aa1ab015c813.JPG)

Clicked the 'please continue to error page' link. and it took me through to the course outline service with access denied page. Tried the following in the command terminal to get a 1-time login link... `d @courses.kb uli` but it returns with '-bash: d: command not found'. Any ideas how to fix? Thanks

**Comment by btopro** [comment]
Try drush, alias might not be set

Wp8
________________________________

**Comment by rickhumphries** [comment]
Ah that did it :)

**Comment by btopro** [comment]
What kind of server did you deploy this on? There are one-line installers for Ubuntu and CentOS 6.5 but CentOS has been the most tested as it mirrors our RHEL 6 instances internally. Also if you'd rather play locally with less effort in getting it spun up, the Vagrant instance included with the main repo utilizes the One-liner for spin up in CentOS 6.5 -- https://github.com/elmsln/elmsln/wiki/Vagrant:-Step-by-Step-setup

**Comment by rickhumphries** [comment]
I followed the video on the Drupal PSU blog link above so believe it must've been CentOS 6.5. I got it going in the end.

I tried Vagrant, but kept running into problems because I'm a noob. I got an ELMSLN instance spun up a while ago, then when I wanted to update it, I deleted all the files and the virtual machine etc. instead of running 'vagrant destroy' (which I feel like would've been the right thing to do). Now when I try to vagrant up there's a problem with a port already being used. Will need to post a separate issue when I get back to my home computer

**Comment by btopro** [comment]
hmm... port already in use is common when it wasn't shut down correctly or there are multiple VMs running. If you open Virtual Box you might see something else running, especially if you played around w/ Learning Locker in a VM or something at one time.

**Comment by rickhumphries** [comment]
Hey @btopro - decided to try out TinCan Drupal module on my local install of ELMSLN that I did through DigitalOcean. It asks for my FTP settings when I try to install a module though. Do you know what they would be?

**Comment by btopro** [comment]
I'm assuming the IP address / end point for Learning locker

**Comment by rickhumphries** [comment]
It's for the installation of the module itself here:
![image](https://cloud.githubusercontent.com/assets/4973810/8673277/fe9664dc-2a2c-11e5-938f-7b86d1862cb1.png)
Or should I just to this via Drush?

**Comment by btopro** [comment]
oh, always drush.

`drush @courses dl tincanapi`

most likely

**Comment by rickhumphries** [comment]
![image](https://cloud.githubusercontent.com/assets/4973810/8673931/7ab1af4a-2a32-11e5-952f-6081b0ad0304.png)
Any ideas?

**Comment by btopro** [comment]
Try
`cd /var/www/elmsln/config/shared/drupal-7.x/modules/`
`drush dl tincanapi`

That should bring it into scope assuming it built correctly.

**Comment by btopro** [comment]
from the looks of it it'll be in the main package of the system as an optional add-on pack pretty soon so we'll avoid this setup part :)

**Comment by rickhumphries** [comment]
So I got the module installed OK. Tried whipping up a course afterwards and got hit with a few errors. First it was the same error I got from the first post above. Then when I clicked 'continue to error page' this was the courses page:
![image](https://cloud.githubusercontent.com/assets/4973810/8675237/a4268186-2a3a-11e5-83a0-6510c5135e23.png)
And this was the page when I entered the one-time login link url:
![image](https://cloud.githubusercontent.com/assets/4973810/8675270/d1e0c906-2a3a-11e5-9410-7e88951a6338.png)
I tried generating statements in Learning Locker using our details but it didn't work. I might DM you our LL details to see if you can get anything generated from your setup.

**Comment by btopro** [comment]
Yeah I'll have to play w/ LL as well as the D.O. spin up, haven't done it there in awhile

**Comment by btopro** [comment]
Thinking this was a temporary thing as I've been able to bring up in D.O. via the CentOS 6.5 install routine.

**Comment by rickhumphries** [comment]
hey @btopro just returning to this as I'd like to test the PDF library thing from #280. I'm trying to setup a local install of ELMSLN to mess about on, so did a video showing my steps just in case there's anything I'm missing? https://youtu.be/lSvzuTfLnRM

**Comment by btopro** [comment]
ugh. I hate ubuntu so much right now. no looked like the right steps. Try on a CentOS 6.x box and use the handsfree centos one. Either that or fire it up in vagrant locally (which uses the centos 6.x routine to install).

**Comment by rickhumphries** [comment]
Tried a CentOS 6.x box, but I get the following on the CIS page:
![image](https://cloud.githubusercontent.com/assets/4973810/11166426/cb946aac-8b2a-11e5-9517-a3238da7c4cf.png)
Got the following error in my console towards the end but not sure if that's related
![image](https://cloud.githubusercontent.com/assets/4973810/11166432/043036b6-8b2b-11e5-88fe-2bcd63e6b549.png)

**Comment by btopro** [comment]
ugh.

try doing this prior to the "one line"

`
RPM="$(which rpm)"
# get the epel and remi repo listings so we can get additional packages like mcrypt
wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
$RPM -Uvh remi-release-6*.rpm
wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
$RPM -Uvh epel-release-6*.rpm
`

**Comment by rickhumphries** [comment]
@btopro yeh, so that's got the installation working which is cool (just had to get the epel repo first before the remi repo).

So the CIS displayed properly, then tried to create a new course w/content outline and it redirected to this page after all the processing had been done (I can send all the text if you want!):

![image](https://cloud.githubusercontent.com/assets/4973810/11197631/ab1e22da-8cb6-11e5-8096-407298549a7e.png)

And then afterwards the CIS page just shows this:

![image](https://cloud.githubusercontent.com/assets/4973810/11197695/08b6bf2e-8cb7-11e5-98ed-fc4f062d566c.png)

**Comment by bradallenfisher** [comment]
Mysql isn't running.

**Comment by btopro** [comment]
hmm... yeah... how big a server did you tell Digital ocean to spin up? Been reading some stuff recently about mysql 5.4+ requiring digital ocean / amazon servers to have at least a gig of ram; most tests I spin up on digital ocean are

**Comment by rickhumphries** [comment]
Ah OK, that makes sense. I did a 512MB server so I'll give it more beef and see

**Comment by rickhumphries** [comment]
Yeh that's worked :) So after I set up a course and everything, one other thing that was going on (I think) was that Drush wasn't being picked up correctly so I couldn't run the `d @courses.coursename uli` command. I needed to change some info in the .bashrc and .bash_profile files. I used info here https://www.drupal.org/node/1213092 to fix this. 

So my .bash_profile file looks like this:
```
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/home/username/drush

export PATH
```
And my .bashrc file looks like this:
```
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
# .bashrc

# User specific aliases and functions

#alias drush="~/drush/drush"

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
alias g='git'
alias d='drush'
alias l='ls -laHF'
alias drs='/usr/local/bin/drush-create-site/rm-site.sh'
alias leafy='bash /var/www/elmsln/scripts/elmsln.sh'
alias g='git'
alias d='drush'
alias l='ls -laHF'
alias leafy='bash /var/www/elmsln/scripts/elmsln.sh'

PATH=$PATH:$HOME/bin:/home/username/drush

export PATH
```
And that did the trick

**Comment by btopro** [comment]
@rickhumphries yeah the source .bashrc fixes that up since the active session doesn't know that this file changed during setup (and needs to be a deliberate action by the user to trigger it). Next login it would work :)

Would you mind starting a requirements page in our docs section about specs needed to run? https://github.com/elmsln/elmsln/tree/master/docs

I can help you issue the PR if your interested or just writing a basic Requirements page in a gist or issue or something that we can pull in would work too.

**Comment by btopro** [comment]
After there's an item in the docs for this we can close it out

**Comment by rickhumphries** [comment]
Sure, I'll see what I can do. Will probably need some help though :)

**Comment by rickhumphries** [comment]
@btopro couldn't see how to add a page to the docs (would I just add a file called requirements.md?) In any case, wasn't sure what to put other than 'minimum system requirements: 2GB RAM' so I've added this to the installation page instead

**Comment by btopro** [comment]
make a file called Requirements.md (.md files auto render nice on github)
 then go into https://github.com/elmsln/elmsln/blob/master/mkdocs.yml and see how you can add references to pages. If you have questions let me know
