### ISSUE TITLE
Ubuntu /tmp / temp files directory location

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1180]
Should we should push /tmp into the same bucket as private files. We just ran into a crazy ubuntu specific issue as a result?

`/var/www/elmsln/config/private_files/tmp`

this should be the default for everyone since it's then not in the system level tmp and has its own free reign to manage temporary (as far a drupal cares) files

**Comment by bradallenfisher** [comment]
is this a drush vset call I can't find?

**Comment by bradallenfisher** [comment]
found it. nm.
