### ISSUE TITLE
Materialize CSS Components Available in 0.4.0

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1187]
Just wondering which components are available to implement out of the box in the new release? We're doing some mock ups for improving our dashboard so it'd be good to know what's available for us to utilise :)

**Comment by btopro** [comment]
So we have full access to the latest version of materializecss's CSS / JS. There is currently 1 file that implements some of the JS / calls for its styles to be applied to things
https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/js/material.js#L30-L34

**Comment by btopro** [comment]
@rickhumphries this would be something good to add to the developer docs; that we use this spec and so it can be looked to to make things look awesomer :)

**Comment by rickhumphries** [comment]
@btopro yeh good idea. I'll write some stuff once we've updated and I've played around with it a bit so I'm a bit more familiar :)

**Comment by btopro** [comment]
reopen w/ specific things missing from the implementation when we get there. I just added a bunch more into 0.5.x branch as well (like card component rendering
