### ISSUE TITLE
Tincan module and .live function error

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1190]
It tries to trace when you click links to kick off statements; right now that's an issue because that isnt available in newer versions of jquery

**Comment by btopro** [comment]
@mmilutinovic1313 can you turn this into a patch against the http://drupal.org/project/tincanapi project on drupal.org?

**Comment by mmilutinovic1313** [comment]
Yup - I need a simple win today.

**Comment by mmilutinovic1313** [comment]
Posted the code from that commit to d.o. Do you want me to push the patchfile up into our codebase? Ifso would you like it in the patch folder or in the module itself?

**Comment by btopro** [comment]
thx dood
