### ISSUE TITLE
Course outliner script error

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1195]
While editing course content (both moving sections/pages and renaming them), page responds in two abnormal ways:
1. WYSIWYG moving isn't keeping up with icon dragging; you essentially have to guess at where the page will move to and cross your fingers. The page or section icon selects, but does not preview to new location or insertion mark.
2. Most (85%) attempts at moving or renaming result in script error (see attached). Items do move, however, though often a manual page refresh after  the error helps. 
![scripterror](https://cloud.githubusercontent.com/assets/16839175/17827983/c41b13f6-6654-11e6-9fd4-c920c8c57e10.jpg)

**Comment by btopro** [comment]
1 - we have some open issues to completely redo this functionality bc of things like this once you get into bigger course structures. To combat this a bit, if you are looking to move pages within the same hierarchy you can do the following
- go to the parent of the pages you want to move around
- click the three dots off to the right side that have additional options
- click 'edit child outline' and it'll load just the items under the current page to move
2 - this should be resolved, if you see it again please let me know.

**Comment by pja12** [comment]
Hi Bryan,



I suspected you were there; nice to be online late night again!



I tried your suggestion, but cannot see the three dots. I’m working in 
outliner mode, so Outliner Designer>edit order and titles>attached 
screenshot.

The page address in case the screengrab is blurry: 
<https://courses.aanda.psu.edu/aa121/admin/content/book/141> 
https://courses.aanda.psu.edu/aa121/admin/content/book/141

Any advice?

~Peter





Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
Clarifying; to get to the three dots I'm referring to, navigate through the course to the parent of the pages you want to move around. Then the 3 dots should be there allowing you to access a mini outliner tool that just deals with the content below that page

**Comment by pja12** [comment]
OK, I see what you mean. Unfortunately, my problem is that I’m trying to 
move items at the top two levels. Maybe its hanging because of the quantity 
of subpages within a section (i.e. moving a lot at a time?). I simply can’t 
get it to respond by showing me where it is going to place items.



Is there a way/shortcut to bump an item up/down or in/out of the hierarchy 
without the drag and drop? Example: an item is now nested at level 3, and I 
want to bump it up to level 2?



Also, I’d like to move pages deep in a nest in one part of the course to 
another deeply nested location in another section entirely. The way it works 
now is that I grab it, throw it in the general direction of where it needs 
to go, then keep dragging-and-dropping until it finally hits the right 
place. Slowness I can deal with, but the main issue is that it doesn’t seem 
to show me where the item is going to go.



~Peter





Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by pja12** [comment]
Oh, and the script error keeps popping up almost every time I do move 
something. Should I be worried about this?

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
If you edit the page you want to move look for advanced options in a tab, then there is a place it should say outline. This lets you select where to place the current page under in a much more low tech (but apparently working) way.

**Comment by btopro** [comment]
#1196

**Comment by btopro** [comment]
@pja12 give it a shot now; I disabled a project that apparently the outline designer doesn't enjoy that was recalculating the time for students to engage with the content on page saves. This is awesome and will make for really useful visuals in the future but unfortunately it seems to make the system angry when moving stuff around (which it then needs to rebuild all that data).

Let me know if it's any faster / working now.

**Comment by pja12** [comment]
Hi Bryan,



The low-tech page mover is great; I really appreciate being able to point 
the page to the right tree fork and it works like a charm.



But….. I can push the item up the tree, so to speak, but I don’t think I can 
set where in the order of the new hierarchy it sits, right? So if I pop it 
up from level 2 to level 1, it shows up at the end of the list of all the 
original level 1 items. Now I’m back to square one: when I try to move it 
via the WYSIWYG course outliner, it’s again hit-or-miss as to where it goes, 
plus it triggers the script error again. (BTW, this goes for not only moving 
an item order on the same level, but even for dragging an item up a level 
from 2 to 1, say.)



Or maybe I just need to restart Firefox to get a clean start?

~Peter





Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
Are you able to try Chrome? We generally recommend building in Chrome as i've started noticing issues w/ firefox recently (beyond just what you are describing). If that's no dice I can disable the outliner till I have time to rebuild it (higher priority now :))

**Comment by btopro** [comment]
#160 #355 #294

**Comment by pja12** [comment]
Hi Bryan,



Everything went well with the revisions work over the weekend. I wanted to 
give you an after-action report on what worked and what didn’t:



1.       Switching to Chrome did indeed take care of the script hanging 
error!



2.       Performance of the course outliner did not change, either after 
your note about switching off live preview or by switching to Chrome.

a.       The WYSIWYG doesn’t preview what you want to do: I can see that the 
item is selected, but not to where it’ll go.

b.      Performance is super slow. Granted, I am trying to move high level 
tree items, but even turning visibility on/off is measure din minutes of 
response time, plus….

c.       …in Chrome, there’s no indicator that the system is chugging along, 
so there’s no way to know if anything has changed (or not) until you wait, 
then manually try to click on an item. If it selects, the system is done, 
otherwise, not.

d.      I did some work in the ‘modules’ section of Canvas, and their 
drag-and-drop interface is likely the sort of thing our course outliner is 
supposed to be like. If I understood your email correctly, the slowness 
comes from the back-of-house work; perhaps there’s a way to let the user 
make the changes/rearrangements, then hit a ‘save’ button that executes the 
changes? This would be in contrast to live change with delays; and it might 
be best only to allow in course outliner mode.



3.       I could not access the ELMS file server section for the course via 
either Firefox or Chrome.

a.       Process: editing a page > inset image > browse server > pop-up 
window opens, navigation is <root> <local_uploads>

b.      In the past, the pop-up would point right at the ELMS server. How do 
I get there now?



Working in a time efficient manner with the course outliner is pretty super 
important, so I appreciate you sorting that one out!



Thanks again for your help,

Peter







Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
@pja12 Nice catch on the image server thing. That's working now so thanks for describing that clearly.

**Comment by btopro** [comment]
From talking this sounds like it was taken care of thanks to the disable button and probably was the result of theme incompatibility (addressed now) and the massive size of the operation (addressed with a bandaid for now w/ the disable button, rewrite of the whole thing down the road)

**Comment by pja12** [comment]
Hi Bryan,



Yes, I believe it is resolved. I did work both ‘live’ and disabled, and only 
later realized I was still in Firefox. Not a script error to be seen!

Also, the WYSIWYG works just fine now, even ‘live.’ Huh, how ‘bout dat!.

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
