### ISSUE TITLE
TinCan / XAPI support via Learning Locker

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#120]
Just found this TinCanAPI module for Drupal - https://www.drupal.org/project/tincanapi

If it does what it claims, this would be great for integrating with all aspects of ELMSLN distributions so they could report back to Learning Locker what people are doing where and when. Most likely this would be enabled everywhere so we could track page views / access in courses tool, submission of assignments in studio, viewing / engagement with media in elmsmedia, taking of quizes / interactions in interact, and participation in discussions in discuss tool.

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=_r1gJb6K9A0 video by @rickhumphries showing possibilities in this area

**Comment by btopro** [comment]
module added into ulmus, testing now

**Comment by btopro** [comment]
@rickhumphries I can confirm that this module works in elmsln and now is in the global package though not configured or enabled by default :)

also as per the #306 discussion. It has a function called tincanapi_get_actor which assembles a property for username and one for the mailto: address. I think we could easily patch this to allow for using a token to select what you want the mail / other identifier to be (since we discussed the need for it being init and their concept is just using ->mail)

**Comment by rickhumphries** [comment]
Nice one @btopro !! :)
