### ISSUE TITLE
Nav order reversed in sidebar vs. breadcrumbs?

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1206]
Hi Bryan,

I turned on the side nav bar, and noticed that the two don't match order-wise. 
- The breadcrumbs pulldown items are in the proper order
- The left side nav bar is out of order, and shows a different heirarchy depth than the course outliner (very minor amounts of greater indent)
See attached for example from this page: https://courses.aanda.psu.edu/aa121/node/251
, also happens in other instances (i.e. the next section, Design involves...) https://courses.aanda.psu.edu/aa121/node/250 

![orderissue](https://cloud.githubusercontent.com/assets/16839175/17948753/1d2b7994-6a20-11e6-85d9-100a03afbd13.jpg)

**Comment by btopro** [comment]
wow that is so stinking weird. I'm going to chalk it up to the issues from the other day and will have to dig in a bit deeper then I already have been this evening. The top breadcrumb is correct (if you open the outline you'll see it matches). I'll keep exploring what's up w/ that left block. So far I've only seen it in the 2 places you mentioned (most levels its perfectly fine).

**Comment by btopro** [comment]
@pja12 tracked both of these down. Give it a shot now and let me know if you find anything else wonky like that. I think it should do the correct menu order as well as hierarchy presentation (same issue manifesting 2 different ways).

**Comment by pja12** [comment]
Thanks, Bryan! Funny it is only those two; I specifically checked a second 
case to see if it was persistent – I wonder what the chances are that I 
managed to hit the two exceptions?

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
