### ISSUE TITLE
Instructor View

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#121]
Is it possible when adding the ANGEL string that we default to the ability for the instructor/course editors to access the course content immediately rather than when the course starts? Also, can we add other editors/instructors if they are not in the ANGEL section in the spirit of sharing or do they need to be in the ANGEL space? Ultimately, all instructors will need to ability to edit their content before the course starts.

**Comment by btopro** [comment]
ANGEL is a word loaded for just PSU, this is Access string (or something like that) for the community at large.  To your question though, I think this makes a lot of sense. When a section is initially created like this we could possibly do the pull w/ a special mode (like hey update sections... btw pull faculty for this one) and then make sure they gain access at that exact point in time as opposed to when the semester dictates its ready to go.

Right now they'd technically have to wait till the legal definition of a semester start, which would then pull in the roster from the data source. Comply will provide the "hey go do this" single command to add people and such but yeah, definitely needed.

**Comment by btopro** [comment]
not pushed up yet bc of testing but need more
