### ISSUE TITLE
xAPI ideas for data based visuals / information to draw

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1210]
- [x] Add support for a 'session' value in extensions to relate statements to a period of time
- [x] Add support for duration of page engagement based on scroll down / on unload
- [x] Add support for a permission to "view own data" so students can see their own data
## Meaningful visual for faculty
- Picture of what a person is doing
## Meaningful information for students
- How long to budget time
- Continue where you left off
## Meaningful visual for Staff / IDs
- Which lesson has the least material
- Is this balanced
## Meaningful visual for managers / program managers
- Which course has the least material
### How long have they been here:
- use meaningful session id that's unique
- First piece of data with a timestamp
- minus last piece of data with a timestamp

**Comment by btopro** [comment]
@kat-wehr tagging u on this since this is the issue mentioned in slack as a good place to list ideas about how to visualize this stuff / questions to ask / etc. @kmiffitt was talking about this w/ the Dev team yesterday (how we get meaningful research questions generated) and I thought this might be a good first step: Asking and answering dumb / easy questions, then progressively enhancing from there to more complex ones.

**Comment by kat-wehr** [comment]
I'm just going to add thoughts as they come to me.
Would be cool to have a calendar view of most popular days of access (calendar with numbers that show # of statements, # of individual users, etc) and be able to break that down by student too. 

Another one - line graph illustrating access over a semester to try to look at where the spikes are. Would be nice to have this for course as a whole, and then also to be able to break it down by page to see what students were revisiting at certain points in semester.

**Comment by kat-wehr** [comment]
Student stats: duration of sessions spent w/ content. How long are they interacting with content? How does that compare with the avg calculated/estimated time, etc.

**Comment by kat-wehr** [comment]
Also compare page stats by category: Pages w/ media, how many views/interacts/time spent do they get with the class, vs pages w/ questions, vs pages with no media at all, etc.

**Comment by kat-wehr** [comment]
Student stats: where did they go next? do they view content sequentially, do they bounce around seemingly randomly, did they just leave, etc. 

Data useful for students: how do I compare with the rest of the class, how does my grade compare, what do other students who are doing better than me do, how can I improve.

**Comment by kat-wehr** [comment]
For students: When they have reached certain points in the course, give them a "badge" or button or green light or something that lets them know how far they've progressed. Maybe 3 dots - red, yellow, green: red, just clicked & didn't interact, yellow, clicked and did some stuff in the page, green, did most of the stuff on the page. Could be based on how much they've interacted, and provide "hints" (ie, when you hover on a yellow dot next to your name, it could give a tip like "watch the video on the "Resume Tips" page to improve" or "answer the questions on the community service page to up your score" etc)

**Comment by btopro** [comment]
duplicate of #1360
