### ISSUE TITLE
Support for TED videos in media

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1212]
Lower ish priority? Add Khan Academy video support in media and also so it's included in the stats at the top. 

Example: https://courses.eldig-elmsln.vmhost.psu.edu/psu006/node/17

**Comment by btopro** [comment]
video on that page is TED, did you mean that? Both would make sense to support in some capacity if it's possible. The youtube method for obtaining the duration currently in use is pretttttty hackey and may break at some point just as an fyi :)

**Comment by kat-wehr** [comment]
Ha, yeah, TED. Woops.

**Comment by btopro** [comment]
@kat-wehr don't these exist on youtube?

**Comment by kat-wehr** [comment]
The embeds they give aren't served up from YouTube, if they do I'm going to be really annoyed because that would have solved a lot of problems!

**Comment by btopro** [comment]
well I added support for it, I haven't tested it (who would do such a thing) but it's pretty simple the part that mines the duration from windows since looking at their code it works the same way as vimeo

**Comment by btopro** [comment]
@kat-wehr you can find illegitimate versions on youtube I believe since you can download their files directily; that's probably what I found; they want the analytics of who watches what kept closer I'm sure

**Comment by btopro** [comment]
there's an underlying glitch in the way we ask for media if it redirects somewhere else. Looking into it today; could have been just a hiccup with my VM being weird (cause it was being really weird last night as you saw the slack storm)

**Comment by btopro** [comment]
@kat-wehr this is in the latest 0.5.x which I can roll on your server at some point if you'd like since you are running ahead of the official version

**Comment by kat-wehr** [comment]
Woohoo! Go for it. As long as you're reasonably confident it won't destroy anything of course. :)
