### ISSUE TITLE
rebuild public demo

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1214]
Fragged it the other day when I tried to rebuild it via shortcut / manual job. We need a better way of making this wipe itself and be kept on version with whatever the latest stable is. maybe we want this to be a manual process or something with docker on a crontab so we can roll back to a snapshot really easily.

**Comment by btopro** [comment]
I put this back to where it was but still the nightly rebuild script it uses doesn't work when run via cron; works fine when run as the user. something to look at at some point

**Comment by bradallenfisher** [comment]
need access to the digital ocean server.

**Comment by btopro** [comment]
https://github.com/elmsln/handsfree-demo
