### ISSUE TITLE
Edit Section List - Options not appearing in display after save.

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1215]
I changed the outline for 21681---1517 to Canvas Migration, yet Course Outline still shows as  the outline.
![screen shot 2016-09-06 at 11 07 00 am](https://cloud.githubusercontent.com/assets/12716869/18282252/5399b4c4-742e-11e6-8e81-7d810c9dab30.png)

**Comment by btopro** [comment]
cache setting currently invalidates this every hour, but you'd expect to see new results like 2 seconds after hitting save. This creates a lot of confusion as coming back to it it'll have the right info.

#1216 appears like it might provide a good solution but @mmilutinovic1313 will need to dig a bit deeper on it and provide some feedback. Very promising from my testing but we'll want to test a bunch more so we're not here having the same convo a semester from now :)

**Comment by btopro** [comment]
#1256 will fix this
