### ISSUE TITLE
Look into using views_content_cache to replace most views caching methods

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1216]
Something for @mmilutinovic1313 to throw into the shredder all work he did in the past ;)

Check out https://www.drupal.org/project/views_content_cache and see if there's any quirks that happen as a result. If this works (as my early testing seems to suggest it might) we could potentially throw out ALL past views cache settings and questions of caching things and instead of caching them as a question, we could cache EVERYTHING and set long cache times while making the settings such that "if the node type is created or updated, then wipe the cache".

This ensures that ANY operation that involves stuff shown in that view will invalidate the cache so that the latest data is always shown but that cached data is there for a long time (until the moment it needs blown away).

Mark, play with this, especially as it relates to operations in CIS. I'm not entirely sure we CAN use this everywhere but it looks like we could use this in many places. Also, DO NOT use the "current user context" or whatever it is under organic groups memberships. This doesn't work (and I don't know that we really need it cause I dono how that'd help us).

**Comment by mmilutinovic1313** [comment]
Tested this out and it seems to work well. Is there any speed analytics you would like me to do with this before making a PR for the module and then setting our caches?

**Comment by btopro** [comment]
#winning

**Comment by mmilutinovic1313** [comment]
Caching working when creating a new service. Need to check if it works with new sections etc.

**Comment by btopro** [comment]
awesome keep it up; hueristic we apply here is critical I think. For example. I was messing w/ the section list view the other day (which kicked this whole discussion off) and noticed that if I changed the title of a book outline (Course outline to Things and Stuff or whatever) that it wouldn't reflect the change there; update the section tho and it would. Section nodes are saved (to force a roster sync and keep titles happy w/ ANGEL/Canvas) nightly which then ensures that these wouldn't live more then a Day (yes I know we're setting to max length :)).  So there might be some room to step in and try and write something that allows other cache flush methods (i'd hate page saving to flush view displays too often if you know what I mean).

For example, if we could select a cache granularity of "If this book node changes" then it would ensure that the display would update instantly when a top level node that's in a book is updated but NOT when it's just a random page. This can be for down the road / if it's necessary, the defaults being sound will make this kick ass regardless :)

**Comment by mmilutinovic1313** [comment]
Awesome! I reread through your message here today and I think that could be a great place to move forward as the semester progresses. I can potentially work on something like that as a long-term semester project. Doing one more test on the new vagrant instance to see if section granularity works still. And then I will put in a PR tonight.

After that I'll add an issue for setting the caching to the max time so we can talk specifics on that. :)

**Comment by mmilutinovic1313** [comment]
Okay - through more testing it appears that adding a section can trigger the caches to clear. I tested this by seeing if there were inserts occurring within `cache_views`. I'll put a PR in for this module now and we can work on a plan for configuration soon. Let me know if you need any other tests or have questions!

**Comment by mmilutinovic1313** [comment]
Should be good to close I think
