### ISSUE TITLE
H5P and xAPI

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1219]
After upgrading to 0.4.0 we're going to use the core method of generating xAPI statements rather than our module. Just wondered what the process for setting it up is? For example, would all H5Ps embedded within a course outline automatically emit statements OOTB if the TinCan module is configured? Or do we need to do anything first?

**Comment by btopro** [comment]
tincanapi + h5p_tincan_bridge and it should just work so long as you have the LRS credentials in

**Comment by btopro** [comment]
@rickhumphries I'll close this out but once we test the xAPI statements more (they work, I want real world usage to see if we need to tweak before rolling it everywhere) and start building some visualizations of the data (doing now if you've seen tweets a week or so ago) then I'm hoping in 0.5.0 or 0.6.0 this stuff will just be on by default. For now you can enabled it in the way I said above.

Those 2 projects need to be enabled on the media system. If you want to track other stuff then they can be enabled in the course content as well (rocking both sides in our prototypes and having it push to the same backend).

**Comment by rickhumphries** [comment]
Good stuff! Yeh - I was thinking that by 0.6.0 (or beyond!) the most user friendly way of doing it would be to be able to enter the LRS credentials on a per course basis via CIS. The reason being, that if a course network is fairly extensive with blogs/forums/studio etc. and you wanted to track this sort of thing too, you'd potentially have to enter the LRS credentials in every course service for every course. If you agree with that direction then I'll create a new issue for this

**Comment by btopro** [comment]
@rickhumphries I think you'd enter the credentials once and they'd be setting the default everywhere else. Eventually this would be on spin up that it would ask you questions after build like where your LRS is. I would think we'd just do "I want to track stuff" level or are you saying you need a different LRS end-point per course?

**Comment by rickhumphries** [comment]
@btopro yeh so personally we've just got one LRS and happy to keep it that way - but I can imagine a use case where someone might want one LRS per course, or one LRS for the majority of courses, but a separate LRS for a smaller group of courses. You could enter the credentials once at the 'I want to track stuff' level which will be applied everywhere, but also (later) include the option to tweak this on a per course basis?
