### ISSUE TITLE
Create a Daemon

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#122]
drush-create-site would be at least 1-2 minutes faster (in initially starting) if it was a Daemon instead of a crontab entry. Also, we could use daemon's for the task running aspects of the system too. Whether this would be 1 daemon or a few I'm not sure, most likely 1 which is able to check for a few job files to process.

This can go hand in hand with the #80 as the daemon could run as this user. This will allow us to add the capabilities into comply / others that involve backend task running / spidering jobs.

**Comment by btopro** [comment]
@bradallenfisher any thoughts on how best to accomplish this

**Comment by bradallenfisher** [comment]
Oooh. Looking into it.

**Comment by btopro** [comment]
@bradallenfisher any thoughts on how to create this?

**Comment by bradallenfisher** [comment]
Not really.  I think you have to write C code.  I can keep looking.

**Comment by btopro** [comment]
cron works fine
