### ISSUE TITLE
try ckeditor markdown plugin

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1222]
https://github.com/hectorguo/CKEditor-Markdown-Plugin/issues/14

Something to try out when you'd like a change of pace. Basically it adds a button to modify stuff as markdown in ckeditor. something collins would love for sure.

**Comment by mmilutinovic1313** [comment]
Also looking into this

**Comment by mmilutinovic1313** [comment]
Is our version of ckeditor called `ckeditor_link`?

**Comment by mmilutinovic1313** [comment]
Ah wait I'm dumb -- /libraries not /modules

**Comment by mmilutinovic1313** [comment]
Running into the same issue described in that issue queue. Looking for a way to patch.

**Comment by mmilutinovic1313** [comment]
Tested this out again with clearing browser caches - did not seem to load the library properly as described in the issue. I've put a marker in their queue in case someone finds another fix.

**Comment by btopro** [comment]
ok, we'll just close it out then since it's a nice to have if it existed but we wont build it if its not
