### ISSUE TITLE
SSH Missing From Drupal GUI module install menu

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1227]
I may be one of the few people who uses this for testing from time to time, but today I noticed that the ssh option is gone from the gui module install menu in drupal. Not sure if this has something to do with the last centos box upgrade for vagrant?

![ssh_not_option](https://cloud.githubusercontent.com/assets/7243665/18395306/0be77822-768c-11e6-96eb-2e9dd103f64f.png)

**Comment by btopro** [comment]
uhh... what are you talking about?

**Comment by btopro** [comment]
gui install module? oh like the upgrade module?

**Comment by mmilutinovic1313** [comment]
connection should have ssh as an option

**Comment by mmilutinovic1313** [comment]
Modules -> install module -> Install from a URL

**Comment by btopro** [comment]
dono, we just pushed 7.50 into the 0.5.x branch which may have fixes associated with this.

**Comment by btopro** [comment]
drush / sftp things like a normal person ;)

**Comment by mmilutinovic1313** [comment]
Yup will do :P. I can close this if you would like
