### ISSUE TITLE
WYSIWYG template import via Textbook Sub-module Invalid PHP Argument upon ELMSLN Install

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#123]
Hi all,

This issue can be seen while running the ELMSLN Install via the Vagrant setup instructions (https://github.com/elmsln/elmsln/wiki/Vagrant:-Step-by-Step-setup). The Templates appear to be importing, but it is curious as to why the system is complaining about invalid variables, and it would be good to check if it is causing any other problems in the system itself that we haven't noticed yet. This can be seen in the image screenshot attached below. 

![wysiwyg_textbook](https://cloud.githubusercontent.com/assets/7243665/8432807/7927a968-1f42-11e5-99c4-ee70c52514ee.png)

**Comment by btopro** [comment]
@mmilutinovic1313 on the case ;)

This doesn't cause any issues but is annoying; something to do w/ updates tot he wysiwyg_template module downstream when the templates are imported via features

**Comment by mmilutinovic1313** [comment]
Hey @btopro, is this still an issue that should be investigated?

**Comment by btopro** [comment]
If still happening then yes, its pretty minor tho

Wp8
________________________________

**Comment by btopro** [comment]
checking the travis logs this has been resolved when some templates were reexported I believe
