### ISSUE TITLE
Saving Pages

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1232]
I can't save any content on the following two pages:

https://courses.aanda.psu.edu/art211revi/node/13/edit
https://courses.aanda.psu.edu/art211revi/node/12/edit

This is the message that I receive: 

The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved.

NOTE: No one other than me should be editing this page.  

Screenshot:

![screen shot 2016-09-12 at 11 33 06 am](https://cloud.githubusercontent.com/assets/12716869/18443960/3f1a8fee-78e5-11e6-8cd0-a58f704e7405.png)

**Comment by btopro** [comment]
close / reopen browser and try again, it's possible if you save it too quickly cause of the form-saving thing
