### ISSUE TITLE
Make our own CDN

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1234]
This could work with #1203 so that we could choose a mode for deployment that forcibly rewrites ALL drupal / elmsln delivered style sheets to come from a CDN such as raw-git / etc. This would mean disabling advagg and instead delivering something from our own CDN. Till then / as a prototype of what would be required, we could hit point release based rawgit addresses such as: https://cdn.rawgit.com/elmsln/elmsln/0.4.0/core/dslmcode/cores/drupal-7/modules/book/book.css

This would mean we'd be rewriting (via EasyCDN) references to the Drupal core book.css and instead point to the rawgit cdn. We'd have to disable advagg as mentioned, so there would be ~25-50 CSS/JS files being loaded BUT they'd only be downloaded once. Then every site you go to anywhere / everywhere (across deployments) would not need to download new files _so long as they are on the same version_.

This would also require either setting the version it's on or allowing for "developmental" addresses as well (in interim that would be https://rawgit.com/elmsln/elmsln/0.4.0/core/dslmcode/cores/drupal-7/modules/book/book.css ; not the cdn. is missing which prevents cloudflare hit)

**Comment by btopro** [comment]
Might be a great use for the aws pilot. Cloud based delivery of files that have no Pii implications

**Comment by btopro** [comment]
#994

**Comment by bradallenfisher** [comment]
just to be sure we are on the same page here...
Do we really want to build a CDN? Or would using a service be a better option?
AWS Cloudfront seems promising. But before I look into it, I want to make sure there aren't other reasons we would want to build our own.

**Comment by btopro** [comment]
Not going to be doing this, the new webcomponent paradigm makes asset delivery make so much sense that via CDN isn't going to net much
