### ISSUE TITLE
ELMS editor // "templates" pulldown pops open new window instead 

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1236]
Hi Bryan,

Whilst editing a page in A&A 121, as I attempt to pulldown the templates menu, I instead encounter a popup window with rather large images showing the templates. Plus, awkward sizing. See attached image for wowza moment.
![bigbox](https://cloud.githubusercontent.com/assets/16839175/18459705/cc3b346a-7939-11e6-8a02-0eefb9a0d1dc.jpg)

**Comment by btopro** [comment]
Well that's weird. Firefox wasn't respecting the fact that image should be 100px wide. Fixed on your site and committing code now. @pja12 you might need to clear your local browser cache if you go to the site and it's not fixed
