### ISSUE TITLE
ELMS student view outliner mode shows hidden(?) icon for not-hidden pages

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1237]
Hi Bryan,

Pulling down the course outline in regular/student view shows crossed-out eye icons for items that the Outliner has pegged as visible. 
- Seen in Firefox (doh! I was supposed to use Chrome!) 
- Persists after reload and restart of Firefox. 
- Happens in multiple other instances in the menu, but I don't see a pattern. 
Not sure if sections are actually invisible to students, or if it just a glitch.

Attached image shows student view in left half, course outliner of the same bit on the right.
![goldeneye](https://cloud.githubusercontent.com/assets/16839175/18459888/4dedbdba-793b-11e6-9138-e4a00c6f6fa2.jpg)

**Comment by btopro** [comment]
This might be related to the previous issues you were having w/ the outline dragging and not updating.

**Comment by btopro** [comment]
@pja12 yeah this was related to the previous issue (some icon associations under the hood never got refreshed).

In the future if you notice this with future content here's how I fixed it:
- Individual page I just hit edit then save
- Groups of pages - go to the page above that page in the child outline designer. Hide the item and select "propagate status". Then once it's done it do it again in reverse.

Students would have still been able to see these pages but I agree it would have been confusing. If this happens again I'll dig deeper but I believe it was related to the issues at the beginning of the semester and outline reordering.

Thanks for using the queue this makes life much easier :)

**Comment by pja12** [comment]
Thanks for both of those, Bryan, and the workarounds. I’ll keep you posted 
if they show up again!

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
