### ISSUE TITLE
Bulk upload for Images

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1240]
Support bulk uploading/drag and drop for image uploads in Media :)

**Comment by bradallenfisher** [comment]
I have used this in other projects with success https://www.drupal.org/project/multiupload_imagefield_widget

**Comment by btopro** [comment]
To create each image as a new node?

**Comment by kat-wehr** [comment]
I would think so since that's the way to organize/display it other places.

**Comment by btopro** [comment]
@bradallenfisher have u used this successfully to turn them into nodes?

**Comment by bradallenfisher** [comment]
nope. sorry. it will create one node with fields. with file_entity each file is an entity... but not a node.

**Comment by btopro** [comment]
https://www.drupal.org/project/plupload
https://www.drupal.org/project/node_gallery
https://www.drupal.org/project/bulk_file_nodes <-- promising sounding

**Comment by btopro** [comment]
https://www.drupal.org/node/2250573 + https://www.drupal.org/node/2181163 on top of https://www.drupal.org/project/bulk_file_nodes and https://www.drupal.org/project/plupload and I think we've got something pretty usable in its current state, more so after some form clean up.

those 2 issues are no joke though. It needs support for ignoring that figure entity reference creation field. Without that it works fine, allowing for drag and drop bulk upload, then modification of each item, saving them all as individual nodes.

**Comment by btopro** [comment]
fixed; the above combo worked w/ some patching and accounting for. Now there's a bulk option that shows up
