### ISSUE TITLE
Break drupal's core "conflict" connotation with node forms

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1245]
I've had multiple reports from instructors and some students that they are receiving the following error when adding content to MOOC and Studio.

```
The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved.
```

I'm going to disable authcache in these systems to see if this fixes the issue.

**Comment by btopro** [comment]
Has this cleared up when dropping authcache? If so, we might want to explore changes to the authcache settings

**Comment by btopro** [comment]
https://www.drupal.org/node/394694#comment-3869546

**Comment by btopro** [comment]
https://www.drupal.org/project/conflict

**Comment by btopro** [comment]
https://api.drupal.org/api/drupal/modules%21node%21node.module/function/node_validate/7.x is what causes this in the 1st place (in core)

**Comment by btopro** [comment]
Maybe we should disable authcache for any form / node edit system paths and then increase the time before we airspace. Autosave might conflict here. Can also look into automatic lock breaking if user ID matches

**Comment by btopro** [comment]
from running through authcache_debug module for all roles this page shouldn't be cacheable anyway (node edit form). Potentially something else

**Comment by btopro** [comment]
added a better message to explain what to do to solve the issue.

```
To prevent this error, don\'t hit refresh or use the back button once you start editing content. Instead, click the address bar and press return to reload the latest content.
```
