### ISSUE TITLE
Add banner picture to user profile fields list

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1265]
it's becoming common practice with social tools to have a headshot type image (user profile picture) as well as a landscape / inspiration / larger image. Google+ FB and twitter all have them and it would be cool to have support for in our people distribution as well. Especially as we move towards implementation of side nav it would look REALLY nice for the user profile flyout / to style into any area that's related to the user and their stuff.

Throwing this one Brad's way so he can dig into the guts of a new system we haven't done much with yet, see how we export features for things that ride across distributions (as this will) and just get in the front end a bit more.

**Comment by bradallenfisher** [comment]
do we have user profiles at this point? Or are we starting from scratch? 
I don't see any user profile fields at all at this point.

**Comment by btopro** [comment]
go to people.elmsln.local; it has the start of it

#550  #798  #1132  for related issues to get up to speed on it.

Idea is we have a central profile location which we can then replicate over to local storage bin / local sites as needed.
