### ISSUE TITLE
studio critique prototype

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1267]
https://dmd-program.github.io/pipeline/crit

**Comment by btopro** [comment]
#1273

**Comment by michael-collins** [comment]
Now that I look at it, a better design pattern for organizing this would be waffle.io. I really like the collapsible columns as opposed to the collapsible horizontal rows that I mocked up. Then modifying the process is about renaming or adding/removing columns.

**Comment by btopro** [comment]
@heyMP tagging potter since I know he's been actively working against this as of yesterday

**Comment by btopro** [comment]
merged into #1251
