### ISSUE TITLE
materialize all the things

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1273]
there's a branch for this currently just for this cause it's quite the job but it's effectively a blocking issue for other design component issues.

https://www.youtube.com/watch?v=VNp74xDlcnA

**Comment by michael-collins** [comment]
This template: https://getmdl.io/templates/dashboard/index.html
 is on the material light website: https://getmdl.io/templates/index.html

Would not be hard to create with materialize. Might be a good default interface, where the network auto opens on large screen widths?
