### ISSUE TITLE
Side nav current tool highlight

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1281]
For the network side nav, I wonder whether the menu item for the tool you're currently in should have some highlight or colour line next to it too, just as a visual cue that you're already there?

**Comment by btopro** [comment]
![2016-09-30_09-11-30](https://cloud.githubusercontent.com/assets/329735/18992725/e9da4878-86ed-11e6-96cf-2b0329ddf34f.png)
great suggestion
