### ISSUE TITLE
Customising and Localising the ELMSLN network styles/logos/names

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1287]
With the recent Material design work that's just been done in applying a distinct colour to each tool set, it's made me think that there should be a space in the CIS where global settings for each of the tool sets can be applied to personalise the feel of the tool for your setup.

So if you wanted to apply a different tool name/icon and colour for the 'Course Outline' (e.g. call it 'Online Textbook' instead), upload a custom SVG for the logo, and set the colour - you can do so and it would propagate through to the tools already in the system.

**Comment by btopro** [comment]
totally agree

**Comment by btopro** [comment]
#611 related

**Comment by btopro** [comment]
Because of #1516 we now can modify all colors, icons, titles, etc by modifying the registry in custom code. Here's an example that could be implemented:
```
/**
 * Implements hook_module_implements_alter().
 */
function MYCUSTOMCHANGES_cis_service_registry_alter(&$map) {
  $map['mooc']['default_title'] = 'stuff';
  $map['mooc']['group'] = 'Network 2';
  $map['mooc']['icon'] = 'interact';
  $map['mooc']['color'] = 'green';
  $map['mooc']['color_dark'] = 'darken-1';
  $map['mooc']['color_light'] = 'lighten-1';
  $map['mooc']['color_text'] = 'yellow-text';
  $map['mooc']['color_outline'] = 'orange-outline';
  $map['mooc']['color_code'] = '#ff0000';
}
```
