### ISSUE TITLE
Feedback about Menu Navigation

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#129]
It would be nice to be able to change the color or to bold to help the student identify where there are. There aren't many visual cues when they move from one navigation to another. When clicking on lesson one it should also go to lesson one not the next drop down.

**Comment by btopro** [comment]
When rolling down a menu level, it should be highlighted at the top of that nav item what is currently in context BUT NOT BE CLICKABLE.  The first page would the be well served to be an introduction.

This could also be starting to express the need for more well defined content types that have structural implications.

**Comment by btopro** [comment]
just pushed a ton of commits in this area. Look at #88 down in the comments as I'll be posting a video after I caffeine up a bit more
