### ISSUE TITLE
Mind map diagram builder

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1293]
I came across this and thought it was worth sharing:

https://www.drupal.org/sandbox/farrisimin/2806787

It's a quiz question type, which could be useful in itself, but didn't know whether you'd be able to get any more use out of the code. E.g. as an interact or media content type that can be embedded in the content outline to visualise workflows etc.?

**Comment by btopro** [comment]
interesting. I will say these have turned out to be pipedreams in the past but I can have one of the students see if they can get it to do anything. Where's that multimedia person you hired again? ;)

**Comment by btopro** [comment]
@mmilutinovic1313 something fun to play with / see if you can tinker and get working some time

**Comment by rickhumphries** [comment]
@btopro haha, he's probably off creating somebody a flyer in InDesign. Looking into the quality of code is a bit beyond him though! (I am toying with the idea of getting a developer in sometime in the future though 👍 )

**Comment by btopro** [comment]
thoughts

- UX would need some work.
- It does turn on but has warnings when loading up. This claims to be for quiz 4 and we have quiz 5 in our stack and it was a major rewrite
- it's making calls out to http://api.filepicker.io/v0/filepicker.js which I don't know what filepicker.io is so I don't know about security
- tool itself is pretty cool / seems to work reasonably well for creating a mind-map in the browser window
- saving / moving to the next question in the quiz bricks completely :)

**Comment by btopro** [comment]
Reopen later if another project comes up that could help get us there as this one seems very buggy

Also, ICOR already supports something called YUML which is worth looking at. It's not in the official package so you'll need to go into the features page of ICOR and enable YUML_type but you can get the idea of what it lets you build here https://www.drupal.org/project/yuml
