### ISSUE TITLE
Media - attribute content to more than one course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1298]
Sometimes I have a piece of media content that I use across more than one course so I feel like I should be able to select more than one course here. 

![image](https://cloud.githubusercontent.com/assets/4973810/19195944/7cb87e22-8cab-11e6-832e-9fa02d775087.png)

Alternatively (and way cooler) would be if the system automatically detects that I've embedded that piece of media in a course, and tags it with each course it's been embedded in.

**Comment by btopro** [comment]
hmmm. latest build is still single select. I do like the trackback idea though I'm not sure the best way to do that. In our legacy media system we have this happen at the media end point. So when media is loaded the nodes goes "dude who calls me.. oh, ok, let's stuff that here". Might add something like that in, not sure. good suggestion tho

**Comment by btopro** [comment]
@mmilutinovic1313  Basically, just allow for multiple courses to be selected for all assets in media and interact

**Comment by mmilutinovic1313** [comment]
Should be good to go pending PR merge
