### ISSUE TITLE
Bullet List Items

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#130]
Bullet list items maintain their own style.

**Comment by btopro** [comment]
![2015-07-07_15-08-08](https://cloud.githubusercontent.com/assets/329735/8554829/0f5c12c6-24ba-11e5-8b0c-e93dac591dba.jpg)

**Comment by btopro** [comment]
as part of the the theme and style thing; this is probably pretty easy

**Comment by btopro** [comment]
![2015-08-31_07-59-04](https://cloud.githubusercontent.com/assets/329735/9578268/5fc44a04-4fb6-11e5-9512-3d649a518405.png)

**Comment by btopro** [comment]
Got this report in from the Rock, initial indent seems goofed up here as well.
