### ISSUE TITLE
No database connection after install scripts

### ISSUE THREAD

**Issue by aaronbauman** [elmsln/elmsln#1306]
I've tried both Centos and Ubuntu installs from the one-liners, but after the script completes i'm getting Drupal's install screen.
Drupal can't find a database, and I don't know my sql password...

I feel like i must be missing something obvious.

**Comment by bradallenfisher** [comment]
what is your memory?

**Comment by aaronbauman** [comment]
I'm on EC2 small - 2G RAM, as stated in reqs.

**Comment by bradallenfisher** [comment]
gotcha. how are you spinning up the base box?

**Comment by aaronbauman** [comment]
So far, manually via EC2 gui:
" Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-2d39803a "

**Comment by bradallenfisher** [comment]
would you mind trying :"Amazon Linux AMI 2016.09.0 (HVM), SSD Volume Type - ami-c481fad3"

I have gotten that one to spin up correctly. I have not tested ubuntu on ec2 yet. Make sure you use the install line from

https://github.com/elmsln/elmsln/blob/master/scripts/install/handsfree/amazon/example-deploy

**Comment by bradallenfisher** [comment]
I will test the ubuntu today as well, to see if it's something obvious.

**Comment by aaronbauman** [comment]
OK i'll try that image and report back.

(Just tried Ubuntu again, and the errors start around warning about running composer as root - which I found elsewhere in the issue queue and won't re-report.)

**Comment by bradallenfisher** [comment]
thanks. yeah the composer errors are basically just warnings. as long as drush installs you should be good. I have a feeling it is something deeper with the ubuntu image that aws provides.

**Comment by aaronbauman** [comment]
Of course when I tried again the Ubuntu install worked as expected.
No clue what I did differently.

Thanks for your quick attention!

**Comment by bradallenfisher** [comment]
Sorry to re-open. I just spun up
AMI ID
ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160627 (ami-2d39803a)

and on Linode

Ubuntu 14.04 from the builds list. 

I just wanted to wrap this up by declaring that those scripts do work. 

Thanks for reporting this @aaronbauman.
