### ISSUE TITLE
People next steps

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1307]
- [x] tpl file for profile in CPR system
- [x] elmsln_core use hook menu alter to push user back to people.whatever/their profile when they go to edit their profile. This way calls to user/1/edit redirect to people.elmsln.local/user/1/edit (for example) and then know how to come back to courses.elmsln.local/sing100/user/1
- [x] use the _cis_connector_request methodology used in cis_filter to process shortcodes so that we can request what to display on `courses.whatever/course/users/btopro` from `people.whatever/user.json?name=btopro&display_mode=full`
- [x] Clear CID for the right object so that the change is instant
- [x] make profile / tpl file for their profile in context
- [x] figure out best approach for flyout profile side-nav element (user picture and background image) which may involve population of LocalStorage JS bin (scale concern)
- [x] note #1311 and then implement / enable https://www.drupal.org/project/filefield_paths on people domain and then make both file fields for the user store in locations we can easily tack after the fact. ( userfiles/backgrounds/abc123.jpg for example )

**Comment by btopro** [comment]
#842 #851 #421

**Comment by bradallenfisher** [comment]
I think there will need to be some discussion about what the user page is supposed to be. I see it as a dashboard of sorts. With things like my assignments, critiques, etc... for now there is a tpl with some fields and some minor css. Once we get the front end stack worked out this will be easier to style as well. #1330

**Comment by btopro** [comment]
#842 agreed

**Comment by rickhumphries** [comment]
Agree with @bradallenfisher on this. Things like 'upcoming deadlines' and recently awarded badges and stuff too. I also think the CIS could become the place for something like an 'individual course overview dashboard' as well but will write up thoughts in a separate issue.

**Comment by btopro** [comment]
got the last part of that in there
