### ISSUE TITLE
First login experience

### ISSUE THREAD

**Issue by aaronbauman** [elmsln/elmsln#1308]
After getting ELMSLN services up and running on AWS (thanks @bradallenfisher ), i'm now trying to use the site.

The install script says `use this link to get started: http://people.EXAMPLE.DEV` - so I do that and realize i don't have a  password (or username).

No problem - I call `drush @stacks.people uli` for a login link.
The login link doesn't work.
I get sent back to `/user` as though I wasn't trying to reset password at all.

OK, I poke around some more and find other people saying they started at `online.EXAMPLE.DEV`, so I call `drush @stacks.online uli` for a login link.
That link works; I log in and set my password.

Then I go back to `people` and try the password.
Doesn't work.

I read something about bakery, think maybe this is related to syncing something on cron.
Run cron 2x on `online` and `people`, alternating between them.
Still can't login to `people`

I'm looking in the docs for anything about logging in or managing passwords, but the docs jump from "installation via command line" to "adding a course via UI" without mentioning how to get from one to the other.

And now, as i've been writing this issue, i am finally able to login at `people` with the password i set above, although maybe I don't even need to.

I'll keep poking around to figure out what I'm doing, but I hope this narrative can provide some valuable outsider experience to help lower the learning curve for others.

**Comment by btopro** [comment]
@aaronbauman thanks for the feedback. I should be online.whatever not people unfortunately. If you use admin/admin you'll login the first time. This uses bakery so bakery will actually login at people.whatever BUT the user originates in online.whatever (or whatever else).

**Comment by btopro** [comment]
you also definitely bring up good points about how we need documentation pages for this and also improved security by not settings admin / admin on spin up.

**Comment by btopro** [comment]
@aaronbauman thoughts on related issue #1361 as part of cleaning up this experience (and then some)?

**Comment by btopro** [comment]
Especailly now that @bradallenfisher did the user profile thing we need at least SOME kind of page they are taken to after logging in as right now it's frigging blank :). Let's at least redirect to a help page or something

**Comment by aaronbauman** [comment]
Thanks for the reply and updates.
I haven't yet had occasion to re-install yet, but I'll update this thread with any additional feedback when I do.

**Comment by btopro** [comment]
- install screen now reports correct link
- we now have a #1361 install screen during spin up at the IP your putting it on
- 1st login welcomes you to the system and suggests you build a course; it also rewrite the message that would be presented at that IP address both for security and usability (suggesting the drush commands you can run to get back in if you don't know where to go as well as the domain name to log in on)
- UX associated with where and how to do this has improved in general
- bakery based issues previously w/ after build have been resolved.

Closing for now for my own sanity but feel free to open other suggestions after playing with these changes if you get a chance.
