### ISSUE TITLE
A&A 121_Outline shows hidden content

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1312]
Hi Bryan,

I navigated the course via the outline button that pulls down all the course content. To my dismay, I saw that the currently hidden sections of the course are visible in that outline. Is this visible to the students as well? If so, can you kindly set it so that the hidden items don;t show up for them? 
Thanks,
Peter
![slipisshowing](https://cloud.githubusercontent.com/assets/16839175/19250060/7823da8e-8f06-11e6-9867-3fb622004f2e.jpg)

**Comment by btopro** [comment]
Nope just hidden for students. This way you can easily find it still.

**Comment by pja12** [comment]
Thanks, Bryan!

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
