### ISSUE TITLE
Gitbook Outline Importing

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1313]
Is there a limit to nested items? In unit 2 tutorials, nothing seems to have imported.

https://courses.aanda.psu.edu/dmd100/node/234

vs

https://dmd-program.gitbooks.io/dmd-course-materials/content/topics/twine-tutorial-getting-started.html

**Comment by btopro** [comment]
8 levels deep

**Comment by btopro** [comment]
That's currently 6

**Comment by bradallenfisher** [comment]
Must be due to timeout.

**Comment by bradallenfisher** [comment]
I will put into batch i guess?

**Comment by btopro** [comment]
Yup batch API that badboy

**Comment by bradallenfisher** [comment]
that level didn't import on local either. not due to timeout.

**Comment by bradallenfisher** [comment]
we should still batch it, but this issue is not related to that. I will open another issue for batch api relating to gitbook imports.

**Comment by btopro** [comment]
Brad fixed it. It's up there now. Batch API aspect should be a future issue still just to prevent monster courses from bombing on import
