### ISSUE TITLE
Accessibility: Create an animated gif player style

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1315]
In upcoming courses, we will be using animated GIFS. I think people with disabilities need to be able to stop the looping of Gifs. Would a video fallback be a good option?

**Comment by btopro** [comment]
hmmm... is there something you've seen to suggest you need to account for this in this way? @heyMP

**Comment by btopro** [comment]
http://accessibility.psu.edu/animations/

**Comment by btopro** [comment]
@michael-collins so video fallback isn't necessary; if we use this plugin (or something like it) then we could have it be more of a "gif player"

**Comment by btopro** [comment]
http://ctrl-freaks.github.io/freezeframe.js/

**Comment by btopro** [comment]
https://github.com/ctrl-freaks/freezeframe.js looks promising. we should build support for this as a gif player in elmsmedia

**Comment by btopro** [comment]
need to apply circle classes consistently to parent items created during gif processing of circle style or you get weird grey outlines to things

**Comment by btopro** [comment]
This is in now!

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=6Kr04aZTmWI

**Comment by btopro** [comment]
it plays nice with all of our display modes, lightboxes, everything.
