### ISSUE TITLE
Authority: Webinars

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#132]
An area for group video meetings and discussions. Couple of possible integrations include:
- https://www.drupal.org/project/bbb
- http://openmeetings.apache.org/DrupalPlugin.html

**Comment by btopro** [comment]
H5P has a type that's for http://appear.in integration which looked pretty cool for easy, paid above 8 people, integration.

There's also some cool demos of what you can do w/ WebRTC here -- https://www.webrtc-experiment.com/

H5P / appear.in seems easiest to get going but have heard good things about bigbluebutton in the past.

**Comment by btopro** [comment]
@curiosity26 any thoughts on a WebRTC P2P conferencing "app" using sockets / something related?

**Comment by curiosity26** [comment]
Yea there's a lot of options for P2P WebRTC and web sockets (for direct file transfers and such)

**Comment by btopro** [comment]
FOSS?

**Comment by rickhumphries** [comment]
Found this as a possibility of looking into https://www.drupal.org/sandbox/gt/2210803

**Comment by btopro** [comment]
talked to some BBB people today, they now support WebRTC then fallback to Flash. good move on their part and seems like they've picked up some groups, cool stuff

**Comment by btopro** [comment]
from a lead in the project re drupal module:
```
We've not tried the Drupal integration ourselves -- it was completely created by the Drupal community.

That said, if it needs improvement, we have two other integrations -- Moodle and WordPress -- that are PHP based.  We also have an updated PHP library for BigBlueButton, see

  https://github.com/bigbluebutton/bigbluebutton-api-php
```

**Comment by btopro** [comment]
this would probably be an authority

**Comment by btopro** [comment]
There is no movement to do this at this time; Apereo has BBB in it's network of applications, perhaps down the road this functionality could be sponsored for addition but not at this time
