### ISSUE TITLE
Gitbook batch api on import

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1320]
Use batch API so we can import tons of items without timing out

**Comment by bradallenfisher** [comment]
should this go directly in to git_book? or in each submodule calling _git_book_make_node()?

**Comment by btopro** [comment]
looking through it it would be nice if this happened in git_book but the make node function only makes the node. I'd say it probably has to happen in the gb plugin itself with an example for how we'd do it in other formats if we wanted to.

**Comment by btopro** [comment]
not seeing timeouts, even on large imports we're doing now for DMD

**Comment by btopro** [comment]
This might be required to use APDQC with git book. ugh. shouldn't be hard to do though. We need to save, then do a redirect over to another page that does the batch api import of the rest of the nodes. Right now it starts to save node 1 then imports the rest. This can cause some race condition issues of associating to things that APDQC wants to rip into the background

**Comment by btopro** [comment]
500 error on import when disabling APDQC yet having lock and the rest on. If we go to the home page after import instead of the node itself, then it's fine. Could be related to the other markdown based issue we discovered as it related to course context but I doubt it

**Comment by btopro** [comment]
original apdqc blocking issue for this NOT importing has been resolved
