### ISSUE TITLE
Markdown Filter needs proper permissions

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1322]
For now I added 
- staff
- administrator 

to https://courses.aanda.psu.edu/dmd100/admin/config/content/formats/git_book_markdown

i bet there is a script though that adds in the right perms for this.

**Comment by btopro** [comment]
Try enabling mooc_markdown module. I believe this happens if you do things via the commandline but checking now

**Comment by btopro** [comment]
these permissions should be good when doing things out of the box. Now taht you have that importer working I made it the default under the hood for when things get setup.
