### ISSUE TITLE
Demo site says access denied

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1327]
I'm new to ELMSLN and want to try the demo. I logged in at http://online.do1.demos.elmsln.org/ with "staff" but got "Access Denied". Could you please allow the demo account to access a sample course? That will be very helpful! Thanks

**Comment by btopro** [comment]
I was just able to login with staff/staff
could you try again?

**Comment by lizatgit** [comment]
I can access the site now. Thanks a lot for the quick fix!
