### ISSUE TITLE
Zip file support in Interact

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1328]
I think I thought it was possible to upload a zip file (such as a published Captivate, or Adobe Animate package) to Interact and then embed it within the course outline.

I thought I'd just give it a try on the demo site now but it's saying that uploading a zip file isn't possible:
![image](https://cloud.githubusercontent.com/assets/4973810/19315864/4965fcee-9097-11e6-87fe-3ce9bf44bdca.png)

**Comment by btopro** [comment]
is the path this -- file/add/upload/archive

**Comment by btopro** [comment]
it's working local at least, demo I may have disabled it thorugh other methods for security but it does work

**Comment by rickhumphries** [comment]
Ok nice one. Thanks for looking
