### ISSUE TITLE
Add in the news area to elmsln.org

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1335]
For when things like this happen -- http://www.thedrum.com/news/2016/09/15/buttercups-and-orange-bus-create-online-learning-platform-pharmacy-students

reused / modified for part of their own press release at OB http://orangebus.co.uk/work/buttercups-training-elearning

**Comment by btopro** [comment]
@rickhumphries --^

**Comment by rickhumphries** [comment]
@btopro nice, they finally released it. Shame about the out of date screenshot!

**Comment by btopro** [comment]
https://www.elmsln.org/news
