### ISSUE TITLE
don't set a php-fpm specific memory limit in installers

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1337]
@bradallenfisher Cent 7 spin up right now claims it's 128; it should be 256 to be safe, especially in local development. It's mostly the save of massive forms / rebuild opreations where you might need like 170 M (like saving the module form which has to bootstrap a ton of code to be presented / submitted)

**Comment by btopro** [comment]
#1314 this would also help reduce the code loaded during this operation

**Comment by bradallenfisher** [comment]
Made the change https://github.com/elmsln/php56-fpm-centos7-mysql56/blob/master/php/www.conf

I assume that since ubuntu/deb versions don't use this fork that they aren't affected.

**Comment by btopro** [comment]
good to know, thx; realized it was because I had devel on but still haven't seen a PHP timeout error in years so.... good to know it's minor / developer only issue

**Comment by btopro** [comment]
confirmed that fixed it on my environment too so i can keep moving forward

**Comment by bradallenfisher** [comment]
i'm spinning up ubuntu 14 to see what the defaults are for that. If it's low I will bump it up in install script.

**Comment by bradallenfisher** [comment]
ubuntu is 128 by default in the php.ini file. Do we want to sed in the higher value?

**Comment by btopro** [comment]
yes, 256 across the board plz; I want these all effectively mirrors so then there's less variation when we someday to go docker (at which point there will be none)
