### ISSUE TITLE
Research content type

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1357]
Ok. so... crazier idea but really not that hard to do given what we have available to us now.

Thinking out loud, we could make a content type in the courses system called "research question" or something like that. What it takes as input is a composite field association as follows:
- Referenced item - link to whatever it should display
- criteria for displaying (if then statement with fill in the blanks)
  - if (student section, previous page, xapi record exists, xapi score exists) then (load referenced item)

Think rules module but less complicated logic / possibly even human written statement or constrained flexibility. The criteria could spell out what the research question is (more or less) as well as allow branching paths (minor / easy to make ones).
For example, different content based on section (possibly to answer a research hypothesis about outcomes):
`If student->section = 'up100' then display media.whatever/node/25`
`If student->section = 'other200' then display media.whatever/node/100`
Or, branch path content (more complicated / difficult to maintain but would be possible potentially)
`If xapi->verb = 'visited' and xapi->context = 'media.whatever/node/100'  then display courses.whatever/sing100/node/400`
Or, based on geographic location delivering concepts / media / etc specific to the region. For example, if trying to relate to students about architecture in their location, it doesn't make sense to be US based examples if bulk of students are from Japan (hypothetically)
`if student->location != 'US' then display 'art for Tokyo games'`
`if student->location = 'UK' then display 'art from London olympics'`
`if student->location = 'US' then display 'art from Atlanta olympics'`

This type would be embedded in the outline, not sure if it lives in media, cis, courses, or some place else (open to discussion obviously, though it really wouldn't matter where it lived...). It's also potentially interesting to have a portal JUST for conducting / storing / working with research questions. Like research.elmsln.local which would be dedicated to possible if / then types of scenarios which could be added across course contexts. So, we want to see if students have higher scores on a quiz when video A is presented instead of video B. This would be established in research as it could get messy. Then we'd embed this item into the flow of a course.

Criteria matches student A, they see video A, student B sees B and so on. Dono, still thinking about how that would work but wanted to write it down.

**Comment by kat-wehr** [comment]
Wow this is really cool, and I could see it going further... stick with me as I vomit my ideas into text... And this is sort of jumping off the original post and adventuring more into the realm of personalized learning (I think). 

What if you have students who have demonstrated higher ability than others, maybe by getting 100's on quizzes or scoring high on projects, have their content be differentiated based on their demonstrated ability. For example, if student A scored 95-100 on a specific group of content (first three weeks, or the first 5 quizzes, or two projects whatever), they are served up their next unit of content at a higher level. Obviously you'd need instructors who created "extra" or "higher level" stuff to be placed there, but it would be neat and a way to foray into true personalized learning. 

The idea of differentiated based on demonstrated ability is HUGE in K12 also. Just a thought.
