### ISSUE TITLE
xAPI Data Dashboards

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1360]
Some things to consider including: 

Overall interactions per user. Example: Student A interacted with X number of questions out of X total questions in the course so far. 

Timeline of interactions over a semester - line graph that shows the waves from semester start to semester end in order to easily identify where the most access is occurring, could indicate that those are heavy/light weeks in the class and help us do better with balancing workload week by week. 

Video Statistics: How many/what percentage of students played, completed, stopped, skipped videos, also, break out where they stopped watching. Perhaps also be able to say "average drop off occurs at 3:12" or something like that. 

Patterns of access by week: similar to overall course timeline, be able to see when students are completing coursework during the week. Don't know if this would be worthwhile but could yield interesting results if anything out of the ordinary happens. 

Will add more as I think of them.

**Comment by rickhumphries** [comment]
I think stats showing patterns between different content types/media and their outcomes is the most interesting potential aspect of xAPI for me. So to be able to pull out a stat like '70% of learners who watched this video for over 2 mins also achieved over 90% in a particular exam'. Or '80% of learners who commented on this particular discussion also engaged highly with a particular chapter (if we start measuring engagement rating for time spent reading etc.). 

That kind of thing would really help to narrow down the specific value of a learning activity and poor performing activities can be reviewed and enhanced

**Comment by btopro** [comment]
related: #1210

**Comment by btopro** [comment]
some inspiration, http://demo.geekslabs.com/materialize/v3.1/app-widget.html

**Comment by kat-wehr** [comment]
Those are fantastic

**Comment by btopro** [comment]
@kat-wehr to clarify; they are non-free, incredibly complex, and plentiful. However, they ARE in materialize so we can take inspiration from the ones in there we like and try to emulate them (possible but not uber easy)

**Comment by btopro** [comment]
https://projects.invisionapp.com/share/9K8UP44EZ#/screens

cough

**Comment by btopro** [comment]
covered by #900 and #1542
