### ISSUE TITLE
Optimize global user cache clearing when editing profile.

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1371]
**0.5.x**

**Steps to reproduce the bug**
1. Edit User
2. Save User

**We should try to reduce the number of calls needed by updating the pin prick API**
Essentially we have to make 2 calls to _cis_connector_request(); at the moment in order to get the entity id that will be cleared.

**Comment by btopro** [comment]
So in reviewing we probably only need one call in order to get the right uid since we have the display mode aspect working on lists of items. This would allow querying based on name and rendering that way as well, reducing the need for the round trip

**Comment by btopro** [comment]
The only reason currently to do this is so the cache bin entry gets fragged correctly. We could just modify our cid Co striation to include user name as an alternate way of storing and killing the cid request

**Comment by btopro** [comment]
hmm... thinking about this a little more...
- this is a non-critical event
- it doesn't happen often
- when it does, this really isn't a huge deal as it's following "REST" capabilities.

Instead I'm going to make a todo comment that it could be more performant; really not a big deal scale wise.
