### ISSUE TITLE
Display mode for documents

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1372]
The display mode for documents is sort of overkill. 
<img width="952" alt="screen shot 2016-10-21 at 11 19 10 am" src="https://cloud.githubusercontent.com/assets/15616523/19603779/62a0fdd6-9780-11e6-84ef-4b2b0132634d.png">

Is there a way to just add a link with the icon and the file name (like below)? Am I just missing it? 

<img width="317" alt="screen shot 2016-10-21 at 11 21 07 am" src="https://cloud.githubusercontent.com/assets/15616523/19603811/82257f10-9780-11e6-95f0-d0e97eedaa48.png">

If this display does exist, maybe this could be made more clear in the display options page? 

Edit: By deleting part of the CIS code I was able to make it work the way I wanted but I don't see that as a default option anywhere. Here's the one I used: [ciscode|rev=1|tool=elmsmedia|item=94|entity_type=node]

**Comment by rickhumphries** [comment]
I use the 'file direct link' shortcode option under 'individual field's in the shortcode options dialog to do this

**Comment by rickhumphries** [comment]
Although not 100% sure if the file icon displays through this method

**Comment by kat-wehr** [comment]
Yeah, I mean based on the previews it "looks" like it will always show the title/header associated with the file in addition to the file itself, so if nothing else making one of them that actually looks the way it displays would be helpful as far as user experience goes.

**Comment by btopro** [comment]
umm... yeah it's obviously not supposed to do that ;)

**Comment by btopro** [comment]
fixed broken image and output issue. Now there's a mode called "document" that behaves as expected
