### ISSUE TITLE
Implement views_content_cache in media / interact

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1374]
our asset management solutions should have the same caching granularity as #1256

**Comment by mmilutinovic1313** [comment]
# Media / Interact

- [ ] CIS Authority Courses - Course
- [ ] CIS Section List - Course Section
- [ ] ELMS Media overview (Content)
- [ ] Node results (Content)

**Comment by mmilutinovic1313** [comment]
Good to go pending PR merge into 5x

**Comment by btopro** [comment]
note PR review, some minor changes to make

**Comment by mmilutinovic1313** [comment]
Noted: Added questions to PR comments. Will fix then soon after

**Comment by btopro** [comment]
nice work on the fixes to the PR; looks great
