### ISSUE TITLE
tincanapi patch clean up w/ drupal.org

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1377]
@mmilutinovic1313 I want @proconnor15 to do this so he has a bit of a footprint on drupal.org as well as gets comfortable with the methodology involved with creating patches and submitting them to a project. This would document the changes I've made in the threads on github (closed / already in elmsln).

https://www.drupal.org/node/2821232
https://github.com/elmsln/elmsln/issues/1375

https://www.drupal.org/node/2821235
https://github.com/elmsln/elmsln/issues/1375

https://www.drupal.org/node/2589945 / #1292

**Comment by mmilutinovic1313** [comment]
Sounds good @proconnor15 let me know if you need help patching!

**Comment by proconnor15** [comment]
We uploaded that patch to https://www.drupal.org/node/2821232. Is that good, or should it be uploaded for all the issues?

**Comment by proconnor15** [comment]
@btopro

**Comment by btopro** [comment]
@proconnor15 it's in the wrong issue queue. see which it should be posted to; then include the patch local to the repo and do a pull request against elmsln. This would go in the tincanapi module directory so that we've got it documented. thanks!

**Comment by mmilutinovic1313** [comment]
@proconnor15 - let me know if you have any other questions with this patch.

**Comment by btopro** [comment]
@mmilutinovic1313 how bout you clear it up; mostly involves posting it to the correct issue queue on d.o. (its up, good patch but wrong place) and then doing a PR to elmsln placing the patch in the right location (w/ the tincanAPI project)

**Comment by btopro** [comment]
@mmilutinovic1313 you should also redo the patch in case there have been changes since it was pushed up (I think there might have been)

**Comment by mmilutinovic1313** [comment]
I see the patch that was in the wrong place has been re-uploaded to https://www.drupal.org/node/2821235. 

As far as the other patch goes, I'll add the patch mentioned in https://www.drupal.org/node/2589945 to that the d.o. issue as well.

Let me know if I am wrong about this task at all. Should only take a few minutes to finish.

**Comment by btopro** [comment]
nope you've got it

**Comment by mmilutinovic1313** [comment]
PR submitted - repatched and resubmitted first patch to d.o. as there were changes to the codebase.
