### ISSUE TITLE
do a textbook rewrite for #1387 to have template plugin local

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1388]
Right now we hacked CKeditor (technically) from the source taken from ckeditor.com. This will get overwritten the next time we update. Instead of patching it I think there's a way to modify the registry of these plugins. If not, well, we'll just document it.

**Comment by btopro** [comment]
@mmilutinovic1313 could be a good change of pace; involves digging into ckeditor and it's integration w/ the wysiwyg API to see if there's a way to remap a plugin. Or, if we should just fork the plugin and implement it via these APIs.

**Comment by mmilutinovic1313** [comment]
I'm gonna tag #1222 in here too as since CKEditor was hacked in - that could be messing with adding that plugin.

**Comment by btopro** [comment]
just added a file saying the three plugins we changed
