### ISSUE TITLE
Multi-field field

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1393]
We need a multi-field thing in order to do #1251 correctly without a ton of issues with our data model and performance / usability.

Project could use this for it's phases to eliminate 1 level of the hierarchy at least

**Comment by bradallenfisher** [comment]
http://loopduplicate.com/content/drupal-create-custom-compound-field-types

For my reference.

**Comment by btopro** [comment]
@bradallenfisher like you said, facepalm level easy. Ok, this might be exactly what we're looking for

**Comment by bradallenfisher** [comment]
@btopro do we want this type of functionality in it's own module? should it be part of the studio distribution?

**Comment by btopro** [comment]
both are correct. let's map it out a bit tomorrow if there's time

**Comment by btopro** [comment]
merged into #1251

**Comment by btopro** [comment]
this is a bigger piece of the data model. @bradallenfisher could you help get me in the right direction with this or if you want to do this piece to get your head out of sys-ops for a little bit

**Comment by bradallenfisher** [comment]
I had started to work in the cle_assignment.module... not sure where @heyMP thinks this fits now though. I never pushed/sort of started over due to entity reference.

My thoughts were that we just needed a multi-value field to be added to cle_assignment.module

**Comment by btopro** [comment]
ok, can you start on this as it's own module then that's scope is to provide this specialized field which we can then assign to the assignment? It's complex enough that I think it should be its own thing even tho we'll hook it in / it'll be required by cle_assignment

**Comment by bradallenfisher** [comment]
Yeah. that's actually better in my mind. meant to bring it up regarding merge issues.  👍

**Comment by btopro** [comment]
@bradallenfisher ignore this issue, @heyMP and I talked and as we're hashing it out I think this is WAY too complicated an approach. Will sleep on it but I think a data-blob would be just fine given that potter has the App doing all the project and assignment creation process.

https://www.drupal.org/project/blob

which later we could convert to

https://www.drupal.org/project/jsonb
