### ISSUE TITLE
gitbook imported images and internal links broken

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1399]
The images issue should be easy to fix since that was working before. We'll need to decide what we want to do about internal gitbook as they do not get converted.

https://courses.aanda.psu.edu/dmd100/node/863

**Comment by btopro** [comment]
@bradallenfisher VERY similar to the way you solved the link rewriting in book duplication

**Comment by bradallenfisher** [comment]
the links never worked if I recall. The images did. Is there something different you recently did when adding the images?

**Comment by btopro** [comment]
issue is things like this:
```
![](plot_diagram_reverse2.png)
```

Will need to become something like this (not correct but general idea)
```
![](/dmd100/system/files/dmd-course-materials/plot_diagram_reverse2.png)
```

**Comment by btopro** [comment]
This may need to be an enhancement to the git_book_gb plugin to comb through after the markdown parser has run and forcibly modify the source to point to the right places. Otherwise we'll need to forcibly correct the markdown on import which isn't ideal

**Comment by michael-collins** [comment]
We talked about internal hyperlinking to other Gitbook pages also being a problem. Is it possible to convert those links, or should I not use them at all? I've just been reducing the amount of internal linking between pages.

**Comment by btopro** [comment]
like pages in the same book? We'd have to rewrite them in a fashion similar to the other outline duplication links problem that brad / potter figured out previously (same problem different criteria). Working on some other git book stuff now, we'll see if I get this too

**Comment by michael-collins** [comment]
Yup, exactly. I often want to refer to other topics.

**Comment by btopro** [comment]
commit resolves internal references at least (tho ...'s may still bust we'll see). by setting the node's path alias to the name of the file path. this fixed several in testing automatically. next, images

**Comment by btopro** [comment]
- [ ] fix internal image / file links
- [ ] see why some links come up w/ path alias of 'null' as the actual word
