### ISSUE TITLE
Gitbook import titles are doubled

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1400]
We need to show just the title printed on the gitbook page, not the title autogenerated by ELMSLN. Or, we can come up with a way to wrap some template language around the title in gitbook .md so elmsln knows to not print it to the page after being imported. We'll need a gitbook plugin to accomplish that.

**Comment by btopro** [comment]
known issue but thx for creating a stub for it

**Comment by michael-collins** [comment]
Actually, I think if we just adopt OER Schema in ELMSLN (for which the plugin is already enabled in gitbook.com), we can use that schema to describe the titles, and then account for it in ELMSLN. No plugin needed.

**Comment by btopro** [comment]
"just adopt {insert completely influx specification here}" ;)

**Comment by michael-collins** [comment]
Let's ask the spec writer. Hey, @curiosity26 can you chime in. Is this a good/bad idea?

**Comment by btopro** [comment]
I was just going to tell @bradallenfisher to hide the title in page.tpl if we are viewing a page that's part of a git book; this isn't specific to your spec, all markdown pages / files have this convention from what i've seen

**Comment by curiosity26** [comment]
Yea gotta keep this in the purview of GitBook.

**Comment by michael-collins** [comment]
Ah okay. That's easy.

**Comment by btopro** [comment]
going to be stuck with @michael-collins for a long car ride so I'm assuming this will suddenly make its way into the 050 release ;)
