### ISSUE TITLE
Gitbook ingestion enhancements

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1401]
update from original thread:
- [x] Trace git book deletion cache_menu issue #1541
- [x] APDQC rebuild thing #1320
- [x] add ability to pull / resync elmsln content from the gitbook itself; this pulls code on the server for the branch then rebuilds the hierarchy / page content to match (with option to delete all and rebuild)
- [x] notify when making a change that it's out of sync with the repo on github
- [x] ability to push back to github (assumes ssh key and/or login creds be entered at that time to do so)

original thread below:

The main goal is to maintain the integrity of the content no matter where it's published, and to enable content modification. ELMSLN and gitbook.com are the two publishing platforms we want to get syncing initially. Perhaps a new platform will emerge that is better, but those are the two we have available to us now. When published, we shouldn't see code from either system show up in rendered content. What are some workflow considerations that can make this easier?

**Initial questions:**
1. Could HAX have an OER Schema selector when editing content? Otherwise, would the WYSIWYG need an editor plugin for OER Schema?
2. What ELMSLN would make sense to sync back to gitbook?

**Comment by btopro** [comment]
so your going to make markdown that has layout implications which you then want to interpret on our side of the house bc of superior render capabilities of html over markdown?

So you want markdown to be html, correct? ;)

**Comment by michael-collins** [comment]
I don't know. Trying to figure it out via this conversation. Are you saying that syncing after import is not possible for this reason? Or are you saying that a sync from and edit in ELMSLN would strip out layout implications?

**Comment by btopro** [comment]
Markdown has no layout implications. If you don't care about that then it's fine I guess. If it is under any situation, your screwed.

Push back from elmsln to git report more an ssh key issue rather then impossibility. However, import probably should be thought of as forking since if changes are made inside they r with a far more powerful editor

**Comment by michael-collins** [comment]
I definitely understand the implications. The problem with a total fork of the content is that it's only editable on ELMS. All future courses would be cloned from that fork, and changes would never see a git repo again. I would be very sad. I don't really care about editing the layout, the css does a  good job out of the box, and major layout problems could hopefully be solved with styling the default html output from the markdown. I'm really interested in keeping the content in motion.

Adjusting the content editing workflow to accommodate that is my priority. I think media is the major issue. Without media, it seems fairly simple. With media, there are CIS shortcodes and things. Can we export an elms-config file of some kind to keep in the repo that would make reimporting changes/media/whatever possible? Or just deal with the fact that shortcodes appear? Or, maybe I can figure out how to make a plugin that renders media pleaceholder images for shortcodes on gitbook so we can keep them in the md. Md supports html, so I'm thinking that could work...

**Comment by btopro** [comment]
we have stuff (untested) that will rip back to the local repo in same format. This worked in the read the docs stuff so the capability is there. but again, it'll come down to where does media live, especially when getting into stuff the unit produces vs stuff that lives in public places, as well as shortcode workflow embed methodology with studio / etc. The shortcodes can be passed into markdown (if we fix that issue) and then rendered locally, saving back to the repo for consistency of the repo / version.

Laying out the context of what's possible. smeal has discussed previously a workflow where "books" live in a different repo internally (LOR) and then courses are built out of forks of those (basically) but that stuff is way off the reservation from reality

**Comment by michael-collins** [comment]
Ah. Yeah, simplicity is key for now. Is there an open an issue for fixing the shortcode to markdown feature? If not, we should open one. This seems like the path of least resistance for now.

**Comment by btopro** [comment]
I won't utilize the quote that you know is in my head right now, but the ability to fork and export the material is the goal, not that there is a singular version of individual characters that are forever the same. This isn't possible in code so I wouldn't expect it to be true in text.
MD supporting HTML would mean this is a non-issue but then anything imported into a CMS would convert it into HTML basically which MD may or may not choose to keep

**Comment by btopro** [comment]
you can open one if u can't find one. Plugin was around importing only so you might need to live with reality this time around and we can learn from issues on both sides so that future things keep having less and less friction here around how humans use the tech and the reality of VC stuff.

**Comment by btopro** [comment]
OER Schema may need that friction to know what needs added / supported as well.

**Comment by michael-collins** [comment]
I'll open an issue if there isn't one and see what happens.

**Comment by btopro** [comment]
Thus far we're able to support a pull based, all development happens on github / gitbook and then is pushed into elmsln with total content accuracy (horray!). We will however want to add support for like a "pull changes" or something as right now it's a (very manual) delete and rebuild the outline process.

**Comment by btopro** [comment]
@heyMP split this into other issues and did most of it
