### ISSUE TITLE
Make a Base-image for Vagrant based development from Ubuntu 16 image

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1410]
Just like it says, changing this issue from what it was because instead of advancing our current base image might as well see how far we can get on this one. instead

**Comment by btopro** [comment]
https://atlas.hashicorp.com/ubuntu/boxes/xenial64

**Comment by bradallenfisher** [comment]
Beat me to this. 😁

**Comment by bradallenfisher** [comment]
so the issue with https://atlas.hashicorp.com/ubuntu/boxes/xenial64 is that at the moment the box doesn't spin up with a vagrant user. It creates an ubuntu user. Other boxes like https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04 aren't booting properly. They fail with config timeout warnings.

I will be watching the progress on this as there are active issues in the packer and vagrant queues.

**Comment by btopro** [comment]
we'll push this back then since there's not much we can do till they fix that stuff

**Comment by bradallenfisher** [comment]
k this works if you have the exact cocktail of vbox and vagrant... not sure if that is okay or not. IF not should we proceed with RHEL7 so we can start to migrate data and set up the dev/stage/media servers?

**Comment by bradallenfisher** [comment]
This issue explains it all https://github.com/chef/bento/issues/688

Do we want to introduce this type of version locking just so we can have http2. 

Technically we could build and make apache from scratch to use an "unsupported" version of it that supports http/2.0. Rhel won't "support" it but they already don't support most of our stack.

Testing on blank 7s to see how much is involved.

**Comment by bradallenfisher** [comment]
Thats' correct. It's only an issue of not having local dev in sync with our live environments.

**Comment by bradallenfisher** [comment]
so I have this working now... not sure how you want to proceed. If you checkout my 0.7.x branch and run vagrant up it works.

**Comment by btopro** [comment]
can you tell me if this page lets you upload a zip file:

```
http://interact.elmsln.local/file/add/upload/archive
```

In my VM on cent7 it does have zip but on ubuntu16 deploy it doesn't. Not sure if its because of zip being available or not

**Comment by bradallenfisher** [comment]
Needs unzip installed. Will do that after lunch.

**Comment by bradallenfisher** [comment]
unzip is already installed. I will investigate this further.

**Comment by bradallenfisher** [comment]
it did not allow me to upload a zip file

**Comment by bradallenfisher** [comment]
sudo apt-get install php7.0-zip

**Comment by bradallenfisher** [comment]
will add to script
