### ISSUE TITLE
Support Ubuntu16 (as best we can)

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1416]
U16 is the latest and greatest from ubuntu. It comes with PHP 7, apache 2.4 w/ simple http2 support and maria 10 support without complex repo gathering. In other words, it can be made insanely fast with minimal effort. @bradallenfisher has been doing an awesome job experimenting with this recently and almost has it working. This would be a game changer for performance on top of how insanely fast 0.5.x is compared to previous versions because of front-end changes; this would be the same but for backend changes.

**Comment by btopro** [comment]
closing but related #1351

**Comment by btopro** [comment]
related: #998

**Comment by bradallenfisher** [comment]
- [ ] mysql/mariadb conf tests
- [ ] opcache test
- [ ] crontab test

spinning up stable at the moment. running builds until nothing fails.

**Comment by btopro** [comment]
damn.
