### ISSUE TITLE
Latest UX not showing as responsive on mobile

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1417]
The example here: https://drupal.psu.edu/library/node/20

Viewing this on my mobile (Chrome Mobile 54), the site doesn't appear in the responsive form. Instead, the site is reduced in size

![image](https://cloud.githubusercontent.com/assets/4973810/19801192/12364dee-9cf6-11e6-8dc8-91787fc75958.png)

I wasn't sure if it was just my phone though, so I ran it through the Google mobile friendly test, but it's reviewed it as 'not mobile-friendly'

https://www.google.com/webmasters/tools/mobile-friendly/?url=https%3A%2F%2Fdrupal.psu.edu%2Flibrary%2Fnode%2F21

**Comment by btopro** [comment]
good catch; did some investigation; try now as it's working across a few phones I tested. works REALLY well in chrome, even takes on the color of the system your in and if you pin the page to your desktop it'll treat it like an app with a loading screen and removing the browser bar :)

**Comment by rickhumphries** [comment]
Very nice :) especially love the colour inheritance thing
