### ISSUE TITLE
CiviCRM

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1418]
Just came across this today so thought I'd bring it up as a possible option to build off or use as a comprehensive CRM solution if it was required

https://www.drupal.org/project/civicrm

**Comment by btopro** [comment]
Yeah. Comprehensive is the key phrase. I don't that we want to tread into full on inclusion of this stuff. Might be a nice thing to account for ifbsomeone ends up deploying on their own and integrating with.
