### ISSUE TITLE
Zurb Foundation in v0.5.0

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1419]
Hi - I'm just wanting to get an idea of whether the Foundation styling is still accessible from the release to come (0.5.0). Particularly in Courses/MOOC, as we use quite a few of the classes to arrange our content within the wysiwyg. Particularly the grid, tabs, modals, and some utility classes off the top of my head. I know that MaterializeCSS is being used in general now, so just wanted to get an idea of what will still be there, and the future plans for it. Thanks

**Comment by btopro** [comment]
Since i know you guys are working towards 4 atm it's all still in there, the two are loaded together. 5 the grid classes technically should still be in there / work but I know the JS elements won't load without something invoking / adding in the zurb library / running:

Should be as easy as ensuring the css/js is loaded and that the js is invoked like this:
```
<script>
      $(document).foundation();
    </script>
```

**Comment by btopro** [comment]
@rickhumphries probably 15 minutes of customization on vendor's part to ensure both those load back in once you get there.  Yet another good reason we broke CIS 1.x / your marketing site off from the rest :)

**Comment by btopro** [comment]
- [ ] We'll make a module that re-enables support for zurb for backwards compatibility

**Comment by btopro** [comment]
It won't be on by default

**Comment by rickhumphries** [comment]
thanks @btopro sounds good. We're working towards 0.4 at the moment, but half tempted to jump straight to 0.5...

**Comment by btopro** [comment]
I'm hoping to release next week; depends on how much I can get cleaned up this weekend and additional testing Monday. Hoping to roll out internally in another 2 weeks (need more mirror'ed testing internally to ensure it plays nice w/ some of our custom integration projects but early signs are that it's fine)

**Comment by btopro** [comment]
this can be enabled now via adding the following to the shared_settings.php file

`$conf['foundation_access_legacy'] = TRUE;`

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln-config-example/commit/dfec9e997db5a8a33c184817f5b400095de6b1ca reflected in our example config that's kicked out now too
