### ISSUE TITLE
Host end-user documentation via elmsln.org off of elmsln courses

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1425]
#1296 our ELMS help agent / system could be tied off of elmsln.org so it's more of a living, breathing thing. As tutorials / documentation for end users gets updated, it is reflected in the sites itself. We could also put in a way for people to suggest changes.

This content could automatically be updated based on accepted git pulls, using a gitbook / similar content structuring to auto push from the repo to our elmsln site. #692 #1263

**Comment by btopro** [comment]
@kat-wehr thoughts on us using the system to build a course about how to use the system / what different concepts mean, etc? Then making little (?) icons or whatever throughout the system that when clicked pop up the references to how to do / use / extend whatever the thing is? Might also be nice to have things per role at some level, like relevent things per staff and per faculty. Generally faculty won't care about sustainability / institutional scale for example, where a staff member might be very interested in the reuse / remixing of components bc of long term viability / less maintenance after launches.

**Comment by kat-wehr** [comment]
Yes, this is great. I can build writing some of these tips into the workflow as I add new material for spring.

**Comment by btopro** [comment]
Related: #1623 could live there as well as all our end user docs so it would be a living example of the platform as well as cool visual things you can easily build with it.

**Comment by btopro** [comment]
#1855 can at least help w/ styled definitions / #1623 aspect of documentation

**Comment by btopro** [comment]
https://github.com/elmsln/documentation/
https://btopro.gitbooks.io/elmsln-documentation/content/
