### ISSUE TITLE
Suggestion: Marking or Notification System for when to run leafy

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1427]
I was thinking perhaps we could have a tag or way of notifying developers on the project when we should run an `upgrade the ELMSLN code base and system` leafy command. For example, if there are update hooks that need to be fired from a prior commit. Maybe this could be a Slack integration where a channel sends a message that the system should be upgraded for users at ___ commit and prior.

**Comment by btopro** [comment]
could display this in the admin status page I guess. We do this under the hood if you run leafy but yeah a way of notifying that the versions are out of date / copy and paste commands to run would be a good idea.

**Comment by btopro** [comment]
```
$requirements['elmsln_version']['severity'] = REQUIREMENT_WARNING;
        $requirements['elmsln_version']['description'] = $t('Code: @code<br/>Configuration: @config<br/>Your code base is newer then the configuration that\'s been applied to the server. To fix this, log into your server and type `leafy`. Then select the option of applying server / bash level upgrades. You don\'t HAVE to apply these but we just want you to know you are out of sync with the changes that we recommend for the platform and are reflected in newer deployments.', array('@code' => $code, '@config' => $config));
```

in looking at cis_connector we already have this for config version differing from code on system version, pushing up minor changes to reflect the request
