### ISSUE TITLE
create patch against leaflet / leaflet widget

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1436]
follow up from #479

There were a few changes made to leaflet and leaflet_widget modules to clean up the integration with ICOR. I think they are essential to making leaflet_widget usable in general since it resolves some conflicts w/ the latest version of leaflet.

@mmilutinovic1313 like the last patch related issue shadow @proconnor15 so he can get some more practice doing this / getting contributions back out there. PR back to our Repo when done for documentation purposes.

these live in `/var/www/elmsln/core/dslmcode/stacks/interact/site/all/modules/local_contrib`

**Comment by mmilutinovic1313** [comment]
@btopro is @proconnor15 putting this patch as an issue on the leaflet drupal project?

**Comment by btopro** [comment]
yes sir

**Comment by btopro** [comment]
and leaflet_widget
they are 2 different things

**Comment by proconnor15** [comment]
Submitted the patches on drupal and submitted PR.
https://www.drupal.org/node/2828094
https://www.drupal.org/node/2828085

**Comment by proconnor15** [comment]
@btopro

**Comment by btopro** [comment]
Excellent, these are exactly what they should be. Now put the patches in the related project folders and submit a PR here (not seeing the PR even though you said there is one)
