### ISSUE TITLE
Install HTTP/2.0 on Rhel Based system

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1443]
- [ ] Get apache 2.4.17+ 
- [ ] Download the latest version of OpenSSL 
  - Need OPEN SSL 1.0.2 min

### Prereqs
```shell
yum install gcc wget apr-devel apr-util-devel -y
```
### Install Open SSL
```shell
cd /usr/src
wget https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz
tar -zxf openssl-1.0.2-latest.tar.gz
```
### Manually compile OpenSSL and install/upgrade OpenSSL, do as follows:
```shell
cd openssl-1.0.2a
./config
make
make test
make install
```

### Install Apache. 
- Download the latest release from http://httpd.apache.org/download.cgi
- Extract	
``` shell
gzip -d httpd-NN.tar.gz
tar xvf httpd-NN.tar
cd httpd-NN
```
- Configure	
```shell
./configure --enable-http --enable-http2 --with-nghttp2=/usr/lib64 --enable-ssl --enable-so
make
make install
```

Will update this as it progresses.

**Comment by btopro** [comment]
is this for documentation purposes or are you going to add this to the install routines?

**Comment by bradallenfisher** [comment]
both. once in place this will just be an issue.

**Comment by bradallenfisher** [comment]
However, at this point it may not come to fruition, it is still in testing phase.

**Comment by bradallenfisher** [comment]
not even an option... for it will be WAY to crazy to maintain. 👎
