### ISSUE TITLE
OSX Sierra Virtual Box Warning

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1444]
Just wanted to make everyone aware, but virtual box throws this error message when running `vagrant up` on Sierra. Doesn't seem to have any problems when the command is run again. But I wanted to document this just in case other users have a similar issue.

## Error Message

> failed MSpanList_Insert 0x1e3000 0x17e448cb1e3b 0x0
fatal error: MSpanList_Insert
runtime stack:
runtime.throw(0x19816b)
	/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:491 +0xad fp=0x7fff5fbff710 sp=0x7fff5fbff6e0
runtime.MSpanList_Insert(0x1b3988, 0x1e3000)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mheap.c:692 +0x8f fp=0x7fff5fbff738 sp=0x7fff5fbff710
MHeap_FreeSpanLocked(0x1b0580, 0x1e3000, 0x100)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mheap.c:583 +0x163 fp=0x7fff5fbff778 sp=0x7fff5fbff738
MHeap_Grow(0x1b0580, 0x8, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7fff5fbff7b8 sp=0x7fff5fbff778
MHeap_AllocSpanLocked(0x1b0580, 0x1, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mheap.c:298 +0x365 fp=0x7fff5fbff7f8 sp=0x7fff5fbff7b8
mheap_alloc(0x1b0580, 0x1, 0x12, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mheap.c:190 +0x121 fp=0x7fff5fbff820 sp=0x7fff5fbff7f8
runtime.MHeap_Alloc(0x1b0580, 0x1, 0x10000000012, 0x10d39)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mheap.c:240 +0x66 fp=0x7fff5fbff858 sp=0x7fff5fbff820
MCentral_Grow(0x1b82f8, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mcentral.c:197 +0x8b fp=0x7fff5fbff8c0 sp=0x7fff5fbff858
runtime.MCentral_CacheSpan(0x1b82f8, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mcentral.c:85 +0x167 fp=0x7fff5fbff8f8 sp=0x7fff5fbff8c0
runtime.MCache_Refill(0x1df000, 0x12, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/mcache.c:90 +0xa0 fp=0x7fff5fbff920 sp=0x7fff5fbff8f8
runtime.mcacheRefill_m()
	/Users/mitchellh/code/3rdparty/go/src/runtime/malloc.c:368 +0x57 fp=0x7fff5fbff940 sp=0x7fff5fbff920
runtime.onM(0x13d650)
	/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7fff5fbff948 sp=0x7fff5fbff940
runtime.mallocgc(0x120, 0xff4a0, 0x0, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/malloc.go:178 +0x849 fp=0x7fff5fbff9f8 sp=0x7fff5fbff948
runtime.newobject(0xff4a0, 0x1df000)
	/Users/mitchellh/code/3rdparty/go/src/runtime/malloc.go:353 +0x49 fp=0x7fff5fbffa20 sp=0x7fff5fbff9f8
runtime.newG(0x2520a)
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.go:233 +0x2a fp=0x7fff5fbffa38 sp=0x7fff5fbffa20
allocg(0x1a33e0)
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.c:925 +0x1f fp=0x7fff5fbffa48 sp=0x7fff5fbffa38
runtime.malg(0x8000, 0x1a3480)
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.c:2106 +0x1f fp=0x7fff5fbffa78 sp=0x7fff5fbffa48
runtime.mpreinit(0x1a3840)
	/Users/mitchellh/code/3rdparty/go/src/runtime/os_darwin.c:137 +0x27 fp=0x7fff5fbffa90 sp=0x7fff5fbffa78
mcommoninit(0x1a3840)
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.c:201 +0xc9 fp=0x7fff5fbffab8 sp=0x7fff5fbffa90
runtime.schedinit()
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.c:138 +0x55 fp=0x7fff5fbffae0 sp=0x7fff5fbffab8
runtime.rt0_go(0x7fff5fbffb10, 0x2, 0x7fff5fbffb10, 0x0, 0x2, 0x7fff5fbffc40, 0x7fff5fbffc48, 0x0, 0x7fff5fbffc4b, 0x7fff5fbffc62, ...)
	/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffae8 sp=0x7fff5fbffae0

**Comment by mmilutinovic1313** [comment]
Guest Additions Version: 4.3.13
VirtualBox Version: 5.0

**Comment by btopro** [comment]
wierd; what versions of Vagrant?

**Comment by btopro** [comment]
Closing either way since it works, but I agree @mmilutinovic1313 good to know it's a thing

**Comment by mmilutinovic1313** [comment]
Updating for future reference: 
Vagrant 1.7.4

**Comment by btopro** [comment]
oh, upgrade vagrant that's way old now :)
