### ISSUE TITLE
Dropdowns don't work in Firefox

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1445]
**Version**
0.5.x

**Steps to reproduce the bug**
1. open online.elmsln.dev in firefox
2. log in
3. click on "Network" or "admin" or any menu item

**Expected behaviour**
Submenu should be displayed because the dropdown/modal are expanded.

**Actual behaviour**
Submenu is not expanded or displayed in Firefox 45.0.1. They work fine in Safari/Chrome/IE.

**Additional information**
OS: Windows 7
Browser: Firefox 45.0.1

**Comment by btopro** [comment]
@lizatgit could you take a screenshot? I was just messing w/ modals / dropdowns today / this week

**Comment by btopro** [comment]
some other stuff goofed up but these are working, may want to try rebuilding the caches on that site, it might flush css/js / have been a temporary error while I was doing work against those items; I'll leave open for now

**Comment by lizatgit** [comment]
Here's a screenshot. The buttons in red circles do not respond when clicked in Firfox but they work fine in other browsers. I've cleared cache.
![capture](https://cloud.githubusercontent.com/assets/5192319/20060045/43df8ff8-a4c7-11e6-849d-5072d8a8d0bf.JPG)

**Comment by btopro** [comment]
hmm... do you have the latest 0.5.x? also go into terminal and run `drush @online cc all --y` and see if that fixes it; there are some minor nagging JS errors (look in console if you could) after initial build at times right now

**Comment by lizatgit** [comment]
I did cc but it stays the same. 
I think it might be related to voice command. The modal/drodown works fine while logged out, but once I logged in they stopped working. The js console message shows a voice command error.
![capture](https://cloud.githubusercontent.com/assets/5192319/20062036/30e19b7c-a4d0-11e6-9ac6-e4f5e8051547.JPG)

**Comment by btopro** [comment]
blarg ok i see it looking deeper

**Comment by btopro** [comment]
ok, it's fixed now; I believe it's related to older version of firefox / versions that don't actually support speech synthesis
