### ISSUE TITLE
Add better banner

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1451]
@rickhumphries has a sweet banner he uses in courses that I think would make a cool starting point for all new courses. We need the source files to do it right though.

**Comment by rickhumphries** [comment]
@btopro just getting the photoshop file together. Do you want me to do a pull request against the location of the last commit and drop in there?

**Comment by btopro** [comment]
umm... can you fork and do a PR against https://github.com/elmsln/elmsln-logos that's where we put raw assets. I want to tweak it a bit to replace the one I have up currently

**Comment by rickhumphries** [comment]
Sure no problem. I'll sort tomorrow now cause didn't get sent the file in the end

**Comment by rickhumphries** [comment]
PR done

**Comment by btopro** [comment]
awesome! ty
