### ISSUE TITLE
Rip Aliases to an actual file 

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1462]
I suggest that we create rip all existing sites to an actual alias file on site creation. This way we can sync this file downstream as well as save drush some effort on each call. It will also make it easier to split up which aliases are available on which server. 

We could attach a script to the drush create site command that upon site creation the alias file gets blown away and regenerated based on new directory structure.

**Comment by btopro** [comment]
I think you're over thinking the problem this solves but I agree, these could just be rebuilt when there's a new space made.

**Comment by btopro** [comment]
related #1454

**Comment by btopro** [comment]
I think the new environments capabilities make this moot
