### ISSUE TITLE
Add all domains to sites.php

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1463]
Similar to #1462 we could add this to the drush create site routine so that all domains we support get added to the $sites array.

**Comment by bradallenfisher** [comment]
basically we could use the contents of this directory
/var/www/elmsln/core/dslmcode/stacks/courses/sites/courses/aa

to delete and re-create the sites.php file each time a site is built.

**Comment by btopro** [comment]
is this much different from appending to the bottom of the file each build?

Also, while we're at it, wouldn't it make even more sense for neither of these + the settings files to not include a hard coded base URL but something that reads of an environment file / whatever which tells it what the address is. Like variable-ize it?

**Comment by btopro** [comment]
related #1454

**Comment by btopro** [comment]
I believe this is now fixed if  you see the way new sites.php files are created
