### ISSUE TITLE
central course list w/ quick links

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#147]
We'll need to clean it up later but for now we at least need shortcuts to get to everything for internal staff working on the courses in a portfolio. Right now you go tot he course list in CIS, click a course, then slide out the snowflake or hit edit tab and go to services; way too many steps as those are both good alternative ways of getting there but not if I just want to get to the course as quickly as possible from a working perspective.

**Comment by michael-collins** [comment]
I designed an interface for this in the ux channel on slack.

**Comment by btopro** [comment]
Ahh yes, can you post that here for open suggestions; for now I'll just add a link that generates the right path, obviously what you've done is more comprehensive and amazing :)

**Comment by michael-collins** [comment]
@btopro Let's just be careful with this, I know how "bandaids" can stick around for years...

https://files.slack.com/files-pri/T02F8NY7Y-F06NCLURK/screen_shot_2015-06-23_at_4.17.46_pm.png

https://files.slack.com/files-pri/T02F8NY7Y-F06NCED24/screen_shot_2015-06-23_at_4.17.34_pm.png

https://files.slack.com/files-pri/T02F8NY7Y-F06NCEC7J/screen_shot_2015-06-23_at_4.17.22_pm.png

https://files.slack.com/files-pri/T02F8NY7Y-F06NCEBDE/screen_shot_2015-06-23_at_4.17.02_pm.png

**Comment by btopro** [comment]
these files wont exist cause its slack. we need a repo for just interface mock ups that you can reference

**Comment by btopro** [comment]
original issue not as direction taken; CIS UX is its own thing (and obviously still needs implemented)
