### ISSUE TITLE
Assignment Studio-Display of Code and Image/Working Code

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1474]
Would it be possible for students to submit code to the assignment studio, and be able to see how that code works?  I am thinking about a split screen, code on one side, and the working code on the other.

**Comment by btopro** [comment]
http://codepen.io/ and embedding code pens is probably the best solution to this. If people could embed code pens easily (or something like it) then that'd probably meet this need without being impossible to accomplish

**Comment by btopro** [comment]
definitely the best way. Also helps them build an online identity as a developer which is something we could push across the program via tutorial units on how to make a github account, codepen account, etc. Projection of online identity is important.

also, there's a super easy "embed" button right on codepen.

![2016-11-30_01-41-47](https://cloud.githubusercontent.com/assets/329735/20742485/5145755c-b69e-11e6-9283-77df12385025.png)
