### ISSUE TITLE
Auth.elmsln.local / auth domain

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1475]
If we abstracted authentication to a singular domain / address, everyone could redirect over to it when there's an access denied. This would then ship off to elmsln's universe using Bakery to broker the connection once your inside our universe.

This would make the intergration w/ external authentication systems so much easier (like webaccess) @bradallenfisher .

**Comment by btopro** [comment]
@curiosity26 could we get together sometime in the near future for coffee and just hash this out. We're thinking this will be something higher in priority to clear up issues we've been having in QA / in general w/ webaccess. If we have 1 point of webaccess integration that'll make our lives a lot easier (obviously :)).

**Comment by curiosity26** [comment]
Yea! How about laster this week? I'll hit you up on slack. I'll be at the coffee session tomorrow, too.

**Comment by btopro** [comment]
closing as this continues on in #1473
