### ISSUE TITLE
Shop Safety-Quiz Tool

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1476]
I embedded a quiz into the shop safety site, and to view the quiz questions, I have to scroll.  Can the entire question be displayed?

![screen shot 2016-11-16 at 1 03 30 pm](https://cloud.githubusercontent.com/assets/12716869/20359294/3b63e616-abfd-11e6-8ebd-8faf66f5d7be.png)

**Comment by btopro** [comment]
This shouldn't be an issue once we upgrade, I'll leave open till then

**Comment by btopro** [comment]
this should now be fixed in the course; let me know if not
