### ISSUE TITLE
Error notices on Course Outline

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1479]
Bug:
- version 0.5.0

Getting fairly consistent error notices when accessing a course outline:

![image](https://cloud.githubusercontent.com/assets/4973810/20413257/d8e2ab12-ad23-11e6-92ed-991864a84025.png)

**Comment by btopro** [comment]
I believe this is related to data being requested of CIS from anywhere else. I'll have to hop on and take a look but it should be pretty minor
