### ISSUE TITLE
Add/Edit Network Option Removed

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1480]
Bug:
- 0.5.0

Ability to add/edit custom links to Network flyout has been removed:

Previously:
![image](https://cloud.githubusercontent.com/assets/4973810/20428467/35a3f84e-ad81-11e6-929e-b49c66824a89.png)

0.5.0:
![image](https://cloud.githubusercontent.com/assets/4973810/20428619/04121f30-ad82-11e6-9545-e6a5f95904c4.png)

**Comment by btopro** [comment]
Ahh forgot we had that link under there when we modd'ed the design. #611 will resolve this (but isn't done yet or it would be in place obviously). This is actually 2 issues; 1 issue is that link being present, another issue is the links displaying (something we also experienced yesterday in testing).
