### ISSUE TITLE
Unable to change banner for CIS and Courses

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1481]
Bug:
- 0.5.0

- The banner in the CIS seems to be applied everywhere globally and I'm unable to change it. The option no longer appears at `cis/course-settings` and it doesn't recongise the change when a custom logo is uploaded at `admin/appearance/settings/cis_foundation_access` 

![image](https://cloud.githubusercontent.com/assets/4973810/20429252/6928b76e-ad85-11e6-943e-6d7767bb7717.png)

**Comment by btopro** [comment]
these switched where they come from under the hood. We just noticed this as well as we're doing similar mirror'ed environment testing. Basically the images you had uploaded are still there but now the theme asks CIS for it's banner; if no banner is supplied there, this is the default.

I'll make an upgrade hook that looks at theme setting and uses that path (if it exists) to copy the file over to the correct location in the file system as if CIS had created it. This won't show up on the course node if you edit it but will have the same effect as being there.

**Comment by btopro** [comment]
fixed; actually will work in the interim w/o server upgrades applied (just code) but then there's a big server upgrade that sweeps through and makes it stick pervasively
