### ISSUE TITLE
ELMSLN SSO Feature

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1482]
Should this feature be switched on in the Course Outline service if the core bakery setup is being used?

![image](https://cloud.githubusercontent.com/assets/4973810/20432973/8f353b76-ad99-11e6-9ecb-20fd2903064a.png)

**Comment by btopro** [comment]
should be enabled everywhere

**Comment by rickhumphries** [comment]
OK I'll enable it. Thanks
