### ISSUE TITLE
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ctools_context has a deprecated constructor 

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1484]
When running drush title is error

fixed in latest dev of ctools. 
https://www.drupal.org/node/2659666

Not sure if ctools is a candidate for dev or not.

**Comment by btopro** [comment]
give it a shot and see the A/B comparison of what's all changed; that's a very slow moving project so either htat or if it's simple enough just patch it as is

**Comment by btopro** [comment]
latest stable, we were 2 versions back on this; includes mostly minor bug fixes and PHP 7 support
