### ISSUE TITLE
install run and remove https://www.drupal.org/project/module_missing_message_fixer

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1486]
Ran on new dev server against all sites now to see if it would work. It did. :)
However, since live at a version not ready for this module, every time we sync the db's down this will be undone. 

For now we will just have to ignore the drush errors.

**Comment by bradallenfisher** [comment]
I also patched this so that drush would work. again though I am not putting this into repo yet as it doesn't apply currently. 

https://www.drupal.org/files/issues/drush_integration-2770115-4.patch
from
https://www.drupal.org/node/2770115

**Comment by btopro** [comment]
yeah, add module_missing_message_fixer into our stack, this happens for everyone now as of 7.50+
