### ISSUE TITLE
Media shortcodes not rendering in Course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1487]
Bug:
- 0.5.0

- The course outline  currently ignores all shortcodes from Media.

This is probably specific to our dev setup at the moment, but Media shortcodes aren't being rendered at all. 

I've checked the Features, thought it might've been because 'ELMSMedia Service Integration' was switched off, but switching this on didn't work:
![image](https://cloud.githubusercontent.com/assets/4973810/20440115/870ff068-adb6-11e6-8af0-b58053b25b28.png)

**Comment by btopro** [comment]
that does something eles.
DM me an example cause I can't find one and this works flawlessly on all other 0.5's we have

**Comment by btopro** [comment]
unique to deploy, dm'ing solution
