### ISSUE TITLE
Icon Not Showing Up

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1488]
![screen shot 2016-11-18 at 12 33 36 pm](https://cloud.githubusercontent.com/assets/12716869/20441868/3fbb1fd4-ad94-11e6-810c-ab771f5780e3.png)

Icon is not showing up.

**Comment by btopro** [comment]
@Deb-G try it out now. In looking at Kickback in this example it didnt have a significance set. I set it to `reading` and it showed up correctly.
