### ISSUE TITLE
Apply Pure-speed setup to VagrantFile

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#149]
CentOS installer that runs as part of Vagrant spin up (and one line installers) nets us Mysql 5.1 and PHP 5.3.3. While the VM config (and it being local memory) makes it fast, this isn't fast enough for me. @bradallenfisher 's been doing some work on an effort called Pure Speed and I was hoping we could work on getting those improvements into the CentOS one-line installer / Vagrant that's spun up.
Goals / steps in that from remi or where ever:
- [x] Get php 5.6.x
- [x] Get mysql 5.6.x
- [x] Apply opcache tweaks to php out of the box to further optimize opcache (https://tideways.io/profiler/blog/fine-tune-your-opcache-configuration-to-avoid-caching-suprises)
- [x] Automatically setup and configure Varnish

We want the speed mechanism OOTB to be bullet proof for deployments that reside on a single system which is currently all the PSU deployments. I want this to be able to hit as ridiculous a scale possible before getting into clustering #19 or load balancing / server scale.

**Comment by bradallenfisher** [comment]
Are you going for rhel7 here? I would but it's up to you.

**Comment by btopro** [comment]
Hmm.. Upgrades to apply r easier but MySQL / PHP still need it

Wp8
________________________________
