### ISSUE TITLE
Scrollspy error

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1494]
Bug:
- v0.6.0

- Scrollspy links should scroll to the relevant heading tag, however the ID of the first paragraph is the same as the ID of the first heading tag (and the second paragraph ID is the same as the second heading tag etc.)

Therefore the scrollspy menu is just scrolling from one paragraph to the next.

E.g. first paragraph: `<p class="elmsln-core-in-context" id="cfcd208495d565ef66e7dff9f98764da">....</p>`

First heading tag: `<h2 data-scrollspy="scrollspy" id="cfcd208495d565ef66e7dff9f98764da" class="scrollspy">....</h2>`

First Scrollspy menu item: `<a class="scrollspy-link cis-lmsless-border cis-lmsless-text vibrate accessible-blue-text blue-border active" href="#cfcd208495d565ef66e7dff9f98764da">...</a>`

**Comment by btopro** [comment]
fixed in master
