### ISSUE TITLE
Material Icon Link in Network List Display Error

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1495]
Bug:
- v0.6.0

There's a link in the network flyout which I add here:
/admin/config/user-interface/cis-lmsless-nav

However it doesn't display correctly:
![image](https://cloud.githubusercontent.com/assets/4973810/20496153/e9d5f3ca-b01b-11e6-8ab5-12b717fae3a6.png)

**Comment by btopro** [comment]
fixed it in a site for you so you can see the difference. this isn't the name of the icon which is why it got goofed. http://design.google.com/icons/ has the names in question. This was listed as view-dashboard but the icon name is just dashboard

**Comment by rickhumphries** [comment]
Ahhh, makes perfect sense. Thanks!
