### ISSUE TITLE
Settings Cog is Inaccessible for some Shortcoded Media

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1497]
Bug:
- 0.6.0

Images from Media that use certain display modes (i.e. those positioned to the left) will display the settings cog at the top right hand side of the paragraph area:

![image](https://cloud.githubusercontent.com/assets/4973810/20504040/5aa10bb4-b03d-11e6-8d2b-b993809c0812.png)

However, you need to hover your mouse over the image to see it, so the cog can't be clicked in this instance.

**Comment by btopro** [comment]
should fix it for now; basically special accounting for things floating left since it works for the rest
