### ISSUE TITLE
Colour blindness simulator glitch

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1499]
Bug:
- v0.6.0

When selecting any of the colour blindness simulators, the performance of the page because very glitchy. I've attached a gif to illustrate the issue I'm seeing.

![colour blindness glitch](https://cloud.githubusercontent.com/assets/4973810/20504385/06867f62-b03f-11e6-8d22-0510c88b521c.gif)

**Comment by btopro** [comment]
try firefox for a bit better performance. Chrome used to work better till the latest build (of chrome). It's an incredibly aggresive SVG filter so it does have performance implications (i mean it works with video playing in real time so...)

**Comment by rickhumphries** [comment]
Ah yeh. Firefox works better. I've grown to hate firefox so don't use it anymore :)

**Comment by btopro** [comment]
same, chrome is up and down every release w/ these sorta issues
