### ISSUE TITLE
Token Insert for submission

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#150]
*Update: Video / Blog post about this -- https://www.elmsln.org/blog/post/insert-tokens-submission

We are working on the creation of something like this
`[ciscode|rev=1|tool=cle|entity_bundle=cle_assignment|submit=cle_submission|field_cis_tag=Assignment 4|render=submit|submit_reference=field_assignment|entity_key=nid]`
or
`[ciscode|rev=1|tool=discuss|author_field=uid|entity_type=harmony_thread|entity_bundle=thread|submit=post|submit_type=harmony_post|field_cis_tag=Discussion 1|render=submit|submit_reference=field_harmony_thread|entity_key=thread_id|submit_endpoint=post]`

To dynamically turn itself into:

![2015-07-27_17-08-22](https://cloud.githubusercontent.com/assets/329735/8922249/76c2e134-34ae-11e5-82b3-6cc5560a287c.png)

The codes can then be generated by anything in the system, allowing for unlimited remixing of embedding potential (any part of anything can be embedded in any part of anything is the goal). Entity Iframe also allows cross-domain communications so we'll be able to wrap a Ctools modal on that injects a drill down data passthrough. This will allow what appears to be native submission in the modal but is actually a well made frame on the other end. After submission, the page will tell the child of its child (who is its parent) what the link to go to is. At this point it will close the modal automatically and update the "Submit...." with a "View your Submission for...".

On subsequent page loads it will just appear as the View your... text. Code structure is still influx to account for different use cases but we have ones shown to be working for a dev build of Discuss and Studio

**Comment by michael-collins** [comment]
@btopro I love this. A lot.

**Comment by btopro** [comment]
video uploading now. got 3 different kinds working, still just popping an iframe at the moment but a good start

**Comment by btopro** [comment]
Blog post about this (made edit to original post as well) -- https://www.elmsln.org/blog/post/insert-tokens-submission

**Comment by btopro** [comment]
@michael-collins we'll need some kind of standard way of presenting these via class / style (obviously). Would like to keep the structure of them pretty simple though. Needs to convey that you need to do something (color / setup aria language), where your doing it (the icon / aria) and have support for multiple actions (like Submit _____ to studio | View Studio); whether that's multiline or not doesn't matter.

I'll gather some quick workflow thoughts from the ID team today about the fram-ing thing. cleaning up the presentation of the themed items might be enough to get going the first semester w/ this stuff and then move to something more clean (can't envision what that is just yet though).

**Comment by btopro** [comment]
Task: Review structure of the codes to ensure they'll do anything we want w. This capability in mind.
Add it into the share buttons list of short codes that are generated.

**Comment by btopro** [comment]
We'll want to clean up the UX for it down the road / integrate it better as we transition towards #85 types of setups but this is already in there and running this semester!
