### ISSUE TITLE
List style type set to 'none' for bullet points

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1500]
Bug:
- 0.6.0

I think this is a bug...bullet points within the course content now don't show as the list-style-type is set to 'none'. They also appear in a different font - Droid Serif instead of Roboto:

![image](https://cloud.githubusercontent.com/assets/4973810/20504515/c28cd6fc-b03f-11e6-96cf-14ea519752f7.png)

**Comment by btopro** [comment]
good catch
