### ISSUE TITLE
Edit from the Welcome Page in Course Outline doesn't redirect to CIS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1503]
Bug:
- 0.6.0

When on the welcome page, there's an edit link which previously redirected to the 'edit section' page within CIS. This doesn't seem to work anymore. It will instead just popup with a "CIS is currently refreshing its cache, reload this page in a moment to reflect any change" message.

![image](https://cloud.githubusercontent.com/assets/4973810/20521870/365a1094-b0a5-11e6-9e5f-8441ad5a078d.png)

**Comment by btopro** [comment]
able to replicate

**Comment by btopro** [comment]
tricky fix, fortunately we've got all kind of helper functions since this was originally written
