### ISSUE TITLE
Scrollspy menu links on long pages

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1504]
Bug:
- v0.6.0

On reeeeally long pages with a lot of headings, the scrollspy menu falls off the bottom of the page and the rest is hidden:

![image](https://cloud.githubusercontent.com/assets/4973810/20521931/88d2b2ae-b0a5-11e6-9689-2a5a1d809c0f.png)

Think there's the same issue in Media with the display mode options:

![image](https://cloud.githubusercontent.com/assets/4973810/20521962/ab9e3d08-b0a5-11e6-97f3-33fe7ee35012.png)

**Comment by btopro** [comment]
stop making lots of items then ;)

Have seen this as well, not sure the best method for dealing w/ it visually

**Comment by heyMP** [comment]
We'll have to look into scrollspy to see if there is a callback that fires when a selection changes.  If there is, we can do something like 

```
if (element.offset() > window.height) {
  // move list up so active element is visible.
  element.parent('scrollspy').position.top(window.height * 0.2);
}
```

**Comment by btopro** [comment]
@rickhumphries now it makes it only take up 1/2 the vertical area and then allows scrolling within it. we'll see in real world instances how effective this is but it cleans it up / makes it usable in testing both in content and in media

**Comment by btopro** [comment]
on scroll start
![2016-11-22_11-48-45](https://cloud.githubusercontent.com/assets/329735/20532911/add10aca-b0a9-11e6-8e09-d8eef5d814e6.png)

at bottom of page
![2016-11-22_11-48-56](https://cloud.githubusercontent.com/assets/329735/20532916/b639673e-b0a9-11e6-8d32-888f15bc7a37.png)

**Comment by rickhumphries** [comment]
😀😀😀
