### ISSUE TITLE
H5P errors on fresh install

### ISSUE THREAD

**Issue by djfusco** [elmsln/elmsln#1507]
Bug:
- ELMSLN version - 0.6.0 (fresh install recently)

- What happens
When trying to add the H5P libraries (all content types) from https://h5p.org/update-all-content-types to http://media.drdavefusco.com/admin/content/h5p

it gives me the following errors - below and screen shot attached

Should I update H5P and then try again?  
Thanks.

    There is a security update available for your version of Drupal. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates.
    There are security updates available for one or more of your modules or themes. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates.
    The system was unable to install the H5PEditor.Duration component from the package, it requires a newer version of the H5P plugin. This site is currently running version 1.9, whereas the required version is 1.10 or higher. You should consider upgrading and then try again.
    The system was unable to install the Timecode Editor component from the package, it requires a newer version of the H5P plugin. This site is currently running version 1.9, whereas the required version is 1.10 or higher. You should consider upgrading and then try again.
    The uploaded file was not a valid h5p package

<img width="1238" alt="screen shot 2016-11-22 at 9 52 40 am" src="https://cloud.githubusercontent.com/assets/16759277/20528735/5af40554-b09b-11e6-942e-6b50b1b5c37b.png">

**Comment by btopro** [comment]
@djfusco Ok, latest version up there, pull master and it should be good (hopefully). The drupal issue I spun off as another one. It's relatively minor #1508 

Keep 'em coming this is great

**Comment by djfusco** [comment]
Yep - that did it @btopro Thanks!  Off to add some xAPI transactions.

"Added 88 new H5P libraries."

Pic attached of success.

<img width="415" alt="screen shot 2016-11-22 at 10 50 02 am" src="https://cloud.githubusercontent.com/assets/16759277/20530531/ad3dbebc-b0a1-11e6-8c32-2a92a8309f00.png">
