### ISSUE TITLE
Custom modals added to WYSIWYG don't work

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1513]
Not really sure if this is a bug or a feature request.

Previously we used Zurb foundation modal code directly within the WYSIWYG source code which allowed us to develop a lot of custom modal buttons/content. Since updating to v0.6.0 this doesn't work. Tried to swap it out with the Materialize modal code but this doesn't work either.

I know there's been some work on modal display modes but some of our use cases are a bit more custom than those allow. Is this something that should still technically work or has it been disabled?

**Comment by btopro** [comment]
```
// re-enable the legacy zurb foundation components css/js
$conf['foundation_access_legacy'] = TRUE;
```
add this into the shared_settings and it'll load in the JS/CSS to support zurb. If this doesn't fix it let me know

**Comment by rickhumphries** [comment]
Hmm, I think this was already set but not certain. I'll double check when I get home (I'm bug hunting on the train!)

**Comment by btopro** [comment]
@rickhumphries also as per Materialize Modal question -- we had to make our own variation of the modal trigger in materialize, otherwise you can't customize them at all (which is bogus)
As per the code from our integration you can see that the trigger to bind it is `.elmsln-modal-trigger` and the modal itself has the class `.elmsln-modal`. You may want to include your own similar js for like `buttercups modals` sorta thing; that way they don't break w/ materialize or elmsln changes to the way these are invoked.
```
// modal items
    $('.elmsln-modal-trigger').bind('click', function() {
      // hide all currently visible modals
      $('.close-reveal-modal:visible').trigger('click');
    });
    $('.elmsln-modal').modal({
      dismissible: true, // Modal can be dismissed by clicking outside of the modal
      opacity: .5, // Opacity of modal background
      in_duration: 150, // Transition in duration
      out_duration: 50, // Transition out duration
      starting_top: '8rem', // Starting top style attribute
      ending_top: '8rem', // Ending top style attribute
      ready: function(modal, trigger) {
        $('.close-reveal-modal:visible').parents().focus();
      }, // Callback for Modal open
    });
```

**Comment by btopro** [comment]
moved this back to 0.7.x as I'm pretty sure it's related to this, if not we can explore it in future release as it'll be pretty minor addition / fix most likely

**Comment by btopro** [comment]
any update on this and that setting?

**Comment by btopro** [comment]
closing for house keeping, reopen if it's still an issue but the code is loaded to do it

**Comment by rickhumphries** [comment]
Yeh sorry. Haven't had chance to add to the shared_settings file yet as just waiting for that other issue to be sorted first.

I did try doing my own buttercups trigger using his injector but couldn't get it to work. I'll keep trying though

**Comment by btopro** [comment]
k

**Comment by btopro** [comment]
closing for now; reopen if it proves to not have been resolved
