### ISSUE TITLE
Tab menu doesn't horizontally scroll on mobile

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1514]
Bug:
- v0.6.0

Looking at the Materialize docs it looks like the tab menu should scroll horizontally on small screens. However, it looks like these are cut off:
![screenshot_20161122-072714](https://cloud.githubusercontent.com/assets/4973810/20539744/15f71682-b0ee-11e6-86af-627a6036f751.png)

**Comment by btopro** [comment]
well that was excessively easy, lol 4 characters and its fixed
