### ISSUE TITLE
Responsive banner

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1519]
Bug:
- 0.6.0

The banner image is squashed when resizing to small screens. The banner image should maybe retain its dimensions down to a certain point and then just be cropped?

Current behaviour causes this:
![image](https://cloud.githubusercontent.com/assets/4973810/20555450/1b477020-b15a-11e6-9355-abe38c1530ec.png)

**Comment by btopro** [comment]
this is only an issue for exact dimension banners. so long as it doesn't fall below 8rem height it won't stretch. I also put in a minimum width of 1000px (for now). This prevents stretch; oversized banners look and scale fine.
