### ISSUE TITLE
UX of Which 'View' Page You're Directed to in Media

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1520]
Bug:
- 0.6.0

I like the new 'display mode' view page when clicking on 'View' on an item in Media. 
![image](https://cloud.githubusercontent.com/assets/4973810/20556291/64a65750-b15e-11e6-9d21-91782a8d8b28.png)

Which takes you to /node/[#]/view_modes

I think this should be consistent with the 'View' option available within the settings cog when embedding using a shortcode. Currently the view option here:
![image](https://cloud.githubusercontent.com/assets/4973810/20556410/d916c818-b15e-11e6-8d7b-dc3811d5b786.png)
Will direct to  /node/[#]/view rather than 'view_modes'

**Comment by btopro** [comment]
Good idea
