### ISSUE TITLE
List of Courses in Media doesn't match those in CIS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1521]
Bug:
- 0.6.0
- Media

The list of courses shown in Media system is slightly different to those in the CIS. Some courses are missing, and others are there which have previously been deleted. Is there a way of resyncing them? Or is there a feature I should look for in order to keep them in sync?

**Comment by btopro** [comment]
Hmm should sync over onto resale the course in cis. It may sync up correctly nightly . If you notice a course, try hitting sync in the ... menu in cis

**Comment by rickhumphries** [comment]
This menu?

![image](https://cloud.githubusercontent.com/assets/4973810/20567879/47630682-b192-11e6-904f-b93c8880a320.png)

Which sync button is it? Sync roster?

**Comment by btopro** [comment]
yes

**Comment by rickhumphries** [comment]
doesn't seem to have worked unfortunately

**Comment by btopro** [comment]
Hmm OK. Try running crib which will kick off the whole thing I believe . We may need a command to forcibly rebuild the data model to match . This most likely only affects you and I bc of the age of our deployments from before the model syncing was possible

**Comment by rickhumphries** [comment]
Hmm, I ran the cron if that's what you meant, which hasn't worked. I got quite a lot of warning messages:

![image](https://cloud.githubusercontent.com/assets/4973810/20605570/f48ddbda-b263-11e6-96b0-2fc59b7e1f13.png)

But suspect these are unrelated

**Comment by btopro** [comment]
Cis cron

**Comment by rickhumphries** [comment]
Ah right. Just ran this and I get an error:

![image](https://cloud.githubusercontent.com/assets/4973810/20610550/2f91db08-b293-11e6-87ca-1a9b866a7ee9.png)

**Comment by btopro** [comment]
Err yeah I'm thinking so

**Comment by rickhumphries** [comment]
uh oh

**Comment by btopro** [comment]
closing for now; reopen if its still an issue after your custom cron goes through

**Comment by rickhumphries** [comment]
Unfortunately the courses still haven't synced. #1575 could be related? But don't really know. (not sure if I have permissions to reopen this either.)
