### ISSUE TITLE
Include a css class for each of the Read-time data types

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1522]
Feature request:
- I think the read-time data is great, but we have some pages where there's a lot of icons which are included in this count, and so the 'images' data chip isn't as relevant. If each of these data types had an ID attributed to it, we could target with CSS and remove just the images chip from displaying.

**Comment by rickhumphries** [comment]
Something like:
```
<div class="read-time-wrapper">
<div id="read-time-chip" class="chip blue lighten-4">...</div>
<div id="image-count-chip" class="chip blue lighten-4">...</div>
<div id="video-length-chip" class="chip blue lighten-4">...</div>
</div>
```

**Comment by btopro** [comment]
Good idea
