### ISSUE TITLE
Error notices on 'edit section' page within Course Outline

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1523]
Bug:
- 0.6.0

- Error notices appearing when editing a section list from courses.[...].co.uk/[coursename]/cis/section-list

![image](https://cloud.githubusercontent.com/assets/4973810/20567706/b4da9a96-b191-11e6-9f5f-7a5164cacb54.png)

**Comment by btopro** [comment]
hmm probably a section that doesn't have an outline defined

**Comment by btopro** [comment]
can't replicate though this should solve that
