### ISSUE TITLE
Can't use colour pickers in MOOC

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1526]
Bug:
- 0.6.0

Using any of the colour pickers, either when editing content or changing the theme colours doesn't work:

![image](https://cloud.githubusercontent.com/assets/4973810/20603951/e2d00dbc-b25b-11e6-86ff-b3121dd7dd3d.png)

**Comment by btopro** [comment]
The picker doesn't work or it doesn't get applied?

**Comment by rickhumphries** [comment]
The picker doesn't work

**Comment by btopro** [comment]
z-index issue, easy
