### ISSUE TITLE
Read time/media time don't appear to be calculating 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1527]
Here: https://courses.eldig-elmsln.vmhost.psu.edu/psu006/node/24 

The calculated time is 1 minute, but it doesn't appear to be pulling the info from the video that's lower in the content or the h5p questions either.

**Comment by btopro** [comment]
yeah, need a happy medium between calculating on every page save (which is incredibly intense w/ bigger course) and updating when it makes sense.

**Comment by kat-wehr** [comment]
Could a possible solution be that we add a button that lets the instructor/author/me calculate it when I'm done editing the page and then I just have to click it whenever I make a major update?

**Comment by btopro** [comment]
try going to the following path (after the url of the course) -- read_time/rebuild

**Comment by btopro** [comment]
confirmed

**Comment by btopro** [comment]
ok, so here's how it works now:
- Save a page; read time updates just for that page
- rebuild read time entirely (under settings tab for the site); it will correctly recalculate all values now
- enable a module or otherwise clear caches on the site, it will correctly rebuild all values
