### ISSUE TITLE
Back to top button interfering with body html on smaller screens. 

### ISSUE THREAD

**Issue by Anthall** [elmsln/elmsln#1529]
Hi Guys, 

I'm just wondering if there is an alternative solution for the back to top button and blue + icon for smaller screens sizes. At the moment they just sit over the text.  We'll hide them at this size for now.  

Thanks, Ant

![capture](https://cloud.githubusercontent.com/assets/24223210/20665563/1617c198-b558-11e6-8020-d503a5140016.PNG)

**Comment by btopro** [comment]
+ sign only developers / staff see. Back to top could be hidden / changed OK mobile I guess if a decent proposal was put forward. It can be convenient on long screens

**Comment by btopro** [comment]
moved it over so its more out of the way / square design
