### ISSUE TITLE
Materialize Tabs Issue

### ISSUE THREAD

**Issue by Anthall** [elmsln/elmsln#1530]
Hi, I've switched our tabs over from foundation to materialize but having come across and issue. When you click on a tab the page is shifting up, you then have to scroll back down to view the content of the tab. Is there an anchor point on the tab heading?  I've attached a gif to show the issue. 
Thanks, Ant

![tabs](https://cloud.githubusercontent.com/assets/24223210/20667087/750ef4a8-b55f-11e6-978b-88e0bae07b49.gif)

**Comment by btopro** [comment]
Have you set an anchor that's unique for the tab names? Guessing here

**Comment by Anthall** [comment]
No I've not set any anchors, I wondered if anchors were set up automatically for materialize tabs. This didn't happen when foundations tabs were used.

**Comment by btopro** [comment]
hmm.. can you use the ``` to paste the code here so I can throw it in mine and try to replicate?

**Comment by btopro** [comment]
make sure the names don't match another element on the page. When I use this from the materialize documentation it doens't jump up the screen:
```

  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#test1">Test 1</a></li>
        <li class="tab col s3"><a class="active" href="#test2">Test 2</a></li>
        <li class="tab col s3 disabled"><a href="#test3">Disabled Tab</a></li>
        <li class="tab col s3"><a href="#test4">Test 4</a></li>
      </ul>
    </div>
    <div id="test1" class="col s12">Test 1</div>
    <div id="test2" class="col s12">Test 2</div>
    <div id="test3" class="col s12">Test 3</div>
    <div id="test4" class="col s12">Test 4</div>
  </div>
```

**Comment by Anthall** [comment]
this the HTML I'm using...
```
<div class="row">
  <div class="col s12">
    <ul class="tabs bhivetabs"><li class="tab col s4"><a class="active" href="#tab1">Tablets and Capsules</a></li><li class="tab col s4"><a href="#tab2">Controlled Drug Liquids</a></li><li class="tab col s4"><a href="#tab3">Ampoules</a></li>
    </ul>
  </div>
  <div class="col s12" id="tab1">
    <p>[ciscode|rev=1|tool=elmsmedia|item=1256|entity_type=node|render=link|field=field_image|text=Tablet Flow Chart|target=_blank|delta=0|item_type=image|alt=Tablet Flow Chart|width=933|height=489]&nbsp;
    </p>
  </div>
  <div class="col s12" id="tab2">
    <p>[ciscode|rev=1|tool=elmsmedia|item=1257|entity_type=node|render=link|field=field_image|text=Liquid Flow Chart|target=_blank|delta=0|item_type=image|alt=Liquid Flow Chart|width=933|height=489]&nbsp;
    </p>
  </div>
  <div class="col s12" id="tab3">
    <p>[ciscode|rev=1|tool=elmsmedia|item=1258|entity_type=node|render=link|field=field_image|text=Ampoule Flow Chart|target=_blank|delta=0|item_type=image|alt=Ampoule Flow Chart|width=933|height=489]&nbsp;
    </p>
  </div>
</div>
```

I don't think the images inside the tabs will link for you though.  This is my custom css:

```
.bhivetabs{
background-color: #008cba;
}

.tabs .tab a.active {
     background-color: #f89939;
         border-bottom-style: none;
    border-bottom-width: 0;
}

.tabs .tab a {
    color:white !important;
    font-family: 'Droid Sans', sans-serif !important;
    font-weight: 700!important;
    font-size: 120% !important;
    text-transform: none !important;
}

.tabs .tab a:hover {
    border-bottom-style: none;
    border-bottom-width: 0;
    background-color: #06769a !important;
}

.tabs .indicator {
    height: 0;
}
```

**Comment by btopro** [comment]
css wont impact it. hmm, it doesn't cause the same behavior for me. Maybe try renaming those anchors to something more unique instead of just 'tab1'. Could also be something related to the bhivetabs class which isn't a normal one unless the only behavior of it is to apply the background

**Comment by Anthall** [comment]
I've just tried changing the anchor names, but this didn't work.  .bhivetabs does only change the colour so i'm confident it's not that.

**Comment by Anthall** [comment]
I've just pasted in your tab html above and removed my custom css for tabs and it is still jumping. Strange. I wonder if we have something on either  <div class="row"> or  <div class="col s12"> or some kind of rule for <a href="#">

**Comment by btopro** [comment]
where do you have a `<a href="#">` on the page?

maybe send me the full content of the page / try pasting the above stuff into their own stand alone page and see if it still persists

**Comment by btopro** [comment]
ok, I was able to replicate this.

It seems that it behaves that way if there's not enough content on the page. I was able to make this happen when there wasn't content below it. Try to replicate. I modified source and put:
```
<p>quisque. Vestibulum ut est, wisi velit, nulla sollicitudin morbi. Fermentum non wisi. Magna nec id sit consectetuer vel, montes mauris, scelerisque erat purus etiam nisl erat. Sit ut pulvinar quisque quisque. A ante, odio pharetra urna suspendisse nascetur metus. Dignissim dui nullam adipiscing amet, tincidunt tincidunt turpis. Duis a ipsum aliquam purus orci, in nec vel libero fusce, imperdiet quisque sem, in ac aenean ut, ac dolor scelerisque nibh nam.quisque. Vestibulum ut est, wisi velit, nulla sollicitudin morbi. Fermentum non wisi. Magna nec id sit consectetuer vel, montes mauris, scelerisque erat purus etiam nisl erat. Sit ut pulvinar quisque quisque. A ante, odio pharetra urna suspendisse nascetur metus. Dignissim dui nullam adipiscing amet, tincidunt tincidunt turpis. Duis a ipsum aliquam purus orci, in nec vel libero fusce, imperdiet quisque sem, in ac aenean ut, ac dolor scelerisque nibh nam.
</p>
```
below the `<div>` area of the tab layout and it stopped jumping positioning. When I took out my fodder content below it it started jumping again

**Comment by Anthall** [comment]
Yes i've tried it in a new page and it's still happening, The `<a href>` I'm referring to is in the materialsie html for the tabs...

```
 <li class="tab col s3"><a href="#test1">Test 1</a></li>
```

**Comment by btopro** [comment]
yeah that's really weird... seems related to there being content below it on the page. If I put an empty `<p></p>` it still does it

**Comment by Anthall** [comment]
I don't have any content below it, I'll add some and see what happens

**Comment by Anthall** [comment]
hmmm, it's still jumping, even with all this content below... 
![capture6](https://cloud.githubusercontent.com/assets/24223210/20674234/0c070dd0-b580-11e6-9e37-af6633a9b008.PNG)

**Comment by btopro** [comment]
how bout above then? lol. Whatever it is it's not elms related, probably more weirdness w/ materialize

**Comment by Anthall** [comment]
Where exactly are you placing your `<p> placeholdertext</p>` code?

**Comment by btopro** [comment]
above and below the whole tab thing

**Comment by btopro** [comment]
closing as this will eventually get fixed over here https://github.com/Dogfalo/materialize/issues/3955
