### ISSUE TITLE
Make patch off of chosen library

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1532]
chosen library was patched in order to meet accessibility guidelines

**Comment by btopro** [comment]
more low hanging fruit

**Comment by mmilutinovic1313** [comment]
How does one patch a library file on d.o.? I don't see a `.jquery.js` file listed in the chosen module page.

**Comment by btopro** [comment]
oh, get the library from github (search for jquery chosen and it should come up). Then leave the patch in our queue / submit as a PR to theirs

**Comment by mmilutinovic1313** [comment]
I've found their library - but they do not have the jquery files on their repo for PRs. Just coffeescript files. https://github.com/harvesthq/chosen. We are also many versions behind.

**Comment by mmilutinovic1313** [comment]
I'm gonna keep digging around their repo to see if they have the 1.1.0 version we are using with the proper file - just wanted to let you know what I found

**Comment by mmilutinovic1313** [comment]
Wrote text file to document the change as chosen no longer has direct jquery files in its version control.

**Comment by btopro** [comment]
one of the best text files ever added.
