### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#154]
Can you change it so level one headings and level two headings are not tied to each other when you set a color scheme. See the image below it changed the required to orange.  
<img width="1105" alt="screen shot 2015-07-28 at 3 00 09 pm" src="https://cloud.githubusercontent.com/assets/13224682/8940737/784808f0-3539-11e5-8a32-fc3a1de9a49a.png">

**Comment by btopro** [comment]
Added in fields for secondary, required, and optional. These will get rolled in whenever the files get applied to our real server (probably next week)
