### ISSUE TITLE
CentOS 7 Install ulmusdrush password

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1543]
Tried to use the one liner to install fresh copy. However, it's asking for an ulmusdrush password:

![image](https://cloud.githubusercontent.com/assets/4973810/20751070/d57e960c-b6f1-11e6-9907-133d7a0e06aa.png)

Not seen this before and not sure what it is/would be

**Comment by rickhumphries** [comment]
oh wait - the install seems to have kicked on. 

![image](https://cloud.githubusercontent.com/assets/4973810/20751315/04ac03be-b6f3-11e6-88cb-7662df114923.png)

Probably being too impatient!

**Comment by btopro** [comment]
Surprise you could interrupt it like that in the first place but yeah, composer it sometimes get cranky Bout and takes awhile to get the dependencies for it so it hangs out for 30s or more. Network / server latency thing.
