### ISSUE TITLE
A&A 121_lost ability to upload image file to ELMS

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1552]
Hi Bryan,

Great new look for the site!
But... it looks like I lost permission to upload files to the ELMS server - can you kindly regrant?
It happens when:
editing a page in ELMS > insert image > browse server > (Server dialogue box)
at the server dialogue box I can see previously uploaded files but the usual menu bar at the top is a simple blue bar, no options available.

Many thanks!
Peter

**Comment by btopro** [comment]
Thanks, if you have any visual recommendations / areas that there could be further clarity let us know in another issue please. Always looking to make things smoother to work with.

I'll look into that permission thing now should be done in an hour or so.

**Comment by btopro** [comment]
@pja12 this is fixed now. Thanks for the accurate and easy to reproduce report. Had to do with our xAPI tracking engine (which we can talk about the next time you stop by) wanting to track that page (which obviously it shouldn't) :)
