### ISSUE TITLE
Creating Roles and System-wide syncing

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1553]
Having a standardised way of setting up a new role and having that be propagated through the rest of the network would be really useful. Especially if these roles needed to share a role ID too. This may then be developed further to have a way of defining permissions for each tool and having those permissions be set for each instance of that tool.

In addition to this, it should be possible within the CIS to have a more flexible way of controlling the non-student roles on a course. So under each offering, every possible role would appear, and you can select multiple users in one go and provide them with the 'guest' role (for example). If this was done in a VBO type way, I'm thinking you could filter by role (say 'staff'), click 'select all' then say 'assign as 'guest' to quickly give all 'CIS staff' users a guest account within a course network, and place them in the appropriate section.

**Comment by btopro** [comment]
Best way to do this is via features / custom module (and it's easy to do)
- Create a new role you want everywhere in a site (or multiple roles)
- Create a feature that only exports those roles called (obviously your name making more sense)  MYCUSTOMMODULE
- Put the feature into /var/www/elmsln/config/shared/drupal-7.x/modules/custom/ MYCUSTOMMODULE (probably a folder from here that looks like its the place for your customizations)
- Enable the featureon all sites `drush @elmsln en  MYCUSTOMMODULE_ --y`

This will get it everywhere, right now. To make sure all new sites that get created have it edit  MYCUSTOMMODULE_.module and add the following:
```
/**
 * Implements hook_cis_service_instance_options_alter().
 */
function MYCUSTOMMODULE_cis_service_instance_options_alter(&$options, $course, $service) {
  // modules we require for all builds
  $options['en'][] = ' MYCUSTOMMODULE_';
}
```

**Comment by btopro** [comment]
@rickhumphries on the 2nd question. Right now compliance has (some) of this capability. You can assign people access to different parts of the system (single individuals) by doing something like "give Jeff access to every system with this role" or "give marry access to media with this role" or "give smithers access to course A with this role" sorts of logic.

Not sure if comply is on your setup and this doesn't do the bulk assignment you are talking about. Definitely something on our radar though via #1051 and #935 and #1473 types of issues which would start to touch on this.
