### ISSUE TITLE
Error messages when logged out

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1557]
ELMSLN version 0.5.x,  commit 503ca45db6600834c86b18a6dd9011da6460fa72

When online.elmsln.dev opens without user logged in, there is a pink notice box with these messages:

Notice: Undefined property: stdClass::$name in _cis_lmsless_theme_vars() (line 431 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module).
Notice: Undefined property: stdClass::$name in _cis_lmsless_assemble_user() (line 135 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module).
Notice: Undefined property: stdClass::$name in _cis_lmsless_assemble_user() (line 151 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module).

**Comment by btopro** [comment]
upgrade to 0.7.x and see if this is still the case, I believe it's fixed
