### ISSUE TITLE
Can't edit a user locally within a course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1561]
Bug:
- v0.6.0

When I try to edit a user account within a course site, it redirects me to edit their user profile within the master site (in my case, the CIS). However, this is causing issues as an administrator, as there are some things that I need to fix locally. 

For example, I have multiple staff users who I've been pulling into the course site manually (via `/admin/config/people/bakery`) and then assigning them guest access. I need to edit their profile within the course to give the correct role and group.

Is there a workaround? Thanks

**Comment by btopro** [comment]
@rickhumphries you are correct, I just applied a fix that I can hot fix on your server if needed; back channel from here
