### ISSUE TITLE
Error messages after cron runs in Media

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1562]
Bug:
- v0.6.0

Just thought I'd report that I see these errors after running the cron in Media:

![image](https://cloud.githubusercontent.com/assets/4973810/20839364/364bb34e-b8a4-11e6-8020-ba8498f9037c.png)

**Comment by btopro** [comment]
0.6.1 has an upgrade hook that addresses these; they are harmless but distracting looking for sure.
