### ISSUE TITLE
Bakery Master Site Setting

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1566]
Bug:
- 0.6.0

When creating a new course outline site, the bakery config is setting the Master Site as 'people' at `admin/config/system/bakery`

![image](https://cloud.githubusercontent.com/assets/4973810/20893317/4b2b4ce0-bb09-11e6-811e-ecea45a3c248.png)

This happens even though the CIS has been set as the master site in share_settings etc.

**Comment by btopro** [comment]
this gets generated on install. If you do the following it should fix it:
```
drush dis elmsln_bakery --y
drush pm-uninstall elmsln_bakery --y
drush en elmsln_bakery --y

```
