### ISSUE TITLE
Ubuntu Yaml notice at commandline

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1567]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/yaml.so' - /usr/lib/php/20151012/yaml.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by bradallenfisher** [comment]
in a new spin up? or on dev server?

**Comment by btopro** [comment]
brand new, lookin at it now
