### ISSUE TITLE
Fix padding weirdness on media asset display in content 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1574]
Not a major issue, but this has been frustrating me as I'm adding a ton of these things in one content page. The padding above media assets added with the shortcodes is too much. Whatever the padding is below them would be ideal, or at least even it out a bit. Example with videos: 

![screen shot 2016-12-06 at 11 34 17 am](https://cloud.githubusercontent.com/assets/15616523/20934164/2eb55e44-bba8-11e6-9ca4-52b46a2c3808.png)

The gap between "Watch -video name-" and the actual video is just weird, wasted white space. Whereas in the next line, the instruction (Watch...) is so close to the video above and way too far away from the video below.

What I've been doing with documents at least is adding the instructions below the item, but logically I'd want the instructions to go above the document. However, since the text below these appears so tight against the item above, it looks like whatever is below is "attached" or implies some sort of connectedness. Here's an example: 

![screen shot 2016-12-06 at 11 39 28 am](https://cloud.githubusercontent.com/assets/15616523/20934308/aeca4ae0-bba8-11e6-9c23-6c7c8d85991b.png)

In the "Tips on Writing" there's too much space. The "Tips on Presentations" looks great, except I'd prefer the two to be swapped and have the text appear above the link. In the editor it shows like this, which is what makes me think it's the padding above: 
![screen shot 2016-12-06 at 11 41 36 am](https://cloud.githubusercontent.com/assets/15616523/20934407/03b41e3c-bba9-11e6-9594-0ab4c3306e35.png)

Side note, the first display option for external videos looks really clean. Not sure what it's "called" but this is the shortcode for the one I mean: [ciscode|rev=1|tool=elmsmedia|item=89|entity_type=node]

**Comment by btopro** [comment]
@kat-wehr can u give me a link to this? not seeing it

**Comment by kat-wehr** [comment]
https://courses.eldig-elmsln.vmhost.psu.edu/mgmt215/node/3

**Comment by btopro** [comment]
you have an empty paragraph tag inside a row container. The row is dictating it's a new line
