### ISSUE TITLE
Access denied when running course service cron from CIS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1575]
Bug:
- 0.6.0

I'm logged in as an administrator, however, when I try to run the cron for a course service from within the CIS:

![image](https://cloud.githubusercontent.com/assets/4973810/20937733/21d5145c-bbe0-11e6-8cc6-7ef1da9be298.png)

it gives me a HTTP Error 403, and says 'Access to courses.abc.co.uk was denied'

**Comment by btopro** [comment]
is there a key in the path (dont paste what it is just asking if there is one) may be from a earlier faulty build

**Comment by rickhumphries** [comment]
There is a key in the path yes

**Comment by btopro** [comment]
DM me the path on slack

**Comment by btopro** [comment]
able to replicate and found the fix, easy thank goodness :)
