### ISSUE TITLE
0.7.x installation issue

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1576]
Version: 0.7.x
OS: Ubuntu 16.04 LTS
Issue: during installation, there were a few error messages, then installation stopped with the prompt asking for ulmusdrush password. I hit enter key but got "sorry, try again". Then I entered the root password and installation continued. I'm copying the screen messages below.

---------------------------------------------------------------------------
groupadd: group 'elmsln' already exists

cp: cannot stat '/root/.composer': No such file or directory

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/yaml.so' - /usr/lib/php/20151012/yaml.so:
cannot open shared object file: No such file or directory in Unknown on line 0

  [Composer\Downloader\FilesystemException]

  Filesystem exception:

  Composer update failed: the "/root/.composer/cache" directory used to download the temp file could not be written

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--] [<version>]

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/yaml.so' - /usr/lib/php/20151012/yaml.so:
cannot open shared object file: No such file or directory in Unknown on line 0

  [ErrorException]

  chdir(): Permission denied (errno 13)

global <command-name> [<args>]...

/var/www/elmsln/scripts/install/users/elmsln-admin-user.sh: line 63:
drush: command not found

/var/www/elmsln/scripts/install/users/elmsln-admin-user.sh: line 65:
drush: command not found

if you see targets listed above other then 'none' then you are good to go (otherwise elmsln still needs to be fully installed via bash /var/www/elmsln/scripts/install/elmsln-install.sh). Log out, then issue the following after you log back in to play with your new super
powers:

d @online status

cp: cannot stat '/root/.composer': No such file or directory

[sudo] password for ulmusdrush:

Sorry, try again.

[sudo] password for ulmusdrush:

Sorry, try again.

[sudo] password for ulmusdrush:

sudo: 3 incorrect password attempts

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/yaml.so' - /usr/lib/php/20151012/yaml.so:
cannot open shared object file: No such file or directory in Unknown on line 0

  [Composer\Downloader\FilesystemException]

  Filesystem exception:

  Composer update failed: the "/root/.composer/cache" directory used to download the temp file could not be written

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--] [<version>]

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/yaml.so' - /usr/lib/php/20151012/yaml.so:
cannot open shared object file: No such file or directory in Unknown on line 0

  [ErrorException]

  chdir(): Permission denied (errno 13)

**Comment by bradallenfisher** [comment]
I have the library worked out... still tracking down the missing sudo pw. :)

**Comment by btopro** [comment]
latest PR fixes this issue. thanks @bradallenfisher
