### ISSUE TITLE
Turn on `always_populate_raw_post_data` for restws calls

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1577]
Bug:
In vagrant, when you first load the app, the post requests to the `restws/session/token` will not return with the correct data, causing the app to not work.

- What happens
You will see an error on the network requests for POST `restws/session/token` saying that if you want this endpoint to return raw data, you need to enable it in your php.ini file `always_populate_raw_post_data = -1`

Solution;
We need to set `always_populate_raw_post_data = -1` by default

**Comment by btopro** [comment]
lol why is that and how did u track it to that yet it's not an issue in your dev!?

**Comment by btopro** [comment]
or is it not an issue on prod but is in dev?

**Comment by btopro** [comment]
```
always_populate_raw_post_data boolean
Always populate the $HTTP_RAW_POST_DATA containing the raw POST data. Otherwise, the variable is populated only with unrecognized MIME type of the data. However, the preferred method for accessing the raw POST data is php://input. $HTTP_RAW_POST_DATA is not available with enctype="multipart/form-data".
```

**Comment by btopro** [comment]
could that be the actual issue? mime-type is wrong?

**Comment by heyMP** [comment]
I have no idea.  These are my headers right now:

```
accept:application/json
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
authorization:Basic XXXXXXXXXXXXXXX==
Cache-Control:no-cache
Connection:keep-alive
Content-Length:53
content-type:application/json
Host:studio.elmsln.local
Origin:http://localhost:4200
Pragma:no-cache
Referer:http://localhost:4200/projects
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
x-csrf-token:XXXXXXXXXXXX
```

**Comment by bradallenfisher** [comment]
so are you going to update your dev manually?

**Comment by bradallenfisher** [comment]
This can't be the solution since it was deprecated in 5.6 and removed in 7
http://php.net/manual/en/ini.core.php#ini.always-populate-raw-post-data

**Comment by bradallenfisher** [comment]
This will be fixed when we upgrade to php as Setting always_populate_raw_post_data to -1 will opt into the new behaviour that will be implemented in a future version of PHP, in which $HTTP_RAW_POST_DATA is never defined.
