### ISSUE TITLE
Course Edit Form in CIS automatically adds a section

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1578]
Bug:
- 0.6.0

When editing a course in the CIS, a section will always automatically get added. This is a bit of a pain, as it's a required field, so each time you want to save you need to remove the bottom section:

![image](https://cloud.githubusercontent.com/assets/4973810/20944357/0ac8cb80-bbfb-11e6-82f0-12816240dc2a.png)

**Comment by rickhumphries** [comment]
Once the bottom section is removed, the top one then always becomes uneditable too:

![image](https://cloud.githubusercontent.com/assets/4973810/20944428/5458bfd0-bbfb-11e6-96d4-aab88a1d0f3d.png)

**Comment by btopro** [comment]
yeah this is an annoyance I saw the other day. Angular can't come soon enough
