### ISSUE TITLE
Setting a banner - always reverts to originally uploaded image

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1579]
Bug:
- 0.6.0

When adding a banner to a course in CIS, I can't override the originally uploaded banner. If I remove it, upload a new banner, then save - the first banner I uploaded will always show

**Comment by btopro** [comment]
Try doing. Super browser refreshing. Control shift R

**Comment by rickhumphries** [comment]
Wow...mind.blown

**Comment by btopro** [comment]
@rickhumphries this is a local browser cache thing w/ the system (which we can't really clear). When you upload the original file, it gets renamed thing.jpg. Then you upload a new one, it deletes the original thing.jpg and renames the new thing, thing.jpg. Your local browser goes to load the file and goes "oh, dude I already know about thing.jpg we're good". The result is that it skips the call entirely to save on having to deliver you another file.

Ctrl + Shift + R forces the browser to request new copies and ignore local cache for all assets.
