### ISSUE TITLE
some index.php files have header redirects in them.

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1580]
when rsyncing this is problematic. we should just create vhost logic in place to handle the redirects.

**Comment by btopro** [comment]
agree, this isnt really an elms problem so much as a our group's usage, though we probably should have those redirect to CIS or some place since right now they go no where. Either that our a static page that's something of a 404 / go back sorta deal

**Comment by btopro** [comment]
fixed in repo and fixed on production
