### ISSUE TITLE
CIS Service type no longer needs addresses

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1581]
I remember we had a solution for this but, I imagine it will happen each time we import databases after a sync. 

<img width="1440" alt="screen shot 2016-12-06 at 10 28 14 pm" src="https://cloud.githubusercontent.com/assets/2347525/20953690/4cff34e6-bc03-11e6-85f7-403b98539847.png">

**Comment by btopro** [comment]
hmm.. shouldn't be anymore, i'll have to look into it a bit deeper. Might be a module left to clean up somewhere

**Comment by btopro** [comment]
fly out issue addressed. still left to do on this
- [ ] drop the fields
- [ ] fix the views dependent on this to use registry based address (or at least drop the address piece of this... eliminating the need for it so...)
- [ ] remove the "cis registry sync" connotation (drush thing) as it won't mean anything

**Comment by btopro** [comment]
@bradallenfisher will help w/ our migration pathway to eliminating paths and also get you digging into the guts of the CIS a bit. Basically the webservice content type doesn't need to have these fields (for service path and the other one). They are referenced in a few views and a few other places in the code base, so find and remove them / find work arounds for the views to still accomplish the same things
