### ISSUE TITLE
HTTP 500 Error on first cron run

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1585]
Bug:
- 0.6.0

I get a HTTP 500 Error each time I try to manually run a cron, however it only happens on the first try. If I run the cron again immediately after then it seems to run fine.

The only 500 error on the server logs that we could find that coincides is the following:
`PHP Fatal error: Call to a member function query() on a non-object in /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/apdqc/apdqc.module on line 238`

It's happening in a caching class of some kind.

Is this a case of running through the list of apdqc related recommendations given on the status report? Thought I'd report anyway just in case

**Comment by btopro** [comment]
it's the same as the other issue i'm pretty sure, this is just a different error message

**Comment by rickhumphries** [comment]
Ah ok cool :)
