### ISSUE TITLE
Section syncing issue between CIS and Course outline service

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1589]
Bug:
- 0.6.0

I've just added a new course outline to a course but I'm unable to sync across the course sections. I've tried running all the crons, and also syncing the roster from the CIS, but this still hasn't synced the sections across.

The course itself was previously setup in the CIS, and I added the course outline by clicking the link on the `service-instances` page in the CIS

Issue reminded me of #689 (which has also not been resolved now that I look at it)

**Comment by btopro** [comment]
is there a cron key preset in the field field / does it claim the service is ready to go? (looking for clues)

**Comment by rickhumphries** [comment]
There's a cron key in the service instance field yeh, and it says 'service available'

**Comment by btopro** [comment]
ok; dug a little bit, saw a setting that needed corrected in the way CIS was asked for data but have to dig some more. May be related to there not actually being "data" addresses for this environment / them calling on https paths (again, that dont really exist).

**Comment by heyMP** [comment]
Possibly related? #1596

**Comment by btopro** [comment]
`$staff = _cis_connector_assemble_entity_list('user', 'user', 'uid', 'name', array('__role' => _cis_connector_role_groups('staff')));`

this needs to be a direct query for users of a certain role because role has to load EVERYTHING, hence timeout if loading everything = 40,711 users (thanks @rickhumphries )

**Comment by rickhumphries** [comment]
Woops 🙃

**Comment by btopro** [comment]
- [ ] simplify automatic staff sync from CIS out to other services
- [ ] cut a 0.6.3 that includes this and the other enhancements
- [ ] test sync on OB deploy after upgrade

**Comment by btopro** [comment]
@rickhumphries note above game plan --^

**Comment by btopro** [comment]
This commit fixes what was causing 500 timeouts on larger deploys that stored all their users in CIS. @rickhumphries 

This is a complex issue which would have happened no matter where the accounts originated though so a good thing to clean up.  Your deploy may still have the sync issues related to the need for upgrade routine to be applied as we discussed earlier.
