### ISSUE TITLE
Teamweek Gantt chart integration and meeting scheduling

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#159]
Once the ELMSLN course calendar is working, it might be interesting to send calendar items to this service: http://www.teamweek.com, but an API would need to be written based on this documentation: http://docs.teamweek.apiary.io/# They are still working on trello and git integration, but that should come before we get the calendar built for ELMSLN.

Unfortunately, https://youcanbook.me only allows webhooks for the pro account, but this is a pretty fantastic tool for scheduling office hours and integrating with whatever a person's calendar is.

**Comment by btopro** [comment]
outside of scope for now, a cool idea for functionality to sponsor down the road
