### ISSUE TITLE
Print PDF related error message in course outline

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1590]
Bug:
- 0.6.0

Receiving the following error message when I flush the cache or do other process type things in a course outline recently created `Warning: rmdir(/var/www/elmsln/config/private_files/courses/accuracycheckda/print_pdf/cache): Permission denied in drupal_rmdir() (line 2448 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/file.inc).`

![image](https://cloud.githubusercontent.com/assets/4973810/21010039/d8099718-bd41-11e6-80fe-2916c049d1b9.png)

**Comment by btopro** [comment]
ya i dono what that's about, it's never consistent

**Comment by btopro** [comment]
@rickhumphries when u get a chance, fix the permissions on the rig, might just be that (hopefully).
```
leafy
option 6
```

**Comment by btopro** [comment]
latest version clears this up and is WAY faster then previous version, win win.
