### ISSUE TITLE
script to convert from one domain to another

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1593]
When you change the domains pointing to a server (like when we go dev to prod) we should have a script that helps change the address everywhere needed under the hood. This is a basic sed but will save a boatload of time: elmsln/scripts/deployment/change-address.sh sorta deal
- [x] copy current config into new files
- [x] sed /old/new/g -i in new apache conf files
- [x] find way to not disrupt certs
- [x] restart apache
- [x] restart php (for cfg file change to register potentially
- [ ] delete environment file elmslm/_elmsln_env_config/environment.php (day of)

this way we can switch domains quickly or when people want to migrate to another location / change it's registered domain. These should be the only places they exist now.

We will have to manually move over the certs which I am doing now... I am not sure that we can really automate something like that since certs can be named anything.

**Comment by bradallenfisher** [comment]
I would probably leave the current config in place until after the DNS propagation. 
Edited in todos.

**Comment by bradallenfisher** [comment]
This is basically done. 
- copied live certs to dev box
- renamed certs to match domain pattern (easier sed)
- rehashed certs

There are now 2 sets of conf files that are in place. 
- *-old.conf files configure elmsln-dev domains
- *.conf files configure the domains that we are going to migrate over. 

Once complete we can delete all the *-old.conf files and we should be good. 

There is also a list of IP addresses on the LIVE box. Do we need to add a set of new IP's to the dev box and set them up in DNS? Or can all domains be on the same IP now?

**Comment by bradallenfisher** [comment]
leaving open until we delete the environment file.

**Comment by btopro** [comment]
ips shuokd be box specific so that calls get rewritten internal to dev / non-prod deploys
