### ISSUE TITLE
Adding new section via CIS add offering page, not syncing section with course outline

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1596]
Bug:
- ELMSLN version/commit reported on admin/reports/status
Code: 0.4.0 
Configuration: 0.3.1

- What happens
Visit `/cis-add-offering` in the CIS
Add section to course.
Go to the course outline `/admin/content`
No new section nodes created

- Work around
if you click edit on the course offering in CIS and hit save, it will work.

**Comment by btopro** [comment]
yeah I believe this has been fixed in 0.5.0; it was related to switching the direction the sync went. We'll get you guys up on the latest once the students leave :)
