### ISSUE TITLE
Quiz Tool

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1600]
Just created a new quiz in ELMS: https://grades.aanda.psu.edu/assessment-quiz-list#, "Drill Press Safety Quiz."  However, I was unable to add questions.  See images below.

![screen shot 2016-12-09 at 2 38 40 pm](https://cloud.githubusercontent.com/assets/12716869/21062482/28592e94-be1f-11e6-80c7-a8a3afe312d3.png)
![screen shot 2016-12-09 at 2 38 23 pm](https://cloud.githubusercontent.com/assets/12716869/21062490/2f4bf7a4-be1f-11e6-95e5-d68bc560460e.png)

Let me know if you have any questions

**Comment by btopro** [comment]
DO NOT use categorical random that seems to break :)

**Comment by btopro** [comment]
@Deb-G let me know if this works without that option. I was able to save it when I switched off categorical select (which has known problems from what I've seen)

**Comment by Deb-G** [comment]
That works!
