### ISSUE TITLE
Shortcodes within shortcodes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1602]
Not sure if this was a bit too trippy. But I'd set up rows of cards, each with a shortcode link to a document hosted on Media:

![image](https://cloud.githubusercontent.com/assets/4973810/21103054/afc750b2-c078-11e6-86c6-2afb00a974a9.png)

Code for a card is this 
```
<div class="card horizontal">
      <div class="card-border">
      </div>
      <div class="card-stacked">
        <div class="card-content"><span class="card-title">Candidate Introduction</span>
        </div>
        <div class="card-action">
          <div class="valign-wrapper"><i class="material-icons valign">file_download</i>[ciscode|rev=1|tool=elmsmedia|item=1400|title=Candidate Introduction ACDA|entity_type=node|icon=pageview|render=link|field=field_document_file|text=DOWNLOAD|target=_blank|delta=0]
          </div>
        </div>
      </div>
    </div>
```

I then realised that this organisation of documents is available on two separate courses, so I set up a Static Page content type within Media, and used the same html. 

However, it doesn't look like Media can reference shortcodes from within itself, because it displays like this:
![image](https://cloud.githubusercontent.com/assets/4973810/21103170/3906a5c6-c079-11e6-9048-a6fea4506d10.png)

And then if I use a shortcode to render this now in a different course, it displays how it shows with the full shortcode text instead of the rendered links.

Is it possible to do what I'm attempting?

**Comment by btopro** [comment]
cis filter is disabled in media; it's possible but very dangerous and will through erroneous 500 errors on save. the tokens bc of caching / rendering don't like being told to destroy and rebuild others at the same time (destroy even being save, which blows away cache, rebuild being render the token from the same system)

**Comment by btopro** [comment]
ok, this should be possible now. Don't know what you said but made me think of how I could tackle the redirect loop issue (which was a larger issues identified as part of #1404 but not 100% resolved, till now)
