### ISSUE TITLE
Feature Request / Idea -- Editable Review / Note Taking Documents in Browser

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1603]
Feature request:

As I've been studying for finals - I've noticed there is still way too much of a dependence on Microsoft Word Technologies in the classroom. Not everyone has access to Word, and many students (like myself) have ancient versions of Word that require constant updates and run slower than molasses. 

I would like to propose that we provide an alternative to word documents for students. We can have editable content that can be edited and saved in browser for note taking / review. It can be exported in a variety of formats if students so choose, but it gives the option for things to be all in one place. 

I have seen a few modules that accomplish this task and I know we have a few things installed already for this purpose. Let me know if you all have any feedback or ideas on this.

**Comment by kat-wehr** [comment]
Have you heard of Genius? http://genius.com/web-annotator 

It would be neat to do something like this that lets students then export the page with their annotations into whatever format. 

I'd also love to see a way for students to collaboratively take notes on web content too.

**Comment by mmilutinovic1313** [comment]
I will check that one out! I've also found this as another possibility: http://www.smashdocs.net/subscribe/

**Comment by btopro** [comment]
showing how something cool that can be used as a plugin works would be good; both of these seem like things u need accounts for tho

**Comment by mmilutinovic1313** [comment]
Yeah I checked the first one to see if there was a module - but didn't see one. I'll do more digging on this shortly.
