### ISSUE TITLE
Media Filters Display Issue

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1606]
Bug:
- v0.6.0

When filtering my assets by course in Media, the majority of the filter options disappear, so I can't further refine.
Also, in Table View, the option to filter by course isn't present.
I've recorded my screen to highlight both issues:
![media filters issue](https://cloud.githubusercontent.com/assets/4973810/21110552/87d2ecc0-c095-11e6-93a4-55764064e706.gif)

Now, this might be my fault for messing with these views at some point, but thought I'd check

**Comment by btopro** [comment]
yup

**Comment by btopro** [comment]
simple fix
