### ISSUE TITLE
Quiz Tool

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#1607]
Bug:
I took the "Drill Press Safety Quiz" and answered it correctly to see how the feedback works.  Then, I tried to answer it wrong to make sure that worked right, and I got the attached error message:

![screen shot 2016-12-12 at 1 07 35 pm](https://cloud.githubusercontent.com/assets/12716869/21110754/84c0ffb4-c06c-11e6-89db-acd0494b359d.png)

**Comment by rickhumphries** [comment]
I noticed this when playing around with Assessment tool too. I put it down to Quiz 5.x not being supported by the TinCan module - https://www.drupal.org/node/2608622

**Comment by btopro** [comment]
@rickhumphries you were right; I threw a quiz5 tincan module into the stack and disabled the old but haven't enabled the new. It's not required ,more so nice to have functionality but I haven't tested the quiz5 version yet.
