### ISSUE TITLE
Longer title texts will not resize to fit screen 

### ISSUE THREAD

**Issue by Meg5080** [elmsln/elmsln#161]
![screenshot_2015-08-04-16-25-35](https://cloud.githubusercontent.com/assets/13649297/9072174/aff347b8-3ac7-11e5-9b59-22e603cf58da.png)

**Comment by michael-collins** [comment]
@Meg5080 could you also post a link to the page in question. @heyMP and I are doing a code sprint tomorrow on the theme, so we can take a look at this.

**Comment by btopro** [comment]
https://courses.aanda.psu.edu/crimj101/ open course

**Comment by heyMP** [comment]
Relates to #128

**Comment by btopro** [comment]
h1 - h4 made slightly more logical for the time being though will still need something for mobile most likely. Current setting
h1 / page title - 2.75rem
h2 - 2.25rem
h3 - 1.75rem
h4 - 1.25rem

The .5rem step per heading makes it significantly visually different at each step but is just my solution for the time being. H1 came down from 5rem so... yeah that looks normal by comparison :)

**Comment by btopro** [comment]
not closing but no longer a release blocker as it has been mitigated, still need a fuller solution after review by the UX team.
