### ISSUE TITLE
Drush deprecation notice on Ubuntu 16 (in vagrant)

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1610]
when running a drush command:

```
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Console_Table has a deprecated constructor in /home/vagrant/.composer/vendor/pear/console_table/Table.php on
```

<pre>Array
(
    [type] => 8192
    [message] => Methods with the same name as their class will not be constructors in a future version of PHP; Console_Table has a deprecated constructor
    [file] => /home/vagrant/.composer/vendor/pear/console_table/Table.php
    [line] => 58
)

**Comment by bradallenfisher** [comment]
https://pear.php.net/bugs/bug.php?id=21155

i filed a bug report.

**Comment by btopro** [comment]
good enough for now, ill bump this back in priority since its a bigger thing

**Comment by bradallenfisher** [comment]
Yeah there's literally no fix since you need the console_table/Table.php but you can't edit it since it's a library that composer installs. dep hell. :)

**Comment by btopro** [comment]
gotcha; how about the deprecation notice? could we just turn that level of E reporting off?

**Comment by btopro** [comment]
I see that u fixed the part I was reporting; the other console table thing only complains on the status page and we have no ability to control unless the dependency gets fixed; okidoke; closing
