### ISSUE TITLE
Validation prevents update of existing course service offering in CIS 

### ISSUE THREAD

**Issue by curiosity26** [elmsln/elmsln#1613]
Bug:
- ELMSLN version/commit reported on admin/reports/status

0.5.x - https://github.com/elmsln/elmsln/commit/3b1949c036cc7d70eb7daa43dcd8d1816f806c06

- What happens

When editing a course service offering, I keep getting a validation error stating that the Semester is required. So I go down and the Semester information is filled in, but I reselect, just in case. Save again, same error, now there's two semesters shown. I remove the latter and both are removed and I don't have the ability to add a new semester at all.

- What you expected to happen
I expect to be able to save the service offering without any validation errors.

**Comment by curiosity26** [comment]
Somehow I ended up on the node edit page, where the issue occurred:
https://online.eldig-elmsln.vmhost.psu.edu/node/132/edit

**Comment by btopro** [comment]
This has been resolved in the 0.7.x branch which I'll start getting everything built off of starting Monday (once the kiddos leave)
