### ISSUE TITLE
Scrollbars on scrollbars in side nav 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1620]
Low priority, but there are scrollbars within scrollbars on the right nav within outline pages which seems odd since there's plenty of vertical space. Here's the page, and a screen shot below: 

https://courses.eldig-elmsln.vmhost.psu.edu/psu006/node/3

<img width="183" alt="screen shot 2016-12-19 at 8 42 45 am" src="https://cloud.githubusercontent.com/assets/15616523/21314921/9b68893e-c5c7-11e6-96da-ef22fbabf1c9.png">

**Comment by btopro** [comment]
get a larger monitor

**Comment by kat-wehr** [comment]
I'll add that to my syllabus.
