### ISSUE TITLE
Document display mode not displaying

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1621]
Any document shortcodes that had been added to outline pages are no longer displaying. I'm not sure how helpful links are in this case, except that the shortcodes are in the editor but just not appearing in the content. A few pages that should have documents displaying: 

https://courses.eldig-elmsln.vmhost.psu.edu/mgmt215/node/4
https://courses.eldig-elmsln.vmhost.psu.edu/mgmt215/node/11

**Comment by btopro** [comment]
fixed
