### ISSUE TITLE
Roster Upload "Illegal Choice" error

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#1638]
When trying to upload a csv to the roster at... https://online.eldig-elmsln.vmhost.psu.edu/mgmt215/import-users

<img width="1418" alt="screen shot 2016-12-21 at 11 27 16 am" src="https://cloud.githubusercontent.com/assets/15616523/21397140/a425b056-c770-11e6-8862-59b005fdca83.png">

<img width="701" alt="screen shot 2016-12-21 at 11 27 33 am" src="https://cloud.githubusercontent.com/assets/15616523/21397141/a4297c18-c770-11e6-934c-96709cd93c09.png">

**Comment by btopro** [comment]
may be related to not having correct rights, I'll have to see since I was able to push things through even if it didn't propagate fully yet

**Comment by btopro** [comment]
@kat-wehr can you let me know if this works now for you now that there's the correct "campus" options.

**Comment by btopro** [comment]
fixed through other roster clean up. reopen if not the case
