### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#164]
Footnote functionality is not working. 
Highlighted text is supposed to be the footnote, but it's showing up inline.

![2015-08-06_0938](https://cloud.githubusercontent.com/assets/1186260/9112797/f103b4c4-3c1e-11e5-9448-98f92da1a174.png)

**Comment by btopro** [comment]
Need a link, footnotes do work it might be a spacing issue

**Comment by juststormy** [comment]
https://courses.ed.science.psu.edu/psu16/node/13

**Comment by btopro** [comment]
fixed; pushed to space manually, we'll be doing a code push prior to semester start so hopefully it's lumped in elsewhere; if you see this pop up elsewhere let me know, it's an easy fix. The "limit allowed HTML tags" needs <fn> added

/admin/config/content/formats/textbook_editor
