### ISSUE TITLE
Image upload endpoint for ELMS api

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1644]
I need an endpoint where I can post base64 images and have the endpoint return the newly created image fid and at least one image url.  I am going to need this for the WYSIWYG image uploader for the studio.

<img width="781" alt="screen shot 2016-12-27 at 11 24 41 am" src="https://cloud.githubusercontent.com/assets/3428964/21503728/6c305a00-cc27-11e6-953e-f9886196682e.png">

**Comment by btopro** [comment]
I believe the restws `Access the resource file` and then file entity permissions will allow this so that you can post / query at /file (for the time being).

**Comment by heyMP** [comment]
yeah that structure looks good.

**Comment by btopro** [comment]
![2016-12-28_15-37-31](https://cloud.githubusercontent.com/assets/329735/21531122/8fd5ddee-cd13-11e6-90e0-891d1036df34.png)

**Comment by btopro** [comment]
@heyMP I can't get postman working so I couldn't test file creation (other then the null case) but if you pot against it with 'name' for filename and 'data' for the base64 object it *should* work.

The delete, list and query endpoints do work however and the create code is reverse engineered from how our restws support works for it.

**Comment by btopro** [comment]
![2016-12-31_09-08-13](https://cloud.githubusercontent.com/assets/329735/21577883/9f751026-cf39-11e6-84e8-01922fe4024e.png)

create works

**Comment by btopro** [comment]
![2016-12-31_09-15-43](https://cloud.githubusercontent.com/assets/329735/21577887/b7a99f90-cf39-11e6-8ab8-3789a51c457c.png)

list, create, delete, return single, all working. "Update" isn't really an operation for a file, it's more so delete, re-create and re-associate to something
