### ISSUE TITLE
Help review Drupal core patch

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1653]
https://www.drupal.org/node/2820757

Background: This would enable https://www.drupal.org/project/render_cache and https://www.drupal.org/project/d8cache to "just work" in D7 core. What this would enable is effectively a perfect cache expiration / setting scenario like D8 has (one of the only major advantages D8 has over D7 currently other then refactor-land).

@mmilutinovic1313 I think this would be a good one for you to focus your efforts on asking questions of https://twitter.com/fabianfranz for guidance on how best to rig up a test bed for it. This would then be good to try out in elmsln in a developmental branch as it'll provide a WAY more complex setup then most D7 sites to see if it generates any issues.

The patch in that thread changes some internal core asset gathering to ensure that all css/js needed to correctly deliver the page are still associated to the page even after a very aggressive level of output caching (currently not possible since it starts skipping hooks all over the place)

**Comment by btopro** [comment]
@nmillin drupal core patch that would help enable faster / more accurate cache granularity in core just like D8. Needs review / testing

**Comment by nmillin** [comment]
@btopro a bit too deep for me. I'm trying to stay away from the Drupal core issue queue ;)

**Comment by btopro** [comment]
np; it mostly needs "I applied this patch and things didn't break" level review

**Comment by btopro** [comment]
not as useful as we get more and more headless
