### ISSUE TITLE
how can Organic group Admin enter score for each member in one list?

### ISSUE THREAD

**Issue by mahnazafshar** [elmsln/elmsln#1656]
Hello Happy new year.
I developed schodmanagment system with Drupal.I defined "course" as a organic group content type.
each course envolve students.I want the organic group admin be able to view the students list, and he/she can enter score for each student via list.
Help me How could I define score?
Thank you.

**Comment by btopro** [comment]
this issue queue is specific to elms learning network. Your question might be better posed in one of the following:
- https://www.drupal.org/forum
- https://groups.drupal.org/drupal-education
- https://plus.google.com/communities/111161359890617128846
or on IRC / reddit / twitter
