### ISSUE TITLE
HTTP status codes need to match api status responses.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1658]
Angular HTTP uses response codes to handle success and error callbacks.  Need to make sure they are being set to match the status in the api responses.

![screen shot 2017-01-03 at 11 31 07 am](https://cloud.githubusercontent.com/assets/3428964/21614646/460c1554-d1a8-11e6-800b-f10259b575f3.png)

**Comment by btopro** [comment]
good to go on 0.7.x

**Comment by btopro** [comment]
@heyMP in the future mark these w/ the `ELMSLN API / JS API` tag as well almost nothing here is specific to CLE at this point (even though that's where it's being developed).

**Comment by heyMP** [comment]
sounds good.
