### ISSUE TITLE
Get ELMSLN distros submitted for review by Pantheon

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#166]
https://pantheon.io/docs/articles/organizations/adding-a-custom-upstream/#3.-test-your-upstream

MOOC and ELMSMedia are key candidates for inclusion there. Studio, Editorial and Discuss could be useful down the road.  Currently the other parts of ELMSLN like Comply, Inbox and CIS might be a bit too specific to the structure of our configuration to make sense as stand-alone's elsewhere but eventually it could be good to try and get all the gang submitted to different services for inclusion.

**Comment by btopro** [comment]
@mmilutinovic1313 once you get vagrant up and going and play w. Building some courses out for feedback, this would be a good one for exploring git deeper and increasing project visibility

**Comment by mmilutinovic1313** [comment]
https://github.com/elmsln/elmsln/issues/153

I will combine these two tasks into one. May have to wait for next semester for new online courses (I am taking one online Astronomy one)

**Comment by aaronbauman** [comment]
I'm new to ELMSLN, but would like to get an instance up and running on Pantheon.
Docs imply that this is not possible.
Where do I start?

**Comment by btopro** [comment]
@aaronbauman yeah it's not possible on Pantheon. Platform.sh it's most likely possible (I haven't tried). Running straight to AWS / DigitalOcean / VPS is probably more reasonable.

https://www.elmsln.org/install-guide has a mini interactive thing to build a 1-line installation
https://elmsln.readthedocs.io/en/latest/INSTALL/ also has details on how to get to each of the 1-line installers.
