### ISSUE TITLE
Unify the data model for all CRUD operations on api endpoints

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1662]
For Example:

The `api/v1/cle/submissions` endpoint is outputting submission objects structured like so:
```
{
"id": 1179,
"title": "new cle_submission",
"status": 1,
"created": 1483467930,
"assignment": 0,
"evidence": {
"text": null,
"images": [],
"videos": null,
"files": [],
"links": null
},
"energy": {
"timestamp": "2017-01-03T13:25:30-05:00",
"value": "100"
},
"state": "in_progress",
"section": 0,
"links": {
"self": "http://studio.elmsln.local/studio2/api/v1/cle/submissions/1179"
}
}
```
I should be able to create or update submissions with this identical structure.

**Comment by btopro** [comment]
@heyMP all 3 should be in the same form as they are output. start trying to submit and we'll see how stuff shows up.

**Comment by btopro** [comment]
post other issues branching from here as they come up so we can track / stomp them 1 at a time
