### ISSUE TITLE
ELMS Makers - a monthly Google Hangout on Air to showcase work being done

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1664]
Working title.
Mini-podcast of sorts w/ trying to get different perspectives / implementation use-cases of the platform. Faculty centric for some, ID centric for others, Techie centric for others and a general showcase sorta thing for where we're heading and what people are making with the platform at all levels. This is not intended to be a "look at this cool function @heyMP wrote", much more end-user centric and better telling the story that is elms and the things only possible w/ elmsln.

We'd invite anyone using or affiliated w/ building to join as a guest and talk about their experiences, show what they built and field questions. Basically drawing from the backlog of cool stuff we've all put together and have been talking about places in the last year.

Thoughts @rickhumphries @juststormy @michael-collins @heyMP @kat-wehr @djfusco @mmilutinovic1313 et. all?

**Comment by AndrewGearhart** [comment]
Please put together an ical schedule of these so that I can easily put these on my calendar.

**Comment by kat-wehr** [comment]
I'd gladly participate.

**Comment by michael-collins** [comment]
Yeah, sounds fun to me.

**Comment by djfusco** [comment]
Count me in.

**Comment by mmilutinovic1313** [comment]
I'm down

**Comment by btopro** [comment]
Episode 1 is tomorrow at 4pm EST. have a small audience that want a demo / tour of the architecture so this will kick things off. haven't done a public tour in awhile so worth an overview, then digging into individuals work mentioned here via small interview / them doing the future tours / explanations of their work.

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=03WdqcZsaKI

**Comment by btopro** [comment]
Link is being processed on youtube w/ edits (1st 8 minutes is testing / waiting for it to hit 4pm). This is the most comprehensive elmsln demo yet and no real errors while random walking between multiple deployments and multiple live courses.
