### ISSUE TITLE
Proposal for front-end uuid for every node.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1668]
I'm running into issues with relying on Drupal's node id (nid) to keep track of my angular 2 components.  If we allow the front-end to handle its own routeing via a UUID, then we can easily keep track of components that have been created in the front-end, but not in Drupal.  The Redux way is to tell Redux to create an item, it creates the item and adds it to your UI.  Once redux finds out that a certain component has been created, it will say "Oh let me create that on the server." 

This will also allow us to work the interface without needing a backend (mind blown).  So we can do things like having @michael-collins working on modifying the interface without running the ELMSLN environment.  It will also allow us to put prototypes on Github to get feedback.

And! if the user has the Redux dev tools Chrome extension, they can send us JSON files that contain information on how they generated bugs.  (crazy)

So, in summation, I think we should have some type of field on every node where I can store this UUID that was created by the front-end.

**Comment by btopro** [comment]
@heyMP does front end HAVE to be the one that originates it or can you create something, use the UUID generated by the system and swap it out.
