### ISSUE TITLE
Change language for "you don't have access to this page"

### ISSUE THREAD

**Issue by lizatgit** [elmsln/elmsln#1670]
version: 0.6.2

When a user is not authorized, the message reads "The Network firewalled your requested (you don't have access to this page)." Where can we change this message?

Thanks!

**Comment by btopro** [comment]
this is fixed in the latest to not be silly

**Comment by lizatgit** [comment]
If we want some custom language, how do we change it?

**Comment by btopro** [comment]
see elmsln_core_menu in elmsln_core

it'll be something like:
`hook_menu_alter`

in which you'll override the menu callback for that to deliver whatever you want for it or to force it over to wvu login or something.

```
$items['elmsln/error/%'] = array(
    'title' => '',
    'title callback' => '_elmsln_core_error_title',
    'title arguments' => array(2),
    'page callback' => '_elmsln_core_error_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'weight' => 10,
    'type' => MENU_CALLBACK,
    'file' => 'elmsln_core.errors.inc',
  );
```

Internally we handle access denieds by attempting to automatically log the user in via webaccess credentials (your CAS). Probably could rig up something similar to force over to CAS instead of delivering an access denied

**Comment by lizatgit** [comment]
Thanks I will try that!

**Comment by lizatgit** [comment]
We want to display some instructions to people without access. I did a
custom errors.inc and it works. Thank you!

**Comment by rickhumphries** [comment]
@btopro I'm keen to do something similar and have a custom error page too. I'm conscious of not wanting to change anything in core though. Is the above method by @lizatgit recommended?

**Comment by btopro** [comment]
yeah, we don't see this page often as we have a module that highjacks access denied before they are delivered and attempts to log the user in. It's still possible to get an AC in our deploys just a lot less likely unless your trying to go some place you really shouldn't be

**Comment by lizatgit** [comment]
@rickhumphries I did a custom error page named custom_module.erros.inc under the config folder within my custom module, no need to change anything in the core. Then refer to this custom error page as what @btopro instructed:

function custom_module_menu_alter(&$items) {
  $path = drupal_get_path('module', 'custom_module') .'/';
  $items['elmsln/error/%'] = array(
    'title' => '',
    'title callback' => '_custom_module_error_title',
    'title arguments' => array(2),
    'page callback' => '_custom_module_error_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'weight' => 10,
    'type' => MENU_CALLBACK,
    'file' => $path.'custom_module.errors.inc',
    );
 
  return $items;
}

**Comment by rickhumphries** [comment]
appreciate that @lizatgit thanks. I'll see what I can conjure up!
