### ISSUE TITLE
"Archive" state for important pieces of content

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1678]
I think it might be a good idea to not full on delete important content like projects and assignments but rather 'archive' them.  Trello has similar functionality.  Since Trello makes everything easy, it's possible to delete a board inadvertently so archiving is necessary.

Especially since we are going to be dealing with student submissions, we really can't be deleting projects or assignments that are referenced by submissions.

## Proposal

We could add a new boolean field called "archived" to projects and assignments.  Then in our api, we can check to make sure that we are not outputting content that is "archived".  Then, we can change the settings in the cle_app to set content to "archived" instead of deleting them.

**Comment by btopro** [comment]
@heyMP this is now reflected in archived which is 0 or 1 based on if it's available. It's a top level property like `assignment.archived` or `project.archived`
