### ISSUE TITLE
Where art thou Instructional Icons?

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1679]
v0.6.3

I thought the use of the instructional icons in the table of contents (both in the left hand block and the outline modal)  were a great visual cue on how the course was structured and worked really well. Especially when you get into using the container page types. Now they've disappeared and I miss them :(

![image](https://cloud.githubusercontent.com/assets/4973810/21722783/f99c992a-d425-11e6-82d8-6e018fd4812b.png)

Is this a bug or have they been taken away?

**Comment by btopro** [comment]
they were killed but we could make it an option. #1673 shows that this is in flux slightly as we've been improving readability / contrast of these little bits

**Comment by rickhumphries** [comment]
Yeeeh making it an option would be very useful I think 👍

**Comment by btopro** [comment]
nested content needs a distinction and we might allow for expand collapse dynamically. icons were too prominent previously

**Comment by btopro** [comment]
thoughts?
![2017-01-06_11-48-21](https://cloud.githubusercontent.com/assets/329735/21725342/0890278c-d406-11e6-9c30-8aa314556179.png)
