### ISSUE TITLE
cross browser compatability

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#168]
Flexbox doesn't work for the top navigation.

**Comment by aitala** [comment]
Also Safari 8.0.7 for Mac.

E


![screen shot 2015-08-07 at 1 02 58 am](https://cloud.githubusercontent.com/assets/4474470/9129105/2511ed62-3ca1-11e5-8989-d27efd468808.png)

**Comment by bradallenfisher** [comment]
Are you using autoprefixer? And is your browser list accurate?

**Comment by aitala** [comment]
Two minor Safari issues

![screen shot 2015-08-07 at 3 32 47 pm](https://cloud.githubusercontent.com/assets/4474470/9144323/17787490-3d1a-11e5-8ef3-5300f39d9ad3.png)

![screen shot 2015-08-07 at 3 35 20 pm](https://cloud.githubusercontent.com/assets/4474470/9144331/20fc7336-3d1a-11e5-8526-52fcc0890a6a.png)

**Comment by btopro** [comment]
yeah I noticed that one, couldn't figure out the property since it's not a display:inline-flex; issue but i'm sure flex-box related

**Comment by btopro** [comment]
![2015-08-10_12-30-00](https://cloud.githubusercontent.com/assets/329735/9176823/88cf38ac-3f5b-11e5-8cd2-453ffce94110.png)

updated screenshot of safari. Much better then it was, still the minor issues that @aitala points out though so still active

**Comment by heyMP** [comment]
Fixes the Safari issues.

<img width="1440" alt="screen shot 2015-08-10 at 11 59 09 pm" src="https://cloud.githubusercontent.com/assets/3428964/9189802/ef296554-3fbb-11e5-849f-9e42627e78d0.png">
