### ISSUE TITLE
Using the arrow keys to scroll

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1681]
Bug:
- v0.6.3

I've had reports from a few people who use the keyboard arrow keys to scroll that sometimes the scrolling can be buggy and will scroll slowly by itself and become unresponsive.

I think this is due to the 'double tap' scroll function which works fine when used that way, but if you do something like holding the arrow key down to scroll, it can cause strange scrolling behaviour.

**Comment by btopro** [comment]
ya i was starting to be able to replicate this recently, annoying; gone
