### ISSUE TITLE
A&A 121 header bar misscale

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1692]
Hi Bryan,

The new format on the course looks great! It appears on my screen that the header bar image is not dynamically scaling - perhaps you might have a look? I am attaching a screenshot of what I see.
Thanks, Peter
![header issue](https://cloud.githubusercontent.com/assets/16839175/21745374/5c6a969c-d4f8-11e6-8e9a-2d4131c1a240.jpg)

**Comment by btopro** [comment]
It's scaling, just not in a way that will display the text in it. If you keep text within boundaries of 0px to 128px in the image then it'll be displayed at all times. Other banners that include text are typically aligning it with the top left to ensure it's always visible.

**Comment by btopro** [comment]
if you ship me a new version then I can swap it out

**Comment by pja12** [comment]
Hi Bryan,



Let me make sure I’m getting the parameters right:

1.       Overall image is 1200 x 200

2.       Inset boundary for visibility is 128 pixels from all sides?



I had made the image so that the pencils graphic runs out to the edges.

As I understand it I will revise it so that all the text elements are within 
the 128 inside boundary and what goes beyond that will get cut off at some 
point variably. Is that right?



Thanks!,

Peter





Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
correct. 200 is a recommended size bc of variations / scale at different resolutions but you outlined it correctly, 128 is the standard cut off. Sorry, didn't realize this till reviewing your upload.

**Comment by pja12** [comment]
Hi Bryan,



OK, I think I got it. It’s the 128 border *below* that is primarily 
critical.

I revised the image so the text sits within that boundary and am attaching 
it. Please let me know if it needs further modification!



Thanks,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
