### ISSUE TITLE
Shared Email Module

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1695]
We've had a bit of trouble recently with some students who don't want to supply a personal email address, and instead want to use their workplace address. The client management are also support the students in this, so we may need to support multiple users having the same email address.

I came across this module and was thinking of implementing it:
https://www.drupal.org/project/sharedemail

Just wondering if there are any reasons why I shouldn't be doing this. Is it likely to cause conflicts? I don't think it would but thought I'd check

**Comment by btopro** [comment]
dont know what the implication of this would be, maybe one for bakery but really not sure

**Comment by rickhumphries** [comment]
OK no worries - I'll see if we can apply it and do some testing

**Comment by btopro** [comment]
#1717 merge
