### ISSUE TITLE
ELMS api fails for non admins

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1699]
https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/elmsln_api/elmsln_api.module#L242

`menu_get_router()` throws 403 error if a non admin tries to access an api endpoint.
![screen shot 2017-01-09 at 12 12 42 pm](https://cloud.githubusercontent.com/assets/3428964/21775833/a48c376e-d665-11e6-8e0e-304c6ee03cc9.png)

**Comment by btopro** [comment]
can't reproduce
