### ISSUE TITLE
Snowflake textual description

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#171]
Love the snowflake / network icon but it would be good to have the ability to put a written description of what it is. For example, even if it just said "Art 10" this would let someone know they are going somewhere else in art 10.

This would also be useful in the Rock deployment as they list all the other available courses (12 of them). In this instance, it saying "Courses" or something of that kind could be very beneficial.

**Comment by michael-collins** [comment]
Would prefer not to put "art010" in the header twice, thats poor design. Not sure this approach would solve your problem anyway. Let me think about it and see if I can come up with something else.

**Comment by btopro** [comment]
meant more so the option / flexibility, poor example I gave as that would obviously look poor :)
