### ISSUE TITLE
Updating student email address in master site breaks course access

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1717]
In our implementation we allow students to update their email address on their profile. However, this will temporarily break their access to the course sites since the accounts on their course then have a different email address and bakery can't handle it for some reason.

We'll investigate and report back with a fix

**Comment by btopro** [comment]
previously email address couldn't be updated. The referenced issue should fix that and hopefully this in conjunction. For bakery to work email and name have to match, this now allows for updating email address after an account was already created; which previously would have broken this
