### ISSUE TITLE
A&A121 - seem to have lost arrow on 'design case' template

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#1719]
Hi Bryan,
I went to insert a new 'design case' feature on a course page and discovered that the template  with the right-pointing-arrow icon seems to have been replaced by one that looks like the Yamaha tuning forks. Did I find the wrong template, or has something gone awry? 
What I see is attached; You can see an example of the correct one at the bottom of the page here: https://courses.aanda.psu.edu/aa121/?q=node/357
Thanks for your help,
Peter
![casestudy](https://cloud.githubusercontent.com/assets/16839175/21862823/d3085812-d808-11e6-8343-15c57b36b7ab.jpg)

**Comment by btopro** [comment]
are existing ones not working? This was the general purpose / open version we can include for everyone to use so if your existing ones are fine then can copy and paste that in.

**Comment by pja12** [comment]
Hi Bryan,



Yes, I can copy/paste, no problems. In the past, though, there was a 
template set up for it that is no longer on my pulldown list. My first 
inclination was to look for it in the pulldown list I screenshotted and then 
let you know. My bigger thought was that maybe something went awry where 
icons got switched out unexpectedly and maybe it affected other instances as 
well.



I’ll go with copy/paste for now but if you have a free moment sometime 
perhaps you might be so kind as to restore the old arrow one?



Thanks,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
@pja12 shoot me an email directly of a link that has the one you want on a page and I'll add it in.
