### ISSUE TITLE
Section save timeout

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1729]
Bug:
- v0.6.3

When saving a section after editing from the course outline (/cis/section-list) this will timeout on courses with a massive amount of students as described in #1271 

I think the timeout is due to it trying to sync all the students(?) but this isn't required anymore since this should be done from the CIS now.

I have a section where I want to switch the instructional outline from one book to the other, but the section size is massive in terms of students, so it's unable to save.

**Comment by btopro** [comment]
hmm.. sounds deploy sepecific as this should only be syncing if you have code implementing it still since the new CIS push out methodology is to avoid this

**Comment by rickhumphries** [comment]
Ah yeh - you're right. Just spotted a custom module that's messing with it. Sorted now - thanks
