### ISSUE TITLE
Access Duration End Date Options

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1730]
The access duration only allows me to set until 2018 which worries me a little since we just hold our courses open indefinitely. 

Would I be better just unchecking 'show end date'? I hadn't done this before, and set it to something like 2030, based on advice I was given when we first set up ELMS, but not sure if this would work now...

**Comment by btopro** [comment]
yeah, maybe we need support for no end date. If there's no end date then it just ignores all the 'shut down' procedures.

**Comment by btopro** [comment]
bumped up to 2025
