### ISSUE TITLE
player.vimeo.com CDN is wonky

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1731]
this causes our whole UX to be unstable (odd point of failure I know). It's very zone specific so like twice a year in the PSU area kind of a thing. Still, annoying and we should just include the file that can't be served VIA CDN at times (causing the page to hang like crazy).

https://player.vimeo.com/api/player.js

**Comment by mmilutinovic1313** [comment]
Could we use EasyCDN stuff as fallback? Or does this only load from vimeo's CDN itself

**Comment by btopro** [comment]
direct from vimeo. vimeo the part boming
defer tag might help but hard to test
