### ISSUE TITLE
Replace Image Carousel with a webomponent

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1735]
Bug:
- v0.6.3

We're having trouble implementing an image carousel in Media. I've made a video with an example to highlight what's happening:
https://youtu.be/noBk-OJR4mE

The sort of thing we're trying to do is something like this Slick slider:
http://kenwheeler.github.io/slick/
https://www.drupal.org/project/slick

**Comment by btopro** [comment]
Did you put one ina course? They screw up on that page but work when implemented from what ivr seen

**Comment by rickhumphries** [comment]
Yeh I tried in a course. The image gallery carousel slider shows the same behaviour. Image gallery carousel works a bit better, but still not completely user friendly:

![image carousel stuff](https://cloud.githubusercontent.com/assets/4973810/21985075/f8810ee0-dbf0-11e6-8867-bc71afd8c917.gif)

**Comment by btopro** [comment]
it's a horrific design pattern so it looks about right to me ;)

**Comment by btopro** [comment]
this won't be resolved till we find a web component that can replace it. The lack of scoping on the materializecss carousel makes it impossible to not conflict w/ other things going on -- https://www.webcomponents.org/element/annsonn/fancy-carousel/demo/demo/index.html is 1 that's been messed w/ internally

**Comment by btopro** [comment]
@rickhumphries can check out what @nikkimk has been up to here -- https://github.com/LRNWebComponents/lrndesign-gallery which is in pursuit of this issue

**Comment by rickhumphries** [comment]
Looks great! H5P have an image slider now too (https://h5p.org/image-slider) which we've been using for now until this is up and running :)
