### ISSUE TITLE
Bookmarking Style for Flag Module

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1736]
Feature request:

- Looking to add some custom styling to the way bookmarks look in the flag module. Currently they are just a button that says `add bookmark`. @rickhumphries made this graphic as a template that we might be able to shoot for. 

![699cc816-cc26-11e5-9aac-9c921c5ff7cc](https://cloud.githubusercontent.com/assets/7243665/21991018/ff470d7c-dbde-11e6-8487-119303f744b7.png)

**Comment by btopro** [comment]
Bookmarking needs to be an action on the page too

**Comment by mmilutinovic1313** [comment]
Yes - if we could add those bookmark logos on the page and have either a tooltip, description, or both that would be best.

**Comment by btopro** [comment]
dup
