### ISSUE TITLE
Replicating H5P Content

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1741]
Bug:
- v0.6.3

- I get thrown the following error message after doing the following:
- Replicate a H5P node in Media
- Edit the replicated node, change some stuff, click save

![image](https://cloud.githubusercontent.com/assets/4973810/21999926/7bc34604-dc34-11e6-9fc6-9b9d2de1720c.png)

**Comment by btopro** [comment]
ooo ya, don't replicate h5p items I think this is a known issue

**Comment by rickhumphries** [comment]
lightning reply! Yeh not really a big deal. Can easily just create from new

**Comment by btopro** [comment]
Best way to "replicate" an h5P I believe is to download the .h5p file and then use it as the basis for a new one. Haven't tried tho

**Comment by btopro** [comment]
accounted for so button isn't there to do it (since that will never work without a ton of effort for little gain). This also includes the latest version of H5P which is a lot more accessible and easier to use!
