### ISSUE TITLE
Tweaks.css styling affecting H5P content

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1743]
Bug:
- v0.6.3

Just raising awareness that some of the styling from tweaks.css appears to be affecting the style of H5P content. One example I've seen is this CSS:

```
article ul:not(.collapsible):not(.browser-default):not(.dropdown-content):not(.table-of-contents):not(.menu) li {
    list-style-type: disc;
    list-style-position: outside;
}
```
makes a disc appear on the MCQ checkbox. 

![image](https://cloud.githubusercontent.com/assets/4973810/22027326/69f946de-dccb-11e6-8b4e-986e2423e91a.png)

I've also seen some styles altered on the documentation tool.

**Comment by btopro** [comment]
yea that's in master right now as accounted for.
