### ISSUE TITLE
Tell vagrant server to not track filemode changes in git.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#175]
Here is the command that needs to run after the elsm repo is cloned into the server:
`git config core.fileMode false`

Since there are file mode changes that occur during the Vagrant setup process, there are automatically staged changes in git.  We need to disable git from tracking those changes.  To do that we need to set `fileMode.false` during vagrant provision.

Here is a post explaning the issue:
http://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

**Comment by btopro** [comment]
`git config --global core.filemode false` can also be run to ensure it doesn't pop up elsewhere. good catch, where you you a year ago to save me on this one
