### ISSUE TITLE
Buttons for Course pages

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#1754]
Two questions:

1. Is there a way to create a button on the course page that links to the specific assignment in the studio (or to the assignments page in general)
2. Can we create a short video that shows the students how to navigate back from the studio to the content pages? Once they submit an assignment they may not know how to get back.

**Comment by btopro** [comment]
@jtb260 this is not a real thing but flash reaction to would something like this solve the "students don't know where they are" issue (as well as the specific thing being mitigated tho I still get why its useful to do)

![2017-01-18_19-24-15](https://cloud.githubusercontent.com/assets/329735/22088725/1ce2b2ec-ddb4-11e6-8374-54d94269e0d1.png)

**Comment by btopro** [comment]
Tools students have access to would be highlighted on the UI while administrative tools are accessible under the (current) network icon for administering the system / doing less common tasks for powering a course (working w/ media for example, a task only needed in initial building and after build not utilized much)

**Comment by btopro** [comment]
I see you made the buttons so should be good for now w/ this
