### ISSUE TITLE
Add critique style to assignment content type

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1755]
Need to add a critique style that has the following option list: 'Open', 'Blind', 'Double-blind'

**Comment by btopro** [comment]
hmm... I believe method serves this purpose potentially

**Comment by btopro** [comment]
none|None
random|Random
partner|Partner off
open|Open to anyone

**Comment by btopro** [comment]
open = open (completely open)
random = open (both know each other but don't have option to pick ppl)
random = double-blind (basically)

Blind isn't really useful from what the Com professor we talked to. Either it's double blind for fairness or it's open. If people need to know who did it, it's open, if it's closed, it's closed. Makes it much more black and white in describing it to others too I think

**Comment by btopro** [comment]
@heyMP need confirmation of this either way as to if it's taken into account or if we need to build still

**Comment by btopro** [comment]
This is the field_critique_privacy field in drupal. 1 means it is public, 0 means it's double-blind.

In the response data this is:

assignment -> evidence -> critique -> public
