### ISSUE TITLE
Add submissionActive property to Assignments endpoint

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1760]
Proposal to add a property on the metadata object that indicates whether or not the current user can make a submission.  It would have the following logic:

- [x] does the current date fall before the due date and after the begin date.
- [x] does the assignment have 'allow late submissions' selected
- [x] does the user have permission of 'Bypass cle assignment submission permissions' that would be given to admins, staff, instructors 

This logic would also allow or deny users from creating, updating, or deleting submissions on the drupal side.

**Comment by btopro** [comment]
allowLateSubmissions comes across in the assignment object, or do you mean something different by that?

**Comment by btopro** [comment]
@heyMP you'll have to describe the point of 2 and 3, 1 I did, the other 2 I think the data is there unless you want it in a different format (verifying this)

**Comment by heyMP** [comment]
so if the `allowLateSubmissions` is true, then it should override the first `if` statement of `does the current date fall before the due date and after the begin date.`

`allowLateSubmissions` is a setting where `submissionActive` is a node access check.  The reason why I want to make specific access properties in the metadata is because I want to keep their logic in Drupal and as little in the app as possible.

**Comment by btopro** [comment]
last sentence makes sense
