### ISSUE TITLE
remove the chosen module

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1762]
In some old courses that have been updated there can be input types that are different to the standard. For example:
![image](https://cloud.githubusercontent.com/assets/4973810/22120813/3f495dde-de79-11e6-9c57-5947a9f7404f.png)

And the following is usually a typed input rather than a dropdown:
![image](https://cloud.githubusercontent.com/assets/4973810/22121327/90540e98-de7b-11e6-89cd-405d2a1dbb7c.png)

Can you point me in the right direction on where to fix things like this. I've tried going into Features and reverting all the components that say 'Overridden' but there are some things that always show as Overriden, even when this is done. Not sure if this is the right fix though. Thanks

**Comment by btopro** [comment]
I could be wrong but I believe masquerade will show you a searchable list IF you are viewing as a section other then master

**Comment by rickhumphries** [comment]
Hmm, not in this particular course. And there are other courses where the searchable list shows even though I'm viewing the master section

**Comment by rickhumphries** [comment]
Something I'm noticing fairly consistently on this is that the search box in the Masquerade modal is a dropdown list if viewing within a particular section, but is a search bar if you're in the master section.

Not major, but would be good to have a search bar for all

**Comment by btopro** [comment]
if we drop the chosen module then this will clean up
