### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#1763]
Is there a way to align the text that gets pushed to the second line (i.e, poster) so it aligns with the first line (i.e., lesson). In addition, can we decrease the line spacing? 

![screen shot 2017-01-19 at 3 56 44 pm](https://cloud.githubusercontent.com/assets/13224682/22125170/aa590494-de60-11e6-8360-56d3ac79e7f4.png)

**Comment by btopro** [comment]
or account for really long titles as well

**Comment by btopro** [comment]
![2017-01-20_19-33-30](https://cloud.githubusercontent.com/assets/329735/22170045/573e25b8-df47-11e6-9e91-7f740bbf2b03.png)

really long titles on the overview will now hide overflow / do a ... when it can. Full title displays on full interface after clicking assignment
