### ISSUE TITLE
Layout design idea

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#1764]
I've used the icons to display the due date and the estimated time for the project. Can we make this into a template? 

![screen shot 2017-01-19 at 3 56 57 pm](https://cloud.githubusercontent.com/assets/13224682/22125313/2cc2918e-de61-11e6-97fe-f792773ea359.png)

**Comment by btopro** [comment]
@heyMP she's doing this via just the HTML that's input but might be a nice way of visualizing that data stored w/ the assignment

**Comment by jtb260** [comment]
Just maybe, we can connect the date with canvas?

**Comment by btopro** [comment]
merging into app feedback issue
