### ISSUE TITLE
Varnish feature

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#177]
ELMSLN currently has 2 performance core features which automatically optimize for a standard advagg configuration as well as one for authcache. It would be good to have one as part of the authcache feature which also tunes things / changes settings as needed for use with Varnish.

After building w/ the auto installer for varnish in digital ocean I get a "yes! sorta.." from isvarnishworking.com when it comes to pages served up from a course.

**Comment by bradallenfisher** [comment]
for the yes sorta thing you need to set The maximum time an external cache can use above 1 minute and the course needs to be able to be viewed by anon traffic.

**Comment by bradallenfisher** [comment]
sorry it's the minumum cache lifetime. mine says yes! try it with online.bytesofweb.com

**Comment by btopro** [comment]
yeah that setting, I dono what it is exactly, I usually just mess around w/ Drupal cache settings until isvarnishworking says yes instead of yes sorta

**Comment by bradallenfisher** [comment]
closing this and will explore at a later date. Essentially there is no way to accurately assume how one system would use varnish. Until we get some sort of settings.php file delivery system for cache specific variables this will be guess work at best.
