### ISSUE TITLE
SSL Terminator

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#178]
It doesn't need to be OOTB but it would be good to document on the wiki how you can obtain an SSL terminator so that we can start varnish caching https based traffic. This will be a common method of site access to uses logged into university systems.

**Comment by bradallenfisher** [comment]
looking into this.

**Comment by bradallenfisher** [comment]
looks like pound may be the way to go? Or do you have something else in mind?

**Comment by btopro** [comment]
Pound is only thing I ever heard of. Also an option to do a self signed cert would be a good additional option (it's not perfect but at least encrypted)

**Comment by btopro** [comment]
Do you think we could auto generate a self signed cert and do so during install? Not great but better then nothing plus we could make a script to do the cert, a script to do pound and pass in if it has a cert or whatever.

**Comment by btopro** [comment]
Pound working on staging but doesn't respect our internal authentication system. It is working though so this is great news

**Comment by btopro** [comment]
@bradallenfisher do you have any kind of automated pound installer?

**Comment by bradallenfisher** [comment]
Not yet. I will try to get one going.

**Comment by btopro** [comment]
even just an example of one; something we can point to, not positive how automated we could do this part just cause of the complexity of Pound -> Varnish -> Apache relationship but we won't know till we try :).  #349 should also help simplify how it's applied a bit so that we're only listening on a proposed cdn domain

**Comment by bradallenfisher** [comment]
Just for reference: 
- http://blog.ajnicholls.com/varnish-apache-and-https/
- http://www.project-open.com/en/howto-pound-https-configuration

### Notes:
Looks like there needs to be 2 backends setup in varnish: default (8080) and default_ssl (8443)
Pound will now do the encryption so we spoof the ssl connection in a sense. (X-Forwarded-Proto header)

todo add more...

**Comment by btopro** [comment]
sounds correct from when I've implemented successfully (dev box)

**Comment by btopro** [comment]
@bradallenfisher could you add a page to the docs section about scale and then add one for pound perhaps?

**Comment by btopro** [comment]
@bradallenfisher can you update the docs section around performance to included some of the details here; once that's done issue a PR and close please
