### ISSUE TITLE
Only mark assignments complete if the submission state is 'submission_ready'

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1787]
Since we have `states` with the submissions we should not mark assignment status as complete until the related submission state == 'submission_ready'

![screen shot 2017-01-24 at 10 12 46 am](https://cloud.githubusercontent.com/assets/3428964/22252904/bd2ff954-e21d-11e6-9199-6e1b0ed7d116.png)

**Comment by btopro** [comment]
There are 3 cases w/ rationale field now included in response:
- No submission (says didn't submit anything) - status 0
- Submission but not in right state (says they need right state)
- Submission in right state, says it's in the right state (though this could possibly be that multiple submissions were made yet 1 has been correctly placed into this state)
