### ISSUE TITLE
Image styles make gifs look funny

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1802]
Original:
![giphy](https://cloud.githubusercontent.com/assets/3428964/22301749/1fc3a55c-e2fa-11e6-9ea5-6ca016c365d0.gif)

Image Style:
<img width="1440" alt="screen shot 2017-01-25 at 12 30 11 pm" src="https://cloud.githubusercontent.com/assets/3428964/22301743/1b2f672e-e2fa-11e6-8d59-cd439ae637ad.png">

**Comment by btopro** [comment]
should be fixed via normalizer
