### ISSUE TITLE
ELMS:LN Vagrant Default Site Displaying Code Instead of Status

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1810]
## Steps to Reproduce:

- `vagrant destroy` previous vagrant
- `vagrant box remove elmsln/ubuntu16`
- `sh developer`
- Install begins...page hangs on following screen:

![gruberror](https://cloud.githubusercontent.com/assets/7243665/22346812/68a42100-e3d3-11e6-8dc6-355bc4d79e11.png)

**Comment by mmilutinovic1313** [comment]
Additionally, the default screen that appears with `sh developer` returns a blank page with code...

![defaultpagebroken](https://cloud.githubusercontent.com/assets/7243665/22346899/c5f876d0-e3d3-11e6-88a3-7a9c39cafeff.png)

**Comment by btopro** [comment]
yeah that was broken by someone when repackaging the server, never got around to fixing it

**Comment by mmilutinovic1313** [comment]
Sounds good - I'll do a restart to see if that fixes the first issue then. I'll change this issue over to be documenting the white screen with code then:

**Comment by btopro** [comment]
@mmilutinovic1313 low priority but could be a good change of pace to get you experience with something radically different.
The steps to fix this:
- Spin up VagrantFile but JUST the box, not running the install scripts (basically just turn on the server to the blank state)
- log in, the restart apache
- see if the page at the ip address works
- log out of vagrant
- Export the box in its current state (this is commandline via vagrant box command)
- place box file in Box.net
- tell me where it is
- I download and wipe the existing with this file
- I update the atlas listing (vagrant registry) to indicate the box is now at version 1.1
- update box in local vagrant via commandline to pull down this image again
- build VagrantFile, actual file w/ installer, and see if it's all resolved

**Comment by BeardGod** [comment]
![screen shot 2017-01-31 at 5 33 53 pm](https://cloud.githubusercontent.com/assets/14913109/22487495/99139576-e7db-11e6-9a58-43046559c068.png)

I have received the exact same error as the initial of this post

**Comment by btopro** [comment]
@BeardGod crap ok, thanks for the confirmation / evidence. @mmilutinovic1313 was having issues w/ a basebox the other day and I didn't want to blow away my primary work VM if this was legit. I'll start spinning up on personal laptop to see if I can debug what's up w/ the basebox

**Comment by mmilutinovic1313** [comment]
@btopro yep @BeardGod showed me this in class today. I can help work on this in Co-Working tomorrow if you would like.

**Comment by mmilutinovic1313** [comment]
http://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt

This is the command they recommend to run with no prompts:

`sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade`

Additionally, this could explain why this issue appeared all of a sudden? 

> The /etc/default/grub file is generated at package install time, which is necessary because it integrates with debconf.

**Comment by mmilutinovic1313** [comment]
http://askubuntu.com/questions/560685/what-do-i-select-for-grub-install-devices-after-an-update-on-a-vm

**Comment by btopro** [comment]
http://stackoverflow.com/questions/40748363/virtual-machine-apt-get-grub-issue/40751712

**Comment by btopro** [comment]
@mmilutinovic1313 good catch / probable answer. Pull latest of 0.8.x branch and then retry to build fresh (`vagrant destroy` first)

**Comment by mmilutinovic1313** [comment]
@btopro looks good to go - the install moved past where it was erroring. @BeardGod, download the latest version of ELMS and you should be able to get the vagrant up and running

**Comment by btopro** [comment]
nice work mark!
