### ISSUE TITLE
Include revision_delete in all systems

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1817]
follow up from #1615. Like it says, get it worked into each distribution and tested heavily in MOOC and CIS to validate it for the rest.

**Comment by proconnor15** [comment]
I'm working on implementing a minimum time that the revisions must be there before deleted. Should I just set the value to 2 years or should I make it so that you have the option to make it longer if you want?

**Comment by btopro** [comment]
it should be a setting if the year / time value is when to delete stuff

**Comment by btopro** [comment]
code is in place for this with a feature in mooc for testing though it's not implemented yet till it becomes an issue
