### ISSUE TITLE
Cannot Access online.site.com

### ISSUE THREAD

**Issue by serveradmin247** [elmsln/elmsln#1819]
I installed elmsln on a fresh Cebtos7 and installation was success. When tried to access online.site.com I see the PHP error

PHP Fatal error:  Call to undefined function db_query() in /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc on line 349

I tested it on Redhat 7 as well and same error.

**Comment by serveradmin247** [comment]
It works now without doing anything.

**Comment by btopro** [comment]
You may have accessed prior to install finishing. During install the drupal sites can throw notices like this up until they are fully built. Has to do with caching and settings file manipulation during build.

Ubuntu 16 is much faster then the cent based installers and better positioned for the future fyi
