### ISSUE TITLE
Outline Designer Perpetually Says Lesson 1 Before Lesson Title

### ISSUE THREAD

**Issue by Meg5080** [elmsln/elmsln#182]
When I initially click on the content outline I see all of my lesson titles in a pretty row (no mention of lesson numbers  because I overrode that option to simplify my life... The first pic shows what I see... and it is gorgeous. 

After clicking on a lesson title and then returning back to the content outline (no matter what lesson title I click on) it shows a stinking "Lesson One" before each lesson title... see pic two :) 
<img width="568" alt="outline looking lovely" src="https://cloud.githubusercontent.com/assets/13649297/9178384/fdebf81a-3f64-11e5-80a1-97ed8a173186.png">

<img width="445" alt="outline not making logical sense" src="https://cloud.githubusercontent.com/assets/13649297/9178391/0615375e-3f65-11e5-82a7-b6fbabf3493f.png">
 

Is there a different place I edit this feature?

**Comment by btopro** [comment]
This is currently under settings and then System settings `admin/config/system/course-settings`
Under the theme sub-tab there's the ability to do auto label, auto number or none. We're still playing with integrating this correctly so you can disable it for the time being. This is related to #180 as part of the desires for that are to have a per level auto naming and numbering option so you could choose to use that if you want.

**Comment by Meg5080** [comment]
Genius!
