### ISSUE TITLE
Accessible Fallback - selecting existing content types

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1820]
It seems as though when selecting an existing content type for the accessible fallback, you're only able to choose from static content. It would be good if you could choose other existing content types too. 

For example, I've got an interactive video and then an accessible video version which I've uploaded directly and contains captioning and transcript. I know there's a workaround option of adding the shortcode from the video into a static content type - but want to be able to avoid this if possible.

**Comment by btopro** [comment]
And then when you add questions to the video and need to write them out to accompany the accessible fallback you will play them... ?

**Comment by rickhumphries** [comment]
Hmm, yeh I see what you're saying. It seems a bit restrictive but makes sense

**Comment by btopro** [comment]
I mean it's not that hard to extend though it'll make it harder to find what ur looking for until we replace entity references with some nicer way of finding things to relate.  Anyway, do you think it should be ALL types available for fallback? Also thinking about the #1302 if maybe we couldn't hard code these as accessible, print, mobile sorta things. Then if they exist (or it can be reasonably detected that event is happening) then deliver that version.

**Comment by rickhumphries** [comment]
Yeh #1767 definitely ties into this too. I guess I'm jumping on the accessible fallback idea and trying to use it as an alternative format type of thing as well. So allowing to select from all content types just gives that added bit of flexibility. 

I also wonder whether (down the line) you might have media types which suit particular disability profiles, which you can tag, then the media delivered would depend on the disability profile set by the user in People. Just thinking long term, but in that situation you'd want to be able to select from ALL content types too.

**Comment by btopro** [comment]
true. cool idea on the disability profile. We do have something like that in the pipeline but I like the term you used for it better #1000 .

**Comment by btopro** [comment]
from
![2017-01-30_13-49-59](https://cloud.githubusercontent.com/assets/329735/22436683/11ba4c98-e6f3-11e6-8965-d01fda27c58f.png)

to this
![2017-01-30_13-50-16](https://cloud.githubusercontent.com/assets/329735/22436676/0c164c06-e6f3-11e6-96e4-ae5a65e2f01c.png)

**Comment by btopro** [comment]
ok, can select images, audio, documents, svg's, video, and external video sources as well.
