### ISSUE TITLE
ELMS:LN Website Remodel

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1825]
Currently working on redoing the ELMS:LN website in Jekyll. I'll post my status here via a checklist and link to my project for code references. We can do staging testing using github pages as Jekyll is cool like that ;)

**Comment by mmilutinovic1313** [comment]
https://github.com/mmilutinovic1313/elmsln-website

**Comment by btopro** [comment]
https://github.com/OpenCollective/OpenCollective/wiki/Website-banner

**Comment by btopro** [comment]
https://github.com/BlackrockDigital/startbootstrap-new-age love this btw, @mmilutinovic1313 super simple starting point that's static / forkable / MIT license. Be nice for like "ELMS in a minute" sorta page and then clicking into more info after the scroll down could go to the other parts of a site taht are more dynamic (like a blog)

**Comment by mmilutinovic1313** [comment]
I'll look into this as well. It looks like a better forking point than what I was working on with the Jekyll site as this template is more of what we would want stylistically

**Comment by btopro** [comment]
seems simple enough to copy and paste our way to what we want :)

**Comment by mmilutinovic1313** [comment]
This is where github pages version will live: https://mmilutinovic1313.github.io/elmsln-website/

**Comment by btopro** [comment]
nice

**Comment by mmilutinovic1313** [comment]
Apereo stuff is in - we just need some backers to get users to show up there ;)

**Comment by btopro** [comment]
@mmilutinovic1313 make sure there's a part of the site that's like a "As seen in" section. Between me, katrina, potter and collins we've got plenty of places we're showcasing elms this year (and in past years) and it would be helpful to list out some of the biggies we've been to.

Also maybe some kind of Implementations in practice or something were we can have example screenshots as well as links to articles and public deploys

**Comment by mmilutinovic1313** [comment]
That sounds like a good idea. Do you like the idea of a blog section to the site? Or perhaps that section could link to external articles as well as articles we've written? Not exactly sure how that would work but I will look into it! 

Also - Do you think it is worth it to convert that template to a Jekyll build for simplicity? Jekyll instead of raw bootstrap might be easier to write blog posts in and update information? I'm not 100% sure as I have not made a raw bootstrap site yet, so this is new territory :). Let me know your thoughts on this!

**Comment by btopro** [comment]
Yeah like an articles section of something

**Comment by btopro** [comment]
could just be a polymer element you know, to build even more stuff to do stuff

**Comment by mmilutinovic1313** [comment]
That's true - let's shoot for that then cuz that allows us to naturally increase the amount of polymer elements we have available in general.

**Comment by mmilutinovic1313** [comment]
Update: Flushed out homepage a bit more. I want to rearrange the way information is displayed, as right now the template still has too much scrolling. I've also been looking at different gallery/team pages on the website to figure out what design I like best. I plan on pushing up one of the bootstrap templates I've found later this weekend / next week.

**Comment by mmilutinovic1313** [comment]
Some more inspiration: https://openideo.com/

**Comment by mmilutinovic1313** [comment]
Gonna make a list of Webcomponents I find here:

- https://www.webcomponents.org/element/oscarmcm/profile-vcard

**Comment by mmilutinovic1313** [comment]
Okay - so now that we have webcomponents installed locally we can start creating components for sections of the website. The list is as follows:

- [ ] Features Card - Image, Title, Description
- [ ] Social Media Card - Logo, Link, Overtitle, Untertitel 
- [ ] Team Card - Round Image, Purpose, Description, College Button, Social Media(?)
- [ ] Blog Page - Need to think about this one in more detail

**Comment by mmilutinovic1313** [comment]
@btopro how do you feel about linking bios to twitter profiles?

**Comment by btopro** [comment]
twitter should be in there but you need to have a small bio

**Comment by mmilutinovic1313** [comment]
Do you have the original email or PDF of the presentation for this blog post? 
https://www.elmsln.org/blog/post/lms-implementation-webinar-featuring-elmsln

**Comment by btopro** [comment]
no, u can kill it if it's screwing up the render as Im sure it is

**Comment by mmilutinovic1313** [comment]
Blog posts completed! Moving on to style improvements for blog and user profiles. Also adding a static HTML template page that will be able to render static web page content (z.B. an about page or basic page).

**Comment by btopro** [comment]
nice. publicly accessible yet?

**Comment by mmilutinovic1313** [comment]
Added .sh script you mentioned. Wanted to check if you wanted this project to be placed in a different project (i.e. in the LRNWebComponents project or somewhere else). Working on making the demo publically accessible while I continue working on making things better.

**Comment by mmilutinovic1313** [comment]
@self I see that I'll leave it where it is now based off of twitter reply

**Comment by mmilutinovic1313** [comment]
Creating a new issue about Polymer caching previous page content and displaying it on other pages it shouldn't be...

**Comment by mmilutinovic1313** [comment]
@btopro working some more on the design of this site. Want to get it to more of a "finished state" so all that has to be done is to put the data in!

**Comment by btopro** [comment]
Sold

**Comment by btopro** [comment]
#878 #2300

**Comment by btopro** [comment]
merging into #1825
