### ISSUE TITLE
Legacy "hidden" pages no longer hidden

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#183]
Hi, I have legacy pages from a prior system where the parents and children were hidden. Now, in ELMSLN, they are showing and I have to go in by hand and Un "Publish." 
Two issues...
how do i know which pages were previously hidden (beyond going back and comparing)? 
is there a quicker way to re-hide them again beyond going in and unpublishing them one at a time? Thanks.
https://courses.ed.science.psu.edu/chem005/node/104 (Lessons 13-15 were formerly hidden---the main reason I knew that is cos they were blank. Some courses will not be so obvious to me if I haven't been in them lately)

**Comment by btopro** [comment]
Unpublish or you mean hidden via the "hidden nodes" project? You can remove them from the UI (at least from students seeing) by using the outline designer. Click the edit button next to Lesson 13 - 15, and hide that item. This will remove it from the UI

**Comment by juststormy** [comment]
I did click hide. They didn't look grayed out so I didn't think it had worked. Sorry.

**Comment by btopro** [comment]
Yea you'll probably just get a message for the time being while on that page. We're still working the hidden aspect into the UI / flyouts.  believe they should have an eyeball w/ a cross through it in the icon but I'm not positive.
