### ISSUE TITLE
Student Name

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#1835]
Is there a way to  include a field for Studio posts that says the students' names? Ideally right below the title of each submission. Right now you have to click through to to see the details of each post and it only shows the student's PSU username.

**Comment by btopro** [comment]
@heyMP Im thinking maybe we add a field to the user object that's like the RealName field in drupal where there's a username but then there's how the user wants to be presented. We can pull this field from their distributed profile in the project as a whole but for a more immediate win, we could just use the user object alter ability to ping their username off ldap and display whatever that says.

**Comment by btopro** [comment]
merged into #1816
