### ISSUE TITLE
Content Outline Icons Not Uniform Size on Mobile Device

### ISSUE THREAD

**Issue by Meg5080** [elmsln/elmsln#184]
![screenshot_2015-08-10-14-09-03](https://cloud.githubusercontent.com/assets/13649297/9179374/24494e7c-3f6a-11e5-8dfc-fc7bd5037ea8.png)

Third book icon down is miniature. I can't tell any apparent differences on the edit page screen from that page to the others.

**Comment by heyMP** [comment]
Looks like a flexbox issue.  We'll explicitly set a width on those so they are uniform.  Thanks!
