### ISSUE TITLE
APDQC Lock Issue on vagrant halt to sh developer

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1843]
So I know I've mentioned this before, but in my environment whenever I run `vagrant halt` and then `sh developer` again I receive the following error message when I go back into my online.elmsln.local instance. 

![apdc_lock](https://cloud.githubusercontent.com/assets/7243665/22525955/6532738c-e897-11e6-8583-97a0a319ab57.png)

Additionally when I run `drush @online cc all` I get an error telling me that a drupal site cannot be found. This was a clean install and re-up of vagrant from this morning with no changes to the codebase. So I'm not sure if something else is getting screwed up in the install routine that's causing this. Next step will be a machine reboot and I will update here if that changes anything.

**Comment by mmilutinovic1313** [comment]
So this seems to be related to the OS version I have (possibly). I am running into this on the following type of machine: 

- MacBook Pro (13-inch, Mid 2012)
- MacOS Sierra 10.12.2
- 2.9 GHz Intel Core i7

This is overkill with specs. But I am writing documentation to denote that one should run the following command if vagrant hangs up and presents the `apdqc_lock_aquire()` Error: 

- `vagrant ssh` (within the elmsln folder where you usually do `sh developer`)
- `sudo -i`
- `service mysql restart`

This should remove the error and allow you to continue smoothly :)

**Comment by mmilutinovic1313** [comment]
https://github.com/elmsln/elmsln/pull/1844 - this adds documentation.

**Comment by btopro** [comment]
good work keeping on this
