### ISSUE TITLE
Infinity Symbol not displaying 

### ISSUE THREAD

**Issue by kmiffitt** [elmsln/elmsln#1851]
Bug:

Using both the keyboard shortcut and Mathjax, I've tried to insert infinity symbol. It looks correct in editing mode, but appears as a ? when saved. To be fair, it's a fancier ? when using Mathjax. 

https://courses.aanda.psu.edu/frnphoto/node/106

**Comment by mmilutinovic1313** [comment]
I can't see the image as I don't have access to the course, but my guess is this would be an encoding error with Unicode or UTF-8 (not sure what is being used where). I'll see if I can recreate this in my local install.

**Comment by btopro** [comment]
@kmiffitt give it a shot now, you might need to resave pages to have it reflected on other pages. @mmilutinovic1313 is correct, we had a filter to ensure "normal" UTF and infinity gets into the extended stuff. I disabled the filter doing it on this one course for now
