### ISSUE TITLE
Make a textbook mathjax module

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1852]
Textbook has settings that conflict with Mathjax. We should make a module that specifically modifies the values of textbook in order to achieve the same effect but with 1 feature being enabled as well as ensuring we don't lose specific settings when doing upgrades.

@mmilutinovic1313 this is a tricky one as it involves feature overrides but would be a legit useful contribution to the textbook module as a sub-project

**Comment by mmilutinovic1313** [comment]
Sounds good to me. Are some of these settings related to the UTF-8 bug previously mentioned? Or was that just a custom setting on a local install? I'll take a look at this and probably start working on it next Monday.

**Comment by btopro** [comment]
mathjax module on
UTF validation off (input filter)
wysiwyg mathjax on
mathjax on (input filter)

**Comment by btopro** [comment]
@mmilutinovic1313 see resolution / commit from #1872 as it simplifies what this has to be (1 less thing to account for in features override)

**Comment by btopro** [comment]
Now we have a textbook submodule called textbook_mathjax
