### ISSUE TITLE
Documentation Request: PC Environment Instructions

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1853]
I think we should add instructions for PC install support. Whether this is "Download a Unix Command Line Tool" or setup instructions themselves. I'm testing out the steps presented in this article (http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) as an example for getting a PC environment to use Unix commands.

**Comment by ernharthsw** [comment]
![windows command error](https://cloud.githubusercontent.com/assets/25517075/22571403/991815a4-e96d-11e6-80ae-bd33d32bfb9e.JPG)

**Comment by rickhumphries** [comment]
I use putty.exe as my command line tool on a PC (http://www.putty.org/)

In fact, I could probably write this guide if you like?

**Comment by mmilutinovic1313** [comment]
@rickhumphries that would be great!

**Comment by btopro** [comment]
cygwin

**Comment by rickhumphries** [comment]
Just looked at cygwin..think I got the wrong end of the stick. My guide would pretty much be, get a digital ocean server, download putty, use that to log into server,  how to change host file.. etc. Can do that if that's what you meant but anything else is beyond me I reckon

**Comment by btopro** [comment]
lol

**Comment by btopro** [comment]
Vagrant works on PowerShell if you run as an admin too btw

**Comment by mmilutinovic1313** [comment]
I'll figure this out once I pull up my Windows partition

**Comment by btopro** [comment]
#1868 doesnt have a ton of implications for this but worth mentioning that the install routine for vagrant has been simplified

**Comment by mmilutinovic1313** [comment]
I was shown that the git download listed on the install file can be used to run unix commands and should fix the command problems for windows users.

**Comment by mmilutinovic1313** [comment]
Closing as merged
