### ISSUE TITLE
H5P Statement Overload

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1856]
I know this has been raised against the H5P Bridge module itself here https://www.drupal.org/node/2589945 so let me know if this should be a comment on there instead..

I get overloaded with the 'attempted' verb quite a lot. For single questions like 'fill in the blanks' it creates an 'attempted' statement every time the page loads (even when you're working in it within Media - though this will solve that... https://www.drupal.org/node/2607828). For questions sets, it's every time you move between a question. 

I've seen the fix for this sort of thing here - https://github.com/elmsln/elmsln/commit/66410a50aaae43d6b50826bde3e13141072013d6

Is this just for the 'interacted' verb though? Or should it be reducing the 'attempted' verbs too?

![image](https://cloud.githubusercontent.com/assets/4973810/22742362/6a470a5a-ee0e-11e6-8915-b34f6312cdb1.png)

**Comment by btopro** [comment]
I believe the specific issue ur pointing to is resolved in 0.7.0 (by ignoring these on textfields) but I might have missed some cases. And yes, xAPI = data flood sometimes :)

**Comment by btopro** [comment]
This is currently for `interacted` and not `attempted` do you know what is generating that many attempteds?

**Comment by rickhumphries** [comment]
The H5P content type that was causing it in this case is 'Fill in the Blanks'. An `attempted` statement is generated each time the page loads, whether the user interacts with the question or not. I'm not sure if there are other content types this happens with too though

**Comment by btopro** [comment]
- [ ] expand reduceStatements to reduce these type of statements of at least verify if they do

**Comment by btopro** [comment]
@cgldevel tagging you on this since your our resident H5P'er. I believe your instance is wired up to learning locker so it would be good to make some sample H5P's or look through existing courses to see if there's any that are basically flooding the learning locker instance. Not only do we not need these statements they will bog up the database which I know you all want to start using xAPI data and visualizing it for students (us too)

**Comment by cgldevel** [comment]
@btopro I just had @heyMP give me a quick tour of our instance; the real-time interaction is pretty awesome.  I'll bet this makes it into H5P talk at DCPA \m/
