### ISSUE TITLE
Support for xAPI recipes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1864]
Having seen the recent work with beacons and xAPI. I wondered whether the next step to make things more interoperable is to include support for xAPI recipes.

For example, should the triggering of a beacon support the 'attendance' recipe?  (Described here http://tincanapi.com/new-recipe-attendance/ and actual recipe here https://registry.tincanapi.com/#profile/48)

There's a whole registry of activity types, verbs, profiles etc. https://registry.tincanapi.com/ that can be used when doing custom stuff.

**Comment by btopro** [comment]
so these are more like structuring meaning intentionally into the way you make a record instead of just saying "they did something" it's "here's how we express them attending a meeting" sorta deal, is that the gist?

**Comment by rickhumphries** [comment]
Yep, that's pretty much the gist :)

**Comment by btopro** [comment]
hmm.. so what do we have to do to support these? like recalling them or submitting them?

**Comment by btopro** [comment]
I'm not sure what supporting this entails other then we'd need to know what we're looking for / tracking as a recipe. I think this is more of "we should do this as we expand statement usage" but isn't really directly actionable
