### ISSUE TITLE
No Timer Icon (Attendance) In Upper Right Corner

### ISSUE THREAD

**Issue by michellelowman** [elmsln/elmsln#1867]
Bug:
- ELMSLN version/commit reported on admin/reports/status
Timer icon does not display on the home screen, in the upper right corner, as usual, upon login.

- What happens
All other icons seem to appear, except for the Timer.

- What you expected to happen
The Timer to be there allowing both our AZDL 
![attendancescnsht](https://cloud.githubusercontent.com/assets/25618711/22859848/f176e072-f0a7-11e6-965a-3a46154528f5.jpg)
customers and ourselves to enter and verify attendance

Feature request:
- What you are trying to do / where it should go
![attendancescnsht](https://cloud.githubusercontent.com/assets/25618711/22859851/0ba21a66-f0a8-11e6-91cb-5b736b5c42e5.jpg)

**Comment by btopro** [comment]
? I think you have the wrong project as we don't have connotations like that on our ui

**Comment by michellelowman** [comment]
Did you see thw screenshot I included?

Up by the house icon, there should be a timer/clock.  Are you telling me that entire UI is not the UI belonging to the ELMS that you support?

**Comment by michellelowman** [comment]
The issue as resolved itself and the Timer/Clock icon is back, as you can see from the below screenshot

![image](https://cloud.githubusercontent.com/assets/25618711/22884414/08c2d550-f1b2-11e6-9ed1-4e824c283c1e.png)

**Comment by btopro** [comment]
I've never seen this solution but no I don't believe this is elms. ELMSLN doesn't look like this and the Drupal 6 ELMS system is unsupported / also didn't look like this. I believe this is a custom solution that happens to also be called ELMS
