### ISSUE TITLE
Support injection of ELMS context into non-ELMS systems

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1869]
Yeah, we're going to go here via https://www.webcomponents.org/

As we explore webcomponents further, @heyMP had a pretty incredible idea that I don't want to be lost since I just remembered its not in the repo anywhere. What if ELMS's "lmsless" bar was a component. At first, this is just simple, makes perfect sense design principle. If we have a `<elmsln-lmsless></elmsln-lmsless>` tag, then *we* can use it to simplify design.

But then he took the idea further: "Then we could implement that tag on any non-elms system to supply the same UX pattern".

Yup.

Taking a page from the Stripe credit card processing as tag paradigm. If we had support for registering applications in elmsln, w/ an option being for remote UX delivery, we could give people a copy and paste code which would see their ELMS based account, user experience, possibly even data tracking, extended out into non-CMS based systems / the general web. Granted, it's the web that's still controlled by someone, but this would allow for complete decentralization of the experience. ELMSLN is the hub w/ it's baseline tools for stitching together and orchestrating the ecosystem *even beyond it's own walls*.

Architecturally, this would be critical in our pursuit to never just become another bs lms.

- Register tool w/ elms
- elms generates token / tag
- copy and paste into any website
- At runtime, elms injects the lmsless banner into the space at the top
- this turns any website we can get our tag into to have a consistent UX pattern

**Comment by rickhumphries** [comment]
lol well I can confirm there's definitely a use case for this . Look what we've just done with our assessment system!

![image](https://cloud.githubusercontent.com/assets/4973810/22900679/16c4cfbc-f227-11e6-9cdc-9eeadcfa4f6e.png)

**Comment by paulhibbitts** [comment]
You might also be interested in another example with the Grav Course Hub, where a flag can be passed in a URL so that all header/footer chrome is not displayed.

For example, here is a regular Course Hub page:
https://paulhibbitts.net/cmpt-363-163/home/week-01/

And here is the flag with URL to display the same content sans header/footer:
https://paulhibbitts.net/cmpt-363-163/home/week-01/onlydisplaypagecontent:true

This makes the experience of embedded Course Hub content much less confusing, let's say within Canvas:
https://canvas.sfu.ca/courses/28233/modules/items/557928

Cheers,
Paul

**Comment by btopro** [comment]
@paulhibbitts sounds like our Entity Iframe mode / display mode thing that can strip the UI

**Comment by btopro** [comment]
![2017-02-22_09-58-41](https://cloud.githubusercontent.com/assets/329735/23217282/b3bf4d0e-f8e6-11e6-8943-c66a535c53a2.png)

**Comment by btopro** [comment]
Using the ideas from the xapi bookmark let injector, we could allow users to inject elms into any website of their choosing and then using this capability ship things back to base like activity statements via xapi or having like an elms remote control for the Internet to keep the active assignment they are working on present across other systems

**Comment by btopro** [comment]
This is possible now that we move down the webcomponents route
