### ISSUE TITLE
Remove the spoken word on the 404 page

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1871]
Feature request:
- Although a cool easter egg, If I hear "I'm sorry Dave, I'm afraid I can't do that" one more time I'm going to completely loose my mind. 😜

**Comment by btopro** [comment]
@heyMP go to more pages that actually exist ;)

**Comment by michael-collins** [comment]
I agree with @heyMP .

**Comment by btopro** [comment]
gone. type more accurately in the future or ELMS:AI will do more then just annoy you ;)
