### ISSUE TITLE
Session Expiration for Bakery Master Site

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1877]
Issue linked to #920 

We currently use the elmsln bakery setup to handle authentication between systems but have the CIS as the master site.

Each of the slave sites will log the user out after a certain amount of time, however this is never the case for the master site/CIS. The user will stay logged in until someone is logged out. Is it possible to set the session expiration time to be the same as the other systems?

**Comment by rickhumphries** [comment]
We currently have the following code in share_settings which may be related - or may need an additional setting here
```
$databases['default']['default']['init_commands']['isolation'] = "SET SESSION tx_isolation='READ-COMMITTED'";
$databases['default']['default']['init_commands']['lock_wait_timeout'] = "SET SESSION innodb_lock_wait_timeout = 25";
$databases['default']['default']['init_commands']['wait_timeout'] = "SET SESSION wait_timeout = 600";
$databases['default']['default']['init_commands']['join_buffer_size'] = "SET SESSION join_buffer_size = 8388608";
$databases['default']['default']['init_commands']['read_rnd_buffer_size'] = "SET SESSION read_rnd_buffer_size = 8388";
$databases['default']['default']['mysql_db_type'] = '';
```

**Comment by btopro** [comment]
that's the database query engine, doesn't impact bakery timeout. Bakery timeouts I believe are tied to the timeouts of PHP sessions which is a setting in settings files I believe.

**Comment by rickhumphries** [comment]
Ok cheers, I'll take a look

**Comment by rickhumphries** [comment]
So the PHP sessions look set at 2.3 days from the looks of things which looks standard for Drupal:
```
 * Set session lifetime (in seconds), i.e. the time from the user's last visit
 * to the active session may be deleted by the session garbage collector. When
 * a session is deleted, authenticated users are logged out, and the contents
 * of the user's $_SESSION variable is discarded.
 */
ini_set('session.gc_maxlifetime', 200000);

/**
 * Set session cookie lifetime (in seconds), i.e. the time from the session is
 * created to the cookie expires, i.e. when the browser is expected to discard
 * the cookie. The value 0 means "until the browser is closed".
 */
ini_set('session.cookie_lifetime', 2000000);
```
However, there's also a setting on the bakery configuration page which is set to 1 hour:
![image](https://cloud.githubusercontent.com/assets/4973810/23044848/eb31667e-f499-11e6-8d96-b7366ecb823b.png)

So it looks like all the slave sites are adopting the bakery configuration settings but the master site is adopting the php session setting in the setting file? Will have to arrange to change that value to confirm.

**Comment by btopro** [comment]
hmm yeah it appears currently we aren't setting a default value for that w/ elmsln_bakery. Might be worth doing to at least make sure they are in alignment.

If this is something like `$conf['bakery_freshness'] = 86400;` in your shared_settings.php then you'd at least have them all standard at a day. I wonder what a good length would be (standardizing them would help resolve what you reference though)

**Comment by btopro** [comment]
We could at least force a baseline to be the same and do this in the included shared_settings w/ the project. @rickhumphries did you have something in mind or just that they be uniform?

**Comment by rickhumphries** [comment]
Yeh I think having them uniform is the main thing. I think all situations will be different, so having this configurable from shared settings would be good. A day would probably work across the board as a good default. We would probably change it to an hour or something because we get a lot of training going on within the pharmacies themselves - so a lot of people sharing computers to log into etc.

**Comment by btopro** [comment]
@rickhumphries ok, there's a default of 1 day. Changing in your local shared_settings.php you can make it something more like an hour.
