### ISSUE TITLE
Print PDF Error

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1879]
Bug:
- 0.6.3

When I try to print a page as a PDF, it says that the site can't handle the request. Then on reloading the page, Drupal gives me the following error:

`Warning: require_once(/var/www/elmsln/core/dslmcode/shared/drupal-7.x/libraries/dompdf/lib/fonts/Font_TrueType.php): failed to open stream: No such file or directory in Font::load() (line 51 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/libraries/dompdf/lib/fonts/Font.php).`

I'm not using or referencing any additional fonts though.

**Comment by btopro** [comment]
hmm.. does this happen on every page or just some? Wondering if it's related to the type of font that's involved.

**Comment by rickhumphries** [comment]
Yes it happens on every page except one. Although there's actually nothing really special about that page - it's the same as all the others so a bit weird. The first time it tried to generate a PDF for the page that works took aaaages though but now it's instantaneous. I've also added all the settings for it to pick up our custom style sheets, but the page that works doesn't show any CSS stylings either

**Comment by btopro** [comment]
weird, I just did it from a few different deploys successfully, though I have experienced what you are talkng about before

**Comment by btopro** [comment]
Im running 0.7.0 or 0.8.x tho so could be related

**Comment by rickhumphries** [comment]
We should be upgrading to 0.7.0 next week so I'll check again then. When you generate a PDF is it picking up the materialize CSS too? Or can you get it to pick up any custom CSS if you provide a reference to a stylesheet here - `admin/config/user-interface/print/common` ?

**Comment by btopro** [comment]
ummm... not positive, I've got the MaterialCSS in the Print mode but not the Print PDF (to my knowledge).

Should hit up 0.7.1 at that point, I can cut a release of that shortly as it's got a lot of little improvements -- https://github.com/elmsln/elmsln/milestone/17?closed=1

**Comment by btopro** [comment]
little deeper in the weeds

**Comment by btopro** [comment]
Many PDF printing issues were stomped recently that fixed issues like this; hopefully it's gone though in the future PDFs will be handled by #2168
