### ISSUE TITLE
Learning Locker Link Up

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1880]
v0.6.3

I just want to check that I've got my hook up to learning locker setup correctly. At the moment I've got my authentication details in the share settings file and all the set up in Media. 

On the course page itself - I've got one interactive video, which I'm getting statements coming through for on the related data page (excellent):
![image](https://cloud.githubusercontent.com/assets/4973810/23094990/80cafa5e-f5fa-11e6-8024-01385897008b.png)

However, there's nothing being recorded against the actual media type in Media...
![image](https://cloud.githubusercontent.com/assets/4973810/23094995/a7f48d48-f5fa-11e6-8b38-b0db99bf80ea.png)

Also, on the related data page within the course site - I can view a list of users who have completed the interactive video:
![image](https://cloud.githubusercontent.com/assets/4973810/23095028/04cb782e-f5fb-11e6-8924-9db2a8a96a33.png)

However, when I click on one of the user's names, it says that there haven't been any statements generated by that user...
![image](https://cloud.githubusercontent.com/assets/4973810/23095043/414a7796-f5fb-11e6-8a30-2e40ea57b7fe.png)

**Comment by btopro** [comment]
It's recording fine, those queries to pull back the data are unfinished :) so you are seeing moly correct info that sees some more improvements in 070 and even more in 071 though the media and user pages are still screwed up

**Comment by rickhumphries** [comment]
That's cool, loving it anyway, but just wanted to make sure I had all the settings in the right place :)

**Comment by btopro** [comment]
Merged into 1542 since these were known issues but I didn't have them documented anywhere
