### ISSUE TITLE
Windows Install Problems

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1886]
I have been shown that PCs are having difficulties running the sh developer script. Below is a collection of screenshots of the sh developer command on PCs. I had group members install the git bash program which could run unix commands, however, this did not seem to fully solve their issues of the install finishing. 

![1](https://cloud.githubusercontent.com/assets/7243665/23172215/1531644c-f823-11e6-9c8c-dad154770624.jpg)
![1920x1080 jpeg](https://cloud.githubusercontent.com/assets/7243665/23172230/21b1004c-f823-11e6-82ba-3585f6da0be2.jpg)

**Comment by mmilutinovic1313** [comment]
- Biggest concern `developer: line 4: open: command not found`

**Comment by btopro** [comment]
That script doesn't work on windows that's why, lol

**Comment by btopro** [comment]
just vagrant up. You can't run SH scripts correctly on windows and the commands in that are geared specifically toward OSX development

**Comment by mmilutinovic1313** [comment]
Good to know - I'll tell them to run that instead. Can they do that on their regular terminal? Or should they use the unix-based one still?

**Comment by btopro** [comment]
probably regular? not sure but maybe we do need a timeout value. Research that

**Comment by btopro** [comment]
`config.bm.boot_timeout`

**Comment by mmilutinovic1313** [comment]
Will research - whenever I got the timeout errors it seemed to work on the Mac.

**Comment by btopro** [comment]
@bradallenfisher have you ever heard of this setting / experienced it b4? I know we all unfortunately use Mac's when PC land exists. I feel like it's related to not having enough resources to run it but not positive

**Comment by mmilutinovic1313** [comment]
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\markymark1346>dir
 Volume in drive C is BOOTCAMP
 Volume Serial Number is B4B0-9B1C

 Directory of C:\Users\markymark1346

02/21/2017  02:41 PM    <DIR>          .
02/21/2017  02:41 PM    <DIR>          ..
02/21/2017  02:40 PM    <DIR>          .VirtualBox
02/10/2017  11:26 AM    <DIR>          Contacts
02/10/2017  12:04 PM    <DIR>          Desktop
02/21/2017  02:41 PM    <DIR>          Development
02/10/2017  11:26 AM    <DIR>          Documents
02/21/2017  02:30 PM    <DIR>          Downloads
02/10/2017  11:26 AM    <DIR>          Favorites
02/10/2017  11:26 AM    <DIR>          Links
02/10/2017  11:26 AM    <DIR>          Music
02/10/2017  11:26 AM    <DIR>          Pictures
02/10/2017  11:26 AM    <DIR>          Saved Games
02/10/2017  11:26 AM    <DIR>          Searches
02/10/2017  11:26 AM    <DIR>          Videos
               0 File(s)              0 bytes
              15 Dir(s)  264,617,713,664 bytes free

C:\Users\markymark1346>chdir Development

C:\Users\markymark1346\Development>dir
 Volume in drive C is BOOTCAMP
 Volume Serial Number is B4B0-9B1C

 Directory of C:\Users\markymark1346\Development

02/21/2017  02:41 PM    <DIR>          .
02/21/2017  02:41 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  264,617,717,760 bytes free

C:\Users\markymark1346\Development>git clone https://github.com/elmsln/elmsln.gi
t
Cloning into 'elmsln'...
remote: Counting objects: 107790, done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 107790 (delta 97), reused 0 (delta 0), pack-reused 107484
Receiving objects: 100% (107790/107790), 362.17 MiB | 2.42 MiB/s, done.
Resolving deltas: 100% (54830/54830), done.
error: unable to create file core/dslmcode/stacks/interact/sites/all/modules/loc
al_contrib/entityreference_dynamicselect_widget/entityreference/examples/entityr
eference_behavior_example/plugins/behavior/EntityReferenceFieldBehaviorExample.c
lass.php: Filename too long
error: unable to create file core/dslmcode/stacks/interact/sites/all/modules/loc
al_contrib/entityreference_dynamicselect_widget/entityreference/examples/entityr
eference_behavior_example/plugins/behavior/EntityReferenceInstanceBehaviorExampl
e.class.php: Filename too long
Checking out files: 100% (21393/21393), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'


C:\Users\markymark1346\Development>
```

**Comment by mmilutinovic1313** [comment]
This is with the normal command line tool

**Comment by mmilutinovic1313** [comment]
Filename too long occurs on both the `CMD` terminal and the `Unix-based` terminal.

**Comment by mmilutinovic1313** [comment]
After running the install - I get the apache landing page

**Comment by mmilutinovic1313** [comment]
It is working now - I have a working install on PC. All you need is Unix command support in general (this appears to come from installing git). Vagrant up takes care of the rest.

**Comment by mmilutinovic1313** [comment]
User Reports Windows 10 - version 1607 is causing the timeout error. I do not experience this running 8.1.

![image](https://cloud.githubusercontent.com/assets/7243665/23188329/5140f130-f85c-11e6-800b-529e25fb1bb8.png)

**Comment by btopro** [comment]
between http://stackoverflow.com/questions/32731629/where-to-find-config-vm-boot-timeout and https://github.com/mitchellh/vagrant/issues/2973

it seems an easy fix (hopefully). ELMSLN also spins up asking the host OS for 2 gigs of RAM on windows, basically guaranteeing it takes longer to do everything. fixing the timeout limit, if that doesn't fix it it might be something else (like age of machine / Windows being a jerk to Vagrant)

**Comment by btopro** [comment]
if this didn't fix it keep working on it but not sure there's much we can do other then dig into stack exchange for "why is windows stupid at times?" :)
