### ISSUE TITLE
Comments Feature 

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#1895]
One of the professors would like to see a holistic view of who has left comments on a given assignment, without looking at every image and writing a list of who commented. This could either be a generated list of all students who commented on a given assignment, or something like the Canvas discussion boards where you can search for a given student within the comments for an assignment.

**Comment by btopro** [comment]
- [ ] export feature added into DMD201 to start to get at this as it's universally useful even if simplistic currently
