### ISSUE TITLE
Site error message during upgrade routine - field_campus field

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1896]
I get this error message each time we run an upgrade routine:
```
Site:           https://online.co.uk
Severity:       Error (3)
Timestamp:      2017-02-23 14:10:16
Type:           features
IP Address:     127.0.0.1
Request URI:    https://online.co.uk/
Referrer URI:
User:           Anonymous (0)
Link:
Message:

Attempt to update field field_campus failed: A list field (field_campus) with
existing data cannot have its keys changed.
```
Doesn't cause any issues particularly that I can see, other than the message

**Comment by btopro** [comment]
This doesn't cause issues, it has to do w/ us having new default / fallbacks. At some point this probably will just have to be "text" since it ships w/ default values which will never be used.
