### ISSUE TITLE
Issue pulling info from CIS in Courses - welcome page/resources etc.

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1898]
Bug:
- 0.7.1

When switching to a new section in a course outline, the 'welcome' message doesn't display and the following error message appears:
![image](https://cloud.githubusercontent.com/assets/4973810/23269248/da40df72-f9e7-11e6-90de-8ed57896e86e.png)

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'elmsln_core_data_form' not found or invalid function name in drupal_retrieve_form() (line 842 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/form.inc).`

**Comment by btopro** [comment]
Cache clear resolves.

**Comment by rickhumphries** [comment]
ah so that's brought the info over. I'm still getting the error message and majority of the html is being lost also - only the link tags look like they're brought over:

![image](https://cloud.githubusercontent.com/assets/4973810/23269799/a48e18b6-f9e9-11e6-9797-897dccd7d436.png)

This is how it appears in the inspector:

![image](https://cloud.githubusercontent.com/assets/4973810/23269825/bcb30bb8-f9e9-11e6-8874-d2fcf9bf4fca.png)

**Comment by btopro** [comment]
hmm it might have shown the error once but that error should go away. may want to log in and run
`drush @elmsln cc menu --y`

which will frag just the menu cache (which is what's out of sync as per that message)

**Comment by btopro** [comment]
as far as content being filtered... I gotta think on what would do that bc we haven't experienced that.

**Comment by rickhumphries** [comment]
ran that command just now but error message still displays unfortunately. It also displays if I masquarade as a student

**Comment by btopro** [comment]
DM me what link ur on that this happens I can't replicate it even on a welcome page of a course in your deploy
