### ISSUE TITLE
Import files with cache busting strings

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1899]
Compiling angular apps for production creates files with cache-busting strings.

Here is how we are importing the cle app currently: https://github.com/elmsln/elmsln/blob/master/core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/cle_app.module#L15-L19

The files have to be imported in that order, however they will have cache busting strings on them like this:
```
inline.a2006e204e8c70f100ab.bundle.js
```

**Comment by btopro** [comment]
@heyMP this works both with and without production angular files so it'll target either one and then forces them to load in the right order
