### ISSUE TITLE
Button for ToC

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#190]
Would be nice to both modify the container type for folder to display LITERALLY everything below it, not just 1 level.  Then we could have a ToC button that would show you the entire course outline at once.

This might be a nice alternate navigation method for desktop based nav to replace the slide out.

**Comment by btopro** [comment]
Or ToC could pull above the UI; on mobile it's the Hamburger but when on desktop this could use modal overlay to have the whole thing presented as open

**Comment by btopro** [comment]
extremely functional / optimized prototype of the ToC nav. I think we may have something here...

https://www.youtube.com/watch?v=7q1vbqfeIOc

**Comment by btopro** [comment]
@michael-collins @michael-collins --^

**Comment by btopro** [comment]
#180 related

**Comment by rickhumphries** [comment]
Yeh really like it @btopro. Just a couple of things though. Would there still be support for Unit based menu in the ToCs? (shown in early prototype here https://youtu.be/xvkOpgFELQI). So you could have a separate ToC per Unit if you wanted to? I also think it'd be useful to be able to expand/collapse parent nodes in the ToC similar to outline designer, and have an expand/collapse all button too

**Comment by btopro** [comment]
Feedback from an ID via email:

1. "Jump to" active shaded page in the the map. If students are on a specific part of the course, it makes sense to me that if they open the map, their place is "saved" and it would open with the active page in view.

2. Enhanced iconography or no iconography. Thinking of it from a student perspective, what they really care about is "lesson", "page", and "active". The differentiation between a page and a page with subpages doesn't mean very much to them. If you want to play on iconography, perhaps you'd want to use icons to designate "lesson book", "content page", "active page" (ie drupal forms or discussion", and maybe even an "assignment" page type. 

3. Verbiage to frame up that the breadcrumb is more of a "jump to" convenience and isn't the main source of navigation. Or focused more on "current place". Something as simple as having "jump to" as the default item in the first level drop down or saying something like "Location" before the drop downs might work.

**Comment by btopro** [comment]
@rickhumphries So I think what might be nice is some kind of top navigation layer to the overall "map" if you will. This could show the highest levels of the outline as quick links. I also think as per the ID's comments I just pasted, if it focused you on where you currently are and had collapse / expand all kinds of buttons that might also play nicely with this approach.

@michael-collins has done some mock ups of the next generation Outline Designer so it's funny that you mention that (cause he did too and I didn't really think of that when mocking this up). Outline Designer NG would probably just slot into this map button and edit mode for the map would effectively be what the outline designer accomplishes now. This would unify the authoring experience w/ the student experience.

**Comment by rickhumphries** [comment]
@btopro yeh I think that would be a good idea to have a top navigation layer. I would still push for some way of being able to just focus on each one of the highest levels of the outline separately too. Whether that's just by filtering/hiding the other sections or something when a top level menu heading is clicked. That would be really useful for chunking information in extremely long courses and being able to support non-linear courses a little better too.

Really liking the look of ToCs though. Re: iconography - I'm a fan of having an icon to indicate the content type of the page but it looks much cleaner at the moment with no icons. I wonder whether it's worth only having icons for child pages? Or only having icons for pages that include some sort of activity (discussion, quiz etc.)

**Comment by btopro** [comment]
@rickhumphries I like that idea / have some others w/ the nav down into the "map" (course as a map of where your going and you can focus on things). I had stuff on paper about 3 years ago that described a course GPS display where you can get heads up info about where your going (X number of tests coming up, Y discussions, Z interactive activities, etc).

On the iconography right now it'll only pull in icons if one is defined by the page (like a discussion or quiz for example). None of those are defined here and you can see the result (this site updates itself automatically) -- https://drupal.psu.edu/library/

**Comment by btopro** [comment]
![2015-08-13_07-34-17](https://cloud.githubusercontent.com/assets/329735/9248911/17b16174-418e-11e5-89c2-0dcfd0236d7b.png)

**Comment by btopro** [comment]
mock of sticky nav w/ this style
![2015-08-13_07-50-41](https://cloud.githubusercontent.com/assets/329735/9249151/66fe85d4-4190-11e5-8c9f-6dc66edd6f03.png)

**Comment by btopro** [comment]
Sticky navigation will finally make sense w/ this structure now even just anecdotally playing w/ it

**Comment by heyMP** [comment]
I really like the sticky header.  Typically sticky headers are obtrusive and take up far too much real estate on mobile but since we have a different navigational pattern at mobile, then I think this really works.

**Comment by btopro** [comment]
@heyMP another thought on mobile is to potentially dump the slide out nav as well as breadcrumb on mobile and then just have a sticky map / pager (which could actually make more sense at the bottom on mobile). See https://www.youtube.com/watch?v=3ok5dKUu4Ic and https://www.youtube.com/watch?v=KsL1Bh4xyOU for past prototypes worth noting. @michael-collins hated the sticky bottom nav on mobile but it's incredibly usable from a page-turning perspective (think kindle, particularly on a phone).  Thumbnav / the projects in this prototype are deprecated but a mobile nav style that makes sense can live in foundation_access / mooc - fa

**Comment by btopro** [comment]
@michael-collins assigning this to you, we need a mock up that's an updated version of the Outline Designer 3.x interface you laid down that takes into account some of the considerations in this thread. Also something for @heyMP to work off of as far as sticky nav is concerned

**Comment by btopro** [comment]
Mobile nav thought. Drop slide out, drop breadcrumb, drop bottom arrows. ToC in top left corner, nav arrow to side of it only and both smaller. Also might not need back button as all phones have a hardware based back, forward only to consolidate buttons even further

**Comment by btopro** [comment]
@heyMP let's dump off canvas and then keep the book icon on mobile but not the breadcrumb trail
