### ISSUE TITLE
Menu Icons Jumping and Double Scroll bar

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1903]
Bug:
- 0.7.1

I've bundled three issues into one here just because you can see them all in the gif:
![menu-icons-jumping](https://cloud.githubusercontent.com/assets/4973810/23298781/e11dec10-fa76-11e6-900d-cb31d1aafed4.gif)

1. On some of my courses, the menu icons jump around oddly
2. There are two hover labels appearing. Think this happens on all sites
3. The double scroll bar in the right hand scroll nav (the second scroll bar disappears when scrolling down and that block sticks to the top of the page though

**Comment by btopro** [comment]
definitely can't simulate that anywhere. Thinking this is possibly related to that 'support foundation' flag that might be conflicting between the foundation css/js processing and the materialize

**Comment by rickhumphries** [comment]
yeh the icons skipping only happens on some courses. But it doesn't happen on others, and doesn't happen on any of the authorities from what I've seen either (CIS, Media etc.)

**Comment by rickhumphries** [comment]
I've found the offending bit of code for the icons. That was our custom CSS - sorry about that. The double tooltip definitely reeks of foundation code too. 

The double scroll bar on the right hand nav seems to be because there's two CSS bits which both have the  `overflow-y: scroll;` property:
`.scrollspy-toc.table-of-contents` and `@media screen and (min-width: 80rem)#scrollspy-nav` in tweaks.css

**Comment by btopro** [comment]
hmm.. you'll have to show me a little animation / shoot me a path of exactly where that's happening; Haven't experienced that but might be related to an insanely long heading title or something

**Comment by rickhumphries** [comment]
for the double scroll thing? You can see it in the animation above:

![image](https://cloud.githubusercontent.com/assets/4973810/23341971/91d6898a-fc49-11e6-9a53-d6aff233b290.png)

I can dm an example link to that too though if you like

**Comment by btopro** [comment]
@rickhumphries yes cause I've never seen that so thinking it's CSS related on your end unless I can look at a specific example to see otherwise

**Comment by btopro** [comment]
#1993 fixed in the code about to be pushed up.... because we moved it elsewhere :)
