### ISSUE TITLE
How to choose which xAPI statements to track

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1906]
0.7.1

Currently I'm limiting how many learning locker statements come through by not tracking page views. To do this for all courses, I changed the following option so page views weren't tracked.
![image](https://cloud.githubusercontent.com/assets/4973810/23331732/ca457dbc-fb63-11e6-9d5e-1659354e36dc.png)

Since updating to 0.7.1 it looks like page views are being tracked and overriding this option choice. Is it still possible to control this on a course by course basis?

**Comment by btopro** [comment]
this currently is not configurable now that you mention it as elms is now providing this functionality so that we can track things other then content types (it works on views / any page for example now) and appends a duration value. But, I agree, this should be configurable.
