### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by metelmann** [elmsln/elmsln#1908]
I installed ELMS:LN using the method described here: http://drdavefusco.com/installing-elmsln-on-aws-and-configuring-xapi-and-h5p/ . When I try to update (security updates - I installed vsftpd and enabled anonymous login for this test) I get the following error which I can't figure out why this is happening.

Error: Call to undefined function _cis_connector_url_get_properties() in elmsln_core_url_outbound_alter() (line 1015 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_core/elmsln_core.module).

Can you point me in the right direction (I didn't find a support forum, so please bear with me if this is the wrong place to ask).

**Comment by btopro** [comment]
You've come to the right place.

what security updates are you referring to? ELMS:LN is meant to be upgraded as a whole package much like traditional Drupal distributions how it's best to follow the known working configuration together instead of updating parts independently.

https://elmsln.readthedocs.io/en/latest/development/Should-I-update-Drupal-modules/

**Comment by metelmann** [comment]
I'm talking about the ones in /admin/reports/updates/update which you get directed to by a nice little warning message 

"There are security updates available for one or more of your modules or themes. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates."

on the Administration page.

**Comment by btopro** [comment]
Yeah, those. We don't recommend updating off schedule unless you are updating the code in the same location / are testing / contributing to releases. The core directory in deployments isn't intended to be modified off version control for consistency. If there are specific modules you want to work towards us getting newer versions in then they can be brought in through individual PRs.

I'm not sure how you went about upgrading the modules but if you upgraded cis_connector which has all the elmsln core modules then it definitely has a chance of breaking as d.o. is *always* behind what's in this repository with regard to distributions included in the system and modules that are in the elmsln_contrib folder.

**Comment by metelmann** [comment]
OK. Thank you for your time and answer. I'll just ignore this then, and try out the rest now :)
