### ISSUE TITLE
Update vagrant box to include php7.0-mbstring & php7.0-zip

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1911]
`sudo apt-get install php7.0-zip`
`sudo apt-get install php7.0-mbstring`

**Comment by nmillin** [comment]
Just a note that to install the h5p libraries from http://media.elmsln.local/admin/content/h5p, I had to run these two commands.

**Comment by btopro** [comment]
@nmillin ya i think that's where it comes from; this needs to be in our install routines for the VM I think but not prod builds as I think they already have these packages installed out of the box. Welcome to fix if you know how to work against VagrantFile sh files

**Comment by nmillin** [comment]
So it looks like ubuntu16-install.sh - https://github.com/elmsln/elmsln/blob/master/scripts/install/handsfree/ubuntu16/ubuntu16-install.sh includes installs for php-mbstring & php-zip. Do they just need to be updated to php7.0-zip & php7.0-mbstring?

**Comment by nmillin** [comment]
Tested vagrant up with https://github.com/elmsln/elmsln/pull/2068. This fixes the issue of not being able to install H5P libraries.

I'm not sure if this is the root cause or if other packages need to be updated.

**Comment by btopro** [comment]
@nmillin so Vagrant spins up? If so that basically means this is resolved

**Comment by nmillin** [comment]
@btopro yep. vagrant up worked and I didn't need to sudo apt-get anything to install h5p.

**Comment by btopro** [comment]
excellent cause then this fixes our normal build out as well
