### ISSUE TITLE
Studio, Project App, Discuss - Feature needs by Summer

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1925]
@heyMP has already been working on many of these features, but I think it is helpful to write down a list. For each project, which is broken into the different design phases, I'll be asking students to submit different types of deliverables. Ideally, we need to account for the following by  mid-April, start of May at the latest:

### Part-project Card features:

**Instructor creating/editing:**

- [x] Title of the card
- [x] Text area for instructions
- [x] Link to content (also where instructions might be)
- [ ] Video link - (video-based instructions, demo)
- [ ] Audio track upload* (audio-based instructions) -- *Would be nice, but not necessary
- [x] Publish setting: Public (to the class) / private (for the instructor only)
- [x] Other settings, can't think of them right now.
- [ ] Associate an assessment rubric
- [ ] Post-submit quality control questions: mandatory/optional
  - [ ] Question with 5- Star Rating response
  - [ ] Question with text area for feedback.
  - [ ] Question with check boxes or radio buttons.

**Student submitting/editing:** Can I enable/disable these fields so the students don't see them all when they submit?

- [x] Single Image
- [x] Image Grid (used to show visual research, sketches, journal pages)
- [x] External Link
- [x] Document Upload (PDF, doc, text)
- [x] Area text input
- [x] File Upload (ZIP archive, etc)
- [x] Line text input 
- [ ] Optional idea, After they hit submit or save, it could ask them optional/mandatory followup quality control questions or a start rating of the assignment. This would be set by the instructor.

### Studio Project Aggregated Card features:

- [x] Student name (instead of their userID)
- [x] Aggregated part-project submissions into a single card per student
- [ ] Feedback button per project-part. I imagine that when they click on this button, it can either pop up in a modal, or navigate away to the discuss system, where the particular project part is now in view with a comment field. I don't have a strong preference either way. Can it email the student when they have new feedback?
- [ ] PDF Downloading of entire aggregated project (this might be hard to set up, but it would be great in terms of long-term project storage and archiving outside of ELMS)

#1915

**Comment by michael-collins** [comment]
#1915

**Comment by michael-collins** [comment]
![whiteboard](https://cloud.githubusercontent.com/assets/1085304/24529247/8b84740a-1578-11e7-84ae-402ab186d410.jpg)

**Comment by michael-collins** [comment]
@btopro The filters in the red box aren't going to work for the way I have assignments structured. Is there a way to tag the assignments with the project they reference, and then filter according to that tag?

<img width="1192" alt="studio-issue-01" src="https://cloud.githubusercontent.com/assets/1085304/25472282/b0e0cfd8-2af8-11e7-919b-593afeecf940.png">

**Comment by btopro** [comment]
It's past summer, much of this done, others splits into other issues. Closing and resolving in future issues!
