### ISSUE TITLE
Build a LRN visual learning ontology

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1927]
This is a start at trying to build a possible polymer ontology of elements for education / training / teaching / learning in general. This is an initial stab to get this down some place:

Ontology
```
lrn - Learning, an element in the quest for learning something
	lrn-lesson - a container relating pages together
	    - title
	    - (multiple)lrn-competencies
	    - (multiple)lrn-page
	lrn-page - a page of instruction, simple wrapper element for quantification purposes
	lrn-vocab - vocabulary term
		- term
		- definition
		- optional: know-source(multiple)
	lrn-lecture - lecture, in place or reference to one in the real world
		- title
		- link (optional)
		- duration (optional)
		- date (optional)
	lrn-quote - called out quote
		- quote
		- attribution
	lrn-additional - additional / associated information
		- body
		- theme
	lrn-steps - steps to complete something
		- (multiple)lrn-step
		- type (number,bullet,required, optional)
	lrn-step - a single step to completion
		- text
		- icon (optional)
		- required / optional flag (optional)
	lrn-required - applies stylistic attributes to make this "required" to end-users
	lrn-optional - applies stylistic attrigutes to make this "optional" to end-users
	lrn-objectives - listing of instructional objectives
		- (multiple)lrn-objective
		- theme (light,dark,color, etc)
	lrn-objective - a single instructional objective
		- name
		- lrn-competency (optional associated competency if gaining a skill here)
		- icon (optional)
		- description
	lrn-competency - a new skill expressed to the learner
		- title
		- description
		- (multiple) lrn-xapi
	lrn-example - example work
		- body
	lrn-math - offset mathjax loaded item
		- equation (mathjax markdown)
	lrn-code - offset code block
		- language
		- theme (light/dark)
		- code
	lrn-assignments - a list of lrn-assignment
		- (multiple)lrn-assignment
	lrn-assignment - an assignment of instruction
		- name
		- description
		- due date (optional)
		- {rest of OER ontology}
	lrn-roster - a list of lrn-course-people
		- lrn-course-person
	lrn-person - someone associated to a course
		- roles
		- image
		- icon
		- first-name
		- last-name
	lrn-course - a sequence of course-objects
		- name
		- description
		- instructor(lrn-person)
		- machine_name
		- number
		- icon
		- image
		- colors
		- (multiple)lrn-course-object
	lrn-course-object - higher level grouping of materials in a course
		- type (module,lesson,unit,etc)
		- name
		- icon
		- image
		- colors
	lrn-course-section - organizational element for the offering of a course
		- name
		- dates
		- term / semester (optional)
		- lrn-course-person (instructor)
	lrn-beacon - a method of triggering an xAPI / caliper event
		- activator (javascript callback to determine when to fire / event listener)
		- lrn-xapi
	lrn-xapi - an xapi statement generator
		- callback location
		- <lrn-xapi callback="whatever.com/xapi">
			{
				"verb": "viewed",
				"actor": {
					"mbox": "btopro@outlook.com",
					"name": "btopro"
				},
				"authority"...
				"object"...
			}
		  </lrn-xapi>


lrn-know-source - Knowledge, references to knowledge sources
	know-source
```

**Comment by btopro** [comment]
Always have a singular and multiple case in a file
for example:
- lrn-assignment
- lrn-assignments

**Comment by michael-collins** [comment]
Could the oer schema vocab make sense to follow? We did a ton of taxonomy
work.

**Comment by btopro** [comment]
Always follow MVC in the individual components that are above atoms and all **instructional** components need to define their method of rendering when handed different **design** components. For example:
- lrn-assignment would have a title / etc but also have a display="card" (or whatever)
- All logic of how to render lrn-assignment for each designed display mode will be contained in here.
- `<lrn-assignment title="Assignment 1" display="card"></lrn-assignment>`, presents as a card
- `<lrn-assignment title="Assignment 2" display="list"></lrn-assignment>`, presents as a list
- `<lrn-assignment title="Assignment 3" due-date="November 12" display="table-row"></lrn-assignment>`, presents as a table row

The names of those displays would also be included w/ the spec, so we'd have molecules for design as well. Things like....

- lrn-design-card
- lrn-design-list
- lrn-design-grid
- lrn-design-table
- lrn-design-table-row


The hierarchy would be two trees then. Effectively, we've got lrn as a visual way of communicating about educational concepts at the top. From there we've got 2 branches, either down the **instructional branch**, or the **design branch**. Thus cementing lrn architecturally as a process of instructional design. All elements of the page, at a glance, would be expressive instructional design based "html".
For example:

- lrn
  - **instructional**
    - lecture: lrn-lecture - `<lrn-lecture time="5pm" date="Next Saturday" topic="Peace in our time" design="card"></lrn-lecture>`
  - **design**
    - card: lrn-design-card `<lrn-design-card title=""></lrn-design-card>`

**Comment by btopro** [comment]
@michael-collins absolutely borrowing from that

**Comment by btopro** [comment]
example hierarchy w/ descriptions in lucid charts:

https://www.lucidchart.com/invitations/accept/9971b55d-5091-4b7c-b98a-a276c2d5035b

![2017-03-17_10-01-16](https://cloud.githubusercontent.com/assets/329735/24046387/bdd54fcc-0af8-11e7-8e18-1a854c6f6c05.png)

**Comment by rickhumphries** [comment]
Wouldn't a lrn-module be at a level above lrn-page? Probably not quite understanding this, but just from the viewpoint that a module could be made up of many pages?

**Comment by btopro** [comment]
lrn-module would be like an in-page element communicating what a module is. So like if we had a page and needed an element to talk about a module in the course, it would be that. You are correct about hierarchically. All these elements are within the context of a page of some kind, whether those elements are then generated by Drupal saying "let''s list all the modules" which then are made up of pages, or drilled down in a module communicating in a standard way the vision of what that module is.

Trying to mix pedagogical terms with http://patternlab.io/ with webcomponents.org where the context of everything is creating an ontology and initial list of learning / education / training based web components.

**Comment by profmikegreene** [comment]
Should things like lrn-required/lrn-optional/lrn-beacon/lrn-xapi be in the instructional tree? They seem more like attributes of instructional elements. I don't see them in the lucidchart which makes me think you've already got another place in mind to stick things like that. Attributes maybe? Or a third tree for capabilities or something that would apply to all elements in the instructional tree?

Other possible elements
* group (roster is one type of)
* grade/score/experience point
* rubric
* media
* file
* communication (many forms)
* peer review (or is peer reviewable an attribute?)
* annotation (or is annotable an attribute?)
* credential (badge is one type of)
* curriculum/learning pathway

Other possible attribute/capabilities 
* restricted (ex. library resources)
* synchronous/async (classroom response assessment vs in class exam vs online exam)

**Comment by btopro** [comment]
Love the other possible elements list.

Important thing to take into account w/ webcomponents: they could be attributes and full on elements. Since they can nest infinitely, you can get a mix of object oriented programming (of sorts), design, and instructional significance.

As an example:  iron-ajax is kind of a meta-element that can be added onto another element to basically wire that element up to an ajax callback (https://www.webcomponents.org/element/PolymerElements/iron-ajax).

But I agree these sound like they should be name spaced differently somehow as there's like Design elements (Card, list, chip, etc), Instructional (quiz, assignment, reading list, etc), and then almost like Functionality or system based (xapi, beacon, ajax, etc).

I also like the idea of the restricted / synchronous aspects. @michael-collins are there quantifications like this in OERSchema properties? (that's an established ontology we're at minimum trying to account for)

**Comment by profmikegreene** [comment]
It seems that to fully realize the next gen learn tech ecosystem mindset, each one of these lrn elements and probably more things, need an open standard way to be understood by other technologies. Is that what this ontology is/becomes? Or should I be starting openAPI docs for all these? Something else? Not needed?

If we knew how to technically represent a forum for example, any LMS or ecosystem could know _that_ is a forum, it does these things, it integrates at these endpoints, relies on these entities, etc. Forums could then ensure they meet those requirements and provide differentiation and value by doing things on top of that. 

Am I off - is that needed? Seems like a lot of work to get right, but I can't wrap my brain around how the ecosystem mindset becomes scalable and transportable from institution to institution without it.

**Comment by btopro** [comment]
I think we need a screen share.. like Monday to hash this out a bit. The lrn webcomponents both help express the concepts visually but would start to allow for what you said about like an API that other systems could start to grep. It's design driving API which is a concept from headless systems so it's less a "here's the packing format" and more a "I want to talk about a concept. So I'm using this tag"  which may have come from a system generating the tag, someone typing it manually in a wysiwyg editor, or using a select list of options visually. So I might visually add an lrn-assignment tag to a page and the system it's in might say "we'll visually this thing knows how to represent I self. But let's see what systems we could hook this up to"

Also then you could have static systems / future systems expressing cocos visually without needing to build the design elements to do so. Helps a lot w. The ux across solutions issue as well as building all future things / even making just simple html pages. Let's talk Monday about some of the guts of a webcomponent to see how they plugin :)

**Comment by michael-collins** [comment]
@btopro I imagine that we could add a synchronous/ascynchronous property to an **Instructional Pattern** or **Learning Component** to account for it: http://oerschema.org/InstructionalPattern/ 

@curiosity26 What do you think?

In terms of "restricted," I think that just means copyrighted or licensed in some way. Schema.org has [CreativeWork](http://schema.org/CreativeWork) which has properties for licenses. A library resource will almost always be a creative work (book is a child of creative work). Since we are compatible with schema.org, we can use it seamlessly.

**Comment by btopro** [comment]
so this issue obviously isn't "finished" per-say but at least it's time here has as we now have 28 components (at this time), will be working on more in the coming months, and are starting to get pretty decent at Polymer to build webcomponents. https://github.com/LRNWebComponents now will have all things related to the details of ontology / building / tooling / docs for these things.

If there's a request for an element or an idea about one it's still a good idea to bring it up here since we'll have to work towards what things are elmsln-elements, lrn-elements, design elements, etc.
