### ISSUE TITLE
Sort group membership options in account details on authorities

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1931]
For example, in Media, I have to manually change/add group memberships sometimes. This is made harder as the options aren't sorted alphabetically.

I've changed this in the config on mine but thought it would be good to make this a standard change in the OG entity reference options

![image](https://cloud.githubusercontent.com/assets/4973810/23949936/2a812c14-0981-11e7-90c0-03a839cc0f6c.png)

**Comment by btopro** [comment]
makes a lot of sense to be included the way you are describing

**Comment by btopro** [comment]
fixed for users and content associations if content is associated to a group
