### ISSUE TITLE
Outline Changes Not Saving 

### ISSUE THREAD

**Issue by kmiffitt** [elmsln/elmsln#1933]
![screen shot 2017-03-20 at 1 53 09 pm](https://cloud.githubusercontent.com/assets/17576440/24113969/ed11ba4a-0d74-11e7-86b6-ea2257619fca.png)
Bug:
I've made several changes to outline (you can see in screenshot, I've typed it in enough times it's auto-populating), but when I hit save the changes don't stick.

**Comment by btopro** [comment]
hmm If you hit View off to the right of there I bet the title of the page will reflect what you've been saving. There's a project we have that allows the titles to be different between menus and pages. I wonder if this bulk update mode is causing them to get out of sync.
