### ISSUE TITLE
ELMS:LN Preference Chatbot

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#1941]
Hi guys! So I'm currently obsessing over the socket.io chat implementation and was thinking of another use case we could use this chat application for. Chatbots. We already have voice command for ELMS:LN, however, many people may also like to mess with their settings through a chatbot (kind of like how slack does its magic). I was thinking that we could add something like this down the road once I get the socket module in via a PR. I think this would be really cool - but let me know what you guyses' thoughts are!

**Comment by btopro** [comment]
yup

**Comment by mmilutinovic1313** [comment]
http://zenorocha.github.io/voice-elements/

**Comment by mmilutinovic1313** [comment]
This will now combine with the new socket-chat WebComponent mentioned in https://github.com/LRNWebComponents/socket-project.

**Comment by btopro** [comment]
merge with #381
