### ISSUE TITLE
Drupal Error Message Notifications not showing in CIS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1949]
Bug:
- 0.7.1

I've noticed that Drupal error notification messages don't seem to show in the CIS. For example, if a user logs in and types their username/password incorrectly then there is no message.

It came up again today as I was trying to save a user profile - the form wasn't saving because the email address was replicated elsewhere, however no error notification was showing so it took a while to realise what was going on.

**Comment by btopro** [comment]
hmm.... I haven't seen this. is it possibly related to the foundation access compatibility mode stuff? Maybe try and generate an error and then inspect the console in chrome and see if there's any errors

**Comment by rickhumphries** [comment]
Just done some digging and this was my own stupid fault by messing with the alert box CSS. Apologies!
