### ISSUE TITLE
Build a system for conversing around math equations

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#195]
Word on the street has it that administrative bodies at some higher ed institutions may go so far as to decree that a tool such as Piazza will be banned from use, unless certain faculty are so confident and rich, they want to bet their lifeblood on it.I know quite a few people who would use it.

**Comment by michael-collins** [comment]
Can you describe its features?

**Comment by juststormy** [comment]
https://piazza.com/product/overview

**Comment by juststormy** [comment]
Reasons to deny approval from Risk Management: data stored in another country; non-specific use of data; comprising student information and forcing them to use something they don't have to

**Comment by btopro** [comment]
@juststormy what aspects of a platform like Piazza are faculty looking for? From what I've seen in the past it was almost like a time-line based Q/A that handles math equations well. If we can get the math equations down well and allow for discussions that are clean / have similar usability I wonder if that'd be enough.

This might be something for @heyMP and you to talk w/ some faculty that currently use like tools and see it used in practice to gather what parts of it they are really keen on.

**Comment by juststormy** [comment]
I'm not sure math equations is the specific purpose...I'm sharing this article from 2012 by Phil Hill, who we happen to know very well http://mfeldstein.com/piazza-an-example-of-free-learning-tool-targeted-at-faculty-student-adoption/

**Comment by rickhumphries** [comment]
Could also try hooking Piazza into the network with LTI as well. Might become a useful example to showcase that kind of integration too https://s3.amazonaws.com/piazza-materials/LTI-Setup/GetAProgrammerStartedWithLTI.pdf

**Comment by btopro** [comment]
@rickhumphries there are legal ramifications to this for EDU crowd that training I'd say "Absolutely just go do that" :)

**Comment by rickhumphries** [comment]
@btopro ah OK :)

**Comment by btopro** [comment]
Closing this out; we need to focus on what we can pull into scope and accomplish the next several months. Once we clear the issue queue and have solved world hunger we can build this
