### ISSUE TITLE
advagg_mod module duplicating dropdown causing JS to break

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1953]
We've got our own achievements section in the CIS where the label for a dropdown is being duplicated:
![image](https://cloud.githubusercontent.com/assets/4973810/25381025/2d7bd434-29aa-11e7-916d-09f8117e096b.png)

The dropdown is generated by the following code
```
<div class="achievement-course-select-box">
    <label for="courseDropdown">Filter by course</label>
    <select id="courseDropdown" onchange="filterContent();">
        <option value="all">All content</option>
        <?php foreach ($account_courses as $course) : ?>
            <option value="course-<?php print $course_sections[$course['target_id']]['item_id'] ?>"><?php print $course_sections[$course['target_id']]['course_title']; ?></option>
        <?php endforeach; ?>
    </select>
</div>
<script>
    function filterContent()
    {
        var course = jQuery("#courseDropdown").val();
        console.log(course);

        if (course == 'all') {
            jQuery('.achievement').show();
        } else {
            jQuery('.achievement').hide();
            jQuery('.' + course).show();
        }
    }
</script>
```

It seems that the advagg_mod module is duplicating the dropdown on this page and also causing the JS to break as a result. Although I'm not sure why. Wondered if anyone could help

Thanks

**Comment by btopro** [comment]
is it advagg_mod or are you suspecting that it's that? I recall a few other places this has happened before

**Comment by rickhumphries** [comment]
I reported it as a fault to our developers and they replied back that it was due to the advagg_mod so I'm taking their word for it

**Comment by btopro** [comment]
that's a Drupal JS issue relative to that isn't the way to write JS in drupal land (generally speaking).

rewrite it to this and see if it's still an issue (if it is, you can go to admin/config/development/performance/advagg/mod and disable the rewriting of inline JS since I believe it's checked but can cause issues with things like this)
```
<script>
(function ($) {
    function filterContent()
    {
        var course = $("#courseDropdown").val();
        console.log(course);

        if (course == 'all') {
            $('.achievement').show();
        } else {
            $('.achievement').hide();
            $('.' + course).show();
        }
    }
})(jQuery);
</script>
```

**Comment by rickhumphries** [comment]
Thank you for this. I'll try to implement and then report back

**Comment by rickhumphries** [comment]
Hey hey, so we've managed to resolve this. Initially tried changing the JS and disabling the rewriting of the JS but that didn't work unfortunately. However, we then reverted the JS back to how it was originally and turned off inline JS aggregation and that did the trick

Cheers!
