### ISSUE TITLE
Issue with the menu on ipad

### ISSUE THREAD

**Issue by Anthall** [elmsln/elmsln#1954]
Hi there, 
I've come across an issue regarding the top menu bar (#etb-course-nav ) when testing on an Ipad. (see attached screenshots taken on an ipad4)

When on the dashboard, the menu displays correctly (image2) but when you go to a course it disappears (image1). 

Initially we thought it was to do with our own CSS styling, but we tested on a demo site without any of our custom CSS and we had the same issue (image3). The problem seems to be with ipad only as it displays normally on iphone, we've also tested this on Safari and Chrome on ipad and having the same issue on both.  

On further investigation it looks as though the menu is still there but being hidden by content being pushed above it. On the image3 you can still see the blue menu bar slightly.

Any idea why this is happening? 
Thanks
Ant 
![image1](https://cloud.githubusercontent.com/assets/24223210/25480926/eb5ae834-2b42-11e7-9be9-ea5b5123a239.PNG)

![image2](https://cloud.githubusercontent.com/assets/24223210/25480929/eec374fa-2b42-11e7-8227-2f44f335136e.PNG)
![image3](https://cloud.githubusercontent.com/assets/24223210/25480931/f160228a-2b42-11e7-8a18-de7aa5e8a134.PNG)

**Comment by btopro** [comment]
Hey, thanks for report @Anthall . I can't replicate this in Safari (and I don't have an iPad) but I checked in Safari after doing some modifications to this bar and it doesn't appear to happen anymore. The new version of the UI top-bar wrapper is also more compatible across browsers I believe since I implement flexbox better then before.

Closing for now, if after upgrade to the next release this still happens let us know

**Comment by rickhumphries** [comment]
Just as an aside to this - it may have been fixed but the below view is the CIS in Chrome for Android:

![image](https://cloud.githubusercontent.com/assets/4973810/26244211/be21e25a-3c86-11e7-8bb3-c96b2c595450.png)

Swiping left, you can see the additional icons out to the right which causes the whole screen to shift

**Comment by btopro** [comment]
fixed in 0.8.x branch; thx for the report.
