### ISSUE TITLE
Issue with Outline Contents on iPhone

### ISSUE THREAD

**Issue by Anthall** [elmsln/elmsln#1955]
Hi, we have found an issue regarding the contents (#block-mooc-helper-mooc-helper-toc-nav-modal) on iphone. 

When you click on the Outline button, the modal pops up, but you are not able to scroll vertically down the contents. It only allows you to scroll horizontally. (image1)

We've checked this against a demo site without any of our own custom css and we are having the same issue here. (image2)

It appears to only be an iPhone issue as an android phone worked correctly, iPads also work correctly.  Any ideas?

Thanks
Ant

![img1](https://cloud.githubusercontent.com/assets/24223210/25481599/cfcf751e-2b45-11e7-950b-76ee9499ce37.jpg)

![img2](https://cloud.githubusercontent.com/assets/24223210/25481600/d188a114-2b45-11e7-842c-56d3ea257766.jpg)

**Comment by btopro** [comment]
Hmm.. I think this might be related to the overflow text for really long titles. This looked poor anyway (long title running into itself) which we solved on the main nav via the ... ellipsis so I just implemented a similar solution for this nav.

Again, if this isn't solve in 0.8.0 then reopen just like the last one and we'll look again
