### ISSUE TITLE
Add 'Machine name' to the course creation form

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1963]
Bug:
- 0.7.2

- What happens
I'm creating four courses that form part of a 'programme' and as such they're similarly named:
Pre-reg 17-18 Intro
Pre-reg 17-18
Pre-reg 17-18 MCA
Pre-reg 17-18 UHI

I created the pre-reg 17-18 course normally (url is then /prereg1718) and then tried to create pre-reg 17-18 intro. Although the course itself is created in the CIS (url is /prereg17180) the courses service that links to it is the one from the previous course and shows without a status:
![image](https://cloud.githubusercontent.com/assets/4973810/25739731/10ca973e-317b-11e7-89d5-c4c71a7e7972.png)

- What you expected to happen
The course service that should be created should be called prereg1718intro and this should be associated with the course. It seems like it's something to do with being able to use a limited number of characters in the course name?

**Comment by rickhumphries** [comment]
Another oddity is that the course that was created in Media from this has the 'Course Compliance Master Section' linked to it, rather than just 'Master Section'

![image](https://cloud.githubusercontent.com/assets/4973810/25743936/042314ca-318f-11e7-8f5a-008ed07d6463.png)

**Comment by btopro** [comment]
there is a hard limit on the length of a course name / machine name combination because of limits in the database name that matches

**Comment by rickhumphries** [comment]
I created the course using the quick setup form (/cis-quick-setup).

It might be that it needs to drop an error message if you're creating a course service where the machine names would clash

**Comment by btopro** [comment]
ya we need better error checking on that page for sure

**Comment by btopro** [comment]
rolling into #2049 when it gets added as that would supplant the error messages of this but also would make it possible to account for when we are in the process of revising that item
