### ISSUE TITLE
Automatic lockout after 5 attempts - admin controls

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1965]
Just a feature suggestion really. We've had a few students receiving the 'sorry you've been locked out because of 5 failed login attempts' because they can't enter their passwords correctly.

Thought it might be good to have some admin controls for unblocking users etc. with these modules:
https://www.drupal.org/project/flood_unblock
https://www.drupal.org/project/flood_control

**Comment by btopro** [comment]
Yeah that's a good idea on both of them

**Comment by btopro** [comment]
What site (all of them or a specific one) would you envision this being enabled on?
@cgldevel can at least get this added into the setup sometime to practice a pull request cc: @heyMP

**Comment by cgldevel** [comment]
Sure...Quick question:   Are you thinking of just adding the modules to the repo or enabling them through Features?

**Comment by btopro** [comment]
@cgldevel 1st step - add them to the repo. We're not sure what feature they would be apart of yet till  Rick answers about where it would go. Making a feature called elmsln_floodcontrol isn't a bad idea though which could at least set some sane defaults for the flood_control module and enable both modules.

Let's not actually enable this by default till rick's group gets a chance to play with it down the road to know where it's best to include but this should be enough info to at least start asking more questions about where we put modules and stuff.

**Comment by rickhumphries** [comment]
@btopro @cgldevel hey - so for us it would make sense in the CIS because that's where our students log in from and that's our bakery master site and where all the admin type stuff takes place

I don't know if it makes a difference that the default bakery master for ELMS:LN is people though?

**Comment by btopro** [comment]
yeah that's the part i'm unsure of (if this is related to the master site or the drupal site they log in from)

**Comment by btopro** [comment]
@rickhumphries CPR and CIS both have this enabled now by default / update hook
