### ISSUE TITLE
broken images in section content

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1978]
Not sure if I'm looking at an outdated section or not, but these images seem to be broken: https://courses.aanda.psu.edu/dmd100/topics/twine-tutorial-getting-started.md

**Comment by btopro** [comment]
dono i'll have to look at your convention for this one

**Comment by michael-collins** [comment]
All course images seem to be broken for me.

**Comment by btopro** [comment]
deploy specific as I think we figured out the two issues at hand (cache rebuild)
