### ISSUE TITLE
Course naming confusion

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1979]
Not sure of the difference between course name and course title. Might make sense to call it course abbreviation and course title in the settings. And then in the LMSLESS bar, the course title would print on the top (FUNDAMENTALS OF DIGITAL MULTIMEDIA DESIGN), and the course abbreviation (DMD100) would print below as on the mockups: https://dmd-program.github.io/pipeline/forum

Currently, there is no way to get the course title into the top area:

<img width="612" alt="screen shot 2017-05-09 at 5 29 56 pm" src="https://cloud.githubusercontent.com/assets/1085304/25873625/3d4ff87a-34dd-11e7-80fb-df843ff85270.png">

<img width="887" alt="screen shot 2017-05-09 at 5 31 00 pm" src="https://cloud.githubusercontent.com/assets/1085304/25873640/4b324b46-34dd-11e7-84fd-7ce7d0ec0ac0.png">

**Comment by btopro** [comment]
correct

**Comment by btopro** [comment]
fixed forgot to close
