### ISSUE TITLE
default course section

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1980]
How do I see the latest course section? Perhaps I don't understand how sections work, but I thought the idea was that you could edit them independent of the master? When I look at the available course sections, this is what I see for DMD100. I've attached an image, I'm sure there is a reason that art201 is showing up, but I don't know why that would be.

<img width="730" alt="screen shot 2017-05-09 at 5 35 43 pm" src="https://cloud.githubusercontent.com/assets/1085304/25873826/f533b3f0-34dd-11e7-96c8-ae450886851b.png">

**Comment by michael-collins** [comment]
Okay, I located another section settings box. Now I'm starting to think the wrong outline is associated with DMD100...

<img width="1046" alt="screen shot 2017-05-09 at 5 41 58 pm" src="https://cloud.githubusercontent.com/assets/1085304/25874057/d5661be8-34de-11e7-954d-affc84a7417c.png">

<img width="586" alt="screen shot 2017-05-09 at 5 42 23 pm" src="https://cloud.githubusercontent.com/assets/1085304/25874066/e45e8d92-34de-11e7-9e82-8fc0fca99636.png">

**Comment by btopro** [comment]
looks like someone put that in for some reason, I'll have to look into it
