### ISSUE TITLE
Broken image from gitbook

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1983]
This page seems to still have a broken image, despite the alt text being available:

Will update the following list as they are found/fixed:

- [ ] https://courses.aanda.psu.edu/dmd100/topics/interaction_design.md `/assets/avg-man-dreyfuss.png`
- [ ] https://courses.aanda.psu.edu/dmd100/node/1387/edit `/assets/dd-process-develop-1200px@2x.png`
  - [ ] https://courses.aanda.psu.edu/dmd100/node/1388/edit
  - [ ] https://courses.aanda.psu.edu/dmd100/projects/narrative/discover_focus_words.md
- [ ] https://courses.aanda.psu.edu/dmd100/node/1396/edit `../assets/interactive-narrative-branching-paths.png`
  - Lots of other images on this page with the same path issue

**Comment by btopro** [comment]
I see an image without alt. any place else this happens saving the page forces a rebuild of the locations. markdown editor caches things heavily on the way in the door (so to speak) so some of these may have just been products of the import minus processing the file location look up that I do on save

**Comment by michael-collins** [comment]
So I didn't understand the explanation. Are you fixing them, or is there a way that I can?

**Comment by btopro** [comment]
ya we clear caches and they should up after import, should be there now
