### ISSUE TITLE
Youtube uploading pass through

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#199]
@heyMP, you are all things media server right now.
- [x] Module (i don't think one exists) that can bridge the API with YouTube
- [ ] Create a Feature that implements this content type
- [ ] Allow user to upload a video to the content type which actually passes it through and saves it to youtube
- [ ] Display video via the media_youtube / accessible media player
- [ ] have it optional and attached directly to the external video type
- [ ] add support for external videos to have local fallback (ala accessible fallback)
- [ ] unlist everything by default
- [ ] route it through local player so that we can fall back on it effectively
- [ ] document how to use this since we can't do the OAuth handshake automatically for people

**Comment by mmilutinovic1313** [comment]
Perhaps this could be a solution to the first section? 

https://www.drupal.org/project/youtube_uploader

**Comment by mmilutinovic1313** [comment]
Update: Looks like this could be a good solution to this! I need to test this on a live instance so I can hook the service up with the API provided in the module. Once I get that hooked up I can post some screenshots and write up if this looks promising or not. Then we can work from there!

**Comment by btopro** [comment]
#644

**Comment by btopro** [comment]
#1248

**Comment by btopro** [comment]
This most likely should be replaced with https://www.webcomponents.org/element/GoogleWebComponents/google-youtube-upload and we can use the events to either allow direct webcam recording in place OR upload a video (which passes through to youtube). After the passthrough (in either case) we can use the event to post the link to elmsmedia ensuring that we know about it in our systems and can present it consistently across platforms

**Comment by btopro** [comment]
#848

**Comment by btopro** [comment]
webcomponents and the API router trump this
