### ISSUE TITLE
Sticky nav jumping

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#1996]
Bug:
When scrolling down on the page there is a split second when the sticky nav is in between states that appears to be janky.

https://youtu.be/ymhA_C1yOf8

**Comment by btopro** [comment]
User error. Scroll faster. Every body is scrolling fast these days.

**Comment by heyMP** [comment]
I don't twitter very good. I'm not up on this stuff.

**Comment by btopro** [comment]
fixed, switched to materializeCSS pinned instead of jquery Sticky. We need a component for making things sticky and there doesn't seem to be one yet (stupid)
