### ISSUE TITLE
edit or hide lmsless navigation items

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#1999]
I am unable to edit the syllabus, rsources, and help pages on elmsln. Could I either (1) hide those, (2) change the link to a page of content in the book, or (3) Edit the pages the currently link to?

- https://courses.aanda.psu.edu/dmd100/course-help
- https://courses.aanda.psu.edu/dmd100/resources
- https://courses.aanda.psu.edu/dmd100/syllabus

**Comment by heyMP** [comment]
You can change those links in the course-settings page.  https://courses.ed.science.psu.edu/phys010/cis/course-settings

![screen shot 2017-05-15 at 8 38 44 am](https://cloud.githubusercontent.com/assets/3428964/26058084/3fad8ee0-394a-11e7-876c-780326e71803.png)
![screen shot 2017-05-15 at 8 39 01 am](https://cloud.githubusercontent.com/assets/3428964/26058089/42fab82a-394a-11e7-8688-65f6f3564844.png)
