### ISSUE TITLE
navigation should not initiate until after the bottom of the left navigation block is out of view

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2000]
https://github.com/elmsln/elmsln/issues/1998#issuecomment-301364969

**Comment by btopro** [comment]
hmm.. I mean if there are like 20 items in the scrollspy you could hit a scenario where it doesnt trigger v. quickly but i see the concern, just not sure the best methodology

**Comment by heyMP** [comment]
We might be able to move the "pinned" target from the scrollspy element to its parent, the navigation block.  Something like this:
```
#block-mooc-nav-block-mooc-nav-nav.pinned ul.table-of-contents {
  position: fixed;
  ...
}
```

The other option would be to write lots of javascript to figure out what the height of the navigation is and do some algebra. :)

**Comment by btopro** [comment]
@heyMP is this taken care of post clean up of clean up of clean up? ;)

**Comment by nmillin** [comment]
So is the idea to hide the scrollspy table of contents until the user has scrolled past the navigation? The issues raised in https://github.com/elmsln/elmsln/issues/1998 don't appear to be issues anymore (reverted code that caused issues).

![2000-scrollspy-vs-menu](https://user-images.githubusercontent.com/1018136/27645800-a2a507ac-5bec-11e7-8dae-0b50e1488869.jpg)
Screenshot for future Nate.
