### ISSUE TITLE
Horizontal Scrollbar

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2001]
This is a small interface issue. The horizontal scroll indicator is only needed on pages with a lot of text. On the studio, for instance, it doesn't make much sense to have this indicator. Also, the indicator should be hidden if the content page in question is twice the height of the page or less.

**Comment by btopro** [comment]
the 2nd part of this is incredibly petty lol

**Comment by michael-collins** [comment]
Not petty, just specific. Trying to figure out a good rule of thumb for when you'd want help with page length. I feel like double the height of a typical monitor (2400ish?) doesn't really need a scroll bar, but that's more of a guess.

**Comment by btopro** [comment]
a number of pixels we can (probably) do. As you know there are 2 difficult things in programming
1. naming things
2. positioning things vertically in CSS

**Comment by nmillin** [comment]
@michael-collins Can you share a screenshot of this in action & the page URL? I'm trying to recreate what you are describing. Thanks.

**Comment by btopro** [comment]
make any page in your content setup courses.elmsln.local/whatever and then paste a bunch of content into the window. Then have one without much content. He's saying that when content itself isn't tall that the scroll progression thing that's blue at the top of the UI shouldn't show.

**Comment by nmillin** [comment]
Gotcha. Thanks. (screenshot for future Nate's reference)
![scroll-bar-screenshot](https://user-images.githubusercontent.com/1018136/27609343-1ebe7230-5b50-11e7-9c91-11b0c201351a.jpg)

**Comment by nmillin** [comment]
I looked into display: none on .page-scroll, but that would cause a blank space at the top of the page (bad idea - see screenshot).
![scrollbar-display-none-bad-idea](https://user-images.githubusercontent.com/1018136/27642371-3cc80630-5be4-11e7-8165-9ca5b8c4d940.jpg)


PR will not show the blue line and no spacings are effected (see screenshot).
![scroll-bar-screenshot-short-page](https://user-images.githubusercontent.com/1018136/27642540-b9d03b48-5be4-11e7-8117-0c82dd0cc361.jpg)

**Comment by btopro** [comment]
showed this is now working
