### ISSUE TITLE
Authcache inserting 'plus' sign in User Icon Menu in Courses

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2003]
v0.7.2

When a student user logs in, it seems their name in the User icon is showing with a '+' sign in place of any spaces:
![image](https://cloud.githubusercontent.com/assets/4973810/26101524/563623e0-3a29-11e7-90f6-fca6b692144b.png)

There are occasions when this doesn't happen (sometimes on first login or something) and the code for it looks like this:
`<span class="hide-on-med-and-down truncate">Name Here</span>`

However when the '+' sign is introduced, the code looks like this:
`<span class="hide-on-med-and-down truncate"><span class="authcache-user authcache-user-processed">Name+Here</span></span>`

Unsure whether this is to do with my APDQC settings? This seems to only happen in a course though - not the CIS etc.

**Comment by btopro** [comment]
lol that's a new one.  I looked at authcache settings and nothing associated with URL encoding of this. will have to look in issue queues to see if anything comes up like this as the authcache stuff we basically just provide drop in support for (and may drop I mean I don't really think it's saving us much at this point, especially as we move toward component architecture which is more efficient anyway)

**Comment by btopro** [comment]
@cgldevel can you check the authcache issue queues to see if there's anything that might be causing / suggesting this can happen (with usernames or otherwise). Not sure why this would be a thing as we don't have spaces in our usernames, HOWEVER, as we move more towards a flipped LMS world we'll allow people to use their own way of presenting themselves in interfaces / listings which could have spaces in those names.

**Comment by cgldevel** [comment]
I've spent some time scanning through the authcache issue queue -- As of today, I'm not seeing anything that resembles the issue described.

**Comment by btopro** [comment]
dropped support for it, it doesn't appear to have issues either way. As we move more towards webcomponents we might want to look into getting rid of authcache since it's for output caching and as we get more "one page app"-ish then it'll have increasingly less impact.
