### ISSUE TITLE
Bulk Import of WYSIWYG templates

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2004]
We have a bunch of custom templates set up that we need to export and then import one by one into each course we set up. I was just wondering if it's possible to add them all in at the same time? Either via Drupal or dumping them on the server?

Also wondering if this problem is being solved through web components in the future as wysiwyg templates won't be required as much?

**Comment by btopro** [comment]
Yeah, you can make a Feature (probably like buttercup_templates or something) and then select the wysiwyg templates to export, then just enable this feature on all your sites after it's been uploaded to `/var/www/elmsln/config/shared/drupal-7.x/modules/`

As for the web component piece, there will be a transitionary time where both are utilized (maybe you'll even place webcomponents into your templates to simplify them). Template will become less important once we get to HAX, however we might even hit the templates from HAX to allow for easy inserting of batches of elements (like a layed out page)
