### ISSUE TITLE
Drop slide out nav for MOOC

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#201]
I like the slide out nav and what it provides, especially for the time being, but on the courses / mooc domain it's been shown (by IDs, students, developers, etc) to be obnoxious and confusing. I like it as a stepping stone toward a better solution in the other platforms but I believe MOOC has found its way to get around that steeping stone w/ the Map based navigation. As such, I think we need to abandon the fly out / nested nav as the default mobile methodology.

Thoughts requested from @michael-collins but I'm throwing this to @heyMP to tackle via modifications to the Context's in MOOC (I believe mooc_cis_ux delivers this)

**Comment by michael-collins** [comment]
@btopro Yup, I'm on it. We can use off-canvas on the parts of the system that make sense.

**Comment by rickhumphries** [comment]
Is there an approx timeline for developing a solution to this? Currently thinking of upgrading to the latest UX in order to solve #228 but looking at the demo site I can't see an alternative way of accessing course outline for mobile

**Comment by btopro** [comment]
hmm, I see what your saying. Yeah, it would be nice to dump the left slide out and then just display the map on mobile or whatever but I see what your saying rick, it's hiding on mobile. some simple css to not hide the map but hide the breadcrumbs on mobile @heyMP

**Comment by btopro** [comment]
#391 resolved this along with discussion sin #379
