### ISSUE TITLE
Add hyperlink functionality to simple text format

### ISSUE THREAD

**Issue by cgldevel** [elmsln/elmsln#2012]
ELMSLN 0.8.x

Feature request:

- Add hyperlink functionality to simple text format.  This would be useful when a user adds a link in the image 'citation' field, for example.
  
![screen shot 2017-05-17 at 1 56 24 pm](https://cloud.githubusercontent.com/assets/11019355/26168906/d067018a-3b09-11e7-8206-283bace8ebb7.png)

**Comment by btopro** [comment]
what's the simple text format? is this on gitbook related setups? Not disagreeing just looking to clarify

**Comment by cgldevel** [comment]
I assume 'Simple text' format is a text format that was set up previously?  I don't think it's gitbook-related...but rather Drupal-related.

<img width="1403" alt="screen shot 2017-05-18 at 8 45 12 am" src="https://cloud.githubusercontent.com/assets/11019355/26202814/c0e465ca-3ba6-11e7-8546-707462967fb2.png">

**Comment by btopro** [comment]
ahhhh nice. Ok, yes that would be good to add. elmsln_simple_filter is the name of the feature and currently I think it's only available in the media system
