### ISSUE TITLE
Studio UX Mockups

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2014]
I'm just getting started on these. I'm thinking that a vertical nav is a good idea to separate it from the rest of the horizontal navigation we have going on. This is just a photoshop mockup until we can get the entire ux nailed down. I'll update as I make progress.

<img width="1267" alt="screen shot 2017-05-17 at 2 26 07 pm" src="https://cloud.githubusercontent.com/assets/1085304/26169876/3d2500e4-3b0d-11e7-95c3-793ffadbc812.png">

**Comment by michael-collins** [comment]
![image](https://cloud.githubusercontent.com/assets/1085304/26170611/11cd1cbc-3b10-11e7-9e75-67de4773e85d.png)

**Comment by michael-collins** [comment]
<img width="1260" alt="screen shot 2017-05-17 at 2 49 01 pm" src="https://cloud.githubusercontent.com/assets/1085304/26170635/1d24f134-3b10-11e7-87e6-3105136c17f0.png">

**Comment by btopro** [comment]
I wonder what a left panel would look like if shaded to match the thing you are working on or how color could help reinforce that. google+ does this to help discern between different aspects of google plus once in that "app" so to speak -- https://plus.google.com/collections/followed

**Comment by btopro** [comment]
what is a discussion feed? Like what people are saying about stuff centric instead of submission centric?

**Comment by michael-collins** [comment]
Instead of the comments tab, I renamed it discussions. I haven't had a chance to put nearly as much time in today as i wanted. Spent all day reworking a tutorial for one of their assignments, and building stuff out  on elms.

**Comment by btopro** [comment]
gotcha, ok, just clarifying

**Comment by btopro** [comment]
also did u make the above icons the the mock up? If so, can I have them at 30px svg?

**Comment by michael-collins** [comment]
Those are material, trying to standardize on them as much as possible.

<img width="1216" alt="screen shot 2017-05-17 at 11 57 07 pm" src="https://cloud.githubusercontent.com/assets/1085304/26186012/970edefa-3b5c-11e7-9958-8a4eff0a69e3.png">

**Comment by michael-collins** [comment]
Let's work color in at a later time. We should focus on greyscale for now, and introduce color after we have things working a bit better. I'm not anti color, it's just harder to design with, and takes a more wholistic overview to do it right.

<img width="1353" alt="screen shot 2017-05-18 at 1 08 15 am" src="https://cloud.githubusercontent.com/assets/1085304/26187409/bbaf6d4c-3b66-11e7-80ef-aa2544809963.png">

**Comment by michael-collins** [comment]
Bit cleaner. Added the toolbar area back into the layout.

<img width="1251" alt="screen shot 2017-05-18 at 1 26 34 am" src="https://cloud.githubusercontent.com/assets/1085304/26187731/147bb460-3b69-11e7-9083-58f5dab35b75.png">

**Comment by btopro** [comment]
![2017-05-18_09-53-13](https://cloud.githubusercontent.com/assets/329735/26205469/d0fbcfee-3baf-11e7-9c23-33ac7784c1c5.png)

app loading into studio so that's a big 1st step towards implementing any design work in this thread.

**Comment by michael-collins** [comment]
Nice!

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=bF6PEPq8QZk
