### ISSUE TITLE
Enable CIS Shortcodes in studio for DMD 100 

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2015]
Assuming what @heyMP said is true, shortcodes will work in studio if they are enabled. Can we enable shortcodes DMD100 Studio? I'd like to embed outline book content into the assignment descriptions so that it becomes easier to keep things in sync.

**Comment by btopro** [comment]
this was previously enabled, it won't do what you think I'll do unfortunately.

**Comment by btopro** [comment]
this is already enabled, would have to save and reload the page to see it tho because of how @heyMP is loading the text area
