### ISSUE TITLE
Studio start/end dates are conflicting

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2016]
I set 11:59pm. The Due Date readout area gives the correct time, but the settings below are incorrect. The area where you set the times are defaulting to 3:59am for some reason.

<img width="737" alt="screen shot 2017-05-17 at 3 37 56 pm" src="https://cloud.githubusercontent.com/assets/1085304/26172584/f2212640-3b16-11e7-9d9f-53756a2b5478.png">

**Comment by btopro** [comment]
Due dates would be all @heyMP world

**Comment by btopro** [comment]
outdated, working on this in the new app soon
