### ISSUE TITLE
Aligning menu icons with material

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2018]
This is low priority.

Current:
<img width="410" alt="screen shot 2017-05-18 at 1 42 17 am" src="https://cloud.githubusercontent.com/assets/1085304/26188103/4e18d796-3b6b-11e7-84d4-302c4b70be8a.png">

Suggested:
<img width="105" alt="screen shot 2017-05-18 at 1 50 04 am" src="https://cloud.githubusercontent.com/assets/1085304/26188288/695de9e6-3b6c-11e7-970c-e526fe4e3788.png">
<img width="127" alt="screen shot 2017-05-18 at 1 45 08 am" src="https://cloud.githubusercontent.com/assets/1085304/26188283/6401b716-3b6c-11e7-80a9-56b4ead6e79a.png">
<img width="125" alt="screen shot 2017-05-18 at 1 43 41 am" src="https://cloud.githubusercontent.com/assets/1085304/26188270/59cb4adc-3b6c-11e7-98f0-432fad14a9d7.png">
<img width="126" alt="screen shot 2017-05-18 at 1 45 03 am" src="https://cloud.githubusercontent.com/assets/1085304/26188280/61a8269e-3b6c-11e7-9bab-29469455807e.png">
<img width="123" alt="screen shot 2017-05-18 at 1 44 41 am" src="https://cloud.githubusercontent.com/assets/1085304/26188277/5f4f6704-3b6c-11e7-9263-b9bd55bb9dd5.png">

**Comment by michael-collins** [comment]
replace this icon...
<img width="127" alt="screen shot 2017-05-18 at 1 52 57 am" src="https://cloud.githubusercontent.com/assets/1085304/26188359/be0ef426-3b6c-11e7-8061-4f037c6880c7.png">

with this...

<img width="112" alt="screen shot 2017-05-18 at 1 44 02 am" src="https://cloud.githubusercontent.com/assets/1085304/26188366/cb60f87c-3b6c-11e7-8f7d-c90efeeeaca2.png">

**Comment by btopro** [comment]
There's an icon called assessment and one for assignment. Google has some "education" icons in there (thinking of the last one that u said as playlist)

Rest sound good

**Comment by btopro** [comment]
![2017-06-13_16-09-33](https://user-images.githubusercontent.com/329735/27102326-c7d136ae-5052-11e7-98ce-7f3d002dac38.png)

**Comment by btopro** [comment]
another good stepping stone / design micro project; we need more icons in the core lrn-icons set but also need to replace some of our own with the ones from https://poly-icon.appspot.com at 30px export size and added to https://github.com/LRNWebComponents/lrn-icons/blob/master/lrn-icons.html

**Comment by bterp-web** [comment]
The icons above seem to already be in lrn-icons, are there others that need to be replaced or added?

**Comment by btopro** [comment]
@bterp-web so they exist but Mike wants to align them w/ those from https://poly-icon.appspot.com/ instead of the custom ones he made before. Basically we want to gut out the ones we previously made w/ ones that better match the otherall google design spec.

**Comment by btopro** [comment]
@bterp-web awesome, which ones still need icons? there was like "svg" and "video" and other ones in the screenshot from above which aren't in this (unless they just weren't in the demo one).

**Comment by bterp-web** [comment]
All but "about, dino, quiz, dot grid, labs/lab/beaker, editorial/write" have not been replaced. "svg" and "video" didn't exist before, I can add those. What screenshot has them? I added play and replay so we can use them for the animations.

**Comment by btopro** [comment]
The image I posted with the add fab menu open w. The labels of items. For different types of things you can add. Would be cool to have an icon in each colored circle

**Comment by btopro** [comment]
just tried a bunch of them out, great work @bterp-web . Marking closed for now as we'll keep adding in icons as we need them.
