### ISSUE TITLE
make an lrndesign-audio player that mimics paper-audio-player

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2027]
https://www.webcomponents.org/element/gorork/paper-audio-player this then goes in media as a display mode

**Comment by btopro** [comment]
@nmillin could mentor you in making a web component to do this so it's a contribution to the LRNWebComponents org if interested

**Comment by nmillin** [comment]
@btopro yes please!

I'm assuming this would be added as part of the core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_audio feature?
Let me know how best to do this in ELMSLN. If you have an example branch/commit that I can look at, that might answer a lot of my simple questions.

**Comment by btopro** [comment]
`core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_audio` would implement it but actually this would start with 0 affiliation to elmsln. we try to make everything as if it had already existed b4 our project. Welcome to the world of https://github.com/LRNWebComponents

https://github.com/LRNWebComponents/ontology/blob/master/lrndesign-ontology.md#lrndesign-audio provides a suggestion of what the audio player might work and function.

https://github.com/LRNWebComponents/lrndeveloper has directions and scripts to jump start the tooling and general speed of development.

**Comment by btopro** [comment]
Once we have this player, then it will most likely replace https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/node/audio/node--inherit--audio.tpl.php so that thing are themed appropriately when rendered out but we're ahead of ourselves there :). That's affiliated w/ the workflows that will be discussed in #2062 #2061

**Comment by nmillin** [comment]
Thanks @btopro ! I'll be in touch when I hit a wall.

**Comment by nmillin** [comment]
@btopro So I have a working fork of https://www.webcomponents.org/element/gorork/paper-audio-player. Is the next step for you (?) to create a new repo at https://github.com/LRNWebComponents/lrndesign-audio? Then I could create a PR?

**Comment by btopro** [comment]
https://github.com/LRNWebComponents/lrndesign-audio-player/invitations

your in, you can contribute to this repo as u see fit

**Comment by nmillin** [comment]
so... I named it lrndesign-audio per https://github.com/LRNWebComponents/ontology/blob/master/lrndesign-ontology.md#lrndesign-audio. Should I update it to lrndesign-audio-player? I don't have strong feelings, but wanted to make sure I don't mess things up.

**Comment by btopro** [comment]
rename plz

**Comment by nmillin** [comment]
renamed and pushed up. A couple of things TODO
- update mp3 links to http://nadikun.com/audio/[something] to a different URL
- review license (MIT vs Apache)
- style player more or add more markup? (next steps?)

**Comment by btopro** [comment]
MIT and Apache are very similar, if it was MIT then that's fine

**Comment by btopro** [comment]
https://github.com/LRNWebComponents/lrndesign-audio-player need to review
