### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#203]
The black progress bar that shows up on mobile doesn't work completely in all scenarios. Sometimes it goes backwards when you scroll down. Most likely there needs to be a few extra lines of jQuery in the Foundation Access theme. I think the file containing the code is called app.js, in the js folder in the theme.

**Comment by btopro** [comment]
need a video of this not working, can't reproduce

**Comment by rickhumphries** [comment]
This doesn't just happen in mobile. I've experienced on desktop too. Usually when there's only a small amount of content on the page (I think) - https://www.youtube.com/watch?v=zV6v7i728tY

**Comment by btopro** [comment]
ahh ok, thank you @rickhumphries that should help me root it out. it's probably
- screen hits the point of triggering the progress bar AFTER
- screen has hit the "bottom" of the content container

**Comment by btopro** [comment]
fixed the math to account for when the screen is taller then the body of the document (which is what was causing the negative math / progress bar to go backwards)
