### ISSUE TITLE
Make an element to visualize steps / progression

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2032]
This is a really nice steps to completion / progression component that shows where you are in a process. With some Clean up and re-scoping as to the labels / animation speed, this would be a great way of illustrating to people that they've finished a lesson, are starting a new one, are at the next step in a studio process, etc.

https://www.webcomponents.org/element/timeu/timeu-wizard/v1.1.0

**Comment by btopro** [comment]
https://lrnwebcomponents.github.io/lrndesign-stepper/components/lrndesign-stepper/ @michael-collins LOL we have a team of people doing stuff!!!!

**Comment by michael-collins** [comment]
I like this a lot!
