### ISSUE TITLE
possible studio bugs?

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2034]
There seems to be some strangeness with the Open Studio. It doesn't maintain the section when I move there from the content outline. Additionally, student submissions to open studio appear in master and currently running section even though the assignments are technically different. So far, only one person has submitted work, but the assignment is due in two days. I'm unsure if it's working correctly and students have just not yet submitted, or if it's not working correctly, and student work isn't appearing.

**Comment by btopro** [comment]
Same stuff runnung in 2 other courses w.o. report. Section thing obnoxious I'll have to look into that but they should all be good to submit and see each others work

**Comment by btopro** [comment]
`/cle/admin/bulk` shows the assignments listed per section at a high level. Also seeing someone submitted and did so under the correct section / assignment so I think they are just not working quickly :)
