### ISSUE TITLE
Issue when uploading an image to a template 

### ISSUE THREAD

**Issue by Anthall** [elmsln/elmsln#2035]
Hi There. 

I'm creating templates for the individual elements of our course style. I'm setting these up using the Wysiwyg Templates in the content authoring section. When I go to add a thumbnail image to the template I get the below error message? Any ideas what this means?

![image](https://cloud.githubusercontent.com/assets/24223210/26586017/d1277aa0-4545-11e7-9c02-2440bcde02fd.png)

Thanks
Anthony

**Comment by btopro** [comment]
Yeah that happens I think when a template already has an image under the hood. That approach will need to be replaced with a more sustainable alternative as we move further into the web component future as is but good to know. wysiwyg_template module is stretched to its limits currently.

**Comment by Anthall** [comment]
Thanks Brian, Is there a short term fix to this? It's happened when I've imported a template which has a thumbnail image attached.

**Comment by btopro** [comment]
So this happens when you try to add an image to any template or an existing one with an image?

**Comment by rickhumphries** [comment]
@btopro I'm going to tackle this issue using the features module as you've described in #2004 

I'm comparing the feature I've created against the 'textbook_templates' one you have at `/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/textbook/features/textbook_templates` and it seems the only thing that I need to add is within `textbook_templates.module`:

```
**
 * Implements hook_wysiwyg_templates_load_alter().
 */
function textbook_templates_wysiwyg_templates_load_alter(&$templates) {
  // This is the array we need to add stuff to...
  $textbook = array(
    'vocab_term',
    'secondary_sources_list',
    'paperstack',
    'line_header',
    'icon_header',
    'heading_solid_bar',
    'grid_of_video',
    'buttons',
    'case_study',
    'callout_panel',
    'regular_panel',
    'two_column_list_image',
    'two_column_list_video',
    'topic_reading',
    'quote',
    'flex_video',
    'lorem_ipsum',
    'clean_table',
    'table_of_terms',
    'table_style_1',
    'table_style_2',
    'materialize_card',
    'materialize_collapsible',
  );
  foreach ($templates as $key => $template) {
    // see if the template matches one in the textbook definition
    if ($template['image'] == '' && in_array($template['name'], $textbook) === TRUE) {
      $templates[$key]['image'] = '/' . drupal_get_path('module', 'textbook_templates') . '/images/' . $template['name'] . '.png';
    }
  }
}
```
So this should work if I add this code to my `buttercups_templates.module` file, replace the templates in the array with ours (machine names) and change
`$templates[$key]['image'] = '/' . drupal_get_path('module', 'textbook_templates') . '/images/' . $template['name'] . '.png';` 
to
`$templates[$key]['image'] = '/' . drupal_get_path('module', 'buttercups_templates') . '/images/' . $template['name'] . '.png';`

**Comment by btopro** [comment]
yeah that's basically how it works. It's just reading off the file system to present those and override what it wants to display by default (since the default doesn't really work as your dev found)

**Comment by rickhumphries** [comment]
If I just update the code in the feature directly, will the changes take effect in the courses it's switched on?

**Comment by btopro** [comment]
which feature? the elms one or a buttercups one? this hook runs at execution time right b4 presenting the templates so dont need to revert

**Comment by rickhumphries** [comment]
The buttercups one. OK great, I'll update and see how it goes

**Comment by rickhumphries** [comment]
I've updated the .module file but it's causing a HTTP 500 Error on the whole site. This is the file content now:
```
<?php
/**
 * @file
 * Drupal needs this blank file.
 */
 
/**
* Implements hook_wysiwyg_templates_load_alter().
 */
function textbook_templates_wysiwyg_templates_load_alter(&$templates) {
  // This is the array we need to add stuff to...
  $textbook = array(
    'accordion_drop_down',
    'action_textbox',
    'bee_page_break',
    'box_no_icon',
    'british_values_modal_pop_up',
    'button_pop_up',
    'button_text',
    'captivate_container',
    'collums_two',
    'columns_three',
    'example_box',
    'fsnumbers',
    'h2_with_lines',
    'h3',
    'h5p_question_set',
    'icons_outside_of_box',
    'image_centered',
    'images',
    'important_pullout_text',
    'module_introduction',
    'paragraph_and_list',
    'pharmacist_modal_pop_up',
    'responsive_table',
	'safeguarding_modal_pop_up',
	'show_or_hide',
	'step_1_2_3',
	'table_non_responsive',
	'tabs',
	'text_center',
	'textbox_legal',
	'textbox_with_icon',
	'video_container',
	'white_page_container',
  );
  foreach ($templates as $key => $template) {
    // see if the template matches one in the textbook definition
    if ($template['image'] == '' && in_array($template['name'], $textbook) === TRUE) {
      $templates[$key]['image'] = '/' . drupal_get_path('module', 'buttercups_templates') . '/images/' . $template['name'] . '.png';
    }
  }
}
```
Are there any other changes I need to make?

**Comment by btopro** [comment]
`textbook_templates_wysiwyg_templates_load_alter` should be `buttercups_templates_wysiwyg_templates_load_alter`

**Comment by rickhumphries** [comment]
That did it :) thanks 👍
