### ISSUE TITLE
Add token replacement to Markdown textfilter configuration

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2039]
Bug:
- Drupal tokens and CIS tokens aren't on by default in the Markdown text filter.

Need to add them to the Markdown feature.

![download](https://cloud.githubusercontent.com/assets/3428964/26682447/7dad696a-46ae-11e7-88d5-bd435be39120.png)

**Comment by btopro** [comment]
This already exists but maybe we want to think about enabling it by default in mooc

`mooc_markdown` module provides this though it's currently listed as an extra / manual enable project.

**Comment by cgldevel** [comment]
Sorry didn't see your post --  reverting now. :)
