### ISSUE TITLE
Gradient Issue in the Media Server

### ISSUE THREAD

**Issue by cmd30** [elmsln/elmsln#2041]
Gradients don't appear in media server SVGs 
https://media.ed.science.psu.edu/content/biol110carbonlifephospholipids
<img width="1264" alt="screenshot 2017-06-01 11 03 28" src="https://cloud.githubusercontent.com/assets/14110329/26686112/00874e86-46ba-11e7-88e7-4ef5aa971e19.png">

**Comment by btopro** [comment]
weird... what's it supposed to look like so we can have an idea of what might be missing in render

**Comment by btopro** [comment]
immediate guess is the SVG sanitizing thing that @heyMP added as part of that solution

**Comment by heyMP** [comment]
Here is the process for whitelisting the gradients elements: https://www.youtube.com/watch?v=Nb9W9-Ufq0g&list=UURX2GGMGmt9phKFoOElKA_A&index=55

**Comment by heyMP** [comment]
@cmd30 Can you post an image of what it should look like?

**Comment by btopro** [comment]
proposed attributes to allow to pass through
`viewBox, gradientUnits, gradientTransform`
proposed tags to allow
`linearGradient`

**Comment by heyMP** [comment]
as well as the `radialGradient` tag.

**Comment by nmillin** [comment]
Added pull request. Thought I did that last week...
