### ISSUE TITLE
Example card stack template

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2043]
Sharing our html/css for example card stack with little dude poking out. 

Still an issue with spacing on certain devices but works slightly better in this regard within ELMS than on codepen:
https://codepen.io/rickhumphries/pen/YQWOQW

**Comment by btopro** [comment]
Should be a variation of https://www.webcomponents.org/element/LRNWebComponents/lrndesign-paperstack, maybe a style or mode change to be one vs the other. Obviously dropping the little guy and dropping the "examples:" image and replacing it /w some slanted text that's CSS controlled.

**Comment by btopro** [comment]
@bterp-web this would be a good one to tackle 1st prior to studio. Should be pretty quick but I can help in streamlining workflow and critique code quality / internals of the element. Then we can move on to the studio parts which will be a bit more involved but this can be an easy ramp off of the cool animations your doing to an object that's produced open first in naming, etc.

**Comment by btopro** [comment]
thanks for the contribution @rickhumphries via your staff and congrats to @bterp-web on her 1st commit to the project :)

**Comment by rickhumphries** [comment]
Nice work @bterp-web!
