### ISSUE TITLE
Polymer Caching Problems (Website Remodel)

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#2044]
Hi all -- 

I've been working on the website and noticed a strange occurrence. Polymer is caching several items from the previous page load when it loads a new page that is similar. For example: If I navigate to the blog page that lists all blog posts, and then change over to the about section, it displays the first 4 blog post images (with no links to click into the content itself) on the page load. This is also happening with videos in the blog to a team profile page. I'm attaching some screenshots of this issue and I'll make a short troubleshooting video that I'll post here as well to document the problem. If anyone knows why this caching is happening -- let me know and I can make the fix!

**Comment by mmilutinovic1313** [comment]
https://youtu.be/MSMO41HbWe8

**Comment by mmilutinovic1313** [comment]
Fixed problem between blog posts and team profiles: 

https://github.com/mmilutinovic1313/elmslnwebsite/commit/212100b44442ec931dc07c9ff0a77911d65a6cf0

Still getting some issues in switching between blog and about / shop page.

**Comment by btopro** [comment]
@mmilutinovic1313 are there steps to building this website that's not done so we can hand it off to someone at some point to try and repair ;) ?

**Comment by mmilutinovic1313** [comment]
@btopro yessir -- working on documentation!
