### ISSUE TITLE
Tweaks.css and H5P font Size

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2046]
Bug:
- v0.7.1

This issue was raised in #1743 but there's an issue with font size that's still occuring for us. It seems this is affecting it:
![image](https://user-images.githubusercontent.com/4973810/27227133-1844e29a-529a-11e7-978b-267ece772763.png)

Although it doesn't affect the Question Set H5P content type, it does still affect the individual question types such as multiple choice, fill in the blanks etc.

**Comment by btopro** [comment]
#2019 related

**Comment by nmillin** [comment]
https://github.com/nmillin/elmsln/commit/38fc7e4098b0cbf534ac9a45944f7ec88b053a80 (proposed in #2019) would decrease the font-size to 1.2rem.

I wasn't able to reproduce an issue with 1.3rem using the example from https://h5p.org/multichoice.

**Comment by btopro** [comment]
should be resolve after the major css gutting to simplify things
