### ISSUE TITLE
Timelines - Adding Borders

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#205]
Currently timelines display with a considerable amount of white space, and this leaves the area looking empty and undefined.   Maybe a block of color or border would help with the display.  

![screen shot 2015-08-21 at 11 41 44 am](https://cloud.githubusercontent.com/assets/12716869/9412947/e9308af8-47fc-11e5-8f94-26c86bb1b303.png)

**Comment by btopro** [comment]
This comes from interact; probably able to target the classes applied (or maybe we need to apply some) and then slap a border on it so it's more obvious that it's a part of the page / widget instead of now where it blends in a bit too much

**Comment by michael-collins** [comment]
This sounds like a job for the style guide! @heyMP

**Comment by btopro** [comment]
this is rendered by cis_filter in the `_cis_filter_iframe_render` function. I think all we need is to point to the tool in question in the class names and then make one for interact which says to have a border as its default behavior (right now it just has classes for frame and entity type). I'd do this but as that's being refactored by @heyMP in a fork I don't want to touch it and risk merge conflict hell

**Comment by btopro** [comment]
class will be in place to do this now w/ the next commit

**Comment by btopro** [comment]
![2015-10-06_15-48-47](https://cloud.githubusercontent.com/assets/329735/10320500/c0175d54-6c41-11e5-9103-00fa759dcdfd.png)
@Deb-G here's a mock up of what it would look like currently (I haven't applied to our system yet)
