### ISSUE TITLE
Deliver menu icons from lrn component

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2050]
Icons on the tip bar are not web components yet and should be paper button with lrn icon. For now let's just wire it into tpls

**Comment by nmillin** [comment]
It looks like this commit squished the icons a bit. Is this a bug?

![before](https://user-images.githubusercontent.com/1018136/27490836-66eb83f2-5805-11e7-801c-ff83cb479066.jpg)

![after](https://user-images.githubusercontent.com/1018136/27490835-66e62ea2-5805-11e7-90e4-fe78c5dbbeb3.jpg)

**Comment by btopro** [comment]
refresh your VM with the latest from 0.9.x. Those icons are replaced with new ones (ignore the MOOC as App / upload thing they are prototypes)

![2017-06-23_12-26-41](https://user-images.githubusercontent.com/329735/27491165-3fc8af98-580f-11e7-8217-3d86bc8b79ea.png)

**Comment by nmillin** [comment]
ugg... sorry. Still getting the hang of ELMSLN.

**Comment by btopro** [comment]
no worries. Aren't we all :)
