### ISSUE TITLE
Missing Module Warning

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2052]
Bug:
- 0.7.2

I've just checked our recent log messages and it looks like we're getting the following error being written every minute or so about a missing module called beautytips

![image](https://user-images.githubusercontent.com/4973810/27296389-91da15fa-5518-11e7-8aa7-d5071a642df5.png)

Was this module previously in core? Or maybe someone was typing into Google and accidentally made a commit? :p This is the page it points to about the documentation - https://www.drupal.org/node/2487215 ?

**Comment by btopro** [comment]
@rickhumphries this is an annoying thing from D7.50 core upgrade (I  think it came in then). There's a module in our setup that can help remove it everywhere as a single sweep

```
drush @elmsln en module_missing_message_fixer --y
drush @elmsln mmmff --all --y
```

That should ensure that this (stupid) module is enabled which can then clean up those registry notices and then the 2nd call actually runs the clean up to remove all the issues from showing up. You can read more about it here -- https://www.drupal.org/project/module_missing_message_fixer

**Comment by rickhumphries** [comment]
Thanks!

**Comment by rickhumphries** [comment]
Ran the drush commands and the UI interface here `admin/config/system/module-missing-message-fixer` says there aren't any missing modules. But I'm still getting the warnings here `admin/reports/dblog`

![image](https://user-images.githubusercontent.com/4973810/27447103-b0ef04a8-5777-11e7-8218-94494711c4c4.png)

weird

**Comment by btopro** [comment]
would have to know what said module is in that message but other then that dono, maybe a bad locally developed module or something

**Comment by rickhumphries** [comment]
still saying it's the beautytips module so assuming this:
https://www.drupal.org/project/beautytips

**Comment by btopro** [comment]
weird... I don't recall us ever having that in the system tho i could be wrong
