### ISSUE TITLE
explore removing authcache

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2055]
From initial testing, there doesn't appear to be any negative repurcussions of getting rid of authcache and elmsln_authcache features. There are 2 ways to approach this issue:

1. drush dis it everywhere. This could be a problem if anything implements this module
2. remove the code and then in an upgrade hook use the module missing message fixer to clean up the registry.

Option 2 is very similar to 1 in net effect but if there's any module people have that depends on authcache (which there shouldn't be) then it won't impact it.

It appears that this module doesn't provide as much because of advances in apdqc. It also has added complexity over the years and would be nice to drop some edge cases that pop up from time to time if possible. Still, needs testing.

**Comment by cgldevel** [comment]
If we go with option 2 and remove the module / feature -- where should I place the update hook?

**Comment by btopro** [comment]
elmsln_core as that runs everywhere

**Comment by btopro** [comment]
closing, we're going to be going more headless anyway so it's not going to hurt anything. If it does then we can always get rid of it later.

**Comment by btopro** [comment]
blah ok, time to ax this

**Comment by btopro** [comment]
will need to get more reports back on if it was successful but she's gone now..

**Comment by btopro** [comment]
well that was way too much effort to do..
