### ISSUE TITLE
Content styling / widget guide

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#206]
We've tried for years to do this and now I think we might have the right person to really make it a thing.

We need a content style guide for describing instructional components. We've got a lot of thought into how this starts to happen already but have yet to officially start doing it. Things involved in this:
- [x] Add different heading options to the styleguide #307
- [x] templates that match these attributes
- [x] instructional significance of components aligned w/ visual significance
- [x] Content Layout Ideas to Blueprint/Template #1074

- [x] accessibility minded default selections and templates
- [ ] definition of different attributes that can have color associated with them
- [ ] Documentation / Official style guide page that illustrates all supported components (and that can serve for visual regression)

As we're on Materialize this gets a lot easier to build new templates / have design criteria to build off of. See http://materializecss.com/ for html you can use and we've started adding some templates in that match this styling already.

**Comment by btopro** [comment]
Related: #42 #205 #155

**Comment by rickhumphries** [comment]
Thought I'd just post this link here as had trouble finding it the other day :) bit.ly/1XkE9km

**Comment by btopro** [comment]
thank you!

**Comment by btopro** [comment]
#669

**Comment by btopro** [comment]
![icon_header](https://cloud.githubusercontent.com/assets/329735/21322427/f748580a-c5e6-11e6-9f85-541456b3264c.png)
![line_header](https://cloud.githubusercontent.com/assets/329735/21322428/f74bc076-c5e6-11e6-907c-233efddee608.png)

**Comment by btopro** [comment]
inspiration from @rickhumphries 's group

**Comment by btopro** [comment]
![2016-12-19_14-12-30](https://cloud.githubusercontent.com/assets/329735/21325624/3dda2f1a-c5f5-11e6-9ac8-13bdc7a6823c.png)

@rickhumphries can you ask your graphics person to get you an SVG version of this example icon? Also what font is that? I want to start reverse engineering some of these things into possible shortcode templates / etc

**Comment by rickhumphries** [comment]
Will do. The CSS behind that font is: `font-family: 'Sriracha', cursive;`

**Comment by rickhumphries** [comment]
Oh, and the heading is `font-family: 'Special Elite', cursive;`

**Comment by btopro** [comment]
![secondary_source_list](https://cloud.githubusercontent.com/assets/329735/21328634/ee102c1a-c602-11e6-84a6-460eda4341a1.png)
![vocab_term](https://cloud.githubusercontent.com/assets/329735/21328633/ee0e7f6e-c602-11e6-8fee-51235fdac238.png)
![paperstack](https://cloud.githubusercontent.com/assets/329735/21328635/ee11cb60-c602-11e6-8ffb-790f03e1430c.png)

**Comment by btopro** [comment]
breaking the last two points off into other issues. We've now added like 8 new templates associated since this issue first opened and now it's onto the documentation of those so those issues will get moved to something else for the future.
