### ISSUE TITLE
Open Studio

### ISSUE THREAD

**Issue by bterp-web** [elmsln/elmsln#2067]
![screen shot 2017-06-23 at 4 00 13 pm](https://user-images.githubusercontent.com/22225779/27499767-495ff75e-5833-11e7-8e35-5ed8d6068068.png)

There is not a link attribute on the lrndesign-gallerycard. The link comes through as the text attribute.

**Comment by btopro** [comment]
I see the confusion (and it is confusing). The lrnapp-open-studio element passes down via data binding like this:
![2017-06-24_09-45-59](https://user-images.githubusercontent.com/329735/27509054-fa512b26-58c1-11e7-817a-8ac40dc7be94.png)

So whats happening is there's a body of a document / node / student submission that actually is just a link to google :).  There is a (more or less) hidden field we don't have a way of populating via the app yet that is for link. Image is the only thing we bridge over correct that if its drag and dropped in the field it associates to the right place on the back end.
