### ISSUE TITLE
Add SIS value to CIS

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2073]
@rickhumphries Question: Do you utilize ANY of the properties in CIS that are left over from the 1.x move in which you broke the 1.x system out to another location. I ask because I'm working through the course content type to add a 'sis' value so it can be relational with internal systems and while I'm there doing features work I might as well gut stuff no one is using (where no one is you and me)

**Comment by btopro** [comment]
Examples:
- Basically anything in `Resources` group
- Basically anything in `Promotional` group

**Comment by rickhumphries** [comment]
@btopro are both these groups within the course content type? I can see promotional but not resources. We definitely don't use promotional stuff anymore and doubt we use the resources either 

We have a few of our own custom fields which we've added in but yeh these should be alright anyway

**Comment by btopro** [comment]
okidoke, and those are captured in features you have elsewhere through OB so they should be fine. I just want to reduce the complexity of the course record while i'm doing the SIS stuff but wanted to ask 1st

**Comment by rickhumphries** [comment]
Hmm, yeh OB probably captured them, but not completely sure. I also went rogue and added a couple myself (and definitely didn't capture them), so might need to look into that before updating next (which we'll need to do soon judging by recent email...)

**Comment by btopro** [comment]
yeah, capturing changes is always a good idea though at least when we do reverts and stuff it just impacts the fields that were defined and any additional should hang around
