### ISSUE TITLE
Media Server filter sidebar overlaps content area.

### ISSUE THREAD

**Issue by cgldevel** [elmsln/elmsln#2074]
Bug:
- Media Server filter sidebar overlaps content area:
![screen shot 2017-06-28 at 11 15 38 am](https://user-images.githubusercontent.com/11019355/27645593-6e8c324e-5bf4-11e7-8e5c-a19a4971899c.png)

Proposed Solution: Add margin-right 35px to css.  I've tested this and it seems to work fine -- If it checks out, I can submit PR.

![screen shot 2017-06-28 at 11 17 27 am](https://user-images.githubusercontent.com/11019355/27645606-787363d6-5bf4-11e7-88d2-03b83d1cbccd.png)

**Comment by btopro** [comment]
this float method is currently on everything that has an exposed block of filters as an FYI

**Comment by btopro** [comment]
@cgldevel make sure there's a PR associated to this to get it in

**Comment by cgldevel** [comment]
@btopro  I closed this because it looks like whatever changes heymp pushed recently, also covered that issue as well; the sidebar is no longer overlapping.

**Comment by btopro** [comment]
gotcha
