### ISSUE TITLE
Pre commit incorrectly identified debug code

### ISSUE THREAD

**Issue by andrewbelcher** [elmsln/elmsln#2084]
When I tried to make this commit, I got the following error:
```
.git/hooks/pre-commit: 68: .git/hooks/pre-commit: php: not found
---------------------------------------
^ Found PHP debug code in core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/cis_section/cis_section.module
---------------------------------------
.git/hooks/pre-commit: 68: .git/hooks/pre-commit: php: not found
---------------------------------------
^ Found PHP debug code in core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/cis_section/src/CisSectionRosterProcessor.php
---------------------------------------

git: Can't commit; fix errors first.
(If you definitely need to commit this as-is, use the --no-verify option.)

If the reported line numbers do not match, try stashing your unstaged changes:
git stash save --keep-index
```
There's definitely none of the disallowed functions in either of the changed files... My environment doesn't have php installed, so I think that it thinks the regex is failing...

**Comment by heyMP** [comment]
Can you try using the `--no-verify` option when committing, then push to your fork so I can take a look at it.  I wasn't aware that we were implementing pre-commit hooks.

**Comment by btopro** [comment]
It's in the recommendations for setting things up for local development I believe.

**Comment by btopro** [comment]
if system had PHP probably wouldn't happen. we also don't require this for builds it just mostly to help in local development
