### ISSUE TITLE
Add option to display page title in course content

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2086]
Feature request:
- In some circumstances, we need the page title to be displayed above the content instead of being hidden.

![screen shot 2017-07-05 at 10 42 16 am](https://user-images.githubusercontent.com/3428964/27869705-c2981f18-616e-11e7-84a0-426a399ca54c.png)

**Comment by btopro** [comment]
This is hidden via template I believe since the title would duplicate based on how collins used it so yea an option would be good.

**Comment by btopro** [comment]
HAXcms themes will provide the flexibility to allow for things like this instead of our archaic template methods
