### ISSUE TITLE
Webcomponents in H5P

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2087]
I'm currently trying to get Mathjax working in H5P questions in our media system.  I think a great solution would be to put that functionality into a web component.  So we would need to:

- [x] Enable web components on the media server.
- [x] Ensure web components can work in the H5P wysiwyg

**Comment by nmillin** [comment]
@heyMP & @btopro I would suggest something along the lines in https://h5p.org/node/1001. Basically, add the MathJax JS to the page and include the MathJax CKeditor plugin so it works with the WYSIWYG editor.

I've dug into H5P's code, and I wouldn't suggest web components inside of H5P. You'll have a bad time.

If this sounds like a good idea, I can dig into this more. Let me know.

**Comment by heyMP** [comment]
I tried something different.  Rather than getting involved with the CKEditor portion of it which is a mess with web components, what if we just altered the text output right before it's rendered, run it through `filter_xss` and whitelist all of our web component tags.

It would look like this: 

![screen shot 2017-07-06 at 12 30 12 pm](https://user-images.githubusercontent.com/3428964/27921920-55a2f142-6247-11e7-95f3-4acf04098634.png)

![screen shot 2017-07-06 at 12 09 32 pm](https://user-images.githubusercontent.com/3428964/27921925-590bb986-6247-11e7-836a-d656fbbd655e.png)

@nmillin what do you think?

**Comment by nmillin** [comment]
@heyMP ah, sorry. I was thinking along the lines of using the CKeditor mathjax plugin ([demo](http://sdk.ckeditor.com/samples/mathjax.html)) since H5P uses CKeditor so much.
I agree that web components and CKeditor would be fun.

I'll back away slowly.

**Comment by heyMP** [comment]
lol... no problem at all.  Feedback and additional options are never bad.  Keep em coming!
