### ISSUE TITLE
Create specification for developing new features.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#210]
Need to develop a model with documentation for naming conventions and build pattern for creating new feautres/distros/tools.  Similar to the KIT spec from Open Atrium.

**Comment by btopro** [comment]
Visual of how these things build on each other
![Visual of core stacking on eachother](https://cloud.githubusercontent.com/assets/329735/9475751/b892cafe-4b36-11e5-8a12-e18d0b05cde6.jpg)


What we need is something of a specification for that critical "distro" layer and how it's constructured. the rest is pretty clear
