### ISSUE TITLE
Media Confused About Section Context

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2102]
Bug:
- 0.7.2

- When creating content in Media, it can get confused as to the course/section that I'm currently in. For example, I'd previously been doing stuff in 'Flu-Refresher', then moved around a bit, came into Media, selected a different course, however the system is putting me in Flu-Refresher still:
![image](https://user-images.githubusercontent.com/4973810/28141900-8330bcc0-6756-11e7-8177-fc5378a2e739.png)

It's also then automatically adding this as a section to all new Media created - even when I'm doing it within a different course.

**Comment by btopro** [comment]
if your on 0.7.2 a you claim then this is a known issue I believe that was solved in 0.8.0 because we used to experience it when building from time to time but the logic surrounding the context switch got cleaned up.
