### ISSUE TITLE
Virtual Classroom tool

### ISSUE THREAD

**Issue by aryavart** [elmsln/elmsln#2104]
Hello sir 

I want to know, is virtual classroom tool  included or support ELMSLN
If  not, sir is there any future plan to include this tool

Thank you so much for providing such a worthful platform 

With warmest and kindest regards 

an ELMSLN admirer

**Comment by btopro** [comment]
what kind of things are you looking for in a virtual classroom tool? Like whiteboard stuff no but we've got a lot of content production / management areas which are being used to augment classrooms. Also there's deep support for https://h5p.org/ which brings in a lot of interactivity which can be built right in elmsln.

**Comment by aryavart** [comment]
Thank you so much for Quickest response and taking time to respond 
my query 

Sir, In virtual classroom, i need all tools to take Live Classes
Whiteboard Tool
Screen Sharing 
Video and Audio 
Live Recording
Chat
Sir Drupal is nice, ELMSLN is Excellent, H5P also provide many tools 
Everything is fine, but i am missing the most important thing i need- Virtual Classroom Tool

I am sorry sir i don't know any technical complicacy so please excuse me, as a common user i want to know is it possible to include virtual classroom tool in ELMSLN

**Comment by btopro** [comment]
we would certain add those capabilities if someone paid / hired someone to contribute them but we won't be adding these at this time. Definitely in scope, just need more people to work on cool stuff like this :)
