### ISSUE TITLE
SVG figure label missing tag and course field 

### ISSUE THREAD

**Issue by carlydcreative** [elmsln/elmsln#2105]
Both tags have to be added manually to figure title item in media server after SVG is saved
![screenshot 2017-07-14 14 53 44](https://user-images.githubusercontent.com/14110329/28226551-8e07991c-68a4-11e7-933a-1816167e26d6.png)

**Comment by btopro** [comment]
node/add/figurelabel is the content type that needs to get these, didn't understand at first

**Comment by btopro** [comment]
gitch with _resizeMenu function in autocomplete_deluxe

**Comment by btopro** [comment]
tested in 0.10.x and appears to be working at this time (has those fields)

**Comment by btopro** [comment]
#2416 would skip this kind of an issue though it's way off
