### ISSUE TITLE
Guidance if not logged in on course page

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2106]
v0.7.2

Feature request:
I've come across a few occasions where the bakery SSO has failed for whatever reason. By that, I mean the user has logged into the Master site, then gone through to the course site, but is not logged in and so they come to a blank Welcome page.

In all cases, all that the user needs to do is click on the user icon and click the log in link...this must refresh something because they are then logged in without having to enter their details again. However, since this isn't obvious we get a lot of queries thinking the site is broken etc. 

Therefore, I thought it might be a good idea if there was some simple default information on a welcome page for anonymous users along the lines of 'You are not currently logged into your course. Please click the user icon (image of icon) and click the log in link.'

**Comment by btopro** [comment]
why are they able to get to it anonymously? The elmsln_bakery module has the ability to force a login for this edge case so long as it requires logins.

**Comment by rickhumphries** [comment]
I'm not sure why they show up anonymously. They get there by first logging into the Master site (CIS in our case). The courses show on their dashboard. They click to access the course. Then when they navigate there, they aren't actually logged in there. 

Is there a setting on the course for bakery that I need to change to force logins?

**Comment by btopro** [comment]
check the drupal layer permissions on that one and see if anonymous users can access things. Bakery is supposed to regenerate a login during this edge case

**Comment by rickhumphries** [comment]
Just checked and the Drupal layer permissions that an anonymous user has are:
- View LMSless bar
- Access View changes button
- Access iframe version

Are these normal?

**Comment by btopro** [comment]
anon should have nothing on courses in your setup most likely since you aren't letting them see anything (again this is me guessing here a bit)

**Comment by btopro** [comment]
`You have to login to see this content.` will display if they hit this edge case now.
