### ISSUE TITLE
Students Profile Edit in Course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2111]
Bug:
- 0.7.2

I'm getting an issue where students who are logged into their course can click on the user icon > profile, then the edit icon appears which allows them to attempt to change their password/email address etc. locally within the course site itself:

![image](https://user-images.githubusercontent.com/4973810/28664490-9788e3e2-72b8-11e7-9c11-fe9f78f3c964.png)

This would be an issue anyway, as you'd want them to change their profile info in the Master site, however, I'd actually just prefer it if we could prevent them from being able to edit their profile at all as we have a separate 'edit profile' form in the CIS for this. I can't see a Drupal permission to change this locally though...is there a way?

**Comment by btopro** [comment]
have you logged in as someone NOT user 1 and done this? User 1 currently has the ability to get to the drupal user edit page for legacy purposes but the behavior you describe is what's supposed to happen with any other user (hitting edit profile anywhere is supposed to direct to their central profile, CIS or CPR)

**Comment by rickhumphries** [comment]
Yes, I've been logging in as a student in courses.xyz/course1, going to profile, then the edit button shows, when I click this I'm in courses.xyz/course1/user/001/edit - so the student isn't being re-directed either.

**Comment by rickhumphries** [comment]
So I guess this is both a bug report, to say the student isn't being redirected, and a feature request, that we're able to add a Drupal permission so the student can't access the 'edit profile' button - so this sort of thing maybe https://www.drupal.org/project/edit_own_user_account_permission ?

**Comment by btopro** [comment]
so ur saying u dont want people to be able to edit their own account is that correct?

**Comment by rickhumphries** [comment]
Yeh that's correct

**Comment by rickhumphries** [comment]
We've added this module and it's done the trick - https://www.drupal.org/project/edit_own_user_account_permission

**Comment by btopro** [comment]
ok, closing out then since we dont really have that usecase currently and you found a solution :)
