### ISSUE TITLE
add PR to lrnsys-comment

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2112]
figure out how to manage patches in bower (or fork paper-input to lrn area and apply the PR in this thread)
https://github.com/MaritzSTL/mtz-marked-editor/issues/6#issuecomment-318539281

This needs testing but would allow us to have a github style very lightweight markdown editor on our comments / elsewhere while still playing nice with the paper-textarea which is awesome looking (https://lrnwebcomponents.github.io/lrnsys-comment/components/lrnsys-comment/)

**Comment by stramel** [comment]
@btopro You can point to my fork if you would like. Modify your `bower.json` to do this.

`"paper-input": "stramel/paper-input#feature/selection",`
