### ISSUE TITLE
Implement Smoothstate.js for better UX

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2114]
https://github.com/miguel-perez/smoothState.js#built-with-smoothstatejs

https://css-tricks.com/add-page-transitions-css-smoothstate-js/

This would allow Drupal to act more like a PWA in that it only updates the parts of the UI that changed in the body of the document. After about 15 minutes this is mostly working though it would need more cleaned up to be worthy of adding at this time. It also messes w/ the JS a bit so the closer we get to being all web component driven the better this will operate. Right now there some JS that breaks / doesn't work correctly because of the loading within the same document as the previous page but sooooo much of it does already :)

This video shows what we gain as a result: drastically better performance in Firefox and Safari -- https://www.youtube.com/watch?v=aP1B19bVBjA

**Comment by rickhumphries** [comment]
This is soooo cool btw! Excellent UX improvement!

**Comment by btopro** [comment]
thx, still aways off most likely just cause of testing requirements but I think it'll be viable in the coming months the more components make their way in and conditional JS/CSS makes its way out (conditional here being like Page 1 vs page 4 load different style sheets or a view vs not a view, custom CSS/JS applied globally would be fine)

**Comment by btopro** [comment]
incredibly promissing but unfortunately that's about where it ends. It seems to have issues with doing replacements for certain custom elements. The good news is that there's work on a revamped content presentation interface which takes this into account already and will ajax load everything.

Early work on it is patterning this style atm -- https://dmd-program.gitbooks.io/dmd-100-sp17/content/topics/projects.html Present a two-pane that can scroll independently and auto jog the placement on the left to have visible whatever page is being looked at on the right.  Not exactly this, inspiration.

**Comment by btopro** [comment]
#2026
