### ISSUE TITLE
Slow transaction component - /restws_page_callback -> httprl_establish_stream_connection

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2115]
v0.7.2

We're having issues today with really slow performance across the system. Looking at the details on newrelic it seems to be to do with a web transaction called /restws_page_callback and, tracing it a bit further, the slowest component of that is 'httprl_establish_stream_connection'

The transaction seems to be traceable to a particular course for which we have a section set up that works kind of like a demo site. There is one universal login that we have distributed to many students. 

Is this something that would potentially cause the issues I've described, if the same login was being used at the same time by multiple students? Or is there something else this could be?

Thanks

**Comment by btopro** [comment]
restws_page_callback technically delivers every page.

**Comment by rickhumphries** [comment]
Hmm, I've also seen this on another course now too. Could it be linked to the volume of xAPI/TinCan statements being produced concurrently?

**Comment by rickhumphries** [comment]
Meant to say also that this isn't a public demo space, and we haven't published what the singular login is publicly either (we've just made it available to a specific company)

**Comment by btopro** [comment]
Also possible, is the tincan box hosted elsewhere? We did make xAPI statements asynchrounous at one point but can't recall what version (meaning they were blocking before hand so a flood like you mention was possible to hamper things potentially) hmm.. what kind of concurrent users you hitting any idea?

**Comment by rickhumphries** [comment]
Yeh the tincan box is on a different server. Hard to say the exact number of concurrent users we're getting because it varys and not easy to report on for specific times, but here's a snapshot of what I see right now:
![image](https://user-images.githubusercontent.com/4973810/28825780-8bea5cea-76bf-11e7-83ef-13325fdae79f.png)
I'm getting stress hotspots looking at it

**Comment by rickhumphries** [comment]
#1856 may be related to this also

**Comment by btopro** [comment]
Ya I mean if you get flooding of web calls those go I to elms before launching out so you'd be spamming yourself to make calls oit to track things like this

**Comment by rickhumphries** [comment]
I disabled the TinCan API from Media and the ELMS LRS stuff too but that didn't improve things. Therefore I think it's simply related to the number of users on a single login but still not sure.

I've been told that there are 700 users that this single login has been circulated to, but not sure how many would be concurrently using it

**Comment by btopro** [comment]
the courses will still ship it around. If there are 700 concurrent users you'd want to bump up the specs on your infrastructure I'm guessing.

**Comment by rickhumphries** [comment]
Hmm, yeh it might just be that. It's been better the last few days as less users have been using that login so it's not an issue with ELMSLN itself. Cheers
