### ISSUE TITLE
Favicon is overidden when changing Course settings

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2116]
We change our favicon in the Drupal theme settings, however - when you save any course settings at `/cis/course-settings` the favicon reverts to the default

**Comment by btopro** [comment]
hmm... favicon is currently delivered from the html.tpl.php bc of all the variations; will need a check for if custom use that otherwise provide the million versions for diff platforms we now provide by default

**Comment by btopro** [comment]
If you set this on `/admin/appearance/settings/mooc_foundation_access` it'll keep now
