### ISSUE TITLE
Changing the Paper Avatar Icon per Course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2117]
v0.8

Is it possible to configure this icon? 
![image](https://user-images.githubusercontent.com/4973810/28935062-1e67e4e0-787b-11e7-8257-b4a36fe2c0cd.png)

Either change it or switch it off on a per course basis?

**Comment by btopro** [comment]
it's a mathematical hash based on the name of the course so currently no unless it was removed from the system via template change or support was added for an icon (which CIS is in early days of)

**Comment by btopro** [comment]
#935 if we had access to an icon field we could supply that in the event its used, don't use jdenticon

**Comment by btopro** [comment]
@rickhumphries would you want the option of disabling and/or making an area to upload an icon / image to take its place? Trying to think of what the best solution would be from a flexibilit standpoint for this. It is very useful (when people don't have something else in mind) but if wanting something specific it should be able to be added (or removed entirely).

**Comment by rickhumphries** [comment]
Yeh those three options would be ideal for flexibility:
- No icon
- Upload icon
- Let the robot decide

**Comment by btopro** [comment]
ok. thinking what we might want to do in this case is start with auto or no icon and then move to a model (with all iconography) that it MUST be pulled in via an iron-icon SVG library. Otherwise it'll be very hard to support all possible options (for example, an image that we then crop + none + svg + icon + #840 + auto sorta deal)

**Comment by btopro** [comment]
This has been dropped from the latest #2606 thread as supporting customization in something that was just randomly generated based on name would be overly complicated

**Comment by btopro** [comment]
![2019-06-24_16-52-34](https://user-images.githubusercontent.com/329735/60051200-7a29bc00-96a0-11e9-91bc-866d918ddeb6.png)
latest comp
