### ISSUE TITLE
Captions turned on by default

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2122]
Feature request/question:
Is there a way we can turn off captions for video assets by default? They're not necessary when using a transcript window and we'd like to remove them if possible (although keep the option for users to turn them on if they wanted to). 

Please could you tell me the best way to go about this without editing the core?

**Comment by btopro** [comment]
what video are you referring to and how does it display to suggest a caption? Like the player has the CC button even when there isn't one? It's able player so might just be a setting associated with output of able player which is in the media distribution. If there's something to override (which I dont know hook or if this is what ur talking about) it probably should happen in elmsmedia_video.module.

I agree it should be a feature of the system and core should be improved to allow for it (or just not show it when a CC isn't in use).

**Comment by JackWillDavis** [comment]
Thanks for that, I'll have a look into whether it can be implemented with the module.

The situation is that when uploading any kind of video, we use transcripts, which means that having CC is pretty redundant. However, videos automatically have CC turned on when they start playing and we're looking at a solution to turn them off by default.

**Comment by btopro** [comment]
traces this down. This is the (blah) default behavior of ableplayer. I think I have a patch I could push against it but it's borking some other stuff so I'll have to look into it further.

**Comment by btopro** [comment]
https://github.com/ableplayer/ableplayer/issues/292

**Comment by btopro** [comment]
found it! single boolean statement. I don't want this on by default either so it's getting hacked in there for now unfortunately w/ a patch notice
