### ISSUE TITLE
AA121_logo bar size

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#2124]
Hi Bryan,

The logo bar is still showing up way too big on the header. (see attached screenshot for typical)
 Can you kindly either tell me what I'm doing wrong or, if the source is on the site, ensure that it shows the full course logo?

Thanks,
Peter
![logobar](https://user-images.githubusercontent.com/16839175/29141543-9f72107e-7d1c-11e7-9c73-fb18b4910818.jpg)

**Comment by btopro** [comment]
This has been forced to be the same as the image uploaded and should now show all the contents centered.

**Comment by pja12** [comment]
Hi Bryan,



Thanks for having a go at this. Having a vertically squashed image is quite 
the optimal result; let’s see how I can help fix it.



I believe you’re using an image I sent along on Jan 10 of this year, sized 
at 200x1200. I suspect the 200 was so that it could sort of slide along when 
the page is scrolled, but the visible window is some pixel count smaller 
than 200. By forcing it in, we’re now squeezing the 200 into something 
smaller.



I’m fine either way – I think it depends on what eLearning’s standards are:

1.       If you want to have it scroll, let me know and I can redo a 
200x1200 with more white space at the bottom so more of the logo is visible 
“at rest.”

2.       If you want to keep it forced, let me know what the vertical forced 
pixel count is and I’ll send you a revised one that is sized to (your 
vertical count) x 1200

Again, either one is fine for me per your preference and ease, but let’s 
make it match properly for whichever one you tell me.



Thanks again,

Peter









Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
The container is *currently* 8rem or 128px. We have the slide under approach because the design changes based on community feedback as well as improvements in the design of the system. It is currently all shown but this is not gaunteed in the future unless doing the squashed method. Most of our banners are abstract images and I believe this is the only one which contains text. If you want to keep it as it is, then 128px is the height to shoot for.

**Comment by pja12** [comment]
Hi Bryan,



Thanks for the info. I checked the original file from last Spring (“course 
header bar-v2” 200x1200) and it should’ve allowed for a 128p top height 
visibility (see “course header bar-v2-128 crop” – the red fills below the 
top 128p). That’s part of my confusion that maybe something had gone awry – 
I thought you and I had worked this out really carefully way back in the 
Spring!



I’m attaching a replacement image that shifts the image up more, hopefully 
it’ll work better? I can’t check it against the current since its forced. 
Can you swap ‘em out and kill the forcing so we can see what happens?



Thanks,

Peter





Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
I don't have an attachment, you'll have to email me directly instead of responding to this github thread I guess
