### ISSUE TITLE
AA121_Additional video widget

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#2125]
Hi Bryan,

I'm hoping you can add a third video widget box right below the two existing ones. 
- they should appear on all pages just like the existing ones
- they'll draw from a new set of videos that Cody has been working on this summer. I'll let you know when I hear from him about their status; you and I will likely need to coordinate the uploading to ELMS.
- see attached image for box location

Thanks again,
Peter
![videobox](https://user-images.githubusercontent.com/16839175/29141722-63622da2-7d1d-11e7-99be-539e30bc174b.jpg)

**Comment by btopro** [comment]
This is in place for whenever the videos are added as part of "Area 3"

**Comment by pja12** [comment]
And thanks also for your help with this and the arrow issue.



For the video widget#3, I have uploaded 18 new videos processed by Cody. I 
put them on the ELImedia site per instructions you had kindly provided 
earlier. I used ‘new document’ upload, assigned them to AA121, and tagged 
each of them with “StudentBigIdea”



That should give you the content to point the widget to, if I’m not 
mistaken. That whole process is bit murky to me, so please let me know if 
that was the right way to get the videos to you or if there’s something else 
I need to do that would make it easier.



Thanks once again and I look forward to seeing them live on the site!



Best wishes,

Peter







Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
https://courses.aanda.psu.edu/aa121/node/add/elmsln-random-content can be used to add items to area 3 by selecting Type: Area 3.
https://courses.aanda.psu.edu/aa121/random-content can be used to find / edit / delete existing items

**Comment by pja12** [comment]
Hi Bryan,



Thanks for the direct link. I just burned through the whole stack – turns 
out the previous uploads weren’t the right ones, so I had to redo.

But now the vids appear in the third box on the pages!



The controls are still showing, though, as they had not previously. We 
designed the still images without the player controls which are now blocking 
part of the images. Can you kindly turn off the player control visibility 
when you have a free moment?



One day, when you get this thing together, ask me for my “how to do…” file 
and you’ll have your faculty-side handbook in one shot!



Thanks once again!

Peter







Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
I don't believe there's an option for disabling player controls on that media source. This is unfortunately an accessibility issue as well so they need to remain. If they make the video full screen and mouse off the controls it'll go away in a second or two

**Comment by pja12** [comment]
Thanks for checking on that, Bryan. No worries then – the sun will rise in 
the morning!

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
