### ISSUE TITLE
AA121_widget formatting

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#2126]
Hi Bryan,

This affects four widgets you've created for the course:"aa121 Arrow callout", "Design tool", "Words of Wisdom", and "Case study"

These widgets' formatting was set before the global style changes you put in last year; those changes upped sizes on most text types, making the widget formats a bit too large.  

I went back during the end of the semester to manually upgrade the items on pages the students encountered, but doing local overrides is not a wise use of time. My thinking is that if you change the widgets' default formatting, the existing ones will update to look like the manually updated ones. 
- you can see the existing ones here: https://courses.aanda.psu.edu/aa121/node/278
- and the manually updated, desired formatting is here: https://courses.aanda.psu.edu/aa121/node/297 

I'm asking for you to change the default formatting for those widgets as follows:
1. Title is now: Heading4; Title should be: Heading5+Strong
2. Body copy is now Normal; body copy should be Normal+text,smaller

Thanks once again!
~Peter

**Comment by btopro** [comment]
@bterp-web can you take a look at this / ping me at some point about how to go about looking into this.

**Comment by pja12** [comment]
Hi Bryan,



I’m a bit confused – was I cc’ed on this or are you asking me to take a look 
at something? I suspect the former but just want to be sure.

Thanks for tackling this!



Cheers,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
@pja12 this is how github works, you opened the issue and then any commentary of any kind gets sent to you. There's a notifications button in the right column on the site so you can not get responses if you'd like. I have asked Brittany to take a look, this doesn't presume when it will be completed.

**Comment by pja12** [comment]
Thanks, Bryan. I get how GitHub works; what isn’t clear in the notice I get 
is to whom it is sent or if there are others it the chain. That’s why I was 
simply making sure we were all clear.

Thanks again,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
the default widget for `aa121 Arrow callout` has been updated to reflect the desired formatting changes
