### ISSUE TITLE
Enabling modules with drush en mass - inconsistency

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2134]
Bug:
- 0.7.2

In trying to enable a module across all course sites I ran the following Drush command:
`drush @courses-all en edit_own_user_account_permission --y`

This seemed to successfully do its thing and I got the following for each site:
```
The following extensions will be enabled: edit_own_user_account_permission
Do you really want to continue? (y/n): y
edit_own_user_account_permission was enabled successfully.           [ok]
edit_own_user_account_permission defines the following permissions: edit own user account
```

Only when I then checked the course sites, the module had been switched on for some sites but not for others. I ran the command again and got the following for each course: 
```
elmsln.courses.course100          >> edit_own_user_account_permission is[ok]
already enabled.
elmsln.courses.course100          >> There were no extensions that could[ok]
be enabled.
```
But again, it hadn't been enabled. So I targeted the site specifically with:
`drush @courses.course100 en edit_own_user_account_permission --y`
And that then suggested it had worked (which it had)
 ```
$ drush @courses.course100 en edit_own_user_account_permission --y
The following extensions will be enabled: edit_own_user_account_permission
Do you really want to continue? (y/n): y
edit_own_user_account_permission was enabled successfully.           [ok]
edit_own_user_account_permission defines the following permissions: edit own user account
```

**Comment by btopro** [comment]
if u type `leafy` while logged in you can refresh the drush configuration of the user and try again. it's possible that an outdated configuration of the drush settings could cause it not to find anything. It's also possibly a caching issue but less likely

**Comment by rickhumphries** [comment]
hmm, I'm typing `leafy` from `/var/www/elmsln` but it's saying `leafy: not found`. I'm sure I've run that previously though and it worked.

**Comment by btopro** [comment]
maybe wrong account logged in, dono. `bash /var/www/elmsln/scripts/elmsln.sh` should also trigger it

**Comment by rickhumphries** [comment]
Just want to feedback that this worked. Thanks very much

**Comment by btopro** [comment]
excellent! I hoped so since I had run into it last year :)
