### ISSUE TITLE
Custom error page settings not being saved

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2135]
Bug:
When attempting to set custom 404 and 403 error pages for ELMSLN, changing the URL reference doesn't actually save to the database, despite getting a success message.

- What happens
When navigating to **/admin/config/system/site-information**, changing the URL links for 404 or 403 pages and clicking "Save", results in a success message appearing. However, the URLs just default back to the default values as below:
elmsln/error/403
elmsln/error/404

- What you expected to happen
I expected changing the custom error page URLs to save and allow us to display our own brand 404 and 403 pages rather than the ELMSLN defaults.

**Comment by btopro** [comment]
these are set globally for consistency in the shared_settings.php file
```
// redirect default error pages to some standard ones
$conf['site_403'] = 'elmsln/error/403';
$conf['site_404'] = 'elmsln/error/404';
```

if you want to override them yourself, you can change them in your local shared settings file.
`/var/www/elmsln/config/shared/drupal-7.x/settings/shared_settings.php`

**Comment by JackWillDavis** [comment]
Oh I see! Sorry, I'm still getting to grips with ELMSLN, thanks for letting me know!
