### ISSUE TITLE
Media video play icon missing

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2136]
The icon for the play button is missing from the media videos.  We should replace it with an lrn-icon.

![screen shot 2017-08-14 at 4 17 57 pm](https://user-images.githubusercontent.com/3428964/29289927-5786991c-810c-11e7-9002-c0ff18816a6a.png)

**Comment by btopro** [comment]
![2017-08-18_01-41-45](https://user-images.githubusercontent.com/329735/29445765-6ca7f33e-83b6-11e7-8217-e8a1f9f2c7ad.png)
hover:
![2017-08-18_01-41-52](https://user-images.githubusercontent.com/329735/29445768-6fd246e0-83b6-11e7-92d7-06ed99115540.png)


bandaid that works till we replace these with components. Speaking of which, @bterp-web converting this element into a component would be quite helpful (look for mediavideo display mode after submitting an external video in the media system)
