### ISSUE TITLE
Videos Not Playing in ELMS

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#2143]
Videos uploaded to a page are not playing. These videos are from Youtube that were uploaded to the system.

Here is a page: https://courses.aanda.psu.edu/dmd201/node/228

Here is sample code: [ciscode|rev=1|tool=elmsmedia|item=633|entity_type=node|render=display_mode|display_mode=mediavideo]

This is what the page looks like:
![screen shot 2017-08-17 at 1 49 29 pm](https://user-images.githubusercontent.com/13224682/29425956-0e6b40b8-8353-11e7-9807-28cb107ce719.png)

**Comment by btopro** [comment]
fixed already
