### ISSUE TITLE
Bullet and Number Lists

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#2144]
Bullet and number lists are showing up as a different size font and font type.

Here is a sample page: https://courses.aanda.psu.edu/dmd201/node/227

Here is a image: 
![screen shot 2017-08-17 at 1 53 30 pm](https://user-images.githubusercontent.com/13224682/29426077-7a5df766-8353-11e7-82fb-5655a2b99efc.png)

**Comment by btopro** [comment]
@bterp-web can you look into what global styles would be influencing this and normalize them? It should be in the main.css global

**Comment by btopro** [comment]
@jtb260 Brittany fixed this, pushing up to our server now

**Comment by btopro** [comment]
Great start, let's hit the spacing / indentation aspect too
