### ISSUE TITLE
convert mediavideo type to webcomponent

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2153]
follow up from #2136

**Comment by mmilutinovic1313** [comment]
@btopro is this why the video link wasn't working in the studio for submission upload?

**Comment by mmilutinovic1313** [comment]
![videonotloading](https://user-images.githubusercontent.com/7243665/29952445-732ae950-8e97-11e7-9865-b5bf888b2155.png)

**Comment by btopro** [comment]
Did you click video and reference a youtube video? Wirked the other day when I did it

**Comment by btopro** [comment]
And no they arn't related at this time

**Comment by btopro** [comment]
#2217 solves this for reference @mmilutinovic1313

**Comment by btopro** [comment]
#2386

**Comment by btopro** [comment]
taking further in referenced thread; closing this as duplicate
