### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#216]
It would be great to have a copy to clipboard button for remixables / other areas where it makes sense to have the user copy and paste something. example from an application I used recently
![2015-08-26_08-48-03](https://cloud.githubusercontent.com/assets/329735/9493659/4a247dd0-4bcf-11e5-944f-ff96bdaab8e1.png)

Assigning heyMP since he might know a codepen that can easily provide this

**Comment by heyMP** [comment]
http://zenorocha.github.io/clipboard.js/

**Comment by btopro** [comment]
Yes, exactly that

**Comment by zenorocha** [comment]
+1 ;)

**Comment by btopro** [comment]
@zenorocha you'll be happy to know this is now in core :) @heyMP should shoot a video once we get the icon @michael-collins made worked in

**Comment by michael-collins** [comment]
@btopro I redesigned the icon and posted to slack (twice). Reads much better, particularly when small in size.

**Comment by btopro** [comment]
saw that, make a new related issue for styling it better so @heyMP doesn't forget. I like the icon btw, also like the way Potter is currently implementing the library (you can hover on an image and click to get the shortcode to generate it in the currently visible style)
