### ISSUE TITLE
Terminology Template

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#2160]
The old terminology template is not appearing correctly. You used to be able to click it definition would appear. Right now the definition is just appearing. 

Here is an example: https://courses.aanda.psu.edu/dmd201/node/252

Image: 
![screen shot 2017-08-21 at 10 47 05 am](https://user-images.githubusercontent.com/13224682/29525229-ef481d2c-865f-11e7-8595-3fb10d564192.png)

**Comment by btopro** [comment]
Take a look at the collapse I added and let me know if that's workable. The collapse that you were using we had to drop cause of accessibility and I can make a new one but it might not be till next week. We've been having issues with our process for replacing our designed content items which we need to fix so we can make new ones like this and the button you brought up previously

**Comment by btopro** [comment]
these are working now
