### ISSUE TITLE
'More Apps / Applications' side drawer breaks scroll on smaller screen resolutions.

### ISSUE THREAD

**Issue by cgldevel** [elmsln/elmsln#2161]
Bug:
- On full screen, everything works great.
<img width="1440" alt="full screen - more apps applications" src="https://user-images.githubusercontent.com/11019355/29526974-5c8d04e2-8665-11e7-9772-be663f491da7.png">

However, on smaller resolutions some links become hidden below view and scroll does not scroll 'far enough' to access them.
<img width="1436" alt="small screen - more apps applications" src="https://user-images.githubusercontent.com/11019355/29527066-95f26d76-8665-11e7-9ba5-830d65e9f79b.png">

**Comment by btopro** [comment]
good catch

**Comment by btopro** [comment]
fixed
