### ISSUE TITLE
Alternative Formats Visibility for Authenticated Users

### ISSUE THREAD

**Issue by cgldevel** [elmsln/elmsln#2162]
Feature request:
- We're not implementing sections this year and so our students will not receive the 'Student' role that they typically would.  Consequently, we've had some students request access to the 'Alternative Formats' (Print Page / Print PDF) options that were unable to view them.  Could we grant access to those features on an 'Authenticated User' level as well so our students can view them without needing a 'Student' role?

<img width="1432" alt="missing print options" src="https://user-images.githubusercontent.com/11019355/29531054-d49378ea-8674-11e7-9c68-223903332675.png">

<img width="1430" alt="full print options" src="https://user-images.githubusercontent.com/11019355/29531085-f5466b92-8674-11e7-8862-bf5ee88317b0.png">

**Comment by btopro** [comment]
those are normal Drupal permissions for print and so on I believe

**Comment by cgldevel** [comment]
You are correct sir, I'm gonna close this issue now - thank you!
