### ISSUE TITLE
Kanban App CSS updates

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2166]
The following will make the lists slightly more attractive and will prevent some overlap of buttons and titles. I do not understand how elements are placed on this page, as it looks like everything is placed with a translate3d property instead of floats. If you explain to me how the card height is calculated, perhaps I can help. Right now, the cards are overlapping due to this calculation being incorrect.

////////////////////////////////////////
Remove the following classes from these elements where indicated.

<paper-card class="project-card   /---remove---> grey lighten-3 <---remove---/   style-scope lrnapp-studio-kanban x-scope paper-card-0" elevation="2" id="project-261" aria-label="">

<div class="status-indicator   /---remove---> grey lighten-4 <---remove---/   style-scope lrnapp-studio-kanban">

////////////////////////////////////////

.lrnapp-studio-kanban-0 .assignment-row.lrnapp-studio-kanban .assignment-row-button.active.lrnapp-studio-kanban {
    background-color: #efefef;
}

.lrnapp-studio-kanban-0 {
    background-color: #efefef;
}

.lrnapp-studio-kanban-0 .grey.lighten-3.lrnapp-studio-kanban {
    background-color: #fff !important;
}

.lrnapp-studio-kanban-0 .project-card.lrnapp-studio-kanban {
    border-radius: 6px;
}

.lrnapp-studio-kanban-0 .assignment-row.lrnapp-studio-kanban {
    border: 0;
    background-color: #fff;
}

.lrnapp-studio-kanban-0 .status-indicator.lrnapp-studio-kanban {
    border-right: 0;
}

.lrnapp-studio-kanban-0 .project-operations.lrnapp-studio-kanban {
    position: inherit;
    padding: 0 0.25rem;
}

.lrnapp-studio-kanban-0 .projects-container.lrnapp-studio-kanban {
    height: 100%;
}

**Comment by btopro** [comment]
Floats are so 2008

**Comment by michael-collins** [comment]
For reference, this is what the css does:

**Before:**

<img width="1413" alt="screen shot 2017-08-23 at 12 47 06 pm" src="https://user-images.githubusercontent.com/1085304/29627786-3f77eb0e-8801-11e7-997f-503a7c593e3d.png">

**After:**

<img width="1399" alt="screen shot 2017-08-23 at 12 44 18 pm" src="https://user-images.githubusercontent.com/1085304/29627673-d8ff845e-8800-11e7-99d7-72d3e0dada4d.png">

**Comment by btopro** [comment]
looking at it, not my system, I just work here
