### ISSUE TITLE
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'filename' at row 1

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2175]
Not sure what we've been doing wrong, it is a fresh install. Getting this, trying to access **people.host.tld /admin** area

`PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'filename' at row 1: UPDATE {system} SET info=:db_update_placeholder_0, filename=:db_update_placeholder_1 WHERE (filename = :db_condition_placeholder_0) ; Array ( [:db_update_placeholder_0] => a:17:{s:4:"name";s:5:"Stark";s:11:"description";s:208:"This theme demonstrates Drupal's default HTML markup and CSS styles. To learn how to build your own theme and override Drupal's default code, see the <a href="http://drupal.org/theme-guide">Theming Guide</a>.";s:7:"package";s:4:"Core";s:7:"version";s:4:"7.54";s:4:"core";s:3:"7.x";s:11:"stylesheets";a:1:{s:3:"all";a:1:{s:10:"layout.css";s:296:"themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/stark/layout.css";}}s:7:"project";s:6:"drupal";s:9:"datestamp";s:10:"1485986921";s:6:"engine";s:11:"phptemplate";s:7:"regions";a:9:{s:13:"sidebar_first";s:12:"Left sidebar";s:14:"sidebar_second";s:13:"Right sidebar";s:7:"content";s:7:"Content";s:6:"header";s:6:"Header";s:6:"footer";s:6:"Footer";s:11:"highlighted";s:11:"Highlighted";s:4:"help";s:4:"Help";s:8:"page_top";s:8:"Page top";s:11:"page_bottom";s:11:"Page bottom";}s:8:"features";a:9:{i:0;s:4:"logo";i:1;s:7:"favicon";i:2;s:4:"name";i:3;s:6:"slogan";i:4;s:17:"node_user_picture";i:5;s:20:"comment_user_picture";i:6;s:25:"comment_user_verification";i:7;s:9:"main_menu";i:8;s:14:"secondary_menu";}s:10:"screenshot";s:300:"themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/stark/screenshot.png";s:3:"php";s:5:"5.2.4";s:7:"scripts";a:0:{}s:5:"mtime";i:1502978128;s:14:"regions_hidden";a:2:{i:0;s:8:"page_top";i:1;s:11:"page_bottom";}s:28:"overlay_supplemental_regions";a:1:{i:0;s:11:"page_bottom";}} [:db_update_placeholder_1] => themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/themes/stark/stark.info [:db_condition_placeholder_0] => themes/stark/stark.info ) in system_update_files_database() (line 2274 of /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module).`

Please help!

**Comment by btopro** [comment]
What are the server specs for this setup and which version of ELMSLN is this running? (master or 0.9.x branch). I haven't experienced this. Are you able to run `drush @people cc all` against the site from terminal? Speaking of which, drush has lots of targets automatically set to do operations like this

**Comment by yurg** [comment]
Believe it is the latest ELMSLN on  fresh Ubuntu 16.04 as suggested in #2137;  we've discussed a possibility of using https://www.elmsln.org/install-guide  script on a fresh distro, which I did 3 days ago. 
drush cc & drush rr both failed for the same reason: 

`root@ticket-fruit:~# drush @stacks.people cc all
PDOException: SQLSTATE[22001]: String data, right truncated: 1406    [error]
Data too long for column 'filename' at row 1 in
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/database.inc:2227
Stack trace:
#0
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/database.inc(2227                                                                   ):
PDOStatement->execute(Array)
#1
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/database.inc(697)                                                                   :
DatabaseStatementBase->execute(Array, Array)
#2
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/query.inc(1212):
DatabaseConnection->query('UPDATE {system}...', Array, Array)
#3
/var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module(2274):
UpdateQuery->execute()
#4
/var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module(2645):
system_update_files_database(Array, 'theme')
#5
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/common.inc(7671):
system_rebuild_theme_data()
#6
/root/.config/composer/vendor/drush/drush/commands/core/drupal/cache.inc(99):
drupal_flush_all_caches()
#7 /root/.config/composer/vendor/drush/drush/includes/drush.inc(722):
drush_cache_clear_both()
#8 /root/.config/composer/vendor/drush/drush/includes/drush.inc(709):
drush_call_user_func_array('drush_cache_cle...', Array)
#9
/root/.config/composer/vendor/drush/drush/commands/core/cache.drush.inc(144):
drush_op('drush_cache_cle...')
#10
/root/.config/composer/vendor/drush/drush/includes/command.inc(361):
drush_cache_command_clear('all')
#11
/root/.config/composer/vendor/drush/drush/includes/command.inc(212):
_drush_invoke_hooks(Array, Array)
#12
/root/.config/composer/vendor/drush/drush/includes/command.inc(180):
drush_command('all')
#13
/root/.config/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64):
drush_dispatch(Array)
#14 /root/.config/composer/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 /root/.config/composer/vendor/drush/drush/drush.php(11):
drush_main()
#16 {main}



root@ticket-fruit:~# drush @people rr
The registry has been rebuilt via registry_rebuild (A).                                                                                 [success]
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'filename' at row 1 in                       [error]
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/database.inc:2227
Stack trace:
#0 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/database.inc(697): DatabaseStatementBase->execute(Array, Array)
#2 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/database/query.inc(1212): DatabaseConnection->query('UPDATE {system}...',
Array, Array)
#3 /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module(2274): UpdateQuery->execute()
#4 /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module(2645): system_update_files_database(Array, 'theme')
#5 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/common.inc(7671): system_rebuild_theme_data()
#6 /root/.drush/registry_rebuild/registry_rebuild.drush.inc(276): drupal_flush_all_caches()
#7 /root/.drush/registry_rebuild/registry_rebuild.drush.inc(183): drush_registry_rebuild_cc_all()
#8 /root/.config/composer/vendor/drush/drush/includes/command.inc(361): drush_registry_rebuild()
#9 /root/.config/composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
#10 /root/.config/composer/vendor/drush/drush/includes/command.inc(180): drush_command()
#11 /root/.config/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
#12 /root/.config/composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /root/.config/composer/vendor/drush/drush/drush.php(11): drush_main()
#14 {main}
root@ticket-fruit:~#
`

**Comment by btopro** [comment]
what about `drush @people si cpr --y`

**Comment by yurg** [comment]
`root@ticket-fruit:~# drush @people si cpr --y
You are about to DROP all tables in your 'people_ml' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                            [ok]
PHP Fatal error:  Uncaught Error: Call to undefined function db_query() in /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc:359
Stack trace:
#0 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc(340): DrupalDatabaseCache->getMultiple(Array)
#1 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc(57): DrupalDatabaseCache->get('module_implemen...')
#2 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/module.inc(754): cache_get('module_implemen...', 'cache_bootstrap')
#3 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/module.inc(954): module_implements('system_theme_in...')
#4 /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#5 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/theme.inc(798): _system_rebuild_theme_data()
#6 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/theme.maintenance.inc(57): list_themes()
#7 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/bootstrap.inc(2867): _drupal_maint in /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc on line 359
Drush command terminated abnormally due to an unrecoverable error.                                                                      [error]
Error: Uncaught Error: Call to undefined function db_query() in /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc:359
Stack trace:
#0 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc(340): DrupalDatabaseCache->getMultiple(Array)
#1 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc(57): DrupalDatabaseCache->get('module_implemen...')
#2 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/module.inc(754): cache_get('module_implemen...', 'cache_bootstrap')
#3 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/module.inc(954): module_implements('system_theme_in...')
#4 /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#5 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/theme.inc(798): _system_rebuild_theme_data()
#6 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/theme.maintenance.inc(57): list_themes()
#7 /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/bootstrap.inc(2867): _drupal_maint in
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc, line 359
`

**Comment by btopro** [comment]
do any other sites work cause this still sounds like it's not installing. Have you tried spinning up vagrant? We run Ubuntu 16 all the time and aren't experiencing this. Is it behind a firewall or in a region that might not be able to hit certain repos or anything odd at the server layer?

**Comment by yurg** [comment]
That's I've been trying to figure out since first installation attempts. Thank you for help, will post here my findings, if any, if/when this is figured out.

**Comment by btopro** [comment]
what are the server specs? Maybe mysql / maria didn't install correctly or something. Is this after installing on a fresh box?

**Comment by yurg** [comment]
It's a fresh Ubuntu 16.04 with 4G RAM, the same story continues from #2137, still struggling.

**Comment by btopro** [comment]
continued in #2184 since it's the same issue
