### ISSUE TITLE
Styles from Content Templates in WYSIWYG editor not displaying correctly 

### ISSUE THREAD

**Issue by kmiffitt** [elmsln/elmsln#2177]
Items from content templates are not displaying correctly, including regular panel, callout panel (reported in AA121), and vocab items (reported in DMD 201). Styles are used in multiple courses. 

![template-callout01](https://user-images.githubusercontent.com/17576440/29677446-1dd2b8e4-88c9-11e7-8910-df7e4da3e16d.jpg)
![wysiwyg-callout02](https://user-images.githubusercontent.com/17576440/29677447-1eed49c4-88c9-11e7-9992-61705b050d8a.jpg)

**Comment by btopro** [comment]
Thanks for the screenshots; regular, callout and vocab are now fixed. That should be all of them but if you notice any others let me know.

**Comment by btopro** [comment]
This is fixed in the course too (DMD 201 that is)
