### ISSUE TITLE
Math editor (WIRIS) for CKeditor

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2182]
Feature request:
Just came across this so thought I'd share. I've switched on the MathJax feature on a couple of courses and it works pretty well, although this editor seems like it would be an enhancement
http://www.wiris.com/en/editor
http://www.wiris.com/solutions/ckeditor

Came across is while reading some comments on the H5P fill in the blank content type https://h5p.org/comment/9805#comment-9805

**Comment by btopro** [comment]
@heyMP has thoughts about the lrn-math tag

**Comment by btopro** [comment]
seems like a pretty complicated solution for this but just from assessing the fact that it requires PHP / a backend to operate

**Comment by btopro** [comment]
lrn-math tag + HAX at some point will make this solution seem a bit crazy from a setup perspective. As we're scaling back on mathjax token methodology (in favor of it being handled through webcomponents) let's focus efforts there
