### ISSUE TITLE
Studio Add/Edit Project: section field not populating

### ISSUE THREAD

**Issue by kmiffitt** [elmsln/elmsln#2183]
There's a field in the add/edit project form that requires that it be linked to a section, but no section options populate, so therefore changes can't be saved. 
![studio-add-project-error](https://user-images.githubusercontent.com/17576440/29727484-13376ef0-89a2-11e7-80b6-185bd9f2837b.png)

**Comment by btopro** [comment]
tweaked some permissions that are currently too strict for staff / instructors, shows up now. this form is a bandaid till we replace it w/ a well designed version (coming up soon in the list of things to add). At that time we'll have total control over the display of it so less things like this can happen :)
