### ISSUE TITLE
MySQL root credentials? 

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2185]
Since MySQL has been installed by "hands-free" method (and it seems it's running with --skip-grant-tables option) how does one get root credentials? Have tried to search in docs and issues, no luck, please help!

**Comment by btopro** [comment]
pure root is lost intentionally. However, an account that's effectively root without being root is created from the root user during setup. This account is used to request new database users which are then set for each database created.

These creds if you need them for connecting can be found in `/var/www/elmsln/config/scripts/drush-create-site/configpwd.cfg`

If you could find a good place for this info in the docs please PR it in there too.
