### ISSUE TITLE
Project structure: what each subdomain actually does?

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2186]
Sorry if it was asked before, can't find some information for puzzle solve. ELMSLN provides several subdomains (Authorities and Services, according to https://elmsln.readthedocs.io/en/latest/systems/service-vs-auth/ )  : 

@elmsln
@elmsln.comply.ml
@elmsln.grades.ml
@elmsln.inbox.ml
@elmsln.interact.ml
@elmsln.lor.ml
@elmsln.lq.ml
@elmsln.media.ml
@elmsln.online.ml
@elmsln.people.ml
@network
@network.ml
@none
@service
@service.comply-all
@service.grades-all
@service.inbox-all
@service.interact-all
@service.lor-all
@service.lq-all
@service.media-all
@service.online-all
@service.people-all
@stacks
@stacks.comply
@stacks.grades
@stacks.inbox
@stacks.interact
@stacks.lor
@stacks.lq
@stacks.media
@stacks.online
@stacks.people

There are diagrams here https://cloud.githubusercontent.com/assets/329735/14988658/ef2316a2-1122-11e6-8a91-eb4815f46db9.jpg and here https://raw.githubusercontent.com/elmsln/elmsln/master/docs/diagrams/ELMSLN-system-connections.jpg whicn, I believe, explains which each part of system is doing. 
Yet, any chance there is a documentation page which explains the architecture in a simple words, like:

_comply.domain.tld: serves for "whatever purpose it is", you can delete / uninstall it  
online.domain.tld: provides login capabilities, required for elmsln to work  
people. : keeps user data, required
etc..._

**Comment by btopro** [comment]
Description of network tools in the docs has a small blurb about each of them, starting here https://elmsln.readthedocs.io/en/latest/systems/authority/media/

**Comment by btopro** [comment]
if this stuff can be made more clear PLEASE issue a PR or suggest how. We really want to improve the developer UX. Also the doc site is driven by https://github.com/elmsln/elmsln/tree/master/docs

**Comment by yurg** [comment]
thank you for answer; didn't think any of my questions deserve a PR. Let me please get this thing running, promise, I'll do as much PRs as I can.
