### ISSUE TITLE
Leafy: "please select a branch you want to update"? 

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2187]
I'm really sorry, but what is "a branch" here? Assuming it is one of a subdomains, I've typed "@compy" and have got  "Are you sure you want to update the entire network" message. Please advice.

**Comment by btopro** [comment]
this is code branch like master, 0.9.x, etc. This allows you to run automated updates from single commands. If you can think of a better way to describe that we'll update the naming

**Comment by btopro** [comment]
improved commandline statement
