### ISSUE TITLE
Studio assignment draft/publish viewing

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2189]
It appears that "draft" submissions are immediately showing up on the Open Studio.

**Comment by btopro** [comment]
OMG WHAT!? How can that be?!

**Comment by btopro** [comment]
At 8:49pm on a Sunday!? Crap @heyMP did you put in a failsafe for Sunday submissions!??!?!!!!!!

**Comment by btopro** [comment]
@heyMP please respond, we have sunday submissions by @michael-collins that are showing up where they are supposed to but too early. Do you copy? over.

**Comment by btopro** [comment]
@michael-collins yeah I wondered about that. I'll give 'er a look tomorrow. Now that semester rush has died down it should be 100% studio work instead of 60% :p

**Comment by btopro** [comment]
fixed in the next code push :)
