### ISSUE TITLE
support updating user data after the fact

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2194]
#1717 could also solve this because we previously were only setting this stuff on setup. Now password, mail, and other sis data fields can be updated on future syncs / account creation.

**Comment by rickhumphries** [comment]
Would this have implications for the pending pull request here... https://github.com/elmsln/elmsln/pull/2118/commits/3dcf3d3bba8d24adc67b179e07ed7d112c1cbd3d

**Comment by btopro** [comment]
nah this is downstream of that, this is what that hands the data over to to actually save a person. That PR helps ensure that it doesn't timeout when having to do 1000s of those handoffs. This would be like your XML files pulling into CIS say "Jeff Bezos" for username "coolstuff" then switches to "Jeffery B" for username "coolstuff". Previously this wouldn't have updated
