### ISSUE TITLE
Description of Calendar and Inbox functionality

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#220]
@btopro Main question to resolve: Should the Calendar be separate from the Inbox system? Or instead should we add time and date functionality to the Outline Designer, with an additional lightweight interface within the Inbox view for creating specific kinds of Calendar items (which are also outline nodes)? I kind of like the latter idea at this point.

**Inbox:**
- Bundled email notification that you received a message or notification (Like slack, twitter, etc.) 
- Sending Messages
  - messaging peer to peer
  - group messaging
  - messaging student to instructor(s)/TAs
  - messaging instructor/TA to student(s)
- Notifications
  - ELMSLN system or interface updates
  - Discuss
    - Discussion thread response
  - Assignment/Grading
    - Upcoming assignment deadline (alert is set when creating the assignment)
    - Grade and feedback is ready
    - Suggested reading (helps to set the pace of the course)
  - Blog
    - Comment posted to your blog post

**Date and Time (Associating within different interfaces):**
- Outline designer Interface [Auto adds things with time/date info to calendar view]
  - Timed node reveal (hide/unhide)
  - Send a notification to look at the node (for a reading or something else)
  - Create an event (lecture, live demo, visiting lecturer, etc.)
  - Create assignment (exercise, reading, project, etc.)
  - Create assessment (quiz, test, other) due date
- Calendar Interface [If you create a new node, it's added to the book outline in a hidden node section in outline designer. You can move them into the book outline if you want them to be visible on book pages]
  - Add an event (lecture, live demo, visiting lecturer, etc.)
  - Create Assignment (exercise, reading, project, etc.)
  - Create assessment (quiz, test, other) due date
- Cross-tool Embedding Interface [short code date/time options?]
  - Assignment
    - Dropbox submission deadline notification
    - In-line Group Discussion due date

**Comment by btopro** [comment]
I hope you have more functional requirements then this as the person requesting both of these capabilities ;)

**Comment by michael-collins** [comment]
Yes, will be filling out the list.

**Comment by btopro** [comment]
I added you a special label for lists like this

**Comment by michael-collins** [comment]
@btopro I've updated the list, what are your thoughts?

**Comment by btopro** [comment]
This speaks to 1 system. I think the Outline designer could be 1-way of driving things, though having the properties directly associated to nodes in the course outline would imply that you MUST have online, paced content. If you just wanted a learning environment, especially w/ more experiential learning, it might make sense to have your course actually be blog centric, w/ the studio for more high quality work and discussion boards for non-posting related conversation.

In this hyopothetical, you no longer have an outline of sorts as the course is entirely "calendar" / time driven. In this situation, it becomes clear that Outline Designer needs to be able to have dates associated to it but not actually tied directly to it.

I think if we think of inbox as a notification / activity stream center and notifications (which can have dates) formulate an agenda / "calendar". I think the words calendar / message are tripping up some of the conception of what this actually provides. This is effectively your dashboard to all courses, it is an authority, and it works the same for everyone (at some level). We can have variability in displays and organization of the dashboard / inbox but not fundamental differences (your not adding a new field for example for just course X).

@heyMP thoughts on all this

**Comment by btopro** [comment]
#76

**Comment by btopro** [comment]
Another thought from a conceptual level:

CIS -- System, ID, IPS, Instrctor instructional console to build new and set things existing in motion. The gears of the university if you will.
Inbox -- Student / Instructor (day to day) communication, messaging and "what do I do next" situational awareness hub.
CPR #165 -- Ultra lightweight CRM kind of thing. Just knows stuff about who's doing what, where. Eventually all systems ask this for the roster and it's the bridge to legacy / central data sources for rosters / user enrollments

**Comment by michael-collins** [comment]
Inbox will be a place to see:

1. Individual or course-wide Messages
2. Alerts and Notifications (included upcoming assignments)
3. Course-wide discussions (Activity Feed type feature for course)

These items need to go somewhere, but the Inbox connotaion doesn't make sense... Thoughts @btopro ?
1. Currently enrolled courses
2. Grades
3. Course Completion Progress

**Comment by btopro** [comment]
there's an address / placeholder called grades; currently enrolled is info people would have

**Comment by btopro** [comment]
What if we used xAPI for this? Think about it...

**Comment by btopro** [comment]
this has been put in the docs as to what / when these happen and are priority. closing for now
