### ISSUE TITLE
Z-index problem for image submission in studio

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2205]
This prevents the use of drag and drop as well as browse:

<img width="1408" alt="screen shot 2017-08-29 at 8 51 36 pm" src="https://user-images.githubusercontent.com/1085304/29854625-028ae944-8cfc-11e7-9599-e879e4c66211.png">

**Comment by btopro** [comment]
Mind telling me how you were able to make that happen?

**Comment by michael-collins** [comment]
Here is a video: https://www.dropbox.com/s/tgulr7s45r6m1cw/image-upload.mov?dl=0
