### ISSUE TITLE
Align style guide classes with FA available colors

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#221]
The orange heading is impacting the color where it says required. Can that stay red? 
<img width="1068" alt="screen shot 2015-08-28 at 6 34 49 am" src="https://cloud.githubusercontent.com/assets/13224682/9553270/e0e15c30-4d8b-11e5-839b-f8a8fefcd055.png">

**Comment by btopro** [comment]
As part of the next steps in making the content kick butt we should visit what kinds of things can be modified color wise and get classes that align with that

**Comment by heyMP** [comment]
Yeah absolutely.

**Comment by btopro** [comment]
duplicate of #206
