### ISSUE TITLE
Math equations in H5P editor

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2219]
The H5P editor doesn't have built in support for adding in equations. This is frustrating in particular when you want to write a 'fill in the blank's question where the answer is a fraction (using a forward slash in H5P actually gives an alternate answer)

The NDLA (maintainers of H5P) have kindly shared with me their custom Drupal 6 module for adding this functionality in, so this could potentially be updated to Drupal 7 and adopted

https://bitbucket.org/ndla/ndla.no/src/2282db5876140010eccfad1d12d35a35020fda54/sites/all/modules/ndla_h5p/?at=master

#2182 relates as it uses the same math editor as a plugin

**Comment by btopro** [comment]
I think some of this already works from whats in the elmsmedia_h5p module in

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/blob/0.9.x/core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmsmedia_h5p.module#L67

**Comment by btopro** [comment]
I believe this is taken into account and was fixed recently; allowing drupal to take the output of h5p and then filter it via input formats
