### ISSUE TITLE
Terms Template

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#222]
Can we make it so the second  column is editable - where the learner can write and save the definition. 

<img width="1034" alt="screen shot 2015-08-27 at 10 35 42 pm" src="https://cloud.githubusercontent.com/assets/13224682/9553296/0897bda0-4d8c-11e5-907e-1b7ad37c6197.png">

**Comment by btopro** [comment]
EMS has had things like this as requests before, not sure if they'd be able to help on this part. We've had this before requested, kinda difficult to pull off w.o. a more comprehensive solution for in-page workbooks.

**Comment by btopro** [comment]
@jtb260 so this would be an assignment kind of thing? It's the storage aspect that gets a little tricky / would involve a lot more work

**Comment by btopro** [comment]
Can't make this column editable in this way. Maybe http://h5p.org is worth a look
