### ISSUE TITLE
Course Setup stuck on 'Waiting for Server'

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2220]
- v0.7.2

Not experienced this before. I've just set up a new course but the Courses service is stuck on 'Waiting for Server'
![image](https://user-images.githubusercontent.com/4973810/30021839-9e574f12-9160-11e7-8530-b18999dca3d0.png)
I can't see any errors or anything in NewRelic though

**Comment by rickhumphries** [comment]
Tried to delete the CIS service instance and add it again. However same thing happened. Saw these in the logs...

```
Location | https://online.buttercupstraining.co.uk/node/add/service-instance?field_services=1&field_course=1699&destination=node/1699/service-instances
-- | --
https://online.buttercupstraining.co.uk/node/add/service-instance?field_services=1&field_course=1699&destination=node/1699/service-instances
Warning: fopen(/var/www/elmsln/config/jobs/safeguardi.courses): failed to open stream: File exists in _cis_helper_add_service_instance() (line 948 of /var/www/elmsln/core/dslmcode/profiles/cis-7.x-2.x/modules/custom/cis_helper/cis_helper.module).
```

```
Location | https://online.buttercupstraining.co.uk/node/add/service-instance?field_services=1&field_course=1699&destination=node/1699/service-instances
-- | --
https://online.buttercupstraining.co.uk/node/add/service-instance?field_services=1&field_course=1699&destination=node/1699/service-instances
Warning: fwrite() expects parameter 1 to be resource, boolean given in _cis_helper_add_service_instance() (line 949 of /var/www/elmsln/core/dslmcode/profiles/cis-7.x-2.x/modules/custom/cis_helper/cis_helper.module).
```

```
Location | https://online.buttercupstraining.co.uk/node/add/service-instance?field_services=1&field_course=1699&destination=node/1699/service-instances
-- | --
https://online.buttercupstraining.co.uk/node/add/service-instance?field_services=1&field_course=1699&destination=node/1699/service-instances
Warning: fclose() expects parameter 1 to be resource, boolean given in _cis_helper_add_service_instance() (line 950 of /var/www/elmsln/core/dslmcode/profiles/cis-7.x-2.x/modules/custom/cis_helper/cis_helper.module).
```

**Comment by rickhumphries** [comment]
Tried again with a new course name and didn't get the errors I've given above. However, the same thing did happen again. The only thing I can see in this case is the 'Login attempt failed for SERVICE_MOOC_BC.':
![image](https://user-images.githubusercontent.com/4973810/30025776-f079b990-9171-11e7-8bfd-ae53cdadff43.png)

**Comment by btopro** [comment]
which log is that a screenshot of?

**Comment by btopro** [comment]
if manually deleting a failed build (not saying why that happened cause I dono) then you need to remove its associated job file in `/var/www/elmsln/config/jobs/COURSEAME.TOOLNAME`

**Comment by btopro** [comment]
not sure if messing w/ crontab has happened related to other issues but crontab is what resolves this so that's my 1st guess potentially

**Comment by rickhumphries** [comment]
Screenshot of `/admin/reports/dblog`

**Comment by btopro** [comment]
in what site tho

**Comment by rickhumphries** [comment]
Oh sorry - the CIS

**Comment by btopro** [comment]
hmm.. my guess is this is an older issue since resolved on the access denied part given that MOOC isn't supposed to (nor can it) call home to CIS on this account and has to use special account credentials only available under the hood

**Comment by btopro** [comment]
have ur dev look in the logs to see if the site isn't building for some specific reason like a module is missing or a lock file needs removed. log into the server, go in as root and try to ry and run this:
Log file to look for is: `/var/www/elmsln/config/logs/drush-create-site.log`
Command to try and run that cron runs (might just give u more feedback): `/usr/local/bin/drush-create-site/drush-create-site`

if it got stuck at one point this should help clear that up: `sudo rm /tmp/drush-lock`

**Comment by btopro** [comment]
generally what should show up when doing a build. calls to itself with its own backend call account after saying its making it
![2017-09-04_10-14-42](https://user-images.githubusercontent.com/329735/30030138-e6ef0582-9159-11e7-9cfa-850f91b93f03.png)

**Comment by rickhumphries** [comment]
That seemed to do something. I've had a look at the log (dev is on holiday!) and doesn't look like there's anything strange in `/var/www/elmsln/config/logs/drush-create-site.log` 
Ran `/usr/local/bin/drush-create-site/drush-create-site` command and then `sudo rm /tmp/drush-lock` and that's allowed both sites to be created now (not sure which one did it though!)

The first course I set up (the one in the initial screenshot) now has 'Almost there...' for service status - I'm guessing because I didn't delete the job file(?). But the site is fine. 
The second course I set up has 'Service Available' and all looks good on that front too. 

So now I want to delete the first one. I'm guessing the best thing to do is:

- `leafy 11` - remove the site
- Delete the service instance from CIS
- Delete the Course from CIS

Is there anything else I should do?

**Comment by btopro** [comment]
"almost there" is typically built fine. It has to do w/ cron key not shipping back. Deleting it tho you layed it out

**Comment by btopro** [comment]
also want to delete the file in the jobs directory so u can rebuild it (if it didnt delete it from there)

**Comment by rickhumphries** [comment]
OK - thanks for this. I've come across an issue when deleting the site from the command line but will create a new issue for that.
