### ISSUE TITLE
Styling of elmsln-add-menu-items cropped

### ISSUE THREAD

**Issue by jgonyea** [elmsln/elmsln#2221]
v0.9.x, commit 948ea6a8b97a1753b5ee9d1edb6929f22f314548

**What happens**
Display of elmsln-add-menu-items appears to be cut off in FF and Chrome (looks worse in FF, see attached).

**Machine setup**
Win10x64, 1680x1050 screen resolution
Vagrant 1.9.8, Virtualbox 5.1.26
Chrome Version: 60.0.3112.113 (64-bit)
FF Version: 55.0.3 (32-bit)

**What you expected to happen**
Display of menu to not appear cropped

**Steps to reproduce**
1. Checked out elmsln git repo
2. "vagrant up"
3. Logged into http://online.elmsln.local/ as admin:admin
4. Pressed the button to add a new course
5. Menu style appears broken

**Screenshots**
![chromemenubug](https://user-images.githubusercontent.com/1057441/30028108-beb3c0ce-9151-11e7-8860-ab27dee3cfa7.PNG)
![firefoxmenubug](https://user-images.githubusercontent.com/1057441/30028107-beb0fb46-9151-11e7-9a64-b2d2a26ba42c.PNG)

**Comment by btopro** [comment]
this happens on all of them, some worse then others.

**Comment by btopro** [comment]
fixed spacing; also fixed the loss of icons that happened a few months ago.

**Comment by btopro** [comment]
![2017-09-05_11-11-03](https://user-images.githubusercontent.com/329735/30068184-f5eee242-922a-11e7-9e8d-d5b853905e88.png)
