### ISSUE TITLE
Section not Syncing to Course Site

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2224]
Bug:
- v0.7.1

The course created as part of the issue raised in #2220 won't sync with the CIS in order to populate with the sections that have been created.

I've run both the CIS cron, the course cron, and made sure the section has been set up with proper access durations etc.

**Comment by rickhumphries** [comment]
Yeh - I just spun up a new course and this one built correctly but again won't sync. I feel like it's to do with some of these features being overidden by default:
![image](https://user-images.githubusercontent.com/4973810/30055965-fab4249c-9228-11e7-8a8b-8848bd5401ff.png)
However, when I try to revert the components it won't let me. They just stay overidden

**Comment by rickhumphries** [comment]
@btopro Is there any way of manually correcting this for one course as a quick fix?

**Comment by btopro** [comment]
try `drush @whatever elmsln-service-pwd` to make sure those line up. that enables things to talk to it. Also might want to go through the job file and apply the drush commands to the site; not sure why it wouldn't have built.

**Comment by rickhumphries** [comment]
Thanks Bryan. I've got it in there now for this course.

**Comment by rickhumphries** [comment]
Came across this issue on another course that already had sections set up previously. Added a new section and it isn't syncing across.

Tried `drush @courses.[coursename] elmsln-service-pwd` but this shot back an error

```
Error message
E_ERROR: Call to undefined function drupal_sanitize_options()

Stack trace
in sqlsync_drush_command called at /root/.composer/vendor/drush/drush/commands/sql/sqlsync.drush.inc (90)
in sqlsync_drush_command called at /usr/share/php/drush/includes/command.inc (975)
in drush_get_commands called at /usr/share/php/drush/includes/command.inc (1175)
in drush_parse_command called at /usr/share/php/drush/includes/drush.inc (1115)
in drush_preflight_command_dispatch called at /usr/share/php/drush/drush.php (59)
in drush_main called at /usr/share/php/drush/drush.php (16)
```

**Comment by btopro** [comment]
sounds like there's a space that isn't there? that function exists in drupal sites that bootstrap

**Comment by btopro** [comment]
does the section show up but not sync its users instantly (this happens currently in some scenarios until a full job is kicked off)

**Comment by rickhumphries** [comment]
hmm - the space is definitely there. No, the section just doesn't show up at all in the course site. I might wait until a cron on the CIS runs tonight though and check tomorrow

**Comment by btopro** [comment]
yea give that a shot; are you in prod w/ the 0.8.1 stuff or still in testing?

**Comment by rickhumphries** [comment]
Finished testing but OB won't update us to v0.8.1 cause we have massive network slowdowns still and it takes 3 hours for the update process to run so they're worried it'll all go tits up if something crashes whilst updating. Been investigating it for weeks but still waiting for a resolution unfortunately

**Comment by rickhumphries** [comment]
Still not showing unfortunately

**Comment by rickhumphries** [comment]
Sometimes a get a 'toast' message when saving a section which says - 'changes are being synchronized to the network' or something along those lines but I'm not seeing that message

**Comment by rickhumphries** [comment]
@btopro when you said it sounds like the space isn't there - did you mean the course site itself? Still unsure how to force this through. Is there anything else I can check?

**Comment by btopro** [comment]
is there actually a course space there it's just not syncing?

**Comment by rickhumphries** [comment]
yeh there's a course space. There's also about 12 sections that I'd previously set up for this course and it's been going for a few months. Got asked to add another section, so did and it won't sync
