### ISSUE TITLE
Look at PWA module

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2229]
https://www.drupal.org/project/pwa

**Comment by btopro** [comment]
And apparently I've made commits to this..

**Comment by btopro** [comment]
@cgldevel can you test this module when you get some time (low priority for sure) and see what it does? I don't know that we'd actually use this but I'd be curious to see what it provides and we might reverse engineer some of the same functionality in. Ultimately this is supposed to create options which allow drupal site's to work more like Apps on phones and work offline. The offline aspect being particularly interesting from a scalability standpoint in mooc/content which could function offline.

**Comment by cgldevel** [comment]
@btopro I will def check it out, sounds pretty cool!

**Comment by btopro** [comment]
cool module but our Polymer Apps do way more then this would have. #2414 makes it feel like this without the downsides
