### ISSUE TITLE
Assignment centric doesn't quite filter properly

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2230]
I'm attempting to filter just to the assignment within the project. Instead, this is showing all of the assignments for the project.

In the image, you can see Interview is selected at the top right, yet Journey Mapping is the first visible item.

**Comment by btopro** [comment]
if you select a different assignment and then it should reset. That or pick an author and then pick an assignment and then then unselect an author. I'm not suggesting it's the correct thing just saying that's a fix for it that I've seen for this issue. This is the only real issue we've had with Polymer is that this is a "restamping" issue; in that the data in javascript is most likely saying to only show the thing you selected but then Polymer doesn't correctly get told to refresh it's contents to update the paint on the screen (so to speak).

**Comment by btopro** [comment]
I might need @heyMP help on this one as these can be tricky to track down

**Comment by btopro** [comment]
This happens when you start reviewing a project and then switch to assignment. It needs to correctly trigger the data bind update

**Comment by btopro** [comment]
yeah that's what it was. still has some issues on the edges but better then it was
