### ISSUE TITLE
Feature request: Batch downloading studio assignments

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2236]
It is way faster to grade if assignments are on my local system. The one really great workflow advantage of using Box was that I could download everything. Could we add something like this, perhaps on on the table view page?

Since filtering works really well on that the table view in studio, we could use the results of the table view filtering to make a manifest for assignment downloads.

**Comment by michael-collins** [comment]
A good stop gap could be printing out a download link below each image when viewing the individual assignments.

**Comment by btopro** [comment]
also related to #2226 if we had a way of quickly panning through and viewing multiple images + zoom + rotate + download types of functions
