### ISSUE TITLE
Studio image lightbox scrollbars too short, obscures image.

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2237]
Images seem to be cropped by the lightbox in studio, preventing me from scrolling down to see the entire image.

<img width="1123" alt="screen shot 2017-09-08 at 3 41 24 pm" src="https://user-images.githubusercontent.com/1085304/30228541-49e95f2a-94ac-11e7-8ec8-a34dd89d20a1.png">

**Comment by btopro** [comment]
#2226 would resolve this

**Comment by btopro** [comment]
closing so we resolve it in the related issue
