### ISSUE TITLE
Vagrant Boxes are now only accessed through authentication

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#224]
Anyone without the chef box already on their machine will not be able to run 
```shell
vagrant up
```
https://atlas.hashicorp.com/chef/boxes/centos-6.5 this URL is now protected by a login process.

**Comment by bradallenfisher** [comment]
However, you can create a new box via the web UI process. https://atlas.hashicorp.com/boxes/new

**Comment by btopro** [comment]
Uhh great... Time to find a new image I guess

Wp8
________________________________

**Comment by bradallenfisher** [comment]
Testing several now.

**Comment by btopro** [comment]
status update? I think you found one

**Comment by bradallenfisher** [comment]
bradallenfisher/centos-6.7 could replace chef/centos65 . You gonna fork? It
has the same basic setup that the chef box had.

status update? I think you found one

—
Reply to this email directly or view it on GitHub
<https://github.com/elmsln/elmsln/issues/224#issuecomment-137301383>.

**Comment by btopro** [comment]
==> default: Importing base box 'bradallenfisher/centos-6.7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bradallenfisher/centos-6.7' is up to date...
==> default: Setting the name of the VM: system_default_1441278356079_13551
==> default: Pruning invalid NFS exports. Administrator privileges will be required...

You need a password to get this going?

**Comment by bradallenfisher** [comment]
I think I might know what it is.  I think the perms on the box need to be
more permissible.

**Comment by btopro** [comment]
ur box is currently the default only because the old one is gone entirely; we'll work through any wonky little perms issues here and there, once it's not experiencing issues I'll fork for the project proper

**Comment by btopro** [comment]
@bradallenfisher changes to make before we fork and use this as our base
Clean out your repo that's left behind
make the vagrant user able to login with vagrant as the password

**Comment by bradallenfisher** [comment]
this is being uploaded now download from here
https://atlas.hashicorp.com/bradallenfisher/boxes/centos-6.7

**Comment by btopro** [comment]
You are now an owner on the elmsln team in there so you should be able to just re-associate it with the elmsln team. let me know

**Comment by btopro** [comment]
last PR fixed this, thanks for figuring this out @bradallenfisher you saved me weeks :)
