### ISSUE TITLE
Studio assignment detailed issue descriptions

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2241]
Student 1:

"I'm unable to view any submissions. When I click on the assignment, the tab across the top has "view submission" and nothing happens when I click on it. The same happens when I try to view comments you left on other submissions."

Student 2:

"I was able to open up the submission page for the HMW project earlier today, but now when I click on it when I'm on the Recent Activity page, in the "Your active project" section, it takes me to the Project Management page. From there, whenever I clicked on the HMW assignment, nothing happened. The page just seemed to reload. The comment and edit icons were also just reloading the page. But the delete button worked! Unfortunately, though, since it deleted the assignment from my Project Management page. (Sorry! I wasn't sure what would happen, so I just went for it). Anyway, it also looks like my Discover: Interview submission is also missing from the list on my Project Management page. I didn't delete that one though."

**Comment by btopro** [comment]
deleted to the other one......
