### ISSUE TITLE
Memory Script Problems with Yosemite(?)

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#225]
For some reason the code below won't let vagrant finish booting the VM. 
Mac Pro
Yosemite 10.10.5
Fresh install of vagrant 1.7
Latest VirtualBox

When i remove it from the Vagrant file, vagrant finishes booting. 

```ruby
  # automatically carve out 1/4 of the box resources for this VM
  config.vm.provider "virtualbox" do |v|
    host = RbConfig::CONFIG['host_os']
 
    # Give VM 1/4 system memory & access to all cpu cores on the host
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    elsif host =~ /linux/
      cpus = `nproc`.to_i
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    elsif host =~ /mingw32/
      mem = `wmic os get TotalVisibleMemorySize | grep '^[0-9]'`.to_i / 1024 / 4
      if mem < 1024
        mem = 1024
      end
      cpus = 2
    else # sorry weird Windows folks, I can't help you
      cpus = 2
      mem = 1024
    end
    # you can modify these manually if you want specific specs
    v.customize ["modifyvm", :id, "--memory", mem]
    v.customize ["modifyvm", :id, "--cpus", cpus]
 end
```

**Comment by btopro** [comment]
hmm, might be in need of a windows folks solution in the code. @andrewGearhart might know of something we could do cause he modded this for windows support in some other projects I believe

**Comment by AndrewGearhart** [comment]
I'm guessing that the host variable is no longer coming back as something other than mingw32 (or that sysctl no longer exists in that version of OSX. I should have a mac soon (next week or so)... and then should be able to work on figuring out why this is happening.

**Comment by btopro** [comment]
@AndrewGearhart awesome, keep us posted if you find anything out about said variable. This scripts generally makes the VM fly... or doesn't boot at all for others :p

**Comment by mmilutinovic1313** [comment]
Let me know if this is the same problem -- but I have been running into a similar error message running Yosemite in Vagrant. I get the following warning before the Vagrant boots: 

    Failed to mount folders in Linux guest. This is usually because
    the "vboxsf" file system is not available. Please verify that
    the guest additions are properly installed in the guest and
   can work properly. The command attempted was:

   mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
   mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

   The error output from the last command was:

   /sbin/mount.vboxsf: mounting failed with the error: No such device

According to the Vagrant issue queue, this is a known issue in Vagrant with Linux  

https://github.com/mitchellh/vagrant/issues/6169
https://www.virtualbox.org/ticket/928

Perhaps we can add some custom code for the OS detection. I'm currently trying to understand how vagrant determines OS to see if this is a plausible solution for either of these problems. The vagrant still runs, so this doesn't seem critical, but still rather annoying.

**Comment by mmilutinovic1313** [comment]
I upgraded the System to the following: 
Mac Pro
Yosemite 10.10.5
Fresh install of vagrant 1.7.4
Latest VirtualBox

This upgrade did not solve the mount error above -- however when I installed the plugin that @heyMP reccommended the message went away and it appears to have fixed this error. I'm not sure if I have posted this issue in the correct thread (I can move it if it isn't), let me know if this info and plugin helps you guys. Link is posted below:

 https://github.com/dotless-de/vagrant-vbguest

**Comment by mmilutinovic1313** [comment]
@bradallenfisher and @AndrewGearhart : I believe this is a reference to how to determine specific OS in Vagrant. 

https://github.com/mitchellh/vagrant/issues/5885

**Comment by bradallenfisher** [comment]
yeah when the box ages it needs updates. For instance yum update will update a whole ton of packages on the box including the kernel for the OS. Since the kernel is what the Virtual Box guest additions are built off of, when it gets updated, things like folder mounting break. 

This https://github.com/dotless-de/vagrant-vbguest was a life saver for me a couple months ago cause every box I built need yum update -y which would always break guest additions. :+1:
