### ISSUE TITLE
Cannot change theme colors 

### ISSUE THREAD

**Issue by lifelike99** [elmsln/elmsln#2254]
Bug:
- ELMSLN 0.8.0 

Changing the color values in theme / style settings does not change the colors of the theme.

**Comment by btopro** [comment]
What path are you on that you experienced this and also are you running 0.9.x or the 0.8.0 point release? 0.9.x currently reports 0.8.0 till we roll a full release from it

**Comment by btopro** [comment]
able to replicate, thanks for the report; our webcomponent transition altered a lot of class names and so the targeting needs to be more specific to hit "primary" and "secondary" at this point I think

**Comment by btopro** [comment]
they should be targetted correctly now

**Comment by lifelike99** [comment]
I applied the latest updates and initially was able to change theme colours but after a few changes it has become unresponsive again. I am only able to change the primary colour (affecting the font on certain pages)

**Comment by btopro** [comment]
@lifelike99 please open a new issue describing in details the steps you've taken to produce this problem so we can try and reproduce.  I'll also put it out there that the 0.10.x branch is HEAVILY refactoring the content outline concept and will have color support added back in (so to speak) and via a very different method of getting the support added (web component driven so much clearer as to what and why something is happening or not happening).
