### ISSUE TITLE
Sidebar menu items implemented differently

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2262]
While working on the sidebar css, I noticed that the navigation links are implemented differently.

The sticky jump-to-heading menu only has a paper-button while the rest of the sidebar nav has a lrnsys-button wrapper element. Would it make sense to also wrap the jump-to-heading menu in the same way? I think this is contributing to the large difference in style presentation.

## Sidebar item
<img width="426" alt="screen shot 2017-09-18 at 9 53 55 pm" src="https://user-images.githubusercontent.com/1085304/30572515-15271e5e-9cbc-11e7-9d58-c8f1d1647229.png">

## Jump Menu item
<img width="419" alt="screen shot 2017-09-18 at 9 54 27 pm" src="https://user-images.githubusercontent.com/1085304/30572514-152438b0-9cbc-11e7-995c-a573ef20295d.png">

**Comment by btopro** [comment]
mock ups or nuttin. You're not going to be able to chase down things implemented hastily ;)
