### ISSUE TITLE
studio admin filtering menu items are cut off

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2264]
<img width="853" alt="screen shot 2017-09-18 at 10 30 18 pm" src="https://user-images.githubusercontent.com/1085304/30573302-0d78e002-9cc1-11e7-935f-1c505f9529d4.png">

**Comment by btopro** [comment]
#2260 is the thing u probably actually want. this admin display is a bandaid for 1 time data model fixes in upgrade that took place

**Comment by michael-collins** [comment]
Oh, yea, would much rather have #2260
