### ISSUE TITLE
Studio Comment CSS and HTML updates

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2265]
```
lrnsys-comment {
  padding: 1rem 0;
}
.lrnsys-comment .style-scope.marked-element {
  line-height: 1rem;
  font-size: 0.9rem;
}
#papercard.lrnsys-comment {
  padding: 0.5rem 1rem;
  margin: 0.5rem;
  background: transparent;
}
h4.lrnsys-comment {
    font-size: 1rem;
    line-height: 1.25rem;
}
```
1. Delete Paper Badge. The amber highlight color is enough to differentiate the instructor comment from student comments.
2. For instructor comments: 
   - REMOVE `.amber .lighten-5` from `<paper-card>`
   - ADD: `.amber .lighten-5` to `<lrnsys-comment>` to encapsulate the entire comment in amber
3. I don't think we need shadows here. **Set elevation="0" instead of "1"** for `<paper-card id="papercard" class="paper-card-length-1 amber lighten-5 style-scope lrnsys-comment x-scope paper-card-0" aria-label="" elevation="1">`
4. Make more of the comment text visible by default. We need some way to know that you can expand the comment to see more. A down arrow or the word "more" could work.

This won't be perfect, but will make the comments experience much better in the short term.

**Comment by michael-collins** [comment]
## After:

<img width="529" alt="screen shot 2017-09-19 at 12 51 47 am" src="https://user-images.githubusercontent.com/1085304/30576274-cd0b04fa-9cd4-11e7-84bf-9f1aac593b83.png">

## Before

<img width="529" alt="screen shot 2017-09-19 at 12 52 06 am" src="https://user-images.githubusercontent.com/1085304/30576275-cd249ffa-9cd4-11e7-8fbb-07aa73569a7a.png">

**Comment by btopro** [comment]
> Delete Paper Badge. The amber highlight color is enough to differentiate the instructor comment from student comments.

Is it? Is it though? There is a distinct lack of neon pink in your mock up.

> For instructor comments: REMOVE .amber .lighten-5 from <paper-card>

not enough amber

> ADD: .amber .lighten-5 to <lrnsys-comment> to encapsulate the entire comment in amber I don't think we need shadows here. Set elevation="0" instead of "1" for <paper-card id="papercard" class="paper-card-length-1 amber lighten-5 style-scope lrnsys-comment x-scope paper-card-0" aria-label="" elevation="1">

"I don't think we need shadows" - Are you a web professional? The web only makes sense to people when skeomorphs are applied early and often

> Make more of the comment text visible by default. We need some way to know that you can expand the comment to see more. A down arrow or the word "more" could work.

Now your just getting greedy, we pay for that line visibility per pixel you know.

> This won't be perfect, but will make the comments experience much better in the short term.

Much like a lot of opinions these days, I see no sources cited. Please cite at least 3 sources that verify this "won't be perfect".

**Comment by michael-collins** [comment]
The main goal was to reduce font size and reign in line height to something usable. Next time instead of spending an hour getting you "hyper specific" recommendations (AKA I did all the annoying work for you, you're welcome), I'll just create an issue called "Comments suck, didn't read" and expect that you'll know which css properties I was referring to.

**Comment by btopro** [comment]
Lol. This was closed cause all your feedback was implemented ;)
