### ISSUE TITLE
Issues with Making Section Active

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#228]
@btopro hoping you might be able to help out with this. I'm getting an issue with getting my section to show as active. When I spin up a MOOC for a course and run the cron/sync everything, the section set up from the CIS  access string is automatically set to inactive, so all students have their roles automatically set as 'past student'. When I edit the section and change it to active (from /cis/section-list) I get a lot of warning messages (about 30 lines of "Strict warning: Only variables should be passed by reference in _cis_section_load_section_by_id() (line 436 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/features/cis_section/cis_section.module)." I also get these messages during the initial roster sync :
![image](https://cloud.githubusercontent.com/assets/4973810/9574878/d6200cd6-4fc2-11e5-9fe9-33809a64d148.png)
![image](https://cloud.githubusercontent.com/assets/4973810/9574892/04dd1a3c-4fc3-11e5-86c7-fcdecf1ecc4c.png)

When I check out the user list, it's duplicating the users and giving them both roles:
![image](https://cloud.githubusercontent.com/assets/4973810/9574908/3fc46dee-4fc3-11e5-920f-f43cb23aa342.png)

I've run the cron after this and get the following:
![image](https://cloud.githubusercontent.com/assets/4973810/9574923/614e777a-4fc3-11e5-8e29-1e0f9eb180a8.png)

But that doesn't affect anything. I've then left our nightly cron to work, and it automatically sets the section back to inactive again - and all users have the past students role again too. 

Not sure if you can tell what the problem might be or if this issue might have been fixed as we're working in the old UX but thought there might be a patch or something we could apply?

**Comment by btopro** [comment]
Do you have terminal level access to the server its on? Might need to ser what version git commit this is based on since we are in preversion territory. I believe all 3 of the issues you mention have been resolved in newer builds, the pass by references definitely are, the automatic past user ls part I believe as well.

CIS UX shouldn't be an issue as the data model is the same there and I actually still run the 1.x at the moment so I know that's not the issue.

Let me know if you have term access and well go from there via slack dm

**Comment by rickhumphries** [comment]
Looks like an upgrade might be on the cards then. I don't have terminal level access unfortunately and it's a bank holiday here today so won't be able to get in touch with Orange Bus atm. I'll talk to them tomorrow and Slack dm you. Thanks

**Comment by btopro** [comment]
Closing til we get some word on upgrade as I believe this is an order issue.

**Comment by rickhumphries** [comment]
@btopro since the update, those strict warning messages don't show up anymore, however - we still get the "extra user role" problem when switching a section between active and inactive. If a section is inactive then all users are past students, however if it's switched to active each student then has both the 'past student' and 'student' roles.

**Comment by btopro** [comment]
@rickhumphries so are you seeing the section switch between active and inactive on a regular basis or the issue from before where it's not holding its state? Activating a section will grant student role, deactivation will grant past student, then activation again currently is just told to grant a student role (so you could have both). This is the default behavior as silly as it might seem.

So. if you don't want past student role to be granted as that's built into cis_section, it does have support for overriding itself and while I wrote this just this comment window it SHOULD work. to stop granting the past student role at least.
```
function MYMODULE_cis_section_deactivate_alter(&$calls) {
  foreach ($calls as $call) {
    if ($call == '_cis_section_deactivate_section') {
      unset('_cis_section_deactivate_section');
    }
  }
  // my custom call to run MY deactivation routine
  $calls[] = '_MYMODULE_cis_section_deactivate_section';
}

/**
 * Callback for hook_cis_section_deactivate().
 */
function _MYMODULE_cis_section_deactivate_section($node) {
  // standard conversion of student to past student roles
  $student = user_role_load_by_name(CIS_SECTION_STUDENT);
  $past = user_role_load_by_name(CIS_SECTION_PAST_STUDENT);
  $current = _cis_section_load_users_by_gid($node->nid, $student->rid);
  // find users that no longer came across
  $diff = array_diff($current, array());
  foreach ($diff as $uid) {
    $account = user_load($uid);
    // drop student role
    unset($account->roles[$student->rid]);
    // gain past student role
    // THIS IS THE PART THAT GIVES THEM THE PAST STUDENT ROLE
    //$account->roles[$past->rid] = $past->name;
    user_save($account);
  }
}
```

**Comment by rickhumphries** [comment]
I'm not seeing the state switch automatically - will do some further checks later to see whether it's holding its state but I'm pretty sure it is.

I think it's the default behaviour that was confusing me with students having more than one role - I've been switching the state of the section manually from editing '...cis/section-list' so now when a section is active all students have two roles (student and past student). I think I was expecting the past student role to be removed at the same time as the student role was granted when making the section active.

Anyway, just checked and it doesn't seem to be having an affect on student access to the course so that's good. Is the student role a 'higher priority' role than the past student role then?

**Comment by btopro** [comment]
Oh ok, Roles are addative so it's not a big deal in that regard

**Comment by rickhumphries** [comment]
OK that's fine then
