### ISSUE TITLE
LRN apps should not inherit header styles

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2282]
![screen shot 2017-09-27 at 3 09 04 pm](https://user-images.githubusercontent.com/3428964/30932564-de79f30a-a395-11e7-9985-2239cd7d6464.png)

**Comment by heyMP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LRN apps should not inherit header styles #2282](https://trello.com/c/r8L0d1oU/64-lrn-apps-should-not-inherit-header-styles-2282)

**Comment by heyMP** [comment]
This needs more of a holistic approach.  Mitigated locally.

**Comment by btopro** [comment]
+1
