### ISSUE TITLE
blank comments created by accident

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2283]
I've noticed that some students are leaving blank comments. I think this is because the comment is created when you click on the comment button, not on save. Perhaps if the comment doesn't have any content, it can be deleted when navigating away or not get created until the initial save? This will also throw off the "students who need feedback" listing on the dashboard tricking the system into thinking that comments have been left.

**Comment by btopro** [comment]
workflow wise it has to make something to have things associated with it. If they are leaving a blank comment legitimately then I'm not sure how to help with that. There may be older ones that are blank because they had emoji's in them which caused some initial batches to fail because emojis are apparently 🌶

**Comment by michael-collins** [comment]
I don't think anyone was using emojis in the comments. I think they clicked the comment button, which creates the text area (and Drupal comment) to then write, and instead navigated away without writing anything. I've done this accidentally myself. Maybe a better way would be to have a text area where you can add the comment into a text field at the top, and then click comment button to create the "thing" and associate the text entry after it's made?

**Comment by btopro** [comment]
this probably won't be logical sounding but that workflow shift is a complete refactor. I don't disagree with you. Perhaps we could make comments "unpublished" behind the scenes by default and then if there's content saved into it that it publishes it (which would solve both issues; sticking to model while fixing the issue)

**Comment by btopro** [comment]
fixed as well
