### ISSUE TITLE
Validating H5P Package Failed - Updating H5P Content Types

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2288]
Bug:
- 0.8.1

When updating certain content types in H5P I get the message that validating H5P package failed. See below:
![image](https://user-images.githubusercontent.com/4973810/31148414-8ecba2f6-a884-11e7-9744-98455abf7199.png)

After checking the dblog this is the error that shows:
Type:	php
Location:	http://media.elmsln-dev.co.uk/h5peditor/5e473493da82c/526/library-install/H5P.MultiChoice
Referrer:	http://media.elmsln-dev.co.uk/node/482/edit
Message:	Warning: unlink(/var/www/elmsln/config/stacks/media/sites/media/bc/files/h5p/temp/h5p-59d3f53231161/h5p-59d3f53231161.h5p): No such file or directory in H5peditorDrupalStorage::removeTemporarilySavedFiles() (line 230 of /var/www/elmsln/core/dslmcode/stacks/media/sites/all/modules/local_contrib/h5p/modules/h5peditor/h5peditor-drupal-storage.class.inc).
Severity	warning

This has only happened on certain content types. Others I've been able to successfully update.

**Comment by btopro** [comment]
may want to run leafy to update permissions under the hood cause that's what that unlink error is

**Comment by rickhumphries** [comment]
Ran `6) clean up directory and file permissions issues` but got a similar error along with a couple more about upgrading my version of H5P:
![image](https://user-images.githubusercontent.com/4973810/31163644-47b20caa-a8db-11e7-95f7-28d6fbf3735e.png)
Should I just swap it out for the latest version?

*sidenote: I actually couldn't find the H5P module in core so I'm presuming this wouldn't have updated to the version you run? Might not have been looking in the right place though but thought it would be here https://github.com/elmsln/elmsln/tree/master/core/dslmcode/shared/drupal-7.x/modules/ulmus 
I can only see h5p_tincan_bridge. The H5P module we have is in our config

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/tree/master/core/dslmcode/stacks/media/sites/all/modules/local_contrib/h5p

**Comment by btopro** [comment]
Each domain can have its own local modules. The ones that do only have a couple ever

**Comment by btopro** [comment]
As for version not sure but maybe your copy is messing w. The included copy.  A bit of a guess there tho

**Comment by rickhumphries** [comment]
Ah OK - that's useful to know. I had a copy in config that said it was v1.6(!) which is weird. Then the core version is v1.3 - which is the one that is showing in Media so that warning still doesn't make sense.

I've removed the copy from config but will have to wait to pull that onto the server to see if it has an effect.

**Comment by btopro** [comment]
cool; then you'll also have to issue a `drush @media rr --y` in order to rebuild file locations (since H5P will have moved as far as it's concerned)

**Comment by btopro** [comment]
I just ran into this as well. It had to do with the php libraries `zip` and `mbstring` being installed on the server (fyi)

**Comment by rickhumphries** [comment]
So I need to install those libraries on the server for it to work? OK, I'll try it and report back

**Comment by btopro** [comment]
@rickhumphries ever get this fixed?

**Comment by rickhumphries** [comment]
Yeh - updating Drupal module from v1.30 to v1.32 seems to have done the trick
