### ISSUE TITLE
Downloading Whole Book as a PDF

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2289]
I'm lead to believe from reading about the Printer, Email and PDF module that if you Print PDF from the book root then it should download the whole book. However, when I try this I only get a blank page. (/printpdf/[nid])

However, when I choose to Print from the book root it sets up a print preview of the entire book. (/book/export/html/[nid])

**Comment by btopro** [comment]
good question; that's a really complicated problem (sadly) which something like #2168 could help w/. The real issue is performance as well as PDF tech inconsistency. For example DOMPDF (or whatever lib we use in PHP) has a lot of issues where if it fails it'll hard brick. I changed that to cut the page off early / make it blank as a safety net.

It should absolutely be an option, but it probably requires more consideration for scale.

**Comment by rickhumphries** [comment]
Does wkhtmltopdf library work on PHP? I don't think it does and would be interested to see how this performs over dompdf too. I know I've championed this before in #280 

Pandoc mentions wkhtmltopdf in it's manual too (https://pandoc.org/MANUAL.html) and I feel like it would be the best in terms of converting CSS styles as well

I'd like to switch the library in and see how it goes, but not sure how I'd do it purely as config as we'd need to do a symlink from a directory in core (`elmsln/core/dslmcode/stacks/courses/sites/all/modules/local_contrib/print/lib`)

**Comment by btopro** [comment]
I mean you could throw it in there if that's the only available install location and see. I seem to recall it having issues but it's been awhile. Pandoc solution (even if it uses that) would be highly preferrable

**Comment by JackWillDavis** [comment]
I've got a partial solution for including a book's child pages within a PDF to allow downloading a full book in one go. Just working out some of the details now but I have a few questions:

1. Is this already in development? If so, I won't spend too much time (although it is good practice)
2. It involves changes to /var/www/elmsln/core/dslmcode/stacks/courses/sites/all/modules/local_contrib/print/print_pdf/print_pdf.pages.inc which I assume is maintained outside of ELMSLN?
3. Please could you tell me where the hook is for adding a "Print PDF" preferences menu on the right hand side? (So I can add a new link to the Alternative Options)?

**Comment by btopro** [comment]
1. No, planned yes but we're still a ways off. The PDF stuff that's in 0.10.x is the same as 0.9.0 which has SOME improvements / accuracy over the previous ones but still lacking.
2. I'd review the 0.10.x version of that code prior to modifying just to be sure it doesn't do anything weird. May want to just download the print module used in the 0.10.x (if its different) and then replace yours and make changes from there.
3. here's where stuff gets in there -- https://github.com/elmsln/elmsln/blob/0.10.x/core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper/mooc_helper.module#L848-L890

**Comment by btopro** [comment]
also for context; the longer term vision is to have a dockerized #2168 pandoc microservice will be able to provide far more accuracy / flexibility on print options (haven't started work on it #2310 blocking for it). Also #2247 the high fidelity content authoring / presentation app will lead to those menus being changed.

This isn't a "don't bother working on those" it's a "within the next year they'll need some modifications / we'll have more lasting solutions" potentially.

**Comment by JackWillDavis** [comment]
Thanks for sending that info over! Happy to make a PR if you think it might serve as an interim solution but can always just apply our end. I've applied it to the 0.10.x branch but it looks like it works back to 0.8.1 too.

I've had a crack at it anyway and added a section [here](https://github.com/JackWillDavis/elmsln/blob/print-pdf-book/core/dslmcode/stacks/courses/sites/all/modules/local_contrib/print/print_pdf/print_pdf.pages.inc#L131-L146) which automatically includes any child nodes when printing from a Book. It will work the same way for most pages but if you're in the top-level, it'll append all child pages to the PDF before downloading. This should allow the user to print the entire Book if they want.

At the moment, there is no Print PDF link (in the preferences menu on the right) for the top level of a book (like there are on child pages). I'm not sure where I would add that?

**Comment by btopro** [comment]
very cool; if modifying a drupal contrib module make sure to include a patch file against that project that has the change (that way we can send back to the print module as well as for our own purposes when we upgrade core projects).

https://github.com/elmsln/elmsln/blob/0.10.x/core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper/mooc_helper.module#L875-L888 place to add support for placing that link on the top level of the outline

**Comment by JackWillDavis** [comment]
Thanks for sending that info over. I got a solution sorted, I just need to move it into a patch file then I'll be able to apply manually if it's needed. Let me know if you wanted a PR put through to last until the microservice is up and running.

Thanks again

**Comment by btopro** [comment]
PR most welcome

**Comment by btopro** [comment]
Deploy specific use case resolved; longer term solution will be to consolidate document creation into #2384 via #2168
