### ISSUE TITLE
Top Menu Layout

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2293]
Kicking off a discussion on the top menu layout in order to make the most effective and efficient use of this space.

We're trying to reduce the amount of menu layers somewhat so the main content isn't always pushed so far down the screen. This is particularly noticeable on mobile too as I believe the etb-course-nav layer is split into two and they sit on top of each other (which I don't think is really needed).

This is the kind of thing we're going to apply in the current version we run (0.8.1), merging the banner and the etb-course-nav layer:
![image](https://user-images.githubusercontent.com/4973810/31268744-9fcbcdd6-aa75-11e7-9b8e-96692e92c8a5.png)

I think we've also been able to make the banner and etb-network-nav layer slightly thinner too with this setup.

Our aim going forward is to have less text in the banner itself and let the 'course title group' provide the textual info we need about the course name etc. The banner would just be for visually 'branding' a course.

**Comment by btopro** [comment]
another thought I know has come up in this discussion internally was the idea of the 1st hit on a course site being a bigger banner then the pages within. In this way you'd almost have a punch in the face of "this is where you are / what you'll be learning about" w/ a bigger image and then everything after that is condensed down.

For additional context (granted still completely a prototype) the lrnapp-book app that I've been working on effectively eliminates page reloads for the majority of users and also manages scroll position. This effectively keeps the top bar above the fold of the user's display.

Thanks for getting this discussion kick started :)

**Comment by btopro** [comment]
Changing associations as @zanesensenig @nikkimk would be running point on any form of a re-envisioning of the top of the UIs we use for building out our apps

**Comment by btopro** [comment]
merged in :) thank you
