### ISSUE TITLE
H5P Drag and Drop

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2297]
Bug:
- 0.9.0
- H5P drag and drop content type throws an error and doesn't render.

![screen shot 2017-10-13 at 12 36 36 pm](https://user-images.githubusercontent.com/3428964/31556941-f2559b78-b014-11e7-8f82-375c794b3409.png)

**Comment by btopro** [comment]
upgrade everything in H5P manually (its annoying) but make sure it actually is all upgraded from the hub and see if this helps.

**Comment by btopro** [comment]
just tested; newer versions of H5P have fixed this (love when we do nothing and it works)
