### ISSUE TITLE
ELMS:LN GravCMS Branding Site Add Ons?

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#2300]
So I'm not sure if this is the right place, but I was thinking for purposes such as Open Ulmus, we could provide a central "branding" domain where universities, organizations, etc. can create an "about us" for their group. I've noticed that the document root usually is blank (for example openulmus.org throws an apache landing page message as opposed to online.openulmus.org.). Would it be feasible to add a branch of ELMS:LN that allows for a branding site? The site wouldn't have to be drupal specific (D7, D8, etc.) but Drupal, Wordpress, non-CMS' such as jekyll could be optionally installed at the document root for this purpose? Idk...just thoughts!

**Comment by btopro** [comment]
makes sense

**Comment by btopro** [comment]
other then the jekyll part. The rule of things in core is 2 people have to approve and understand how it works. Maybe a polymer static site or a GravCMS site since Grav will be supported at some point

**Comment by mmilutinovic1313** [comment]
Perfect. I was thinking of grav but I couldn't think of it's name. I can coordinate with you how this might work in the next few days?

**Comment by btopro** [comment]
yeah, we'll want a single Grav core that we do our silly symlinkage stuff for :p

**Comment by btopro** [comment]
#878 related

**Comment by btopro** [comment]
@mmilutinovic1313 I just deployed a site using https://getgrav.org/downloads/skeletons Agency and it's really slick (i'll DM it to you)

**Comment by mmilutinovic1313** [comment]
Awesome! Looking forward to it

**Comment by mmilutinovic1313** [comment]
I'm guessing this may take a bit to get into core. What I'd like to do to help with this is figure out if we can run grav on the root of openulmus.org (ie. not online.openulmus...) And then use lessons learned to try and pull this into core? Would this be feasible with how web servers are configured? 

https://github.com/elmsln/openulmus.org/issues/27

**Comment by btopro** [comment]
yeah that's not terribly difficult. Easy to add in support for, slightly more involving to add support in a sustainable manner like the drupal stuff so it's not tied to the repos that get stamped down.

Absolutely in the roadmap. Absolutely feasible. My real questions with it come down to how best to multi-site it; wether it's a single copy or multiple copies of Grav core (probably multiple but needs some diagramming / thinking about deeper)

**Comment by mmilutinovic1313** [comment]
https://github.com/getgrav/grav-plugin-login-oauth

**Comment by btopro** [comment]
Grav is now in core though it needs hooked up / customized. There is an available domain to start working w/ the installer located at `/var/www/elmsln/domains/_toplevel`

We can have a working session at some point if you need help debugging how to wire this up (I Haven't tried yet cause I'm focusing on the centralized webcomponent registry but technically it's there and ready to start experimenting with where files will go / what's the defaults / etc)

**Comment by mmilutinovic1313** [comment]
Thanks @btopro! I'll set up some time with you soon so we can work through the specifics.

**Comment by btopro** [comment]
dropped grav out of core, HAXcms reigns.
