### ISSUE TITLE
Drush @elmsln up error:  /root/drush-backups/SITE-ALIAS/DATESTAMP/drupal/profiles/blah-blah is not readable or does not exist.

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2306]
Bug:
ELMSLN 0.8.0

- What happens
drush @elmsln up error: "/root/drush-backups/SITE-ALIAS/DATESTAMP/drupal/profiles/blah-blah is not readable or does not exist" Updates rolled up.

- What you expected to happen
Updates went successfully

Feature request:
Perhaps what happens is: drush creates backup folder(s) but doesn't have write access because folder(s) owner is root. Any chance this can be fixed?

**Comment by btopro** [comment]
yea that's most likely the case. Option 6 cleans up some permissions and option 7 cleans up the drush plugins for the active user account. Try both of those and report back please.

**Comment by yurg** [comment]
Options 6 & & haven't change a thing, yet let us close this one in favour of #2307
