### ISSUE TITLE
Command line upgrade confusion: Leafy

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2307]
Bug:
ELMSLN 0.8.0

- What happens
Following exactly this page https://elmsln.readthedocs.io/en/latest/development/upgrades/How-do-I-run-upgrades/  I've tried any option available (2, 3, 9) yet  system stays at 0.8.0  after a long process of making changes visible via command line. 
Especially confusing is this line "please select a branch you want to update" after selecting Option 2:
have tried to type **0.8.0** and **0.9.0** with no difference in Leafy behaviour at all: it starts doing something yet nothing changes in the end.  

- What you expected to happen
Upgrade to 0.9.0 and (if lucky enough) get all the most recent Drupal security core updates.   

Feature request:
* Please explain, what have I done wrong?
* May be elaborate this bit: "This will prompt you for a branch" on https://elmsln.readthedocs.io/en/latest/development/upgrades/How-do-I-run-upgrades/ page by an example of what exactly has to be typed in reply?

**Comment by btopro** [comment]
leafy helps w/ getting a specific branch of elmsln going and applying upgrades off of it. For example, if your running master branch (which currently holds 0.9.0) then this will pull the latest of master and then run the upgrade routine. if you get your code from some other place (mirror or manual upload / checkout of a tag like you said) then you probably want the option that's just updating sites in the network.

If you are trying to checkout a specific tag
```
cd ~/elmsln/
git checkout 0.9.0
leafy
```
Pick option 3

The other bit you are looking for is option 9 which applies server level scripts which can't be changed via simple drush config. These can require `sudo` rights at times which is why they are in a separate command (for reference).

Hope this helps. Please feel free to PR against the documentation page in question in order to clear this up better: https://github.com/elmsln/elmsln/blob/master/docs/development/upgrades/How-do-I-run-upgrades.md
Or leafy command language: https://github.com/elmsln/elmsln/blob/master/scripts/elmsln.sh
Or upgrade system script language: https://github.com/elmsln/elmsln/blob/master/scripts/upgrade/elmsln-upgrade-system.sh

**Comment by yurg** [comment]
Thank you for your input; still a bit unclear though. 
This part:

> cd ~/elmsln/
> git checkout 0.9.0

Ends at this message: 

> error: pathspec '0.9.0' did not match any file(s) known to git.

Leafy also invites to perform:

> git pull origin master

And an output is:

> From https://github.com/elmsln/elmsln
>  * branch            master     -> FETCH_HEAD
> Updating 0bcffc4..643a7dd
> error: Your local changes to the following files would be overwritten by merge:
> 

So we need to do 
> git stash save --keep-index 
(worth adding to Leafy output perhaps?)

Running 
> git pull origin master

Gives very informative message

> Current version of codebase: 0.9.0
> Current version of your system: 0.8.0

It's time to ask "So what?" at this point. Well, let us see what's next:

> Leafy - option 9 selected  

Here we are (among of notices): 

```
stacks.online >> PHP Fatal error:  views_plugin_display::destroy(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "authcache_views_plugin_display_extender" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/views/plugins/views_plugin_display.inc on line 272
stacks.online >> Drush command terminated abnormally due to an unrecoverable error.                                                          
[error]
Error: views_plugin_display::destroy(): The script tried to execute a method or access a property of an incomplete object. Please ensure that
the class definition "authcache_views_plugin_display_extender" of the object you are trying to operate on was loaded _before_ unserialize()
gets called or provide a __autoload() function to load the class definition  in
/var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/views/plugins/views_plugin_display.inc, line 272
Undefined index: error_status preflight.inc:573 
```
And another one: 

```
Error: Cannot redeclare _field_info_field_cache() (previously declared in
/var/www/elmsln/core/dslmcode/cores/drupal-7/modules/field/field.info.inc:16) in
/var/www/elmsln/core/dslmcode/stacks/courses/profiles/mooc/modules/field/field.info.inc, line 16
elmsln.courses.frontdeskv >> 
PHP Fatal error:  Cannot redeclare _field_info_field_cache() (previously declared in /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/field/field.info.inc:16) in /var/www/elmsln/core/dslmcode/stacks/courses/profiles/mooc/modules/field/field.info.inc on line 16
```
And finally 

> Undefined index: error_status preflight.inc:573                                                                                         [notice]
> ELMSLN full network upgrade complete!

**Yahoo!!!**

Let us double-check:

```
leafy
--2017-10-24 23:00:09--  https://raw.githubusercontent.com/elmsln/elmsln/master/VERSION.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.28.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.28.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6 [text/plain]
Saving to: ‘STDOUT’

100%[=====================================================================================================>] 6           --.-K/s   in 0s

2017-10-24 23:00:09 (1.11 MB/s) - written to stdout [6/6]

ELMSLN VERSION: 0.9.0
```

And an extra check:

> drush @online status
>  Drupal version                  :  7.56

Looks good, but why this now?? 

```
 drush @online up
Update information last refreshed: Tue, 10/24/2017 - 08:03
 Name                                                Installed Version      Proposed version  Message
 Advanced CSS/JS Aggregation (advagg)                7.x-2.21               7.x-2.27          Update available
 Asynchronous Prefetch Database Query Cache (apdqc)  7.x-1.0-rc3+14-dev     7.x-1.x-dev       Update available
 Bakery (bakery)                                     7.x-2.0-alpha4+21-dev  7.x-2.x-dev       Update available
 Entity Reference (entityreference)                  7.x-1.2                7.x-1.5           SECURITY UPDATE available
 HTTP Parallel Request Library (httprl)              7.x-1.14+53-dev        7.x-1.x-dev       Update available
 IMCE (imce)                                         7.x-1.10               7.x-1.11          Update available
 Module filter (module_filter)                       7.x-2.0                7.x-2.1           Update available
 No Current Password (nocurrent_pass)                7.x-1.0                7.x-1.1           Update available
 Replicate (replicate)                               7.x-1.1                7.x-1.2           Update available
 Universally Unique ID (uuid)                        7.x-1.0-beta2          7.x-1.0           Update available
 Wysiwyg (wysiwyg)                                   7.x-2.3                7.x-2.4           Update available


Security and code updates will be made to the following projects: Advanced CSS/JS Aggregation [advagg-7.x-2.27], Asynchronous Prefetch Database Query Cache [apdqc-7.x-1.x-dev], Bakery Single Sign-On System [bakery-7.x-2.x-dev], Entity reference [entityreference-7.x-1.5], HTTP Parallel Request &amp; Threading Library [httprl-7.x-1.x-dev], IMCE [imce-7.x-1.11], Module Filter [module_filter-7.x-2.1], No Current Password [nocurrent_pass-7.x-1.1], Replicate [replicate-7.x-1.2], Universally Unique IDentifier [uuid-7.x-1.0], Wysiwyg [wysiwyg-7.x-2.4]
```

**Comment by btopro** [comment]
looking at git docs I was wrong its `git checkout tags/0.9.0`

if you get 'files have changed' that either means you were manually updating / uploading things or there's some permissions off. I run the following to get things forced to the correct release point
```
git fetch --all
git reset --hard origin/master
```

In this case, forcing to master (which for this example would be 0.9.0).

as for the errors that happen during upgrade I can't do anything about these; they are a result of drupal's underpinnings being swapped out and get resolved after upgrade (hence the need for the upgrade).

As to your last question of running `drush @online up`... Never. and I mean NEVER, run this command unless you are planning on forking the project and doing things on your own. The reason for this is that this will update drupal at a code layer and that's something that elmsln is in charge of (https://elmsln.readthedocs.io/en/latest/development/Should-I-update-Drupal-modules/).

If you were trying to apply commands to get the database in sync with the code base then you might want something like

```
drush @elmsln rr --y
drush @elmsln updb --y
```

While not exactly the same, this is more or less what the upgrade all sites option is doing (https://github.com/elmsln/elmsln/blob/master/scripts/upgrade/elmsln-upgrade-sites.sh#L54-L66 )

**Comment by yurg** [comment]
@btopro Thank you for your input, very handy! Well, that was a journey. What if I PR all important parts of this issue  against documentation?

**Comment by btopro** [comment]
that would be fantastic, we're always looking to grow and improving dev UX for the next person

**Comment by yurg** [comment]
@btopro  Great, let me just summarize it all to be clear for anyone.

**Comment by btopro** [comment]
keeping open till theres a PR that reference this so we can close it off of that (general convention we follow; issues have to close w/ a PR or duplicate / resolution)

**Comment by yurg** [comment]
#2311

**Comment by btopro** [comment]
thank you for the documentation PR!
