### ISSUE TITLE
Create a circle click menu

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2316]
As part of HAX the web, we need a context menu when working with outline designer's replacement / complex operations.
Something like this in general design yet having pie slice areas to be able to hit to improve usability (the google one you have to press the icon)
![2017-11-03_08-56-46](https://user-images.githubusercontent.com/329735/32374622-ed54861e-c074-11e7-9448-10acbd395bba.png)

 More like this (tho less terrible looking)
![2017-11-03_08-57-14](https://user-images.githubusercontent.com/329735/32374662-17577e80-c075-11e7-8e1a-aea78de78c5e.png)

**Comment by btopro** [comment]
https://github.com/LRNWebComponents/pie-menu work is being conducted here

**Comment by btopro** [comment]
@nikkimk as we step you into polymer land this could be a good 1st one to transition front end skillsets into component based skillsets since I've hit a bit of a diminishing returns (personally) associated w/ solving this. Tagging so we have a reference point for after polymer land begins

**Comment by nikkimk** [comment]
@btopro Take a look at what I uploaded. I have the shape, but for some reason, the icon attributes aren't setting.

https://github.com/LRNWebComponents/pie-menu/

**Comment by btopro** [comment]
if it's in the svg thing being messed with that's the whole svg in a svg thing I was running into which rips it out. Need to port the circle to be CSS driven instead I think to solve it. Also the `icons:` is fine but is also the default of `iron-iconset-svg` that is a sub-element to iron-icons so it's not necessary.

also if you push changes up you can run `sh update-demo.sh` from inside the directory and it'll update the demo on github pages to share around (esp useful when sending over to Kate n company in the future for quick feedback)

**Comment by nikkimk** [comment]
@btopro It's an SVG sandwich. They aren't nested in the SVG. Instead it's SVG background & SVG foreground with icons hiding between them. My version of the demo/index.html had camelCasing, which is where the SVG sandwich broke down.

**Comment by btopro** [comment]
@nikkimk dono where the best place to add things to add functionality:
- [ ] color per pie segment
- [ ] support for empty segments
- [ ] support for naming the event to fire up. (we do this in HAX to make it clear what event was bubbled up) so we can bubble up a 'machine name' like 'left' instead of 'Left'
- [ ] not sure the current implication but we'll need events that can then trigger menus. Maybe this is using slots in the tag in a holding pen per button name so that when clicked it can display that inform (optionally). Like if the button said 'visibility' and it was clicked it would quickly show the slot contents which is a menu of options to toggle between.

**Comment by btopro** [comment]
exists, just haven't had need for it yet; once we do then we'll implement it :) great work @nikkimk
