### ISSUE TITLE
In-Context Repository

### ISSUE THREAD

**Issue by nikkimk** [elmsln/elmsln#2319]
As content is being authored, it would be great to have repository access (OER and internal resources) in the AX. 

The system could use page titles, competencies, tags, and headings to recommend repository resources to use.

And... a learning object, a page, lesson, or entire an entire course could be shared with repositories easily from the AX.

And... it would be great if student submissions could become learning objects in their own right if students opt in to it and instructors click something to indicate it has been reviewed.

**Comment by btopro** [comment]
#567

**Comment by btopro** [comment]
at least part of this sounds like it fits into the app store concept currently being baked into HAX; the site itself or a centralized repo of stuff would just be another backend to search and content objects would be what was being provided.
