### ISSUE TITLE
White Paper Update - http://www.elmsln.org/documents

### ISSUE THREAD

**Issue by cleverington** [elmsln/elmsln#2321]
Feature request:

Both for faster onboarding and for interesting sponsors, it would be useful to have an up-to-date set of documentation, presentations, and brochures which can be referenced by a varied audience interested in learning about ELMS:LN:

- **non**-developers
- Developers
- Educators
- etc.

This updated documentation will assist in making some notes to create some of the initial workflows and visuals for Open Ulmus, which will in turn assist with the first baby steps towards fiscal sustainability and revenue generation. 

https://www.elmsln.org/documents is a great resource, but the content is either invalid or dated.

### White Papers
- ELMS Learning Network: An EdTech Platform for Sustaining Innovation - **Dated 05/08/2015**
- ELMSLN: A Disruptive Learning Technology - **Dated 08/24/2014**

As a side-note, since onboarding it appears verbiage for both should be reviewed during the update, as well, due to the project generally being referred to as `ELMS:LN`instead of `ELMSLN`.

### Presentations
- Drupalcamp Atlanta, Kennesaw State University - Rethinking System Design (Oct 2015) - **Unavailable**
- GovCon, Bethesda MD - Rethinking System Design (July 2015) - **Unavailable**
- NYCCamp, United Nations - Creating Sustainable Innovation (July 2015) - **Unavailable**
- OpenEd, Washington D.C. - ELMSLN for OER (Nov 2014) - **Unavailable**
- Campus Tecnology, Boston MA - Transforming Educational Technology Design (July 2014) - **Unavailable**
- Drupalcon, Austin TX - We're here to replace your vendors (June 2014) - **Unavailable**

**Comment by cleverington** [comment]
As an additional visual, expanding the diagram within the `ELMS Learning Network: An EdTech Platform for Sustaining Innovation` document with the full complement of currently available services would definitely be useful on a brochure.

## Current Service Example

This is an _excellent_ visual, and an expanded/completed version of it would look _great_ as a background for our OpenCollective Sponsor page and possibly the branding site.

![example-visual-services](https://user-images.githubusercontent.com/1015474/32684565-519752ca-c64a-11e7-840c-b8b85e70c3c0.png)


## List of Current Services?

I found this on https://elmsln.readthedocs.io/en/latest/development/Vagrant-Step-by-Step-setup/ 

It looks like it might show the full compliment of services, but... I'm still onboarding so I'm not sure.

![current-services-is-it](https://user-images.githubusercontent.com/1015474/32684576-774cfc18-c64a-11e7-9b4e-41764df774ce.png)

**Comment by btopro** [comment]
@rickhumphries if offering

**Comment by btopro** [comment]
[elmsln-siggraph2015-abstract.docx](https://github.com/elmsln/elmsln/files/1479267/elmsln-siggraph2015-abstract.docx)
@cleverington @rickhumphries @mmilutinovic1313 previous source document of that last PDF that @michael-collins dug up :)

**Comment by btopro** [comment]
Create vision statements white paper style about the big 4 initiatives of elmsln for the next year, in no order.
Data visualization
High fidelity mode / book creator
Media production workflow
Open studio

Vision statement
What this transforms
Who it serves
A visualization of the concept
An ER visualization
Roadmap high level to MVP

**Comment by btopro** [comment]
HAX, Web components and the distributed NGDLE future white paper added to elms:ln website -- https://psu.app.box.com/s/gk6013odcl3115j3ibfzudj3bqar059v

This is related to this issue since it's big enough to get it's own white paper. ELMS:LN still needs an updated one more directly though.
