### ISSUE TITLE
Make a generalized powered-by webcomponent for community sites

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2322]
https://github.com/elmsln/elmsln-logos/blob/master/elmsln-powered-sticker/powered-by-elmsln-sticker-3-1200-%402x.png

@nikkimk @michael-collins while not critical, given that Polymer Day is this week, this could be a really good element to make sure you get some fundamentals down. @heyMP and I did a lot of these sorta elements early on (aka March :) ) as we practiced a bunch in the ramped up to larger elements.

To our larger contrib audience also attending Polymer Day -
@djfusco @AndrewGearhart @aitala @rickhumphries @JackWillDavis similar advise for you if interested in a good tight scoped component to really get the fundamentals of the concept down.

`powered-by` property MVP:
- image
- label

Extra credit:
- icon (for the lightning bolt)
- iconColor (with support for css variables)
- primaryColor (with support for css variables)
- secondaryColor (with support for css variables)
- poweredText

**Comment by nikkimk** [comment]
@michael-collins any chance we have https://github.com/elmsln/elmsln-logos/blob/master/elmsln-powered-sticker/powered-by-elmsln-sticker-3-1200-%402x.png as an AI or PSD somewhere?

**Comment by btopro** [comment]
#2425 thread just for presentational components. This was supposed to be for example purposes anyway and not needed
