### ISSUE TITLE
Shortcodes not working in Course Outline following v0.8.1 update

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2325]
Bug:
- v0.8.1

Can't get H5Ps or Images to show in the Course Outline using shortcodes if they have the following shortcode options:

- render=display_mode
- display_mode=image
- display_mode=h5p

For example the following shortcode will render
`[ciscode|rev=1|tool=elmsmedia|item=1765|entity_type=node]`

However, these won't:
`[ciscode|rev=1|tool=elmsmedia|item=1765|entity_type=node|render=display_mode|display_mode=image]`
`[ciscode|rev=1|tool=elmsmedia|item=2478|entity_type=node|render=display_mode|display_mode=h5p]`

**Comment by rickhumphries** [comment]
I'm also seeing a problem with the document shortcode, e.g.
`[ciscode|rev=1|tool=elmsmedia|item=1320|title=Student Handbook|entity_type=node|icon=pageview|render=link|field=field_document_file|text=Button with internal document shortcode link|target=_blank|delta=0]`

Previously this would open the document directly in a new tab but now it's just going straight to the node in Media. So we're getting lot's of students navigating to Media and potentially seeing things we don't want them to.

**Comment by rickhumphries** [comment]
I've tried reverting the following in the `CIS Tokens` feature but it stays 'Overridden'
![image](https://user-images.githubusercontent.com/4973810/32880949-66f42e3e-caa7-11e7-895a-5c966c140ab8.png)

Would this be affecting anything:
![image](https://user-images.githubusercontent.com/4973810/32880999-8faee512-caa7-11e7-9af3-7b262bf27304.png)

**Comment by rickhumphries** [comment]
Hmm, I've checked and this isn't happening on our dev server which has the same setup. Very strange. Might be a https setting that's related to just pulling information across the systems in general?

**Comment by rickhumphries** [comment]
Something else which might provide a clue, is that when I'm viewing the context of a course within CIS or Media i.e. online.xyz/Course101/ or media.xyz/Course101, the Course Outline button isn't appearing in the 'More Tools' menu or the Network menu at all. Almost as if they're not recognising each other

**Comment by btopro** [comment]
try: `leafy` option 13
`13) cycle service account connection passwords`

if that doesn't help; go to a course space, dig into drupal admin and enable a module called `cis_devel` it'll start printing log statements for every webservice connection that happens and could at minimum help point to what's going on there.

**Comment by rickhumphries** [comment]
OK, enabled `cis_devel`. Just looking and there's a common error that says
`Error initializing socket ssl://data.media.buttercupstraining.co.uk:443`

**Comment by btopro** [comment]
Hmm certigicate bad maybe?

**Comment by btopro** [comment]
Certificate rather. My phone says that address doesn't exist which reminds me this is an internally resolved address. Perhaps the etc/hosts on the server is goofed / doesn't have this record in it?

**Comment by rickhumphries** [comment]
Yeh also coming across this `Error initializing socket ssl://data.online.buttercupstraining.co.uk:443.` too. 

Just having a look

**Comment by btopro** [comment]
fixed up, unrelated to project (directly at least); deploy networking specific.
