### ISSUE TITLE
Performing Server-Level Updates 0.7 -> 0.8.1

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2326]
Hi quick question. We recently changed our server configuration so our site didn't crash all the time.

The settings we changed were on:

apache mod_expires
apache mpm_event
mpm_common and mpm_event settings
apache mod_status

We're wondering whether performing the server level upgrades through leafy might overwrite any of those settings? Is there any way of seeing the changes that it'll make etc.?

**Comment by btopro** [comment]
No we tend not to touch those sort of settings via that call. Server level would be like we have to edit the structure of your elmsln/config directory or mod permissions on something or create a user account

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/tree/master/scripts/upgrade/system between version upgrade scripts

**Comment by rickhumphries** [comment]
OK thanks - just ran it. It threw some errors, then I updated permissions and plugins etc. and it seems to have worked ok :)

**Comment by rickhumphries** [comment]
Just for reference, the errors that it threw were 

```
Error message
E_ERROR: Call to undefined function drupal_sanitize_options()

Sample stack trace
in sqlsync_drush_command called at /root/.composer/vendor/drush/drush/commands/sql/sqlsync.drush.inc (90)
in sqlsync_drush_command called at /usr/share/php/drush/includes/command.inc (975)
in drush_get_commands called at /usr/share/php/drush/includes/command.inc (1175)
in drush_parse_command called at /usr/share/php/drush/includes/drush.inc (1115)
in drush_preflight_command_dispatch called at /usr/share/php/drush/drush.php (59)
in drush_main called at /usr/share/php/drush/drush.php (16)
```

**Comment by btopro** [comment]
that can happen if there's a site that didn't bootstrap or something while that runs through. see it now and then mid updates but not frequent. thx for the report.
