### ISSUE TITLE
Can't add a new Course

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2329]
Bug: Can't add and propagate a new Course.

- ELMSLN version/commit reported on admin/reports/status
0.9.0 Drupal 7.56

- What happens
1. Confirmation emails about new Course arrives, along with "New release(s) available for COURSENAME"where link to the course looks like:  https://coursename/admin/reports/update/settings

2. Service instances stack at "almost there" ( #955 - related? ) 
![screenshot-2017-11-16-21-45-13-167](https://user-images.githubusercontent.com/273282/32914930-8660884c-cb17-11e7-9b9a-309c3535cd98.png)

3. " frontdeskv/service-instances" 404 appears in Drupal Watchdog

4. `/frontdeskv/service-instances?no-track Failed to load resource: the server responded with a status of 404 (Not Found)` appears in Developer Console

5. Soon after that another 2 appears:

`POST views/ajax net::ERR_CONNECTION_ABORTED`

and

` service-instances:1 Error in event handler for (unknown): TypeError: Cannot read property 'x' of undefined `

6. Bunch of stuff in /var/log/messages

`Nov 17 07:29:01  systemd: Created slice User Slice of ulmus.
Nov 17 07:29:01  systemd: Starting User Slice of ulmus.
Nov 17 07:29:01  systemd: Started Session 54771 of user ulmus.
Nov 17 07:29:01  systemd: Starting Session 54771 of user ulmus.
Nov 17 07:29:01  systemd: Created slice User Slice of ulmusdrush.
Nov 17 07:29:01  systemd: Starting User Slice of ulmusdrush.
Nov 17 07:29:01  systemd: Started Session 54772 of user ulmusdrush.
Nov 17 07:29:01  systemd: Starting Session 54772 of user ulmusdrush.
Nov 17 07:29:01  systemd: Removed slice User Slice of ulmusdrush.
Nov 17 07:29:01  systemd: Stopping User Slice of ulmusdrush.
Nov 17 07:29:02  systemd: Removed slice User Slice of ulmus.
Nov 17 07:29:02  systemd: Stopping User Slice of ulmus.
Nov 17 07:30:01  systemd: Started Session 54773 of user root.
Nov 17 07:30:01  systemd: Starting Session 54773 of user root.
Nov 17 07:30:01  systemd: Created slice User Slice of nobody.
Nov 17 07:30:01  systemd: Starting User Slice of nobody.
Nov 17 07:30:01  systemd: Started Session 54774 of user nobody.
Nov 17 07:30:01  systemd: Starting Session 54774 of user nobody.
Nov 17 07:30:01  systemd: Created slice User Slice of ulmusdrush.
Nov 17 07:30:01  systemd: Starting User Slice of ulmusdrush.
Nov 17 07:30:01  systemd: Started Session 54775 of user ulmusdrush.
Nov 17 07:30:01  systemd: Starting Session 54775 of user ulmusdrush.
Nov 17 07:30:01  systemd: Created slice User Slice of ulmus.
Nov 17 07:30:01  systemd: Starting User Slice of ulmus.
Nov 17 07:30:01  systemd: Started Session 54776 of user ulmus.
Nov 17 07:30:01  systemd: Starting Session 54776 of user ulmus.
Nov 17 07:30:01  systemd: Removed slice User Slice of ulmusdrush.
Nov 17 07:30:01  systemd: Stopping User Slice of ulmusdrush.
Nov 17 07:30:01  systemd: Removed slice User Slice of ulmus.
Nov 17 07:30:01  systemd: Stopping User Slice of ulmus.`

- What you expected to happen
I'd like to get here https://youtu.be/5xNXOPfPHlA?t=7m16s

**Comment by btopro** [comment]
hmm... what OS did you deploy on? Does a courses.whatever domain exist? The email generation means that a drupal site installed though I realize something else is obviously goofed here.  Do you have certs for this (https) or no? That can also cause some issues in setup initially.

**Comment by yurg** [comment]
Thank you for your reply! It is CentOS from #2137 with the latest upgrades to 0.9.0 mentioned in #2307 and we ain't got none https certificate(s).

**Comment by btopro** [comment]
hmm... give this a try to do some debugging:
on the online site. Enable the module `cis_devel` at `/admin/modules` and try to go to a course page like `/frontdeskv`. You should see a bunch of debug messages. click to expand them and see if there's anything out of order. @rickhumphries recently went through some of this w/ network level debugging.

Another way to tell if the network connections are goofed is if your on a course page in CIS if you don't see links across the top left w/ icons then it could be that. Anyway, let me know what's in the debug output cause that could give some clues as to what's up.

The 'Almost there...' is indicative of a network level thing as well since that's it testing the call home to set a value for using later.

**Comment by yurg** [comment]
Thank you, indeed `cis_devel` prints `php_network_getaddresses: getaddrinfo failed: Name or service not known` , yet I'm not really sure where to move from here. Please advice!

**Comment by btopro** [comment]
does that address exist cause that sound like that path isn't real?

**Comment by yurg** [comment]
yep, I substituted a real domain name by "domain.tld", yet it works and accessible by name via web.

**Comment by btopro** [comment]
gotcha. if you log into the server and do a `wget {address}` where `{address}` is all that you just copy and pasted what happens? sounds like the box isn't resolving that domain

**Comment by btopro** [comment]
`cat /var/www/elmsln/config/logs/drush-create-site.log`

**Comment by yurg** [comment]
There is nothing fancy there, I'm afraid:

`
/var/www/elmsln/core/dslmcode/stacks/courses ownership of ‘/var/www/elmsln/core/dslmcode/stacks/courses/sites/courses/ml/test333/files/feeds’ retained as apache:elmsln
mode of ‘/var/www/elmsln/core/dslmcode/stacks/courses/sites/courses/ml/test333/files/feeds’ changed from 0755 (rwxr-xr-x) to 0774 (rwxrwxr--)
requester equals admin
mkdir: created directory ‘/var/www/elmsln/config/private_files/courses/test333’
mkdir: created directory ‘/var/www/elmsln/config/private_files/courses/test333/feeds’
mode of ‘/var/www/elmsln/config/private_files/courses/test333’ changed from 2755 (rwxr-sr-x) to 2774 (rwxrwsr--)
mode of ‘/var/www/elmsln/config/private_files/courses/test333/feeds’ changed from 2755 (rwxr-sr-x) to 2774 (rwxrwsr--)
Succesfully cached all content!
test333 was added to courses.domain.tld on 2017-11-28_09:54:01
`

**Comment by yurg** [comment]
There is something else though  in Devel output at online.domain.tld:
 **Error initializing socket ssl://data-online.domain.tld:443.**

Have got an email regarding security updates at  http://**test333**/admin/updates/ , which leads me to believe there is an issue with subdomain creation at new course creation: status messages should contain root domain name, like this: http://test333.domain.tld, not just http://test333 
Still, no idea where to start. 

I've played with switch to HTTPS aat live site and, guess, omitted some domains in certbot. Oh, by the way, what is the purpose of **data-xxx** domain(s)?

**Comment by btopro** [comment]
Yeah if the data- variants arn't in your cert setup it could cause this issue. There is a work around for it involving editing /var/www/elmsln/config/scripts/drush-create-site/config.cfg and adding a line that backend protocol is http. I'm mobile atm, let me respond in full shortly

**Comment by btopro** [comment]
![2017-11-28_09-37-00](https://user-images.githubusercontent.com/329735/33325238-b45fe790-d41f-11e7-85b9-2a10cc179f93.png)

**Comment by btopro** [comment]
@yurg try this - edit `/var/www/elmsln/config/scripts/drush-create-site/config.cfg` and then add the following to the file: `dataprotocol='http'`

This will tell data addresses to use http so they don't have to have certs.

To your question of 'what are the data- domains' :
When ELMS:LN calls out to other services, it issues these calls on a 'back channel' of sorts. This allows for increased security by having domains that aren't the ones that everyone accesses to issue the calls. These can also then be wrapped inward via /etc/hosts rewriting. It also helps ensure that pure data calls and end-user delivered webpages happen on different addresses yet access the same database.

There are super-user web service accounts which only operate on the `data-` domains for things like "What tools does this section have" or for when the system syncs up its data model between services like CIS telling media what courses exist or that a new one was added.

**Comment by btopro** [comment]
If this works / makes sense and our documentation needs updated please issue a PR against the related docs - https://github.com/elmsln/elmsln/tree/master/docs

https://elmsln.readthedocs.io/en/latest/

**Comment by yurg** [comment]
Thanks for detailed info! Sure, will update docs as soon as I follow this path till the end :-)

**Comment by yurg** [comment]
**var/www/elmsln/config/scripts/drush-create-site/config.cfg**  looks exactly like 
> serviceprefix='data-'
> #protocol to use for front-facing calls
> protocol='https'
> #protocol to use for backend calls
> dataprotocol='http'

Yet after drush cc / rr / cron it complains regarding 

**Error initializing socket ssl://data-online.mlc.domain.tld:443.**

_What? Can I doooo?_

**Comment by yurg** [comment]
##########

cat /etc/httpd/conf.sites.d/online.conf
NameVirtualHost *:80
<VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/online
    ServerName online.domain.tld
  **ServerAlias data-online.domain.tld**  #>> _Perhaps, the problem is here_ 

RewriteEngine on
RewriteCond %{SERVER_NAME} =**data-online.domain.tld** [OR] # _and\or here_
RewriteCond %{SERVER_NAME} =online.domain.tld
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<Directory /var/www/elmsln/domains/online>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>

**Comment by yurg** [comment]
It seems it is; after commenting out **data-** entries, no errors in Devel. Going to test it further.

**Comment by btopro** [comment]
closing, moving this on to the spun off issues
