### ISSUE TITLE
Tracking a document click

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2330]
ELMSLN v0.8.1

I'm trying to track the clicking of a document link. The document link is a shortcode back to the document in Media, e.g.

[ciscode|rev=1|tool=elmsmedia|item=1901|title=Document Title|entity_type=node|icon=pageview|render=link|field=field_document_file|text=Download Document|target=_blank|delta=0]

I've tried changing the TinCanAPI settings in both the Course and Media to 'track external links' and added the pdf extension too, but can't seem to get it to register.

I just wondered if any other xAPI enthusiasts out there are tracking this too and have managed to get it set up?

Cheers

**Comment by btopro** [comment]
do you have `Track file extensions` set to be tracking external links to pdfs n the course site itself?

**Comment by rickhumphries** [comment]
Yeh I've got the following setup on both Media and the course itself:

![image](https://user-images.githubusercontent.com/4973810/32979800-b8fe42b6-cc53-11e7-9529-8ed839ddfe99.png)

**Comment by btopro** [comment]
hmmm... it should be tracking it then...

**Comment by rickhumphries** [comment]
Just found that if I switch the Function used to `tincanapi (default)` from `elmsln (nonblocking)` then this starts to work.

Perhaps this has been fixed in 0.9.0?

**Comment by btopro** [comment]
hmm.... possibly... or it could be that your server doesn't like the non-block method for call outs on this. what site did you change this on to make it work? the non-block variant is WAY more performance optimized (which is why it uses it or is supposed to).

**Comment by rickhumphries** [comment]
I changed it on a `courses.blah/course` site so it's only using that function for the one course I need it to.  Wonder if it's related to the http/https data thing?

**Comment by btopro** [comment]
also possible. does the pathway to the learning locker instance actually exist? Probably a settings file that defines how to talk to the LRS which may need an additional setting or something to avoid that aspect (again, maybe)

**Comment by btopro** [comment]
Closing as a resolution was found; if this happens again (since we improved stuff surrounding these functions since then and we're talking 3 releases ago) then reopen to explore further
