### ISSUE TITLE
Roster Sync to Media/Interact

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2331]
v0.8.1

I feel like this is potentially an internal deploy specific thing but I remember having a conversation on Slack about how roster syncing to Media/Interact is **not** required from this version forward, and there is a performance gain associated with that.

I've checked the logic of this by deleting a student account from Media, then logging into the course, and H5P activities show and are being tracked in Learning Locker, so that all works.

However, I've noticed that our roster sync is still syncing user accounts to Media/Interact (which is a lot of people) on our live site. This doesn't happen on our dev site though curiously enough. 

Is there anything we can check to try and prevent this sync taking place as I feel like this will take a bit of pressure off the server during the nightly cron run.

Thanks

**Comment by btopro** [comment]
This happens in 0.9.0 #2047. It isn't required and the data model was tweaked slightly to account for it. It should still sync without dying but I started to realize it was a bit heavy needlessly. If it becomes an issue you can probably backport just those commits.

**Comment by btopro** [comment]
if you end up needing that it might be a reason to review what's so bad about what's in 0.9.0 that you can't roll that ;)

**Comment by rickhumphries** [comment]
Ah I see. Thought this was rolled out in 0.8.1. Ok cool. 

Yeh 0.9.0 just needs more testing for us, particularly on Internet Explorer. Checked stats yesterday and we have 20% using that browser so that's a good chunk of people.

**Comment by btopro** [comment]
#2281 could be a good place for @JackWillDavis to issue PRs against to get the few box model issues cleaned up. I think in the future we'll also have a tag around the body field that's generated on demand so that locally scoped CSS can easily be injected into it for a lot of the style overrides your currently doing (We do some of that too though much less :))
