### ISSUE TITLE
New services not hooking into bakery

### ISSUE THREAD

**Issue by lifelike99** [elmsln/elmsln#2334]
0.9.0 ELMSLN 

When I create new courses they do not automatically hook into bakery. After creating a new course I followed these steps:

-perform @courses.coursename uli for a one off login

-noticed bakery module not turned on so enable it

-After enabling bakery module I receive the following message: 
messageWarning: rmdir(/var/www/elmsln/config/private_files/courses/mlctest/print_pdf/cache): Permission denied in drupal_rmdir() (line 2472 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/file.inc).

-After this I am able to access the new service with SSO

**Comment by btopro** [comment]
hm ok.. can you check and see if elmsln_bakery is enabled? Also might want to run leafy on the command line and correct permissions (6).

also can you look in `/var/www/elmsln/config/jobs/` and cat one of the files in there to see if the drush statement mentions elmsln_bakery?

**Comment by lifelike99** [comment]
It is enabled on online & people but not enabled on new services until I enable it. Looking at the drush commands for one of the new courses it mentions elmsln_bakery.

**Comment by lifelike99** [comment]
Ran the leafy command as well but no luck, new services are still not hooked into bakery.

**Comment by lifelike99** [comment]
So i think it's an overall bakery issue, changing permissions for a user at people.domain does not filter through to online.domain, neither do password changes.

**Comment by btopro** [comment]
do all the domains in question actually exist?

**Comment by btopro** [comment]
http or https or is this running in local VM? @rickhumphries did you have to do anything different to your knowledge for it to work on https?

**Comment by lifelike99** [comment]
Domains definitely exist, http.

**Comment by btopro** [comment]
If you look at the command in the service file are you able to run that drush call but against the site created? Sounds like a dependency issue causing that call not to go through cause elmsln_bakery will get enabled everywhere and auto configure bakery, or at least is supposed to

**Comment by lifelike99** [comment]
I can call the drush command against the site created and it seems to work, however only the admin account seems to be able to successfully access created services, even if i create an open course.

**Comment by btopro** [comment]
What install method / OS did you use? it's like it's skipping that part of the file. check the log file for the drush-create-site script via the following:

`cat /var/www/elmsln/config/logs/drush-create-site.log`

see if there's anything in there that looks like an error related to building the site. Also look in `cd /var/www/elmsln/config/jobs` for files related to the machine name of the site, possibly w/ the word error in them. (like sing100.courses.2017-01-10__error sorta thing)

**Comment by lifelike99** [comment]
There are nor error files in jobs for the courses I have created. Here is the 'drush-create-site.log' output for the latest test course I created. Changed my domain to 'courses.domain'. 

/var/www/elmsln/core/dslmcode/stacks/courses
ownership of ‘/var/www/elmsln/core/dslmcode/stacks/courses/sites/courses/ml/test121/files/feeds’ retained as apache:elmsln
mode of ‘/var/www/elmsln/core/dslmcode/stacks/courses/sites/courses/ml/test121/files/feeds’ changed from 0755 (rwxr-xr-x) to 0774 (rwxrwxr--)
requester equals admin
mkdir: created directory ‘/var/www/elmsln/config/private_files/courses/test121’
mkdir: created directory ‘/var/www/elmsln/config/private_files/courses/test121/feeds’
mode of ‘/var/www/elmsln/config/private_files/courses/test121’ changed from 2755 (rwxr-sr-x) to 2774 (rwxrwsr--)
mode of ‘/var/www/elmsln/config/private_files/courses/test121/feeds’ changed from 2755 (rwxr-sr-x) to 2774 (rwxrwsr--)
Succesfully cached all content!
test121 was added to courses.domain.com2017-11-21_15:13:01

**Comment by btopro** [comment]
haven't experienced this then if the job isn't claiming to have an issue. What OS did you install with?

**Comment by btopro** [comment]
have you tried doing a /etc/hosts loop back? Sounds like it migth be something odd w/ your domains, etc. For example I did this recently on another deploy having some weird connectivity issues and it helped.
(substitute for your domain obviously)
```
# elmsln loop back
127.0.0.1 openulmus.org

127.0.0.1 data-online.openulmus.org
127.0.0.1 data-media.openulmus.org
127.0.0.1 data-courses.openulmus.org
127.0.0.1 data-studio.openulmus.org
127.0.0.1 data-blogs.openulmus.org
127.0.0.1 data-discuss.openulmus.org
127.0.0.1 data-interact.openulmus.org
127.0.0.1 data-people.openulmus.org

127.0.0.1 online.openulmus.org
127.0.0.1 media.openulmus.org
127.0.0.1 courses.openulmus.org
127.0.0.1 studio.openulmus.org
127.0.0.1 blogs.openulmus.org
127.0.0.1 discuss.openulmus.org
127.0.0.1 interact.openulmus.org
127.0.0.1 people.openulmus.org
```

This tells your server to call local when asking for those addresses. Not sure if it'll help but possible; we've done it on some other setups before that don't have wild cards correct / all address defined or using proxies / cloudflare sorta gigs.

**Comment by btopro** [comment]
spun off issue that's more detailed as to the issue at hand
