### ISSUE TITLE
E_ERROR: Call to undefined function drush_cache_get()

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2338]
v0.8.1

Got the following error in the logs during a cron run and wondered if it's anything to be worried about:

Error message
E_ERROR: Call to undefined function drush_cache_get()

Stack trace
…lises_build called at /var/www/elmsln/scripts/drush/local/generate_aliases.php (21)
…build called at /var/www/elmsln/scripts/drush/local/
elmsln.aliases.drushrc.php (11)

**Comment by btopro** [comment]
nope. probably means there's a site in your sites.php that isn't real. If your not sure where it is, try the following it to hunt it down:

`d @elmsln pm-info elmsln_core --y`

That'll ask every site the status of elmsln_core. If a site errors or says that's not enabled that's a clue to where the culprit.


This is basically something only possible for those of us prior to stabilization (aka me and you) of some of the under the hood setup request stuff.
