### ISSUE TITLE
Error Editing Course in CIS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2339]
v0.8.1

I'm trying to edit some course details in the CIS and I'm getting the error shown below
This seems to only happen with courses that existed before upgrading to 0.8.1. I've set one up since and I'm able to edit/save this course node.

```
Error message
Exception: Uncaught exception 'Exception' with message 'The host entity cannot be changed.' in /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/field_collection/field_collection.entity.inc:250

Stack trace
in FieldCollectionItemEntity::updateHostEntity called at /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/field_collection/field_collection.module (579)
in field_collection_field_update called at /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/field/field.attach.inc (209)
in _field_invoke called at /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/field/field.attach.inc (991)
in field_attach_update called at /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/node/node.module (1178)
in node_save called at /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/node/node.pages.inc (459)
in node_form_submit called at /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/form.inc (1520)
in form_execute_handlers called at /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/form.inc (904)
in drupal_process_form called at /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/form.inc (386)
in drupal_build_form called at /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/form.inc (131)
in drupal_get_form called at /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/node/node.pages.inc (14)
in node_page_edit called at ? (?)
in call_user_func_array called at /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/menu.inc (527)
…ctive_handler called at /var/www/elmsln/core/dslmcode/cores/drupal-7/index.php (22)
```

**Comment by btopro** [comment]
see if it has sections / offerings. I don't think you use this concept (right?). Do you know specifically which course it is? There's something with some early on created courses where this can happen. I've resolved it by just hitting edit on the sections / offerings and resaving them (i think).

**Comment by rickhumphries** [comment]
Yeh we do use sections - all the courses have them. I've got a bunch of courses that I've tested this on with some being created early on, some created on v0.7.0 etc. Seems to be just the one created on the current version that doesn't do it. I'll try an edit/save on the sections and see if it affects anything

**Comment by btopro** [comment]
it's thanksgiving so I'll be traveling but DM me a course to check and I'll see if it's the same issue that I had at one time (if that didn't work). I do recall now having this happen on my deploy once and only on like 2 courses and I think that's how I resolved it. (If I had a time machine, I'd get rid of field collections :p)

**Comment by btopro** [comment]
edge cases where this was possible; patch appears to fix this
