### ISSUE TITLE
Feature request - non time-based section control

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#234]
Our courses are open for a non-definite period of time and we accept students onto them on a continual basis - so it's rolling enrolment. 

As such we don't determine whether a student has completed a course based on a time period. The information for this currently resides in an external database instead (which could be queried). So each student will have a 'course_status' field with either 'in progress', 'withdrawn' or 'completed' as a value.

It would be nice to be able to use an external field such as this to determine whether the student's role should switch to 'past student' rather than 'student'. Maybe this kind of field would link in with data held in CPR..?

**Comment by btopro** [comment]
I think if we abstracted the part the currently checks dates and made a function that could evaluate if the account / section should deactivate this would allow custom checks like this. Might be best to wait til we get cpr a little further along since it'll act as the hook up for user data.

**Comment by btopro** [comment]
Do you still need this?

**Comment by rickhumphries** [comment]
Yeh I reckon this'd still be useful.

**Comment by btopro** [comment]
this should now be supported because if dates aren't defined when it goes to sync it'll just sync whatever the hooks to pull in users define
