### ISSUE TITLE
Open Studio/Assignment Studio

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#2342]
Wish List from Faculty:

Sorting Comments - the ability to see, in a list,  who posted what, when, and where.  It would be nice to have this view per assignment and for all assignments.

**Comment by btopro** [comment]
@Deb-G has requested that we replace Canvas with a good system. Got it. ;)

**Comment by Deb-G** [comment]
We just need the ability to make private submissions to the open studio/assignment studio.  I know that this is already an option, but after talking with you,  it sounds like we need a more intuitive interface to distinguish between the two.  :-)

**Comment by btopro** [comment]
related #2260
