### ISSUE TITLE
User created by UID#1 can't log in

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2344]
Perhaps it is a follow up of #2329 

System: 0.9.0 Drupal 7.56

In order to test new Course creation, I've add a new User with Staff role via online.domain.tld, assuming this is a central place of adding anything, incl. stuff. 

Being logged as Drupal User 1 I can see new user in accounts list, user status is active and Role is Stuff.
Intentionally login and password were set as simple as possible. 

Using a whole new browser (not a new tab, new browser) navigate to online.domain.tld/user  and enter  fresh login and password.

Have got "Sorry, unrecognised login / password" (??!!) 
   
Drupal Watchdog report is perfectly empty, the last record is about successful user creation. Remember I've said about intentionally simple login & password? Right, it's just to be absolutely sure there is no mistakes at this step. 

Please advice.

**Comment by btopro** [comment]
If you add a user to online.domain.tld it'll only add the user there; this is a drupal thing. If you want a user to show up everywhere, right now there's the comply.domain.tld system. This has the ability to add admin / staff level accounts globally, across multiple systems.

We get users into elmsln through a few mechanisms:
- Sections have a access string / primary key of sorts which is used for querying a data source for a roster of users and passing them around that course / things they should have access to.
- user file upload in online.domain.tld which is a csv import and passes users to the right place (by making a section more or less w/ a file hash as the key)
- comply for one-off additions
- custom integrations for user accounts (Buttercups does this using the api's baked in)

We absolutely need UI clean up / love here so that CIS / online is able to orchestrate user accounts and other info.

**Comment by yurg** [comment]
Thank you for the clue! So it's Comply.. not even People, as many of us would have guessed.. This bit is definitely worth adding somewhere into Documentation section, wish it was there yesterday.

**Comment by yurg** [comment]
As a side note: why wouldn't redirect everything.tld/user  to a comply/user? Silly question, yet if there is a single entry point for users to be created / synched, a previous Drupal experience can be very confusing.

**Comment by yurg** [comment]
re: comply. Have just added a new account, thinking it gets propagated across the system; no way. 
But, trying to reach comply/user, have got this wonderful message:

`
    Your user account on comply appears to have problems. Would you like to try to repair it yourself?
    Otherwise you can contact the site administrators.
`

and 

`
Repair account
An account with a matching email address was found. Repairing it will reset the username to match your master account. If this is the correct account, please enter your comply password.
`

I give up, totally confused.  What happens if I proceed to repair? I have just deleted all test accounts "with the same  email address" from _online_ and _people_, how does _comply_ know there were  accounts with the same email? Questions, questions..

**Comment by yurg** [comment]
Well, repair allowed. Can login to comply; yet it is not possible to login to _online_ with same credentials, system doesn't recognize the account. Comply contains list of courses I can see but can't add new or modify an existent. All I was trying to do is make an account which is able to create a Course. 

_Feel myself like in a voice recognition elevator. **"Scotland!! Freedom!!"** &copy;_

**Comment by btopro** [comment]
Absolutely on the documentation / need for UX unification in these areas. This used to be a skeleton crew and is evolving into a larger developer community so thank you for bearing with us and offering feedback. The username and email has to match everywhere for Bakery to work correctly. Honestly though, Bakery is a baseline mechanism; the productions deploys at Penn State don't use Bakery so that's part of where the confusion comes in (WVU is using CAS for example; we use a webserverauth based solution). This is not an excuse, just reality as to why docs are less-so in this area.

A staff account that's in all systems will be able to accomplish what you are saying (usanother user account that can make a course). Because this is a lot of drupal at it's core you can also cheat on commands via drush. For example, comply is just issuing structured drush calls against the other systems.
```
drush @elmsln ucrt username --mail=email@address.com --y
drush @elmsln urol administrator username --y
```
should make the staff user account everywhere.

This was made by hard-core drush / drupal devs so bare in mind the UX is heavily invested in power user, instructors (content contributors more or less) and students (content viewer); all the middle squishy stuff beyond simple content creation into more of the staff / orchestration of the system role (admin-esk) can the UX can suffer (as you've found).

Hope this helps, please let us know how we can improve our documentation or what a UI dashboard to manage this stuff would look like.

**Comment by yurg** [comment]
Thank you for your help;  a quick note regarding 
> drush @elmsln urol administrator username --y

Apart from a prev. command  (drush @elmsln ucrt username --mail=email@address.com --y), which gives simple "User already exists" in console, this one throws an Exception:

`
elmsln.comply.ml          >> exception 'Drush\User\UserListException'[error]
with message 'Unable to find a matching user for Courserer.' in
/root/.config/composer/vendor/drush/drush/lib/Drush/User/UserList.php:114
Stack trace:
#0
/root/.config/composer/vendor/drush/drush/lib/Drush/User/UserList.php(15):
Drush\User\UserList::getFromParameters('Courserer')
#1
/root/.config/composer/vendor/drush/drush/commands/user/user.drush.inc(283):
Drush\User\UserList->__construct('Courserer')
#2 [internal function]: drush_user_add_role('administrator',
'Courserer')
#3
/root/.config/composer/vendor/drush/drush/includes/command.inc(361):
call_user_func_array('drush_user_add_...', Array)
#4
/root/.config/composer/vendor/drush/drush/includes/command.inc(212):
_drush_invoke_hooks(Array, Array)
#5 [internal function]: drush_command('administrator', 'Courserer')
#6
/root/.config/composer/vendor/drush/drush/includes/command.inc(180):
call_user_func_array('drush_command', Array)
#7
/root/.config/composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64):
drush_dispatch(Array)
#8 /root/.config/composer/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 /root/.config/composer/vendor/drush/drush/drush.php(11):
drush_main()
#10 {main}
`

**Comment by yurg** [comment]
Next byte: new user creates a Course named "Art of ELMSLN" 
![capture](https://user-images.githubusercontent.com/273282/33390549-8c6e3c38-d536-11e7-8484-09f371435fb3.PNG)

Confirmation email arrived with link to a newly created course https://studio/artofelmsl/ yet attempts to access the page (and a second one, https:.//courses/artofelmsln) give "Access denied, please log into your account." both for Drupal user 1 and for user who has created the course. 
https://online/artofelmsl/service-instances page shows nice "Waiting for server" circling snowfall animation for 10 minutes minimum. which pretty much seems to be forever.

**Comment by yurg** [comment]
And the same old email(s) with wrong paths  is here: 

`There are security updates available for one or more of your modules or
themes. To ensure the security of your server, you should update immediately!
See the available updates page for more information:`
http://artofelmsl/admin/reports/updates

**Comment by btopro** [comment]
custom user roles are not supported. If you want to add them your welcome to but realize that globally we only support the ones that come out of the box. If you have a `Courserer` role it will then only exist in the system you place it in and it would need globally added via features or whatever method of getting it out there.

If your looking for someone to do something specifically in CIS and want to make that role then I'd make that role just in CIS but grant the user a staff role everywhere else or something.

**Comment by btopro** [comment]
if it's still waiting for the server there's something else happening like a build failing to create. What OS is this?

**Comment by yurg** [comment]
And form another angle: 


cat /var/log/messages
..thousands of  Slice Create/Use
Nov 30 05:08:01 ticket-fruit systemd: Stopping User Slice of ulmusdrush.
Nov 30 05:08:01 ticket-fruit systemd: Removed slice User Slice of ulmus.
Nov 30 05:08:01 ticket-fruit systemd: Stopping User Slice of ulmus.
Nov 30 05:08:32 ticket-fruit dhclient[722]: DHCPREQUEST on eth0 to SOME.IP.ADD.RESS port 67 (xid=0x52df84c)
Nov 30 05:08:32 ticket-fruit dhclient[722]: DHCPACK from SOME.IP.ADD.RESS (xid=0x52df84c)
Nov 30 05:08:34 ticket-fruit dhclient[722]: bound to ANOTHER.IP.ADD.RESS -- renewal in 254 seconds.
Nov 30 05:09:01 ticket-fruit systemd: Created slice User Slice of ulmusdrush.
Nov 30 05:09:01 ticket-fruit systemd: Starting User Slice of ulmusdrush.
... another hundred of Slice Create/Use

**Comment by btopro** [comment]
I have no idea what `Slice Create/Use` is; what OS is this?

**Comment by yurg** [comment]
It is the same CentOS from my initial issue #2137
Have just realised, struggling it from August and still not even close to see it working..

**Comment by yurg** [comment]
Also #2184 has an extended version of previous attempts to make it work.

**Comment by btopro** [comment]
ok. Well, I'm sorry your having so many issues with this but we don't have these issues in our locals or production builds to this extent so I'm not sure how to help. @rickhumphries or @mmilutinovic1313 may have a better idea based on managing a Bakery based deploy but those are at least things that can be resolved with some custom Drupal code invoking hooks.

We also run Ubuntu16 in vagrant locally all the time so while it shouldn't be an issue we just haven't used Cent as much in day to day usage.

**Comment by mmilutinovic1313** [comment]
I ran something like this to fix login issues on my box. 
```
drush @courses user-create DRUPALUSERNAME --mail="EXAMPLE@example.com" --password="EXAMPLEPASSWORD"; drush @courses user-add-role "administrator" DRUPALUSERNAME
```
After this run `leafy` and choose option `6` to flush permissions. This worked for me.

**Comment by btopro** [comment]
might be `@courses-all`

**Comment by yurg** [comment]
@btopro HI Bryan, thank you for all your help, sorry for bothering you. Still, I want to make it work. 
What if we start simple and see where it leads us?
So, isolated situation (issue): 

1. User was created with "Staff" Role; the purpose is, this user will create Courses. 
2. We used Drush and Leafy for setting up the user and clear permissions
3. We enabled "elmsln_devel" module to see what happens.
4. Newly created user navigates to online.domain.tld 

Devel/Krumo output warns us about: 
  a. Request to http://SERVICE_CIS_ML:6ef73ffe7ec91e6d7e073b1a23d554@data-
   online.domain.tld/field_collection_item.json?field_access_string=master&archived=0   via socket  tcp://data-online.domain.tld:80
  b. Response is 404 Error: not found
  c.  Same for http://SERVICE_CIS_ML:6ef73ffe7ec91e6d7e073b1a23d554@data-online.domain.tld/node.json?type=resource&field_machine_name=footer_language

And exactly the same output echoes at Course Creation page after system creates the course. In addition, Course Creation status hangs on "Waiting For Server".   

My guess is, may be these .JSON files system can't find results in Course not being created. What do you think?

**Comment by btopro** [comment]
@yurg so the "socket tcp:" part suggests there's a networking issue on the box unrelated to elmsln.

Have you tried putting in the "loop back" I pointed to here -- https://github.com/elmsln/elmsln/issues/2334#issuecomment-347900982

replacing openulmus.org w/ your own domain obviously.

This would go in the `/etc/hosts` file on the server itself as opposed to your local machine. This tells the server to reroute calls to those addresses to localhost and should skip networking issues of this kind.


also could try running `sudo service networking restart` but that's a shot in the dark if it'll do anything (works sometimes in Vagrant when server gets corrupted during a shut down but isn't normal for sure)

**Comment by yurg** [comment]
@btopro Thank you for the hint: doesn't seem to work, yet has lead me to the next step which might be relevant. So:

**http**://**data-online.domain.tld**/field_collection_item.json doesn't exist, but

**https**://**online.mlc.org.au**/field_collection_item.json and 
**https**://data-online.mlc.org.au/field_collection_item.json
do exist

Next step: 
https://online.domain.tld/field_collection_item.json?field_access_string=master&archived=0
and
https://data-online.domain.tld/field_collection_item.json?field_access_string=master&archived=0
return the same: 

`
{
  "self": "https://online.domain.tld/field_collection_item?field_access_string=master&archived=0",
  "first": "https://online.domain.tld/field_collection_item?field_access_string=master&archived=0&page=0",
  "last": "https://online.domain.tld/field_collection_item?field_access_string=master&archived=0&page=0",
  "list": []
}
`

while https://data-online.domain.tld/field_collection_item.json

returns 

`
{
  "self": "https://online.domain.tld/field_collection_item",
  "first": "https://online.domain.tld/field_collection_item?page=0",
  "last": "https://online.domain.tld/field_collection_item?page=0",
  "list": [
    {
      "field_access_dates": [],
      "field_access_string": [
        "f2"
      ],
      "field_campus": "ca",
      "field_cis_ops": null,
      "field_contact_info": [],
      "field_course_archive": [],
      "field_course_start": null,
      "field_instructor_of_record": {
        "uri": "https://online.domain.tld/user/1",
        "id": "1",
        "resource": "user",
        "uuid": "22e97562-4460-45e0-a3a0-d33e96be0a85"
      },
      "field_resources": [],
      "field_schedule_number": null,
      "field_section_number": "",
      "field_services": [
        {
          "uri": "https://online.domain.tld/node/3",
          "id": "3",
          "resource": "node",
          "uuid": "33fe1d09-daed-4a50-bc7a-ca6a0947e0a1"
        },
        {
          "uri": "https://online.domain.tld/node/4",
          "id": "4",
          "resource": "node",
          "uuid": "70ac0d27-5872-47d6-8164-226e77760235"
        },
        {
          "uri": "https://online.domain.tld/node/2",
          "id": "2",
          "resource": "node",
          "uuid": "305896ac-4569-4650-8e98-dc56dec9cc28"
        }
      ],
      "field_syllabus": [],
      "field_teaching_assistants": [],
      "field_welcome_letter": [],
      "field_welcome_page": [],
      "item_id": "6",
      "revision_id": "12",
      "field_name": "field_sections",
      "archived": "0",
      "uuid": "322d31ca-59da-44f8-a643-69ea00d8a8ef",
      "url": "https://online.domain.tld/field-collection/field-sections/6"
    },
    {
      "field_sections": [
        {
          "uri": "https://online.domain.tld/field_collection_item/8",
          "id": "8",
          "resource": "field_collection_item",
          "uuid": "d78221fd-9aa5-4418-af4d-aa7b4079a889"
        }
      ],
      "field_semester": "sp",
      "field_year": "201516",
      "item_id": "7",
      "revision_id": "13",
      "field_name": "field_offerings",
      "archived": "0",
      "uuid": "5af12394-2f1d-471f-b83a-3a09393ffcd4",
      "url": "https://online.domain.tld/field-collection/field-offerings/7",
      "host_entity": {
        "uri": "https://online.domain.tld/node/101",
        "id": "101",
        "resource": "node",
        "uuid": "d6ba7d50-f6ee-409a-abc6-21ac45dc2d5f"
      }
    },
    {
      "field_access_dates": {
        "value": "1349236800",
        "value2": "1359608400",
        "duration": 10371600
      },
      "field_access_string": [],
      "field_campus": null,
      "field_cis_ops": null,
      "field_contact_info": [],
      "field_course_archive": [],
      "field_course_start": null,
      "field_resources": [],
      "field_schedule_number": null,
      "field_section_number": null,
      "field_services": [
        {
          "uri": "https://online.domain.tld/node/4",
          "id": "4",
          "resource": "node",
          "uuid": "70ac0d27-5872-47d6-8164-226e77760235"
        }
      ],
      "field_syllabus": [],
      "field_teaching_assistants": [],
      "field_welcome_letter": [],
      "field_welcome_page": [],
      "item_id": "8",
      "revision_id": "14",
      "field_name": "field_sections",
      "archived": "0",
      "uuid": "d78221fd-9aa5-4418-af4d-aa7b4079a889",
      "url": "https://online.domain.tld/field-collection/field-sections/8",
      "host_entity": {
        "uri": "https://online.domain.tld/field_collection_item/7",
        "id": "7",
        "resource": "field_collection_item",
        "uuid": "5af12394-2f1d-471f-b83a-3a09393ffcd4"
      }
    }
  ]
}
`

Any chance there is something we can grab a clue for the next step(s) ?

**Comment by btopro** [comment]
OOOOO your very close I think.

OK, so the apache settings associated w/ the address are goofed.

/etc/httpd/conf.d and look for either elmsln.conf or elmsln-ssl.conf; something like that.

Basically you installed with https BUT your cert doesn't cover the `data-` sub-domains.

So in your config you placed the thing saying "hey use http for the backend stuff" BUT you don't have apache configured to handle that. This is why if you go to `http://data-online.domain.tld/` in a browser you'll see the ELMS:LN Installation screen mini-site which means it didn't find a match for the domain.

SO, you need to make like a conf file like this:

/etc/httpd/conf.d/data-domains.conf

```
NameVirtualHost *:80
<VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/online
    ServerAlias data-online.domain.tld
</VirtualHost>

<Directory /var/www/elmsln/domains/online>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>
<VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/people
    ServerAlias data-people.domain.tld
</VirtualHost>

<Directory /var/www/elmsln/domains/people>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>
<VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/courses
    ServerAlias data-courses.domain.tld
</VirtualHost>

<Directory /var/www/elmsln/domains/courses>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>
<VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/studio
    ServerAlias data-studio.domain.tld
</VirtualHost>

<Directory /var/www/elmsln/domains/studio>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>
<VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/media
    ServerAlias data-media.domain.tld
</VirtualHost>

<Directory /var/www/elmsln/domains/media>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>
```

And then make an entry for each of the domains (I only wrote a couple) like above so that the http versions of the data- based domains resolve

**Comment by yurg** [comment]
@btopro Aaand we're back to this point https://github.com/elmsln/elmsln/issues/2329#issuecomment-347523221 we discussed 3 days ago..
According to your suggestion from https://github.com/elmsln/elmsln/issues/2329#issuecomment-347544754 I have this `dataprotocol='http'` in `/var/www/elmsln/config/scripts/drush-create-site/config.cfg` which should use HTTP for  all **data-** domains. It seems I need to revert it all back to HTTPS now.

**Comment by yurg** [comment]
OK, I've changed 
`/var/www/elmsln/config/scripts/drush-create-site/config.cfg` to be `dataprotocol='http'` 

and `online.conf` to look like

```
` 
 NameVirtualHost *:80
 <VirtualHost *:80>
    DocumentRoot /var/www/elmsln/domains/online
    ServerName online.domain.tld
    ServerAlias data-online.domain.tld
    
RewriteEngine on
RewriteCond %{SERVER_NAME} =data-online.domain.tld [OR]
RewriteCond %{SERVER_NAME} =online.domain.tld
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<Directory /var/www/elmsln/domains/online>
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>

`
```


Also, LetsEncrypt adds this `online-le-ssl.conf` file:

```
`
<IfModule mod_ssl.c>
<VirtualHost *:443>
    DocumentRoot /var/www/elmsln/domains/online
    ServerName online.domain.tld
    ServerAlias data-online.domain.tld
    
RewriteEngine on
# Some rewrite rules in this file were disabled on your HTTPS site,
# because they have the potential to create redirection loops.

# RewriteCond %{SERVER_NAME} =data-online.domain.tld [OR]
# RewriteCond %{SERVER_NAME} =online.domain.tld
# RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
SSLCertificateFile /etc/letsencrypt/live/online.domain.tld/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/online.domain.tld/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/online.domain.tld/chain.pem
</VirtualHost>
</IfModule>
`
```

Yet I still see: **Error initializing socket ssl://data-online.domain.tld:443.**

**Comment by yurg** [comment]
Obviously there is **https://data-online.domain.tld** "connection is not secure"
Shouldn't **data-online.domain.tld** have a separate .conf file, instead of exists as a server alias only?

**Comment by btopro** [comment]
because you have `RewriteCond %{SERVER_NAME} =data-online.domain.tld [OR]` in there which will rewrite http://data-online to be https://data-online which then causes the cert issue.

Take out the alias'ing for `data-` in the files and move it over to the new file suggested above.

**Comment by btopro** [comment]
or, make the cert include all the data- domains as well :)

**Comment by yurg** [comment]
@btopro That last combination of tricks seems to has got Course creation done, **thank you!**; there is an issue with users still; perhaps it is more about how Bakery works, yet I'm not quite get the logic, will you please assist? 
So, let us start simple. We have 2 users in the system:
UID   Username   Email                      Role                             Comment
1       Admin          admin@domain    auth, administrator      God's account we used at initial ELMSLN setup
2       Editor           editor@domain    auth, administrator      User created via Drush according to https://github.com/elmsln/elmsln/issues/2344#issuecomment-348031858
Now, Editor can create a new Course, but:

1. No Admin nor Editor can't access https://domain.tld/elmsln/redirect/cle/newcoursename and https://domain.tld/elmsln/redirect/moos/newcoursename  with the message 
**Access denied, please log into your account.**

2.  `drush @elmsln.courses.newcoursename  uls` gives
> 1   Editor   **admin**@domain.tld  authenticated user, administrator  Active

As you can see, Course, created by Editor gets a single user (analog of Drupal User 1), which has Editor username but Admin email (???) I'm not really sure which password new account receives, nor which credentials actually it has: Admin's or Editor's

**Comment by btopro** [comment]
ok, I'll have to look into that one by seeing what happens w/ some that our staff have created (for the longest time I made them all and in most deploys the admin makes them but obviously staff/admins should be able to make them and go from there).

IF that's goofing things up on setup of the new space then that's why Bakery isn't working. Bakery requires a uniform username and email adress (not UID tho) across systems it talks to. If something is getting goofed up on that account when it sets up (which sounds like it might be an issue in the system) then that would cause that.

Try this:
- uli to get in
- update the username on the user 1 account to be the Admin
- manually create the user for Editor w/ the email to match
- see if bakery works then for both

Again, it should just work without this having to happen but I want to make sure Bakery is indeed working and this is in-fact an elmsln related setup glitch.

**Comment by yurg** [comment]
_Something is rotten in the state of Denmark_

**drush @elmsln.courses.newcorsename uli**  gives  **https://courses.domain.tld/newcoursename/user/reset/1/blahblah/login** which, being pasted to browser address bar leads to **https://people.domain.tld/user/38/edit?destination=elmsln/redirect/mooc/user/1&elmsln_course=newcorsename**, where I can see/edit 
 Editor user with editor@domain.tld email. 

Yet,  **drush @elmsln.courses.newcoursename uls** returns  
UID/Name/Email: 
1/Editor/admin@domain.tld

At this stage I'm not really sure how to change Editor's email, apart from direct newcoursename DB intervention.

**Comment by btopro** [comment]
paste the uli into a new / private browser; uli won't override the bakery cookie

**Comment by yurg** [comment]
Incognito mode returns "Access denied, please log into your account." for one-time login link generated by `drush uli` 

_Curiouser and curiouser!_

**Comment by btopro** [comment]
was it a new drush uli against that other course space specifically? Modding that user table DB is not ideal but there's something weird w/ the accounts there so not sure what else to say other then this is now a documented issue and we resolved the other general login stuff (I hope).

If YOU make a new course are you able to connect via bakery and what not without issue?

**Comment by yurg** [comment]
@btopro   Yes, it was a new drush uli; and yes, if Admin (Drupal User 1 account created at initial ELMSLN setup) creates a Course, Admin can access it; but **other users can't**

**Comment by btopro** [comment]
correct. other users don't get access to things newly created unless their accounts are added to them. These are unique drupal sites. These example modules illustrate how to stitch together these last things / customize things when they build --

https://github.com/elmsln/elmsln-config-example/tree/master/shared/drupal-7.x/modules/cis_implementation_example

**Comment by yurg** [comment]
So, let us, perhaps, summarize what we have at the moment: 

1. Would be nice to add a HTTPS setup related section to the docs 
2. There is an issue in Course creation process, if Course "author"  is not a Drupal UID 1, "wrong" user is being created as Course's User 1. ELMSLN team will look into this.
3. In a meanwhile we may manually add Course Editors using Drush(only?) or via custom module creation using this https://github.com/elmsln/elmsln-config-example/tree/master/shared/drupal-7.x/modules/cis_implementation_example 
4. There is still a question of how Students are being assigned to the Course, yet it seems it worth a new thread creation or perhaps it's just a matter of proper documentation reading.

**Comment by btopro** [comment]
Good summary - I think a whole section about user management in general which hits all of these would be good. There are a few ways mentioned throughout here like file import, API usage, Canvas API (this is also baked in via a submodule in CIS that can be enabled). There's also the comply system which can add people pervasively.

Other possible methods would start to step into Drupal contrib more like Shibboleth, CAS, Cosign/Webserverauth, LDAP all of which I believe have Drupal modules that could be configured to pull this stuff in.

While frustrating for sure, we left user management pretty wide open to accomidate the maximum number of methodologies. The glitch discovered def needs fixed (please open another issue just for that) and we definitely need a clear way to do user management in CIS, which is long overdue to have an overhaul #1051. Our focus right now is [HAX](https://lrnwebcomponents.github.io/hax-body/components/hax-body/demo/) and getting new team members ramped up so we can start to improve the UX across the board.

**Comment by yurg** [comment]
Well then, new issue created, perhaps we can close these below in order to eliminate "new bug found" frustration a bit:  
#2334 
#2329 

Thnks!
