### ISSUE TITLE
Image manipulation controls not working after first image

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2345]
The studio image manipulation buttons located in `<app-toolbar class="style-scope lrnapp-studio-submission-display x-scope app-toolbar-0">...</app-toolbar>` work for the first image, but not the second image or ones after.

<img width="1049" alt="screen shot 2017-11-29 at 12 21 29 pm" src="https://user-images.githubusercontent.com/1085304/33389208-198d31dc-d500-11e7-8aaa-70d018850a74.png">

**Comment by btopro** [comment]
this is correct and fixed already tho not pushed up based on release schedule
