### ISSUE TITLE
Course template -  secondary source list

### ISSUE THREAD

**Issue by jtb260** [elmsln/elmsln#2348]
From the course templates, bullets are appearing again on the secondary source list. There shouldn't be a bullet next to the item (see image below) 

![screen shot 2017-11-30 at 2 34 02 pm](https://user-images.githubusercontent.com/13224682/33451087-d0d05e56-d5db-11e7-9cf6-7147ee25ea7a.png)

Course page: https://courses.aanda.psu.edu/aa100/node/29

Code:
<ul class="collection"><li class="collection-item"><a href="http://www.smithsonianmag.com/videos/category/history/what-the-completed-great-pyramid-wouldve-lo/2" target="_blank">What the Completed Great Pyramid Would Have Looked Like</a> <a class="secondary-content" href="http://www.smithsonianmag.com/videos/category/history/what-the-completed-great-pyramid-wouldve-lo/" target="_blank"><i class="material-icons">play_circle_outlined</i></a></li><li class="collection-item"><a href="http://www.smithsonianmag.com/videos/category/history/the-egyptian-pharaoh-with-the-biggest-ego/" target="_blank">The Egyptian Pharaoh With the Biggest Ego</a><a class="secondary-content" href="http://www.smithsonianmag.com/videos/category/history/the-egyptian-pharaoh-with-the-biggest-ego/" target="_blank"><i class="material-icons">play_circle_outlined</i></a></li>
</ul>

**Comment by btopro** [comment]
fixed (in the course as well)
