### ISSUE TITLE
Media Citation Patterns

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2349]
@nikkimk You may have already seen something like this, but since I heard you are working on ux/ui patterns, I noticed one that is pretty neat here for media citations and thought I'd see if you thought it was worth attempting: http://byanymedia.org/works/mapp/activity-1?path=activities

<img width="1074" alt="screen shot 2017-12-05 at 9 09 08 pm" src="https://user-images.githubusercontent.com/1085304/33640787-9aef5b6a-da00-11e7-98c2-5335c63f4efd.png">

<img width="1070" alt="screen shot 2017-12-05 at 9 07 07 pm" src="https://user-images.githubusercontent.com/1085304/33640745-625c233c-da00-11e7-9e48-2b111c825931.png">

<img width="771" alt="screen shot 2017-12-05 at 9 09 14 pm" src="https://user-images.githubusercontent.com/1085304/33640793-a55b9a0a-da00-11e7-965f-d0e995668a92.png">

**Comment by btopro** [comment]
work started on citation element for uniformity in schematization as well https://github.com/LRNWebComponents/citation-element

**Comment by btopro** [comment]
we have citation and license elements now
