### ISSUE TITLE
More icons

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#235]
@michael-collins I need the following icons

- [ ] Play button for video
- [ ] Arrow for remixable button
- [ ] Arrow for navigation dropdowns
![screen shot 2015-09-02 at 2 40 19 pm](https://cloud.githubusercontent.com/assets/3428964/9640800/4cd3d154-5181-11e5-9a95-eb55fd7e59aa.png)
![screen shot 2015-09-02 at 2 41 22 pm](https://cloud.githubusercontent.com/assets/3428964/9640802/4ea613de-5181-11e5-9007-b68dc2354969.png)

**Comment by heyMP** [comment]
Side note... if you find a good tutorial on drawing arrows in Preview on the new OSX that would be greeeaaaatttttt.........

**Comment by heyMP** [comment]
@cmd30 Carly made them.

**Comment by btopro** [comment]
PR and make sure she's credited then
