### ISSUE TITLE
Restricting Links in the 'More Tools' Menu

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2352]
v0.8.1

I was wondering what the best way of restricting the links in the 'more tools/apps' area of the site is based on role. We have an area of the site which is for clients called b-Hive Analytics:

![image](https://user-images.githubusercontent.com/4973810/33761521-340a7788-dc01-11e7-9c0b-e0c781fd80f5.png)

I want these clients to be able to access this link, but not be able to view the other 'admin' type areas. Thanks

**Comment by btopro** [comment]
implementing `hook_cis_lmsless_theme_vars_alter` should be able to git into things on the side bar to hide contextually

```
function whatever_cis_lmsless_theme_vars_alter(&$vars) {
  if (_cis_connector_role_grouping('staff')) {
    $vars['services']['Administrative']['lrs'] = $vars['services']['Analytics'][0];
    $vars['services']['Administrative']['lrs']['title'] = t('Learning Analytics');
    unset($vars['services']['Analytics']);
    $vars['services']['Administrative']['piwik'] = array(
      'title' => t('Browser analytics'),
      'url' => 'someaddress',
      'machine_name' => 'dotgrid',
      'icon' => 'dotgrid',
      'weight' => 10,
    );
  }
}
```

This example I add a special link only for people that are staff. `unset()` statements can be used to remove things from parts of the array to make them not show up

**Comment by btopro** [comment]
if @JackWillDavis ends up implementing this please have him contribute a section to our docs on this subject

**Comment by JackWillDavis** [comment]
Hi @btopro, am I right in thinking that using _cis_connector_role_grouping can only be used for modifying the links when the user is assigned to admin, staff, learner, teacher or active learner roles?

I assume I could get around it by checking Drupal for the active user role of whoever is viewing the page but thought I would ask as you used that function in your example.

**Comment by btopro** [comment]
`_cis_connector_role_grouping` is for quickly getting if the current user is part of a role grouping you care about without doing a bunch of drupal based checks https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/cis_connector.module#L1662-L1708

that is for modifying the links on the fly and then only doing so for certain users; you can modify whatever you want in there without if statements to modify for all
