### ISSUE TITLE
Course creation wrong user creds assigned. 

### ISSUE THREAD

**Issue by yurg** [elmsln/elmsln#2353]
Comes from here: #2344

Description:
We have 2 users in the system:
UID Username Email Role Comment
1 Admin admin@domain auth, administrator God's account we used at initial ELMSLN setup
2 Editor editor@domain auth, administrator User created via Drush according to #2344 (comment)
Now, Editor can create a new Course, but:

No Admin nor Editor can't access https://domain.tld/elmsln/redirect/cle/newcoursename and https://domain.tld/elmsln/redirect/moos/newcoursename with the message
Access denied, please log into your account.

drush @elmsln.courses.newcoursename uls gives

1 Editor admin@domain.tld authenticated user, administrator Active

As you can see, Course, created by Editor gets a single user (analog of Drupal User 1), which has Editor username but Admin email (???) I'm not really sure which password new account receives, nor which credentials actually it has: Admin's or Editor's

**Comment by btopro** [comment]
duplicate (same underlying issue) as #2344
