### ISSUE TITLE
Studio submission download link incorrectly generated

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2354]
Re-saving the submission didn't fix the issue. Studio submission url:

https://studio.aanda.psu.edu/dmd100/apps/lrnapp-studio-submission/submissions/955

The link directory is listed as:

`https://studio.aanda.psu.edu/dmd100/sites/studio/aa/dmd100/files/`

I think it is supposed to be this:

`https://studio.aanda.psu.edu/dmd100/system/files/submission_files/`

**Comment by michael-collins** [comment]
Found another example of this issue: 

https://studio.aanda.psu.edu/dmd100/apps/lrnapp-studio-submission/submissions/1311

`https://studio.aanda.psu.edu/dmd100/sites/studio/aa/dmd100/files/prototype-jts5274.zip`

which should be

`https://studio.aanda.psu.edu/dmd100/system/files/submission_files/prototype-jts5274.zip`

**Comment by btopro** [comment]
should be fixed in 0.13.x can revisit if not
