### ISSUE TITLE
What if HAX were like Roku...

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2356]
another thing I’ve been thinking of; what if we had a token based decentralized app. What i mean is, think of a finished copy; you get it and install it and you have HAX and HAX can save to the local file system, it can build out pages, import, etc

but you want to use Youtube, or you want to use Kaltura or some other thing

what if we had a “integrate” button in the file system menu or something (or add source in the sources area works too). Then, you go to like elmsln.psu.edu/integrations and webaccess to login, it’s a basic site that says what you should be allowed to do (MVP, this provides integration with Kaltura for example)

so you are on that dashboard and say “I want to use Kaltura” and it gives you a custom address like certify.elmsln.psu.edu/u/dkuj82u3u28r8re9299eedskkcccc222 and that is your personal ID token

you copy and paste that address into your “add source” area in your HAX desktop app and it automatically adds the Kaltura button to your local HAX client and then brokers calls on your behalf
 
so now, if you want to upload something, it can go straight to Kaltura (or whatever)
 
a similar workflow would work with ELMS Media, Interact, Studio, etc

you could do the entire thing on your machine, but actually your saving out to and leveraging a distributed series of services

You could actually have a copy locally, in Box, on some OER Schema hosting location, and on *multiple ELMSLN deploys and they would have all stemmed from the same desktop app*.

**Comment by zanesensenig** [comment]
I would like to help you build out this vision! This is where I would like to go with content editing for my IDs. Our current processes are not efficient and a desktop client might feel more familiar.

**Comment by btopro** [comment]
@heyMP is putting in some of the node wiring required for https://github.com/LRNWebComponents/hax-desktop-app to read off the local file system and load a file. We'll be doing a bit of that this week. Whatever it ends up being I want to publish hax-body / "hax" series of tags and workflow once and deploy it anywhere (anywhere being Drupal 7, Backdrop, GravCMS, hax-desktop-app, ionic down the road for mobile apps)

**Comment by btopro** [comment]
as blog post of this vision -- https://btopro.com/blog/the-lms-is-cable-we-are-roku

**Comment by btopro** [comment]
#1473 would have to provide the backend for our "channel store" of sorts

**Comment by btopro** [comment]
![ngdle-university](https://user-images.githubusercontent.com/329735/35882693-00092ebc-0b53-11e8-9d4e-949f278bc1b9.jpg)
 vision of this and blog posts exist and more are on the way; this is the way forward and now HAX supports app stores which supply it with the data needed to browse engines
