### ISSUE TITLE
Updates to Discuss Templates

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2357]
v0.8.1

I've been asked to set up a forum on one of the courses we offer so just testing this out. It looks like I need to change some of the template styling though to account for our lack of user profile photos.

![image](https://user-images.githubusercontent.com/4973810/34166620-451cf0e4-e4d7-11e7-9453-53d42f991684.png)

Ideally I'd like to just add the username of the author in here instead. What's the best way of going about this? I imagine this is probably going to be replaced by something built in web components at some point so just kind of looking for a short term solution.

**Comment by btopro** [comment]
yeah, this was mostly just positioned correctly and has a decent data model but wasn't finished. It's templates are driven by the Harmony project which we use some of the data model of https://github.com/elmsln/elmsln/tree/master/core/dslmcode/profiles/discuss-7.x-1.x has the distro. 

https://github.com/elmsln/elmsln/tree/master/core/dslmcode/stacks/discuss/sites/all/modules/local_contrib - has those projects.

I THINK that those come from views templating from those modules but I'm not positive. Hope this is enough of a push in the right direction.

**Comment by rickhumphries** [comment]
Thanks - we'll dig around and see what we can do

**Comment by JackWillDavis** [comment]
Hi @btopro, we've managed to resolve by amending the template directly but is there a way of protecting this from future updates? For example, is there somewhere in the ELMS config files where we can define our own harmony templates to use by default?

Or will it have to be done via a patch file?

**Comment by btopro** [comment]
well what's the patch look like? We don't actively use the discuss system at this time. It's very low in our priority though it needs a make over (and will get one ala webcomponents at some point). Guess what I'm saying is depending on what it is if it's a generic solution we can accept it into core :)

**Comment by JackWillDavis** [comment]
It is basically commenting out the code which shows the profile image and places the username in there instead. Very minimal tweaks really.

**Comment by btopro** [comment]
Oh ya let's do it then, it's a bandaid anyway. Have you checked out the studio in a local development environment to see what's available in 0.9.0 and the 0.10.x branch? It's much more refined then the discussion boards currently

On Jan 3, 2018 7:07 AM, Jack Davis <notifications@github.com> wrote:

It is basically commenting out the code which shows the profile image and places the username in there instead. Very minimal tweaks really.

**Comment by btopro** [comment]
PR accepted; issue fixed
