### ISSUE TITLE
Export Book

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#236]
Just wondering if there's a way of exporting a book (instructional outline) created in one course, and then importing this into the MOOC site of another course? I can see the 'Book Outline Export' and 'Book Outline Import' modules, but unsure as to how to use them. Thanks

**Comment by btopro** [comment]
yeah, export is listed on the outline designer page and get the node id for the book, then go to /feeds_node_helper_export/{nid}

this will give you an xml package

import is /import and lets you upload something

*should* just work

**Comment by btopro** [comment]
@michael-collins do the mock ups account for import/export areas? Would be good to make it clear via UI that these capabilities exist

**Comment by michael-collins** [comment]
Yes, I have that mostly accounted for in the mockups. Would need to add an
export icon.

**Comment by btopro** [comment]
@michael-collins I'd stop asking this if u posted all of them to the wiki ;)
