### ISSUE TITLE
ELMSMedia Dashboard Changes

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2366]
- [x] make card clickable (visit node page, ie `node/43`)
- [x] handle route changes to outside of app
- [ ] image placeholders for all content types
- [ ] accessiblity
- [ ] sort criteria
- [ ] add more info to card
- [ ] results counter ie(you're seeing)

**Comment by btopro** [comment]
@cgldevel what's the status on this?

**Comment by btopro** [comment]
moving away from this dashboard in general. A new dashboard owuld be headless, built for HAXcms and then able to visualize these assets in a purely decoupled manner. Closing as HAXcms has issues related to this thing by LauraGibbs about media management
