### ISSUE TITLE
Bakery login broken after changing email of User 1

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2368]
Bug:
- 0.8.1

Hey - we changed the master site in shared_settings to be CIS/Online a while back, but when spinning up new courses the bakery master site on the courses site still references 'People'. Do I need to refresh any of the settings for this to get picked up?

Thanks

**Comment by rickhumphries** [comment]
Also getting this now on first login:

![image](https://user-images.githubusercontent.com/4973810/34618884-1fd22e62-f238-11e7-9566-843087c5d96b.png)

I can do a uli to get access but not sure why the admin accounts aren't setting up automatically as they have before.

**Comment by btopro** [comment]
hmm... when you uli in is the username and email address set to match what it is in CIS? I'm not sure if it's hitting people so much as this part's being goofed up (I dont think u even have a 'people' system do you?)

**Comment by rickhumphries** [comment]
I'm actually not sure whether it matches that in the CIS because when I try to view the profile for 'devteam' it takes me to the CIS anyway. In fact, when I use the uli link it directs me to the devteam account in the CIS, then I hit save and navigate back to the course page and that then lets me in.

**Comment by btopro** [comment]
hmmm...
 then is it good after that?

**Comment by rickhumphries** [comment]
Yeh it's alright after that

**Comment by rickhumphries** [comment]
Update - I can use a uli to login, but then after a while (cookie must have expired) the login goes back to being broken. Is there a workaround of being able to view the profile of User 1 on the course site itself (like I can do for students). If I try to view the profile it redirects to the CIS profile

**Comment by btopro** [comment]
oh like user/1/edit or user/1 in general? If you type directly to user/1/edit it'll bypass

**Comment by rickhumphries** [comment]
typing user/1/edit redirects to online so I'm at `https://online.domain.co.uk/user/1/edit?destination=elmsln/redirect/mooc/user/1&elmsln_course=course_name`

**Comment by btopro** [comment]
how about user/1/devel

(this is odd for sure)

**Comment by rickhumphries** [comment]
Right yeh, I switched on devel module and went to `user/1/devel`. That gave me the info I needed to set the email address to match so it was the same on the master site. That seems to be fixing this particular issue. Still weird behaviour that the email address is what bakery thinks is important when I read somewhere that it should be the 'init' email - but the acute issue's been solved. Thanks for your help.

**Comment by btopro** [comment]
Yeah I'm not in love with Bakery (never have been) it just happened to work at the time. In an odd way, the work on HAX surrounding creating an "app store" is also able to position us to solve this problem with a more industry standard login solution via oAuth2 and JWT tokens
