### ISSUE TITLE
Deleting multiple course outlines maxed server memory

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2369]
Possible Bug:

I deleted approx. 6 sizable course outlines. One of the batch processes got stuck which wouldn't time out.  Server memory maxed out and I had to reboot.  I don't believe there is an issue with ELMS rather Drupal batch process but I could be wrong.

**Comment by btopro** [comment]
@heyMP was this on a system that is git backed? book outline cache bins and mass deletes have been finiky in the past

**Comment by btopro** [comment]
read time dropped which will help alleviate this though #2406 is the other piece off in its own issue
