### ISSUE TITLE
Add Media options missing for instructors

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2371]
Bug:

![screen shot 2018-01-08 at 12 45 26 pm](https://user-images.githubusercontent.com/3428964/34684095-02d7d852-f472-11e7-9286-686e7998d0b4.png)

![screen shot 2018-01-08 at 12 45 56 pm](https://user-images.githubusercontent.com/3428964/34684115-10ff5c3e-f472-11e7-8cbd-77aea4654e6a.png)

**Comment by btopro** [comment]
OOOOO YES. ok

`mooc_foundation_access_menu_tree__menu_elmsln_add` in the mood_foundation_access theme has it. This was not intended to be rolled out at the time it was added for testing.

```
/**
 * Implements menu_tree__menu_elmsln_add.
 */
function mooc_foundation_access_menu_tree__menu_elmsln_add($variables) {
  $links = '';
  // make sure nothing shows up if this is the new book
  if (arg(1) != 'lrnapp-book') {
    if (_cis_connector_role_grouping('staff') && user_access('add item in context')) {
      $links = _elmsln_core_in_context_list();
      $links = implode("\n", $links);
    }
    return '<ul role="menu" aria-hidden="false" tabindex="-1" class="elmsln-add-menu-items">' . $links . $variables['tree'] . '</ul>';
  }
  return FALSE;
}
```

correct that function and you'll be golden. If you tweak it just to `user_access('add item in context')` then we can correct permissions / make sure they are aligned
