### ISSUE TITLE
Can't Stop the Guy Reading Course Materials to Me!

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2373]
Bug:
- 0.8.1

When I check the 'Read to me' checkbox on a course site, the guy starts reading, but he doesn't shut up when I uncheck the box. He doesn't even stop when I navigate to another page! haha

![image](https://user-images.githubusercontent.com/4973810/34715200-b0228f0a-f523-11e7-81b9-f4254dc7644c.png)

**Comment by rickhumphries** [comment]
In fact, it doesn't even stop at the end of the page - it's reading through the whole book too

**Comment by btopro** [comment]
lol I think once checked it follows you around
