### ISSUE TITLE
Unconnected field collection items in the CIS when deleting a course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2374]
Related #2113 

When closing down a course I step through the following:
1. Run leafy and delete all associated services/databases etc.
2. Delete the service content types associated with the course from the CIS
3. Delete all the sections linked to the course content type in CIS
4. Finally, delete the course content type from CIS

However, it seems that there are still unconnected field collection items hanging around that I (assumed) had been deleted. I can access them from a url like `/field-collection/field-sections/464/` and the details of the section will show with the title 'Unconnected field collection item'

**Comment by btopro** [comment]
yea that sounds about right; I believe FCs will more or less unpublish as a default behavior when "deleted" via a UI.

**Comment by btopro** [comment]
absolutely an issue, merging into #2113 since that would require this to be done as part of it
