### ISSUE TITLE
Enrolling students on multiple sections within same course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2378]
I wondered if it's currently possible to set a course up to do this? 

So I could have, for example, 6 different course outlines (books) associated with 6 different sections. Student one is associated with sections 2 and 5, and student two is associated with 1, 2 and 6. Different students can have different combinations.

When they log in, they have the the permission to switch section context but only the options to view the sections they're associated show from the dropdown list.

We've had a few requests recently for a sort of 'pick and mix' style course where content is more tailored to each individual. One course has 16 pick n mix parts and I don't want to go down the road of creating 16 different courses!

**Comment by rickhumphries** [comment]
I did a quick test with the 'guest' role as this has permission to switch section context. I think everything's set up for this to work - except that the user can still view all of the sections in the dropdown, rather than it just being limited to the one's they're allowed to view

**Comment by btopro** [comment]
So I wouldn't recommend this method though it is possible. We have explored branching path systems previously in mock ups. 1 simple way to achieve this is to have the highest level be items named like they are different outlines even though they all have the same book root. Then, the landing page for the course is put on a customized page that presents these options differently.

We have some issues in the queue related to this and I know both my manager and Collins want to come up with a solution that's sustainable. I think 1 way is to have the new content player app in 0.10.x have am option that allows for defining pathways different from how the content is actually structured. Think content outline that just references all the content in a more by reference manner. Then you could do stuff to mess with who gets what pathway visible to them, etc.

There is a callback that me and potter wrote that will figure out the correct book to land on as a wildcard based on who the users section is. That way you can link to 1 place but it diverts to many. Perhaps something like that randomly diverting to the high level pages of a book could also achieve that

**Comment by rickhumphries** [comment]
Hmm, I'm not sure if the simple method you've described would work, because if there are 16 different sections and learners can have any combination (but shouldn't have access to the ones they aren't associated with) that's potentially thousands of different customized pages required. Unless you mean the customized page needs to be generated programatically?

I guess it's not really branching in this case, but kind of - there are 16 chapters, and someone just wants to pay for access to 4 of those chapters. The switching of sections seemed like a pretty neat solution to me. How come it's not recommended?

**Comment by btopro** [comment]
oh I see...

I mean I guess you could do it that way with the section thing, sounds like some form of custom code either way most likely.

You could also build a module that would do the following:
- add a new type of node_access permission which is like "bought access to X" where X is the node id in question
- make the 16 "courses" all in 1 book so it's managable
- When someone pays in CIS, send a message to this module to say "Student Y now has access to node X"

This would effectively mean even people in a course wouldn't have access to anything; this additional level of access would be ensuring that people have only bought access to the pieces they have.

We do something sorta along these lines in some courses where we've replaced textbooks we charge $30. In these scenarios, the course roster syncs effectively telling us who's in the space but then after 24 hours of free access, they have to pay to unlock the space.

**Comment by btopro** [comment]
as for enrolling people on multiple sections in the same course; yes you can enroll in multiple sections within the same course at a technical level. In our world, this is how faculty can be teaching multiple sections of a course and the people are segmented but also options like course outline

**Comment by rickhumphries** [comment]
Thanks, appreciate the input. We'll have a think about some options and how best to implement it
