### ISSUE TITLE
Font icons

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2381]
Hi - just wondered what the recommended way of adding custom font icons into ELMSLN would be?

**Comment by btopro** [comment]
Custom like you made them yourselves or custom like font awesome or another library?

**Comment by rickhumphries** [comment]
A bit of both really. We've selected a few icons from here https://materialdesignicons.com/  and thought it'd be good to try and create a font icon from them and implement it within the course

**Comment by btopro** [comment]
So the answer is (wait for it).... webcomponents, being the recommended way.

We did a bit of taking from that same source and added them into https://www.webcomponents.org/element/LRNWebComponents/md-extra-icons

This pack of extra icons (on top of the assumed https://www.webcomponents.org/element/PolymerElements/iron-icons ) is where we are currently adding other icons we'd like to have available.

https://www.webcomponents.org/element/kriss-kross-io/mdi-iconset-svg might be a better solution tho as I only found it recently. It's got way more of the icons from that website so it's more of a question of if we want to extend that or not. It doesn't have ALL the icons from that website but it has a lot more then the other set.

If your custom ones are SUPER custom to your group then maybe we can discuss adding them into the LRN-icons subset of education / training specific icons https://www.webcomponents.org/element/LRNWebComponents/lrn-icons

If your talking like "this is the buttercups logo" well then maybe just a SVG reference from your own custom webcomponent or a CSS based font solution and add it in that way.

**Comment by rickhumphries** [comment]
Oh ok that's cool. I've just tried adding `<iron-icon icon="mdextra:subscript"></iron-icon>` to my source but it's not picked it up. Is that the right thing to do? Or am I not on the correct version of ELMS (0.8.1) for this to work?

**Comment by btopro** [comment]
0.8.1 has iron-icons not not those extra ones yet. 0.10.x they get in

**Comment by rickhumphries** [comment]
Excellent - thanks for the help :)
