### ISSUE TITLE
Layout a user login page

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2387]
The user login area looks terrible. It's an unthemed page within the normal ELMS:LN GUI. Instead of just fudging these form inputs to looks slightly nicer, what if we instead made our login completely different.

Goals:
- Make the login look nicer
- Have less options so there's no random clicking on things they'll never have access to
- Start to set the tone for the api system which will mostly NOT be connected to typical login systems and down the road will need it's own login prompt / app authorization look
- Our front-door should be awesome to draw new people into everything from there
- optimized delivery; if they aren't logged in, don't bloat them with all the front-end assets

**Comment by btopro** [comment]
with inspiration from GravCMS and the Stranger Things ELMS:LN teaser video style:
![2018-01-23_14-44-51](https://user-images.githubusercontent.com/329735/35297272-81679442-004c-11e8-90f2-ec13262d6848.png)

**Comment by btopro** [comment]
Only things provided to user are username and password. Banner is relative to where you are / course context. If there's a course context / custom banner, then that shows up. If there isn't then it's the default. After logging in we take them to ELMS:LN look at feel. Works well on mobile and ELMS:LN BG is big ol' SVG so scales nicely

**Comment by btopro** [comment]
@rickhumphries is the primary user of this login page currently so would be curious his thoughts. It's a Drupal TPL file so it can be overridden / enhanced.

**Comment by btopro** [comment]
![2018-01-23_15-45-43](https://user-images.githubusercontent.com/329735/35299858-aa70fc72-0054-11e8-855a-53380b4d095f.png)
mobile, when not accessing a course space as another example

**Comment by btopro** [comment]
Login button is WCAG 2.0 AAA contrast ratio approved now

**Comment by rickhumphries** [comment]
@btopro Yeh really like the concept of this. Think this is a good idea. Anonymous users should get automatically directed to it if they land on a page they don't have access to as well

**Comment by btopro** [comment]
when that happened (anon hit) they get pushed over to this screen and a message says access denied. Glad you like the idea, I'll merge it in and we can move forward from there. It's only 2 template files with 99% of the stuff in 1 of them (css too). I'm debating whether or not to deliver webcomponents on this page as with Lighthouse metric I can get really high scores without them and much lower with them (it's a big file :)).
