### ISSUE TITLE
Voting and Decision Making Policy

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2396]
**THIS IS ALL UP FOR REVIEW I AM SIMPLY STARTING THE CONVERSATION** 

As part of incubation we need to agree on a voting and decision making policy. This is for founding members of the 4 primary organizations involved. Tagging people not to exclude, just so we don't have multiple represented opinions from the same organization.

https://wiki.jasig.org/display/INCU/Jasig+Project+Voting+and+Decision+Making is an example of a potential model. As BDFL I'm recommending we adopt something similar but with more flexible language based on the scope of what the decision is. The project is designed for sustaining innovation so change is the name of the game.  We'll also need a policy / procedures for having people be added into the more formal decisions that need made at some point in the future.

When these changes go into effect:
- Once we adopt a policy **and**
- Once we reach an additional layers of platform "productization" **and**
- After picking up at least 1 more core contributing organization, not at Penn State

Examples of things that in my mind are NOT the point of voting:
- Studio needs a better grading interface
- I want that heading blue by default
- I don't want a source to be a default in HAX media integration
- I want another media type supported by the media system

Examples of things that need review and more formal discussion:
- Changes to the default ELMS:LN "skin"
- Any breaking changes that will have no upgrade path (@rickhumphries and I sorted this our 2 years ago for example when CIS went from a presentation site to a backend only system; a move I only went forward with in coordination with his approval)
- We say we're not supporting Drupal 7 one day (years out) and decide to deprecate it in favor of Drupal 9 (or something entirely different)
- We decide to move a technology into the stack that we currently don't support (for example webcomponents, docker)
- Rick makes a "screencast hub" which allows people to do live teaching sessions (hypothetically). He pays / has his team develop this in their deploy of ELMS:LN. Katrina's group wants this capability. A discussion about the feasibility of supporting and sustaining this technology as well as concept in core has to take place (It's not just, oh here's a PR for this massive code base. See next section)

Considerations:
- As this is a system of systems, any technology decision must be something that can be supported by at least 2 core maintainers.
  - Examples of the policy: Drupal originally (all founding members), Webcomponents (me + Potter), docker (not formally included yet but will be me + Potter)
- Katrina's group builds an amazing cool video submission tool and wants it pulled into Studio. This enhancement may be major but so long as it meets the 2 developers can support rule and no one objects then this can get in without a vote. This would be a prime example of something that someone COULD object to.

If something is decided to meet the criteria for a vote and someone requests it then we have a Zoom / online call with webcams in order to sort that out. Based on the current trajectory of the project (gradually phasing in new technologies and replacing ones in place) I don't foresee this being a common used practice but one we need to have something in place for regardless.

**Comment by btopro** [comment]
Not tagging doesn't exclude suggestions, just trying to work towards a core decision making council of sorts to kick things off.

**Comment by btopro** [comment]
Related: https://github.com/elmsln/elmsln/blob/master/GOVERNANCE.md

**Comment by kat-wehr** [comment]
I think the breakdown of what to vote on vs not worth voting on is reasonable!

**Comment by btopro** [comment]
closing just to get them off the queue; always open for discussion as community

**Comment by rickhumphries** [comment]
All hail the benevolent dictator!
