### ISSUE TITLE
Adopt a conflict resolution policy

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2397]
Part of incubation requires having a conflict resolution policy. My personal feelings on this revolve more around this being a very simple statement which mostly references the code of conduct (something we already have an have reviewed). Drupal's conflict resolution (referencing just as one i've seen) seems to be more centric on not being a jerk to people and referencing the CoC w/ a council of people for taking action against persons involved in whatever the conflict is.

I'm more apt to suggest if things are trolling then you block trolls and if we're taking about a violation to the CoC that's different (don't be a jerk) vs conflict resolution "I made feature X called things_and_stuff and Potter makes stuff_and_things and we've both based our future on this getting into core so we argue a lot" sorta deal. I'll put in place at least a boilerplate which we can work against from there.

"keep it simple" rule is definitely in affect though and being good to each other.

**Comment by btopro** [comment]
document started https://github.com/elmsln/elmsln/blob/master/CONFLICT_RESOLUTION.md

**Comment by kat-wehr** [comment]
I think that sounds like a good policy.

**Comment by btopro** [comment]
closing just to get them off the queue; always open for discussion as community

**Comment by rickhumphries** [comment]
I've read this and think it looks good to me
