### ISSUE TITLE
Remixed Content UI

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2399]
Within Google Slides, if you copy a slide from Deck A and paste is in Deck B you will be presented with a list of options that revolve around "Linking" your content.  You can either choose to paste without a reference to the original source or you can "link" the content together.

If you choose to "link" the content, a link indicator will always appear in the upper right corner.  The indicator will allow you to perform the following actions:
- Update
- Unlink
- Open Source

Since there will be a lot of remixing in our system at some point, this stood out as a possible way of managing those connections in the UI.

![screen shot 2018-01-29 at 4 34 19 pm](https://user-images.githubusercontent.com/3428964/35535908-1c9a20b8-0513-11e8-8e39-4c650407926a.png)

**Comment by michael-collins** [comment]
@heyMP This could be very interesting. I didn't consider those needs.

**Comment by rickhumphries** [comment]
+1 for this - that'd be very cool. Linking between different courses too :)
