### ISSUE TITLE
Review and hook up the task runner drush function

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#240]
https://github.com/elmsln/elmsln/blob/master/scripts/drush-command-job/drush-command-job

- [x] test it by producing job files that have drush commands in them
- [x] assign a user to run this (the elmsln user) #80 . Maybe a user called elmslndrush or something since it ONLY can execute drush commands, nothing more advanced, no sudo, etc.
- [x] hook it into cron on the install routine

Tagging @bradallenfisher since I can't assign

ECD needs this in order to function for some of its tasks (like adding a user to all sites)

**Comment by btopro** [comment]
@bradallenfisher can you take a look at an ELMSLN deployment w/ me sometime so we can figure out what's wrong w/ the setup of the crontab when it tries to run some commands as different users

**Comment by bradallenfisher** [comment]
looking into it now. I can do it this week sometime.

**Comment by bradallenfisher** [comment]
what's ../../config/scripts/drush-create-site/config.cfg
and what's ECD?

**Comment by btopro** [comment]
when the system sets it self up in vagrant it writes some settings into /var/www/elmsln/config/scripts/drush-create-site/config.cfg . Every deployment can read off this to setup new sites and what not.

ECD is short for ELMS Compliance Distribution which is comply.elmsln.local in vagrant. This system will allow for things like "I want to add abc123 to these systems". When this entityform is submitted it'll stamp a job onto the server to go off and run the task. The task runner will verify when the task has been recognized by the server and completed. This also gives us the history of who gave who access to what.

The task runner is different from drush-create-site so that that is focused on drush si's / can install systems while task runner can only run certain approved drush commands against anything in its alias setup.  I also want this to run as a different user for security purposes.

**Comment by btopro** [comment]
travis builds currently failing elsewhere due to something weird in composer

**Comment by btopro** [comment]
working; debugging some things related to using it correctly at a code layer; server layer is correct and working OOTB!
