### ISSUE TITLE
Studio comments: Text not wrapping.

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2404]
A `.nowrap` style that affects white space is being applied to studio submission comments. This makes them really difficult to read as the text extends to the right for the length of the sentence. I think this is an easy fix. See image:

<img width="1102" alt="screen shot 2018-02-07 at 11 06 17 pm" src="https://user-images.githubusercontent.com/1085304/35955145-8ef56d9e-0c5b-11e8-855d-a3099f55431b.png">

**Comment by btopro** [comment]
![2018-02-09_10-35-19](https://user-images.githubusercontent.com/329735/36035471-02f175c4-0d85-11e8-94eb-f4a0df55f8fe.png)


@michael-collins think this should fix it. @nikkimk is working on a more complete redesign of this but it's not ready to ship out yet.

**Comment by btopro** [comment]
fyi: long comments have always been accessible by clicking them to see the entire thing for much longer responses
