### ISSUE TITLE
Markdown filter wrapping web components with erroneous <p>

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2412]
Bug:
If the Markdown filter is presented with a web component it will wrap the element with <p> tags.  That doesn't sound bad until you have html content within the web component slot.  If you do, then the markdown filter will attempt to "fix" the html structure and break your dom hierarchy.

### No html in slot

![screen shot 2018-02-10 at 12 10 44 pm](https://user-images.githubusercontent.com/3428964/36064683-7267a446-0e5c-11e8-8daa-273390467797.png)

![screen shot 2018-02-10 at 12 10 55 pm](https://user-images.githubusercontent.com/3428964/36064686-785b33e0-0e5c-11e8-8e58-c2f72f1a8a90.png)

### HTML in slot

![screen shot 2018-02-10 at 12 11 10 pm](https://user-images.githubusercontent.com/3428964/36064695-8ebc2a36-0e5c-11e8-8703-e996ecb0805a.png)

![screen shot 2018-02-10 at 12 11 18 pm](https://user-images.githubusercontent.com/3428964/36064696-94dba43c-0e5c-11e8-93f7-8840a51fa789.png)

**Comment by btopro** [comment]
Should be resolved now w/ the merge
