### ISSUE TITLE
Support longer citations in media

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2417]
They are currently capped at 255. 1000 is more reasonable - field_citation off of the image field. This is going to require DB modification direction.
- [ ] field_data_field_citation
- [ ] field_revision_field_citation
- [ ] field_config blob for the field_citation field is needed
- [ ] cc all after this up db; these will be direct DB calls

**Comment by michael-collins** [comment]
Would 9000 not make more sense?
