### ISSUE TITLE
Question - Remixables

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#242]
From what I can gather from the recent videos I think the use case I'm about to describe can be achieved with the remix stuff but thought I'd throw the question out there. 

We have quite a few courses where 95% of the content is shared between them. Currently when we update content we have to go into each of those courses and update the same thing individually (in PDFs...urgh). Am I right in thinking I could set up a course and use that as the 'master book' then grab a shortcode for each of the pages...paste into the 'twin' pages in the other courses and then just have to update once in the 'master' when something changes?

**Comment by btopro** [comment]
umm... Yeah I mean it could be used to accomplish that; @michael-collins and I have talked before about having a "remote" content type that loads something remotely as its body of content or some way of saying "this course uses this one as it's by reference starting point". The issue would then be allowing for a replicated / emulated outline which references everything and then allows you to "fork" each page individually / customize it.

Too many ways to accomplish this, might need to see some workflows emerge, review, and then see how we can optimize.

**Comment by rickhumphries** [comment]
yeh I see what you're saying. I know it's not ideal for my use case from a workflow point of view but still nice that it's achievable in some way :) 

Down the line it'd be cool using the same sort of concept to let students build up their own course books as like revision guides or resource builders by curating related content across different courses  together too

**Comment by btopro** [comment]
Hmm... @michael-collins do we have an interview for a "make course that's a copy of..." kinda thing in CIS 2.x? I could see your less then ideal workflow being largely automated to start and then you'd fork the pages you want to / detach them from update as needed.

Like this idea of the students curating across curriculum. It could definitely be used to achieve something like that. I'm a maintainer of https://www.drupal.org/project/quickpost_bookmarklet and have thought for awhile it might be a cool way to allow people to prepopulate fields based on what they are currently looking at. We could make a kind of bookmarklet / button on the site that's like "add to my own course" kind of a thing.

**Comment by rickhumphries** [comment]
yeh, nice! :)
