### ISSUE TITLE
studio instructor/ta info grading and feedback grid

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2420]
Customizable way to quickly run through student submissions, comments, etc.

<img width="1137" alt="screen shot 2018-02-16 at 8 48 43 pm" src="https://user-images.githubusercontent.com/1085304/36337741-e7dbc286-135a-11e8-86ab-8a3ab1892302.png">

**Comment by michael-collins** [comment]
@btopro This is a new prototype for reusable data filtering and viewing using left to right panels.

I'd imagine we'd hard wire some filters for certain views, like a studio grader view so a grader couldn't add or remove panels. This could also be used at the CIS level to obtain any information from any course. Perhaps pull from media, content, etc., sort of like a query builder for course data.

See this interactive mockup how it could work: https://xd.adobe.com/view/9ef14bd6-863e-4c4d-bd64-29cefc70e3bf

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=GtT_-TrMaYM it's not the full thing but it's a starting point to generate discussion and reduce instruction time to grade in the short term

**Comment by btopro** [comment]
allows:
- select project to get started
- displays only the assignments for that project (but for everyone)
- sorting by name (will use SIS data for lastname, first in production)
- search by name which filters the shown list dynamically
- pink badge shows the number of comments that student has left on classmates work for that assignment (but not links to those things)
- clicking on student assignments that have been submitted open link to it in a new window
- clicking student name opens new window to their project board in studio

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=MB9OK5jJd9Q

**Comment by btopro** [comment]
grading aspect not implemented (yet) but original intent of having grading be drastically optimized from an instructor centric display is.
