### ISSUE TITLE
Make more pure presentation elements be hax capable

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2425]
@hey__MP recently made a purely visual element that looks like a simple offset note. Things like this if HAX capable would be huge for adoption.  We've been handling the big stuff, let's start unleashing creativity in the small cool things to blow people's minds even more.

Not a comprehensive I've list but things like
- [x] a vocabulary word element
- [x] a citation element
- [x] refined magazine cover element
- [x] simple user bio/description card / area
- [x] steps to completion
- [x] a reveal the answer element like very very basic self check
- [x] parallaxed image element
- [x] activity / task / call to action block

**Comment by btopro** [comment]
Tabbed content / reveal when selected sorta thing which would currently be difficult for hax but VERY powerful from a messaging perspective about how much easier HAX makes life

**Comment by cgldevel** [comment]
Buck and I are gonna tackle some of these, starting with the vocabulary element.
