### ISSUE TITLE
CIS 'Help' Page Information

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#243]
I ran through my first successful course creation on the new system today. Once installed I was unsure at first where my course site was. I think filling out information in the 'Help' Section of the CIS page would be helpful to new users who may not be familiar with where in the System the CIS puts the new courses and other various functions associated with the CIS.

**Comment by btopro** [comment]
We need like contextual help / documentation too.

**Comment by btopro** [comment]
marked documentation and then didn't actually answer the question.

Need to put on your multiple hats for this one. CIS is a staff / internal system only. Imagine it being a hub for instructional designers and instructors to get your courses set in motion correctly prior to the semester. Related though, we should probably default CIS and other authority system to not have a link to "help" and "syllabus" as they make no sense in this context (and we built in support for doing this).
