### ISSUE TITLE
MOOC: Blank pages don't auto advance for students

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2438]
Bug:
- Usually, when there is a blank page, the Mooc outline treats it as a placeholder for sub-content and auto advances to the next page.  The latest one-page app doesn't have that connotation yet.

![screen shot 2018-03-09 at 10 35 38 am](https://user-images.githubusercontent.com/3428964/37215462-fcc428f6-2385-11e8-942b-35d6bcf0ccb4.png)

**Comment by btopro** [comment]
yeah, I dono how we want to handle that, skip to it automatically by sending some call down to say "load this page instead" or what. It does exist for routing purposes and makes sense for admins just non-admins (students) getting a blank page is silly I agree

**Comment by btopro** [comment]
got this replicating the old behavior but using the new methods; if you land on a page that has nothing it'll trigger a reload of the routes same as if clicking next. For editors it'll show the message of before but in blue to mirror the color of things that can only be seen by editors
