### ISSUE TITLE
shortcode menu copy problem

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2443]
When I go to copy the shortcode to embed an iframe, it closes the menu as soon as I click to select the short code: https://courses.aanda.psu.edu/dmd100/node/1924/edit#collapse-item-renderashtml

As of now, there is no way to copy the full HTML iframe shortcode. Sad face emoji.

**Comment by btopro** [comment]
that's excellent news as we largely don't allow or support this so............ what is it your trying to do with it again?

**Comment by btopro** [comment]
largely shouldn't be using shortcodes so I'm not sure what you want one for but it's fixed now (in prod). remediation from #2427
