### ISSUE TITLE
PHP Warning: Unable to load dynamic Library on "d sa" call in Vagrant

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#245]
After ssh-ing into Vagrant I attempted to run a "d sa" call to get the listing of systems installed and created on my elms vagrant. I was given this PHP warning when I executed "d sa"

    PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/apc.so' - /usr/lib64/php/modules/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0

I will be examining what implications this error has to the system, however if anyone has an idea on what this message might be complaining about and a quick fix for it, that would be great!

Updates to follow

-Mark Milutinovic

**Comment by btopro** [comment]
just need to delete the reference to call this. Pull the latest code and rebuild vagrant cause I thinkt his might be resolved recently. If not, you'll want to look in the ini files being loaded by php for the apc. We upgrade PHP from 5.3 to 5.5 during installation. This switches the namespace of apc to apcu as it's an additional library, deprecating apc's old file.

**Comment by mmilutinovic1313** [comment]
Running the test now. New files should have been added in the last pull I made. Will verify upon completion.

**Comment by mmilutinovic1313** [comment]
This may be unrelated however upon updating the source and rerunning "vagrant up" I was given this error message

I think this is unrelated, but might mean I need to destroy my vagrant?

    Mark Milutinović [12:52 PM]
    Failed to mount folders in Linux guest. This is usually because
    the "vboxsf" file system is not available. Please verify that
    the guest additions are properly installed in the guest and
    can work properly. The command attempted was:
    
    mount -t vboxsf -o uid=​`id -u vagrant`​,gid=​`getent group vagrant | cut -d: -f3`​ vagrant /vagrant
    mount -t vboxsf -o uid=​`id -u vagrant`​,gid=​`id -g vagrant`​ vagrant /vagrant
    
    The error output from the last command was:
    
    /sbin/mount.vboxsf: mounting failed with the error: No such device

I am able to run "vagrant ssh" after this message appears, however I am still getting this issue posts' error upon "d sa"

**Comment by bradallenfisher** [comment]
Unfortunately it's cause you are trying to up a new box with the same name in the vagrantfile the old box used.  That box still exists and does need to be destroyed.

**Comment by btopro** [comment]
I'm also seeing the 5.4 PHP thing @bradallenfisher mentioned in a different thread. Not sure why though

**Comment by bradallenfisher** [comment]
sorry was referring to 
```bash
Mark Milutinović [12:52 PM]
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=​`id -u vagrant`​,gid=​`getent group vagrant | cut -d: -f3`​ vagrant /vagrant
mount -t vboxsf -o uid=​`id -u vagrant`​,gid=​`id -g vagrant`​ vagrant /vagrant

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```
 in this thread. moving on. ;)

**Comment by btopro** [comment]
I think the original issue is resolved, make sure you have latest code, destroy vagrant and re-up. if it's still there, let me know but it's completely harmless and `rm /etc/php.d/apc.ini` will fix it.
