### ISSUE TITLE
Course Compliance doesn't pick up multiple courses 

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2452]
v0.8x

I've noticed that when I associate a media asset to multiple courses (within the Media system), this doesn't get picked up in the course compliance system automatically. Only one course is attributed to the asset.

**Comment by btopro** [comment]
Yea that sounds about right. I don't believe comply had that type of logic as ot only has minimal work put into it to begin with

**Comment by rickhumphries** [comment]
OK, just looking at options for stuff linked to revision logs. We need to be able to keep track of all revision logs across a whole course to keep an audit trail of when content is updated as it's important when it comes to accrediting the course with the professional body.

I can build a view of all logs linked to a specific book within the course easy enough, but it just gets tricky where I'm building the page in the Media system with static content and using that across multiple courses, as the revision log is then potentially mixed between the course site and the Media site. 

We don't use Comply at the moment, but was just checking it out when I came across this

**Comment by btopro** [comment]
ahh ok, that makes more sense now. this would be an argument for NOT sharing resources in my opinion but I see what the questions for about. This could be a good direction for comply to go though it would take a lot of lifting obviously. The goal of comply is to help w/ kind of knowing everything attached to a course. In this regard your right, multiple course references per media element would be needed though that's certainly an edge case to typical usage.

**Comment by btopro** [comment]
dropping this system as we consolidate what we'll actually ever get to in this life time among those experiments. Work in 0.13.x drops all the unused sub-domains.
