### ISSUE TITLE
Individual Contributor License Agreement

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2464]
Hey when you get a chance could the following people please fill this out:
- [ ] @yurg 
- [ ] @lizatgit
- [ ] @whereismyjetpack
- [ ] @kfurst

https://www.apereo.org/licensing/agreements/icla 

It will help us achieve full project recognition from the Apereo Foundation which is big deal in educational technology. Basically we need anyone who's got commits to the project in the past (or future) to fill one out and I've seen you all are credited with some. It only takes a minute and would be a huge help toward us achieving legitimacy.

**Comment by CheckeredFlag** [comment]
Done.

**Comment by pja12** [comment]
Hi Bryan

Glad to help. Can you give a bit more info on what agreement we’re signing on to here? And how this fits into our course(s)?

Many thanks,
Peter

Peter Aeschbacher
Associate Professor of Landscape Architecture and Architecture
H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape Architecture
Hamer Center for Community Design
The Pennsylvania State University

**Comment by pja12** [comment]
Hi Bryan,

Thanks for the info! All done, and best of luck on the projects!

Best wishes,
Peter

Peter Aeschbacher
Associate Professor of Landscape Architecture and Architecture
H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape Architecture
Hamer Center for Community Design
The Pennsylvania State University
