### ISSUE TITLE
Cookie-less domains

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#247]
While @heyMP and I were talking scale and the #165 , an interesting notion came up...

It might be useful to allow for a 3rd series of sub-domains to point to the same sources we have currently. Right now we have (for example) online.elmsln.local and data-online.elmsln.local. This allows for webservice calls to have to talk on the back channel and also helps in avoiding cache bleeding into people wanting HTML instead of JSON objects when going to addresses. Also a minor security thing hooked into it when running advanced authentication (like PSU does).

If we had an additional like nocookie-online.elmsln.local this could allow us to do a couple things:
- run the CDN module to deliver all static assets down this path, increasing performance via parallel DLing of resources
- create a cookieless domain that YSlow / Google PageSpeed complain about being unnessecary
- potentially give an alternate IP for access which could have all assets served up via Pound / Varnish, making it super fast without affecting other protocols that might not be happy w/ Pound

It's not really a lot of additional work, basically just making conf files, adding some additional lines that it tells people to copy and paste, etc. Now, it's a lot more domains to request when settings things up but MOST of the world has SANcerts at this point so that's a lot easier then it once was.

@bradallenfisher your viewpoint from "Pure speed" initiative?

**Comment by grayside** [comment]
Why not configure Varnish to ignore the cookies for static asset URLs?

**Comment by btopro** [comment]
so it can just strip off the ones it doesn't care about like that? Still kind of a varnish newbee even tho I'm running it a few places now

**Comment by grayside** [comment]
Yes, everything that Varnish does can be like a context module reaction to anything in the HTTP request.

Not sure about payload introspection but that would be a very subtle thing to hide in varnish if so.

**Comment by btopro** [comment]
Thank you sir. Well take that approach when the time comes and only use this for internal instances that conflict w. Our authentication system
