### ISSUE TITLE
Assignment Studio - Filter Users

### ISSUE THREAD

**Issue by Deb-G** [elmsln/elmsln#2471]
A faculty member brought to my attention that everyone is listed in the assignment studio including students, guests faculty, instructional designers, and admin. This makes it difficult for him to discern who needs to be graded, and would like to have a filter feature so that only students would be listed for him.

**Comment by btopro** [comment]
- @btopro make sure you backport the dashboard you gave Ben for doing this. Then instructors can hide people that shouldn't be there but we can't prevent from showing up
