### ISSUE TITLE
Share Options missing in ELMS Media

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2474]
The sharing options in the Media server aren't appearing.  This is where users can access the iframe embed url for the media asset.

![screen shot 2018-06-07 at 12 55 14 pm](https://user-images.githubusercontent.com/3428964/41114370-3fcec2f6-6a52-11e8-993c-8cb5e88df359.png)

**Comment by btopro** [comment]
wow we need to just redo this whole page anyway, lol but yes. they only appear on the edit form (tho then it probably has edit in the path)

**Comment by btopro** [comment]
#2476 if we rope this into here and #2483 then we wouldn't even need this page; we are very close to eliminating the need to go to the media system it all if we get searching down

**Comment by btopro** [comment]
![2018-09-24_15-15-31](https://user-images.githubusercontent.com/329735/45973511-b2667600-c00c-11e8-8edb-7f35752b1bdf.png)
now at the top of the render options page
