### ISSUE TITLE
Contextual links for static Media disappear when the static content contains tokens

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2482]
Bug:
- ELMSLN v0.8

As the title says, I've got a lot of content where the whole page is static content from Media. This content has tokens in it too (that are set up on the course site). When the tokens are included, the contextual links for the static content doesn't appear

**Comment by btopro** [comment]
I believe this was inception and sounds a lot like #2476 which would have the same solution ultimately as this. New HAX token resolution system just got pushed into 0.10.x and turned on by default a few hours ago (timely) though it will need an implication of in-context click to go to the underlying thing. Solving that UX flow problem for #2476 will solve it here; also this issue stemmed from drupal rendering out and trying to wrap the item; we've dropped this approach entirely bc of edge case bugs like what your mentioning. Instead we'll have the front-end generate the contextual links.
