### ISSUE TITLE
Vagrant VM has php 5.4 and 5.5

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#249]
@bradallenfisher any idea why this is happening? I know you witnessed it once and I also just noticed it while doing some local dev

**Comment by bradallenfisher** [comment]
yep

you have this
```bash
# using yum to install the main packages
yes | yum -y install patch git nano gcc make mysql mysql-server httpd php php-gd php-xml php-pdo php-mbstring php-mysql php-pear php-devel php-pecl-ssh2 php-pecl-apc php-mcrypt*
```

then later you have 

```bash
yes | yum -y --enablerepo=remi,remi-php55 install httpd php php-common
yes | yum -y --enablerepo=remi,remi-php55 install php-opcache php-pecl-apc php-cli php-pear php-pdo php-mysqlnd php-pgsql php-pecl-mongo php-sqlite php-pecl-memcache php-pecl-memcached php-gd php-mbstring php-mcrypt php-xml
```

I would say you could ditch the first instance since all the libs are coming along on the second then you will be sure not to have any leftover php references/pointers/conf laying around.

**Comment by btopro** [comment]
Ya, probably need to consolidate. MySQL is the thing currently difficult to use the auto installer w. BC the piped input changes. Maybe we should try to do both at once and fix the piped input cause it would speed up the install for sure. Right now the upgrades only apply after install on 5.3 PHP and MySQL 5.1

**Comment by btopro** [comment]
@bradallenfisher so if I run these commands myself it gets the right repo using remi. If I build during vagrant by consolidating the calls I get:

`fault:   mailcap.noarch 0:2.1.31-2.el6                                                 
==> default:   perl-DBD-MySQL.x86_64 0:4.013-3.el6                                           
==> default:   perl-DBI.x86_64 0:1.609-4.el6                                                 
==> default: Complete!
==> default: --2015-09-15 08:18:14--  http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
==> default: Resolving dl.fedoraproject.org... 
==> default: 209.132.181.24, 209.132.181.25, 209.132.181.26, ...
==> default: Connecting to dl.fedoraproject.org|209.132.181.24|:80... 
==> default: connected.
==> default: HTTP request sent, awaiting response... 
==> default: 200 OK
==> default: Length: 14540 (14K) [application/x-rpm]
==> default: Saving to: “epel-release-6-8.noarch.rpm”
==> default: 
==> default:      0K .......... ..
==> default: ..                                       100%  219K=0.06s
==> default: 2015-09-15 08:18:20 (219 KB/s) - “epel-release-6-8.noarch.rpm” saved [14540/14540]
==> default: --2015-09-15 08:18:20--  http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
==> default: Resolving rpms.famillecollet.com... 
==> default: 195.154.241.117, 2001:bc8:33a1:100::1
==> default: Connecting to rpms.famillecollet.com|195.154.241.117|:80... 
==> default: connected.
==> default: HTTP request sent, awaiting response... 
==> default: 200 OK
==> default: Length: 7351 (7.2K)
==> default:  [application/x-rpm]
==> default: Saving to: “remi-release-6.rpm”
==> default: 
==> default:      0K .......                                
==> default:               
==> default:  100%  272M=0s
==> default: 2015-09-15 08:18:25 (272 MB/s) - “remi-release-6.rpm” saved [7351/7351]
==> default: warning: remi-release-6.rpm: Header V3 DSA/SHA1 Signature, key ID 00f97f56: NOKEY
==> default: Preparing...                
==> default: #########################
==> default: #########################
==> default: 	package epel-release-6-8.noarch is already installed
`

Then it goes on to install PHP 5.3 :\

**Comment by btopro** [comment]
needed to separate the rpm's being built onto different lines for some reason. Last commit finally allowed it to pick up on the remi repo during installation. https://github.com/elmsln/elmsln/commit/196f9fd7ecc168520a05bf67ce7c21153fa75bef something for you @bradallenfisher if you have multiple rpm's in future vagrant / scripted files
