### ISSUE TITLE
ELM327 Problem

### ISSUE THREAD

**Issue by Benjhon** [elmsln/elmsln#2495]
Hi,

I bought 2 ELM327 with Bluetooth. With booth Adaptors i have the same Problem: I connect to Forscan Lite und run the Programm. A Popup appears: Please turn ignition on.
But the Ignition IS on. is there any troubleshooting available?

Please help. 

I didn't find the right solution from the Internet. 

References:- 
https://forscan.org/forum/viewtopic.php?t=1531
[Motion graphics video studio](https://jobs.vidzzy.com/hire-motion-graphics-video-animation-studio/)

Thanks!

**Comment by btopro** [comment]
wrong project sry
