### ISSUE TITLE
Adding Network Links to 'More Apps' Side Menu

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2500]
v0.10.x

I'm currently looking at an upgrade path from 0.8 to 0.10 and one of the things I'm not sure about it how to add a menu link to the 'More Apps' flyout menu using the edit network links page `/admin/config/user-interface/cis-lmsless-nav`

If I add the group as 'Network' it shows as an icon in the `etb-network-nav` bar just fine, but previously we were able to set the group as something custom like 'Company Links' and it would appear in it's own section here:

![image](https://user-images.githubusercontent.com/4973810/43831108-f0ad2bf2-9afa-11e8-9c47-b112cf51af7c.png)

**Comment by btopro** [comment]
![2018-08-09_08-19-09](https://user-images.githubusercontent.com/329735/43898746-c5470af6-9bad-11e8-8180-41d7969f983b.png)
 here's a snippet of code that put it there.

```
$vars['services']['Administrative']['piwik'] = array(
      'title' => t('Browser analytics'),
      'url' => 'https://WHATEVERWEUSEHERE',
      'machine_name' => 'dotgrid',
      'icon' => 'dotgrid',
      'weight' => 10,
    );
```

**Comment by btopro** [comment]
I think there's some additional group abstraction (its in 'services' now when previously I don't believe it was). This way more parts of the theme have access to this data being passed around for theming

**Comment by rickhumphries** [comment]
Ok thanks. What file is that snippet of code from?

**Comment by btopro** [comment]
implementing `hook_cis_lmsless_theme_vars_alter`

**Comment by JackWillDavis** [comment]
Hi Bryan, I know this has been closed now but I just wanted to check something with you. I've used the following code and it doesn't seem to allow me to add new links, even to predefined groups in that flyout menu.

```
/* Add Analytics Dashboard to the navigation links */
  $vars['network']['services']['Administrative']['piwik2'] = array(
    'title' => t('Browser analytics'),
    'url' => 'https://example.com',
    'machine_name' => 'online_dashboard',
    'icon' => 'dotgrid',
    'weight' => 10,
  );
```

Now, if I change **Administrative** to **Network**, I can get the menu item to appear in the top nav so I know I have the data structured correctly. It's just that no links are being added to the flyout menu, even if we use groups that are already established and I can see it's being hooked into properly with `hook_cis_lmsless_theme_vars_alter`.

What we're really after is doing something like:

```
$vars['network']['services']['Company Tools'][] = array(
    'title' => t('Browser analytics'),
    'url' => 'https://example.com',
    'machine_name' => 'online_dashboard',
    'icon' => 'dotgrid',
    'weight' => 10,
  );
```

Where there would be a new subheading of **Company Tools** added to the flyout menu with a link underneath that which would have a title of "Browser Analytics". The issue being that we can't get any links whatsoever to appear in that flyout regardless of how we try to structure it.

**Comment by heyMP** [comment]
The issue with `hook_cis_lmsless_theme_vars_alter` is that it executes after the menus have already been run through the theme function.  I added a new hook alter that executes prior to the theme function.

Usage: 
```
/*
 * Filter the 'More Tools' flyout menu to show only Analytics when in a certain user role
*/
function ob_cis_search_students_cis_lmsless_network_alter(&$vars) {
  $vars['network']['services']['Company Tools'][] = array(
    'title' => t('Browser analytics'),
    'url' => 'https://example.com',
    'machine_name' => 'online_dashboard',
    'icon' => 'dotgrid',
    'weight' => 10,
  );
}
```

**Comment by JackWillDavis** [comment]
Just confirming that this is solved our end with the new hook. Thanks!
