### ISSUE TITLE
Allowing for more specific CSS targeting on web components

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2501]
v0.10.x

I'm noticing that it's harder to apply specific style changes in 0.10.x with regard to certain elemets that use web components as maybe the classes applied don't allow for it anymore. 

For example, trying to change the menu header for this `lrnsys-drawer-modal` to green from black:

![image](https://user-images.githubusercontent.com/4973810/43831649-be557c7a-9afc-11e8-95ca-072046cf4d6f.png)

Also effects similar elements which aren't easy (or possible) to avoid:

![image](https://user-images.githubusercontent.com/4973810/43831721-f38581c4-9afc-11e8-915e-e062dd7f3f53.png)

**Comment by rickhumphries** [comment]
You know what - I'm starting to find workarounds for these. So maybe not such a big deal

**Comment by btopro** [comment]
we use the "shadydom" CSS processor for this reason. That way it is possible to still target things the way you would expect. If you run into issues targeting anything drop the code in an issue and we should be able to help point you at how to get it.  A lot of times finding the most specific selector in the dom when you inspect is enough to get you at least to the same level for something not previously defined, or at least be able to `!important` your way to success (at that selector that is)
