### ISSUE TITLE
Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2504]
Bug:
- v0.10.x

Having updated a course site on a development server to 0.10.x it seems that the keyboard shortcuts no longer work. E.g. double tapping the right arrow key doesn't take me to the next page anymore

**Comment by rickhumphries** [comment]
Oh OK. Has it been replaced with anything? I can't get any of the keyboard shortcuts to work like before (after pressing alt + shift):

![image](https://user-images.githubusercontent.com/4973810/44602236-de58c680-a7d6-11e8-82f5-f2822f5fc011.png)

And the guidance on the page still shows a double arrow tap:

![image](https://user-images.githubusercontent.com/4973810/44602262-fdefef00-a7d6-11e8-8ef4-6249b0c7169c.png)

**Comment by rickhumphries** [comment]
Ah OK - I can see how the next page keyboard shortcut works now. There are a couple of issues when trying to use these though:

- Pressing 't' for the course setting menu doesn't seem to work
- Pressing 'ctrl' to try and do 'ctrl+d' or 'ctrl+t' brings up the voice commander stuff too which can get in the way (although only for admin). Only 'ctrl+t' works out of these too
- Also 'o+a' didn't work for me, and the hax editor shortcut is the same as the help page one so this doesn't work either (it does take you to the help page though).

**Comment by btopro** [comment]
sorry, i didnt realize it was beyond the one

**Comment by btopro** [comment]
These have been removed in i2606
