### ISSUE TITLE
Impersonate Account > View - not working on course site

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2505]
Bug:
- 0.10.x

When on a course site and looking to search for a user via the 'impersonate account' link, I can masquerade as the user but clicking 'view' doesn't do anything. It should take me to their local user profile.

This functionality **does** work within the CIS and Media etc. Seems to be just on a course site.

**Comment by btopro** [comment]
this works from course site front door but is still an issue in apps. Writing as note to myself

**Comment by btopro** [comment]
appears fixed
