### ISSUE TITLE
MOOC - Content Headings on a Root Page are in Uppercase

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2506]
Bug:
- v0.10.x

This happens:

![image](https://user-images.githubusercontent.com/4973810/44789368-4c650b00-ab94-11e8-9760-2d4a2871871c.png)

Should be this:

![image](https://user-images.githubusercontent.com/4973810/44789400-67377f80-ab94-11e8-85d2-b68a7b9ba802.png)

But this rule isn't being applied...

```
#block-mooc-nav-block-mooc-nav-nav li.elmsln-book-item paper-button {
    border-radius: unset;
    text-transform: unset;
}
```

**Comment by btopro** [comment]
hmm, try putting !important flags on both. WC scoping makes it harder to hit those sorta things without more aggressive selectors

**Comment by rickhumphries** [comment]
I think it's because these buttons aren't wrapped in a li tag with the 'elmsln-book-item' class on it. I can fix it our end with custom CSS but just to let you know :)

**Comment by rickhumphries** [comment]
Using this instead:
```
.scrollspy-toc.table-of-contents li paper-button {
	border-radius: unset;
    text-transform: unset;
}
```

**Comment by btopro** [comment]
no longer able to generate this issue. appears fixed from your suggestion :)
