### ISSUE TITLE
Outline Doesn't Show if page is accessed via a direct link

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2507]
Bug:
- 0.10.x

If on the front page (we generally set this as 'mooc/book-homepage'), when clicking to view the book outline (the one that pops up in a modal) the outline is empty

**Comment by rickhumphries** [comment]
Edit - ah it's showing now. I switched sections to a course section, which sorted it. Then it still shows too when I've switched back to the Master Section. Maybe it's an initialization thing...?

**Comment by btopro** [comment]
May have been a first time thing bc that cXhe rebuilds independently of the rest of the front end. If it pops up on others let me know but my bet is caches weren't fully rebuilt yet

**Comment by rickhumphries** [comment]
@btopro this is still an issue I think - the problem seems to be when you go directly to the URL (or click any link that takes you there like the 'Course Outline' front page link). In those instance, the outline is empty.

 Whenever you then click next or previous page, it'll then show

**Comment by btopro** [comment]
would need a gif as I can't reproduce this

**Comment by rickhumphries** [comment]
Here we go - http://recordit.co/RKlGWq5f40

**Comment by btopro** [comment]
oh I see. and it's not a CSS thing hiding it? Seems to load really fast for "not being there" (on subsequent page load)

**Comment by rickhumphries** [comment]
Hmm I don't think it's a CSS thing. Inspecting the console and it just looks like the div is empty:

![image](https://user-images.githubusercontent.com/4973810/53030395-9c959980-3462-11e9-951c-4a3cdf085125.png)

Whereas it has content when it's there:

![image](https://user-images.githubusercontent.com/4973810/53030457-bafb9500-3462-11e9-8444-559e8e06a92b.png)

**Comment by heyMP** [comment]
Yeah definitely a weird one.  It seems that mooc-content is not executing an a request to `apps/mooc-content/full-outline` after cache clear, however, I can't seem to replicate it on my local instance.

**Comment by btopro** [comment]
this is fixed
