### ISSUE TITLE
Media Static Content - unable to get this to show in the course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2511]
Bug:
- v0.10.x

Previously I would create static content in Media and then use the share button to provide a token to render the body field of the node, then use this in the Course to render it.

The share button no longer exists so I've tried getting the token from the display options instead. The only one that seems correct here is the 'iframe' display mode, but I get an access denied message when using this `[ciscode|rev=1|tool=elmsmedia|item=1611|entity_type=node]` even though other Media items show OK.

![image](https://user-images.githubusercontent.com/4973810/44917493-64719180-ad30-11e8-8d41-e40c882e5a0d.png)

The other recommended display modes are 'media_svg' but these don't display anything at all. Neither does the following `[ciscode|rev=1|tool=elmsmedia|item=1611|entity_type=node|render=value|field=body|delta=0]` which is the token format I've pinched from our current ELMSLN version for rendering just the body field

**Comment by heyMP** [comment]
I've narrowed it down to an issue with the[ _cis_connection_object()](https://github.com/elmsln/elmsln/blob/0.11.x/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/cis_filter.module#L259) call that the theme function taps.  It appears that the token is getting deconstructed appropriately but there is nothing returned.

This doesn't appear to be an issue in 0.11.x.

**Comment by heyMP** [comment]
This appears fixed to be fixed in 0.11.x

**Comment by rickhumphries** [comment]
Yep - can confirm this is fixed. Thanks!
