### ISSUE TITLE
Cognitive computing feature enhancements

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#256]
It looks like IBM lets apps interface with their cognitive computing system for free: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/services-catalog.html

This would be really useful for accessibility features like speech to text and text to speech. Many other kinds of uses as well and could drive some of the AI features we are headed towards.

**Comment by btopro** [comment]
awesome. those two APIs would be good but this also sounds cool to pull into a social hub kind of system as well where it can do self analysis and what not if someone authorizes it (they'd have to)
