### ISSUE TITLE
ELMS/HAX integration list line-height issue

### ISSUE THREAD

**Issue by nikkimk** [elmsln/elmsln#2572]
Bug:
- 0.11.x / 0f153a26008959f8290c8b31f736a5b3e9c4e37a

- List item line height is different from other content, so it appears "broken" to IDs.  Paragraph blocks (<p>) have the following class applied to them, but ordered and unordered lists do not:
.elmsln-core-in-context {
    line-height: 2.5em;
    margin-bottom: 1.25em;
    text-rendering: optimizeLegibility;
}

**Comment by btopro** [comment]
are you saying to add this css to fix this or what's the remedy here?
