### ISSUE TITLE
admin.css rules apply to non-admin parts of the page

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2575]
Bug:
- 0.10.x

This particular rule in the admin css is actually targeting all links within the body when logged in as admin and so affects styling in the course materials themselves:

![image](https://user-images.githubusercontent.com/4973810/50107387-7ec17380-022a-11e9-9a18-97bf479ce30e.png)

**Comment by btopro** [comment]
really?? that scoping shouldn't unless adminimal-menu wraps the whole document. We can hack this :p

**Comment by rickhumphries** [comment]
Latest update has fixed this issue
