### ISSUE TITLE
Dropdown form element doesn't show

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2576]
Bug:
- 0.10.x

Dropdown options don't seem to show in any forms, e.g.

Editing a section, unable to select the instructional outline:
![image](https://user-images.githubusercontent.com/4973810/50119420-a58fa200-024a-11e9-8016-aafb83ce8e18.png)

Switching section menu, unable to select sections:
![image](https://user-images.githubusercontent.com/4973810/50119512-e38cc600-024a-11e9-8b29-fb6b190d6076.png)

**Comment by btopro** [comment]
anything weird your doing to achieve this? maybe the foundation access or materialize compatibility layers?

**Comment by rickhumphries** [comment]
Ah sorry yeh - it looks like this rule in the materialize css is the culprit

![image](https://user-images.githubusercontent.com/4973810/50155974-681c2a80-02c5-11e9-9613-58582b3c53d5.png)

**Comment by btopro** [comment]
are you using materializecss directly or is it in the unwinding directory? I'm trying to maintain compatibility as we collapse both of those shims each release :)

**Comment by btopro** [comment]
can you give me the full path to that file?

**Comment by rickhumphries** [comment]
Just found it and it's in a custom module actually so my fault. We have something called materialize_bridge which allows us to keep using modals and tabs etc. and it was in there
