### ISSUE TITLE
remove webcomponents from h5p embeds

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2582]
Bug:
- 11.x

- h5p embeds are slow, loading duplicate web components

Feature request:
- We should by default remove all web components definitions from all embeded h5p content types

Since H5P requires two separate iframes and each iframe is rendered through drupal theme layer, there are tons of duplicate web components being loaded for each embed.

Here is a potential fix:

![screen shot 2019-01-10 at 2 41 54 pm](https://user-images.githubusercontent.com/3428964/50993292-4a6a6b80-14e7-11e9-83ab-80b839f60e45.png)

Example.  This page has 4 h5p embeds on it.

Before:
![screen shot 2019-01-10 at 2 40 47 pm](https://user-images.githubusercontent.com/3428964/50993265-39215f00-14e7-11e9-9d8d-d9fb24de83ff.png)

After:
![screen shot 2019-01-10 at 2 39 46 pm](https://user-images.githubusercontent.com/3428964/50993340-6f5ede80-14e7-11e9-8120-9eae99170b14.png)

In addition to that fix, I think we could also remove `cms-entity.html` from being loaded as well.

![screen shot 2019-01-10 at 2 53 53 pm](https://user-images.githubusercontent.com/3428964/50993451-b351e380-14e7-11e9-9a12-7cc796ebe7cd.png)

**Comment by btopro** [comment]
I don't believe this will be an issue given the switch off V0 elements. We'd still see some duplicate loading but they'd be off of a CDN (even if just coming from the mediau system) and shouldn't be an issue. I'll just move this over to 11.x thread though and not close it
