### ISSUE TITLE
Foundation Access Iframe - Custom CSS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2583]
What's the best way to go about adding custom CSS to the `foundation access iframe` theme without making any changes to core?

Currently we've got themes set up for our courses which are sub-themes of `mooc foundation access`, but I'm not sure what the best way would be to approach this. I'm assuming just making a sub-theme of `foundation access iframe` wouldn't work? Do I need to include some reference to `foundation access iframe` in my custom course theme?

**Comment by btopro** [comment]
best way to get css in there is via a module that adds css to pages. This gets you the css you want and side-steps the whole theme issue. That way your CSS would apply to any theme so make sure it's just the css you need to work anywhere vs things specific for the normal sub-theme. something like `hook_page_build` with a `drupal_add_css` in it should do the trick

**Comment by rickhumphries** [comment]
OK thanks @btopro

**Comment by rickhumphries** [comment]
Would another way to achieve this be to create a sub-theme of `foundation access iframe` then reference that subtheme in the entity iframe settings `/admin/config/system/entity_iframe` ? Not saying we're going to do it that way, just for my own understanding - is that how it's currently working?

**Comment by btopro** [comment]
sub-theme would be overkill. You could just fork the theme and make your own then reference it as the theme to use when in "iframe mode". I'd still recommend the css via module piece though unless you have very specific ways you want to present stuff when in a frame.

You are correct you could have done it that way though if this was purely a learning exercise :), I just wouldn't recommend it cause it's overly complicated.
