### ISSUE TITLE
a11y-media-player youtube video scrubbing bugs

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2587]
Here is a video demonstrating some of the issues with scrubbing through a youtube video.

https://photos.app.goo.gl/ekbcPLTAh4xZiHkt8

**Comment by btopro** [comment]
Scrubbing?

**Comment by heyMP** [comment]
Seeking, advancing, fast-forwarding, re-winding, moving the slider for the non multimedia specialists.

**Comment by btopro** [comment]
@nikkimk

**Comment by nikkimk** [comment]
@heyMP I believe I fixed this issue a while back, so I can't replicate it on our media server. Are you using the most recent version and are you still having this issue? If there is still an issue send me a URL and how to replicate the issue.

**Comment by btopro** [comment]
haxtheweb.org

**Comment by btopro** [comment]
fixed in source files, builds in 0.11.x will resolve this
