### ISSUE TITLE
Issues with cog action options in outline designer

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2591]
Bug: v0.10

The cog dropdown options don't work as intended. I tried to create a new page within a chapter but, although it created a new page as content, it wasn't positioned within the book at all.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4973810/51390621-b1130900-1b27-11e9-8f9b-7885a03473b4.gif)

I also tried to delete content using the dropdown options but this didn't work either.

**Comment by heyMP** [comment]
@rickhumphries  I think this might be fixed in 0.11.x.  Can you verify on your side?

**Comment by rickhumphries** [comment]
@heyMP yes, you're right - I think this is fixed in 0.11.x, thanks.
