### ISSUE TITLE
Styling discrepancy between buttons on user flyout menu

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2599]
Bug:
- What happens

The buttons on the user flyout menu in v0.11 have different stylings based on the type of button they are.

In the screenshot below, you can see the "My Profile" and "Log Out" buttons are slightly smaller and further inset than the two middle links. Just looking to see if this is something seen across other instances of ELMS and how best to get around it if it's specific to us.

Is this something in ELMS which needs adjusting or would you just recommend we add a new class to the `<lrnsys-button>` components and try to target with CSS on our end (although I've not been able to edit with CSS so far).

![capture](https://user-images.githubusercontent.com/2301874/52703850-2fbc6400-2f77-11e9-87d8-eee1ca768907.PNG)

**Comment by btopro** [comment]
ummm... my guess is they are influenced by specific global CSS. while they should be the same styling, let's hold off on anything fixing this (unless u supply a PR) until after the ES modules migration as that will be shadow DOM / style scoped where as currently re roll shady DOM to allow for tweaks

**Comment by JackWillDavis** [comment]
Nice one, sounds like a good idea. I'll hold off until the ES migration is done 😃

**Comment by btopro** [comment]
I believe this is normalized in branch i2606 Closing and then once that branch goes through (bc it's a major change) we can review consistency issues again
