### ISSUE TITLE
CKEditor: Protected Source Issue

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2600]
Bug: ELMSLN v0.11

#### What happens
HTML comments are being incorrectly processed in CKEditor which results in large parts of content being wrongly wrapped by other tags, causing content to disappear.

I believe this is related to #2328 which I can see has been amended more recently in #2364. The changed `config.protectedSource` regex has a `/` prepended to it which has broken functionality on our end.

Changing the current regex from:

`config.protectedSource = [/<(!-{2,}|(\S*?)-(\S*?)\s*>)[\s\S]*?(<\/(\S*?)-(\S*?)|(-{2,}))>/g];`

to:

`config.protectedSource = [<(!-{2,}|(\S*?)-(\S*?)\s*>)[\s\S]*?(<\/(\S*?)-(\S*?)|(-{2,}))>/g];`

Fixes it for us but just wanted to see whether it was worth a PR or whether we are able to host our own CKEditor `config.js` file within the `config` folder so we can keep the different regex in our own repo?

**Comment by btopro** [comment]
does it continue to work with custom elements?

**Comment by JackWillDavis** [comment]
They do indeed:

![ckeditor-webcomponent-test](https://user-images.githubusercontent.com/2301874/53093003-1171dd80-350e-11e9-8313-5b2ce7cb19d8.PNG)

**Comment by btopro** [comment]
if that's in a body field and comments continue to work then please do issue a PR

**Comment by JackWillDavis** [comment]
Added PR #2601

**Comment by btopro** [comment]
awesome, thank you!
