### ISSUE TITLE
Convert Web components to ES module routines of V1 spec

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2606]
This is a major / breaking change for those that developed V0 spec elements via HTML Imports. We'll be switching to V1 spec elements that require import / ES Module integration routines.

I'll be starting a branch to work on this and it'll be merged in once we cut a 0.10.1 which will be the last release without ES modules in it. 0.11.0's mostly that change and cumulative bug fixes

bugs to fix:
- [x] studio edit form needs to be able to delete items
- [x] studio edit or view items need to pop up when selected, seems to be an issue in lrnsys-dialog (check slots)
- [x] delete button on comments not working
- [x] #2519 JSON blobs are being busted bc of our token processor (multiple-choice most obviously affected)
- [x] hitting delete in studio on 1st item removes 2 items (splice needs to only target 1 item prolly, video/link not having this issue but images and files are)
- [x] comment admin badge shows up way off right side of screen (and in edit form)

Push up to staging for remediation after these have been addressed

**Comment by heyMP** [comment]
![giphy](https://user-images.githubusercontent.com/3428964/53356047-88391d00-38f8-11e9-8e30-e6ac7c0464d8.gif)

**Comment by btopro** [comment]
not done. but a ton of progress on this

**Comment by btopro** [comment]
V1 elements are now in 0.11.x. Doing additional testing and clean up in staging to generate more issues in general but they appear to be working in all major browsers I've tested thus far.
