### ISSUE TITLE
Future Roadmap/Vision with HAX

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2614]
I think it would be good to document the ELMS:LN roadmap for the future and how it's envisiged the HAX side projects (HAX and HAXcms) and Drupal itself fitting into this.

Is the idea for ELMS:LN to adopt HAXcms as a service (e.g. for student portfolios), or is the end goal for it to replace Drupal entirely? Or something else?

What's the future of the project beyond Drupal 7 And is there a rough timetable for that direction to be decided by?

**Comment by btopro** [comment]
agreed; relation of the two has been expressed internally so def something we should hash out. Some important things for context
- HAXeditor is stand alone, works anywhere, ELMS:LN has the V0 version and I started integrating the V1 version last week (and all other elements for that matter)
- HAXcms wraps that editor and plays static files, including building offline capable PWAs automatically
- Neither has any user implications and very little back end functionality / decisions other then to publish stuff statically
- HAXcms abstraction currently called "I AM" is beginning to mirror a lot of the underpinnings of ELMS:LN as far as symlinkage, etc

Editorializing
- ELMS:LN is riding on Drupal 7, which isn't getting any younger
- Drupal 8 is not a viable platform to migrate to outright without an insane lift
- The future is not PHP for the bulk of student experience; PHP will stabilize into a static serving piece of the stack

Roadmap:
- HAXcms is a vehicle for getting people into HAXeditor, which is the vehicle for getting people engaging with and helping with our portfolio of 168 elements (as of writing). It will be it's own thing when communicated and happens to be something that's spun out of ELMS:LN, which has a lot of projects that never have really matured to mass adoption
- HAXcms helps provide additional testing to get HAXeditor great for ELMS:LN (same for the elements in there)
- ELMS:LNs content engine, primary piece that students engage with will be experimented with to have the following solution explored:
  - wire HAXcms INTO drupal, drupal being the backend, which HAXcms based on the way it was (intentionally) architected is just looking for a series of end points to get data
  - this would allow ELMS:LN to leverage HAXcms's design layer, providing more flexibility in design then previously existed and making the design / theme layer a lot more web component / headless
- Web components (currently in HAXeditor) are being wired into media.elmsln and the templates there hollowed out. HAXeditor is beginning to replace many (but not all) needs previously supplied by media.elmsln. This will allow us to use both
- For us internally, ELMS:LN's content layer is being seen as the way to do authenticated users as well as supplying an additional layer of user access.
- HAXcms will not be getting into the complex user management / authentication workflows that ELMS:LN does
- HAXcms isn't anywhere near scope to do things expressed in studio; we're seeing studio as being something that can be augmented by HAXcms to help share assets and simplify scope of studio.
- The more HAXcms powers the content area of the UI (basically taking Drupal content and spitting out JSON Outline Schema, something Potter's been working on -- https://www.npmjs.com/package/drupal-book-2-jos) the more we can let Drupal manage the saving and multi-user permission workflow side of the house and let HAXcms handle the rendering (so less random JS / css in the front end, much like when we 
Where is Drupal going?
- Into a LTS areas of the community, meaning some groups will supply security support
- https://www.drupal.org/documentation/9 -- "However, a large number of sites might still be using Drupal 7 by 2020, so we have decided to extend support of Drupal 7 until November 2021". That's official core support, after that there will be community contributor organizations that will support it, though I don't know what the date is on that.
- Drupal at that point is in a "Do we go Backdrop or Drupal 9?" something to be considered once we get closer to that date

Timing isn't set yet but objective is clear -- deemphasize Drupal's role, it'll still have a role of some kind most likely, but the focus is on front end to solve a lot of the UX issues we're not able to overcome. Just today we discussed a methodology of getting HAXcms to wire up to xAPI data stores and then ways of visualizing that on the front end for students as well as instructors (something currently only @rickhumphries has done at scale).

It would be good to know what custom and community Drupal modules you are currently using beyond our core. To see what core doesn't currently do that you extended it to do.

If you have other questions / concerns surrounding this current vision / roadmap let's hash that out in the open. I think as we get more and more functionality / needs met via front end assets, we'll be able to keep scaling Drupal down on the backend to be closer and closer to Drupal core. As a small example, all the MOOC modules as part of the install profile for content are almost made completely moot as a result of HAXcms. Things like book_title_override are also moot by haxcms. Outline designer is replaced in HAXcms. XAPI tracking, distributed media integration; effectively every aspect of ELMS:LN's mooc system minus user management and permissions can be handled by HAXcms.

We're also pursuing HAXcms for student portfolios though the integration aspect of this into elms:ln hasn't been discussed (it might happen, haven't fleshed out that approach far enough yet).

**Comment by rickhumphries** [comment]
Thanks for that clarification. That's really useful for us going forward in terms of planning. I'll write up a full list of custom and community modules that we use with some use cases shortly. I don't have any issues with the general direction of travel as you've described, it will just be a case of understanding a bit more about how to tackle specific issues as they arise, e.g. should we be writing a Drupal module or web component sort of thing

**Comment by rickhumphries** [comment]
And when I say "I don't have any issues with..." I obviously mean "I'm VERY excited about..."

**Comment by rickhumphries** [comment]
This is a list of the custom or community modules we're using and the use case for them:
## Online
We have our own content types set up here in order to represent the structure of qualification (course):
Course Module - the molecules of a course
Competencies - the atoms of a course (what needs to be demonstrated before a module is achieved).

We've also created additional fields on the course section field collection which allows us to reference course modules etc.

### OpenBadging
Module which allows us to set up a badge that can be awarded to learners when certain criteria have been demonstrated. The badge also allows us to attach a certificate template to it which the learner can optionally download as paper proof. This writes the learner's name and achievement date onto it.

### OB Learning Locker
Looking to improve how this works in terms of querying but essentially allows us to set up a list of xAPI statements that need to be recorded in order to demonstrate a competency or achieve a badge and will award the badge / achieve the competency automatically

### CIS Dashboard and Progress
Few modules which provide admin and learner views to a users' progress details.

### Learner Analytics Dashboard
An Angular application which is predominantly used by employers to view visualizations of learner progress / completion etc. We also have an AWS Lambda microservice which is used to do the progress / expected progress calculations that feed into this.  

### Private Messages / Automatic Messaging
This allows us to send messages to learners. We also have a couple of rules set up which sends a message to the learner if they're approaching a deadline date for one of their course modules.

### SAML SSO
Used to provide SSO with external assessment system

## Course / MOOC
### Webform
For context, the majority of our courses require that the learners have a named workplace training supervisor (WTS) in order to support them on their course. It's also important that the WTS is enrolled on their own course through which they learn the responsibilities that come with their role and what they're required to do (support the learner, facilitate discussions, observe learners demonstrating skills, invigilate assessments etc.). 

We use the webform module fairly extensively through the course for the learner to complete 'activity books' which they then submit to their WTS by entering their email address. The WTS receives these throughout the course and must then complete their own 'assessments and observations' webform (on the WTS course) to confirm that the learner has done everything required, which is then submitted to us for review.

I don't think the process as a whole is particularly elegant and we do get a lot of feedback re: missing emails etc. so I can definitely see a use case for some form of submission/workflow engine and a space where a WTS or teaching assistant can review work.

### Content Pathway
Within the **Online** setup we can specify which course modules are pre-requisites of others (and therefore which needs to be 'completed' first). The Content Pathway module allows us to add a course module dependency to a page:
![image](https://user-images.githubusercontent.com/4973810/55065143-38728080-5073-11e9-9100-c3004dc79f64.png)
The field is an autocomplete and makes an AJAX call to **Online**. When loading the page a call is made to check which modules the learner has completed, and therefore what content can be released for them to view. 

@JackWillDavis might want to elaborate but thought this demonstrated the need for a specific ELMSLN API that can be used for querying data across all the different systems.

## Media
### Captivate Player
I think the only module we've added here is a module which creates a new content type (Captivate Player) which allows for uploading a ZIP file of packaged 'e-learning'. Within the Captivate file itself we use the 'execute javascript' action to emit custom xAPI statements which we can then record in Learning Locker.
 
Happy to discuss any of these in any more detail or if any are worth collaborating on to work into core.

**Comment by btopro** [comment]
Prior to initial thoughts, I appreciate your enthusiasm. It is a heavy decision on my heart to have to more or less continue to walk away from the core piece of the platform (Drupal) that got us this far but it is largely not a bottleneck beyond the user management, complex data modeling.

To further clarify before:
- HAXcms has no relationship to other systems in ELMS:LN, so CIS, media, studio, etc, those are hanging out, leveraging web components, going to increasingly become more headless (already heavily are)

# As per your modules / customizations listed
Here are some thoughts on each group
## Online
That's fine. I think the schema generating capabilities we're discussing in HAXcms could help ease the need for this but we're not talking cis in anyway now.

## OpenBadging / OB Learning Locker / CIS Dashboard and Progress / Learner Analytics Dashboard
These should continue to work, though again, the work being pursued in HAXcms around learning analytics / xapi wiring / schema (for learning objectives) should be complementary -- https://youtu.be/BWwsJa_pyOU?t=398

A lot of what you've pioneered in this area both on capture and retrieval sides will be influencing what we construct and our xapi stuff will be opt-in (you can see @heyMP and I discussing his prototype around the time stamp in the video).

## Private Messages / Automatic Messaging
We haven't talked about anything related to this though some of Mike's needs around xapi and proactively emailing instructors might align here.

## SAML SSO
No impact

# Course / MOOC
From what you've showed me of your previous webform methodologies those would remain in a similar way. HAXcms would basically be "playing" content which Drupal has pre-rendered so this end user side is effectively the same thing the current AJAX'ed mooc player app is doing now. As we get expanded HAX capabilities hopefully we'll (all) be able to start reviewing the needs of web form / inline assessment and expanding it beyond what we have now (which you can see on haxtheweb.org is little self checks, single question feedback items).

Content Pathway and content unlocking could be a big deal as far as something that gets way easier (though would be untouched initially as well). We're talking about making all xapi statements sit in something on the front-end called "indexeddb" which acts like a little mysql database on the front end (simplifing here). We've discussed ensuring our xAPI statements always bridge through that piece.

So for example, student goes to page X, xAPI statement is emitted and stored in that local front end database.... and THEN optionally sent to the backend data store. This helps enable the following enhancements:
- courses can operate offline (theoretically) with students taking content, engaging with materials and then when they get a connection, the statements are sent to the backend
- when available, data can be visualized / leveraged locally. That could be building a chart (off local data so no load implication) showing the user where they've been or how they are tracking forward. It could also be done to say "unlock page B once we've got statements saying they did page A" but without any of that logic happening as complex web calls between different backends.

Querying capabilities between systems isn't affected in this either, pure push to get more and more on the front end.

# Media / Captivate Player
That sounds like something that would be useful for us to pull into core as long as there is no logic specific to your deployment in there. I don't use Captivate but it comes up constantly from people both needing a place to store them as well as "can I embed...".

**Comment by btopro** [comment]
so mike and I did a glance through the module set in mooc. Without thinking (if we had HAXcms doing the content presentation / UX layer in there) we were able to count 20+ modules we could disable in a matter of minutes. As I dug deeper I'd estimate we could disable 60 or more and replace it with a single "HAXcms for Drupal" module.

The closer you get to Drupal core the easier it'll be to get to 9 and beyond or give us good positioning to replace those aspects when we get there.

**Comment by btopro** [comment]
#2608 related

**Comment by btopro** [comment]
Think we hashed this out appropriately, closing out

**Comment by btopro** [comment]
https://btopro.gitbooks.io/elmsln-documentation/content/developer-guide/roadmap.html -- roadmap we DID have. revisiting this along with some internal documents / tasks today
