### ISSUE TITLE
Some css tweaks

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2616]
Saw @btopro was updating css for the top bar earlier today, so this might be good timing to adjust this. Long course names seem to get cut off. See image:

<img width="245" alt="Screen Shot 2019-05-09 at 1 31 03 AM" src="https://user-images.githubusercontent.com/1085304/57429602-b7beac80-71fa-11e9-9a3c-cc76e98ad8ff.png">

**Comment by btopro** [comment]
this css has been gutted in part of this reason but I'll make note to test w/ a long title

**Comment by btopro** [comment]
![2019-05-09_09-59-52](https://user-images.githubusercontent.com/329735/57459434-40603b80-7241-11e9-91c5-ef03d6a36d6d.png)
![2019-05-09_09-59-34](https://user-images.githubusercontent.com/329735/57459435-4229ff00-7241-11e9-92ca-e097862d6330.png)

title and subtitle input were much longer than whats even shown here
