### ISSUE TITLE
Bulleted lists not visible on edit page.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#262]
![screen shot 2015-09-28 at 12 21 20 pm](https://cloud.githubusercontent.com/assets/3428964/10141643/aca002e2-65db-11e5-9830-d3251bc0ec55.png)

**Comment by btopro** [comment]
Switch the admin theme to be mooc_foundation_access and see; I believe these settings get picked up if you run the spidering update but just change this setting in this course and see. if that doesn't get it, look at how textbook is currently configured in the ckeditor settings as far as what stylesheets it taps

**Comment by btopro** [comment]
has been fixed in newer builds / via auto-updating spider
