### ISSUE TITLE
Remove 'Canvas Course List' Menu Item from Core

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2623]
Just a suggestion as this would only be needed for those that have Canvas

**Comment by btopro** [comment]
err... where is that?

**Comment by rickhumphries** [comment]
shows up in the CIS

![image](https://user-images.githubusercontent.com/4973810/58273665-181c2500-7d89-11e9-86e4-2b5726645bc4.png)

**Comment by btopro** [comment]
oh. yea. :p
