### ISSUE TITLE
New ELMSLN Instance for Dev is forcing https

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2624]
I set up a new server and ran the command:

`apt-get update && apt-get -y install wget git && git clone https://github.com/elmsln/elmsln.git /var/www/elmsln && cd /var/www/elmsln && git checkout master && bash /var/www/elmsln/scripts/install/handsfree/ubuntu16/ubuntu16-install.sh buttercups bc buttercups.dev http admin@buttercups.dev yes`

I included `http` in the install script and not `https` but it is forcing me onto https still and so not loading the site

**Comment by btopro** [comment]
hmmm... it's possible that ubuntu 16 doesn't allow http but I'd have to see the server. I don't think we've set anything that would force at that level. Let's encrypt is free too so might be worth setting up to have it going; have you seen if the vagrant instance locally has this issue?

**Comment by btopro** [comment]
is this working?

**Comment by rickhumphries** [comment]
I couldn't get a cert working (and can't get vagrant to either) but then @JackWillDavis just spun up a new environment and there wasn't the same issue so I thought I'd just reopen if I come across the same thing in the future.
