### ISSUE TITLE
_elmsln_scripted module was not authored on installation

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2625]
Set up new Ubuntu 16.04 LTS server and installed fresh copy of ELMS:LN.

I noticed in the installation notes in the console it advises:

```
✻NOTES✻                                                       ║
║ There is a module that was authored during installation at    ║
║ config/shared/drupal-7.x/modules/_elmsln_scripted             ║
║ You may want to open this up and review it but it is your     ║
║ connection keychain for how all the webservices talk. 
```

However I can't see that this module has been authored. I can only see the `cis_examples` and `cis_implementation_example` directories

**Comment by btopro** [comment]
does this happen locally? I'll be honest I haven't used our install scripts in some time as it just kinda sits there and runs. Did you run the install as `sudo`?

**Comment by btopro** [comment]
looping into #2626 since a lot of these issues seem related to php 7.2 compatibility
