### ISSUE TITLE
Foundation JS Elements don't work in CIS 1.x

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#263]
Just curious why this seems to be the case. In MOOC I can use foundation js elements when editing a node etc. However I'm unable to do so when in our CIS - which we use as our 'publicize' service too.

This even extends to the 'X' not hiding the Drupal notification alerts, which I'm assuming is related?

![image](https://cloud.githubusercontent.com/assets/4973810/10162876/5ad62678-66a6-11e5-9ed5-ccbdf2ff66c8.png)

**Comment by btopro** [comment]
jquery_update probably not set to latest version.

`admin/config/development/jquery_update`

make sure this is on 1.10

**Comment by btopro** [comment]
Check jQuery version on jQuery update page

Wp8

-----Original Message-----

**Comment by rickhumphries** [comment]
Jquery version on both CIS and MOOC was 1.8. I've changed CIS to 1.10 but this hasn't made a difference unfortunately

**Comment by btopro** [comment]
might need to frag caches on server and in your local browser cache; jquery heavily cached / might be delivered via CDN

**Comment by rickhumphries** [comment]
Yeh flushed the cache but still have same problem. Also don't think it's delivered via CDN. None of the settings between MOOC and CIS at admin/config/development/jquery_update are different from each other

**Comment by btopro** [comment]
seeing a bunch of JS errors on the homepage, not sure if that's influencing -- PDFObject (dono what that is).

**Comment by btopro** [comment]
@rickhumphries give it a shot now; did some work on the instance to resolve a documented breaking change from 6 months or so ago and want to make sure it wasn't related to this

**Comment by rickhumphries** [comment]
Yeh thanks for helping us with that @btopro. I'm still seeing this problem, though my gut feeling now is that it's related to some of the custom stuff done by OB, as I think this was also a thing before we updated core. I'd say close the issue for now as it seems specific to us, and I'll ask OB to dig deeper
