### ISSUE TITLE
Help button aligned weirdly 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#2636]
On https://online.aanda.psu.edu/apps/lrnapp-cis the help button in the upper right has weird alignment/height that doesn't fall in with the rest of the stuff up there. Screenshot: 
![Screen Shot 2019-07-17 at 2 05 27 PM](https://user-images.githubusercontent.com/15616523/61399444-32abdf80-a89c-11e9-8e47-ad8f33b217c8.png)

it would appear that it happens everywhere the help button is. Here is a course page too...
https://courses.aanda.psu.edu/aa120/node/3
![Screen Shot 2019-07-17 at 2 08 06 PM](https://user-images.githubusercontent.com/15616523/61399570-6555d800-a89c-11e9-96c1-e877ee658054.png)

And here is my Firefox info: 
![Screen Shot 2019-07-17 at 2 09 06 PM](https://user-images.githubusercontent.com/15616523/61399601-77377b00-a89c-11e9-9879-bf71aecdaa55.png)
![Screen Shot 2019-07-17 at 2 31 03 PM](https://user-images.githubusercontent.com/15616523/61401137-ca5efd00-a89f-11e9-86cb-103e6baf85bd.png)

**Comment by nikkimk** [comment]
It works fine on the most recent version of Firefox. We screen shotted Katrina's version of FF (60.7.2ESR), where you can see the following styles are being applied which aren't applied in recent versions:
#etb-course-nav .top-bar li a lrn-icon {
    margin-left: 0.5rem;
    line-height: 5rem;
    height: 5rem;
}

To fix the issue, remove that.

**Comment by btopro** [comment]
fixed thank you. Firefox ESR / Edge / IE11 / Safari 10.1 all have to use polyfills for shadowDom. That's why there's any style inconsistency. ShadowDom native stuff ignores these global styles so bleed through things like this are still in here and there and usually are just solved by removing things :)
