### ISSUE TITLE
Download button alignment

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#2637]
The download button/icon takes up two lines on a page. This is more of a "this looks strange and unpolished" level of issue. 
Screen shot: 
![Screen Shot 2019-07-17 at 2 10 56 PM](https://user-images.githubusercontent.com/15616523/61399798-e01ef300-a89c-11e9-982e-1b5e58c233e9.png)

page link: https://courses.aanda.psu.edu/aa120/node/3

**Comment by btopro** [comment]
verify in firefox for me but looks good now on my end (this was goofy in chrome too)
