### ISSUE TITLE
Studio Submission View Not Working

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#2638]
Course link: https://studio.aanda.psu.edu/aa120/apps/lrnapp-open-studio

This is a "needs to be fixed asap because people are currently using it" level of problem. However, it's only impacting Firefox... 
![Screen Shot 2019-07-17 at 2 09 06 PM](https://user-images.githubusercontent.com/15616523/61400179-b4503d00-a89d-11e9-874c-b90cf902dec5.png)

**Comment by btopro** [comment]
resize the window and tell me if it fixes it

**Comment by kat-wehr** [comment]
resizing the window does not fix

**Comment by btopro** [comment]
fixed
