### ISSUE TITLE
Implement HAX

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#264]
Rows
- Columns MUST be dropped into rows
- Can be dropped into Columns
- Can be dropped next to each other

Column
- Must be dropped into Row

Content
- MUST be in a column

Shortcodes..
- make a data attribute for shortcode
- data-shortcode
- data-tool
- [x] @heyMP  - View mode / templates thing / tokens
- [x] I make a meta controller to return the rendered output of a view mode - This happens in the ['rendered'] property
- [x] Shortcodes updated to reflect auto generation of these
- [x] snag calls going out the door (to self) and process in same request
- [x] CodePen.io to react to from @michael-collins 
- [x] Make this http://codepen.io/michael-collins/pen/memxpe

Adding things like...
- [x] Elements - These live in MOOC as a text based content type with a few fields
- [x] Media / Interact / other sources thing
- [x] click between paragraphs or on paragraphs
- [x] need to know the order of the paragraphs
- [x] Predefined layouts that you can drop stuff into place holders

Some more thoughts
- Static html page (maybe php, if so, limited)
- Dom manipulated by app
- Angular / material css
- Yaml for buttons / elements
- Buttons have html structure
- Structure properties included  can be editable
- Yaml defines options

Take inspiration from wp project but theirs is too complicated

**Comment by btopro** [comment]
rendered is already available in master

**Comment by btopro** [comment]
Great tutorial for the contextual links inline w/ HAX http://dominiquedecooman.com/blog/drupal-7-tip-add-contextual-links-anything

**Comment by heyMP** [comment]
Very nice.  I really like the idea of keeping the contextual links pervasive.  I think we might want to change their default UX to make it more modern and mobile friendly.

**Comment by btopro** [comment]
+1 I view it as a baby step

**Comment by btopro** [comment]
Ball is in @michael-collins court to make something for us to react to on the UI side
@heyMP is working on templates / partial elements
I need to make sites able to intercept the calls to themselves and process locally

**Comment by btopro** [comment]
added http://codepen.io/michael-collins/pen/memxpe to the doto list; first step. get a menu hook into drupal's bootstrap that at least has this in place, then start to deconstruct it as to how it's functioning and start to dynamically load it into existing content. Then make it so that existing content can be manipulated and correctly saved in this manner.

From there were can work on builder / add workflows

**Comment by btopro** [comment]
http://jqueryui.com/sortable/#connect-lists sortable jquery UI classes / functions; not sure if we want to use these / try and transition our current draggable / droppable structure to this.

**Comment by btopro** [comment]
@michael-collins can you mock up (and I don't know how this works structurally atm) a way that we could click on an item, it's selected and then you can delete / edit / etc. I think it would make sense to click a paragraph, then hit edit on it but that's not even the initial use-case I'm thinking; would want to be able to easily delete things. This could hang off the element like the current ::before usage supplied via the "Spacebar to select this" accessibility stuff currently

**Comment by michael-collins** [comment]
Okay, so more like the original hax mockups. I can do that.

**Comment by michael-collins** [comment]
@btopro FYI: http://www.layoutit.com/build

**Comment by michael-collins** [comment]
Check this project out! http://neokoenig.github.io/jQuery-gridmanager/, MIT Licence - https://github.com/neokoenig/jQuery-gridmanager/

**Comment by btopro** [comment]
nice steps in the right direction

**Comment by btopro** [comment]
courses.elms.psu.edu/sing100/sites/all/modules/local_contrib/hax/libraries/hax/hax.html w/ voice stuff and starting to read off file system. Biggest deal is that it's stand alone code base and templates to match as well as voice based inserting of items. Obviously way more to do but the decoupling is a big deal

**Comment by btopro** [comment]
- [ ] drag and drop manifest file so you can customize additional css/js to load js fiddle style
- [ ] materialize style layout
- [ ] elements / widgets to drop down can be transformation way zoomed out versions of the actual items with a layer placed over it to trigger the click
- [ ] clone elements so jquery still maintains event handlers
- [ ] make it so page area can be converted back into additional reusable templates
- [ ] mode to toggle off _hax classes / data attributes which will need to influence style

**Comment by btopro** [comment]
#1855 now makes it possible to start to even dream of doing this

**Comment by btopro** [comment]
Current prototype https://lrnwebcomponents.github.io/hax-content/components/hax-manager/#hax-manager

Still working through issues with the inline components as well as the overall editor.

**Comment by btopro** [comment]
0.20.0 of HAX will ship in 0.10.0 of ELMS:LN. Closing. an issue about an idea we opened almost 3 years ago when the technology needed to create it didn't exist.
