### ISSUE TITLE
display semester info from CIS

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#2644]
CIS should be able to pull together more logical section names than external data (when getting beyond master). @rickhumphries do you do anything with multiple sections?

**Comment by rickhumphries** [comment]
How do you mean? We do use multiple sections per course yeah. In terms of having a more reader friendly label for the access string, that would be a good idea

**Comment by btopro** [comment]
![2019-07-31_14-11-21](https://user-images.githubusercontent.com/329735/62239477-f18af380-b3a2-11e9-8ac9-cef54531e36e.png)

![2019-07-31_14-11-50](https://user-images.githubusercontent.com/329735/62239484-f2bc2080-b3a2-11e9-88a0-9c869b08b700.png)


pulls semester/year from CIS

**Comment by rickhumphries** [comment]
Is it optional? We don't use semester years. How about a text box you can add tokens to instead? Then that displays in place of the access string

**Comment by btopro** [comment]
hmm... what about a developer hook to hijack it and put whatever you want there. The commit is pretty minimalist in that it asks CIS for the section, if there are results, then it prints the semester / year data. Any mutation of data based on the specific way it was sliced sounds a lot more like a drupal_alter hook to allow modification based on specific needs.

Are you thinking a specific field in CIS that you'd want to access for this or some kind of permutation of a field(s)?

**Comment by rickhumphries** [comment]
A developer hook would be fine for us. 

I was just thinking for anyone new coming to the project (potentially) it would be most useful just to be able to type out the 'section title' that you would want to be displayed. If you wanted to type out the semester dates with that then you could just do that

**Comment by btopro** [comment]
True. Thinking of what a settings page for that would look like I see a scenario where 

`hook_cis_lmsless_section_title_alter(&$section_title, $section_id, $section_cis_record)` added which will be given a string of the current title so then you can modify it as needed. It also passes along the key of the section and what CIS returned as results data associated with it already.

Example from source:
```
$cisSectionData = _cis_connector_transaction('section', 'default', array(), $key);
      if (isset($cisSectionData['host_entity']['field_semester']['und'][0]['value'])) {
        $sections[$key] = strtoupper($cisSectionData['host_entity']['field_semester']['und'][0]['value']) . $cisSectionData['host_entity']['field_year']['und'][0]['value'] . ' - ' . $value;
      }
      // allow developers to hijack this / make it as they need displayed
      drupal_alter('cis_lmsless_section_title', $sections[$key], $key, $cisSectionData);
```

alters are pass by reference so any change to what was passed in via $sections[$key] (which is a string representation of the title of the section) will be influenced.
