### ISSUE TITLE
View Studio projects nav display

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2648]
**Describe the bug**
Studio project filtering navigation partially obstructed.

**To Reproduce**
1. Go to 'studio'
2. Click on 'view studio projects'
4. See the navigation is partially obstructed

**Desktop:**
 - OSX
 - Browser: chrome

<img width="1313" alt="Screen Shot 2019-08-06 at 12 45 55 PM" src="https://user-images.githubusercontent.com/1085304/62559303-b2e4b580-b848-11e9-9a39-93d9f1b707ea.png">

**Comment by btopro** [comment]
get a bigger laptop

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/77387774-a7f17d80-6d64-11ea-9cdd-c10d8f50a27b.png)

fixed in upcoming release
