### ISSUE TITLE
[elmsln] default development domain enforces HTTPS

### ISSUE THREAD

**Issue by Sjord** [elmsln/elmsln#2678]
**Describe the bug**

I installed ELMS LN using the [example deploy](https://github.com/elmsln/elmsln/blob/master/scripts/install/handsfree/ubuntu16/example-deploy) command. This configures ELMS to run plaintext HTTP on domain elmsln.dev. The problem is that the [.dev TLD](https://domains.google/tld/dev/) is [HSTS preloaded](https://hstspreload.org/?domain=dev), so my browser only wants to connect with HTTPS, and ELMS doesn't run there. 

**To Reproduce**

1. Install ELMS using the default values.
2. Browse to http://online.elmsln.dev/, as instructed by the installer.
3. The browser connects with HTTPS and shows an error message, or the default Apache page.

**Expected behavior**
I would either expect ELMS to run on HTTPS, perhaps with a self-signed certificate, or that it uses a domain that works with plaintext HTTP.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Firefox and Chrome

**Comment by btopro** [comment]
that sounds awesome; would love an automated way of doing that.
