### ISSUE TITLE
Features Warning Notice: Undefined index: group in views_handler->ui_name()

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#268]
I'm curious if anyone else has run into this Notice message when going to export a feature in ELMS. When I click the *Create Feature* button I get the following error message at the top of the screen: 

    Notice: Undefined index: group in views_handler->ui_name() (line 277 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/views/includes/handlers.inc).

It does not appear to be affecting anything with feature export or the over all User Experience, but I can do a bit of research on why this error may be appearing.

**Comment by heyMP** [comment]
I haven't yet.  I wonder if it has anything to do with the `views_ui` module being disabled by default?

**Comment by btopro** [comment]
agree w/ @heyMP I'm guessing it's related to views UI not being enabled but see if it goes away before and after that happening

**Comment by btopro** [comment]
Can confirm it's happening for me and also happening regardless of Views UI being enabled

**Comment by mmilutinovic1313** [comment]
I can also confirm it happens regardless of enabling.

**Comment by mmilutinovic1313** [comment]
From a cursory glance and a little research, this seems to indicate that there is a value that the code is trying to get that isn't accessable: 

"The cause of this is code trying to access a value (such as 'uid') that hasn't been added to the query."

    $value = $this->get_value($values, 'uid');
    
"get_value() searches for 'uid' among aliases, the aliases array doesn't have such a key, a notice gets thrown."


https://www.drupal.org/node/1103234

**Comment by mmilutinovic1313** [comment]
I have posted in the Views issue queue to try and get this issue resolved. The thread is 5 years old, but was never resolved. I will continue investigating this issue, by monitoring the thread and looking for possible patch solutions.
