### ISSUE TITLE
Add HTML 5 elements to the list of allowed tags

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#269]
To allow the WYSIWYG templates to render the components from the styleguide we need to add some new HTML5 tags to the list of allowed tags in the textbook editor.

Some tags that can be added:
 - figure
 - figcaption
 - details
 - aside
 - article

**Comment by btopro** [comment]
<figure> <figcaption> <details> <aside> <article> <div> <fn> <object> <embed> <param> <h2> <h3> <h4> <h5> <h6> <em> <iframe> <video> <strong> <img> <blockquote> <cite> <sup> <sub> <p> <ul> <ol> <li> <dl> <dt> <dd> <a> <table> <tr> <td> <th> <tbody> <thead> <tfoot> <colgroup> <caption> <hr>

currently allowed list in this filter

The other standard filter is the student input filter which currently allows:

<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd>

**Comment by btopro** [comment]
should be good on this now, repoen if not
