### ISSUE TITLE
AJAX Error during Features Autofill (APC File Missing?)

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#270]
![ajaxerror](https://cloud.githubusercontent.com/assets/7243665/10257508/e17bb216-6925-11e5-88cb-a0e581427ae9.png)

Upon being prompted with an autofil response of "Foundation Access" this AJAX HTTP error appeared on the page. It seems that there is something about a file in APC not loading or existing. Has anyone else encountered this bug?

**Comment by btopro** [comment]
when did u build the vagrant instance? Not sure that's stiill there anymore but has to do w/ upgrading everything during install and APC is depricated for APCu (its stupid yes)

**Comment by btopro** [comment]
rebuild the VM and let me know if it's still an issue w/ the latest code if it is we can tackle it then.
