### ISSUE TITLE
Update Foundation Access Templates

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#272]
I changed some of the components markup in the style guide that need to be reflected in the wysiwyg templates.

**Comment by btopro** [comment]
not sure the best way to do it but we might need to have some way that these templates read their import data directly from the html examples in the style guide. Again, I don't know how possible / simple that is but if this starts to become a regular thing then it might be worth doing for uniformity no matter how they are brought in

**Comment by heyMP** [comment]
I was thinking that too.  I ultimately want to switch the style guide into [PatternLab](http://patternlab.io/), it's way more robust and a lot nicer to manage the templates.  Also, I'm fairly certain that you can use phptemplate engine which would allow us to pull the templates into other parts of Drupal.

**Comment by btopro** [comment]
given the PR I merged we'll assume this is closed for now
