### ISSUE TITLE
Link to add a new course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#273]
I can't for the life of me remember what the relative link is for the add new course / system setup wizard in the CIS. Can anyone post it for me please? Thanks in advance

**Comment by heyMP** [comment]
Is this it?

`https://online.ed.science.psu.edu/cis-quick-setup`

**Comment by btopro** [comment]
ya

**Comment by rickhumphries** [comment]
Hmm, ours seems to have blown away

![image](https://cloud.githubusercontent.com/assets/4973810/10265739/e2e96a84-6a34-11e5-9966-5db9b76494ca.png)

**Comment by btopro** [comment]
check slack, was related to the upgrade
