### ISSUE TITLE
Adding Links to Account Menu

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#279]
Is there a recommended way of adding some custom links to this menu:

![image](https://cloud.githubusercontent.com/assets/4973810/10343257/e1fdf166-6d14-11e5-9037-708169ef458a.png)

This would just be an interim measure to allow our students to navigate back to their dashboard (currently built in the CIS). So I'd like to add a "online.[website].co.uk/dashboard" link there

**Comment by btopro** [comment]
hmm... maybe we'll need to support a block area of some kind there which could provide a menu. @heyMP thoughts?

The snowflake slide out does provide linkage to other places and has hooks that can be used to modify. There's work to be done to open up a UI to allow site builders to say what icon, name, and link they want in that space. Planned but def not there yet.

**Comment by btopro** [comment]
account menu is now a block #374 so it can be modified via sub-theming foundation_access/templates/cis/cis-lmsless-user.tpl.php provides an example that produces the current iteration (with user picture, name, etc)
