### ISSUE TITLE
PDF Libraries

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#280]
We're looking to do a bit of development work to include the PDF libraries which would allow us to generate PDF versions of the Book Outline from a single click. We'd basically then be able to build all our content via the MOOC as the primary authoring platform (rather than building and formatting in Word first).

In one of the early mockups done by @michael-collins I remember seeing the PDF icon here,  

![image](https://cloud.githubusercontent.com/assets/4973810/10367502/cbf91c88-6dc8-11e5-982b-dad5a2885d4c.png)

And also I've noticed these modules:

![image](https://cloud.githubusercontent.com/assets/4973810/10367585/4116f436-6dc9-11e5-90e0-4d517b69c381.png)

Is this functionality on the roadmap? If it is we'd be happy to work on this (pull-request?), but would want to do it so that it's inline with 'the vision' style-wise etc. so it can be easily incorporated back. Also, any experience/thoughts on the best PDF library to use?

**Comment by btopro** [comment]
So at this point in the development of browsers it's more about what is a PDF netting you? The reason I ask is because there's the print version which is currently under the chevron / "tabs" menu in the top right of the page. If you print a page, it pushes it to a print format and then snags everything under it and puts it on the same display.

From there, every browser now supports print and then "save to PDF" or print to PDF. So if there are other formatting / copyright things you are pushing into the PDF i'd say ok, pursue PDF mode. If it's just to get someone a digital copy, I'd just tell them how to print to PDF.

**Comment by rickhumphries** [comment]
Yeh we're governed by policies which dictate that we have to offer a paper version if our courses. 

The print/save to PDF route would work but after saving to pdf the majority of the CSS styling is lost. So think we'd need one of those libraries installed to get the paper/pdf copy looking polished. I thought while we were at it, if we could make two clicks into one to get there, we would :)

**Comment by btopro** [comment]
hmm... really? well ok. Another reason to go the PDF route other then clicks is that you could allow "print course" and "print this lesson" and "print this page" kind of granularity

**Comment by rickhumphries** [comment]
Yeh that would be cool. I haven't tested those modules yet. Tried switching one on but looks like I also need to copy some files across at the back end too. 

I've been trying to go 'fully online' for years but never been able to for that reason. Figured though that if I can use ELMS MOOC as the primary way to author and version everything then produce the PDFs from there (instead of Word) when required then I'm pretty much there.

**Comment by btopro** [comment]
nice! yeah we'll definitely accept a PR for it as long as it meshes w/ the UI. I'd actually put this under accessibility because it's an alternate / enhanced form. @michael-collins may have thoughts on how he'd like to handle it though.

**Comment by rickhumphries** [comment]
We've done a bit of testing on a fresh Drupal install, and would like to test a bit more on the MOOC distro, but think the most compatible library to use is wkhtmltopdf. 

For any interactive content types (H5Ps mainly) we've been adding the '.hide-for-print' class, and for any videos we embed within the content, we've been adding a '.hide-for-print' class - and also have a <p> tag with the '.show-for-print' class that basically says, "you can watch a video on this topic at this url: http://www.youtube.com//". Just mentioning this in case @heyMP wants to bear something like this in mind for the style guide video components :)

**Comment by rickhumphries** [comment]
So we've finally managed to configure wkhtmltopdf into something workable. Writing out a guide below just in case it's useful and you wanted to work it into Core. I did this on my test server (CentOS 6.5)

### Installation
I pretty much directly followed this guide to install wkhtmltopdf on our server: https://jaimegris.wordpress.com/2015/03/03/how-to-install-wkhtmltopdf-in-centos-6-5/
With the exception that downloading from the sourceforge website didn't work, so I used the direct link from the official downloads page (http://wkhtmltopdf.org/downloads.html)

I then put the wkhtmltopdf (and wkhtmltoimage) executable files at this directory:
elmsln/config/shared/drupal-7.x/libraries/wkhtmltopdf
And then added a symlink to this in: 
elmsln/core/dslmcode/stacks/courses/sites/all/modules/local_contrib/print/lib
I'm not sure how recommended that is (having the symlink in core) but it was recommended (https://www.drupal.org/node/2276275#comment-9705155) when reading up about it.

### Setup
I switched on the following modules in Courses:
- PDF version (print_pdf)
- Printer-friendly pages UI (print_ui)
- wkhtmltopdf library handler (print_pdf_wkhtmltopdf)

Which should let you configure things here: /admin/config/user-interface/print/pdf
![image](https://cloud.githubusercontent.com/assets/4973810/11808401/487c63ee-a318-11e5-8c01-be3350d4a8b0.png)

### Print CSS
It took me a while to figure out that when generating the PDF, it actually doesn't recognise any CSS that is within a @media print {} wrapper. So anything like this added to the theme CSS won't work. This was a particular problem for using the Foundation classes '.hide-for-print' and '.show-for-print' as we use this to make interactive activities hidden in the PDF and replaced with something else. 

The workaround I've used in testing is to use CSS Injector and set up a separate rule:
![image](https://cloud.githubusercontent.com/assets/4973810/11808640/81b0843c-a319-11e5-940c-a0fa56f1a3f6.png)
Add your custom CSS, but also source the CSS wrapped in @media print {} within the app.css file and add this in here too. This will not only allow you to use the '.hide-for-print' and '.show-for-print' classes but also automatically add/avoid page breaks for elements like headers and quotes etc.
Uncheck the 'Enable Rule' option:
![image](https://cloud.githubusercontent.com/assets/4973810/11808661/9a19349c-a319-11e5-9939-f7c731fb4b9f.png)
Then in the Printer,email and PDF versions settings (/admin/config/user-interface/print/common) add a reference to this CSS file as a custom stylesheet:
![image](https://cloud.githubusercontent.com/assets/4973810/11808696/e707c9d0-a319-11e5-900f-2ace7f0ce9c4.png)

### Adding Margins, Footers and Headers
You can control these by using the wkhtmltopdf manual (http://wkhtmltopdf.org/usage/wkhtmltopdf.txt) and adding elements here - /admin/config/user-interface/print/pdf/wkhtmltopdf
E.g.
![image](https://cloud.githubusercontent.com/assets/4973810/11808903/44af0d5e-a31b-11e5-9e1f-ae3cf3743f69.png)

### Font Issues
For a while we had a big problem with the Droid Serif font not rendering properly in the PDF 
![image](https://cloud.githubusercontent.com/assets/4973810/11808982/ad32b380-a31b-11e5-8165-a1a4eab118d8.png)
(and documented here - http://stackoverflow.com/questions/34202631/drupal-wkhtmltopdf-font-error)
What we did was add the following CSS to get this to work:
```
@import url(//fonts.googleapis.com/css?family=Droid+Serif|Georgia:400);
  body, p, p a {
  font-family: "Droid Serif", "Georgia", serif;
  }
```
And that seemed to do it. 

This may seem like a relatively small thing but is actually going to make a huge difference for us in terms of authoring content from a central source (through elmsln) and then being able to produce high quality formatted print materials for students who are on paper versions of our courses, as well as a great online experience, and not having to alter the content in separate places :smile:

**Comment by btopro** [comment]
@rickhumphries awesome guide! We'll need to add this into the one-line installers / try to get this automatically installed on the backend (which was why I was hesitant to pick one) but I think we could definitely use this

**Comment by btopro** [comment]
@michael-collins what's that doc converter then that'll give you stuff in any format?

**Comment by michael-collins** [comment]
http://pandoc.org/

**Comment by btopro** [comment]
http://chromatichq.com/blog/converting-drupal-text-formats-pandoc could be a starting point for someone to write / implement though pandoc requires a level of backend system access that's...aggressive to say the least

**Comment by btopro** [comment]
@rickhumphries is this working for you? Playing with it today and trying to get support for wkhtmltopdf out of the box but it's throwing notices / not doing anything. wondering if there's any additional configuration beyond it just being there

https://www.drupal.org/node/2276275#comment-8852617

**Comment by rickhumphries** [comment]
@btopro It worked for us when we installed it last year after going through the steps above. I'll try and go through the steps again later on tonight to see if we can replicate.

**Comment by rickhumphries** [comment]
@btopro quick query, did you put the symlink in?

**Comment by btopro** [comment]
No i didn't

**Comment by rickhumphries** [comment]
I remember coming across the issue you've linked to. I followed the advice outlined here https://www.drupal.org/node/2276275#comment-9709151

And so put the wkhtmltopdf (and wkhtmltoimage) executable files at this directory:
elmsln/config/shared/drupal-7.x/libraries/wkhtmltopdf
And then added a symlink to this in: 
elmsln/core/dslmcode/stacks/courses/sites/all/modules/local_contrib/print/lib

**Comment by rickhumphries** [comment]
@btopro I did manage to get this working again after installing a fresh copy of ELMS:LN on a CentOS 6.8 x64 server.  Steps I took after installing ELMS:LN were.

1. Download some dependencies. The wkhtmltopdf downloads page (http://wkhtmltopdf.org/downloads.html) mentions 'zlib, fontconfig, freetype, X11 libs (libX11, libXext, libXrender)'. And the tutorial (https://jaimegris.wordpress.com/2015/03/03/how-to-install-wkhtmltopdf-in-centos-6-5/) mentions 'xorg-x11-fonts-Type1' and 'xorg-x11-fonts-75dpi'. So I ran:
`yum install -y xorg-x11-fonts-75dpi
yum install -y xorg-x11-fonts-Type1
yum install zlib-devel`
I think the other dependencies might come with CentOS already.

2. Download and install wkhtmltopdf. I installed a slightly older version just because I'm not really confident unpackaging .tar.xz files directly on the server so I wanted to stick to the guide. So I ran:
`wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm`
Then installed:
`rpm -Uvh wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm`

3. So the wkhtmltopdf and wkhtmltoimage files should now be in the location `/usr/local/bin/wkhtmltopdf`. I moved these files to `elmsln/config/shared/drupal-7.x/libraries/wkhtmltopdf` then added a symlink to this folder at `elmsln/core/dslmcode/stacks/courses/sites/all/modules/local_contrib/print/lib` again.

4. I then created a new course in ELMS:LN and switched on the relevant modules and followed the rest of the guide as described.

I'll share my login details to the server via backchannel if this helps.

I've seen that dompdf library has been installed instead at the moment. I've read that dompdf can only handle more basic CSS styles, whereas wkhtmltopdf is maybe more flexible and generates PDFs more efficiently. But I only say that from a small amount of experience (last year) and bit of Googling rather than anything more concrete than that.

**Comment by btopro** [comment]
@rickhumphries lol that's amazing. ok so I think what we'll do for now since this is working is let domPDF play out. it's a lot easier to maintain / install (what's there currently will work for *everyone* without repo inclusion). If there are issues / requests that stem from this level of capability we'll address them. If WK is the clear winner / we can do some A/B comparison and see that it's worth upgrading to that then we'll move that direction down the road.

The nice thing is that print module can swap out PDF engines without changing paths so we can swap these things out at will without dramatically impacting whatever solution is used / primarily supported.
