### ISSUE TITLE
User list page is blank (in course-outline) 

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#282]
Noticed that the user list when in the MOOC (/cis/user-list) isn't showing a list of any users. I'm logged in as admin

![image](https://cloud.githubusercontent.com/assets/4973810/10411287/af5a4e04-6f57-11e5-8255-25ef26109868.png)

**Comment by btopro** [comment]
probably related to role ID in the view not being updated to match roles in the system. @mmilutinovic1313 should be a good one for you to track down. most likely in cis_service_connection_ux or at least somewhere in the submodules of cis_connector.

**Comment by btopro** [comment]
this should be resolved since the #66 went through
