### ISSUE TITLE
Master Section Question

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#284]
When I update a section of a course, for example, something running in Spring 2016, the master course updates as well. I was under the assumption that the master was to stay static and then the courses I built off that would be their own unique and individual elements. Could someone please explain? Thanks.

**Comment by btopro** [comment]
shouldn't, may need to check it out w/ you sometime and see exactly what's going on.

admin/config/system/course-settings -- settings for the space in general, master will inherit these

cis/section-list and then editing an individual section will only apply to that section in question

**Comment by heyMP** [comment]
Are the sections suppose to share the same book outline?  Melissa is trying to change content in one section without that content surfacing in another section.  In this example we have two different instructors teaching the same course in different sections.

**Comment by btopro** [comment]
They can if setup to use the same. New section != new outline. It assumes its the same course. You need to clone the content outline and then associate the right one to each section in question

Wp8
________________________________

**Comment by juststormy** [comment]
Well...
I'm also updating a fall section and the master is changing with the updates. I thought the master was to stay static?



-----Original Message-----

**Comment by btopro** [comment]
I think the changes @heyMP made in #144 and #393 and #391 should help alleviate this confusion. also adding a page to the documentation now.
