### ISSUE TITLE
.ferpa-protect class for hiding protected work and properties in plain sight

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#286]
A mode that forcibly rewrites all calls for data from the username / first / last name. These fields are the reason why you can't demo a course to someone (PII). If we could switch into a mode that hid this info we wouldn't have this issue. Look into something like https://www.drupal.org/project/realname and how it works.

- session flag
- if present on user_load; forcibly rewrite the username / f / l name on load (might be too aggressive but we'll see)

**Comment by mmilutinovic1313** [comment]
Looking into the module for reference

**Comment by btopro** [comment]
@mmilutinovic1313 everywhere the user name / Pii is printed we could also wrap these properties in some data- attribute which could be targeted via this mode and then hide everything from view. The idea isn't that the data in all places is 100% sanitized in code; it's that screens could be safely displayed with real (yet js / css based anonymized) content. imo that is

**Comment by btopro** [comment]
this video shows adding ferpa-protect to anything will lock it up to a button so that you can legally give people a tour of your course https://www.youtube.com/watch?v=-KCp88XHIgc

**Comment by btopro** [comment]
enhancements left to do
- [ ] store session cookie for the state of the privacy checkbox
- [ ] apply elsewhere
