### ISSUE TITLE
Test Coverage Discussion

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#289]
Hi all -- 

So I am about to begin working on adding some test coverage to different parts of the system to help with expiditing the development process. We have the overarching travis test for the whole system, but I was thinking of something like a MADLIB travis-ci .yaml file or other testing medium for things like new feature creation. 

I wanted to get some feedback from everyone in terms of what areas might be priority areas to set up test routines for and if there are any systems other than travis that could be used for local or global testing.

Let me know you-guyses / yinz's thoughts!

- Mark

**Comment by btopro** [comment]
BEHAT would be good; @heyMP can point in the right direction on that.

We've got some test coverage on cis_connector which could be extended / used to provide guidance on writing tests for SimpleTest / Drupal 7. https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/cis_connector.test

cis_connector then uses travis to run the tests via drush; see here for how easy it is to run tests via drush -- https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/.travis.yml#L83

**Comment by btopro** [comment]
needs to turn into actionable tasks. go with Behat. submit issues / PRs when you get stared
