### ISSUE TITLE
Documentation for creating course specific theme overrides

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#291]
Decide what the best method would be for adding custom css/js...
- [ ] per site created
- [ ] per network created (course network wide)
- [ ] per section (maybe, might get expensive)
- [ ] per service (maybe)
- [ ] network wide
- [ ] Document process

Need a code based solution as well as a UI based solution and documentation on when to use one vs the other.

**Comment by michael-collins** [comment]
First question is, who would need to alter css/js? If it's an instructional designer, there should be a ui involved of some kind. The more power they have to alter, the happier they typically are, but the more likely they can do things in an unsustainable way. If it's developers only, then some kind of sub-theming method might be appropriate.

**Comment by btopro** [comment]
https://www.drupal.org/project/css_injector if we're talking unsustainable / spot fixes; what's the actual problem trying to solve tho? As mike nailed it, need to document the right workflows; also, can we get a https://readthedocs.org going for this kinda thing?

**Comment by btopro** [comment]
we now have documentation on read the docs and it can be modified by just editing the md files in the /docs folder. Pleases document this stuff there. http://elmsln.readthedocs.org is what's generated automatically off of new commits.. wow.

**Comment by rickhumphries** [comment]
I'd say I'm probably in the bracket of instructional designer and don't really know anything about sub-theming, but enjoy creating and making custom CSS/JS components. 

In terms of workflow at the moment, when I set up each Course (currently just having the Course Outline service), I've got about 10 .txt files which I copy and paste into either a CSS Injector rule, or for a WYSIWYG template import so I've got different style elements such as a 'yellow box with icon
![image](https://cloud.githubusercontent.com/assets/4973810/10819068/03148bfa-7e3e-11e5-9c71-bdd52f423c36.png)
For some courses I also wanted to alter how the H2 tag looked but still take advantage of the magellan sticky nav, so I targeted .etb-book h2 with CSS injector to get this look instead:
![image](https://cloud.githubusercontent.com/assets/4973810/10819269/0d228e20-7e3f-11e5-98b1-11e5a080520f.png)

Anyway, to answer @heyMP 's first question - I thought CIS-2.x might be the place for allowing you to set these CSS rules/style templates up. Then you could have a 'Styles' tab for each Course where you can associate any previously created CSS rules/template elements to the course, and this would be where they're referenced from?

**Comment by btopro** [comment]
what you describe is why drupal failed at a college so it's not trivial (css needing added globally kinda stuff). Two thoughts; if your doing things that aren't repurposable, then maybe css_injector.

@rickhumphries I think this is a really cool idea though of having assets that are injected from remote so we could do a kind of application of styles / js that can be added everywhere and not do it in code.

Now... it's a hell of a lot more performant to do it in code and making a module to accomplish this and have it be "global" isn't hard (we have tons of examples). So I guess it's an issue of... do you have access to your server and are you wanting to do this in one place in CIS and have it propagate.

Another less expensive option, module that lets you upload css/js files and another module that lets you point to files and include them. Dono, agree we need a few different options and will update the bullet points at the top to include global css / js

**Comment by btopro** [comment]
@rickhumphries Is the "Personal Development Plan" a heading that applies a style? If so I really like that idea of making a section kind of visually stand out aside from just being a header

**Comment by rickhumphries** [comment]
@btopro Yeh I added the following to CSS Injector (might not be the cleanest css but works!);
```
.etb-book h2 {
    color: #474747 !important;
    font-size: 1.25rem !important;
    background: -moz-linear-gradient(left,  rgba(255,241,148,1) 50%, rgba(254,252,234,0) 100%); /* FF3.6+ */
    background: -webkit-gradient(linear, left top, right top, color-stop(50%,rgba(255,241,148,1)), color-stop(100%,rgba(254,252,234,0))); /* Chrome,Safari4+ */
    background: -webkit-linear-gradient(left,  rgba(255,241,148,1) 50%,rgba(254,252,234,0) 100%); /* Chrome10+,Safari5.1+ */
    background: -o-linear-gradient(left,  rgba(255,241,148,1) 50%,rgba(254,252,234,0) 100%); /* Opera 11.10+ */
    background: -ms-linear-gradient(left,  rgba(255,241,148,1) 50%,rgba(254,252,234,0) 100%); /* IE10+ */
    background: linear-gradient(to right,  rgba(255,241,148,1) 50%,rgba(254,252,234,0) 100%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fff194', endColorstr='#00fefcea',GradientType=1 ); /* IE6-9 */
    padding: 10px 5px 10px 20px;
    }
```
So all `<h2>` tags appear like that and it'll work with the sticky nav too.

Like you said, it works well for sectioning off different parts of the content within a page.

**Comment by btopro** [comment]
@heyMP might be nice to have some style treatments for headings like this kind of a thing (not exactly but the idea of it)

**Comment by heyMP** [comment]
The css/js inject is good, but I was thinking of something like @bradallenfisher's method.
https://drupal.psu.edu/blog/post/dynamically-switching-themes-using-sass-and-1-drupal-theme

Where we can have the theme looking on a folder called "overrides" for css/js files matching a pattern that correlates to the course.

i.e. I can easily add new css files to the `chem110` course if I create a file called `custom--chem110.css`

**Comment by btopro** [comment]
@heyMP this still predicates uploading a file into a certain location (which is fine, just saying we'd need to allow for that). But this also assumes someone has that kind of access to the server.

These custom override methods could be a folder in foundation_access that symlinks into the config directory into like a `config/shared/drupal-7.x/css` or something and then if the files are named correctly it shows up; we could also make a folder in CIS that allows uploading css files and selecting what they should override, then writing them to the right location. This would allow both approaches of SFTP / git empowered user base and end-users / form only users.

**Comment by heyMP** [comment]
I think that we would need to allow for both.  Having the option to add arbitrary CSS/JS via a GUI as well as giving users with server access the ability to upload custom CSS/JS files that could be trackable via git.

**Comment by heyMP** [comment]
Related #152

**Comment by btopro** [comment]
check this one out -- https://www.drupal.org/project/cpn seems like a successor to css_injector

**Comment by btopro** [comment]
merging with #1623
