### ISSUE TITLE
Replace Outline Designer autosave with form save button

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#294]
### Problem
When dealing with large book outlines, editing titles and reordering hierarchies can become slow, and in some cases, fail to correctly update the book pages.

### Proposal
Move the 'autosave' ajax functionality into an optional setting and add a `save` to the outline.

**Comment by heyMP** [comment]
@btopro I know that we had talked about this at point.  Just wanted to get your thoughts one this.

**Comment by btopro** [comment]
#131

**Comment by btopro** [comment]
#160

**Comment by btopro** [comment]
#223

**Comment by btopro** [comment]
There are a bunch of things that imply a redesign of Outline designer is coming in the 3.x branch and this is something I've kicked around as well. It would make more sense to do a bunch of operations, checking w/ the backend that they are ok but not actually committing them, and then hitting save / doing the "YOU WILL LOSE CHANGES" / allowing for undo'ing stuff prior to save

**Comment by btopro** [comment]
before
![2016-08-22_16-20-19](https://cloud.githubusercontent.com/assets/329735/17870195/642b1a0e-6884-11e6-89ae-e4afca8f11b0.png)

**Comment by btopro** [comment]
after clicking
![2016-08-22_16-20-44](https://cloud.githubusercontent.com/assets/329735/17870204/6a604d68-6884-11e6-874d-7d550778577c.png)

**Comment by btopro** [comment]
this allows you to disable the outline designer's ajax capabilities in order to do bulk updates of hierarchies; necessary for when you get into larger structures till we refactor OD entirely.
