### ISSUE TITLE
Create space for the Live Question authority

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#296]
To align development efforts with ELMSLN and the Live Question tool I'm currently developing for a faculty member, would you be able to set up a stub authority for `lq`?

![screen shot 2015-10-21 at 12 55 22 pm](https://cloud.githubusercontent.com/assets/3428964/10643836/06573b92-77f3-11e5-9ba8-19955fcb3f97.png)

**Comment by michael-collins** [comment]
+1 this request!

**Comment by btopro** [comment]
space created for it; need a new thread for describing what LQ does and adding it into the documented acronyms / roadmap / what it is this does

**Comment by btopro** [comment]
closing for full description as we now have a space for this: #299
