### ISSUE TITLE
Setting up network form

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#297]
@michael-collins has stuff layed out for how you manage stuff in CIS after the fact but not workflows for how faculty can create course networks. Hibbits makes me realize how simple we need to make this or people just go and do their own thing anyway (which is not a bad thing at all!).

So, super simple form:
- course name
- Big icons, select the applications you will use or add new ones to your network
- build

When it's done it emails you that your network is ready. This creates the defaults for this course, requests tools or adds in external applications along side them and builds out the network visual. Select screen can be like the rock institute homepage w. Big icons and descriptions -- http://stem-researchethics.org/ I don't know if this has been announced yet but should be shortly.

**Comment by michael-collins** [comment]
Well, actually I did a long time ago, in a far away land: https://invis.io/XWY26074

But, considering my design ethos now, this mockup is still too complex. We need a thoughtful design for this, not just "big icons" ;)

**Comment by btopro** [comment]
continuing here -- #405
