### ISSUE TITLE
Student feedback on interface

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#301]
## Everything
- [x] Snowflake needs a menu button text like: "Menu"
- [x] chevron needs to make more sense from a dropdown / what the hell is it perspective

## Studio
- [x] Submission dropdowns need open by default
- [x] Color for save needs to be an actionable color

**Comment by michael-collins** [comment]
@btopro We talked about adding an edit (pencil) icon next to the chevron. Personally, I think all that stuff under the chevron should go somewhere else and we should get rid of that button, and just have the edit icon. @heyMP and I talked about replacing the snowflake with the menu (burger icon) with the dropdown indicator since the snowflake is not really a known icon for navigation. Actually, anything with a drop menu associated should have that drop arrow indicator, much like github's navigation, so we also need to update the breadcrumbs. I like the snowflake from a branding perspective, but no one would know to click on it to access the other applications...

**Comment by btopro** [comment]
"the three lines make no sense that it's a menu" -- so please stop making this assumption. An interface designer understands the burger, I have talked to many people that do not.

**Comment by btopro** [comment]
snowflake with "menu" or "course" or something that indicates textually it's a button; right now we have a mix of buttons w/ text and others without

**Comment by michael-collins** [comment]
The entire thing at the top is a menu. We originally had apps there. To me, that makes the most sense as a label as it's the most descriptive.

**Comment by btopro** [comment]
ahh yes let me ask, but I think so

**Comment by michael-collins** [comment]
I'll do some variations.

**Comment by michael-collins** [comment]
Are you have a design meeting right now? And I wasn't invited :(

**Comment by michael-collins** [comment]
Variation 1:
https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-1.png

**Comment by michael-collins** [comment]
variation 2: https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-2.png

**Comment by michael-collins** [comment]
Variation 3 and 4: https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-3.png | https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-4.png

**Comment by michael-collins** [comment]
Variation 5: https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-5.png

**Comment by michael-collins** [comment]
Variation 6: https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-6.png

**Comment by michael-collins** [comment]
And per your earlier statement: '"the three lines make no sense that it's a menu" -- so please stop making this assumption. An interface designer understands the burger, I have talked to many people that do not.' - My response was that the burger icon was known as a navigation icon (many use it, so technically true) as compared to the snowflake icon (no one uses it, ever). I was not arguing that it was the best option, just a better one that what we currently have.

**Comment by btopro** [comment]
@michael-collins I'm also wondering if something that points to the 4 things you need to care about to use any of these tools wouldn't help too.

**Comment by michael-collins** [comment]
@btopro Can you clarify? Which four are you referring to?

**Comment by michael-collins** [comment]
Variation 7: https://github.com/michael-collins/images_assets/blob/master/elmsln/top-bar-variation-7.png

**Comment by btopro** [comment]
Chevron, Snowflake, Hamburger, Map, the things you immediately see that have no label and could be confusing out of the box.

Chevron - Actions
Snowflake - Network
Hamburger - Menu
Map - Course outline

I really like Network since we're talking things outside of just our own system, this is part of a larger learning ecosystem

**Comment by btopro** [comment]
I think @rickhumphries might have some thoughts on these guys

**Comment by btopro** [comment]
Hamburger was also not expressed as confusing as I thought, it was the notion of "two menus".

I know @michael-collins hasn't liked the design pattern of off-canvas items for other tools in the network and I'm inclined to agree; these items it either would make sense to always be visible like in a left column or tabs at the top. The tabs part above views (for example) would help get these non-edit options out of the chevron

Also having an optional left-nav of where you are, puts this menu visible at all times and then reduces the number of menus to 1; which if labeled "network" it's easy to say "Click on network" and it always makes sense. Course could be double purposed since we have a course system (that drives the outline of the course) and the notion of "course" in general. It's not bad, just could get confusing. Menu would also work, it's just the easiest / boring :)

**Comment by michael-collins** [comment]
Okay, let's evaluate when and how these menus would need to be used. I am fighting to keep the interface as clutter free as possible so that content reigns supreme, so a permanently visible menu needs a clear use-case justification.

**Comment by btopro** [comment]
Here's some examples so we can point to what has started to pop up in context of different systems using this off canvas;

Studio: left fly out things that people need to navigate around to get to different aspects of the studio

![2015-10-26_13-06-33](https://cloud.githubusercontent.com/assets/329735/10736337/c26ef0e8-7be2-11e5-8804-232a170f14da.png)

**Comment by btopro** [comment]
Discussion boards

![2015-10-26_13-06-13](https://cloud.githubusercontent.com/assets/329735/10736359/e5d91f18-7be2-11e5-92c2-17b132394941.png)

**Comment by btopro** [comment]
Journal / Blog

![2015-10-26_13-05-57](https://cloud.githubusercontent.com/assets/329735/10736368/ee7bf3b6-7be2-11e5-8a7f-877b629f8152.png)

**Comment by btopro** [comment]
Interact, which has lots of displays / capabilities though this is my instance which runs ahead of the distros that are more usable:

![2015-10-26_13-05-37](https://cloud.githubusercontent.com/assets/329735/10736382/02646b88-7be3-11e5-8dec-2ffe512ddeb1.png)

**Comment by rickhumphries** [comment]
Yeh I know what you mean for the snowflake thing. I still kind of like it though, and I do think sometimes as a user, you tend to just learn what icons mean. So the facebook notification icon is a globe, and the twitter one is a bell. You just get used to both without having associated these before. I'm not a UX expert though and maybe that's just me being unforgiving.

I think all it really needs is the text next to it, to indicate what it is.If you want to replace snowflake though, I'd be tempted to use something resembling the multiple square icon that both Google and Office use:
![image](https://cloud.githubusercontent.com/assets/4973810/10742205/db9b2e74-7c23-11e5-85ac-435ae3bec618.png)

'Tools' is another option for the name of it maybe? Apps or Network are good too.

I think using joyride is an excellent idea and would try to use that in someway to convey how the navigation works. I actually think having the flyout menu for 'Help' works well, and link to joyride could be in there. Also being able to add your own help pages to the flyout menu would be useful, but that's getting a little off topic

**Comment by btopro** [comment]
![2015-10-27_10-23-37](https://cloud.githubusercontent.com/assets/329735/10760806/cf0636e2-7c94-11e5-8252-ee4e7e02798f.png) Starting point down the right path, we need a label on the snowflake. I like the snowflake because it represents us and is different. Like you said rick, people learn what icons mean so long as it's intentional.

**Comment by btopro** [comment]
Network word is there for now but should be able to be overridden via settings page

**Comment by btopro** [comment]
next interface iterations account for all listed issues from student feedback
