### ISSUE TITLE
Admin theme - adminimal

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#303]
ran into this on another project, looks awesome. @heyMP any experience w/ this:

http://adminimal.netsite.gr/

https://www.drupal.org/project/adminimal_theme

**Comment by heyMP** [comment]
Yeah, I've used it before.  I like it.  It ships with C.O.D.

**Comment by btopro** [comment]
@mmilutinovic1313 you want to take this one? Add that theme in the right place and then make a crush recipe that swaps out the old admin theme with this one and well configures it.

**Comment by mmilutinovic1313** [comment]
On it!

**Comment by mmilutinovic1313** [comment]
Do you want Dev or Stable? Also put in core dir or put in custom themes dir?

**Comment by btopro** [comment]
Stable prefered unless it causes issues. Core dslmcode shared drupal7 themes Ulmus

Wp8
________________________________

**Comment by mmilutinovic1313** [comment]
This should be done as long as the PR looks good :)
