### ISSUE TITLE
UI Components List

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#304]
Master list of components to be updated or created (accessible and mobile/responsive):

**Navigation & Layout**  
- [ ] Magellan Sticky Navigation
- [ ] Breadcrumb Dropdown Nav
- [ ] ToC Outline
- [ ] Modals (left slide out, submit, what else?)
- [ ] Top Bar
- [ ] Tool Bar
- [ ] Footer
- [ ] Double column 100%
- [ ] Left Sub Nav
- [ ] Right Sub Nav
- [ ] HAX UI

**Content Styling**  
- [ ] Lists
- [ ] Tables

**Features**  
- [ ] Inline Discussion
- [ ] Side by Side critique interface #317
- [ ] Filters and search
- [ ] HAX Drag and Drop Content Elements

**Buttons and Icons**
- [ ] Add Button
- [ ] Animated Snowflake

**Comment by michael-collins** [comment]
@heyMP Add whatever is missing here so I can jump into designing when I get free time.

**Comment by btopro** [comment]
closing this, Materialize and #271 being included
