### ISSUE TITLE
H5P Embeds from Media

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#305]
Before upgrading to the newer UX in Media I'd use H5P's own embed option to grab the embed code needed to place in the Course Outline:
![image](https://cloud.githubusercontent.com/assets/4973810/10817320/edd36c28-7e30-11e5-8b7f-fa0b9b157f97.png)
I've just noticed that now this bar doesn't appear, even when these options are selected in the setup (I also think these options may have been different previously):
![image](https://cloud.githubusercontent.com/assets/4973810/10817348/1d300814-7e31-11e5-806d-b0f7d4aa35bb.png)
I wondered if anything had been changed to alter this behaviour?

Tried using the Share button too, but there doesn't seem to be code in the for just embedding.
![image](https://cloud.githubusercontent.com/assets/4973810/10817392/521c560e-7e31-11e5-8a43-0550c93bcfce.png)

**Comment by btopro** [comment]
go to `admin/config/system/h5p` and select that you want the option to use that method.

**Comment by btopro** [comment]
If this lets you fix it close it out but I think it will

**Comment by rickhumphries** [comment]
Yep this has fixed it. Nice one
