### ISSUE TITLE
TinCan xAPI Statement Structure

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#306]
This is to provide a base for discussion around how xAPI statements should be structured in relation to the ELMSLN course network and detail any potential issues. I'll provide a starting point with an example statement from a H5P activity in our deployment:
![image](https://cloud.githubusercontent.com/assets/4973810/10819586/cd6105c6-7e40-11e5-8bfc-b65a00e1ff18.png)

I'll step through where the different values come from for each area and some of the issues I potentially have with these.

### Actor
```
{ 
"name": "Cheryl Cole-849"
"mbox": "mailto:cheryl.cole@example.com"
 }
```
The name is the username of the Drupal user with their UID appended to the end, and the "mbox" is the email address of the user. "mbox" is a type of Inverse Functional Identifier with the specification stating:
- An Agent MUST be identified by one (1) of the four types of Inverse Functional Identifiers (see 4.1.2.3 Inverse Functional Identifier);
- An Agent MUST NOT include more than one (1) Inverse Functional Identifier;

There are [other options](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#inversefunctional) but It's difficult being restricted to one IFI (although I understand why they've done that). I'm not satisfied with how we've set it up at the moment, as our students can actually change their email address in the dashboard so "mbox" in this regard is a bad choice (and why we've also added Drupal UID to end of the name), but limiting the ID to one that's specific to Drupal or any other internal LMS seems to go against the principles of a student's data being transferable and being owned by them.

### Verb
Verbs are kind of determined already by the H5P output, but as we spread this out more throughout the network we should make sure we use [TinCan recipes](https://tincanapi.com/recipes/) to make sure statements are consistent for certain activity types.

### Context
```
{ 
"platform": "Customer Service Course for Delivery Drivers"
 }
``` 
This shows which course the statement took place within. This isn't actually where I wanted this information to sit but it's ended up that way. I actually wanted the following as I think this more accurately represents the spec:
```
"context": {
{ "grouping" : [
        {"id" : "http://courses.buttercupstraining.co.uk/csdeliv"}
    ]  
}
}
```
But there's other [context options here](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#context) where we could pass things like Section ID (section access string?), Service type etc. so these should be decided

### Object
```
"object": {
        "objectType": "Activity",
        "id": "http://courses.buttercupstraining.co.uk/csdeliv/node/44",
        "definition": {
            "name": {
                "en-UK": "Unit 6 Homework Questions"
            }
        }
    }
```
Here this picks out the URL that the H5P has been embedded on as the "id" and gives the "name" as the node title. One problem I have with this is that it almost prevents two learning activities being added to the same page, as both would have the same "id". There somehow needs to be a reference back to the original H5P instance of this in Media (or wherever we're embedding from).

Hopefully this will kick off a good discussion for how xAPI will work within the ELMSLN environment. Happy to spin off any of these points into their own issue if required

**Comment by btopro** [comment]
on user: UID can vary per tool in the network (were yours to get larger) so just saying. username like $user->name is a primary key that can't be changed (Bakery / all SSO gets pissed about this). Email address I hear you on but that might be a hard one to have people modify; Maybe there's like a registered email vs whatever their actual one is as a field difference in ELMSLN.  Another idea here is that $user->init is created and stores the INITIAL email address used to register an account. This prevents duplication of the email even if they change their email after the fact. So sending this instead could be a primary key / relatable even if they switch their communication preference email after the fact (https://api.drupal.org/comment/18324#comment-18324).


No comment on the other two parts at this time but definitely things we need to hash out and thank you for getting this going :)

**Comment by rickhumphries** [comment]
Yeh I think you're right about having the initial email address register for identification and then make sure there's a separate field for email address that's for communication. 

In fact, just noticed that a field for this already exists:
![image](https://cloud.githubusercontent.com/assets/4973810/10885924/9fa8def8-8177-11e5-89e8-77c4a4157e2f.png)

So will make sure we consider this from now on

**Comment by btopro** [comment]
@rickhumphries if you use the ->init value from the user account I think this will help solve this. It ensures that drupal knows the initial registration email address and it also makes sure this isn't duplicated. You'd be able to do queries off of this address safely even if their primary account address has been updated.

**Comment by btopro** [comment]
Need to patch tincanapi_get_actor in tincanapi module in order to allow for the ->init function though I think I'll up the flexibility in general there
