### ISSUE TITLE
Add different heading options to the styleguide

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#307]
In reference to the thread on #291, it might be nice to have a few header styling options so that we can visually breakup the sections without changing the semantic markup.

**Comment by btopro** [comment]
aligning these with pedagogy could be huge. If your talking about an assignment with a heading like
## Fundamentals of Design
And this label was an assignment / call to action, you could construct a standard way of creating headings that implies we're about to talk about an assignment.

**Comment by btopro** [comment]
http://red-team-design.com/cool-headings-with-pseudo-elements/

**Comment by btopro** [comment]
#591 provides 1 alternate style via "san-serif" which forces the heading (if applied) to be san serif and also reduces the font-weight to 300 visually altering it from our current thick headings.

**Comment by btopro** [comment]
change of pace

**Comment by btopro** [comment]
merging into #206
