### ISSUE TITLE
Label intentionality

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#309]
![2015-10-29_14-55-40](https://cloud.githubusercontent.com/assets/329735/10829656/9d7da466-7e51-11e5-99e6-a02db5b90620.jpg)

The red arrow are things we COULD capitalized, orange are things we currently do. I do this only to make an issue here that we have sorta a standard but not in this area.  Initial proposal which would be for @cmd30 / @heyMP / @michael-collins to come up with a standard as to when we use
- forcible uppercase text-transform
- forcible lowercase text-transform
- nothing at all
- first letter cap

Current (yet inconsistent) implementation:
- links are lowercase / normal, no transformation
- things that mentally project hierarchy are all Caps
- page title is part of this (currently)

Initial thought; page title shouldn't all cap, don't care about approach taken so long as it's something that has a small, documented section in the style guide #271

**Comment by bradallenfisher** [comment]
👍

**Comment by btopro** [comment]
Major navigational items get Normal Case
Minor navigation items - All-cap and are smaller
Categories - All-caps
Admin areas / tasks - green in color
Delete / dangerous operations - red
"safe" operations - happy @michael-collins blue

**Comment by btopro** [comment]
UI work is accounting for intentionality of labels
