### ISSUE TITLE
Calendar events view

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#310]
Need a way to be able to add events like assignments, lectures, and assessments based on a date-centric page. A vertical listing of calendar dates with item details is fine. The standard wall calendar grid view isn't necessary or really desired. A way for an instructor to build this page on the fly would be great.

**Comment by michael-collins** [comment]
Related to #220

**Comment by rickhumphries** [comment]
I quite like the Google Calendar schedule view, which shows the dates included in each week on a line, then colour codes each event in a list style. You could have each event coloured depending on the course it's associated with
![image](https://cloud.githubusercontent.com/assets/4973810/10884812/f19ae054-8171-11e5-9c21-422c975e411f.png)

**Comment by michael-collins** [comment]
@rickhumphries Yeah, this is pretty much how I was imagining the inbox would work.

**Comment by btopro** [comment]
primary display w/ traditional calendar as an alternate view; a lot of people still like printing things out :)

**Comment by btopro** [comment]
dropping tool to build tag as this as been selected to be built and is in the core network package. Now we'll just need to actually make it useful :p

**Comment by rickhumphries** [comment]
Thought I'd drop this in here as I came across it and it seemed related:
https://www.drupal.org/project/appointments

**Comment by btopro** [comment]
@proconnor15 is working on a #1968 which is a blocker before moving forward on this. He's looking into taking .ical feeds and rendering them dynamically through a web component
