### ISSUE TITLE
Discussions features

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#312]
I see discussions working in a variety of ways.

**Content Discussion** (voluntary or required by assignments/assessed)  

1. Inline-content discussions - view in **Content Outline** distro
2. Per lesson/topic discussion - view in **Content Outline** distro
3. UI View that aggregates and filters discussions - view in **Content Outline** distro

**Course-wide discussions**  

1. Activity/Feed for general discussion and show n tell - Located in **Inbox** distro

**Comment by michael-collins** [comment]
Related to #220

**Comment by btopro** [comment]
#111 #37 #55

**Comment by btopro** [comment]
continue over in #55 since that has a lot more ideas
