### ISSUE TITLE
Upgrade bash spider

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#316]
we need a way of applying bash scripts automatically during major upgrades. Anything that.s a x.y.z that has x or y changes will need to run the formal upgrade script to ensure everything is correctly functioning. We do this very well with DR currently but need a process for bash scritps.

Proposal
- keep a CURRENT_VERSION and UPGRADE_HISTORY file in elmsln/config
- CURRENT_VERSION ensures that when we pull new code we know where we are now and where we need to apply upgrades up till
- this lazy loads off a directory known to contain the upgrades, then runs them in order
- when done it modifies CURRENT_VERSION and appends all the upgrades as they run into UPGRADE_HISTORY

**Comment by btopro** [comment]
https://github.com/zacdavidm/bash_updates

**Comment by btopro** [comment]
@zacdavidm does this align w/ the repo you were working on?

**Comment by zacdavidm** [comment]
Yep. Sound just like what i was doing. Check out my repo and see if it works for you.

**Comment by btopro** [comment]
awesome; ported it and simplified quite a bit so that it's just doing a text based, sorted comparison

**Comment by btopro** [comment]
@zacdavidm https://github.com/elmsln/elmsln/blob/28508856950b7461e58c9431f128de12ac0fe068/scripts/upgrade/elmsln-bash-upgrades.sh

**Comment by zacdavidm** [comment]
I think the advanced comparison logic was to account for x.y.z to x.yy.z
comparisons. Basic comparison > failed that in certain cases if I remember
correctly.

**Comment by btopro** [comment]
like sort order? not sure I follow cause those would all still process in the same order and the string would technically be "less than" the previous.

![2015-11-20_00-48-25](https://cloud.githubusercontent.com/assets/329735/11292754/791a20ba-8f20-11e5-92dc-74e8f61fdc63.png)

**Comment by zacdavidm** [comment]
sorry. don't have time to test. does it work when upgrading from 0.0.0 to
0.0.10 with the following files?

0.0.1
0.0.2 //I suspect this one will prematurely trigger stop
0.0.5
0.0.10
0.0.11

**Comment by btopro** [comment]
made some tweaks but works correctly when versions are single digit counting up; for example, 0.0.0 to 0.0.11 when the ceiling is listed as 0.0.10 will correctly run everything in order up to it. The issue comes into play when run again because the version is now 0.0.10. When running this it incorrectly triggers 0.0.2 0.0.5 again. Guess I'll need to go for a check closer to what you were describing. thx for the pointer

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/commit/2b07962a0ac0593cc41444f3394bc65258b83dea fixes this
