### ISSUE TITLE
Side by Side critique interface

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#317]
Here's an example of what things look like in the studio currently based on student feedback. Side by Side panel, one with the student work (blurred), and the other with a comment / critique stream.

![2015-11-02_13-05-00](https://cloud.githubusercontent.com/assets/329735/10889883/a464cc6e-8162-11e5-919b-10db08c93f01.jpg)

It would be awesome if this was the default setup for people commenting but if I wanted to leave a critique that there was some kind of large "Critique this" button. Hitting this would pop something above what's currently being viewed that is kind of like the Windows 8 split screen where 1/2 of the screen is the work and the other 1/2 the screen is the form / critique criteria.

Some simple but cool ways of reviewing the detail of work and panning around it:
- http://www.tripwiremagazine.com/2013/07/jquery-image-zoom.html
- http://manos.malihu.gr/jquery-image-panning/ (love this one specifically)

This could be a pretty simple interface item which would allow people to focus just on the task at hand of reviewing some one else's work without constantly clicking between interfaces / multiple windows / programs (which is the current workflow...everywhere).

**Comment by michael-collins** [comment]
This interface style would great for other things where feedback from peers or the instructor would be desirable while having something in visual scope. Can we make this reusable somehow?

**Comment by michael-collins** [comment]
Or... was that the point of this issue?

**Comment by michael-collins** [comment]
Adding this to #304

**Comment by btopro** [comment]
yes :)

**Comment by btopro** [comment]
@heyMP I think there are 2 components here for the general component list.

1. moving around a larger image in place (which could be a cool method in general for panning around a large, high resolution image in place. Kind of like looking into a widow
2. Peer review / review interface

**Comment by heyMP** [comment]
@btopro something like this? http://www.elevateweb.co.uk/image-zoom

**Comment by heyMP** [comment]
Also, just throwing this out there.  I did stumble upon http://aroc.github.io/side-comments-demo/ for doing the inline comment threads.  I don't know if it would fit this specific workflow but since it's so bad ass I figure it would be worth the consideration.  :)

**Comment by michael-collins** [comment]
@heyMP that side comments thing is really nice. As for the image-zoom stuff, it sounds like @btopro was referring to the inner-zoom example on the examples page: http://www.elevateweb.co.uk/image-zoom/examples

I really like the mousewheel zoom example as well.

**Comment by btopro** [comment]
@heyMP so I like that inline coments thing but not for this nessecarily. That'd be great for talking about content; people's work you kind of alwatys want to see what's being said. we COULD get to a point where ur commenting on pieces of the work but.. dono, could be a good convo w/ faculty

**Comment by btopro** [comment]
also @kat-wehr please throw into this thread that kickass idea you had today about video timestamp critique

**Comment by kat-wehr** [comment]
Can do! So the idea was for the split screen "critique mode" for video assignments - one side could contain the video, and allow the students to scrub through the video as they review it, and add their comments on the other side. As the class add comments, the time code could be attached to their comment, so that when the student goes back to look at their critiques, they can click through the comments and be taken right to that point in the video. (I feel like this was a way more wordy explanation than when it came out of my mouth earlier...)

**Comment by heyMP** [comment]
Very cool. Here is a library for highlighting text and commenting.

https://www.drupal.org/project/annotator
http://annotatorjs.org/

**Comment by btopro** [comment]
Ideal from @WilliamMRose . Take the recorded video from student and allow instructor to construct feedback for it via H5P http://h5p.org

**Comment by btopro** [comment]
@heyMP that module is just meh as far as IA. It would need a rewrite

**Comment by heyMP** [comment]
@btopro if that's the case then I would vote for just implementing the http://aroc.github.io/side-comments-demo/  They serve nearly the same purpose but the side-comments could be used to solve more use cases.

**Comment by btopro** [comment]
consolidating in #548
