### ISSUE TITLE
Welcome PSU Smeal College of Business

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#318]
Going to add these brief threads so every time we have a group join we'll be able to find the member accounts and what not..

@mattmooney heads up Smeal's ELDIG group.

@rjf227 is part of the instructional design team

@kat-wehr is part of the instructional design team

@curiosity26 provides code development support and while he doesn't have the keys to the kingdom here yet, will in the future

We'll add other members of their outfit here as we get their accounts.

Welcome to the club, may we build really cool stuff together.

**Comment by rjf227** [comment]
Thanks, @btopro!  Looking forward to the outcomes as we build and maybe even try to break stuff together :+1:

**Comment by btopro** [comment]
@rjf227 break everything you can please :)
