### ISSUE TITLE
User List Drush plugin

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#321]
I found a handy drush plugin that lists all of the users and their roles.  If it's useful to anyone else we might consider putting it in ELMS.

https://github.com/jbickar/user_list

**Comment by btopro** [comment]
@mmilutinovic1313 maybe you can pull this into our setup. it would live in `scripts/drush/server/user_list` most likely though the plugin should get some vetting / testing in a sandbox before being pulled in since it's not on d.o.

**Comment by mmilutinovic1313** [comment]
Looking into this now

**Comment by mmilutinovic1313** [comment]
Testing to make sure it does what it says it does

**Comment by btopro** [comment]
@mmilutinovic1313 awesome cause this is what I was going to ask you to look into :)

**Comment by mmilutinovic1313** [comment]
Core functionality described by the drush plugin works as advertised. One of the issues we see in their issue queue is a problem with devel_generate. https://github.com/jbickar/user_list/issues/7. I could look into this issue for them if that is crucial for us, however I can create a PR to add this plugin if no one has any objections.
