### ISSUE TITLE
Sidecomments.js

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#322]
@heyMP sidecomments has a D8 module; needs a backport and shouldn't be too difficult (hopefully) https://www.drupal.org/project/sidecomments

@curiosity26 any interest?

**Comment by btopro** [comment]
would be useful in #317 and others

**Comment by btopro** [comment]
isn't flushed out (at all) unfortunately though the library it looks to integrate is

**Comment by curiosity26** [comment]
I'll take a peak see at the exiting module and the JS. See what needs done.

**Comment by heyMP** [comment]
Showed this to faculty and they really liked it.  Hopefully I'll get a chance to work on it soon.

**Comment by btopro** [comment]
@heyMP can you show this off at some point?

**Comment by btopro** [comment]
clearing this as a milestone bc @heyMP is working this into the angular app in general

**Comment by btopro** [comment]
merged into #1816
