### ISSUE TITLE
DRAFT: Development process for new concepts

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#323]
Our general development process is as follows (when it works best imo):
- Faculty / Students express a disconnect where technology can be improved or a solution help bridge the divide or enhance the relationship between them
- We discuss concept with an instructional designer / faculty member about the instructional challenge
- We rapid prototype with a goal of getting the information architecture (IA) correct
- Concept is tried in classroom setting when possible
- Iterate over refinement of IA with minor usability enhancements *using things core to how drupal handles interaction flows*
- Once IA is assumed correct, developer works with those that this directly affects to craft a more usable method of accomplishing the same thing
- We take a more "headless" approach to Drupal, constructing the interfaces and visuals needed that would make this task as automated as possible
- We integrate it with Drupal and put it into the workflow; the interface tapping the same information that was native to Drupal but without the standard admin-UX

Feedback much appreciated on this process. Information Architecture is critical because if the foundation is wrong, interfaces need to be drastically rebuild. Get that nailed down and functioning, then make it ultra usable / slick. As the #304 gets built out this will be easier to make it look great while doing the actual prototyping but we need to make sure we never let perfect be the enemy of the good when trying to hash out capabilities / needs with someone.

**Comment by heyMP** [comment]
I think that a really important addition to this document is outlining what that `prototyping` process really is.  I think that the most important feature of ELMSLN is the ability to add new functionality at an extremely fast pace.  The downside is that, if I'm adding custom functionality in my local instance and the down the road similar functionality is merged into ELMSLN core then there is the possibility of conflict. 

So for instance, if I wanted to experiment with adding an `svg` content type to my media I can absolutely do that without issue, which is awesome.  But then a few months from now, an `svg` content type gets put into ELMSLN core, I'm going to have a problem on my hands.

It might be just as easy as name spacing any functionality that local to my elms instance.

**Comment by btopro** [comment]
Name spacing is part of it for sure. that exact thing is part of what KIT spec was trying to resolve in distro development. As a result this is definitely linked to #210 since the naming of types and things is important to ensure downstream customizations that can be retained / prevented from conflicting with the whole package
