### ISSUE TITLE
Outline Map not showing 'default content outline'

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#324]
When I import a new book outline, I want to have the map begin displaying that new outline.  But when I go to `admin/config/system/course-settings` and set the `default content outline` to the new book, the content map still displays the old outline.
![screen shot 2015-11-03 at 11 35 38 am](https://cloud.githubusercontent.com/assets/3428964/10914256/8f0f63f2-821f-11e5-8434-666e667e5143.png)
![screen shot 2015-11-03 at 11 33 58 am](https://cloud.githubusercontent.com/assets/3428964/10914259/91a61048-821f-11e5-9a2b-14825868b936.png)

**Comment by btopro** [comment]
default is when a section doesn't define what book it uses;
- [ ] give better directions on what this settings page is actually doing

To change to the other outline, go to the section list and modify the master section (or which ever your working with) and set it as to which to use there

**Comment by heyMP** [comment]
Ahhhh, Ok.  So I'm sad to say that I never knew that you could assign an outline to a section.  It makes so much sense right now! :)

**Comment by btopro** [comment]
:clap:
