### ISSUE TITLE
H5P Shortcodes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#327]
This is just an update to say that the [latest version of H5P comes with shortcode embeds](https://h5p.org/october-release-note-2015#shortcodes).

Since this is natively supported, this may (or may not - haven't tested it!) help to address the issue of multiple H5P embeds within the page being recorded as separate xAPI activities described in #306

**Comment by btopro** [comment]
What issue is that? Not seeing the example where this causes problems

**Comment by rickhumphries** [comment]
Bit described under the 'Object' heading. Our statements come through and record the activity URL as the URL of the page that the H5P is embedded on. So if you embed more than one on a page they'l both record as the same activity.

**Comment by btopro** [comment]
ahhhh gotcha; maybe need to append some kind of hash on the end of the url

**Comment by btopro** [comment]
- [ ] update to latest version of H5P https://www.drupal.org/project/h5p

low hanging fruit for anyone that wants a commit :)
