### ISSUE TITLE
look into http://www.jsdelivr.com/

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#329]
if we delivered foundation access from CDN it's files would be shared across all systems anyone goes to across deployments. this would make course to course, system to system and location to location changes load faster and with less strain on all servers.

Files worth CDNing
- FA images
- FA css
- FA JS

also Foundation and Foundation Icons are already on there.

**Comment by heyMP** [comment]
Yeah that makes sense since they are all most likely using the same theme with the same js/css files.

**Comment by btopro** [comment]
wouldn't require it and it would need a fallback if blocked but this is one of those few times that it makes more sense to have an additional asset or 2 delivered in order to reduce (all) future page loads. We could also expire these weekly or something; a lot to consider for sure but I think worthwhile long term

**Comment by btopro** [comment]
in reviewing I think we'd use rawgit instead since it could deliver tagged releases of the assets with little to no effort; defering to that in #680
