### ISSUE TITLE
H5P - cross-domain support

### ISSUE THREAD

**Issue by dmurphy331** [elmsln/elmsln#333]
Need to embed "document.domain" declaration into the H5P embed.php to bypass XSS when activities are hosted on the elmsln media domain.

Look at the possibility of making this dynamic.

**Comment by btopro** [comment]
changed title only because it sounded more like an XSS vulnerability which this isn't a security bug, it's a bug in needing to support cross-domain which the browser (correctly) blocks at the moment

**Comment by btopro** [comment]
found this article; https://www.nczonline.net/blog/2009/09/15/iframes-onload-and-documentdomain/ which might make our lives a hell of a lot easier in certain scenarios (like bubble up dynamic resizing of windows for one)

**Comment by btopro** [comment]
raised issue with https://www.drupal.org/node/2612208 to see if there's any way of getting this accounted for in the main project before we craft a solution; simple enough but would rather work with them then patch around it for something this simple

**Comment by btopro** [comment]
@mmilutinovic1313 can you explore the referenced links in this thread as to how we might be able to craft a generic solution / simple patch to get this into the file;

@dmurphy331 can you send along via slack (or here) an example file that you've modified so we see the appropriate place to put it (I'm assuming its at the top)

**Comment by dmurphy331** [comment]
We just placed the declaration at the top of the file.

**Comment by btopro** [comment]
@dmurphy331 might want to chime in here in their queue -- https://www.drupal.org/node/2612208#comment-10562316

**Comment by mmilutinovic1313** [comment]
Looking into how to patch this.

**Comment by btopro** [comment]
got this figured out for entity iframe and h5p; patch to their queue and commit to ours coming shortly

**Comment by btopro** [comment]
closed now; will submit solution to the h5p queue as well
