### ISSUE TITLE
Voicethread integration?

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#335]
Can we integrate Voicethreads into the content pages?

**Comment by heyMP** [comment]
Does voice thread give you an embed code?

**Comment by juststormy** [comment]
Yes. I'm using them now. Is that preferred?

**Comment by btopro** [comment]
would just need an example of one; should be able to though. kind of assuming it's just an iframe; if not we might want to make a token to do it

**Comment by btopro** [comment]
@juststormy can you post one to slack so we can check it out?

**Comment by btopro** [comment]
![2015-12-16_00-02-40](https://cloud.githubusercontent.com/assets/329735/11832643/61491b7c-a388-11e5-967c-fc491bd8195f.png)

Looks like it just gives you the option to do an iframe embed, no real reason not to just do that unless your talking about some kind of deeper integration.
