### ISSUE TITLE
Switching on Shortcodes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#344]
I've noticed that shortcodes don't seem to render. E.g.
![image](https://cloud.githubusercontent.com/assets/4973810/11182118/2c15e65e-8c60-11e5-942b-77be02d35938.png)

Do I need to switch on any of these modules in the Courses distro?
![image](https://cloud.githubusercontent.com/assets/4973810/11182106/14077b9a-8c60-11e5-8f8b-621408220abf.png)

**Comment by btopro** [comment]
cis_shortcodes

Wp8
________________________________

**Comment by rickhumphries** [comment]
So that's provided the link to get the shortcodes in Courses.

But the shortcodes I'm copying from Media and pasting into Courses still don't render.

**Comment by btopro** [comment]
oops ur right; it's cis_filter in the thing you want to interpret the shortcode.

**Comment by rickhumphries** [comment]
Ah yeh, hmmm that module was already on. I've just grabbed all the shortcodes available for a random image and pasted them into a page:

![image](https://cloud.githubusercontent.com/assets/4973810/11184481/d348e4a8-8c6f-11e5-85fb-3d9ee39abe5a.png)

So it's rendering something - just doesn't seem to render the actual image.

Similarly with the document content type, these are how all the shortcodes render:

![image](https://cloud.githubusercontent.com/assets/4973810/11184577/6b944d4c-8c70-11e5-9099-6f994bdfa927.png)

**Comment by btopro** [comment]
@heyMP  --^

@rickhumphries can you copy the shortcodes in here so we can take a closer look

**Comment by rickhumphries** [comment]
Sure thing. 

**Image:**
Direct Link
[ciscode|rev=1|tool=elmsmedia|render=submit|link=node/231|text=Submit node|modal=0]

Submit widget
[ciscode|rev=1|tool=elmsmedia|render=submit|item=231|entity_type=node|entity_bundle=elmsmedia_image|entity_key=nid|submit_type=node|submit_bundle=video|submit_reference=field_course|submit_endpoint=node|submitted_text=View submission|author_field=author]

Shortcode direct iframe
[ciscode|rev=1|tool=elmsmedia|item=231|entity_type=node]

Image field: Render image
[ciscode|rev=1|tool=elmsmedia|item=231|entity_type=node|render=link|field=field_image|text=Whistle|delta=0|item_type=image|alt=Whistle|width=302|height=208]

**File:**
Direct Link
[ciscode|rev=1|tool=elmsmedia|render=submit|link=node/491|text=Submit node|modal=0]

Submit widget
[ciscode|rev=1|tool=elmsmedia|render=submit|item=491|entity_type=node|entity_bundle=document|entity_key=nid|submit_type=node|submit_bundle=video|submit_reference=field_course|submit_endpoint=node|submitted_text=View submission|author_field=author]

Shortcode direct iframe
[ciscode|rev=1|tool=elmsmedia|item=491|entity_type=node]

File field: direct link
[ciscode|rev=1|tool=elmsmedia|item=491|entity_type=node|render=link|field=field_document_file|text=Download Module 1 Course Material (pdf)|delta=0]

**Comment by btopro** [comment]
producing same result on the 'link' thing

**Comment by heyMP** [comment]
I don't see the option to display the image through a display mode.  @rickhumphries is the `elmsmedia_feature` feature enabled?  And if it is, is it listed as `overridden`?

**Comment by rickhumphries** [comment]
@heyMP yeh it's enabled. Just checked under features and it says 'needs review'. Is this where you meant?

![image](https://cloud.githubusercontent.com/assets/4973810/11195190/98795ef0-8ca8-11e5-9fbc-21a9826d722f.png)

**Comment by btopro** [comment]
yeah; if you / OB has made changes to the media system I wouldn't revert that all willy nilly though

**Comment by rickhumphries** [comment]
So I can't render images on this version of media using shortcodes? The only change we've made is the H5P/xAPI stuff

**Comment by btopro** [comment]
@rickhumphries can you give me access to it and I can dig deeper on the needs review; these tend to come up w/ the systems that were kind of developed pre-stabilization (if that makes sense)

**Comment by rickhumphries** [comment]
@heyMP I've just worked through the `elmsmedia_feature` so that the status is default
![image](https://cloud.githubusercontent.com/assets/4973810/11304605/b3924314-8fa0-11e5-9c59-b9066353b0de.png)
However, I'm still getting the same problems with shortcodes.
The version of Media I'm on perhaps doesn't support display modes? I'm not sure when they were introduced...but I should still be able to render an image right?

I ran the cron just to see if it gave any clues. This warning message comes up here (multiple times):
![image](https://cloud.githubusercontent.com/assets/4973810/11304745/50c07110-8fa1-11e5-9c4a-f24782d6acc9.png)
And there's this too:
![image](https://cloud.githubusercontent.com/assets/4973810/11304784/788bad68-8fa1-11e5-8f03-a71e95cc110a.png)

Would they possibly explain it?

**Comment by heyMP** [comment]
It's possible that error has something to do with it.  Can you post an example shortcode that isn't working?

**Comment by heyMP** [comment]
Whoops, sorry.  I didn't see them above.

**Comment by heyMP** [comment]
On the list of shortcodes, do you see one that is labeled `Render using default template`?

Looks something like this `[ciscode|rev=1|tool=elmsmedia|item=320|entity_type=node|render=display_mode|display_mode=default]`

**Comment by rickhumphries** [comment]
No nothing like that comes up. These are the only options that show:

![image](https://cloud.githubusercontent.com/assets/4973810/11306396/6901a4f8-8fa9-11e5-9a2a-6a495a63b9e9.png)

**Comment by rickhumphries** [comment]
The undefined index error was something else. I had two instances of every course in the content type. One instance had a machine name and CIS uuid linked to it and the other didn't, so I've deleted each instance of the course that didn't have a value for those fields and the warning didn't show when I ran the cron next.

**Comment by heyMP** [comment]
Hmmm... Let's first make sure that the shortcode filters are enabled for your courses.  These are the shortcode modules that I have turned on for my `courses` tools.

<img width="1440" alt="screen shot 2015-11-21 at 10 28 19 am" src="https://cloud.githubusercontent.com/assets/3428964/11319144/9cb0923c-903a-11e5-9f72-d7a345f726c7.png">

**Comment by rickhumphries** [comment]
Yeh I have the same setup in courses. In Media `CIS Shortcodes` is switched on, but the other two aren't

**Comment by btopro** [comment]
@rickhumphries diagnosed a bit; this appears to be deployment / networking specific as I'm doing some digging; will DM on backchannel

**Comment by rickhumphries** [comment]
Thanks @btopro, works great!
