### ISSUE TITLE
interface needs

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#346]
Need a in page tabs navigational element. This is always visible and makes it so systems like discuss studio and blog can have their items no longer thrown in the offcanvas menu. Also need a steps to complete block that has links to the pages below the current level.

**Comment by michael-collins** [comment]
@btopro I think there is a list of components kicking around, not sure what issue number though. This would be good to add to that list.

**Comment by btopro** [comment]
design them now graphics dood

**Comment by btopro** [comment]
#304
