### ISSUE TITLE
Add CDN domain for advanced cache strategy

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#349]
The majority of traffic on these instances is authenticated. This invalidates the possibility of using Varnish / Pound in any effective manner. What we could do is use the CDN module http://drupal.org/project/cdn and then produce a domain like `cdn.elmsln.local` which points to `/var/www/elmsln/domains`.

Then using CDN module, you can point all the assets to be rewritten as cdn.elmsln.local/online which will change all css, js, files and images to deliver from this domain. This has multiple benefits:
- CDN allows for multithreaded delivery (browser loads more files faster) = higher YSlow score
- static assets served from a different domain so they are naturally cookieless = higher YSlow score
- This would allow for Varnish / Pound configurations to ONLY listen on this domain / port combo; which would allow the system to play nice w/ other authentication systems while at the same time enabling reverse proxy integration for static assets.

TODO:
- [x] Make feature
- [x] Pick a pattern / name (or names, like cdn1 cdn2 cdn3; need to dig into my notes from years ago on this)
- [x] Point these entry(ies) to var/www/elmsln/domains
- [x] Install by default cause why not. Can't do the Pound side (yet #178 )
- [ ] See about pushing foundation access and zurb CSS / Js stuff over to this alternate address and compress as its own aggregate or something for stuff that's shared across ( #329 )

In playing with this concept on my local machine I was able to pull a 94 on YSlow... which is unheard of for a CMS. This is configuration that we could provide out of the box as part of a normal install as well since we follow a pattern.

@bradallenfisher any thoughts on this technique?

**Comment by bradallenfisher** [comment]
Ref

**Comment by btopro** [comment]
testing in vagrant now to produce the feature and do browser testing since CDN module references some things to pay attention to when pushing JS over a CDN. #177 also might be able to take into account CDN existing as CDN module can push some far expires headers at reverse proxies automatically to optimize them based on asset type

**Comment by btopro** [comment]
last todo has its own issue so it can stay there currently. Need to test more before we'd roll into the live package but it's there and appears to work (very well actually) :)
