### ISSUE TITLE
Course remixables - Body field: value embed

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#356]
Just been messing around on my local instance of ELMSLN and came across this. When using the 'Body field:value embed' shortcode (e.g. `[ciscode|rev=1|tool=mooc|item=9|entity_type=node|render=value|field=body|delta=0]` and pasting that into a different page, the following error messages are thrown up:

![image](https://cloud.githubusercontent.com/assets/4973810/11334455/f836b8b4-91cc-11e5-85a0-d41aac657ced.png)

**Comment by btopro** [comment]
thx for the report; this template file was missing for that use-case
