### ISSUE TITLE
Theme components framework

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#359]
We really should probably do them via https://www.drupal.org/project/angularjs

Just saying. This would make life much easier when developing Outline Designer, HAX and anything else w/ components going forward.  Thoughts @heyMP ?

**Comment by michael-collins** [comment]
@btopro This was recommended to me last year.

**Comment by btopro** [comment]
@michael-collins why isn't it done? did you get a different job or something?

**Comment by michael-collins** [comment]
@btopro There are some things on the Internet that are a mystery to me. This is one of those things.

**Comment by btopro** [comment]
closing, team aware, this might be in a later refactor / when we dig deep in HAX in the future
