### ISSUE TITLE
Autosaving page edits

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#361]
When editing pages, it would be good to have some way of saving editing work in the event of a disconnect or logout event.

**Comment by btopro** [comment]
when applied to HAX it currently tries to inject the previous state and the form gets cleared. Closing this out though as that'll be a #264 bullet point as that UI is heavily in dev.

**Comment by btopro** [comment]
and yes, this took less then a day to do; thank you once again Drupal
