### ISSUE TITLE
Ability for outline inheritance on specific pages of the course outline.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#368]
We have a use case for a Biology course where the instructors have identical lesson content but different orientation content.  Need the ability to have a certain section of the content outline to inherit from a 'master' course outline.

![img_4028](https://cloud.githubusercontent.com/assets/3428964/11571674/86520c9c-99cb-11e5-9d3d-603aacad7385.JPG)

**Comment by btopro** [comment]
pumped if you attack this the right way via a content by-reference type of connotation. Let's talk about the multiple ways of accomplishing something like this. I'd see the branch actually being orientation but the shared material being by reference

**Comment by btopro** [comment]
also look into #302 as that might provide some interesting opportunities to make the course and all outlines as a repo (or repos) and then allow for forking the git repo under the hood which would allow for merging "upstream" aka visualized in the course.

**Comment by btopro** [comment]
Section 1 is just a fork of the initial outline (or if we allowed git_books to live inside existing books which is possible just not currently) then we could have a shared git_book powering the lower parts of the hierarchy (aka the lessons) but the top parts of the content outline (orientation) be associated just to this space

**Comment by heyMP** [comment]
This is what I was thinking.  Adding another option to the Outline Designer that would reference another book.

![screen shot 2015-12-04 at 12 08 38 pm](https://cloud.githubusercontent.com/assets/3428964/11595903/eb42e32e-9a7f-11e5-8768-b5edf9951bb1.png)

**Comment by btopro** [comment]
sounds similar to the by-reference concept; probably can work it in now as stand alone functionality and then we'll have to account for it in the OD3.x rework cause I think we'd want to visualize these slightly differently

**Comment by heyMP** [comment]
This would have to tie into the book module though right?  We would want to alter the book's menu tree to pull in the by-reference books.

**Comment by btopro** [comment]
umm... either it would replicate the whole thing or it would allow a book to inherit; if you look in book.module there's something about not assuming that an item is only in one book so apparently you can (via code) put parts of an outline in multiple books by design (I think)

**Comment by btopro** [comment]
might just be adding the right entry to book table (yea hacking!)

**Comment by btopro** [comment]
looked in book module; appears the parent in a different book thing is a glitch bc of JS; might be able to have a book that alters the load of its outline at a certain special page like this existing book type you've got in the screenshot.  Basically there would be 3 books there and this magic page in Book 1 would allow the user (based on section) to see book 2 or 3 at the inflection point

**Comment by btopro** [comment]
stale
