### ISSUE TITLE
ELMSLN Chat rooms

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#381]
Being looked at in https://github.com/elmsln/socket-project

If we setup a node server
- http://socket.io looks most promising for this

Requirements:
- Helpdesk / Global chatroom; this would allow for the help page to have an online status indicator so you could talk to someone immediately if you had a support issue
- Per network chatroom: Anyone in any part of a course could reach out to classmates regardless of the system they are in.
- Per system chatroom: Talk to anyone else currently in the studio or content (for example).
- DM ability to DM people if you wanted to start a smaller / closed chat
- Cleaned out weekly; these conversations shouldn't be logged because we've be flooded with data; this also eliminates FERPA issues associated with bleed over between semesters because it takes a SnapChat-esk policy
- Text only, no markup by design

**Comment by bradallenfisher** [comment]
where should we set up the node server?

**Comment by btopro** [comment]
I don't know how to set one up, this would be a great thing to have as a baseline one-line installer. I wouldn't install it w/ elmsln outright as #101 Learning locker will be a stand alone service / server and Piwik will most likely be split off from the main package as well (and instead provide lots of documentation / automated installers for that too).  Currently I'm the only one running Piwik + ELMSLN on the same box and I've since started migrating it to a different server because piwik was hammering performance (and is nice to have not need to have kind of data).

Would you be interested in installing a Node.js server if one of our groups fits the bill? Don't think they really need any crazy specs given how performant the tech is. Let me know and I'll spin up a VM and give you admin

**Comment by bradallenfisher** [comment]
Yeah.  I just need a space to test the automation/connect to a remote
running chat.

**Comment by btopro** [comment]
VM request in, should be emailed when it builds

**Comment by bradallenfisher** [comment]
so is the goal here to have this server be standalone and connect to another server that has a running drupal chat on it? Or to have the node server setup on on a separate port on the same server as an apache instance?

**Comment by btopro** [comment]
this is a stand alone, DrupalChat / some chat client would be running in a drupal site and connect to this

**Comment by btopro** [comment]
https://github.com/bradallenfisher/nodejs-elmsln

**Comment by bradallenfisher** [comment]
Is there a next steps todo for this?

**Comment by btopro** [comment]
@bradallenfisher start trying to hook it up to a vagrant instance / another server running elmsln; maybe setup a box on digital ocean for nodejs and then one for elmsln and try to get the nodejs module working. it's now in the scope of all stacks though not enabled yet

**Comment by mmilutinovic1313** [comment]
I figured out how to get socket working locally. Working on a module currently to get this into drupalland. Also, we should think about if we want video chat support. (#1924)

If so check out the following: 
https://de.slideshare.net/micheledisalvatore/webrt-socketio-building-a-skypelike-video-chat-with-native-javascript
