### ISSUE TITLE
url_outbound should always append active

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#389]
Noticed this as you were demoing before; we should ALWAYS append that section identifier when we jump systems. This should happen if the person is an elevated role (if possible, dono if that's too early in the bootstrap to know the user's roles or not).

**Comment by heyMP** [comment]
As long as the user as the context specified in their session, and the url is going to a separate system with elms, then it will add it to the url.

https://github.com/elmsln/elmsln/blob/94e7f1440839d2f952afac5ab439f65ecd299519/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/features/cis_section/cis_section.module#L653-L661

That should cover your use case.  Or am I missing something?

**Comment by btopro** [comment]
`_cis_connector_section_context` currently doesn't set that session value unless something else does though seems like we could just set it on the way out the end of that function and it would satisfy both use-cases. We'd just have to make sure we're calling the function itself and not the session variable (outside of the outbound alter) since you could be in a situation where the setting of the context hasn't been called yet but your trying to access that function (like a higher order hook_init that needs to look into context; the function would return the right result where as the session value won't if its something around initial login).

**Comment by heyMP** [comment]
is there a `get_current_section_context` function?  I thought you could only get the active section through the $_SESSION.

**Comment by btopro** [comment]
_cis_connector_section_context is doing the get

**Comment by btopro** [comment]
$_SESSION is previously only set when you submit that form block to select a section

**Comment by heyMP** [comment]
Ok, I think I got it. https://github.com/elmsln/elmsln/commit/3c6375b6f14172dccaa38e116e58a9efc2cc25f7

**Comment by heyMP** [comment]
I've also added a method of sharing the url with the section context query parameter.  It's just temporary until we figure out where to put it in the new redesign.

<img width="1277" alt="screen shot 2015-12-09 at 5 16 33 pm" src="https://cloud.githubusercontent.com/assets/3428964/11700614/e062a184-9e98-11e5-8c40-a4e74b4b785f.png">

**Comment by btopro** [comment]
nice
