### ISSUE TITLE
Updating email address breaks login to course sites

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#397]
Not really an issue specifically with ELMSLN this but just wanted to get opinions. 

In the current CIS (which is also our 'dashboard/inbox') we allow students to edit their email address. However, since this is linked to their ID it will effectively prevent them logging into their course sites until the overnight cron runs and re-syncs the user details. 

One solution is that we write a custom module to sync the users across all the sites after any user details have been updated. I'm hesitant about doing this just yet for a couple of reasons - 1. I'm expecting these sorts of user details to be stored and updated in the (future) 'people' authority, and 2 - you might already have a solution to this for other user data types so it might not be required.

Another thought for a possible solution is whether to have a separate 'email' field for communication which is separate to the email address for ID, so allowing students to change this won't have any affect on their navigation through the course sites?

**Comment by btopro** [comment]
so you require their email address to be their username?

You are correct that we'll be formulating solutions to this in the people distro down the road. We've also recently been talking about #380 which could allow for a lighterweight / task oriented API end-point (as opposed to the current RESTWS based ones which are entirely entity driven). The separate email would make sense so long as there isn't potential confusion with them updating their email address, then expecting to log in with it.

Another potential solution (which would jive well w/ the people distro). If someone updates their profile in one site, you could ping the courses they are in via API calls to the user object in the other courses and update their profile there to match (and visa versa).  I've been thinking about doing this myself till we have a full on people distribution flushed out as we're going to be allowing user picture uploads for a studio class in the fall (well... anyone using it really).

**Comment by rickhumphries** [comment]
No, sorry - we don't need their email address to be their username. Maybe it depends on the SSO being used, but we're using bakery and it seems to check to see if the username and email address fields are the same before it allows access.

For example, I was logged in the CIS/dashboard as a student, edited their profile and changed email address. Then went back to the dashboard and clicked to be passed through to a courses site and the following warning from Drupal comes through in the courses site:

![image](https://cloud.githubusercontent.com/assets/4973810/11806799/60e68370-a30d-11e5-8220-7b1ec2828ee2.png)

The picture upload thing is interesting too. We allow profile picture uploads in the CIS/dashboard but then that doesn't propagate through to any of the course sites at the moment.

**Comment by btopro** [comment]
oh I see what you mean, yeah email will need to be the same always unless you sync it on save

**Comment by btopro** [comment]
leaving this hang around as documentation of this issue related to email and relating users across systems
