### ISSUE TITLE
CIS 2.x UX overhaul

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#405]
The UX of the CIS needs overhauled. @michael-collins has mocked things up that we haven't had time to implement to this point. Time to push this up in priority a bit or at least increase visibility of the issue. The current long form that you are dumped to has too many options and is ugly.

http://codepen.io/michael-collins/pen/JYWBvP

**Comment by btopro** [comment]
0.0.2 includes a lot of clean up to CIS based on feedback from IDs. Menus and options cleaned up and all types set in alignment with 2.x backend system style

**Comment by btopro** [comment]
#669 #624

**Comment by btopro** [comment]
feedback from @kat-wehr 
- Network pane in CIS 2.x should have quick CTools modal style pop ups to do this administration
- Course Outline - Be able to drive into the outlines right from there with quick links to outline designer display
- Studio - Assignments overview, adding more, etc
- Discuss - Add more discussions, etc
- Blog - Add more postings, etc
- Innovate - Just go to (basically)


Then per section you'll be able to associate them as to which they use. CIS starts to become the window into the universes while still allowing you to be in those universes to get your tasks done

**Comment by btopro** [comment]
- [ ] abstract current implementation in foundation_access so it's only loaded on the dashboard in cis
- [ ] use angular over CDN instead of local copy
- [ ] roll into master but don't link to

This will allow us to progressively enhance the dashboard or even make a dashboard / management link with a (beta) flag or something next to it. Once the sorting and filtering capabilities are activated it'll be pretty amazing just from playing with it in the current state

**Comment by mmilutinovic1313** [comment]
Quick question about Angular. Are we using Angular 2? Or just the original?

**Comment by btopro** [comment]
1.x for now

**Comment by mmilutinovic1313** [comment]
@heyMP got a bunch of stuff fixed for this yesterday. It's now a bit closer to where master is so that the theme isn't screwed up like I was describing. I'm working now on getting some visuals added and implementing the design that @michael-collins drew up.

**Comment by mmilutinovic1313** [comment]
Adding the checklist here so I can check items off: 

- [ ] abstract current implementation in foundation_access so it's only loaded on the dashboard in cis 
- [ ] use angular over CDN instead of local copy
- [ ] roll into master but don't link to

Currently the materialize branch mirrors @michael-collins ' markup for the dashboard. I have a few questions about the direction in which I need to go to finish off some of these remaining tasks

1. Where does the data for `Content`, `People`, and `Network` come from? Is that also present in the JSON we used for course title etc? Or is there a separate source?
2. Is the "Use angular over CDN task" implying that we need to hook up Angular to work with the CDN? Or did this mean "Instead of the CDN".
3. If we are using the CDN and angular together, what files should I be looking at to get the CDN stuff up and running as a potential datasource?

**Comment by btopro** [comment]
1. Network -- online.elmsln.local/sing100/service-instances
People - there's a module called cis_user that allows importing users, maybe that and sync can go on there. It's for all things that have to do with People in that course / sections
Content - I'm not entirely sure this needs to exist and I think is dated. Content makes more sense under Network but we might need to tweak the labels here
2. Angular should ONLY be used over CDN unless we want a mode for developing offline. It's almost gaurenteed to be a cache hit for the end-user.
3. CDN is different issue but Zurb foundation 5.x, jQuery, and anything else that could respond to the CDN. Also (woah) I just stumbled on this in looking a bit -- https://www.drupal.org/project/libraries_cdn might be a good starting point for the #680 setup as this seems like it can hijack delivery of libraries API implementations (which would be huge as MANY things use that).

**Comment by mmilutinovic1313** [comment]
I'm going to try and get a few more of these bullet points checked off today. We should probably have a local angular version we can load / tell Drupal to load it from the CDN. I have verified that it is loading via CDNJS properly. At the moment, adding local angular installation and adding the data for the other menu tabs should be able to close out this issue.

**Comment by btopro** [comment]
yes. also the js_alter is a temporary solution as it fires on every page load which is going to definitely invoke a performance penalty when we could library_alter (or some other method) it's way into using our chosen versions without having to do it on every friggen page :). Keep moving forward with it, realize we'll have to refactor the integration point

**Comment by mmilutinovic1313** [comment]
I'm downloading 1.5.7 and adding it locally. It says this is the stable version now, so I can test that it works with our current implementation

**Comment by btopro** [comment]
sounds good, we should have an all local option for delivery

**Comment by mmilutinovic1313** [comment]
This should now be good to go pending the merge into master! :)

**Comment by mmilutinovic1313** [comment]
Do we want to merge materialize into master? Or still hold off until the module in #994 is finished?

**Comment by btopro** [comment]
let's hold off a bit

**Comment by mmilutinovic1313** [comment]
Sounds good to me

**Comment by btopro** [comment]
could be a good thing to do during the sprint as potter will be there and we can have some dedicated angular tasks

**Comment by mmilutinovic1313** [comment]
That would be good! That's the Drupal Camp Sprint right?

**Comment by btopro** [comment]
yes

**Comment by btopro** [comment]
This is being tested via PR now to see if Travis is happy and more manual testing is going on but the UX has been improved for CIS 2.x drastically from the course creation page last night and the angular CIS dashboard being merged in (shortly) even in it's partly finished state. We'll add a link to it that says beta or something once it gets a litle more work into it. Great work thus far @mmilutinovic1313 @heyMP on getting this to where it is currently and cleaning up a lot of roadmap issues surrounding materialize and angular

**Comment by mmilutinovic1313** [comment]
Sounds good! Will get more of this cleaned up so we can go beta with the dashboard as well as a better CDN module in for handling the angular files!
