### ISSUE TITLE
MOOC Navigation "block" / callout

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#408]
It would be awesome to be able to do 'menu-block'-esk sub-navigational elements (that can be pervasive across / down content nestings if you will). This would be a sub-module / related to the MOOC content styling pack. While reviewing this should also add in #185

Some structure to this as far as settings go.
---- Style
------ magelin
------ left block
------ right block
---- Label
------ textfield (example: Table of Contents, Steps to Completion)
---- Display
------ here and down
------ only below
------ only here
---- Type
------ Links (then provide custom ones as a bulleted list)
------ Content outline

**Comment by btopro** [comment]
screenshot
![2015-12-18_01-17-26](https://cloud.githubusercontent.com/assets/329735/11890710/57684f58-a525-11e5-96fd-37472a894345.png)

**Comment by btopro** [comment]
video https://www.youtube.com/watch?v=jHAdV6eIo74

**Comment by btopro** [comment]
@michael-collins do we have any prev mock ups that show somethign like this? Block injected into the nav to showcase where u are deep in a lesson (potentially).

**Comment by michael-collins** [comment]
No mockups like this were ever made. Add it to the list.

**Comment by btopro** [comment]
assigning to heyMP since he started playing around with this; definitely needs styling. Most output options / combinations work currently. may be best to start rolling it out and see what tweaks need made to clean things up (from a settings stand point). The current approach also might be TOO granular, really only requiring a global "here's how I want to handle nav" but we'll need to run this a few places to start to gather data about how IDs / faculty are using it before making that call.

**Comment by btopro** [comment]
shifting to 0.2.x since this is currently there, its functional but needs cleaned up. 0.1.x is about stabilization, 0.2.x is the next round of improvements / enhancements. I'd like to cut 0.1.x by the end of jan once we get through startup and any issues that come about from us launching all these different courses across groups
