### ISSUE TITLE
User Roles Docs

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#409]
I'm just trying to get my head around how the different user settings are picked up by the other services - in particular the roles. 

My use case is that I'd want to set up an internal training site for staff who may be instructors on other courses. So I'd need them to be instructors in one course and students in another. I see how this is possible though, as it seems like I need to give a user both the instructor and student roles in the CIS, but the roster sync will then give both role types to the user in the course too.

Is this accounted for in the plans for the next CIS/People distros?

**Comment by btopro** [comment]
Hmmm.. This might be specific to your current sync atm as we don't sync roles across systems in out deployments. I'm an admin in one place, a student In Another and staff elsewhere (theoretically).

People could be used to visualize this or inbox having a list of your courses and your role in that course. Worth accounting for for sure.

**Comment by rickhumphries** [comment]
Ah right OK, hmmm, will double check our sync agent to see what's going on. Thanks
