### ISSUE TITLE
Node.js / Learning Locker v2.x

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#411]
Learning Locker v2.x will be based on Node.js rather that PHP and should have an open source release in 12 months. Speaking to the guys at LL there's an opportunity to get our hands on an early release version of v2.x and provide feedback if we want to explore this. 

In any case, we should prepare for adopting node.js as part of the elmsln architecture. I know there's a bit of work here already with #381 which is great. Learning Locker based on node.js would allow us to do the following in real-time (based on xAPI statements) 

- Awarding of badges/achievements
- Embedded objectives/competencies that are visibly 'ticked' off after completing activities
- Activity stream on a users dashboard that updates with anything related to them in LL
- Control the visibility of content on a course (i.e. chapter 4 can't be viewed until activities for chapters 1-3 have been completed, or assignment 3 can't be submitted until assignment 2 has been etc.)
- Send messages 

Will probably require this module https://www.drupal.org/project/nodejs ?

**Comment by bradallenfisher** [comment]
I think that module is making its way into the stack.

**Comment by btopro** [comment]
@rickhumphries to confirm what brad said, nodejs module is currently in the network just not enabled anywhere (latest master that is)

**Comment by btopro** [comment]
Worth noting, I think we can explore this more after we start to integrate more node.js based components / concepts, especially since this immediately requires a more complex setup then our base single system install (most likely).

**Comment by btopro** [comment]
closing for now and referencing as a node.js / php-fpm related install (cause we'll need to rework under the hood if we're to support vagrant installs that have both)

**Comment by MrVibe** [comment]
Is the work still going on in porting LL to Node.js ?

**Comment by btopro** [comment]
LL 2.x has not yet been released to my knowledge but it is node based. https://learninglocker.net/
