### ISSUE TITLE
Fitvids module

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#415]
There's a module called Fitvids which is included for CIS 1.x which isn't working properly at the moment. Darren tracked this down to an issue raised in the Fitvids module https://www.drupal.org/node/2304575.

This issue has been fixed in the most recent version of FitVids 1.17. At the moment the version used in core is 1.15. Could this be updated? Thanks

**Comment by btopro** [comment]
hope that takes care of it. noticed that issue and didn't have time to dig so I had been just disabling it everywhere :). code change is incredibly small so hopefully that works

**Comment by rickhumphries** [comment]
Thanks :)
