### ISSUE TITLE
Quick switch networks when on authorities

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#418]
All authorities should have a standard (relatively standard that is, not hard standard view) /courses type of view which shows all the courses in question. This way let's say i'm in gd100. I could have this workflow:
- media team bumps into me says media is ready for gd100
- I'm in courses.elmsln/gd100 at the moment, I click network, then media
- This drops me into the media.elmsln/gd100 location
- I look for the new media added, grab shortcodes, etc
- I stop and say "this looks like what we used in art122 I think"
- Click the "course list" (or whatever) menu item on the main screen, shown a list of all courses
- click art122; filter to just media for that (media.elmsln/art122). I find the media for comparison, copy that instead, go back to course-list, then gd100, then click content outline.

This will play in nicely with the switching networks functionality as well.

**Comment by btopro** [comment]
posting some screenshots of what the current UX looks like in a real deploy in this area.

![2015-12-22_09-45-16](https://cloud.githubusercontent.com/assets/329735/11957654/ef92d672-a890-11e5-9e8c-4088ad6a406f.png)

**Comment by btopro** [comment]
![2015-12-22_09-45-45](https://cloud.githubusercontent.com/assets/329735/11957660/f3d3d164-a890-11e5-8318-ac5c74fbac9e.png)

**Comment by btopro** [comment]
![2015-12-22_09-46-06](https://cloud.githubusercontent.com/assets/329735/11957665/fc2ef492-a890-11e5-8da2-442de7a0960c.png)

**Comment by btopro** [comment]
@michael-collins Need a place for this / some ideas of where to visualize a button / ability for switching networks. tagging you til we get an idea of where to put this usability pattern

**Comment by michael-collins** [comment]
Okay, will work on an interface for this. It will be a derivative of the CIS codepen: http://codepen.io/michael-collins/pen/qbKvLr

**Comment by btopro** [comment]
this has to be something that can happen from anywhere

**Comment by btopro** [comment]
#1758 has this taken into account in some of the early prototypes. The UX patterns expressed there are to unify all aspects of the network and this would be part of any implemented design.
