### ISSUE TITLE
Creating Custom Styles and Templates for Course Outline

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#42]
This is to kick off a discussion surrounding the best ways of creating and sharing content templates to use in the course outline service. We have started using CSS injector (https://www.drupal.org/project/css_injector) to add our own styling and then the WYSIWYG templates module to create templates to use. Alternatively, I know there's other ways of accomplishing similar things - for example, the UW-Madison group adds their styling via modified versions of textbook (found here: /admin/config/content/textbook). Although I don't know a lot about this method it would be great to learn more about others' techniques for these sorts of things in ways that maintain accessibility etc.

**Comment by btopro** [comment]
@mkwisc may have insight into this as he's the UW ppl you mention :)

**Comment by btopro** [comment]
I know that @michael-collins and I have said that HAX is the future -- https://projects.invisionapp.com/share/432335URA#/screens but HAX is still aways away at the moment as we're in the UX weeds currently and that's a prerequisit to the authoring stuff.

I think there's also a difference in approach to the instructor wanting to add stuff and to the organization adding stuff. Organization standards should be brought in via a module I would think where as the CSS injector approach could be better for one-offs and to spur creativity / flexibility for those wanting to try stuff out without getting knee deep in code.

**Comment by mkwisc** [comment]
@rickhumphries that’s correct, we use a set of custom stylesheets that are based on textbook that ship with ELMSLN's MOOC distribution. There are probably some downsides to going this route too (such as missing future updates to textbook stylesheets), but this was the easiest way for us to quickly add org-wide styles and then create templates to go with them. It was very important for our content authoring experience that we had a variety of styles (bullets, boxes, buttons, icons, layouts) so this helped us accomplish that. I worked with @btopro to set this up and at the moment am blanking about how we actually did this aside from selecting it at /admin/config/content/textbook. Perhaps @btopro can refresh my memory or there is already some documentation about this?
One thing that would be fantastic is if a bunch of us could collaborate on adding new styles for textbook and corresponding templates and ensure they are open source and accessible. These could then be included as default styles, available as something like an extension pack that is easily installed later, or available as an alternate built in. Just some ideas. I’d be happy to share what we did as inspiration, although I know that a lot of it should probably be reworked. There may also be some further work that we could all do towards making templates even easier for content authors to use, such as further development of shortcodes for different styles and parameters.

**Comment by mkwisc** [comment]
And in case helpful, here are two screenshots showing some of the styles I added. 
![screen shot 2015-03-21 at 10 21 19 am](https://cloud.githubusercontent.com/assets/11563132/6765571/2f89565e-cfb4-11e4-9e53-85a728404277.png)
![screen shot 2015-03-21 at 10 21 07 am](https://cloud.githubusercontent.com/assets/11563132/6765572/2f984c2c-cfb4-11e4-9274-1fff4f228d47.png)

**Comment by rickhumphries** [comment]
@btopro I can't currently see how to add the custom stylesheets based on textbook as described by @mkwisc above. Instead we added CSS Injector module to a course-outline site, and added all our CSS for the course in here. This actually worked pretty well but when we created a course-outline for a different course we were getting an error saying 'CSS injector directory not writeable'.

Is there a way that CSS Injector Module can come with course-outline OOTB so this doesn't happen? Or provide a bit of detail on how to set up the stylesheets based on textbook? Thanks

**Comment by btopro** [comment]
@rickhumphries for WISC there's a custom module for them w/ a [hook implemented](https://api.elmsln.org/api/drupal/sites%21all%21modules%21elmsln_contrib%21textbook%21textbook.api.php/function/hook_textbook_style/cis7) to put their styles in place. This is to make a more pervasive change to all systems / courses. Injector is usually design for tweaks to a single one.

**Comment by rickhumphries** [comment]
@btopro Ah I see. I think it would be a good idea to include the custom module OOTB just as an example for others to see how these styles can be put in place.

**Comment by btopro** [comment]
picking this up in #291
