### ISSUE TITLE
Using Learning Locker to track progress on a unified dashboard

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#421]
This has been bugging me but I think I have a workable solution. If we had inbox able to produce a holistic dashboard that shows progress across all aspects of the course which is actually just aggregating data in from smaller dashboards in each system then we can do this. Workflow for tracking how many assignments you've completed / gotten feedback on...
- You have 10 assignments due in the Studio
- Studio reports to Learning Locker when things are completed (you did assignment 1,2,3 and got feedback on assignment 1,2)
- Inbox asks studio for a status report (without really knowing what all the nitty gritty is).
- Inbox pulls in progress in the course content and visualizes it on gauges next to progress through the assignments.

This way we can have each tool interfacing just with the aspect of learning that its focused on. Then Inbox doesn't have to do the "how many assignments did they complete?" kind of logic, instead it can ask studio for what things people care about in that context. This creates a more distributed notion of 'progress' which is more flexible. Course A could be tracking completing of every H5P activity while course B could only be tracking getting to the end of each lesson and cares more about the studio submissions completed. Course C could be a studio course as well but it values engagement and commenting between members over the actual completion of traditional "assignments".

**Comment by heyMP** [comment]
In this scenario, what would be the role of Learning Locker?  Would it just be for running custom reports or would it be responsible for assigning completions?

**Comment by btopro** [comment]
LL stores the statements, it makes no assumptions of anything other then that it securely collects and can pass data.
Then,
- Statements would be emmited from different locations (studio, content, h5p widgets, etc)
- these are stored in LL
- another dashboard in CIS, people, where ever would say "Hey LL do you have these 10 statements?" It does the check, reports back which statements are finished or not

**Comment by btopro** [comment]
duplicate of #1360
