### ISSUE TITLE
Add keyboard shortcuts for navigating the course content outline

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#431]
For accessiblity reasons and for ease of use for everyone, we should add keyboard shortcuts for
- [x] Advance to next page in book outline
- [x] Advance to previous page in book outline
- [x] Open Book outline 'map'

**Comment by heyMP** [comment]
@michael-collins Are you aware of any standard for these types of navigational keyboard shortcuts?  I'm assuming previous/next navigation is left/right on keyboard.

**Comment by btopro** [comment]
Good Idea; @heyMP with a modifier I assume like cntrl or something? Also are these binded via JS or is there some other indexing method? if JS based, outline designer uses http://keithamus.github.io/jwerty/ (we just don't tell people what the shortcuts are so a standard way of presenting those would be awesome too)

**Comment by heyMP** [comment]
I've seen a lot of websites just plan old left right, no control key.  For instance you can browse through Facebook image galleries with left and right keys.

**Comment by btopro** [comment]
But not reload the whole page... Hmm we can give it a shot and see. There honestly might be research to suggest making switching too easily to be a problem. This is supposed to be information that's digested after all. Still, not a bad idea

Wp8
________________________________

**Comment by btopro** [comment]
so we don't lose this; outline designer uses jwerty (not that we have to use it) but doesn't communicate what the shortcuts are. We currently have not styled / found the exact purpose of the accessibility icon / menu; perhaps we could put nice "button" looking icons for navigation in that menu so it has all the shortcuts (inbox would obviously have a bunch too) and use that to start driving the styling of the other items placed over there too

**Comment by btopro** [comment]
started this. `<--` and `-->` arrow now cycle through content. `o` currently opens the content outline. We should add additional support for full on keyboard support here as well as listing what the keys are.
@heyMP any nice keyboard button css we could use like on http://keithamus.github.io/jwerty/ for showing what shortcut keys there are?

**Comment by heyMP** [comment]
Those examples where pretty good.  How about something like this?  http://codepen.io/heyMP/pen/pyeMaZ

**Comment by btopro** [comment]
awesome, now where to put them

**Comment by btopro** [comment]
@heyMP just make it so they are aligned w/ the button to the left w/ action to right and we stuff em on the accessibility drop down page

**Comment by heyMP** [comment]
yeah, under the accessibility dropdown works.
