### ISSUE TITLE
Steps to Install php-fpm

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#436]
- First remove all your current php modules

```bash
yum remove php php-cli php-common php-devel php-gd php-mbstring php-mcrypt php-mysqlnd php-opcache php-pdo php-pear php-pecl-apcu php-pecl-igbinary php-pecl-jsonc php-pecl-jsonc-devel php-pecl-memcache php-pecl-memcached php-pecl-mongo php-pecl-msgpack php-pecl-sqlite php-pecl-ssh2 php-pecl-yaml php-pecl-zip php-pgsql php-process php-xml 
```
- Re-install them with php5.6 using the remi repo

```bash
yum install --enablerepo=remi-php56 php-fpm php-cli php-common php-devel php-gd php-mbstring php-mcrypt php-mysqlnd php-opcache php-pdo php-pear php-pecl-apcu php-pecl-igbinary php-pecl-jsonc php-pecl-jsonc-devel php-pecl-memcache php-pecl-memcached php-pecl-mongo php-pecl-msgpack php-pecl-sqlite php-pecl-ssh2 php-pecl-yaml php-pecl-zip php-pgsql php-process php-xml 
```
- OPTIONAL - Remove /etc/httpd/conf.d/php.conf.rpmsave

- install the repo for fastcgi and then install fastcgi

```bash
sudo rpm --import http://dag.wieers.com/rpm/packages/RPM-GPG-KEY.dag.txt
sudo rpm -ivh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
sudo yum install mod_fastcgi
```

- create /usr/lib/cgi-bin

``` bash
mkdir -p /usr/lib/cgi-bin
```

- Paste the following to the bottom of /etc/httpd/conf.d/fastcgi.conf

```bash
<IfModule mod_fastcgi.c>
      DirectoryIndex index.html index.shtml index.cgi index.php
      AddHandler php5-fcgi .php
      Action php5-fcgi /php5-fcgi
      Alias /php5-fcgi /usr/lib/cgi-bin/php5-fcgi
      FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -host 127.0.0.1:9000 -pass-header Authorization
</IfModule>
```

- Change in /etc/httpd/conf.d/fastcgi.conf

``` bash
# wrap all fastcgi script calls in suexec
FastCgiWrapper On
```

to 

``` bash
# wrap all fastcgi script calls in suexec
FastCgiWrapper Off
```

- restart apache

- edit /etc/php-fpm.d/www.conf
- set your pm.max_children, pm.start_servers, pm.min_spare_servers, pm.max_spare_servers, and pm.max_requests to reasonable defaults and tweak where necessary. 

- modify your .htaccess files to allow basic authorization
```
  # Basic authorization when using FCGI
  RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
- start php-fpm

That should do it... I will see you tomorrow and we will try to implement. Worked on vagrant so fingers crossed.

**Comment by btopro** [comment]
nice! this would make a slick utility bash script though I'll imagine it's ultra specific to RHEL / Centos 6.x

**Comment by btopro** [comment]
updated to include basic authorization item. This kicks ass brad!

**Comment by bradallenfisher** [comment]
awesome!

**Comment by btopro** [comment]
Can you add this documentation to this page and fill it out a bit then do a PR?
https://github.com/elmsln/elmsln/blob/master/docs/scale.md

**Comment by bradallenfisher** [comment]
yep

**Comment by btopro** [comment]
merged
