### ISSUE TITLE
Prevent FigureLabel title from wrapping text

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#441]
The following CSS should be added to the figurelabel component to prevent it from breaking into two rows.

```
.figurelabel {
  display: flex;
  .figurelabel__title {
    white-space: nowrap;
  }
}
```

## Before
![screen shot 2016-01-07 at 9 30 27 am](https://cloud.githubusercontent.com/assets/3428964/12172908/bfee44c2-b521-11e5-9014-413d05bc8427.png)

## After
![screen shot 2016-01-07 at 9 31 13 am](https://cloud.githubusercontent.com/assets/3428964/12172919/cbab45a8-b521-11e5-9a18-d87144c4dd3a.png)

**Comment by btopro** [comment]
WHY IS THERE NO COMMIT FOR THIS YET!??!?! ;)

**Comment by btopro** [comment]
it's in i96... along with everything else it seems
