### ISSUE TITLE
Breadcrumb items not sorted correctly

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#442]
Seeing this in all courses.  The weight of the menu items in not being respected in the breadcrumb dropdowns.  I think it's related to #434 

![screen shot 2016-01-07 at 11 42 46 am](https://cloud.githubusercontent.com/assets/3428964/12176142/fdab257a-b533-11e5-9af4-19f48a31a401.png)

**Comment by btopro** [comment]
not the exact same issue but around that block of code most likely. DM me that course / others doing that cause I haven't been able to replicate that for some time.
