### ISSUE TITLE
Opening document links in new window (Media Shortcodes)

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#450]
Hi - I think @heyMP might be able to help me with this one :) I've got a couple of document links in one of my courses which are generated via shortcodes:

![image](https://cloud.githubusercontent.com/assets/4973810/12197472/2985cee0-b5ff-11e5-8c16-41533dfe92b0.png)
![image](https://cloud.githubusercontent.com/assets/4973810/12197478/37795184-b5ff-11e5-804d-fcf258a233b0.png)

However, clicking these links opens them in the same window, which navigates the user away from the course page. How can I force these links to open in a new tab/window?

**Comment by heyMP** [comment]
We don't have short codes option for opening in new tab yet.  For now, since the shortcode is just rendering a link, can you grab the direct link to the file and make an a tag
`<a href="path/to/file/on/media/system/" target="_blank">Download Exam Invigilator</a>`

**Comment by rickhumphries** [comment]
Yeh sure no worries. Cheers

**Comment by btopro** [comment]
https://www.drupal.org/project/extlink might be worth a look as well. a bit more aggressive solution but if u have a lot of items opening that u need to ensure they are in new windows, that project is for that :)

**Comment by heyMP** [comment]
I suppose it does raise the question about adding custom attributes on the token itself.  There are obvious benefits of giving content creators the flexibility of easily adding custom attributes to the token directly in the body field.
(ie, [...|alt=Override the default alt description|target=_blank])

However, I think almost everyone would agree that this isn't sustainable at scale.  It's the equivalent of allowing inline styling.  The alternative though is that you would have to have duplicate content.
(ie, the two different image nodes with the same image just different alt tags)

**Comment by btopro** [comment]
Or secure

Wp8
________________________________

**Comment by btopro** [comment]
if we limit the supported tags to something reasonable like alt, title and target it might not be too bad. This is also one of those moments where I say something like "well HAX will take care of this so it's a non-issue" ;)

**Comment by btopro** [comment]
simple links have support (but don't add the property) the direct field references which could include something like a file to download will now have this property by default. target|_blank can be added to existing token links
