### ISSUE TITLE
CLE redirects webservice calls against it if sections et to master to NO_SECTION

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#455]
node.json?elmsln_active_course=NO_SECTION

@heyMP you wrote the active_course thing; what's 'NO_SECTION' ? if the call doesn't have a section attached to it or something? We might need to account for webservices to ensure they DONT do any inbound / outbound rewriting.  Potential example solution -- https://github.com/elmsln/elmsln/commit/9caa92c73246adcdf72548a450297d4015a29aff

**Comment by heyMP** [comment]
Hmm.... I don't remember anything about 'no_section'.  I'll look into it.

**Comment by heyMP** [comment]
It's the final fallback in `_cis_connector_section_context()`
https://github.com/elmsln/elmsln/blob/9caa92c73246adcdf72548a450297d4015a29aff/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/cis_connector.module#L498

What exactly is happening?

**Comment by btopro** [comment]
ahhhhhh ok. I think your inbound / outbound rewriting stuff is appending that when NO context is passed across which can goof up some webservice calls. studio gets asked by mooc for a list of assignments for a given section and I think the query params are getting rewritten by this no_section context seletion thing which then busts the query

**Comment by btopro** [comment]
`NO_SECTION` constant replaced with `FALSE` for consistency with other section context returns that should have been empty (like admin pages)

**Comment by btopro** [comment]
Well that was fun lol.
