### ISSUE TITLE
Add default configuration to mathjax

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#459]
We should add the default configuration settings to MathJax so users can scale the font sizing appropriately.
#458

**Comment by btopro** [comment]
@heyMP This is now provided via a textbook_mathjax submodule which applies the recommended configuration from that other thread and also enables the input filter and wysiwyg buttons for mathjax to work. This isn't enabled anywhere but it is available now for 1 click / enable operation to get it up and going in new sites you would do.
