### ISSUE TITLE
Update Behat bash Script Settings

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#469]
The behat.sh script needs to add these lines to the FeatureContext.php file: 
   use Behat\MinkExtension\Context\MinkContext;
   MinkContext
I will update the .sh file to insert these lines upon installation.

Additionally - if anyone has other recommendations for extensions for Behat, let me know and I can add them to the composer.json file.

**Comment by btopro** [comment]
@mmilutinovic1313 didn't you do this or is this that thing that optimizes the Behat script?

**Comment by mmilutinovic1313** [comment]
@btopro this is the optimization thing. I'll work on adding this as a patch after I finish the menu bar bug.
