### ISSUE TITLE
Switch install scripts to use php-fpm / FCGI

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#472]
I'm running a modified install configuration and it's rocking. Uses so much less memory and thus far has provided additional stability. As part of this transition we could also start adding in the node.js components for when we start using #411 or #381 under the hood. Otherwise we'll need a separate vagrant routine just to test these components (unless @bradallenfisher thinks maybe we should silo it even in testing).

**Comment by bradallenfisher** [comment]
will be looking at things like the best way to add things like node.js as mentioned. For instance so far the best luck I have had is with NVM. using this line... not as root... 
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

from

https://github.com/creationix/nvm

but yeah, this needs some love and testing.

**Comment by btopro** [comment]
node may need to start to get into that "here's the directions for how to do this" or at least start as a separate 1-line installer. Much like if @AndrewGearhart asked me for an Apache Solr instance I wouldn't be bundling that out of the box just to support the libraries crazy desire to index :). We'd provide directions on how to correctly get that going and it would be silo'ed on a different server (for example).

Learning Locker will behave much the same way; we can make a script to help get it going but without a full on digital ocean / EC2 API credential it's hard to setup all these other servers and plug them together automatically. A long time from now (like a month or two ;)) then obviously we'll have this ;)

**Comment by bradallenfisher** [comment]
#736 fixed this. 👍

**Comment by btopro** [comment]
@bradallenfisher so all the one-liners now use fpm (with the exception of Cent6.x which is legacy)?

**Comment by bradallenfisher** [comment]
double checking now that you mention it. I know that centos 7 does. didn't think about ubuntu.

**Comment by bradallenfisher** [comment]
no ubuntu 14 is still mod_php 5.5.9
