### ISSUE TITLE
Everything we need to fix to make this actually something usable, at an infrastructure level

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#475]
https://www.youtube.com/user/psuelms/videos

need to hide these some how, they have tons of views but I'll be starting to record a lot of tutorials soon so... .yeah.. want to do that some place else.

**Comment by kfurst** [comment]
@btopro 

This isn't directly connected to this issue but kind of is. I've just spun up a new vagrant version of elms after taking a break (long story involving another lms).... anyway....

1. It works fine and I can navigate (kind of) through the stock content but my basic issue with a vm copy of elms has always been, "Now what?" 

By that I mean, beyond creating a new course via CIS with some dummy content or navigating to the another service and creating a timeline or something, I can't get much further. For example, I'll click on People in the flyout which is how I assume I add dummy users for the other services all at once. Yet it kicks me to a login page where admin/admin isn't recognized. 

So then I get frustrated and go to the Drupal admin and create people there. I know this is the exact wrong thing to do since it is just creates one instance of a user which then probably isn't recognized across the other networked services. But I do it anyway.... 

Why? Because as soon as I go into the admin menu, it's just Drupal and I 
a.) get it 
and 
b.) feel like I can actually "do stuff" even if it is just essentially breaking all the cool things about elms. 

I've watched all the vids ELMS has on YouTube which seem (IMO) to either support the concept or demo features. I get the concept. I get the features as you present them in the demo. My issue is that I feel like I can't replicate any of them which is SUPER frustrating as I'm like, "Yes! this is what I need. I've got the box with the supercomputer components but oops the instructions got wet and the ink ran so I'm on my own with a hammer and blowtorch and a lot of swears..." 

So I'm in desperate need of some tuts a la:

1. In order to add faculty and staff, do this:

2. Is "CIS" via the online.elms.... meant to be the landing page? or should it be a redirect from another site? How is authentication handled at PSU? LDAP, G OAuth2,? Like, what is the page order a student gets for ELMS (1. exterior site link 2. Login page (or SSO???) 3. CIS home?? It's just that I'm not sure what your PSU authenticated user landing page is/should be. I created a student user in CIS to try and well...

3. Why do I get kicked out/have to login in again if I'm simply navigating between services? If I start in CIS and click on any of the other services in the fly out, it kicks me out and I have to login again. The version I spun up today actually doesn't recognize the admin/admin so I can't get into anything other than CIS. In the past, it would kick me out but I could throw in admin/admin again and it would work in any of the other services except People. 

4. After you add a course, do you build in there what you can but then navigate to the other services to build course content there (thinking of maybe the Media service) and then finally return to the course and link/reference it in? How? 

5. Where does the admin live? i.e. should I be messing about in the Drupal admin menu or not? OA2 for example has a special config menu for admin where one has to make changes rather than making them straight from other pages under the core structure menu. Is there something like this that's a dashboard for admins?

I'm looking for a more or less singular spot where an admin spends a lot of time managing a live site. Where I would get my reports, manage my users and groups, manage the site map... maybe moving a course from one department to another, etc. Tasks I typically do in our current LMS. I know I can get to much of this via the Drupal admin pane but then I'm sure that probably just breaks the interconnectedness between sites. 

6. How are submissions archived? Rick made that great video for me regarding learning locker and competencies. Yet, I'm also thinking about the digital portfolio component of our students' requirements. I would love a way for a student to easily see and manage aggregated submissions after they've received feedback. 
----

My goal here is to get enough of a demo version going in a VM that I could demo here for decision makers with the hope we could then invest time and resources (even if they're just mine) into moving this direction and out of the traditional LMS solution we have now. However, I'm stuck which is extremely frustrating since I feel pretty comfortable with Drupal 7 core. 

So am I just dumb or what? (It very well could be...)

Or maybe better question.... What's the tutorial documentation plan for the next 6 months for us non-PSU people?

**Comment by btopro** [comment]
I think this will get broken out into several issues referenced here so we can track and tackle each. First of all, thank you for asking all these questions. We're in a bit of bubble given the resources we have access to and our setup so there are a lot of assumptions around distributed user authentication that our systems make a non-issue (hence the frustration I'm sure when I just click stuff and it works).  So, i'm going to run through these one at a time.

## People, authentication, how do you get data
We have Cosign (called Webaccess here) which allows for distributed authentication. If s site needs authentication (like every site does) it calls for webaccess. If webaccess is already aware of you being logged in via the Cosign (it's SSO for EVERYTHING web at PSU, login once somewhere, your in everywhere), then you have access to everything. It'll log you in on demand, broker the connection, there's probably .25 seconds involved generally so people don't notice (or care) when switching around.

What the Vagrant setup does is attempt to use Drupal.org's SSO called Bakery (drupal.org/project/bakery). What I really need to do is sit down and get Bakery
1. working out of the box every time in all instances no matter where you are
2. have this be the case via the automated installer whether or not its via vagrant (this has a security implication bc of token generation so it's not as easy as the fake token creation in vagrant but possible for sure)

There's an issue recently about switching from CIS to People as the bakery authority. The People distribution at the time of this writing doesn't do much of anything other then hopefully install. It's planned functionality that will be worked on this semester to provide:
1. an account for everyone with VERY lightweight fields associated to it for a global profile of sorts.
2. the authority for telling other sites someone is logged in so that instead of throwing access denied it'll realize they are logged into people and log them in on-demand (much like webaccess does for PSU).

CIS Provides logistics, we use these logistics to sync with a data source, in our case roster data from our legacy LMS. This is an access string which we pull which relates to sections. These sections then get propagated throughout elmsln and then systems ask for an updated roster nightly (or whenever) and people get synced up based on this data source. @rickhumphries is doing this via some other method, I think pulling from an XML list of users but he could speak to what they do. Wisconsin was manually adding people (obviously I don't recommend this).

the compliance system does have the ability to add accounts globally but it's on a per account basis and is intended for when people make access requests.

## You're not dumb, it's still too complicated
I'm sorry we're not there yet. I want to be but that's also why I built a grassroots army (https://btopro.wordpress.com/2013/09/25/products-are-ephemeral-movements-are-eternal/) for several years to prepare for the point that we are reaching now internally; a distributed series of deployments managed by a distributed group of people, taking input from faculty and students and directly improving the complex infrastructure that needed to be built in order to allow for organized chaos. We're as much a social movement (if not more) then a product, and heart and minds aren't so easily changed.

## Admin menu settings
These settings are PER site and there is UX unification still to be done on certain settings to ensure the propagate so that (for example) if someone is added to the people site (which makes sense I totally agree with you) that they then are automatically added to all systems for that course.

## Kicked out all the time
This is an issue that I have to resolve, it shouldn't be doing that (obviously) and it's because I'm trying to switch the bakery authority token from CIS to People. If you are comfortable with command line, drush can be used to repair this: `drush @elmsln upwd admin --password=admin --y`

If you haven't dug into drush or the command line of the system via `vagrant ssh` I highly recommend it. It's why nothing seemed to be happening for a few months because of investments there. `drush sa` will list all the systems and what you can access. There's also a command line version of elmsln for performing different tasks in automating the administration of the system, just type `leafy`.

## where do students go / how do they know where to go
Inbox will unify their info across courses as it has calendar / messaging / notification aspects planned. As I said, planned. For right now we send them a direct link to their course space as part of setup and we use an LMS as a crutch. I wrote in a blog post 4 years ago that we'd systematically hollow out the LMS till there was nothing left and that's exactly what we're doing. Attacking one problem at a time until eventually there's no more need for an LMS as a crutch. It's why we support LTI launches.  Another potential solution would be to run Moodle or Canvas as an open source crutch that at least centralizes info, then LTI launch off for the parts of ELMSLN that you like and make more sense (we're always about options, even if that's not us, it's empowerment and choice).

In Rick's instance, students will be going to the CIS. that's their dashboard and he's added in a notifications / messaging system and dashboard that are pretty custom to what they are doing (along with the badges). We have the code for this and they are willing to share but it needs refactored and added to the right place in the larger ecosystem for sure.

## Media and navigating away
These elements are integrated more fully via HAX but at the moment yes you need to navigate away from the content system in order to build out / upload more complex components to the media / interact systems. Interact makes some sense as assembling a timeline is a pretty complicated task of its own, media obviously will be more deeply integrated. After creating media / interactions there's a "remix" / "share" button in the top right (people with arrows pointing in a circle for now) which has all the possible short codes used to automatically represent what's being looked at. These work on content as well if you'd like to remix one piece of content into another (they can become circular so don't do this :)).

## where is admin
Admin lives in the top right under the name of the course, these settings jump you to parts of the drupal admin side of things. Also if you having trouble finding the admin_menu then hit the tilda ` key and it'll pop-down the normal drupal way of doing anything. In mooc, studio, and others there are many features not turned on out of the box and we'll eventually build a "drupal-ish" admin menu side of things that basically enables and bulk changes functionality of the site and network of sites to match what someone of a faculty mindset would think (giving them the power / flexibility of drupal without the full admin side).

## moving from one department to another
This would happen in CIS, though it has no real implication other then showing things in lists based on department or crafting custom queries to theme based on department (an idea used in a past life).

#demo
I've been trying to get through the beginning of the semester with some things here and there and then I plan on making a demo. Requirements of a demo (to me):
1. fully functional single sign-on (obviously)
2. fully functional experience for every user based on role (including admin, yes, full admin)
3. The demo forcibly destroys and rebuilds itself either nightly or a few times a day. This ensures we can let people do whatever they want without whatever they want becoming a gaping security hole.
4. hosted in EC2 outside the PSU network, again for security purposes, with no command line access (vagrant will be needed to restore this).

## tutorial documentation
hit zero 0.1.0 target issues or feel comfortable pushing things off to 0.2.0 (we're close). Push 0.1.0 out and start documenting both in video form as well as refreshing docs.elmsln.org and api.elmsln.org. Youtube will be flooded as soon as we hit 0.1.0 and after we have some additional staffing announcements (cause we're ramping up internally soon...).

0.1.0 != every system in the network done, but the roadmap is solidifying and system stabilizing that we have clear ways of updating things after the fact; Rick's deployment and success with recent automated upgrades (as well as our internal ones to this affect) have done so as well.

**Comment by btopro** [comment]
#252 
#253 
#56

**Comment by kfurst** [comment]
OK first look this morning. 

1. Password issue resolved via Drush. 
2. Leafy is the greatest thing since sliced bread. No lie.  God how I wish the Open Atrium 2 sites I manage had something like this. 

More later as I work through the rest of this.

**Comment by btopro** [comment]
Keep em coming :)

Wp8
________________________________

**Comment by kfurst** [comment]
So...

Admin- Found it and it makes sense. I like "Drupally" things. 

We're currently using Moodle for both instruction and a curriculum warehouse so if I have to use that for some things and slowly transition, that's not only plausible, it's likely. 

The plans for documentation et al. make sense, too. 

With the state of things as they are + the number of crutches/institution specific things at PSU, how did Wisconsin get started/make the move? 

And finally, what next? In the sense that I still think things will need to come along a bit before I can get a basic demo on a VM ready for show & tell... What, if anything, could I help out with in the list of 10k things that need to happen to make things just work? While I'm adequately comfortable with Drupal, Drush, basic LAMP and so on, I'm likely never going to be contributing a module or touching the code. My expertise comes from the instructional side of things. Nonetheless, I believe in the project and would like to help. So if you want to assign something to me, I'm cool with that.

**Comment by btopro** [comment]
Reporting issues, responding to discussions of pedagogy, making feature requests, jumping in on conversations looking for feedback about capabilities / inflection points in design decisions, helping write documentation, telling people you think this is cool and spreading us word of mouth, any and all help is of equal value.

As far as "make things work" we definitely need clean up in the Bakery / SSO stuff for those not using a more advanced authentication system (the crutch you reference). The things PSU has as an advantage (if you will)
- A jenkins instance that automatically helps w/ security, upgrades, and bulk task issuing against the 7 deployments at penn state. This is a stand alone server I setup to help manage things at scale, where scale = multiple elmsln deployments.
- Roster data synchronization from an internal API so that students, teachers and TAs automatically get access places
- Cosign / centralized authentication so we don't have to use bakery
- me and @heyMP able to fix things at the drop of a hat when needed, we live this

ALL of the PSU specific system modifications were abstracted from the PSU namespace and contributed here as part of the examples directory -- https://github.com/elmsln/elmsln-config-example/tree/master/shared/drupal-7.x/modules

these aren't meant to be run in production necessarily but can easily be forked for local deployments. We have about 10 modules specific to PSU integrations (or connecting to legacy systems in-house) that we have. All relevant ones for others have been contributed.

Wisconsin got going awhile ago by contracting with me directly but I did a lot of custom work for them which I wouldn't do at this point (we rolled most of that in). @rickhumphries group contracted with a firm to build out customizations. @heyMP 's boss hired him bc she believes in the mission of the project and also wanted customizations.  So generally there's someone there to help keep things going forward (much like those who run moodle on their own).

Leafy is there in part to try and eliminate the systems administrator role from the skills needed to run this, much like the 1-line installers are there to help w/ the same thing. Down the road, services that help make 1-line install a thing of the past will be available so people can BYOI (bring your own Infrastructure) and run it on your own rig. Also shooting for an RPM model down the road where people can get on our stable upgrade path (free and invisible, obviously).

Long and rambly again but as always, just jumping in and helping us push things forward always appreciated.

**Comment by btopro** [comment]
been messing with bakery all morning and it appears to be doing the automatic login in the bulk of scenarios. I say bulk because currently it's automatically logging into all systems created downstream (courses, studio, etc) but the authority systems will all throw access denied (falsely) where if you refresh the page your actaully logged in. UX issue for sure, still working through it.

Also bakery the way it's being shifted (as far as what our authority is for it) will break backend webservice calls which I'm currently debugging.

**Comment by btopro** [comment]
reviewing now; looks promising on the SSO stuff thus far

**Comment by btopro** [comment]
@kfurst after much testing and patching, I believe bakery is happy out of the box and will now allow logging in from anywhere and having it automatically log you in everywhere else. newly created courses also respect the login token so you get access automatically. #56 still needs accounted for though. Vagrant does this automatically because it's not really a secure method of doing so (shared hash key). To make this happen at run time we'll need to author two modules automatically that have the creds everywhere needed to loginto the newly created network.

**Comment by btopro** [comment]
more documentation flushed out, critical bakery issue has also been resolved, cleaned up core UX via 0.0.7 and 0.0.8 pushing out now

**Comment by btopro** [comment]
I don't want to put words in @kfurst 's mouth but I think if we can get the OOTB installer to support bakery like Vagrant currently does that we'll be able to jump up a version. 0.0.x focus is on critical things prior to claiming a higher level of confidence in the platform's ability to be upgraded / sustained. Yes it's been running w/ supervision for 2+ years but that's by the original developer. We're hopefully starting to reach a point of stabilization that others without any development experience can jump in and have something that they can build with.

0.2.0 will focus on enhanced usability, documentation, and flushing out more tools
0.3.0 will focus on more tools / infrastructure
0.4.0 is currently where we've pushed everything that's out of scope of the next two point releases

After some additional testing and upgrades to internal deployments this week and the #56 being resolved I'm ready to bump us up to 0.1.0 unless there's feeling that this thread hasn't been resolved (a blocking issue for cutting a greater version number then we currently have)

**Comment by btopro** [comment]
Bakery on, secure and correctly configured out of the box in vagrant as well as production installs.

**Comment by rickhumphries** [comment]
@btopro great work on this so far. Think this will really help push things forward with people taking things for a test drive. 

I've spun up a new network on a CentOS 6.5 box and logged in as admin/admin on the people.elmsln.dev site since this is the bakery master now. However when I click to go to the CIS I get taken to an Access Denied page at this URL: http://people.elmsln.dev/bakery/login

![image](https://cloud.githubusercontent.com/assets/4973810/12887475/70cc4f4c-ce6c-11e5-9cc5-e3e783744e52.png)

Any ideas? I'm trying to spin up a course site with a forum to see where things are at with the discuss distro currently :)

**Comment by btopro** [comment]
well that's weird but you shouln't log into people, still log into online.elmsln.local

**Comment by btopro** [comment]
also make sure your host file is up to date -- docs.elmsln.org/en/latest/development/Vagrant-Step-by-Step-setup/

**Comment by rickhumphries** [comment]
Yeh, host file is up to date (though it doesn't include hub.elmsln.dev). If I go to online.elmsln.dev it always redirects to http://people.elmsln.dev/bakery/login, whether I'm logged in or not

**Comment by btopro** [comment]
HM try killing browser cache as that doesn't sound right. I'll rebuild my vm now

Wp8
________________________________

**Comment by rickhumphries** [comment]
Cleared site cache, logged out, cleared browser cache and tried again but still redirects. Let me know if you need any more info. I can DM my host file info too so you can see what I'm seeing if you like?

**Comment by btopro** [comment]
@rickhumphries hmm... are you sure you have the latest version of the repo before doing this? What browser is this in and I can try testing? Try using an incognito window when doing it. I haven't been able to replicate this since bringing a VM up after Thursday. A ton of work was done Thursday specifically on this component with installation. Thursday when Hub was added in there were several hours where the installer was bricked because of a Drupal core change that was difficult to detect without running through Vagrant after detection.

**Comment by rickhumphries** [comment]
@btopro I installed it all over the weekend so it's pretty recent. My computer doesn't play nicely with vagrant so I always just run the CentOS 6.5 install on a Digital Ocean server. 

I'll DM you the digital ocean ip

**Comment by btopro** [comment]
Time for @rickhumphries to give it a shot but I've had multiple successes on Digital ocean, locally and now (hopefully) EC2 (waiting for it to finish). Did this in CentOS 6,7 and ubuntu 14. The problem boiled down to Varnish being enabled by default (but we disable it on the fly in Vagrant) so it was stripping off the Bakery session cookie that detects if you can login across domains. Also helped in identifying an issue that made logins take longer to resolve then they should. Also, ELMSLN requires at least 2 gigs of RAM so keep that in mind when spinning up a digital ocean machine.

**Comment by rickhumphries** [comment]
@btopro this works very well for me now. I installed on a CentOS 6.7 server then created a new course with Discuss and Course services, all without a hitch.

I think the only missing piece of the puzzle in terms of a 'plug in and play' situation is being able to create users in People (or wherever), then syncing them across authorities and being able to then enrol these students on courses (in the CIS?).

Other than that, it's spot on - and I'm creating a demo course as we speak :)

**Comment by btopro** [comment]
Excellent! The people notion came up at the sprint in NJ with @sbubaron . definitely noted. We'll probably be having sections sync over from CIS and then the ability to do a form of global section management (roster) from the people system. Currently the "magic" at PSU sees us sync all systems with our LMS independently; instead I want to sync all this data either against CIS or people which would provide a logical routing point to work on the interfaces and other things described to make this 'plug and play'. #298 is something that would make this possible given that our 'pin prick api' (yet to be detailed outside of the core team) is working. This allows for a simple way of spidering calls across networks and doing so at a high level of throughput.

Ok, I think we can split this issue off into an issue related to the management of people in the people distro unless I'm missing other pieces that would be required for messing around with this more.

**Comment by btopro** [comment]
#550

**Comment by btopro** [comment]
550 updated and #617 and #616 created off of it. While important and the parts split off, there are backend and less obvious methods of integrating people and rosters across the deployment. These currently rely on coders in some form though 617 shouldn't be hard to do and would allow for associating a CSV / datafeed of users to the logistcs involved. Chime in on #550 with anything related to the 3 ways I see adding people. As @kfurst mentioned, we can always jump into Drupal land and manually add people but those is a last resort.  To do things at scale what we do internally is run things like
```
drush @elmsln ucrt USER --mail=USER@EMAIL.ADDRESS --password=PASSWORD --y
drush @elmsln urol ROLE USER --y
```
Drush 6.x is what's built into ELMSLN under the hood. Here's a cool site with all the possible commands (and we include many more if you run `drush @online help`) -- http://drushcommands.com/drush-6x/

As the bulk of this issue revolved around Bakery which we've debugged to death (hopefully) and got largely working (and automatically!), I'm going to close this and leave the last issue blocking a 0.1.0 release as #25 which has work here -- https://github.com/elmsln/handsfree-demo . I have this working though it needs additional debugging (because I won't set this in motion unless it automatically maintains itself). This works for centos7 but needs additional debugging for cent6 (which we'll run internally), Amazon (which we'll run for another example). I'll also probably fund a cent7 deployment personally because... I believe in this with everything in me.
