### ISSUE TITLE
Adding Resources

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#477]
How do I add resources to a course. I'm guessing this is done through the CIS when editing a section:

![image](https://cloud.githubusercontent.com/assets/4973810/12327826/675bdcac-bad0-11e5-8ac0-d2c395fae988.png)

But how do I get something into that list?

**Comment by btopro** [comment]
It's a content type in CIS Add it and don't set it as a system resource (these don't display on this list and are things like default syllabus language and what not).

`cis/resources` - see all resources
`node/add/resource` - add new ones

Once added, they'll show up here and then you can associate them to a section if you'd like. These then auto build out on the /resources page when in courses

**Comment by btopro** [comment]
This is also more obvious in the 2.x version of CIS as a general note

**Comment by rickhumphries** [comment]
Ah yeh, I see now :) Thanks
