### ISSUE TITLE
Export Book - invalid tag name

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#478]
Related: #451 

Updated to 0.05 and when I export a book as an XML package (feeds_node_helper_export/{nid}) each field shows as an invalid-tag-name:

![image](https://cloud.githubusercontent.com/assets/4973810/12328079/c1eefe46-bad1-11e5-8f6e-f9c6decffc36.png)

Whereas before it looked like this:

![image](https://cloud.githubusercontent.com/assets/4973810/12328114/d3b09932-bad1-11e5-8469-0b0a88249f83.png)

**Comment by rickhumphries** [comment]
I also get these notices thrown up after going to `feeds_node_helper_export/{nid}`

![image](https://cloud.githubusercontent.com/assets/4973810/12328347/e8988ade-bad2-11e5-812e-6cc253a01b8c.png)

**Comment by btopro** [comment]
wow.. that's weird. Don't export often so must have missed that.

**Comment by btopro** [comment]
@rickhumphries can you try disabling and reenabling that capability, maybe even reverting the feature it's attached to? I'm not able to replicate this at the moment

**Comment by heyMP** [comment]
I'm experiencing this too.  Looking into now.

**Comment by heyMP** [comment]
Created an issue on d.o. for a possible patch.  https://www.drupal.org/node/2656418

@rickhumphries try going into

`admin/structure/views/view/feeds_node_helper_export/edit`

then under `Format` click `settings

then set `transform type` to `underline`

**Comment by btopro** [comment]
why does this work?

**Comment by heyMP** [comment]
Well in theory, this option prevents you from allowing any invalid characters in the tag name, ie. spaces.  So by running it through the `transform type` option it will convert those characters into underlines.

However, I don't think any of the tags it generates has spaces in them so I don't know why it would be causing the `invalid tag` option.  It's more likely an issue with the XML format module itself.

**Comment by heyMP** [comment]
Ignore that previous commit to my elms fork, I didn't realize that the feeds_node_helper_export was a d.o. project.  The patch on d.o. should be good.

**Comment by btopro** [comment]
I mean we own it so.... :p

**Comment by heyMP** [comment]
Yeah I know, but when I updated the feature, it removed the d.o. packaging information.

**Comment by rickhumphries** [comment]
Hmm, so this was the detail to what is showing as 'overridden', but when I click to revert it, it stays as overridden. 

![image](https://cloud.githubusercontent.com/assets/4973810/12563896/577547e2-c3a4-11e5-97a3-a2e766770f89.png)

I've tried going to the url you suggested @heyMP but I don't have the 'views' option strangely: 

![image](https://cloud.githubusercontent.com/assets/4973810/12563915/6385ea5a-c3a4-11e5-8377-f3227456236c.png)

Do I need to switch anything on?

**Comment by heyMP** [comment]
Yeah it's weird.  Mine doesn't revert either but the settings are correct.  I believe our views api version is different than the `feeds_node_helper_export` module so it's going to remain stuck.

If you can't get into views it means that the `views_ui` module isn't on.  We turn that off on production.  If you enable that module you should be able to access the url.

**Comment by rickhumphries** [comment]
Ah yeh good stuff! That did it. Cheers @heyMP :+1:

**Comment by btopro** [comment]
can we make this closed if @heyMP has it fixed going forward?

**Comment by rickhumphries** [comment]
Yep that's OK with me

**Comment by btopro** [comment]
fixed. we talked about it, mike made a patch, and then we never applied :) oopsies

**Comment by btopro** [comment]
I had trouble reverting this as well but it allowed me to select it anyway. hmm... may have to keep on eye on this one
