### ISSUE TITLE
Bring back "ELMS Places" concept

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#479]
This is something from the D6 version of ELMS that we haven't ported over to ELMSLN (cause I forgot). It's a complex content type that renders itself as a map so you can do geo location type of stuff as a widget. This would be a perfect addition to ICOR / interact. 

Video showing the prototype from way back when. Inside of a flyout, we'd make it an in-page thing -- https://www.youtube.com/watch?v=oib5lzMtG0k

**Comment by btopro** [comment]
@aitala any thoughts on how best to do this?

**Comment by aitala** [comment]
I think you can do this pretty easily with Open Layers, Views, etc.  There is a new OL JS library out which has a new D7 OL version 3 module which I have not used yet.  There (currently) is no migration between V2 and V3 and there may never be one.

I’ve not used the new version so I don’t know how different it is. But it looks substantial.

OL is pretty heavy, so there might be better ways using GMap or Leaflet. If you just want to place a marker you might want to use GMap or Leaflet.  If you want more complex maps with more data, then you may need to use OL.  See http://calendar.ipmsusa3.org/event-map for a map with multiple layers - pins, boundaries, and pop-ups.

Inputting the location is also important…  I don’t like using the map to drop a pin.  Lat/Long is better, but not always useful.  Sometimes a physical address is needed…  soo….

What would be useful - but I dont know if its possible - would be to have multiple methods of specifying the location that don’t conflict in some way.

**Comment by btopro** [comment]
Good Pro/Con list there. I think we'll go with GMap to provide some level of support and then if someone requests a non-google source (gov space for example isn't allowed to use google maps) then we could help craft a solution that isn't Gmap based. Perhaps providing suffix-ed map engines for this functionality would be useful so people that need to swap it out could. ICOR basically exists for these kind of inflection points to not cripple the system as a whole :)

**Comment by btopro** [comment]
@aitala cant in view given your latest blog post?

**Comment by aitala** [comment]
Not sure what you mean, but I think Leaflet would work using non-Google maps (OSM).

**Comment by btopro** [comment]
wow i dono why i wrote that;meant have you changed your view given latest post

**Comment by btopro** [comment]
made a ton of progress. notices / things to clean up
- [ ] patch leaflet_widget so that it ONLY uses it's built in version of the library

fix this, on the EVA that has a map view applied:
```
Notice: Undefined property: stdClass::$entity in leaflet_views_plugin_style->render() (line 281 of /var/www/elmsln/core/dslmcode/stacks/interact/sites/all/modules/leaflet/leaflet_views/leaflet_views_plugin_style.inc).
Notice: Undefined variable: entity_id in leaflet_views_plugin_style->render() (line 284 of /var/www/elmsln/core/dslmcode/stacks/interact/sites/all/modules/leaflet/leaflet_views/leaflet_views_plugin_style.inc).
Warning: array_flip(): Can only flip STRING and INTEGER values! in EntityCacheControllerHelper::entityCacheLoad() (line 69 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/entitycache/entitycache.module).
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->cacheGet() (line 388 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/entity.inc).
```

**Comment by btopro** [comment]
! in there now!
