### ISSUE TITLE
Icon display inconsistent across courses

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#482]
Bit of a strange one this, and probably specific to us. In some courses, the 'gear' icon and the 'edit' icons aren't showing, although the links are still there and function as usual:

![image](https://cloud.githubusercontent.com/assets/4973810/12350766/08ad6ee0-bb71-11e5-828d-bd8860ea7cfc.png)

In these same courses, some of the icons in the network modal also don't show:

![image](https://cloud.githubusercontent.com/assets/4973810/12350830/49f7bdb0-bb71-11e5-87b2-167ee86b3e6d.png)

However, in other courses, everything shows fine:

![image](https://cloud.githubusercontent.com/assets/4973810/12350867/938ab0a4-bb71-11e5-95d2-fbaf1ecbc07a.png)

There aren't any cases where the gear and edit icons show but the network modal icons don't, and vice-versa - so the display of these seems to be linked, but can't figure it out

**Comment by rickhumphries** [comment]
Would this be the reason?... in those courses where the icons don't display the Foundation Access UX feature shows as 'Needs Review'

![image](https://cloud.githubusercontent.com/assets/4973810/12352569/f7a022a6-bb7e-11e5-8a1d-46d83174eb56.png)

Whereas for those where the icons display, it doesn't:

![image](https://cloud.githubusercontent.com/assets/4973810/12352589/2a97d0f0-bb7f-11e5-9053-cda4e77426a0.png)

**Comment by rickhumphries** [comment]
Hmmm, maybe not actually. Just came across a course where the icons aren't showing but the state is default for that feature

**Comment by btopro** [comment]
did u wipe the cache and ur browser's cache?

**Comment by rickhumphries** [comment]
You're right - it was the stupid browser cache! *facepalm*

**Comment by btopro** [comment]
np :)
