### ISSUE TITLE
System Infrastructure Discussion - The Roles of CIS and Dashboard

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#484]
The current thoughts about the future Inbox distribution, as I understand it, is that it would serve as the 'dashboard' for the course experience, the first page that any user would be directed to once they log into their account. From here the student would view the courses they're enrolled on, along with other course related information etc. Along with this would be messaging, chat, calendar and progress information.

My concern with the approach to this as it stands, is I think the core function of Inbox would be confused. For me, the name and icon associated with 'Inbox' indicates that the page you are taken to when first navigating to that tool should be an inbox of all messages that you've received.  However, this wouldn't necessarily be the case, as I feel like you'd want the first landing page for this to be your 'dashboard' overview of all the courses enrolled on etc,

CIS has always felt, for want of a better word, 'home' - which is how I still think it could play a role for all user types here by acting as the dashboard. Inbox would still have messaging and calendars - these two seem to sit together in a lot of applications, though that's not to say they couldn't be separate either. But the CIS can be where you could easily view the courses, you're enrolled on, recent activity (which would be sort of newsfeed of xAPI activity), and course progress (the actual competencies or course modules achieved). Since, if we're taking in multiple contexts, staff could also be enrolled on courses (internal training courses for example), but also need a place to manage the different groups of students they might be teaching - and get a top down view of who's falling behind etc. Again, with the CIS being seen as more of a data driven application, I see this sort of functionality fitting in well here, as it would be the tool where advanced ways of filtering and viewing course-related data would be most naturally served. 

Just my thoughts anyway - looking forward to hearing other people's views on this

**Comment by michael-collins** [comment]
@rickhumphries As you know,the CIS is currently the courses (and system/network) management interface. Again, we are going to build the interface into something like this http://codepen.io/michael-collins/pen/JYWBvP. It'll be expanded to provide access to analytics and other functionality yet to be dreamt up. The Inbox/Calendar interface as I imagined it, would be an experience for students to get notifications and reminders of events, assignments, as well as other information about learning and interactivity with the network. We don't have a UI mockup yet, but I'm also imagining a discussion activity wall. To attempt to combine this into the CIS would take us back to the original state of the CIS, which attempted to be all things (config, course creation, public marketing, public course catalogue, employee profiles, etc). So, splitting out Inbox functions and CIS functions makes good sense to me.

As we figure out how to make the student experience more interesting, Inbox will need to be iterated at a different rate from core CIS functionality. This suggests that separating these two experiences is essential to rapidly add new things. If you want to make your own custom student Inbox experience, but use the latest CIS as everyone, now we can easily support that. From my perspective, "home" for course developers and "home" for students are two very different places supporting different types of tasks.

**Comment by rickhumphries** [comment]
Hi @michael-collins. I wasn't suggesting building the inbox/calendar etc. on top of the CIS. There would still be a need (as you described) for a completely different Inbox/calendar authority with the functionality you spoke about.

What I mean is just the 'dashboard', which is essentially the 'homepage' of the entire experience - the area which shows a quick overview of the latest information relevant to you across all courses.  

Maybe this is what you have in mind for Inbox, in which case that's OK, but I think as a user I'd probably find the name 'Inbox' slightly confused. When I click Inbox the first page that I'd expect to go to is a view of all my messages, whereas in this case you wouldn't - it'd be the dashboard.

Not sure if this makes sense, and yeh, mock ups always help with this process too :)

**Comment by btopro** [comment]
We debated the "dashboard" style domain for a long time and think inbox as a name was arrived at because you'd think of looking in your inbox for what to do next. If you login somewhere and it pushes you to your `dashboard` which happens to be in inbox with your calendar, messages, completed achievements / badging, assignments coming up (via calendar), etc.

Mock ups needed for sure regardless of name

**Comment by btopro** [comment]
As the system and @rickhumphries 's styling to match take shape, the "where" this happens is mattering less and less. Infact, the way @bradallenfisher made the people system work for profile where it's remote rendered but displayed locally is a big step towards this really not mattering. Inbox in my mind is messaging. @rickhumphries 's setup for CIS as a dashboard for the learner is worth a look in a few months to see how things flow for users. Inbox is a piece of that dashboard of "what are my courses, what do I have to do, oh hey there are messages / status thingies here".

This could live in people, cis, whereever based on where the user happens to access. We want to blur the lines for the end user as to this being multiple systems so from their context, hitting "my profile" or whatever and perhaps using a navigational style like #1380 could help account for the course context vs me in the world context.

**Comment by btopro** [comment]
Compentencies should live in CIS, ya sold me. Whether there's a dashboard there is less of my concern as this will start to be able to be queried and routed to from anywhere (we're talking over the next year or so) #648

**Comment by btopro** [comment]
Dashboard -- where ever you are / want it to be, CIS, in the course, authorities or otherwise.
CIS - Competency host, full content type, associate to course
LRS - storage of statements leading towards potential completion, distributed and disconnected
Inbox - messaging / calendar services at some point down the road; calendar items would be added in a distributed manner, inbox would more so get pushed all these changes of dates so that someone could be delivered a "here's the calendar" sorta display of material.
Chat system #381 would be a stand alone / distributed socket server (messaging in inbox could theoretically be at some point too).

We're already starting to blur lines between systems on the content production side in some prototypes and once we get to full on angular / #1473 capabilities we'll be able to blur many locations into single apps (of sorts).

Going to close this out as I've acknowledged @rickhumphries 's concerns and I think they make sense.
