### ISSUE TITLE
Instructors should be able to hide content in outline designer

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#487]
![screen shot 2016-01-19 at 9 48 33 am](https://cloud.githubusercontent.com/assets/3428964/12421834/f87f7882-be91-11e5-80f8-400ebfc4cb21.png)

**Comment by btopro** [comment]
Yes. this lives in the module `mooc_ux_defaults` and the variable that needs reexported is `outline_designer_context_menu_exclusion_matrix`

**Comment by heyMP** [comment]
Awesome.  Should we give the same ability to the teaching assistant role?

**Comment by btopro** [comment]
by default, no. most TAs have little or no influence on the structure of material. This obviously can be changed on a case by case basis when there are situations where people need it but as a default probably not
