### ISSUE TITLE
Different Colors for H1 and H2 titles

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#488]
Previously I was able to change the colour of my H2 titles with CSS so that it's different from the page title (H1). But I'm having trouble forcing this through on a new course I've done.

![image](https://cloud.githubusercontent.com/assets/4973810/12425891/d9b2c67e-bece-11e5-8675-d06223942da6.png)

In all other courses the page seems to use my CSS injector code as priority:

![image](https://cloud.githubusercontent.com/assets/4973810/12425929/07c6b0f2-becf-11e5-9936-88d7b27cfffa.png)

However, in this latest course, it's the 'primary color' selection that takes priority and I'm not sure how to change that:

![image](https://cloud.githubusercontent.com/assets/4973810/12426026/72b043b0-becf-11e5-822b-4e03546e0aee.png)

Should the primary colour just control H1 tags, secondary colour control H2 tags etc.?

**Comment by btopro** [comment]
Worth discussion. code block that's providing this currently:
```
      switch ($current) {
        case 'primary':
          $css .= ".etb-book h1,.etb-book h2 {color: $color !important;}";
        break;
        case 'secondary':
          $css .= ".etb-book h3,.etb-book h4,.etb-book h5 {color: $color !important;}";
        break;
        case 'required':
          $css .= "div.textbook_box_required li:hover:before{border-color: $color !important;} div.textbook_box_required li:before {color: $complement !important; background: $color !important;} div.textbook_box_required { border: 2px solid $color !important;} .textbook_box_required h3 {color: $color !important;}";
        break;
        case 'optional':
          $css .= "div.textbook_box_optional li:hover:before{border-color: $color !important;} div.textbook_box_optional li:before {color: $complement !important; background: $color !important;} div.textbook_box_optional { border: 2px solid $color !important;} .textbook_box_optional h3 {color: $color !important;}";
        break;
```

**Comment by btopro** [comment]
as you can see, Primary is currently H1/H2 and secondary is H3,4,5
