### ISSUE TITLE
su claims access denied on ubuntu 14 even when root

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#492]
the su command is claiming that root can't run it?

@bradallenfisher @curiosity26 ever run into anything / hear of anything like that? This is the command in question which currently doesn't apply to ubuntu but works on Centos / RHEL based systems

https://github.com/elmsln/elmsln/blob/0.0.6/scripts/upgrade/system/0.0.4.sh

**Comment by bradallenfisher** [comment]
I think its an environment thing. just guessing though.

su defaults to not change the current directory and to only set the environment variables HOME and SHELL (plus USER and LOGNAME if the target user is not root).  It is recommended to always use the --login option (instead of its shortcut -) to avoid side effects caused by mixing environments.

-, -l, --login
              Start the shell as a login shell with an environment similar
              to a real login:

                 o      clears all the environment variables except TERM

                 o      initializes the environment variables HOME, SHELL,
                        USER, LOGNAME, and PATH

                 o      changes to the target user's home directory

                 o      sets argv[0] of the shell to '-' in order to make
                        the shell a login shell

**Comment by curiosity26** [comment]
Yea I agree. Or you can try hacking it by doing `su -c 'export HOME=/home/ulmus/ & export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/ulmus/.composer/vendor/bin /var/www/elmsln/scripts/utilities/refresh-drush-config.sh' ulmus`. But I can't say you'll have success with that.

**Comment by curiosity26** [comment]
Oh! Also, it could be your order of ops. According to this article (http://unix.stackexchange.com/questions/1087/su-options-running-command-as-another-user) you might want to try `su ulmus -c 'commandy wandy thangy wangy'`

**Comment by bradallenfisher** [comment]
when does this get called.

**Comment by bradallenfisher** [comment]
@btopro is this a manual call or a cron run or what?

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/blob/0.0.6/scripts/upgrade/system/0.0.4.sh it was an upgrade hook that i had to run manually for ubuntu14. means that the 0.0.4 hook is wrong for u14 (not that that part matters). Just want to keep it from happening in the future

**Comment by bradallenfisher** [comment]
yeah... so what I am noticing is that all new systems install composer in .config/composer where as older systems install it in .composer. 

My concern with changing this is that it will break ubuntu12 or centos6. is that a valid concern?

**Comment by btopro** [comment]
@bradallenfisher I think u meant to post this in a different thread cause this doesn't have to do w/ composer but the other issue you were tackling the other day does.

**Comment by bradallenfisher** [comment]
I was referring to the path in the second and third line. I think that is responsible for part of the issue. 

su -c 'HOME=/home/ulmus/ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/ulmus/.composer/vendor/bin /var/www/elmsln/scripts/utilities/refresh-drush-config.sh' ulmus
su -c 'HOME=/home/ulmusdrush/ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/ulmusdrush/.composer/vendor/bin /var/www/elmsln/scripts/utilities/refresh-drush-config.sh' ulmusdrush

**Comment by bradallenfisher** [comment]
i'm currently installing to try to reproduce in an ubuntu 14 env

**Comment by btopro** [comment]
you could execute that command directly and see if it still occurs. `sh ~/elmsln/scripts/upgrade/system/0.0.4.sh`

**Comment by btopro** [comment]
I think it might have to do with them being executed in another script so don't just copy and paste run them

**Comment by btopro** [comment]
the last @bradallenfisher assigned mystery goofy infrastructure / bash issues left

**Comment by bradallenfisher** [comment]
this does allow users to run drush now... 

just confirming after a linode install of ubuntu 14.04

**Comment by bradallenfisher** [comment]
still can't run the above upgrade script though 
``` shell
User's Drush plugins refreshed to latest on system
/var/www/elmsln/scripts/utilities/refresh-drush-config.sh: line 27: drush: command not found
/var/www/elmsln/scripts/utilities/refresh-drush-config.sh: line 28: drush: command not found
User's Drush plugins refreshed to latest on system
/var/www/elmsln/scripts/utilities/refresh-drush-config.sh: line 27: drush: command not found
/var/www/elmsln/scripts/utilities/refresh-drush-config.sh: line 28: drush: command not found
User's Drush plugins refreshed to latest on system
root@ubuntu:~# nano /var/www/elmsln/scripts/utilities/refresh-drush-config.sh
```

**Comment by bradallenfisher** [comment]
latest pull https://github.com/elmsln/elmsln/pull/1324 will fix
