### ISSUE TITLE
Clicking a course in "course list" should take you to that course's home/outline/landing page

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#495]
When I sign in to our instance, I get this page. 

![screen shot 2016-01-21 at 1 36 19 pm](https://cloud.githubusercontent.com/assets/15616523/12490534/162bc8d2-c044-11e5-9fcc-268775fbd789.png)

When I click on those courses though, I get a list of services each one uses which probably makes sense for someone other than me - generally when I see a list of courses as an ID (and an instructor) I would want to go to that course's home page (to begin editing or whatever) when I click the name. Or if it's the first login, maybe a "Start here" page (maybe this is the course outline or the syllabus generator or a tutorial/walkthrough tour like we talked about).

**Comment by btopro** [comment]
sounds about right. Right now you click a course, it sasys everything that's using, you click access service. DO it for the course one and tou'll see the content side of things; your right, needs to just take you to the "course" as most people think of that as the course. still marrying the UX / capabilities of CIS (obviously)

**Comment by kat-wehr** [comment]
Cool. Another thought - perhaps when you are just getting in for the first time after creating a course space, it asks you "do you have content to import" or "Are you building from scratch?" and from there the walkthrough takes the user through whichever experience they choose and then the next time they come back, they'll just be taken to the landing/home/outline page.

**Comment by btopro** [comment]
have you built a space out?

**Comment by kat-wehr** [comment]
Still working on figuring out how... I keep getting "access denied" type errors whenever I try to do something.

**Comment by btopro** [comment]
@kat-wehr excellent point on the "first page". changing that to point to a table of contents by default would be a big step forward for sure

**Comment by btopro** [comment]
I don't know that we'll correct this fully at the moment as @michael-collins CIS prototype is coming up in priority soon and it changes this display completely to have more info
