### ISSUE TITLE
Outline Designer: increase readability of 'hidden' items text

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#498]
Would it be possible to make the gray value of text on items that are hidden just a bit darker? Currently the low contrast makes it pretty difficult to read the greyed out text on the grey background. This affects when you want to move nodes around but also when you try to edit a page name. Perhaps upping the grey value to, say, 70%, would be enough to make it clear that is hidden but still be readable.

![outline designer screenshot](https://cloud.githubusercontent.com/assets/16839175/12513995/e0148fee-c0ee-11e5-8b76-8483561d57e6.jpg)

**Comment by btopro** [comment]
@pja12 I upped the opacity slightly and then if you mouse over it'll show you it normally, see screenshot

![2016-01-24_14-28-18](https://cloud.githubusercontent.com/assets/329735/12538397/cafc9160-c2a6-11e5-9fe0-bb3ce90d4b46.png)

**Comment by btopro** [comment]
@pja12 fixed and active in your course
