### ISSUE TITLE
AJAX CORS Issue

### ISSUE THREAD

**Issue by curiosity26** [elmsln/elmsln#499]
When attempting an AJAX request to a restpoint passing the "Authorization: Basic" header, ELMSN fails authentication. 

I am sending the request with the headers:
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET

**Possible solution:**
Add the following to the .htaccess file for the rest domains
```APACHE
Header set Access-Control-Allow-Origin "*"
```

**Comment by btopro** [comment]
So, most likely if we were to do inter-system ajax calls it would suffer this issue currently (since they are all on different sub-domains), were we to start outright supporting this.

If this call is made via straight AJAX isn't it going to expose the U/P of the server-level user if one were to inspect the network calls coming in and out of the application? This is generally why I call stuff locally and  then have that issue a call to the backend, make the call in the background, process, and deliver from the local function.

Also, is there a way we could unlock this command but only against certain paths? https://www.drupal.org/project/cors seems to suggest that's possible in some of its examples or at least it more contextually allows CORS exceptions based on path / domain matching.

**Comment by curiosity26** [comment]
Well remember, if someone is going to spoof basic authentication, AJAX
isn't the only way to do it. So by allowing basic authentication, you're
just as vulnerable.

That being said, implementing proper Access-Control- headers keeps the
service safe. For instance adding Access-Control-Allow-Headers and
Access-Control-Allow-Methods determine what header information is permitted
in the XHR response. And Access-Control-Allow-Credentials needs to be false
to prevent the Authorization header from being readable via the XHR
response.

By using these headers, you actually make the XHR requests completely safe
by controlling what header information is made available to client side
requests.

You can use .htaccess or .conf files with If logic to control which paths
are given the access control headers. With Access-Control-Allow-Origin, the
value has to be "none", "*" or an explicit domain, so you can't grant
subdomains. I think you mentioned that, but just reiterating.

So yea. It's safe.
On Fri, Jan 22, 2016 at 12:57 PM Bryan Ollendyke <notifications@github.com>
wrote:

> So, most likely if we were to do inter-system ajax calls it would suffer
> this issue currently (since they are all on different sub-domains), were we
> to start outright supporting this.
>
> If this call is made via straight AJAX isn't it going to expose the U/P of
> the server-level user if one were to inspect the network calls coming in
> and out of the application? This is generally why I call stuff locally and
> then have that issue a call to the backend, make the call in the
> background, process, and deliver from the local function.
>
> Also, is there a way we could unlock this command but only against certain
> paths? https://www.drupal.org/project/cors seems to suggest that's
> possible in some of its examples or at least it more contextually allows
> CORS exceptions based on path / domain matching.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elmsln/elmsln/issues/499#issuecomment-173992751>.
>
-- 
Alex Boyce

**Comment by btopro** [comment]
Let me know if that worked (though I think you showed that it did while you were here w/ the 2.x version of your video app); Not making this part of the official release at this time unless these type of requests come up in the future or we're able to move the video app into the core package

**Comment by curiosity26** [comment]
Still getting this error:

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dev.smeal.psu.edu' is therefore not allowed access.`

Could be an issue with other headers not being permitted. Try this in the htaccess:

```APACHE
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
```

**Comment by btopro** [comment]
updated

**Comment by curiosity26** [comment]
Ok for the purpose of testing, can you change this line:

```APACHE
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
```
To this:
```APACHE
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type, authorization"
```

**Comment by btopro** [comment]
k
