### ISSUE TITLE
Authority: Grades / Assessment

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#50]
I've been asked to start making plans for an assessment system - initially as a backup for the legacy one we currently use, with a view to replacing it down the road. 

@btopro I can see from Trello that there are plans for an assessment module to handle the submissions and grading from Open Studio. Is that right? Would this type of thing be an area that would handle submissions from something like the Quiz module too? Would be interested in hearing your thought process on this topic in general

**Comment by btopro** [comment]
So i'm working on the studio tool you reference right now. This is the successor to the system we won an award for some years ago in which students can submit work openly. Also working on the UX in this context and how we can get between systems and what not.  This is purely a submission engine and leaving assessments on these things. There will be rubrics (eventually) as a ton of work has gone into them, I just don't have time in the day to make it a priority atm.

Quiz we currently don't have slotted anywhere other then the interact system which is highly unstable.  Quizzing hasn't been thought through in too much detail but to me at least, a quiz / test is a series of "screens" / interactions.  To get this into the course flow, we'd embed the quiz in a frame in a page. This lets us use the quizzing in multiple places and can keep these interactions separate.

Again, I'm not entirely sold on this approach. Studio is submission / creation engine. Discussion tool is conversation, and then embedding a conversation at the bottom of a page or off canvas or something makes sense.  Interact is for H5P kinds of things but this might be where we either branch in our thinking or just need a prototype to react to. If Interact had H5P and that was low-stakes testing / self-check, and then quizzing found its way in there... well it's no longer interactive stuff (tho it sorta is), it's more so assessment stuff or looking for comprehension.  That's either a stand alone thing or part of that system... i dono yet.

I love making systems with dedicated purposes; I hate making systems cause it gives us all more work to do :)

**Comment by btopro** [comment]
As I see your wording to start and title, I think you're asking for a new, dedicated testing and assessment tool; which makes total sense, it's just a bandwidth problem (human that is) :)

**Comment by rickhumphries** [comment]
Yeh I guess that's how I see it. Low stakes quizzing with auto results/feedback are OK to be embedded in course outline, and can be done with H5P (or whatever), but it seems like there should be a dedicated service based on the quiz module which handles high stakes tests that require the answers to be marked by a course tutor. And this would include an 'assessors inbox' where they could keep track of test submissions, mark answers and provide feedback etc.

I might wait until the unified UX is complete then start scoping out how a service like this might look, with a view to possibly creating our own service type (woah!)

**Comment by btopro** [comment]
:) yes, I completely agree with you, there is a logical place for quizzing / testing.  Another question that would need to be answered for this is is it an authority or a service. Authorities are single point deploys that will need to sync data from CIS in terms of courses and sections. This could be handled in multiple locations for privacy as they wouldn't be in the same bucket but, making it a service could increase the complexity of the build for these (i'm still not 100% sold on interact being a service, that might be a different kind of interactive asset thing).

**Comment by rickhumphries** [comment]
I'm still undecided about whether this would be best as a service or authority. Would be happy to take on board other people's opinions on this. I'm edging towards it being better as an authority though for assessors to keep better control over submissions coming from multiple courses

**Comment by michael-collins** [comment]
I'm not entirely sold on the authority vs service paradigm as it stands...
Wondering if there is another way to think about these relationships?

**Comment by btopro** [comment]
you'll have to open another issue and describe what you mean by that. Things are either deployed as a single system that talks to everything or multiple systems that talk within their own smaller network. If you think there's another type of relationship then make a new thread for that.

**Comment by michael-collins** [comment]
Okay, will do.

**Comment by btopro** [comment]
related is #84 , the abstraction of assessment from submission

**Comment by btopro** [comment]
proposed name for this? assess.elmsln.local  as it would be more then just rubrics? Also what kind of name space for the distro? @michael-collins @rickhumphries thoughts?

**Comment by btopro** [comment]
place holder set, will start to add threads associated w/ functionality for this in the future and they can reference this one. Name is assessment (for the distro) and grades for the domain
