### ISSUE TITLE
Do the options below the WYSIWYG when editing content actually affect the content?

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#500]
These are what I'm referring to (all of them, not just the hidden content option): 
![screen shot 2016-01-22 at 12 51 31 pm](https://cloud.githubusercontent.com/assets/15616523/12518889/62b792d8-c109-11e5-9ed3-d11154e9331a.png)

I haven't noticed anything that changes when I was playing with these different settings (at least related to the content block I was editing). I may be totally off base but are these referring to the top navigation? 

If so, my recommendation would be to move this to an overall course setup/style selection page that is filled out during course creation - that way it will be consistent across the course experience rather than different (whether by choice or mistake) on different pages. Unless there is an instructional reason that the navigation should change during the course that I haven't thought of ... but typically this doesn't happen.

**Comment by kat-wehr** [comment]
Related to Visual Identifiers: Could there be "more info" over these to educate users as to why they would want to use these categories? 

Also, for the images... I think this should be a choice made up at the college or program level... each class should have the same icons/identifiers for the readings, assignments, etc. throughout to avoid confusion. Maybe make this a choice when setting up the course look and feel? Ex: "Use defaults" or "Upload your own icon pack" and lay out the specifications for doing that... just a possibility.

**Comment by btopro** [comment]
#378

**Comment by btopro** [comment]
Visual identifiers if u upload an image it'll be the banner for that page and anything below it. Same with the colors. If you change colors, all Headings will pick up those colors for that page and anything under it. This lets you create visual cues as to what lesson / unit you are in and do so flexibly.

**Comment by btopro** [comment]
Hidden node / hide content will make it so students can't see it but you / instructors still will

**Comment by kat-wehr** [comment]
Got it! Ok. Perhaps  "feature image" might be a better name for that, and the explainer could say something like "Add an relevant image from your computer below the page title."  And maybe some size guidelines height/width wise might be good... although I'm assuming this will convert to % anyway to be responsive. 

And for the colors... a simple line that reads like "Change the color scheme of the page" would help with that.

**Comment by btopro** [comment]
yes, upload a wide one and see what it does :0

I agree w/ the help ideas but thinking maybe a short; here's what this does video w/ a help link in context would be even better (if we can do it)

**Comment by btopro** [comment]
@IBGregory document what the editing form's options do. There's a place holder page in the docs currently for end user documentation and 'edit' experience

**Comment by btopro** [comment]
related #378

**Comment by mmilutinovic1313** [comment]
Should be good to go I think!

**Comment by btopro** [comment]
Excellent
