### ISSUE TITLE
Drupal book-specific search and replace

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/elmsln#507]
Currently, the search-and replace feature in ELMSLN is a truly global function that identifies all instances of the search term across all book outlines that a course uses. The results are numbered, listed, with links to the page and a snippet of verbiage presented in the search results to show the context surrounding the usage of the term. All of that is to the good. I have two requests:

1) I need the ability to restrict the search to a particular book. All courses in the portfolio must go through a search-and-replace to embed the token for the LMS in place of "Angel." Since we are forking an outline to do that, I need to be certain that search results and replacements are made to ONLY that book and no other.

2) The usefulness of the supplied contextual verbiage is limited by the inability to select/deselect invividual instances within a long list. For example, if I get 40 results and in scanning them decide that 37 of them should be batch replaced, I currently have no way to easily deselect the 3 I do not wish to change. If checkboxes were associated, that would be great; if the default state for each box was "selected", that would be even better. It is far more common to want 95% of the identified changes and simply deselect the ones you don't want.

**Comment by btopro** [comment]
in reviewing the project providing this functionality 1 would take a long time and 2 would be a 100% rewrite of how it operates currently. Tagging @heyMP since I'm sure he'll get a request like this too at some point

**Comment by btopro** [comment]
https://www.drupal.org/project/vbo_search_and_replace this would be worth a look though. This would let us use Views bulk operations (which have the checkbox capability built in). From there we could do a search the initial time so the user would know what matches that criteria (views to filter out the list of available). Then check the boxes on the ones you want, then select to modify via search and replace, apply the before and after and only have it do it to select items.

This would be a drastically preferred method over modification of the existing Scanner module which was engineered to aggressively change everything without much in the way of criteria matching.

**Comment by btopro** [comment]
module looks well written, need to dig deeper / test, possibly for our sprint tomorrow

**Comment by btopro** [comment]
should be available in the next build
