### ISSUE TITLE
Need clipboard icon

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#509]
We are introducing a new library that will allow us to automatically copy text to clipboard.  It would be nice to have an icon sorta like this one.

![screen shot 2016-01-26 at 4 23 45 pm](https://cloud.githubusercontent.com/assets/3428964/12595456/64d147b0-c449-11e5-96bd-46516ca72a4a.png)

**Comment by michael-collins** [comment]
@heyMP Check slack UX channel for the icon.
