### ISSUE TITLE
Card design component

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#519]
We need a better design component for previewing media nodes through ELMSLN.  Here is a proposal for a new `card` design component that we could use for a variety of media content types, specifically on our media authority.  This component has been heavily inspired by materialize css card component.

http://codepen.io/heyMP/pen/qbYoPm

**Comment by michael-collins** [comment]
@heyMP Great work. Small issue with there not being enough white space around the text and font wieght/size choices. But overall, looks great! Here it is with some more padding: http://codepen.io/heyMP/pen/qbYoPm

**Comment by michael-collins** [comment]
@heyMP Perhaps we should be taking more inspiration from material in our future components and UI since we don't have enough visual designers working on this project. Let
s have a larger converstaion at some point Really liking this site: http://www.uplabs.com/posts/c/freebies

**Comment by michael-collins** [comment]
@heyMP this is relevnant. Material for Zurb: http://eucalyptuss.github.io/material-foundation/

**Comment by btopro** [comment]
check out this design pattern from lucid chart. card has preview and name on it, if you hover, it shows open / share (common operations) as well as a ... menu. if you click the ... menu there's less common operations.

![2016-02-02_15-56-10](https://cloud.githubusercontent.com/assets/329735/12764021/849795d2-c9c5-11e5-8f53-b74d3f53ba5b.png)

**Comment by btopro** [comment]
@heyMP what would be the best way to move forward w/ this? I need this component as well for our student work shown in the Studio for a clean, pinterest style board of cards w/ simple icons for actions that can be taken

**Comment by btopro** [comment]
#669

**Comment by btopro** [comment]
http://blog.codeply.com/2015/04/07/responsive-cards-on-foundation-angularjs/

https://github.com/akoenig/angular-deckgrid

some additional food for thought here

**Comment by btopro** [comment]
@heyMP love the codepen version btw, wonder how best we can get this into media and studio systems

**Comment by btopro** [comment]
another via @michael-collins  -- http://codepen.io/michael-collins/pen/NAwVzO

**Comment by btopro** [comment]
Here's the cards to implement http://materializecss.com/cards.html . all the css is already there :)

**Comment by btopro** [comment]
#669 being implemented makes this easy. We can pick it up as an angular directive in that thread when we start work on those #1069
