### ISSUE TITLE
Let's look at icon solutions

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#525]
http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html

This font set (MIT License) may be a good way to go. I know icon fonts are going out of style, but we need a way to more rapidly put icons onto an interface and these are pretty nice

Obviously, not everything is accounted for, but perhaps we can fork this project (even the git pages site for documentation), and expand the set... Then I can upload icon font updates.

@heyMP What are the downsides to a process like this?

**Comment by michael-collins** [comment]
This font is already used in material for Zurb, which we are discussing on #519: https://github.com/eucalyptuss/material-foundation

**Comment by btopro** [comment]
looks like this was selected; being implemented now
