### ISSUE TITLE
language for innovate

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#535]
We want you to Innovate!

Innovate is for you to build a brand new tool in ELMSLN. We've all got great ideas, but we can't always bring them to life because of technology. Ulmus is an attempt by the ELMSLN project team to democratize great ideas so that anyone with Drupal site building basics could build a new application that changes the face of education. If you hit tilda (~) key you should see the Drupal admin menu.

This profile is built on top of a meta distribution called Ulmus. All of the tools in ELMSLN use this as their base to build upon. This gives you the User experience of the system, the connotation of 'sections' and all the modules we require for things to correctly communicate with the rest of the rools in your copy of ELMSLN.

**Comment by michael-collins** [comment]
**Welcome to Innovate!**

While most online learning technology provides an answer, this space is designed as a question. How can your pedagogy be realized and extended? Think of this space as a blank slate. You can build, experiment, and test your ideas, with much of the heavy lifting done by the ELMS Learning Network platform.

If you aren't an expert, you can jump in right away by creating a [New Page](/node/page/add), or get up to speed with basic Drupal 7 site building skills with the learning resources. When you are ready, you can access the administrative menu with the tilda (~) key. As general rule of thumb, do your best to avoid duplication of content and functionality provided by other parts of ELMS Learning Network. If you want to show us your work once you've finished, open a new issue in the Github issue queue. Happy building!

**Site Building Learning Resources:**  
[Menus](url)  
[Modules](url)  
[Content Types](url)  
[Blocks](url)  
[Views](url)  
[CSS Injector](url)  

**ELMS Learning Network Theming Resources:**  
[Icons](url)  
[Components](url)

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/blob/master/core/dslmcode/profiles/ulmus-7.x-1.x/modules/contrib/ulmus_core/ulmus_core.module

**Comment by michael-collins** [comment]
Did you check the pull request?

**Comment by btopro** [comment]
There r none

**Comment by juststormy** [comment]
I can't edit this as I need to be on a branch and I have no idea where that is. "Tilda" needs to be "Tilde" key. Can someone please fix?

**Comment by btopro** [comment]
ball in @michael-collins court to fix this item that no one knows what key you mean till you point at it ;)
