### ISSUE TITLE
Increase SimpleTest coverage on ELMSLN Core modules

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#539]
We've got some test coverage on cis_connector which could be extended / used to provide guidance on writing tests for SimpleTest / Drupal 7. https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/cis_connector.test

cis_connector then uses travis to run the tests via drush; see here for how easy it is to run tests via drush -- https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/.travis.yml#L83

This would be a good place to start with seeing examples of SimpleTest coverage and how we can work it into increasing build quality (been great, always can be better) @IBGregory

**Comment by btopro** [comment]
cis_connector is the priority and any modules under there that are NOT features.

**Comment by mmilutinovic1313** [comment]
Are these .test files examples of SimpleTest?

**Comment by btopro** [comment]
yes. there's a module in cis_connector that's just for simpletest which is a fake registry but you'll be writing tests

**Comment by btopro** [comment]
related: #1314
