### ISSUE TITLE
Document Setting up ELMSLN in vagrant up to making a course network

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#541]
Review the current documentation for this and document
- How to make it work
- things you need to do to your file system
- create a course network by checking the boxes
- take screenshots along the way

This should demonstrate to someone how to set things up so they can play with them

**Comment by mmilutinovic1313** [comment]
http://docs.elmsln.org/en/latest/development/Vagrant-Step-by-Step-setup/

**Comment by btopro** [comment]
@mmilutinovic1313 correct

**Comment by proconnor15** [comment]
How to Install Elmsln 

- Download and install Oracle VM Virtual Box. https://www.virtualbox.org/wiki/Downloads

- Download and Install Vagrant. https://www.vagrantup.com/

- Navigate to the folder you want elmsln in, and clone the repository using the command (git clone https://github.com/elmsln/elmsln.git)
![clone elmsln](https://cloud.githubusercontent.com/assets/16597608/13260179/60875b1e-da28-11e5-865f-89e6586f370a.PNG)

- Using the command line, cd to the elmsln folder.

- Add this code to your /etc/hosts so you can access it "over the web"
*Windows users, refer to (http://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/) to allow administrative changes

###ELMSLN development
# front facing addresses
10.0.18.55      courses.elmsln.local
10.0.18.55      media.elmsln.local
10.0.18.55      online.elmsln.local
10.0.18.55      analytics.elmsln.local
10.0.18.55      studio.elmsln.local
10.0.18.55      interact.elmsln.local
10.0.18.55      blog.elmsln.local
10.0.18.55      comply.elmsln.local
10.0.18.55      discuss.elmsln.local
10.0.18.55      inbox.elmsln.local
10.0.18.55      people.elmsln.local
10.0.18.55      innovate.elmsln.local
10.0.18.55      grades.elmsln.local
10.0.18.55      hub.elmsln.local

# backend webservices addresses
10.0.18.55      data-courses.elmsln.local
10.0.18.55      data-media.elmsln.local
10.0.18.55      data-online.elmsln.local
10.0.18.55      data-studio.elmsln.local
10.0.18.55      data-interact.elmsln.local
10.0.18.55      data-blog.elmsln.local
10.0.18.55      data-comply.elmsln.local
10.0.18.55      data-discuss.elmsln.local
10.0.18.55      data-inbox.elmsln.local
10.0.18.55      data-people.elmsln.local
10.0.18.55      data-innovate.elmsln.local
10.0.18.55      data-grades.elmsln.local
10.0.18.55      data-hub.elmsln.local


- In the command line, in the elmsln folder, run the command vagrant up. (This will take a while to get set up)

- In the command line (still in the elmsln folder) run: vagrant ssh
This brings up a fully functional ssh accessible virtual machine.

-  In your web browser, go to http://online.elmsln.local/

- login. Username: admin
    password: admin
![log in](https://cloud.githubusercontent.com/assets/16597608/13260446/767d8ae6-da29-11e5-8346-393a09c54cf6.PNG)

**Comment by mmilutinovic1313** [comment]
@proconnor15 good work on this. Screenshots are useful for sure. With the addresses - I would put them together because users will usually be copying and pasting that section directly into the etc/hosts folder. @btopro is there any specific way you want this formatted? i.e. in a document or GIST etc?

**Comment by btopro** [comment]
Update this file: https://github.com/elmsln/elmsln/blob/master/docs/INSTALL.md it's in version control of the repo. Do a pull request for documentation just like any other code. Put it in markdown (just like the comments in the editor). Robots will automatically update http://docs.elmsln.org/en/latest/INSTALL/ to render nicely :). For the images, add them into the repo as well, maybe in a docs/screenshots directory

**Comment by proconnor15** [comment]
OK. I can do that
