### ISSUE TITLE
Odd formatting on bulleted lists (in A&A 121)

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#544]
Course: A&A 121
I’ve been adding bulleted lists on my course pages and they’re formatting weirdly. The bullet appears to cause a line break after bullet, leaving the text on the next line down. It happened in two instances on different pages. The second instance is in the calendar on the course homepage (See attached image) You should be able to see the bullet items in the calendar field. 
![bullets issue](https://cloud.githubusercontent.com/assets/16839175/12708719/b35064b8-c870-11e5-9c02-ceda7704090b.jpg)

**Comment by btopro** [comment]
@pja12 fixed that on the page by setting a min-width. Has to do with our weak attempt to make tables responsive (which we opened a different thread for). For that specific example in-case you need to fix it in content elsewhere; I added this property to the `<table>` tag:

`style="min-width:1000px;"`
