### ISSUE TITLE
A way to control the appearance of the shortcode generated buttons? 

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#546]
![screen shot 2016-02-01 at 1 32 30 pm](https://cloud.githubusercontent.com/assets/15616523/12726967/88404248-c8e8-11e5-8431-b0ada9952633.png)

Any chance there is a way to make these not yellow? Or is there a setting that I flipped somewhere that is causing this? 

It would be cool to have the ability to pre-define these from the start of a course so they are always consistent by default, then allow the designer/instructor to change the appearance if needed.

**Comment by btopro** [comment]
agree on the color aspect or some way we could remix them as settings in the content to do so. They are unstyled currently and need to be brought into alignment with #221 . Also @heyMP is working on #519 which these might be another use-case / variant of.

**Comment by heyMP** [comment]
Collins did make a mockup of these buttons somewhere, I'll have to track it down.

**Comment by btopro** [comment]
Card for "View submission" Needs to support View submission, edit submission and delete submission links all that pop to different shortcuts and then refresh the outer page.

**Comment by btopro** [comment]
I don't think we'll control this more, we'll just standardize it w/ material so it makes more sense #1285
