### ISSUE TITLE
Need to prefix design components selectors.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#547]
We need to control the scope of our CSS selectors within our design components.  For instance our `image` component is inadvertently affecting everything that has a .image class

The problem is that this can't really be done without changing the names of view modes, which if the name of the viewmode changes will break all existing shortcodes.

Need to decide if we can use inherit_display to change the inheritance stacks to include the new prefixes or if we just go ahead and start converting all of the view mode names to the new prefixed versions, knowing that it will break anyones setup that has been using them.

**Comment by btopro** [comment]
can't we just prefix the items so they are like elmsln-image instead of image ? you could prefix the display mode / class names kicked out. or just do id-image or whatever.

We COULD update the shortcode via preg but I really don't want to do that for obvious insane reasons :p

**Comment by heyMP** [comment]
The way that inherit_display works is that the classes have to be the same as the display name.  And if you change the display name then you'll have to update all of the display mode names in your shortcodes.

**Comment by btopro** [comment]
yeah but couldn't you prefix them all to not collide w/ other things or just prefix the first one?

`class="id-image--left--lightbox"` kind of a thing and then just always str_replace the id- from the front of the class?

**Comment by btopro** [comment]
display inheritence fixes this
