### ISSUE TITLE
Clipboardjs not enabled by default in media system.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#565]
We should probably enable this by default whenever the 'view_mode_tab' module is enabled.  That way it can be easily turned on in any system that serves assets similar to elmsmedia and interact.

**Comment by btopro** [comment]
absolutely

**Comment by btopro** [comment]
@heyMP can you tackel this next, I think it's throwing TONS of nasty errors in media right now if it isn't on and makes it so you can't get shortcodes (or at least not as easily)

**Comment by btopro** [comment]
nm ill open an issue
