### ISSUE TITLE
ELMS AI

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#567]
I would like some kind of input area when I can talk or write to describe to ELMS the kind of course I want and my teaching style using natural language. An AI system would interpret, create a few potential course designs based on instructional design standards while auto pulling and remixing OER content for me to teach with.

**Comment by michael-collins** [comment]
related to #256

**Comment by btopro** [comment]
sounds like a good research project for a RA :)

I think maybe things like this we'll want to start a new repo for, maybe in the vastness of things that could go under project-stark of all the crazy stuff (well.. crazy bc we lack the time currently).

I want natural voice processing to kick of drush recipes and build prototype websites for people; this is basically just an extension of that. First would come a mad-lib approach in my mind. Like a form that's branching path and based on what you pick it's basically building out the system behind the scenes.

This could operate like an inteligent agent like #232 suggests. "How many assignments are you thinking?"
What kind of instructional strategy are you looking to implement? Graphic Novels is something I'm pretty sure we could tokenize the initial design of assignments and what not and set in motion with minimal effort.

Want to make a static codepen that's doing this? Doesn't need to be drupal at all and could eventually serve as part of the Innovate distro #542

**Comment by michael-collins** [comment]
I imagine IBM language processing mentioned in #256 can give you a JSON file http://dialog-demo.mybluemix.net/, which is based on search results of OER Content ([specs forthcoming](https://github.com/open-curriculum/open-education-resource)), and Drush Recipes to deploy prototypes in ELMSLN, this is not all THAT hard to build... (for someone who is not me)

**Comment by btopro** [comment]
if you tag brad on things he usually figures it out in a day or two out of desire to show you up ;)

**Comment by michael-collins** [comment]
@bradallenfisher can you build this plz?

**Comment by bradallenfisher** [comment]
lol

**Comment by curiosity26** [comment]
:+1:

**Comment by bradallenfisher** [comment]
are there any browser restraints on this?

For instance
https://www.google.com/intl/en/chrome/demos/speech.html only works on chrome?

**Comment by bradallenfisher** [comment]
starting work on this here https://github.com/bradallenfisher/speech

unless someone wants to create a new project for this.

**Comment by michael-collins** [comment]
@bradallenfisher @btopro Can we put it in the elmsln org to keep things together?

**Comment by bradallenfisher** [comment]
I have insufficient permissions to do so but I'm fine with it

**Comment by btopro** [comment]
https://github.com/elmsln/AI

**Comment by mmilutinovic1313** [comment]
@btopro and @michael-collins I'm working on a side project now dealing with Naturally Language processing AI, so I can keep you all informed as to if I find any tools we could take advantage of

**Comment by michael-collins** [comment]
@mmilutinovic1313 You're hired! @bradallenfisher Okay, go do your stuff!

**Comment by btopro** [comment]
just going to leave this here... https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API

http://mdn.github.io/web-speech-api/speech-color-changer/

....

**Comment by btopro** [comment]
relates to #953 #952 and other voicecommander threads

**Comment by btopro** [comment]
http://codepen.io/matt-west/pen/wGzuJ web speech isn't hard to do anymore (when browser supports it which many do and will continue to) but this is a nice code pen that illustrates how to modify the voice. could be good for finding / allowing tuning of the voice. Reading courses to people when they click play would just be the beginning. a screen reader for all.

**Comment by btopro** [comment]
#232

**Comment by btopro** [comment]
merging into #1296
