### ISSUE TITLE
Ubuntu / Deb complains about not being able to email

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#568]
WD mail: Error sending e-mail (from email@elmsln.dev to email@elmsln.dev).                         [error]
Unable to send e-mail. Contact the site administrator if the problem persists.                     [error]

This is an ultra low importance issue but ubuntu must need something else enabled like sendmail.

@AndrewGearhart want a server level first commit? It'll be part of the setup script in ubuntu-install.sh

**Comment by bradallenfisher** [comment]
You probably just have to start postfix or something like that the service probably just haven't started

**Comment by bradallenfisher** [comment]
sh: 1: /usr/sbin/sendmail: not found

just need to install sendmail since postfix is a rhel based thing ...come back to this later.

**Comment by btopro** [comment]
@bradallenfisher can you pick this off, should be easy I'm thinking so we can clean up the queue
