### ISSUE TITLE
Generate different default content outlines

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#571]
Question came up as a business starts to get involved with testing about if you can change outlines once they are submitted. The concern was that this was what you were stuck with as far as content outline, that also needs documented and will be in a slew of Q/A issues to follow from them.

Related though, I'd like to have people generate outlines, then use the export capability #570 which will appear on the UI soon so that we can use these as the starting points for people to import / work from instead of the generic ones I made some time ago.
## Steps to accomplish
- [ ] Create a new course space
- [ ] modify content / bring in open content that fits a form of pedagogy / flow of instruction design pattern
- [ ] export (location for that coming in #570)
- [ ] Create an issue here that has the exported file attached (assuming github lets you upload xml files)

@kat-wehr - looking to you to drive this
@heyMP has talked about making some "High fidelity screens" and could do so as a second pass, maybe laying out some slick looking pages from the style guide for like the first two pages or so of each.

This way the outlines are pedagogically driven, get people where they need to go faster, and look awesome to start. For the current ones I looked at a course, copied a bunch of stuff, mocked up 2-3 pages and then copy and pasted the hell out of them

**Comment by btopro** [comment]
assigning @kat-wehr . Basically make a structure that's better then what we have currently and then we'll have a working session to get it exported so @mmilutinovic1313 can clean / sanitize it for general reuse. I think the course your working on for the Fall could be a good model for this.

**Comment by kat-wehr** [comment]
Can do!

**Comment by btopro** [comment]
@michael-collins would it make sense / be helpful fro DMD to have like a starting point gitbook repo to fork from / provide a starting point for development of new courses or is that not templatable to be meaningful to get going?

**Comment by michael-collins** [comment]
I think having something that shows an example of what you can do with Gitbook in reference to elmsln would be enormously helpful for people who want to do it. I don't think we need 7 full lessons. Maybe one example of a lesson hierarchy demonstrating a thing, similar to how the OER Schema Gitbook documentation will work.

**Comment by btopro** [comment]
yea that latter is more what I meant. Was also thinking for your program I've seen 3 courses reference Github and possibly CodePen to use; Maybe a little tutorial / digital citizen / DMD program student bootcamp lesson could be a good example, small in scope, and something you need across the program to avoid duplication.

**Comment by michael-collins** [comment]
Somewhat related, I just learned that you are able to import Gitbooks into other Gitbooks. I have not tried this yet, but it sounds like it could solve some issues. I really like "Digital Citizen."

**Comment by michael-collins** [comment]
Can we define some qualities of a digital citizen? Could talk about social norms/trolls in forum spaces, how to use tools like github and codepen to make things collaboratively,  etc.

**Comment by kat-wehr** [comment]
Might need to tweak some info here for the college audience but this might be useful for this endeavor: https://www.commonsensemedia.org/video/educators/digital-citizenship

**Comment by michael-collins** [comment]
Thanks @kat-wehr That's super in-depth, seems like we'd be reinventing the wheel. Maybe we should send students there, and instead do something like "Digital Maker"?

**Comment by btopro** [comment]
Well, I mean framing as Digital Citizen but maybe I meant more of like "How do be a student in DMD /  the Digital Economy" sorta thing. Which does have some overlap w/ DC so could draw from it heavily but more so the how to represent yourself on social coding platforms, etc.

**Comment by btopro** [comment]
haxcms has issues for this and it'll show up as we have a starting point stamper
