### ISSUE TITLE
Support for adding external applications to course network

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#573]
It'd be a nice feature to be able to add a link to any external applications that you might have for a course by having an 'add external service' option here:
![image](https://cloud.githubusercontent.com/assets/4973810/12813224/8da92bee-cb2e-11e5-845c-396b8aae0bcd.png)
Although, I know this would be handled in the CIS.

If you had the option of then providing a url and uploading an icon for that service then you can start to bring in external applications that you might want to appear on this menu. For example, we have an separate assessment system and e-portfolio for some courses.

**Comment by btopro** [comment]
poorly named but that's the idea of #407

Currently these can be modified via code pretty easily, though obviously a way of doing it via UI is more empowering.

Examples of some code based changes:
http://stem-researchethics.org/ -- fly out is entirely different from normal as all the courses in their system are OER and related, so we mirror the order.

Overrides in one of our courses to provide deeplinks into parts of Canvas:
![2016-02-04_08-28-59](https://cloud.githubusercontent.com/assets/329735/12816285/78973404-cb19-11e5-8b8b-7aac43b3ea79.png)

**Comment by rickhumphries** [comment]
Ah yeh #407 is exactly what I mean. Can't believe I got a duplicate tag...shameful community behaviour! haha

**Comment by btopro** [comment]
hehe. Ur screenshot / description is far better then 407. I'll close 407 and continue that here.

I've planned this out before but haven't landed on a solution I like but basically you'd have 3 kinds of tools:
- Ones ELMSLN provides on its own / really deep integration
- Ones that you as the admin say you have (like OUR calendar tool, assessment tool, etc) theses can be told to auto be added to all or if people can configure to use them or not
- Ones that people can add on demand (as you suggest) which would be (short term) "my course has a youtube channel so let's add that since I point them there a lot" and longer term is "Let's LTI launch to..." so it becomes easy and complex linkage but is variable

Option 2 would support LTI launching as well (currently we are a provider system that can spider so it's basically faking consuming but will support consume in the future)

There will always be the current method of developer highjacking what's supposed to be there as needed :). Here's an example of some (blarg) logic I use (sanitized). You can see we are pushing to different places based on very specific values right now (which I hate obviously) :)
```
/**
 * Implements hook_cis_lmsless_theme_vars_alter()
 */
function EXAMPLEMODULE_cis_lmsless_theme_vars_alter(&$vars) {
  global $base_url;
  if (isset($vars['services'])) {
    // thing for stupid art 10 rubric system
    if (base_path() == '/art010/') {
      $vars['services']['External']['grades'] = array(
        'title' => t('Rubrics'),
        'url' => 'LINKHERE',
        'machine_name' => 'grades',
      );
    }
    unset($vars['services']['Network']['inbox']);
    // DINO links
    if (in_array(base_path(), array('/geodz511/', '/arth111/', '/aa121/'))) {
      $vars['services']['Canvas']['inbox'] = array(
        'title' => t('Inbox'),
        'url' => 'LINKHERE',
        'machine_name' => 'inbox',
      );
      $vars['services']['Canvas']['calendar'] = array(
        'title' => t('Calendar'),
        'url' => 'LINKHERE',
        'machine_name' => 'calendar',
      );
      // specific deep link section til we can use a different property
      // to understand how we're going to interface with this thing
      if (base_path() == '/arth111/') {
        $vars['services']['Canvas']['quiz'] = array(
          'title' => t('Quizzes'),
          'url' => 'LINKHERE',
          'machine_name' => 'quiz',
        );
        $vars['services']['Canvas']['grades'] = array(
          'title' => t('Grades'),
          'url' => 'LINKHERE',
          'machine_name' => 'grades',
        );
      }
      $vars['services']['Canvas']['dino'] = array(
        'title' => t('Canvas'),
        'url' => 'LINKHERE',
        'machine_name' => 'dino',
      );
    }
    else {
      $vars['services']['External']['dino'] = array(
        'title' => t('ANGEL'),
        'url' => 'LINKHERE',
        'machine_name' => 'dino',
      );
    }
    // ELIMedia link
    if (isset($vars['services']['Administrative']) && _cis_connector_role_grouping('staff')) {
      $vars['services']['Administrative']['elimedia'] = array(
        'title' => t('ELIMedia'),
        'url' => 'LINKHERE',
        'machine_name' => 'elmsmedia',
      );
      $vars['services']['Analytics']['learninglocker'] = array(
        'title' => t('Learning Locker'),
        'url' => 'LINKHERE',
        'machine_name' => 'dotgrid',
      );
      $vars['services']['Analytics']['analytics'] = array(
        'title' => t('PiWik'),
        'url' => 'LINKHERE',
        'machine_name' => 'dotgrid',
      );
    }
  }
}
```

**Comment by heyMP** [comment]
I need this functionality as well for a few of our courses this semester.  I'm going to make a module that can be configured per website for now.  It won't sync across tools but it will work until we can incorporate this into CIS or something similar.

**Comment by btopro** [comment]
@heyMP cool! that's probably the first step into repurposing it to be used by the rest. Once you get it working I could wire it into the elmsln api task runner so we could flash those settings across the same network to keep it in sync. Maybe add the customizations to the settings page that has the colors and other things being synced and we can go from there. That'd cover per network modifications, CIS we'd set global (or this paves the way to syncing back from here to CIS data model).

**Comment by heyMP** [comment]
@rickhumphries Not quite done yet but here is what I have so far.  https://www.youtube.com/watch?v=pLKe6s8qdH4

**Comment by rickhumphries** [comment]
Yeeeh, that's quality @heyMP. Where does it pick the icon up from? Just the favicon of the site?

**Comment by btopro** [comment]
Rolled in from the video @heyMP shot. Still needs some clean up to support groupings, usability of moving them around and syncing across systems in a course network. Creating related issues for that and closing this out
