### ISSUE TITLE
How to create a new course (breif video)

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/elmsln#574]
Short, low production screencast on creating a course space: http://screencast.com/t/E2Xt561SnMq 
Feel free to share with anyone who just needs a quick guide. Didn't spend too much time with this since I was told the process will be changing, but my team found it helpful.

**Comment by btopro** [comment]
nice! Yeah we've cleaned up the UI since the version you have bc of feedback (less options since they werent all supposed to be there, self refreshing status page of whats going on, etc).

**Comment by michael-collins** [comment]
@btopro I know that you've talked about increasing the priority of the new CIS interface. When do you think we'll get to it?

**Comment by btopro** [comment]
Look at what the current priority for things that are CIS

**Comment by btopro** [comment]
I'll shoot this and some other tutorial videos as soon as my cable comes and we close in on 0.2.0. this will be the last issue to close out and release 0.2.0

**Comment by btopro** [comment]
Thank you for putting this together katrina; I'm spinning up a vagrant instance now; if all goes well then I'll be starting to record a series of tutorials surrounding this and topics of the studio which just reached a new level of stabilization / UX workflow refinement

**Comment by btopro** [comment]
need to close to get in notes; this is being shot after we have a 0.2.0
