### ISSUE TITLE
add support for vagrant-cachier

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#579]
This can drastically increase the speed at which vagrant spins up the routine since it's able to cache repos that will always return the same response. Things like yum install php-5.6 will and should always get the same response.  Credit to @AndrewGearhart for finding. Testing now to get results of before and after cache but looks very promising.

**Comment by btopro** [comment]
vagrant up  9.15s user 3.63s system 0% cpu 43:01.99 total

initial up.

**Comment by btopro** [comment]
vagrant up  9.81s user 4.26s system 0% cpu 39:44.09 total

cut 3 minutes off build out but I'm also on a 1Gig backbone so that's significant; 7.6% gain on my environment

**Comment by heyMP** [comment]
I'm assuming that you have to first install the plugin correct?

`vagrant plugin install vagrant-cachier`

**Comment by btopro** [comment]
To use it yeah, not required

Wp8
________________________________

**Comment by btopro** [comment]
@AndrewGearhart can you add the command to get it to our docs section for vagrant
