### ISSUE TITLE
A&A 121 ONLY: minor edit on widgets

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#582]
Hi Bryan,

I'm hoping you can help me save a good deal of cumulative time by making a simple edit to the dummy text on the widgets for Words of Wisdom, Case Study, and Design Tool. The current dummy text highlights the word "Specimen" as the linked text. In 98% of the cases, I manually change this to "video)" 
Obviously, that's without the quotes, but less obviously, there's a close-parentheses at the end. 

If you could make this change to the dummy texts in those three widgets, it'd be a huge help!

Many thanks,
Peter

**Comment by btopro** [comment]
Give it a shot now!

**Comment by pja12** [comment]
Works great!

I’d say you really gotta cut it out and get a life, but I like the company!



Cheers,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
The future goes to those sleeplessly building it tonight :)
