### ISSUE TITLE
Courses feature - bookmarking

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#589]
I thought it might be quite a nice feature for a user to be able to bookmark a page so they can come back to it later. This could be done from the Table of Contents by clicking a bookmark icon as well as the page itself:
![image](https://cloud.githubusercontent.com/assets/4973810/12852350/699cc816-cc26-11e5-9aac-9c921c5ff7cc.png)

**Comment by btopro** [comment]
https://www.drupal.org/project/flag could provide this pretty easily but the issue could be that this might be something people want to do across the network(s) and also potentially of non-content. Would we want to allow bookmarking any / everything or JUST content in an outline?

**Comment by rickhumphries** [comment]
Yeh, bookmarking content pages is probably the most obvious place to start. There's definitely a place for bookmarking other things across the network like favourite discussions but you'd probably class that differently.

What type of non-content were you thinking about? Like 'following' other students? (thinking more about your studio tool there)

**Comment by btopro** [comment]
I was thinking discussions and what not; still nodes but def a different kind of content. Your right though, bookmark / star / fav / whatever could have different connotations I was just thinking like "Well what if I wanted to see 'my bookmarks'" would this call of just content, just discussions, just ____ based on where you are or would you see everything and where it was, etc

**Comment by mmilutinovic1313** [comment]
Gonna start working on this one today -- do we want to add this to just content "page" nodes as a field at first? I can get that working, do a PR, and then we can reevaluate from there what other content we would want to bookmark.

**Comment by btopro** [comment]
@anything NOT a section in the courses system

**Comment by mmilutinovic1313** [comment]
Doing an initial PR as I got it working. Let me know if I need to remove files at all. I'm reexporting the feature, but I think I need to add the module to custom modules as flag was not global <-(this is the part I'm not 100% I need to do tho)

**Comment by mmilutinovic1313** [comment]
Doing an initial PR as I got it working. Is there any specific folder I should put the `flag` module in. I see it is not currently in courses / mooc, but appears in other profiles we run.

**Update:** So I had some suspicious Feature changes in my VM and am resetting the VM to do a fresh Features export.

**Comment by btopro** [comment]
booo ok, looking forward to seeing this

**Comment by mmilutinovic1313** [comment]
If the mooc_flag feature gets added in, this allows for the bookmarking possibilities to occur. We can experiment with additional settings in the flag module and possibly work on styling to make this look more like the rest of the system instead of a bland button at the bottom of each node.

**Comment by mmilutinovic1313** [comment]
Hey, @rickhumphries is the style of bookmarks that you screenshotted on your elms install?

**Comment by rickhumphries** [comment]
hey @mmilutinovic1313  - sorry, no it's not. I just photoshopped that in to illustrate. Glad it looks realistic though! :)

**Comment by mmilutinovic1313** [comment]
No worries -- I'll play around with the style once we get this issue merged in :)

**Comment by mmilutinovic1313** [comment]
Good to go - making issue to figure out styling for bookmarks

**Comment by mmilutinovic1313** [comment]
@btopro style-wise, would this be accomplished in one of our .tpl files? Or should I make a feature request on d.o. for a bookmark logo instead of the little button they have now?

**Comment by btopro** [comment]
there's probably a font icon for this https://design.google.com/icons/

as far as where, dono, probably on the interface to mean "bookmark"

my guess is in template.php and or page.tpl of foundation_access

**Comment by mmilutinovic1313** [comment]
I just realized we have another issue for this: #1736

**Comment by btopro** [comment]
closing dup

**Comment by mmilutinovic1313** [comment]
In hindsight, I think Web components Module will help solve this real quick - attempting to solve today

**Comment by mmilutinovic1313** [comment]
Related issue: Flag Defaults didn't have a selector outside of the edit form. Will fix in this PR too

**Comment by mmilutinovic1313** [comment]
The last PR should fix both these problems. We have Material icons in now and we will add more material tooltips at a later date.

**Comment by btopro** [comment]
nice work mark! not enabled by default or accounted for in GUI perfectly but still v good if enabled
