### ISSUE TITLE
Provide option for san-serif class application in wysiwyg

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#591]
Hi Bryan,
Bullets are wonky (again?). See attached image...
They work with 'normal' formatting and go awry when I use one of the 'heading' formats. I also tried hard and soft returns but it doesn't seem to have an effect (they wonk either way).
When you have time...
~Peter
![bullets2](https://cloud.githubusercontent.com/assets/16839175/12891447/064807ee-ce56-11e5-9007-2de1ffa0032f.jpg)

**Comment by btopro** [comment]
Headings and Bulleted lists would be in conflict from accessibility and formatting (as seen above). What's the thing your trying to achieve with the headings? Maybe we can make a class that can apply to things to accomplish the same thing visually

**Comment by pja12** [comment]
Hi Bryan,



I see what you mean. I was trying to use the sans-serif typeface for the 
list so it’d stand out as its own thing rather than as a part of the text 
flow.  This is not a big deal, but it’d be a nice feature to have on hand.



Cheers,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
@pja12 changing the title on this to add a class to support making things san serif; do you foresee wanting it to retain the color treatment as well? I could see people wanting this as an option as well.

**Comment by pja12** [comment]
Hi Bryan,



I can see the color being important to someone. I don’t use that feature 
because we’ve already set it in the heading styles. But color coding is 
useful sometimes. Maybe the problem lies in using the heading styles. 
Perhaps the solution is to include a sans-serif body style that people can 
then modify with the second pulldown (bold, color, etc.)

As long as the paragraph styles (body, headings) both work with the bullet 
lists, we’d be fine.

(I hope this all makes sense)

Cheers,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University
