### ISSUE TITLE
Robot to test upgrades to elmsln across the distros

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#60]
Make a jenkins CI job that has authority to create branches on a fork of elmsln. install the system in a clean-environment (digital ocean or whatever) via the automated installer; then apply upgrades to all drupal modules, one at a time, to the latest versions. If nothing bad happens, commit that module to the fork. Once all projects have been upgrade tested, issue a PR for only the modules that appear to have caused no problems.

This will generate a travis job, which will rebuild our demo server automatically. Hook up a dev server that gets rebuilt and automatically upgraded as well. Send me an email about it when its all done while I make coffee, then if I blink my eyes at the email, notice the acceptance of the new code and automatically run #59 and add the updated versions to the stack and then do a PR against the project again for these changes.

ok some of this is a joke... almost all of it isn't.

**Comment by greg-1-anderson** [comment]
This is a very fine idea.  See: [github.bash](https://github.com/pantheon-systems/downstream-updater/blob/master/scripts/github.bash).  Beware of bugs in the scripts in the referenced repository; it is still in development, and not yet completely functional.

n.b. The [hub](https://github.com/github/hub) tool is excellent, but does not do all of the operations in that script. It is my ambition to enhance hub, but in the short term I am using curl to the REST API directly.

**Comment by jalama** [comment]
This is definitely doable.  With Drush the foundation for it will be the drush pm-updatestatus (ups) and pm-updatecode (upc) commands.  With Drupdates we use the ups/upc pattern because ups will return a list of modules that have updates in a JSON format, as opposed to pm-update which only returns plain text table format to stdout (useless from an automation perspective).  

From there you can parse the results and push you commits which Travis can, obviously, pick up and run tests on.  The pushing only the projects that pass testing will be the heavy lifting part of this.  I don't know enough about Travis's API to know about getting test results from it but if Github can do it so can you. ;)

With Drupdates, it's set up allow you to split each project (module/theme/core) update in it's own commit and push to a new feature branch. Currently, Drupdates doesn't support seperating each commit in to it's own branch and then create a PR if the tests come back with a thumbs up.  It's not that a feature couldn't be added but it's just not in there now.

**Comment by greg-1-anderson** [comment]
You might save time if, on your first pass, you updated all of the modules together. If all of your tests pass in this configuration, then you don't need to take the time to do them one-by-one.

The danger to doing modules individually is that sometimes, an update to module A might be dependent upon an update to a dependent module B. This is a little rare, but sometimes there are closely-bound sets of modules (e.g. media) that may experience this more frequently. See drush site-upgrade for some code that orders updates (similar to what you want, but different, as sup is for major upgrades).

**Comment by btopro** [comment]
@greg-1-anderson thank you for the suggestion / code example, very helpful framing; especially in the area of doing all of them first then individual ones if there's a fail as additional options. @jalama ty for the branch per module / theme / core idea, I like notion as well cause then it could suggest many different branches to merge in.

We currently have a self-upgrading deployment that gets pinged by travis when a build passes, which stamps a small file saying it's safe to upgrade. A job on the server notices this, pulls the system over-top of itself and then applies our upgrade routines to itself. Even with weak testing we've only had 1 instance of generating an issue on that system in the months since doing it. (https://drupal.psu.edu/library/ is a hack in the elmsln architecture to this setup so it's actually a self-upgrading deployment as a test of the concept).

Thinking maybe if I align with the security release window (or weekly or something) and do...
- server has a github account that has access to a fork of elmsln
- weekly it rebases, then does the drush upgrade commands (one at a time) creating a new branch for each; commits a small tweak to our standard travis file so that it pings QA instead of our demo w/ response
- pushes all these branches to its fork on github at the same time
- any travis ping-backs from this repo suggesting it was successful, it would merge into its own branch on the server
- once all individual branches pass travis, it would issue a commit against the merging of all successful branches; if this passes travis then it would issue a PR against the main project for me to review
- I merge it in after some manual testing, the process repeats next time and the rebase takes care of the fact that the code may or may not have been acceptable to merge in.

**Comment by jalama** [comment]
Personally, I'm not a huge fan of multiple branches from an expediency perspective but if you're running this weekly you are not likely have have a ton of updates, especially if you focus on security updates, so that may not even be an issue.

**Comment by btopro** [comment]
local bash script approach
- [ ] git checkout -b automated-upgrade-{stamp}
- [ ] cd into locations of drush projects
- [ ] ls into a for loop, drush dl each
- [ ] git add -A && git commit -m "upgraded {project name}" && git push origin automated-upgrade-{stamp}
- [ ] grep for .patch files being modified / removed (collect array)
- [ ] alert user of possible overwritten patches to check
- [ ] generate link for user to paste into browser to take them to where the travis results will be generated per commit

This will automate all the downloading of crap, generate some acceptable 'will it blend' style testing and make it so we can alert someone to manually verify if they get all green lights on the job

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln-developer/blob/master/developer_scripts/upgrade-contrib.sh check 'er out
