### ISSUE TITLE
Document how to install H5P libraries

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#628]
Need something like https://www.drupal.org/node/2243891
Kind of a bug (from an automation standpoint) but it's definitely a usability enhancement since right now a developer / admin member would need to upload the H5P latest library, who we're trying to eliminate reliance on, completely.

**Comment by btopro** [comment]
current version to include / download at run-time -- https://h5p.org/sites/default/files/all-h5p-libraries-20160108.h5p

https://h5p.org/update-all-content-types page that has all the items and description of what / where to down the file from.

**Comment by rickhumphries** [comment]
I agree, and from what ive seen, this is definitely on the H5P roadmap/already..https://h5p.org/roadmap (number 5)

Looks like its already been done for WordPress so hopefully Drupal isn't far behind :)

**Comment by btopro** [comment]
Nice, thanks for pointing this out, I'll drop this back in priority and change it to documenting the way to add it in till they support automated.

**Comment by btopro** [comment]
duplication
