### ISSUE TITLE
Course Outline Renaming Issue - Not all Changes Saving

### ISSUE THREAD

**Issue by rjf227** [elmsln/elmsln#637]
In the Course Outliner, I've renamed some elements of a course outline about 3 times and - though the changes appear in the outline they don't remain when I go back to the course to edit.  I don't know what's going on with that.  Some changed, but 2 won't.  They just keep reverting to "Lesson 2" and "Lesson 3."  What's going on?  I would attribute it to user error, but several that I've renamed did save and change.

**Comment by rjf227** [comment]
<img width="1336" alt="screen shot 2016-02-16 at 9 10 08 pm" src="https://cloud.githubusercontent.com/assets/15616843/13097722/b8462f38-d4f1-11e5-8212-9989c887985b.png">

I also just noticed this warning...not sure what that is about or if it's connected.

**Comment by btopro** [comment]
most likely related to #223 if you edit the content directly the title will stick, I need to really fix the issue referenced as it can produce this at times. We may also want to visit just disabling book title override by the default because now with our new UI and design patterns it's not nearly the issue it once was.

**Comment by btopro** [comment]
@rjf227 for now if you edit the page and scroll to the bottom where it says book outline I have a feeling you'll see your title reflected there (you may have to click override title).

**Comment by rjf227** [comment]
This worked. Thanks you.

**Comment by btopro** [comment]
we'll still need to fix it but you've got a bandaid solution for now :)

**Comment by btopro** [comment]
@rjf227 I fixed the underlying issue, I'll close this out though it won't be reflected in your install for another day or so
