### ISSUE TITLE
How to highlight text in WYSIWYG editor

### ISSUE THREAD

**Issue by rjf227** [elmsln/elmsln#638]
It seems like the only way I can highlight text is to do so in the html code and not in the text editor.  Am I missing something?  I can find ways to change the text color but not to highlight, which I often do to let faculty know where there are missing components of their lessons.  `<span style="background-color: #FFFF00">Is there a way to highlight text without coding `it????``</span>

Blech - I can't do it here either.

**Comment by btopro** [comment]
@heyMP we should review the defaults for textbook. Noticing a few things that come up over and over again in (now all 3 of our) deployments.
- Disabling the HTML tag limiter (we have it on by default, I disable it constantly)
- Reviewing the buttons available out of the box; Highlight is popular but we should review the others

**Comment by rjf227** [comment]
I'm highlighting like a maniac now.  Thanks!  I don't know if you want me to close this or not.  It's resolved in my instance.

**Comment by btopro** [comment]
we'll review and close out once we decide on what other buttons to add in; started with 10 a year ago and have been slowly adding them back in to make people justify w/ good use-cases instead of just having the (overwhelming) kitchen sink of options that is the default

**Comment by btopro** [comment]
https://www.drupal.org/project/wysiwyg_filter looks promising, especially since they just added support for developers to whitelist/blacklist with greater specificity then the UI allows (which it allows a lot already) -- https://www.drupal.org/node/1783966 @heyMP this might help us get all those SVG properties to pass through correctly as well since I know that was an issue at one time.

**Comment by btopro** [comment]
filter can come down the road if needed; for right now the filter has been disabled for admin level users as we end up doing this most of the time anyway
