### ISSUE TITLE
Non linear, adaptive and self-selecting course structures

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#640]
```
things
  that
   are
    structure
    like
  this
   can
    be
  a bit
  dated you think?
```

This isn't the way people learn with the modern web, but it sure is how we structure courses. What we really want in many situations (if only we had the technology) is allow learners to create the structure they wanted to focus on. This flexibility would kind of be seen in tech communities as the big-core vs small core approach to developing things. Does it do EVERYTHING and prescribe exactly how to think? Or does it provide a lot of different options, tells you you need to do a very small % and then the rest is up to you.

This aligns well with

Initial prototype
- Create a content type called topic (module, unit, or whatever, let's all get over these words people)
- Fields include tag, image representation, required status, XAPI statement mapping (optional) and other meta data
- can still be manipulated as a hierarchy from the staff side but these are smaller structures, starting w. a tpoic type
- we render the homepage as a grid of topics, highlighting ones they need to do vs ones they have done / could do.
- instructor sets the number required to meet the objectives of the course (so maybe 28/40 for example)

students largely self select hat they want to focus on and everyone personalizes their own pathway

```
|----------|  |----------|  |----------|  |----------|
| topic x  |  | topic x  |  | topic x  |  | topic x  | 
|----------|  |----------|  |----------|  |----------|  

|----------|  |----------|  |----------|  |----------|  
| topic x  |  | topic x  |  | topic x  |  | topic x  | 
|----------|  |----------|  |----------|  |----------|  

|----------|  |----------|  |----------|  |----------|  
| topic x  |  | topic x  |  | topic x  |  | topic x  | 
|----------|  |----------|  |----------|  |----------|  
```

**Comment by btopro** [comment]
i know @pja12 and @michael-collins have both asked for something like this so please let me know if I'm capturing the idea correctly in textual form. It's something we want to start doing and I'm not sure is that difficult to do, just want to talk it through and make sure we've got all the right things to quantify

**Comment by kat-wehr** [comment]
Yes! I was asking about the possibility of this too - as we advance in online learning "choose your own adventure" type structures (non-structures?) will become more popular.

**Comment by btopro** [comment]
@kat-wehr we can discuss briefly today w/ white-board cause collins wants it too and I think I have a solution that's pretty easy as the stepping stone towards it

**Comment by pja12** [comment]
Count me in on brainstorming this wherever and whenever!

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by michael-collins** [comment]
@btopro Posting from our last meeting. <img width="897" alt="components-chart" src="https://cloud.githubusercontent.com/assets/1085304/13164220/7a98158e-d681-11e5-80f6-beb07f17d817.png">

**Comment by michael-collins** [comment]
This is how the Course Builder tool handles topic dependencies for customizing learning pathways: https://www.youtube.com/watch?v=j5zswydEuOc

**Comment by btopro** [comment]
Where is your bar chart of skill stacking?

**Comment by michael-collins** [comment]
<img width="1162" alt="mastery-example" src="https://cloud.githubusercontent.com/assets/1085304/13179764/5a298766-d6f3-11e5-84c8-dc60a3ea36c4.png">

**Comment by btopro** [comment]
(working through this, not final at all)
right now from a data perspective, I think we have 2 things required:
- How many paths required to unlock me
- What do I point to next

We use the outline designer as usual which provides us with some general ordering. Nested modules can then be used to help with the question of "what do I point to" because it limits it to "what CAN I point to" naturally. So in the visual below. Orientation would be the first thing, nothing pointing to it, it points to Module 1,2 and 3. Orientation says "Ok, you need to finish 2 of the things I point to".

##Module 1,2,3 each are on "level 1"
- each says orientation required to unlock me
- all point to M4 and M5
##Module 4,5 are "level 2"
- each says 2 things required to move here
- both point to M6
##Module 6 is "level 3"
- one of them required to unlock me
- points to M7,M8,M9
##Module 7,8,9 are "level 4"
- M6 required to unlock us
- all point to M10
##Module 10 is "level 5"
- only 1 required to unlock me
- points to nothing

![branching path](https://cloud.githubusercontent.com/assets/329735/13450399/ec6edf64-e002-11e5-991e-df9c63385f23.jpeg)

**Comment by btopro** [comment]
The grid example that I started with then has this: 42 modules in the course. One to start, 40 along the way, one to say congratulations.
Orientation (assumed, this could be 1 page of instruction saying "hey welcome to the course" so lets not get hung up here)
- Orientation (M1) points to 40 other modules 
- First so nothing required to unlock (setting is 0)

All the 40 modules
- Point to Congratulations Modules (M42)
- Orientation required to unlock

Congratulations module
- Points to nothing (so end of the course)
- 34 pathways required to unlock

This creates the completely free-form, non-linear grid. Within that structure you could have smaller branching path adventures that I think would be able to handle the same logic.

**Comment by btopro** [comment]
worth a look http://adaptivemap.ma.psu.edu/

**Comment by btopro** [comment]
http://jtauber.github.io/articles/css-hexagon.html hexagon

**Comment by btopro** [comment]
![2016-11-04_17-05-46](https://cloud.githubusercontent.com/assets/329735/20022429/efb63e3a-a2b0-11e6-9753-b67fa9d9a9b3.png)

**Comment by btopro** [comment]
moving to crazy bucket of fun so it can be continued in HAXcms queue as it would allow for non-linear structures based on the theme that implemented the content outline in a different way
