### ISSUE TITLE
Create Integrations page in API admin section

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#644]
Take the admin here when they first login. This can provide tutorials and quick links (as well as verification they are setup correctly) for all the parts of ELMSLN that can't be automated. For example:
- Google Apps / YouTube API integration (link off to section of elmsemdia to complete)
- H5P installation (link to part of elmsmedia page as well as link of where to download file)
- Piwik (write to a job file to set this globally)
- Learning Locker / xAPI / tincan settings  (write to a job file to set this globally)
- Box integration
- LDAP
- OAuth2 integration  (originally: #1348)

**Comment by mmilutinovic1313** [comment]
Flickr API Integration: Useful for voice commands etc.

Requires an API key

**Comment by btopro** [comment]
relate these two issues please after making a new one

**Comment by btopro** [comment]
start of one and it links off to media for h5p and youtube for now

**Comment by btopro** [comment]
this probably would work better in the proposed API system

**Comment by btopro** [comment]
merging w/ #1473
