### ISSUE TITLE
Discussion Board Text Entry 

### ISSUE THREAD

**Issue by rjf227** [elmsln/elmsln#647]
I can't seem to post discussion forum instructions or reply to discussion posts.  This is what I see when I click "reply":
![screen shot 2016-02-17 at 12 01 42 pm](https://cloud.githubusercontent.com/assets/15616843/13117542/5b16a00e-d56e-11e5-8647-0796b157c50c.png)

Here's what I see when I click the "+Add" button:
![screen shot 2016-02-17 at 12 03 29 pm](https://cloud.githubusercontent.com/assets/15616843/13117574/8842a7f8-d56e-11e5-93e3-cee272f272fe.png)

Also, is there a way to include this discussion in the outline so students can navigate through?

**Comment by btopro** [comment]
this was fixed in more recent versions and I could show you how we're integrating this and other things directly into the content but discussions is still early in development. we want to shatter the forumn model not just replicate it
