### ISSUE TITLE
Fake Webservice Calls in Simple Test

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#649]
So we need to figure out a way to fake Webservice calls in Simple Test. I found a note a while back from @btopro referencing this need, and I would like to assign @IBGregory to research this, since he is working in simpletest currently. If you can find links as to the best way to do this, post them below and we can begin working on enabling this, thus making testing and everyone's lives easier!

-Mark

**Comment by btopro** [comment]
Here's one idea at least https://groups.drupal.org/node/22332

**Comment by mmilutinovic1313** [comment]
I'm looking at and playing with the code that is at that link that you posted back in February. I was wondering if you could highlight some of the parameters you would like to see in getting this faking webservice calls working. Would this module / tool be placed in a testing directory that would hook into simpletest? Or would we put this module in module folders that we were currently testing. I'm curious on the scope of this so that I can understand what we are looking to build in this issue :)

**Comment by btopro** [comment]
Simpletest so modules can fake response data

**Comment by mmilutinovic1313** [comment]
Calls against itself via simpletest. We need something live for cis_connector...probably.

**Comment by btopro** [comment]
not concerned about this aspect
