### ISSUE TITLE
ELMS Learning Network Blockchain

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#654]
Create an ELMS Learning Network Blockchain. Some really great ideas discussed here: http://otlw.co/

another related project idea -- ELMS Infinite #968

**Comment by btopro** [comment]
... this can be an offline conversation. I'm not nearly as impressed with the concept as you are and we don't have powerful enough computers to sit and mine student grades for money ;)

**Comment by michael-collins** [comment]
Mining is how bitcoins work to show proof of work, but, that is a fluctuating concept with blockchain. At it's core, Blockchain is just a trusted and mathematically fair ledger. In a year or two, it should be much easier to create one.

The characteristics are: 

- has a protocol
- cryptographic hash functions SHA256 - (Creates fingerprint)
- distributed
- proof of work (helps establish consensus on the network to establish trust)

This could impact online learning in the future if there was a learning blockchain:

- Prove earned credentials and badging across institutions or without institutions
- Authenticate course or learning path enrollments
- Establish grades across a huge metric instead of the narrow course specific metrics 
- Funding models based on merit and impact that cannot be currently measured
- Probably tons of other opportunities

**Comment by btopro** [comment]
:+1: for "in a year or two" ;)

**Comment by btopro** [comment]
https://ethereum.org/ looks like best bet. We could align with an education provider blockchain that's doing the credentialing and allow for distributed, personalized backpacks for badges and what not

**Comment by btopro** [comment]
this is out of scope for the time being
