### ISSUE TITLE
Scaling issue for images via shortcodes

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#655]
I've noticed that images don't scale properly when resizing responsively...

This is normal size:
![image](https://cloud.githubusercontent.com/assets/4973810/13172760/b0561cf0-d6f1-11e5-8153-3b3b579ddd89.png)

The mobile view:
![image](https://cloud.githubusercontent.com/assets/4973810/13172777/cec4a8dc-d6f1-11e5-8cf2-d0f31e2d3034.png)

**Comment by btopro** [comment]
can you post the code too plz

**Comment by rickhumphries** [comment]
Shortcode I'm using is
[ciscode|rev=1|tool=elmsmedia|item=682|entity_type=node|render=display_mode|display_mode=image__left]
but happens for the other image view modes too

**Comment by btopro** [comment]
figured, just wanted to know the structure so @heyMP can dig in

**Comment by heyMP** [comment]
@rickhumphries I think I might have fixed that.  What commit/tag are you on?

**Comment by rickhumphries** [comment]
@heyMP hmmm good question - do you know the best way of finding out?

**Comment by btopro** [comment]
@heyMP --^ maybe we need an issue for adding something to the drupal status page that says what commit your on? If we have gitphp support under the hood, should be able to craft a way of accessing this (at least in CIS or something) so that people could report something like that

**Comment by rickhumphries** [comment]
Yeh that'd be useful @btopro ...I should be able to find out - just might have to do it later when I can dig into conversations with OB a bit further :)

**Comment by rickhumphries** [comment]
@heyMP just looked back and think we last updated core on 14th Jan...so that would make it 0.0.5 that we're on

**Comment by btopro** [comment]
waiting for travis to report on #664 right now but looks like this on ALL Drupal status pages after application which would help resolve issue reports like this that require a lot of back and forth.

![2016-02-23_13-55-58](https://cloud.githubusercontent.com/assets/329735/13262937/69b96076-da35-11e5-8806-554c00d4267f.png)

**Comment by btopro** [comment]
tested this, it would appear we fixed it in releases after 0.5.0 as when I played w/ some images they scaled correctly using the same style.
