### ISSUE TITLE
Difficult to get from "Media" to "Course"

### ISSUE THREAD

**Issue by rjf227** [elmsln/elmsln#658]
There is no intuitive, one-click way that I can see to get from the "Media" assets list back into the course one is editing.  Here's what's available on the screen:
![screen shot 2016-02-19 at 3 08 45 pm](https://cloud.githubusercontent.com/assets/15616843/13187732/ece9f078-d71a-11e5-894d-fd365290d086.png)
![screen shot 2016-02-19 at 3 08 57 pm](https://cloud.githubusercontent.com/assets/15616843/13187735/f0ad4c78-d71a-11e5-9700-78b8a817c6cb.png)

And when I click "Course List," it doesn't actually take me back to either a clickable link to go back to the service instances, the course outline or the page I was editing prior to going into "Media Assets."  It seems the only way I can get back to edit the course content is to re-enter the direct URL in the browser.

**Comment by btopro** [comment]
won't tag as course / media as this is basically the potential confusion of going from any service (course network) to any authority (media, comply, CIS, interact, inbox, people, etc) and back.

@rjf227 for now, if you are in a course in the URL (like /abc123) and you go to any other system with the /abc123 in it, clicking the "network" icon will show all the available things it can use.

**Comment by rickhumphries** [comment]
When I'm setting up courses I tend to have two browser windows open on two monitors. Media is open on one and Courses on the other so I can work in both at the same time. I understand what @rjf227 means though in that if you're working within one browser window you need to physically move to another authority to pick up shortcodes etc. 

I was on a site today and thought there might be a slick solution showcased in the way the left sidebar works on it (http://www.rome2rio.com/s/London/Berlin) 

If you click one of the options in the sidebar on the left, a new panel overlays it and there's almost a stacking of panels if you click further. It works pretty well.

This might be a way down the line and require the Material stuff that's being talked about, but it could be cool if you clicked Media and there was a way of a panel such as this appearing which displayed all the images/videos etc. linked to that course that live in the Media authority.

That way you can still get to these components and still work in your course. There could even then be a one click option which automatically inserts the shortcode where you want it.

This could even work in the same way for the services - especially thinking of Discuss, where it would bring out a panel of discussions that are linked to the page that you're on or something?

**Comment by btopro** [comment]
HAX resolves this... but we say that a lot

**Comment by btopro** [comment]
@rickhumphries see #480 and the video there from ages ago about how we were looking at doing some related discussions / etc

**Comment by rickhumphries** [comment]
Yeh looks good. #imvotingHAX. I just liked the overlaying sidebars as a way of doing things

**Comment by btopro** [comment]
Course context is now passed between systems so this should help clear this up a bit. We're also working on an in place media integration widget to eliminate the need to go there so some of this is training, some infrastructure, some usability. We're attacking all 3 :)
