### ISSUE TITLE
Unable to see image attribution

### ISSUE THREAD

**Issue by rjf227** [elmsln/elmsln#659]
I can't figure out a way to get image attribution/citation to appear on a content page.  For some reason, I see:
![screen shot 2016-02-19 at 3 19 23 pm](https://cloud.githubusercontent.com/assets/15616843/13187902/351e874a-d71c-11e5-913a-f46e98b7f454.png)

when I enter:

<p>[ciscode|rev=1|tool=elmsmedia|item=23|entity_type=node|render_display=display_mode|display_mode=image__lightboxed]
</p>
<p>[ciscode|rev=1|tool=elmsmedia|item=23|entity_type=node|render_display=display_mode|display_mode=image]
</p>
<p>
  <iframe align="middle" class="entity_iframe entity_iframe_node" frameborder="0" height="400" id="entity_iframe_node_23" name="Ethics" scrolling="no" src="https://media.eldig-elmsln.vmhost.psu.edu/entity_iframe/node/23" title="Dan B." width="100%">
  </iframe>
</p>

**Comment by btopro** [comment]
related which was fixed recently #656 though this is still an issue we need to investigate

**Comment by btopro** [comment]
verified, 656 fixes this. it'll be applied in the next release
