### ISSUE TITLE
support for letsencrypt

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#661]
http://letsencrypt.org is awesome and would allow us to (hopefully) automate certificate granting

**Comment by btopro** [comment]
initial support there, as this is a beta technology we won't debug further but it is there and should be automated

**Comment by bradallenfisher** [comment]
As of right now the main issue with self-signed certs are the domain name suffixes. 
```shell
The request message was malformed :: Name does not end in a public suffix
```

**Comment by btopro** [comment]
is it only blocked bc we end in .local?

**Comment by bradallenfisher** [comment]
Yeah.

**Comment by btopro** [comment]
so if we changed our VM to have different urls we could add this?

**Comment by btopro** [comment]
also I now realize we're having this conversation on the wrong thread

**Comment by bradallenfisher** [comment]
No this is the right thread the issue is with letsencrypt not allowing you to use a domain that is not a TLD. Once we get letsencrypt figured out it will squash the other issue entirely since once we get letsencrypt working we will have self signed cert for all domains

**Comment by btopro** [comment]
I don't think vagrant should have certs that are updated via letsencrypt though; is that satisfying anything different then the box including self-signed / local certs?

**Comment by bradallenfisher** [comment]
gotcha... 
moving back over to #936 

As far as letsencrypt cert bot... Getting that into prod wouldn't be too hard.

It would pick up all the domains create the config for each domain and stick the certs in the right place. That type of automation already exists and is pretty simple. 

Change a couple of things on https://www.exratione.com/2016/06/a-simple-setup-and-installation-script-for-lets-encrypt-ssl-certificates/ and you are good.
