### ISSUE TITLE
Visability settings for online.elmsln.local type urls

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#676]
Upon exploring my online course space this year I have noticed that I as a student can view all of the courses in a college by going to the online.elmsln.local address. I was thinking we could make this page only accessible to admins, or at least filter things out so that only courses that you are a member of can be seen by a student. This could help prevent students who shouldn't have access to certain courses from having access if a site was mistakenly made to be public.

**Comment by btopro** [comment]
well they don't have access to them. DM me the address your talking about. Do you mean in your real course you are taking in sciences or in vagrant?  If you mean your real course I agree it shouldn't display but it doesn't give you access unless you have it via being in the course.

#76 and eventually hiding the online site entirely will resolve this

**Comment by mmilutinovic1313** [comment]
Info sent in a DM
