### ISSUE TITLE
cis_tokens not on by default

### ISSUE THREAD

**Issue by proconnor15** [elmsln/elmsln#679]
The cis_tokens module is not on by default and should be since it is often used. @btopro

**Comment by btopro** [comment]
@proconnor15 this is the case for the MOOC distro; rest don't really have a use for this (yet, could but meh). There's 3 pieces to this commit.
- [ ] document how to use it #503 
- [ ] enable cis_tokens out of the box in MOOC distro (look for mooc.info) and add it to the section of the file that's related to mooc_ style projects
- [ ] drush recipe that will automatically enable it on all existing sites for those playing along
