### ISSUE TITLE
Performance delivery enhancements

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#680]
In order to enable elmsln_cdn out of the box, we'd need the following resolved:

- [ ] uncomment settings in shared_settings.php default set; if CDN not enabled well it does nothing
- [ ] support built in (and remote) CDN mappings in foundation_access
- [ ] lump jQuery CDN based loading into this
- [ ] If using CDN matting for FA, don't aggregate it
- [ ] create a symlink directory off of domains directory which points to the shared assets (modules / themes paths). May need to figure out how to support profiles via this but rest will "just work". Also could make a domain called cdn which mashes all distros together for performance sake (actually this makes the most sense as I say it)
- [ ] get Header add Access-Control-Allow-Origin "*" working for the cdn sub-domains
- [ ] figure out why FA JS breaks after aggregation via CDN but not local to page
- [ ] review the following below for implications of above
- [ ] look at adding support for https://rawgit.com/ if possible

#329
#247
#351
#349

**Comment by btopro** [comment]
after applying these locally I'm able to pull a 90 page speed score on MOOC, if we can get the icon flashing to go away via #593 and fix the cookie-less domain for static assets issue we could have something insanely fast after initial load anywhere

**Comment by mmilutinovic1313** [comment]
Rewriting these steps below so I can check them off: 

- [ ]  uncomment settings in shared_settings.php default set; if CDN not enabled well it does nothing
- [ ]  support built in (and remote) CDN mappings in foundation_access
- [ ]  lump jQuery CDN based loading into this
- [ ]  If using CDN matting for FA, don't aggregate it
- [ ]  create a symlink directory off of domains directory which points to the shared assets (modules / themes paths). May need to figure out how to support profiles via this but rest will "just work". Also could make a domain called cdn which mashes all distros together for performance sake (actually this makes the most sense as I say it)
- [ ]  get Header add Access-Control-Allow-Origin "*" working for the cdn sub-domains
- [ ]  figure out why FA JS breaks after aggregation via CDN but not local to page
- [ ]  review the following below for implications of above
- [ ]  look at adding support for https://rawgit.com/ if possible

**Comment by btopro** [comment]
considering this now a duplicate of #942 since a lot of work has been hashed out there that makes this irrelevant in most instances. We'll use a real CDN so why fake calls for minimal gains?
