### ISSUE TITLE
A&A121_gallery page

### ISSUE THREAD

**Issue by pja12** [elmsln/elmsln#681]
Hi Bryan, 

Two big changes for A&A121: 100 students rather than 20; and, we've moved to Canvas. I now can have students submit via Canvas and can bulk download their submissions. 

I'd like to have a gallery page with the following features:
1. A swipe left/right display that shows one-by-ones, with file names (minus extensions) as titles.  (bonus: each image randomly loads)
2. A four column gallery below that with a thumbnail and title.
3. Everything can bulk upload files to ELMS.

Sitting in a meeting, I sketched the diagram below that's both process and product. There's no fire on this, but I would like to see if we can get it done!
![gallerypage](https://cloud.githubusercontent.com/assets/16839175/13365813/3e3859f8-dca5-11e5-91e0-d2a36e33ff70.jpg)

**Comment by btopro** [comment]
interesting idea, not sure when this could get slotted in but like the concept; what are the images of so I have some context?

**Comment by pja12** [comment]
Hi Bryan,


Glad I’ve peaked your interest! The images themselves don’t really matter; 
it is intended to be interchangeable among assignments. So, for example, I 
have ten mini-exercises, each of which asks students to submit one image 
(typically a photo of the work they’ve done via Canvas– a sketch, a letter, 
whatever.



With 100 students, I wind up with 100 images. Canvas has a great grading 
function, plus a bulk downloader for all content associated with the 
assignment.  The students can’t see one another’s submissions, though, so 
the idea of the gallery allows them to browse it. By making the swipey top 
thing (is there an official name for this sort of thing?) load randomly, 
they’ll not see the same first 10 images before they tire; seeing the big 
gallery below allows them to pick and choose the ones that seem interesting.



For some assignments like the ‘love letter’ the thumbnail will just show a 
tiny letter, but for ones where the students have found or designed 
something, that object will be visible. This is largely a further 
development of the gallery feature you kindly put into the studio part of 
ELMS, but with two main changes: bulk uploading by me; and no student 
submission directly to ELMS. My hunch is that this will be more broadly 
applicable as other faculty move to Canvas and take advantage of its great 
grading system. (Also, since Canvas is so much more integrated than Angel, 
they’ll likely need to do grading via Canvas to make it all work for 
gradesheets).



Hope that helps a bit…

~Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
need someone to do a static mock up and also think through how we'd store this information (medium) / prototype (easy)

**Comment by btopro** [comment]
@pja12 been working on different presentation styles for images / image galleries ( https://github.com/elmsln/elmsln/issues/1112#issuecomment-251165229 ). We've also recently added support for bulk media uploads. Now, I don't know if either will be able to handle 100+ items created but if you had a flash drive of work I could throw it into my test bed and see if it'll fly / see if it's something you'd be looking for. I have concerns about scale (and sustainability, 100 per semester * n number of faculty also doing this would be HUGE storage needs) but I'm open to trying it out and see what happens if you are.

**Comment by pja12** [comment]
Thanks, Bryan. I can come over sometime and give a try with you. For me at 
least, the storage needs are minimal as it’d be images, not huge files.



BTW, I was editing big chunks on ELMS today and it ran sweet as butter, even 
previewing where items were going to go! Thanks a million for making all 
that work so smoothly.



One troublesome item while I have your attention:  When editing a page in 
ELMS, I sometimes get a sizable “space after” a line, esp. if I hit return 
to make a new line right after a video template. This matters because I like 
to put a little ”video runtime is 5 minutes” tag line after a video box, but 
it often winds up with an inch or two of white space between the new line 
and the video box. Is there some way for me to adjust the leading on the 
lines, or perhaps some way to clear whatever wacky formatting is happening?



Cheers,

Peter



Peter Aeschbacher

Associate Professor of Landscape Architecture and Architecture

H. Campbell and Eleanor R. Stuckeman School of Architecture and Landscape 
Architecture

Hamer Center for Community Design

The Pennsylvania State University

**Comment by btopro** [comment]
file concern is longevity issue (like how we deal w/ 100,000 student images for something like this) but it's a concern for eventually, not right now :).

drop by some time and we'll take a look. there's also some capabilities I haven't enabled / visualized yet where we can automatically calculate and present the length of videos. So if you have a way you're envisioning putting that tag line we could just make the videos self aware and write it automatically.

I'd also like to show you our next design iteration which fully implements MaterializeCSS / get your feedback -- http://materializecss.com

Shoot me an email off this thread about when you could swing by some time to talk. Thanks @pja12

**Comment by btopro** [comment]
@pja12 also as per spacing. if you hold control while hitting enter it'll put a single line break (<br>) instead of a full paragraph break (<p></p>). This should result in less white space usage
