### ISSUE TITLE
Voice command support

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#684]
https://www.talater.com/annyang/ is a wrapper for simplifying usage of the web audio API. While still not official WC3 it is under consideration and currently implemented in Chrome out of the box with support from FireFox and Opera possible after enabling. This API is incredibly simple to use and very effective. Here's a demo using Web Audio API directly to do some simple conversation with a website -- https://cdn.rawgit.com/elmsln/AI/master/index.html

over https it only requires 1 authorization (http is every time for security), meaning once you authorize the domain once you'll be able to talk to it. We would make this an optional thing for sure (it doesn't need to AND SHOULDN'T just be listening to you at all times) but for staff / faculty / admins some obvious use cases:
- dictation to fill out fields like content areas
- action commands: Next page, Previous Page, Scroll down, etc
- complex commands: "Go back to CIS", "New studio course that allows for branching paths and has 10 assignments", "Open outline designer", "Add a page here"
- Accessibility option for reading the content which could live next to speedreader (I implemented this prototype in the past but it's too bloated, WA API is built into the browser -- https://www.drupal.org/project/mespeak)
- https://www.drupal.org/project/voicecommander has an implementation of annyang (found it via that) for admin functions like clear caches but we could borrow the idea for things like "devel output", etc.
- anything else leave it below plz

**Comment by mmilutinovic1313** [comment]
So there is a really cool thing in here with the search in FlickerAPI. If we could write something like the FlickerAPI for ELMSLN that could search for keywords / anything, we could do some awesome stuff with this on a mere querying standpoint. I'm going to be messing around with this a lot in the next few weeks and see if I can get some cool stuff hooked up!

**Comment by btopro** [comment]
@mmilutinovic1313 can you review https://www.drupal.org/project/voicecommander and play with it to see what it does and how? I don't care about the "voice commands for admin menus" that it seems to be providing; what I care about is more so how we could fork this to be more useful for our purposes and do so in a way that could be for generically adding voice command support to drupal

**Comment by mmilutinovic1313** [comment]
Works for me! I'll go check that out today

**Comment by mmilutinovic1313** [comment]
So I've got this installed. I'm trying to find a list of commands it uses - because it isn't clear as to what a valid command looks like. It is also possible that it may not be able to run on vagrant, but I'll keep testing and searching for a list of commands. This also uses Anyang (the software you showed me before) so I believe it will work

**Comment by btopro** [comment]
It should be able to work on vagrant. dig in and reverse engineer so you can learn anyang and how it's using it (assuming that project works). We will not adopt voicecommander but potentially anyang / the ideas behind voicecommander

**Comment by mmilutinovic1313** [comment]
Sounds good - I'm on it!

**Comment by mmilutinovic1313** [comment]
I've been exploring Anyang and how it works and I am now in the process of building a demo that we can integrate into elms. Voicecommander was still giving me some issues, so this approach should hopefully work better. My goal for this demo is to display multilingual functionalities so that we can accommodate voice functions to a wide audience. Hope to be able to show you the prototype by the end of this week or next week. Let me know if there are any features you might like in the voice command integration demo

**Comment by btopro** [comment]
excellent!

Maybe "edit page" or something just as a simple opening edit mode among the other things expressed

**Comment by mmilutinovic1313** [comment]
I'm having @proconnor15 help work on this too - he is interested in some backend tasks

**Comment by btopro** [comment]
Proposed modules to produce:
annyang -- library implementation only, doesn't nothing on its own (The Right Way)

Proposed permissions
- can use voice commands
* Use menu permissions to determine what path based go to statements are valid

Proposed admin settings
Mode
- always on; impractical and a data privacy nightmare but fun for tech demos none-the-less
- provide button

Proposed commands:
Go to: path (might be node 25 meaning node/25 or front page or the outline designer)
Go to system: name
Go to course: name
Operations: edit, save, etc

Proposed API
Hook for adding new commands in
- phrase using the annyang syntax
- function to trigger when criteria met
- access callback (whether to use node / menu access permissions or if its a global command)
- file to include

**Comment by btopro** [comment]
Started to fill these up as issues in the voicecommander thread cause there's no reason not to just build on top of this great foundation -- https://www.drupal.org/project/issues/voicecommander

**Comment by mmilutinovic1313** [comment]
I like this approach. Do we still create the annyang module (to enable the library) as a separate task?

**Comment by btopro** [comment]
nah you know what, let's try and effectively fork / improve this project via patches (that's what your supposed to do anyway) but let's fundamnetally change the way it gets rolled out which I think many of the issues I've posed and what we talk about here does. So we morph the project into what we're talking about while still having the code base (which is very well written).

Biggest change in my mind is taking what they have and hollowing it out a bit so that it's a lot more API-ish. It would also be nice to have configurable modes which they currently don't support (though they do support configurable key phrase, right now it's 'drupal' by default but we could make it leafy or whatever)

**Comment by mmilutinovic1313** [comment]
That sounds good to me. Do you mind if I work on this too on the side of the Angular stuff and Apereo application? API building sounds like a cool thing to learn about!

**Comment by btopro** [comment]
Focus on Angular and the Apereo thing, I'll tee this one up and start w/ the refactor progression and then you can jump in on extending / increasing flexibility / documenting / modifying the API base, how's that sound?

**Comment by mmilutinovic1313** [comment]
Sure that works too! Let's meet at some point next week (if you've got time) to talk more about Apereo and I'll work on more Angular today.

**Comment by btopro** [comment]
sounds good

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=2qOt5rbHI44 current state

**Comment by michael-collins** [comment]
@mmilutinovic1313 @btopro Nice work!

**Comment by btopro** [comment]
We need to visualize this somehow but this works... omg it works and works really well across the domains :) I'm about to roll it on production now
