### ISSUE TITLE
ELMSLN installation on localhost

### ISSUE THREAD

**Issue by scottholmes** [elmsln/elmsln#685]
I am researching approaches to creating some on-line courses although I am not associated with any institutions.  ELMSLN looks interesting and I would like to set up an instance on my development box.  The installation scripts that come with a github download are heavily aimed at a fully networked server, not particularly applicable to my situation.  What I would like to be able to do is create a Drupal instance in localhost, then install the ELMSLN modules.

**Comment by btopro** [comment]
Cool, while developed by members of institutions this isn't exclusive to use-cases in edu. Is there a reason you want to install Drupal? The system sets up Drupal and installs everything needed, and can do so in a localhost environment (running one right now) though it sets up a VM in order to do this. This is definitely the recommended way of operating. The repo comes with a VagrantFile which can be used to automatically set up everything needed to get up and running. Detailed directions on how to do that can be found here: http://docs.elmsln.org/en/latest/development/Vagrant-Step-by-Step-setup/

We've also got copy and paste install support on platforms like digitalocean.com which are extremely easy to click and request a server to test things out. I create dozens a day just for testing and then destroy, only paying 10-15 cents for the day at most because of how flexible their billing is.

**Comment by scottholmes** [comment]
I was ignorant of Vagrant until I met elmsln, but will need to check this out.  I was drawn to elmsln precisely because it is a Drupal project.  I have several localhost sites on my development box and a couple on production servers so I'm use to creating them starting with an empty drupal site.  I'm off to my "day-job" now but will check out the Vagrant-Step-by-Step-setup at my earliest available moment.  Thanks for the tip.

**Comment by btopro** [comment]
np. It is drupal and you can engage with it like it's drupal (site building, adding new modules from d.o., the whole thing) but it's setup more like an install profile deployment framework. So it is Drupal and the install profiles can all be setup individually but for the full effect it's best setup as a whole. http://docs.elmsln.org/en/latest/INSTALL/ has some copy and paste style installers for playing but vagrant definitely the easiest. Let us know if you have any questions, I'll close this out for now.

**Comment by jaysharma** [comment]
Hi Bryan, am a novice to virtualbox, vagrant, but not to Drupal. The docs at the specified link pop up the 'Page does not exist statement. Is there any way you would be able to guide me here. I understand this may be out of scope, but I would really want to learn and contribute.

Any help from you is really appreciated.
Kind Regards,
Jay

![pdne error](https://cloud.githubusercontent.com/assets/984329/13773215/2ec87738-eabe-11e5-84e7-fd35ba0da52f.png)

**Comment by btopro** [comment]
@jaysharma hmmm weirdnes with RTD site. Try this -- http://elmsln.readthedocs.org/en/latest/

**Comment by Blancdememoire** [comment]
Hi Bryan. Should I put the one line of code for digital ocean in their console or in my terminal ? I'll try again but the instructions I tried did not work I think because I have either done wrong, there centos system and interfaced are not the same anymore as when you posted. Do you recommend not installing elmsln on one's own server space and only installing it on a digital ocean drop for client site or can client elmsln install be self hosted using alternc ?

**Comment by btopro** [comment]
@Blancdememoire digital ocean though you can use any host that give you root / sudo access. It's recommended that you put it on its own system as this isn't a typical drupal install but a full stack. There's several different examples here http://elmsln.readthedocs.io/en/latest/INSTALL/

**Comment by SuperCognitif** [comment]
@btopro I have succeded so far but I got lost at 3.27 in the video after copy pasting the ip adresses where there is the insert. Terminal doesn't allow me to type anymore and I don't know if what you type would work for my setup. Can you help Bryan ? Perhaps what do you type and why could elucidate.

**Comment by michael-collins** [comment]
@SuperCognitif Which video? Can you post a link? You may just be struggling with Vim commands.

**Comment by SuperCognitif** [comment]
@michael-collins 

Hi Michael, 

This video :
https://drupal.psu.edu/blog/post/install-elmsln-digital-ocean-one-line
Yes it could simply be my struggling. Thank you for your willingness to help ! 

The client wants his site called futuruniversity. I would like to put a coming soon page right after I get it to work but now get this result after I added a domain name. 

I know I'm almost there.

**Comment by michael-collins** [comment]
Okay. I'm assuming you hi the "i" key to insert, and then were able to paste? After, hit ctrl+C on the mac to exist insert mode. Then type "!wq" and enter to write and quit the file. If it doesn't let you write, then you needed to edit the file with sudo or root. 

Here is a list of Vim commands: http://www.radford.edu/~mhtay/CPSC120/VIM_Editor_Commands.htm

**Comment by michael-collins** [comment]
Also, to your question about a home page, this is essentially a series of Drupal sites that communicate with each other. You have full Drupal admin access to modify (and break) each part of the system if you choose. Just hit the tilda key when you are logged in.

**Comment by SuperCognitif** [comment]
@michael-collins Michael, this processs is frustrating. I exited terminal. tried running the one line again and got the answer nothing to do stuff in there after because I did that well first time. I can't really copy paste the ip adresses associated with the services as required then anywhere unless I can take it from some place. I don't know where. Can you can show me ? If I do that and then exit the insert mode, simply typing that !wq prompt will get it all working for me up to login or there is more I should do ?  Basically, I need to know what to do after that to finish the install. I think I'll be good to go after.

**Comment by SuperCognitif** [comment]
This is more questions about other things if you want to answer them. Is there a page or free online course where I can learn much using the terminal and commands to deal with such servers as digital ocean in relation to spined programs so I can come to do lots of good work for client and so I don't have to keep asking you questions ? If there is a web page listing all open source or non open source program that someone can run on such servers I got to know. I think this elmsln is going to be so great I would like to install and developp one for myself to offer online courses about french. What do I have to do locally to be able to run more than one install ? Thank you for your attention.

**Comment by btopro** [comment]
http://mac.appstorm.net/how-to/utilities-how-to/how-to-use-terminal-the-basics/ looks 1/2 decent

**Comment by SuperCognitif** [comment]
I have found this info about open source apps that can be spinned on the clouds for clients if that is of interest to anyone. .

**Comment by SuperCognitif** [comment]
Oh I see this elmsln in my vagrant manager now.

**Comment by SuperCognitif** [comment]
Is there a file I can access to copy paste again the ip adresses linked to services like in the video at some point for the one line install ? I have closed my terminal and lost what got returned programmatically.

**Comment by btopro** [comment]
For vagrant they never change and the documentation has them all listed. For a service like digital ocean just look to what's in the vagrant one and then replace the IP with the IP address of the digital ocean server.

Wp8
________________________________

**Comment by SuperCognitif** [comment]
@michael-collins 

Now I get this : http://www.futuruniversity.com/ 
It is written I should manipulate files on the left. 
Is it really what I should do ? I started over and did what you suggested. Maybe just a question of time. 
Not so confident about doing this for fear of messing things up.

**Comment by btopro** [comment]
http://online.futuruniversity.com/ is where the site would want to load but DNS needs a wildcard so that any sub domain shows up there. The generic apache message is fine at the top level domain as we don't occupy that w/ the application when its installed

**Comment by SuperCognitif** [comment]
@btopro @michael-collins   I will try adding that wildcard dns fix but I'm really getting frustrated and since my client wants a site running soon, I'd be willing to pay someone to get this working for me or to start the spin from scratch. Can any of you do this ?

**Comment by btopro** [comment]
I'm not sure I understand the nature of what your having issue with and this isn't an appropriate forum to ask for paid support for working with DNS entires. I'm also a bit concerned as to how much your client expects or if the job is merely to install our architecture, which is not finished.

**Comment by SuperCognitif** [comment]
@btopro Bryan, he just wants the infrastructure up so I can take care of configuring the rest for him. i know it's not the right place but I'll delete what doesn't belong here. I am saying I would like someone to fix the install with or without dns trouble shooting or someone to get a site running for me by starting over from scrach. I could connect with you with teamviewer if you want ?

**Comment by SuperCognitif** [comment]
@btopro if it isn't finished is it good enough to start a site with for a university in development ? Also, Can you set it up for me so I make him try it ?  Don't know where to reach you so I write here.

**Comment by btopro** [comment]
@bradallenfisher should be reaching out to you

**Comment by SuperCognitif** [comment]
@bradallenfisher I want your help please.
