### ISSUE TITLE
Courses/CIS Sync if Course Section has special characters

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#689]
I'm just migrating a course over from our old system which doesn't seem to be syncing properly with the CIS. It's not able to sync the roster or update the welcome page with content. In fact, when I'm on the welcome page for that section and click edit, it says this...
![image](https://cloud.githubusercontent.com/assets/4973810/13435582/ec1ec34c-dfd2-11e5-9d67-8b703d080a50.png)

What I suspect might be the cause is that it has a course ID/access string with brackets in? Maybe? Is that what #557 was about?

**Comment by btopro** [comment]
hmm... its possible; we haven't done any sanitizing on the section ID info tho, just on the course name itself. migrated from what old system and is the name the same in both systems (course name that is)?

**Comment by rickhumphries** [comment]
Ah right. All our courses are set up first in our current CRM then we put the course ID of this as the access string to sync them across. 

I just mentioned it was a 'migration' as the course has been setup for a couple of years with about 500 students enrolled so I can't really change the course ID

**Comment by btopro** [comment]
gotcha. can you DM me the section name and course name so I can try and replicate a lack of ability to sync / do the look up if there are weird characters

**Comment by rickhumphries** [comment]
Section name is DAC(L2-Equivalent)
Course name is just DA
Course title is Dispensing Assistant Course Level 2 Equivalent

**Comment by btopro** [comment]
@rickhumphries not able to reproduce in my local vagrant checkout of the latest build of the system. was able to use that name for the section without issue

**Comment by btopro** [comment]
can't replicate; reopen after upgrading if it still persists

**Comment by rickhumphries** [comment]
I'd like to reopen this. As of 0.6.0 this hasn't been resolved for the course in question. It might not be related to special characters
