### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#693]
We're working on some virtual environment stuff built in Unity3D. Think a DeusEx type first person experience (if you're into gaming) but having to work through learning scenarios. 

Recently, Unity3D have dropped support for its web player plugin, since all major browsers won't support it going forward and it looks like they'll be focussing on WebGL as the future standard for serving 3D games on the web. 

It looks like WebGL is still about a year away from being able to replicate the quality of a native/plugin experience but it reminds me of the old Flash vs HTML5 decisions that had to be made in the early days when Apple stopped supporting Flash...so I'm pretty sure I'd like to do this in WebGL. As well as enjoying a good open standard.

So assuming we go forward with a WebGL export from Unity3D, I wondered if anyone has come across instances of running WebGL objects in Drupal or if there's any modules out there? Id like to run through Drupal specifically so the interactions within it can be recorded as xAPI statements..so would need to have access to the user details of the student. Or could possibly host externally and do it through an LTI launch...? Not sure. 

Would be keen to hear how others might be tackling similar situations. @heyMP I hear you might be involved in something like this?

**Comment by btopro** [comment]
Work watching https://events.drupal.org/losangeles2015/sessions/drupal-3d-leveraging-webgl-and-x3dom-interactive-3d-content-visualization-0

**Comment by btopro** [comment]
Worth possibly forking / upgrading from https://www.drupal.org/project/unity3d_field

**Comment by heyMP** [comment]
@rickhumphries Yes!  absolutely!  I have a dedicated unity developer in our unit so this is perfect.  It sounds like you've looked into this more than I.  We might need to do an ELMS skype chat to get some ideas rolling.  This is excellent!

**Comment by rickhumphries** [comment]
@heyMP definitely. We've just had a demo video developed to showcase to interested parties what's possible. My plan was then to deliver the finished product through the web player using the Drupal module above @btopro mentioned. But yeh, that's not really recommended anymore.

Unity blog post explaining the decision is here http://blogs.unity3d.com/2015/10/08/unity-web-player-roadmap/

Would definitely be interested to hear what your Unity guy thinks about it. How do you deliver this type of thing to your students currently?

My feeling was that we might need to support a download/run through an application type thing until WebGL capabilities improve. I don't have a lot of experience of this though I'll admit.

**Comment by btopro** [comment]
mostly need exploration of available options / trial and error to see what's out there and how well it works.

**Comment by btopro** [comment]
@proconnor15 explore this module as a possible content type that'd be deployed in the interact / icor system. See if you can get a unity file from somewhere and upload and get it to work in interact. Probably related to #1122 so this could be a combo project you and @mmilutinovic1313  work on.

**Comment by mmilutinovic1313** [comment]
@proconnor15 is currently researching some cool stuff for this issue! Excited to see what he finds.

**Comment by heyMP** [comment]
This sounds like something that would be perfect for web components.  I did find a web component for rendering the unity web player: http://cesardeazevedo.github.io/unity-web-player/

What does the exported unity project look like for webgl?  Is it just a javascript file or a unity3d file?  Does it need pollyfills to run?

**Comment by btopro** [comment]
adding tag for webcomponents cause that makes a ton of sense

**Comment by proconnor15** [comment]
So right now, you can upload a .unity3d file and it will work only if you use safari or firefox. Google chrome does not support NPAPI which the Unity Web Player uses, so it won't play any unity files. I'm looking at how people have gotten around that

**Comment by btopro** [comment]
@proconnor15 good to note; if you find anything (which please explore) please report back; however, w/ how nuanced Unity is as a "type" of media to support then that's still fine.

**Comment by btopro** [comment]
Webcomponents exist to explore to do stuff like this

**Comment by mikemcdaid** [comment]
@rickhumphries did you manage to implement this? I have the same reqirement

**Comment by btopro** [comment]
https://github.com/cesardeazevedo/unity-web-player looks like it needs some work but might be at least something in this area to base off of. Right now (via HAX) we've got support for sketchfab and aframe-player but those aren't able to load unity outright. It appears that this webcomponent may be able to

**Comment by btopro** [comment]
lower priority but we should have a webcomponent in mind to do this as I think @heyMP and the sciences may want something like this native as well (at least as an option)

**Comment by rickhumphries** [comment]
@mikemcdaid we didn't take it any further in the end as other things became higher priority and we were waiting for both WebGL and webcomponents to mature a little.

@btopro I think the focus here should be on finding a webcomponent for WebGL rather than for the Unity web player. The last time I checked, the web player was being depreciated

**Comment by btopro** [comment]
aframe is the go-to for this or the newer google 3d stuff so not going to support unity
