### ISSUE TITLE
During Amazon spin up. PHP Warning:  Error while sending QUERY packet

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#697]
PHP Warning:  Error while sending QUERY packet. PID=18550 in /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/apdqc/apdqc.mysql.inc on line 860

Not sure what this is will investigate at some point...

**Comment by btopro** [comment]
not a blocker for 0.2.x; if it gets done before then cool we'll bump it back in once finished.

**Comment by btopro** [comment]
@bradallenfisher can you pick this off, should be easy I'm thinking so we can clean up the queue

**Comment by bradallenfisher** [comment]
now that the shared settings file is in there and apqdc config is present this is squashed. 
``` php
// Default backend controller to be apdqc
$conf['cache_default_class']    = 'APDQCache';
// THIS MUST BE SERVED FROM DB FOR STABILITY
$conf['cache_class_cache_cis_connector'] = 'APDQCache';
$conf['cache_class_cache_form'] = 'APDQCache';
```
