### ISSUE TITLE
H5P/Learning Locker Bridge

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#705]
Option for sending H5P statements to Learning Locker:
https://www.drupal.org/project/h5p_tincan_bridge

Extension of the (already supported I think...):
https://www.drupal.org/project/tincanapi

**Comment by btopro** [comment]
AAAAAAHHHHHH THAT"S AMAZING!

**Comment by btopro** [comment]
need to review code but I could probably slot that into at least being in the system (not hooked up but available) immediately

**Comment by rickhumphries** [comment]
:) :)

**Comment by btopro** [comment]
Haven't hooked it up because I want to actually see it working before we enable it by default but VERY promising just by looking through the code. Simple, and basically just routes the tincan settings over to H5P which should be able to send it along its way given the settings.

**Comment by heyMP** [comment]
Awesome. I'm going to be setting up an instance of learning locker very soon so this is perfect!

**Comment by heyMP** [comment]
Sorry about that.  I should have searched for it first.

**Comment by heyMP** [comment]
This is a just turn it on and put in the the Learning Locker creds and it just works.  Very cool!  Looking forward to diving in.

**Comment by btopro** [comment]
@heyMP I originally put it in media directly BUT I think if we move to a place where H5P actually loads in the content via display modes remote loading the h5p object (but actually rendering locally as we've talked about this approach potentially) then this code would actually have to run in the course content and NOT in the media system (in a frame)

**Comment by btopro** [comment]
for that reason I like your placement for it and dropped my original

**Comment by rickhumphries** [comment]
Awesome @heyMP . I don't suppose you could you send an example of the statement structure for the H5P quiz (question set) and something else like mark the words? It'd be nice to see if the statements just include everything that H5P throws out (which I hope it does).

**Comment by btopro** [comment]
enabled in my setup without settings and it didn't break anything. For that reason I'm comfortable enabling this and then coming up with ways of hooking it up / documenting LRS integration / setup in the future since right now Learning Locker needs setup manually / plugged into an existing one.

**Comment by btopro** [comment]
#306
