### ISSUE TITLE
remove all but core themes

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#706]
Historically we've supported these themes by having them included OOTB. We allow flexibility in our platform but it doesn't mean we need to include all this code that we don't need laying around unless people want it. This includes:
- adaptivetheme
- antonelli
- aurora
- corolla
- ember
- fontfolio
- omega
- respond
- rubik
- skeletontheme
- tao

And most importantly...
- chamfer!!

**Comment by btopro** [comment]
clean out other modules that we no longer support that are related to these:
- regions
- chamfer_defaults
- mooc theme compatibility modules
- tinynav
- thumbnav
- quojs
- context_var (just never use it, it's not bad)

**Comment by btopro** [comment]
more that have passed initial check
![image](https://cloud.githubusercontent.com/assets/329735/13757685/13ea51ec-e9fc-11e5-8800-45ed731c3a54.png)

**Comment by rickhumphries** [comment]
Is fitvids a CIS 1.x thing? Asking for a friend :)

**Comment by btopro** [comment]
if it is I'll move it over into there, your right it might be; I have another column for what to move directly into CIS 1.x as a profile and that's part of that list

**Comment by rickhumphries** [comment]
Awesome, cheers. Yeh I remember it being something to do with serving videos on course promotion page.

**Comment by btopro** [comment]
gutted a lot more things that we no longer / never have used. we'll do this periodically. .0.3.0 emphasis on refactoring (angular starting, file refactor, etc) will have things like this happen from time to time. anything we drop will be added to https://github.com/elmsln/trashbin and as much as possible we'll keep things backward compatible / these modules can always be added into the local shared config module directory of the deployment in question.

biggest thing with this merge is that we no longer formally support chamfer; my legacy theme. so this is inconvenient for me (by design) to start forcing us out of the trashbin and into the future.

**Comment by btopro** [comment]
another fun visual: I've deleted 1.1 million lines of code this year https://github.com/elmsln/elmsln/graphs/contributors?from=2016-01-01&to=2016-03-15&type=d
