### ISSUE TITLE
vagrant suggests 2 IP's for local hosts file

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#713]
==> default: If you are developing with this and don't have a valid domain yet you can copy the following into your local machine's /etc/hosts file:
==> default: # ELMSLN development
==> default: 10.0.2.15 10.0.18.55       lq.elmsln.local
==> default: 10.0.2.15 10.0.18.55       interact.elmsln.local
==> default: 10.0.2.15 10.0.18.55       courses.elmsln.local
==> default: 10.0.2.15 10.0.18.55       blog.elmsln.local
==> default: 10.0.2.15 10.0.18.55       online.elmsln.local
==> default: 10.0.2.15 10.0.18.55       comply.elmsln.local
==> default: 10.0.2.15 10.0.18.55       hub.elmsln.local
==> default: 10.0.2.15 10.0.18.55       inbox.elmsln.local
==> default: 10.0.2.15 10.0.18.55       grades.elmsln.local
==> default: 10.0.2.15 10.0.18.55       studio.elmsln.local
==> default: 10.0.2.15 10.0.18.55       innovate.elmsln.local
==> default: 10.0.2.15 10.0.18.55       media.elmsln.local
==> default: 10.0.2.15 10.0.18.55       discuss.elmsln.local
==> default: 10.0.2.15 10.0.18.55       people.elmsln.local
==> default: 
==> default: 10.0.2.15 10.0.18.55       data-lq.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-interact.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-courses.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-blog.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-online.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-comply.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-hub.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-inbox.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-grades.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-studio.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-innovate.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-media.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-discuss.elmsln.local
==> default: 10.0.2.15 10.0.18.55       data-people.elmsln.local

I can tell from the Vagrantfile that it should be 10.0.18.55, however for on-boarding this is slightly confusing.

**Comment by btopro** [comment]
it works either way but this happens on AWS install too since there's an internal and external IP:
`ip=$(hostname -I)` may neeed adjusted or only told to pull the last entry or something

**Comment by bradallenfisher** [comment]
this works as designed according to man hostname:

``` html
-i, --ip-address
Display the IP address(es) of the host. Note that this works only if the host name can be resolved. Avoid using this option; use hostname --all-ip-addresses instead.
-I, --all-ip-addresses
Display all network addresses of the host. This option enumerates all configured addresses on all network interfaces. The loopback interface and IPv6 link-local addresses are omitted. Contrary to option -i, this option does not depend on name resolution. Do not make any assumptions about the order of the output.
```

closing since it isn't broken and you can still copy and paste the output into your host's hosts file.
