### ISSUE TITLE
Interactive Breadcrumb runs off page with many menu items

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#715]
This is a bit of a niche one, and there are workarounds, but noticed that when there are many menu items at a particular level, they will run off the bottom of the page when opening the breadhcrumb:
![image](https://cloud.githubusercontent.com/assets/4973810/13574620/d5a9bffa-e47c-11e5-89f0-370d8f9a3fb6.png)
Would they need their own individual scroll bars? ala http://iominh.github.io/ng-scrollbars/

**Comment by btopro** [comment]
yikes

**Comment by btopro** [comment]
Now we account for ridiculously long navs like this. I've also styled the scroll bar (when browsers allow it) to look like the rest of the theme. Firefox doesn't support this property at this time but it looks fine on there

![2016-08-04_18-29-08](https://cloud.githubusercontent.com/assets/329735/17420548/5fe58b26-5a71-11e6-82b3-a311a9ca1edb.png)
