### ISSUE TITLE
Our Custom Developments

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#72]
I've been asked by @btopro to provide a brief run through of the things that we've changed/added to the system and where they currently live - most are in the CIS though with only H5P being added to Media:

### Content Types
* Course Module - provides all the information required for how a student can view their progress on a course. So a course might be made up of 10 modules - this content holds data such as ID, it's weighting (i.e. learning hours to complete), whether it's a core/optional module.
* Course Competency - course modules can be achieved by completing all the competencies associated with it. A competency can be marked as complete either manually by the, or through the recording of xAPI statements. So this content type allows you to set the xAPI activity URLs and verbs that are associated with it.

### People
* Account data - we've added fields to handle the import of student personal data from external database here
* Course progress - admin view which handles import of student course data from external database. Essentially a set of tables showing all course/module/competency data. This is used to inform a 'view progress' area that a student can access from the dashboard

### Open Badges
This is a space for admin to create a badge that will be awarded based on the recording of xAPI statements - and fill in all the other meta data for it, including associating it with a course and section. All badges that a user can achieve based on the course/section they're enrolled on will display in the 'achievements' area of the dashboard.

### Dashboard
This is the page that users go to when they log in. From here they can see the courses they're enrolled on, access these course spaces, view their progress so far on that course, view achievements, edit contact details, access their messages inbox.
* View progress - shows which modules have been achieved etc. along with some custom % calculations for progress and expected progress). Data mainly taken from People->Course Progress
* Edit contact details - allows the student to manually alter some of their account data, including password
* Achievements - shows the badges that a student has either earned or is able to earn. Badges that have not yet been earned are shown with a locked icon.
* Messaging - staff can send messages to students and tag the messages with the course it relates to. Students can currently only view messages, not send any.

### Search Students
This is mainly a tool to be used by admin and other staff members who want to quickly get at data associated with groups of students and perform some bulk operations.
I'm not sure whether this currently pulls in students from our external database or from 'People', but it allows you to build a table (hide/remove columns), filter students based on a number of parameters, and then either export this view as a CSV file, or select these students and send all of them a message, issue all of them a badge, or send an xAPI statement for each.

This is an admin tool for now, but once the system has developed a bit further and the bits regarding course roles and groups has been sorted it will be the area that external managers/mentors will use to quickly view student progress, see who is falling behind etc.

### H5P
Short one this! All we've done here is add the H5P module to Media. We set up interactive H5Ps here, then use the embed code to embed the activity in a course outline. We have code which listens for the xAPI statements generated from the activity, and turns this into a JSON format that can be accepted by our Learning Locker Learning Record Store.

## Learning Locker
Acts as an authority which records all xAPI statements.

Think that's about it!

**Comment by rickhumphries** [comment]
I would add that for the Achievements (Open Badges) and Messaging functionality that we've done could still do with some improvements in the design and ux, but the basic functionality is there

**Comment by btopro** [comment]
This is awesome. I'm sure there will need to be some ingestion of this functionality but it largely sounds like it fits with what @michael-collins and I have been talking about the needs to expand into.  The Course module / competency part *might* be a bit edge-casey for where much of higher education is historically (and guess what, most courses people take in HE have been around for years :)) but it's definitely the trajectory its heading in (or at least a solid option).

I'm curious about the "Account data" section you mention. Mike and I have talked about having this be kind of the user's global profile as they move between systems; that way this info could be pulled into scope local to the site they go to. What kind of fields did you add?

**Comment by rickhumphries** [comment]
Yeh the course module/competency stuff is a specific use case that fits in with the course progress data we hold in our current CRM so it kinda needed to be like that. There's a bit of tidying up required in some places as we've tried not to remove any fields/content types that were there previously in case we broke something! so we just added what we needed.

For Account data we've got:
## Main details
* Username
* Email address
* Password
* Status (blocked/active)
* Roles (may need to tweak the way this works based on your updates)

## Personal Details
* User Photo
* Full Name
* Employee Number

## Contact Details
* Address
* Phone Number

## Company Details
* Company Name
* Address
* Normal working hours

## Enrolment
* Enrolled Courses (checkbox list of course sections)

## Private Messages
* Enable private messages (checkbox)

We've also left in the fields that were there previously but weren't relevant (or some were, but we've added our own for some reason!) - these are things like First name, Last Name, Campus, Department, Email, Phone Number, Instant Messenger.

**Comment by rickhumphries** [comment]
Forgot to mention - we've also added a couple of fields in the 'Course' content type but can't remember exactly what these are. One thing for definite was 'Author Image' along with 'Author video' in the Visuals area of the promotional stuff. Just in case you wanted to have an image here instead of a video.

**Comment by btopro** [comment]
Gotcha. This is great stuff; will need to probably piece-meal it a bit but sounds like it could be a good foundation for us to build from. Re not removing fields: This is good but as part of the CIS futures discussion we'll basically be forking CIS into what we want it to be since the marketing side will go by the way-side / be extras.

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=_r1gJb6K9A0 video by @rickhumphries showing possibilities in this area

**Comment by btopro** [comment]
closing out since this spawned other discussions, more important that we can find this issue then it remaining open for the development team to freak out about high number of open issues :)
