### ISSUE TITLE
Export Course from Development - Import into Production

### ISSUE THREAD

**Issue by scottholmes** [elmsln/elmsln#720]
I'm still quite a ways from wanting to do this but I thought I'd ask in advance.  I'm making pretty good progress in developing on on-line course with elmsln, including H5P, but this is all local.  Are there any guidelines for publishing the course on a production version?  Drupal's import/export module could be used but it would of need be a service by service procedure, possibly requiring stitching by hand.  Thanks in advance.

**Comment by btopro** [comment]
Hi @scottholmes ; that's awesome! @rickhumphries might be able to speak to how their vendor migrated / manage production vs staging environments. There are some scripts built in to help with this process though (which we should expose through Leafy probably #504 ). https://github.com/elmsln/elmsln/blob/master/scripts/utilities/migration/pull-down.sh can be used to help with migrations. This assumes you have elmsln installed somewhere else (like a stage environment) and you want to pull onto it. The issue with going up from vagrant is that pull-down won't be able to talk to your localhost so we'd need `assimilate.sh` which still needs love -- https://github.com/elmsln/elmsln/blob/master/scripts/install/fractal/assimilate.sh

assimilate's goal is to be on an environment and connect to then inject elms on that host (basically pull-down in reverse) but the spidering database dumps and imports haven't been finished in it (it also currently assumes you connect with root or non tty credentials which is difficult to assume so it hasn't been finished yet).

Basic workflow
- Dump all dbs old system
- RSync all files from old to new
- Loop through and import all databases on new system
- drush cc all

**Comment by scottholmes** [comment]
I'm still chipping away at my project, trying to port a vagrant install to my production server and then to my public host.  For reasons that have little or nothing to do with elmsln I'm setting up the project in a location other than /var/www/elmsln.  After modifiing the .htaccess files, the settings.php  and the sites.php files my browsers (Chromium and Firefox) want to display the vagrant version.  Apache and hosts seem to be correct as then can find my hello world files (index.html) in all the domains.  I suspect it has something to do with the cis_connector.module  Links to /var/www/elmsln are hard coded therein.  Do you have any recommendations and/or caveats?  Is this can of worms just too big to pursue?

oneline.tg.local is changed to online.elmsln.local  

Thanks....

**Comment by btopro** [comment]
If you need to install outside of /var/www/elmsln then if it's possible to make a symlink pointing to where ever you put it back over to /var/www/elmsln. Your right, we do have things in place that *attempt* to not be hard coded off of /var/www/elmsln (and I'd accept stuff to make it not required to be there) but since we're going for largely push a button and server components as well as system components (and code to boot) are all loaded in and automatically managed it's kind of hard to not know where it lives. /var/www/elmsln/config/scripts/drush-create-site/config.cfg has a value hardcoded in the settings it reads off of relating to /var/www/elmsln but this assumes we've used it everywhere.

Can of worms indeed; why are you placing it in another directory?

**Comment by scottholmes** [comment]
> It has been my intention to publish an online course, or at least the
> outline/syllabus of a course, on a public server.  In this case my
> host is Bluehost.  I have two sites there now and neither exist in
> /var/www/.  They exist in /home/Username/public_html/Sitename 
>  Consequently I need to hack the elmsln code to port it to a public
> site.  Another reason I've taken this approach is that something in
> the installation scripts crashed my stacks, the mysql portion at
> least.  It was probably my fault but came from making multiple
> attempts at a straight install.  I've actually welcomed this as it
> requires me to look fairly deeply into the elmsln system.  
I can understand perfectly the preference to operate elmsln as a
turnkey system.  That is most definitely the most efficient and safest
approach.  But as I am not affiliated with any learning institution the
site I'm designing will not likely be used for actually taking the
classes.  My expectations are that it can serve as a demonstration of
both your system and my ability to design courses.
Unfortunately I have had little time of recent to spend on it but had
hopes of getting a portable instance ready by the middle of August when
I will have an entire week available to play with it.

**Comment by btopro** [comment]
in that case if you aren't making a bunch of courses or whatever you might want to just do database dumps of the course, make a new elmsln instance that's on a real server, make a course (that is then blank) and then import the database overtop of it for that 1 course.

**Comment by btopro** [comment]
scripts being worked on as part of #1454 make this a thing + paths have been abstracted as part of the #1465 work

**Comment by btopro** [comment]
previously related have been fixed so things exist to get close to this if @bradallenfisher would put our migrate scripts into the main repo (not sure they are currently outside of jenkins so asking here)

new related to make it even easier: #1593 & #1581
