### ISSUE TITLE
An essay assignment on a summary page for a lesson

### ISSUE THREAD

**Issue by scottholmes** [elmsln/elmsln#726]
I seem to be missing something fundamental, adding an assignment to write or upload an essay at the end of each lesson in a course.  I've been including H5P Summaries for each page of a lesson, and that works just fine.  What I want at the end of each lesson is to have the student either write out a summary essay or up load one.

**Comment by btopro** [comment]
The blog service can help provide this and the inline submissions widgets can help keep the UX in one place even though it's happening multiple.  The usability around setting this up isn't the best though as we're only using it in 1 course currently. Try setting up studio / blog and see if either of their capabilities meet your needs.

**Comment by scottholmes** [comment]
I have found what appears to be a satisfactory solution by using the "Create Assignment" option from the Drupal drop down menu in Open Studio.
