### ISSUE TITLE
Update Vagrant to use Rhel 7 Based OS and php-fpm

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#736]
I noticed while working on discuss that the vagrant version uses mod_php. Since elms is working on rhel7, I think we should move everything in infrastructure towards the latest if possible.

**Comment by btopro** [comment]
agreed; now that Vagrant just taps a 1-line installer and has VERY little changes beyond that (there's a cleanup.sh that's short) I agree. there's also #472  which is to get all the install scripts using php-fpm and at least write a tutorial for how to upgrade existing things to use fpm but your right, I want to be using fpm for everything

**Comment by btopro** [comment]
@bradallenfisher got a base-box we could point to in the vagrant file? the rest should be pretty easy to port at this point

**Comment by bradallenfisher** [comment]
Okay, so I hate to reopen this but is there any reason why this would make development difficult for people who are using centos 6 currently? 

For instance don't you guys spin this up to test things out before committing to your live env? What if you are testing something out where a new server module needs to be installed? Could that ever be a problem?

Just asking if not. We can re-close and leave well enough alone.

**Comment by btopro** [comment]
We've only had to do that 1x in the last several years; aside from that advanced setups like php-fpm switch over (as you know) we had to spin up a whole new server anyway. What we really need is #92 to resolve the issue your talking about (which also would make it so we wouldn't need to make dev boxes as we'd have a legit stage)
