### ISSUE TITLE
Discuss reference entity ref relationship

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#739]
If a thread is created and told to be for section ABC (for example) then section ABC should also be told that it uses this thread. This may seem silly, but the first reference provides permissions / lock down of visibility while the second provides display in results. If this thread CAN be used in ABC but ABC doesn't know that, then even though people have access to it (technically) they still won't see it in listings.

This also allows for the granularity of threads available in sections but not technically visible yet; which could then see them unlocked on a certain date if the reference is added. The first part is easy but this other suggestion is much more complex. This issue is for the easy case

**Comment by btopro** [comment]
https://www.drupal.org/project/cer might be useful and more abstract way of approaching this problem

**Comment by danielrose28** [comment]
The above project you referenced [cer](https://www.drupal.org/project/cer) definitely seems like it would be useful for the the first part, re:

> If a thread is created and told to be for section ABC (for example) then section ABC should also be told that it uses this thread. This may seem silly, but the first reference provides permissions / lock down of visibility while the second provides display in results. If this thread CAN be used in ABC but ABC doesn't know that, then even though people have access to it (technically) they still won't see it in listings.

Could you give an example of what would happen in the second part, re:

> This also allows for the granularity of threads available in sections but not technically visible yet; which could then see them unlocked on a certain date if the reference is added. The first part is easy but this other suggestion is much more complex.

I'm only assuming that this is what you meant by "first part" and "second part".

**Comment by btopro** [comment]
@danielrose28 sorry I missed this response somehow.

So discussion board is made called a Thread. A thread is basically just a placeholder which then immediately has a Post associated to it. So What CER would enable is you make a Thread and say that it is for Section ABC (that's adding it as group content). Then CER would make sure that the group (section) has a field populated with the same thing in reverse (Threads that this section uses).

So what this allows; Section ABC uses 10 threads/forums and so we can make a list that says "there will be 10 discussions" BUT we haven't actually enabled / published / etc all 10 threads. If we don't have the reverse we can't build a view of all the available forums because they won't technically have access to an unpublished node but we could safely show everything that's referenced by a section

**Comment by btopro** [comment]
CER is killing me, let's drop CER
