### ISSUE TITLE
Update the roster everytime the cron is ran on the course outline

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#748]
I've been asked to log an issue by OB as currently the roster sync isn't being updated when the cron is ran on the course outline. Does this happen by default in core? Thanks

**Comment by btopro** [comment]
If cron is run by drush it should do it everytime, if via URL method it could take an additional day. Perhaps having this be configurable would be best

Wp8
________________________________

**Comment by btopro** [comment]
resolved via back channel
