### ISSUE TITLE
Play with Features Builder

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#749]
Related to #745 . We've got 745 in the repo and its enabled out of the box but we need to document how to use it and have experience working with it. Basically it allows you to automatically produce features when normally people would have been going through and clicking items one at a time.

**Comment by btopro** [comment]
From talking to @proconnor15 his is a good starting point for #26 but will need san additional layer of automation via task runner to be useful to us outright. Drush plugin it provides is great though

**Comment by proconnor15** [comment]
https://www.drupal.org/node/2699875
Updating so that prefix is necessary.
