### ISSUE TITLE
Core 0.0.5 to 0.2 update - CIS 1.x homepage view/letter tabs

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#756]
Ran a core update today. All went well in general, just have a few queries which I'll outline in separate issues. First one,

The view/letter tabs have appeared on the homepage, what's the best way to hide this?

![image](https://cloud.githubusercontent.com/assets/4973810/13829437/ec7560b0-ebbe-11e5-9039-343907fcc91c.png)

**Comment by btopro** [comment]
View only shows up cause letter is there; what happens if you click letter?

**Comment by rickhumphries** [comment]
It directs to a welcome page:

![image](https://cloud.githubusercontent.com/assets/4973810/13830841/654094b2-ebc7-11e5-9aba-7e68e4dd66fd.png)

**Comment by rickhumphries** [comment]
And this is if I choose 'edit' 

![image](https://cloud.githubusercontent.com/assets/4973810/13830863/9539fe92-ebc7-11e5-96a7-937bb2e5eaae.png)

**Comment by btopro** [comment]
ahh... hmm... that has to do with cis service connection. let me think on the best way to stomp that out of 1.x

**Comment by btopro** [comment]
having private backchannel about this since it's ultra specific to rick's context (cis 1.x runs no where else anymore). We'll hash that out there
