### ISSUE TITLE
Core 0.0.5 to 0.2 update - saving course settings

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#757]
When saving a courses settings from here `/cis/course-settings` I get the following error:

![image](https://cloud.githubusercontent.com/assets/4973810/13829884/5470dbd4-ebc1-11e5-9678-55d6772f7f68.png)
 
This happens on choosing either sync or don't sync

**Comment by btopro** [comment]
were server level upgrades applied? there are 2 forms of upgrades

**Comment by btopro** [comment]
`0.2.1` will resolve this. reopen if that's not the case
