### ISSUE TITLE
Core 0.0.5 to 0.2 update - editing links in network list

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#758]
I also get the same error page described in #757 when adding a new link to the lms-less network flyout at `admin/config/user-interface/cis-lmsless-nav/add-link`

**Comment by btopro** [comment]
it bricks when going there or when saving a new item?

**Comment by rickhumphries** [comment]
just when saving a new item

**Comment by btopro** [comment]
ok, see if elmsln_api is enabled

**Comment by btopro** [comment]
if it isn't it's possible that the server level upgrade routine wasn't applied as it makes sure this would get added.

**Comment by rickhumphries** [comment]
No it's not. This is a list of 'ELMSLN modules' which are all not enabled:

![image](https://cloud.githubusercontent.com/assets/4973810/13830718/605f45ac-ebc6-11e5-9865-1e1338a9b417.png)

Do I need to update OB with new upgrade routine info?

**Comment by btopro** [comment]
that looks like the normal upgrade didn't run but it might be related to #523 . have them fire up `leafy` and run server level upgrades (well first verify that the admin dashboard that shows info about the drupal site doesn't show the version being out of sync)

**Comment by rickhumphries** [comment]
Yeh maybe, OK I'll ask them to do that. Is this the admin dashboard?...

![image](https://cloud.githubusercontent.com/assets/4973810/13830957/3a013bde-ebc8-11e5-85e0-428957330799.png)

**Comment by btopro** [comment]
yup, leafy definitely needs run w/ the admin thing so it can set a version for the "config" to know better what version the server is on. from the looks of your errors you've encountered we may need a 1-time fix kind of command (potentially if the upgrade doesn't do it) which would then get rolled into a 0.2.1 kind of release

**Comment by rickhumphries** [comment]
OK no probs. So they've run the system level updates described here (http://elmsln.readthedocs.org/en/latest/development/upgrades/How-do-I-run-upgrades/) but not the server level updates from `leafy`? 

Is there a bit in the docs about leafy that I can point them to? (did a search but couldn't find anything)

**Comment by btopro** [comment]
true and this is a good note to update that documentation to utilize leafy anyway

**Comment by btopro** [comment]
`0.2.1` will resolve this. reopen if that's not the case. updating documentation too now for the upgrade thing
