### ISSUE TITLE
Core 0.0.5 to 0.2 update - search and replace

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#759]
I watched the ELMSLN 0.2 full tour video and noticed the 'search and replace' feature, but I can't see this in our options:

![image](https://cloud.githubusercontent.com/assets/4973810/13830313/c60a6d9e-ebc3-11e5-9895-21bfbf1a73df.png)

The module which relates to this is on though (I think):

![image](https://cloud.githubusercontent.com/assets/4973810/13830353/0d255176-ebc4-11e5-8676-1356af0cde60.png)

**Comment by btopro** [comment]
try going to admin/content/book/sar and make sure that the path works; link just might be missing

**Comment by rickhumphries** [comment]
Hmm, no the path isn't working:

![image](https://cloud.githubusercontent.com/assets/4973810/13830803/11b98088-ebc7-11e5-8d54-9ed66be723ef.png)

**Comment by btopro** [comment]
`0.2.1` will resolve this. reopen if that's not the case
