### ISSUE TITLE
Authority: Inbox

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#76]
I'll leave it to @michael-collins to describe this as he's got the vision for it the best. Effectively an inbox / messaging / integrated tool that all other systems can push notifications to and that notifications can be queries from for integrating visually into the rest of the system.

**Comment by btopro** [comment]
@michael-collins we wrote this stuff on the white board the other day but I'd still like a bullet list of action items / core functionality for this authority.

**Comment by michael-collins** [comment]
@btopro working on this now.

**Comment by michael-collins** [comment]
# Description:
The core functionality of the inbox is to aggregate and provide visual notifications when something happens relevant to students and other users. Notifications are visually shown with a red badge in the CIS topbar.

# Notification types:

* Reminder
   * An assignment is due
   * Upcoming assessment (Quiz, Exam)
   * Upcoming live event (meeting, lecture, recitation)
   * Group discussion
* Message Notice
   * You received a direct message
   * Someone replied to your comment
   * Someone commented on your content
* Assessment notice
   * Grade and feedback from homework, quiz, test, etc.
* Warning
   * Did not submit something worth (% of your grade)
   * Instructors are supposed to do this manually
* Recommendation (Pedagogically-based)
   * Suggested date and time allotment for reading


# Notification fields:
* To (you, your group, everyone)
* From (instructor, calendar, University, etc.) system
* Date (Date alert was sent) system
* Related Course (optional) system
* Title
* Body
* Actions to take (url, direction, location for physical event, etc)
* Due Date (When this should be done)
* Specific time or range of dates/times (IE - Tuesday at 1pm, Today from 3pm to 4pm, Saturday to Monday)
* Response Date (You must respond to this message by some date) This sounds like due-date
* Context system
* Type
* Read/Unread

**Comment by rickhumphries** [comment]
This is excellent. Love the proposed functionality! :)

**Comment by michael-collins** [comment]
@btopro I added attachment to the fields list.

**Comment by btopro** [comment]
This should now spin up as an authority in the network as a blank slate, no new functionality in here at this time other then that it exists (which is cool) so we have something to build off of as we get into this area going forward. My thinking is that the more of these that we know we're going to make that at least have a foothold, the less upgrade routines we'll need between versions at an infrastructure level later on.

**Comment by michael-collins** [comment]
We should think about sending admin notices to admins via the inbox and creating Slack integration to keep a learning teach informed about what is going on. Currently, an admin gets an email when a course is built and ready, but this is clunky and it would make sense to send these notices via the inbox to all users that need to be aware of what is getting built. Optionally, not everyone on the team will have an account in ELMSLN, but you might want them to be aware of what is happening. This information can also get sent to slack if there is an instructional team that needs to be kept in the loop automatically.

Outside the scope of inbox, Slack could be used for a lot of things, including assignments, announcements, etc., depending on how the instructor wants to use the tool in a course, or for a learning team to develop courses.

**Comment by btopro** [comment]
oooo..... the PM side of things is very appealing, maybe optional integration w/ a slack channel (which wouldn't be hard to rig up, @mmilutinovic1313 write slack stuff; this also sounds like it could help w/ that side of things; maybe branch this off to another issue -- https://www.drupal.org/project/slack cause that's a cool feature for instructional design / faculty teams to be aware of the courses they are building. It's also NOT something that we need to be keeping in elmsln cause this is PM stuff. PM integration w/ larger ecosystems sounds like a better option.

**Comment by btopro** [comment]
Tagging @heyMP since we were talking about inbox yesterday as a group. A calendar system also came up, @michael-collins let me know if you think the notifications spec described above doesn't fully encompass the notion of a calendar. If every thing added is an event / has to have actionable data in some fashion then notifications that flow back to your inbox and that's where the notification live... makes sense.

If the calendar is something we think is super important and in need of being remixed that its its own system we can do that, I'm just not sure that it doesn't fall under a bucket of organizational tools. The Inbox and Calendar seem very closely aligned in my mind with the goal of keeping people organized and aware of what's going on in their courses.

Also, this is worth review: https://www.drupal.org/project/fullcalendar
which apparently is a lot of integration of http://fullcalendar.io/
Open Atrium also has this via https://www.drupal.org/project/oa_events and I'm not going to lie we probably should review https://www.drupal.org/project/openatrium if we're all about ecosystem widening.

**Comment by juststormy** [comment]
just a comment...make sure calendars/shedules are printable. i've had about 10 students asking for printable schedules, even if the faculty populated calendars of sorts. just saying. it's amazing how habits die hard.

**Comment by btopro** [comment]
@juststormy good call. I know a lot of people that still print calendars when they get the chance; just easier to post in non-digital locations :)

**Comment by btopro** [comment]
Place holder has been produced, now to start adding new threads for functionality to build out into it.
