### ISSUE TITLE
Core 0.0.5 to 0.2 update - edit/share/more icons

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#760]
This has only happened on one of our course sites, so it's a bit strange, but the edit/share/more icons only appear as squares:

![image](https://cloud.githubusercontent.com/assets/4973810/13830620/cbab77b4-ebc5-11e5-8aec-78d15ddef3f0.png)

**Comment by btopro** [comment]
did u try clearing caches on the site? Top left corner. there's css changes with regards to fonts here and we've seen this happen from time to time

**Comment by rickhumphries** [comment]
Yeh sorry, meant to say - cleared both the site and browser caches but they still remain

**Comment by btopro** [comment]
can u see if any css is getting blocked? may be related to the other issue post upgrade

**Comment by rickhumphries** [comment]
Yeh I can't really see...I don't _think_ there's any css blocked, but not 100% sure

![image](https://cloud.githubusercontent.com/assets/4973810/13831279/5bd51080-ebca-11e5-9973-c8c7f31d9629.png)

**Comment by btopro** [comment]
`0.2.1` will resolve this. reopen if that's not the case
