### ISSUE TITLE
Idea - Referencing/Remixing Book Outlines 

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#763]
We have quite a lot of courses that all share content between them. For example Course 1 might have 6 course components (let's call these A,B,C,D,E) and Course 2 might have 9 course components (F-N). Course 3 is made up of all of these components plus a couple of extras (O,P), which might be set up in a different order -> C, D, A, F, O, P, B...etc. 

I think a useful idea would be to have some form of shortcode for a book outline, which could then be referenced by another course. This reference might occur in Outline Designer, where you could 'add content' and choose to reference a book outline from a different course, which you could then arrange as a 'block' of content.

For the use case above, I'd create a 'Master Course' with a book outline for each of the components A-P. Then reference these from each of the courses. If any updates to the content need to be made, then this just needs to be done once in the master course, and the content would be updated in all the courses that reference it.

This could also allow for the creation of a 'Content Library', where instructors could set up blocks of content in the Master Course as a book outline. Being able to tag the book outlines (which I think we already kind of have support for) and filter them would help them search and remix others too.

**Comment by btopro** [comment]
related #368

**Comment by rickhumphries** [comment]
Haha, ah yeh - that's what I'm going on about :)

**Comment by btopro** [comment]
could you whiteboard / prototype this in some way (paper, invision app, etc)? We had this request a long time ago from CPP at wisconsin in a way more like what you just said. Central bank, draw from to assemble courses, content isn't editable.

The related thread eberly proposed was more of branches shared within the same course site.

Git book allows (theoretically) for syncing and forking in its roadmap.

I've had it on paper for awhile to do a "by reference" type, the point of which could be leeching content from elsewhere into the current page, then you could hit fork which (not git concept but still same idea) would take the type, promote it to a node with a body field, then do the web call it was doing but scrape the content from it into the body field to be modified. A trace field could let you know where it came from.

Now, that last idea was originally for single items (take assignment directions, dump here, kinda thing) but we have need of centralizing our syllabus and orientation materials in house (as does @kat-wehr in smeal). So potentially this could go one of two ways:

1. we actually make a different service / place for a centralized item to live like a learning object repo
2. we come up with a way of using the system where you make a course content site called like "ourstuff" or something which you don't put people in and it just ends up sitting there serving up / keeping content items in sync downstream.

When you want to add a remote one, you're able to add remote and fork, add and sync as well as if you want just the page or all pages below it (so the whole outline). Then it imports it (by reference being default case) into the current course space. This is all sounding oddly similar to #694 and the gitbook stuff we talked about recently eh @curiosity26 ?

To further complicate things, we're in talks with a group about them joining and they'd bring a full on learning object repository into elms (lor.elmsln.local). :)

So, let's all hash out the ideas here more and start to feel out if we're talking (potentially) a space where everything is in git behind the scenes and allows for easy cloning from this source into the course content that's used to run the courses.

**Comment by kat-wehr** [comment]
This is really great actually. I could see this working both ways, but for some reason the idea of a content gallery/repository organized by thoughtful tags and categories comes to mind first, with the ability to pull in content as is or in a version that can be edited. 

In my past life at another university we used the master course system which was helpful for cases where nothing was really changing. I could see the gallery/repo storing different types of searchable content (ie whole courses, pieces/modules of courses by concept/topic, even smaller pieces like quizzes/activities/discussions, etc (getting back to that whole pattern lab/atom/molecule/organism whatever categorization of content) and drilling down all the way to the boring stuff like syllabi, orientation materials, honor codes, info surveys, midsem evals, etc) which could be cool too. 

Or I could be going off on a completely different direction and maybe this comment is not helpful. :)

**Comment by btopro** [comment]
No, @kat-wehr I think you really just crystalized potential uses of this for me at least. That's a really good justification (pattern lab analogy) for having a dedicated, separate space. let's force @michael-collins to respond

**Comment by rickhumphries** [comment]
Yeh I'm in two minds between (1) Centralised learning object repo and (2) A course site which acts as a master. 

The idea I outlined initially was for (2) because I wanted to be mindful not to lose the authoring experience. It's great at the moment that you can actually see all the CSS styles that are being applied to the content when authoring and I feel that should be preserved in some way. However, (1) would allow for the type of thing @kat-wehr is talking about which would also be really powerful. Like Media but for content. 

If we had a centralised learning object repo that took #291 into consideration, then perhaps it would be possible to apply a style guide to a learning object you're working on so that the authoring experience still shines through? Then you might start work on a separate block of content, switch style guides and that reflects across. You could even just have the style guides set up in the learning object repository, then when you set up a new course it says 'what style guide do you want to use?' and it references those set up in the Learning Object Repo for this.

So talking that through to myself, maybe (1) has more long term legs? Might try and whiteboard something up if this is sounding plausible.

**Comment by kat-wehr** [comment]
@rickhumphries is on point with the style guides. @btopro I feel like this is all tying in with our conversation about being able to put content into a thing (gitbooks/pandoc) and get it out in a different thing based on the what the need is. Part of that out process could be applying the css. I can see all the content living the repo in its most basic form (with perhaps a generic style applied to help folks visualize what it would potentially look like after the "out" process). 

Perhaps a crude sketch of this process as I'm envisioning it would look like: Designer/faculty creates content for their course and is building and going through that process, then uploads said content to the repo where it gets stripped to a basic format, another user comes along and says "hey I like that but I need it to work in this, content gets spit out for the user who then takes it and applies their style and edits to it (ideally if they're popping it back into ELMS LN then they would just apply their style guide (like from a dropdown list or maybe even a wordpress-themes preview selector type thing) in the next step and do whatever minimal editing they see fit then).

**Comment by btopro** [comment]
@rickhumphries I'd learn towards authority / central system which would obviously have very similar authoring experience to Courses/MOOC; just scope different.

(just thinking out loud here) Another idea for @kat-wehr / @rickhumphries -- What if you authored in MOOC/Courses area and then could say "push this back to LOR" which would then lock it at a version, put it in version control (git/gitbook) behind the scenes and start to associate other metadata to it. Then from the course content you could say "keep in sync w/ master" or whatever language we use so that you get what @heyMP was talking about w/ content replication.

My views on this are clouded by knowledge that we may be getting an LOR ingested into the platform which we could build these things on top of and is already an authority (of sorts)

**Comment by rickhumphries** [comment]
@btopro So in that idea, the content would only live in the LOR as 'structure' (json/xml or whatever), and references to the other courses that use it? Then if 4 courses used that learning object, changing the content in any one of those 4 courses would update the structure in the LOR and thus the other 3 courses? Is that what you mean?

**Comment by btopro** [comment]
3 possible modes:
- fork (starting point, totally disconnected from LOR source)
- local (clones it locally, button to sync when / if instructor wants)
- remote (content is completely by reference)

In all 3 of these though the structure gets a little wonky to nicely integrate so might be more of content is local render, remote loaded but the structure could be moved (in some capacity) unless we locked the structure in local / remote modes

**Comment by btopro** [comment]
forgot to tag in issue: https://github.com/elmsln/elmsln/tree/i763

**Comment by btopro** [comment]
you can see the process by which this branch was produced here -- https://www.elmsln.org/blog/post/working-learning-objects

**Comment by btopro** [comment]
This is a starting point and not the end point, we need to hash out the scope of this further and how we'd integrate into our workflows but a lot of good ideas discussed here

**Comment by btopro** [comment]
More to discuss for sure but this is merged in and we have a lor.elmsln.local address that kicks out successfully. It's just a starting point but it's got some decent legs to it already
