### ISSUE TITLE
test item tagging across sections

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#764]
did a quick test the other day and this didn't seem to work though I may have a false negative because I was testing a weird part of mooc (container page) while in an outdated system. mostly a note so I don't forget to investigate further.

**Comment by btopro** [comment]
steps to reproduce:
- make two sections in the content service for a course
- make a branch of content
- edit a page and set the tag to be 'coolstuff'
- go to cis-find-tag/node/coolstuff it should resolve to the page you were on
- duplicate the outline, then associate the duplicate to the 2nd section
- switch sections from 1 to 2
- go to cis-find-tag/node/coolstuff it should resolve to a different node id

**Comment by danielrose28** [comment]
I can try to give this one a shot this weekend and let you know how it goes. I might ask a bunch of questions, which I'd usually feel bad about, but I can tell you'd be cool with it. I appreciate that very much. :+1:

**Comment by btopro** [comment]
Sounds good 😊 and don't worry we need your help!

Wp8
________________________________
