### ISSUE TITLE
3d threejs module investigation

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#768]
@heyMP have you seen this?
http://drupalshowandtell.com/talk/cam3d-three-module-demonstration

**Comment by juststormy** [comment]
ooooh! nice!



-----Original Message-----

**Comment by btopro** [comment]
https://www.drupal.org/sandbox/Shoseki/2062113

**Comment by btopro** [comment]
need someone to explore this, if it works, what it does, what we'd need to do in order to use it, etc.

**Comment by btopro** [comment]
@mmilutinovic1313 @proconnor15 similar to the other ones I assigned you both today; delegate who's going to explore it for viability, this would absolutely go in the interact system. If this appears viable, then it would relate to the other zip based things as far as needing a way of handling embedding elsewhere

**Comment by mmilutinovic1313** [comment]
Watched the video - I'll play with this some. Would we use this and WebGL? Or one or the other.

**Comment by btopro** [comment]
You tell me.:)

**Comment by btopro** [comment]
Webcomponents would make this silly. There are already some components that render 3D that we could implement, and if not, then we should be making those instead.
