### ISSUE TITLE
ELMSLN user group meeting

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#769]
Increasing, it seems that we are all heading in the same direction with our issue topics in the issue queue.  Specifically, I've seen topics that are of immediate interest to my group. Topics like:

- 3D labs in Drupal via Unity
- Embedding course outlines within a course outline
- H5P
- Learning Locker

## Proposal 
I'm proposing that we have a virtual meeting soon with the following agenda:
- Introductions
- Short show and tell.  Cool things that you've built in ELMSLN or that leverages ELMSLN.
- Everyone shares what ELMSLN initiatives they are most interested in perusing. (functionality, integrating new technology, etc.)
- Discuss the possibility of scheduling standing ELMSLN user group meetings

## Purpose
There purpose for this meeting is to ensure that we aren't simultaneous solving the same problems, discuss high level ELMSLN initiatives and potentially set direct for those initiatives, and meet each other :)

**Comment by btopro** [comment]
yes plz

**Comment by btopro** [comment]
Pick a day of the week, let's use appear.in til we blow up the 8 person limit and we can move to hangouts or something

**Comment by heyMP** [comment]
I'm tagging @rickhumphries in this because he's posts were the genesis of this proposal :)

Rick does this sound of interest to you?  Any day or time of day work best for you?

**Comment by rickhumphries** [comment]
@heyMP yeh I'd be up for this. Wednesdays tend to be best for me in general. I think any time between 3-4pm (10am-11am your time) would work because of the time difference?

**Comment by michael-collins** [comment]
My schedule is pretty tight this week. I have a faculty meeting until 11am EST on Wednesday. Any time on Thursday before 2:30pm EST is possible.

**Comment by rickhumphries** [comment]
Oh yeh, sorry. I can't do this week though :) I'm off for the rest of the week from tomorrow. But in general, those tend to be my most available times

**Comment by btopro** [comment]
how bout we try and see if future Wed 10-11AM Amercka time will work for everyone to start

**Comment by heyMP** [comment]
I created a PSU UCS calendar event as well as a public Google Calendar.

## ICS Event

https://calendar.google.com/calendar/ical/1ammtt6smd74le47k9ffqo0v1o%40group.calendar.google.com/public/basic.ics

## HTML Link

https://calendar.google.com/calendar/embed?src=1ammtt6smd74le47k9ffqo0v1o%40group.calendar.google.com&ctz=America/New_York

**Comment by heyMP** [comment]
Reminder: We have an ELMS Users Group meeting at 10am EST.  Here is the link to the hangout: https://plus.google.com/hangouts/_/calendar/bWdwMTQwQGdtYWlsLmNvbQ.4hclaif6tfgsq9uqovr71que6s?authuser=0

**Comment by rickhumphries** [comment]
Sorry I missed this @heyMP . I didn't realise we'd actually scheduled something (the google calendar didn't have an event listed). Are we looking to do this once a month?
