### ISSUE TITLE
Multiple ELMSLN versions with the same Courses

### ISSUE THREAD

**Issue by scottholmes** [elmsln/elmsln#771]
Struggle with an adequate title for this query, my first version of elmsln was created from the zip file.  I have a newer version made by cloning the github master repository.  As I've but a fair amount of work into creating a Course I would like to copy it into this newer cloned version of elmsln.  This is my first experience with vagrant, or any virtualbox developing for that matter.  With all my previous drupal prjects I would simply copy the database then synchronize the modules.  If I must recreate the course one page at a time then so be it, but I'd rather not.

**Comment by rickhumphries** [comment]
You should be able to follow the steps given in #236 .Go to your old course and get the node id for the top level of the book. Then go to /feeds_node_helper_export/{nid} .This will give you an xml package in the browser, which you'll be able to do 'save page as' to download as an xml file. 

In your newer course go to /import which will let you upload the xml file and your course should be copied over as a new book outline.

That's if the course only involves course materials. Not sure what to do if you've got assignments etc. set up in studio

**Comment by btopro** [comment]
@rickhumphries 's solution is a one-to-one content exporting. on the outline designer overview page `admin/content/book/` you'll see export which shortcuts to what Rick mentioned. This is just for the content.

Are you trying to migrate the whole ELMSLN setup from one location to another? There are some ways to do that. https://github.com/elmsln/elmsln/blob/master/scripts/utilities/migration/pull-down.sh can be used in Vagrant if you want to pull a system down from remote to local. Assimilate.sh still needs work which is for migrating the whole stack from one location to another.

This is still just drupal at the end of the day, it's just spread across more databases so if you import / export all of those you could do it that way. A `drush @elmsln sql-dump --result-file --y` will spider mysql dump all sites (though you'll need to import them still which is what we want to work on w/ assimilate in the future).

From a files perspective, /var/www/elmsln/config is where EVERYTHING "configuration" is written. All sites.php, settings.php, files directories, all of that stuff lives in there. As such, this directory can (theoretically) be picked up and moved from one deployment to another and largely will "JustWork"

**Comment by scottholmes** [comment]
So I picked up (tared) the config directory from my original install - the one with the course - and usd it to replace the one in my newer install.  It doesn't quite work:

PDOException: SQLSTATE[HY000] [1045] Access denied for user 'elmslndbo'@'localhost' (using password: YES) in lock_may_be_available() (line 167 of /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/lock.inc).

**Comment by btopro** [comment]
if you look at pulldown.sh (prev comment) it recreates the user accounts local to the location executing the call. Sorry, the copy and paste I really did mean theoretically. Things that need additional intervention:
- `config/scripts/drush-create-site/config.cfg is unique to each deployment`
- the mysql usernames would need to be created on the new box w/ matching passwords. each new site in elms has a unique U/P combo for security; these are local to the box they live on

**Comment by btopro** [comment]
I may be wrong but this seems like a dup of #720
