### ISSUE TITLE
Online Demo Issue

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#772]
The online demo (https://www.elmsln.org/demos) currently walks you through a Drupal installation, then is unable to go any further than the following step:

![image](https://cloud.githubusercontent.com/assets/4973810/13950531/79078036-f023-11e5-9ce9-e823abfc9b9d.png)

**Comment by btopro** [comment]
Ya I need to hit reset

Wp8
________________________________

**Comment by btopro** [comment]
fixed
