### ISSUE TITLE
Explore D3.js

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#773]
related to #640 We'd need something to provide this visualization. The experiment at the end of the conversation currently lead us to explore D3.js (https://d3js.org); a library I haven't looked into in years. Wow has it come a long way.  Just a few of the examples we could use if we supported it in core:
- Possible branching course path visual -- https://mohansun-canvas.herokuapp.com/content/training/
- alternate version: http://mbostock.github.io/d3/talk/20111018/tree.html
- molecule play space: http://orgo.stolarsky.com/

Many of the examples start to get into mapping, interactive charts and other json based, data driven visualizations. If we knew the way the data had to be structured we could produce a "d3 type" for use in interact which would be a content type like:
- file upload / datafeed for source data
- type of display

That's about it; stitch the two together as we continue to add support just based on reading through the examples and we could use our shortcode embed method to really make these things shine and be repurposable.

**Comment by btopro** [comment]
@curiosity26 could you post a link to that codepen your working on so we can have something possibly to react to / fork later on related to d3

**Comment by curiosity26** [comment]
@btopro http://codepen.io/acb222/pen/rewPBo/

**Comment by btopro** [comment]
come up with ideas as to how and where we could use this if its viable. Most likely these things would live in the interact system

**Comment by btopro** [comment]
after reviewing http://www.chartjs.org/ (+1 @curiosity26  for the link) I think we'll drop this and go for intergration of that instead. D3 is too unwieldy.

@proconnor15 checkout http://www.chartjs.org/ when you get a chance. it's WAY easier to work with then D3 (which the current example in your testbed uses)
