### ISSUE TITLE
Icon Libraries for CIS LMS-less Links

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#779]
Is there any documentation for what machine name to add in order to reference icons from the material/foundation icon libraries? Or on how to add your own? Thanks

![image](https://cloud.githubusercontent.com/assets/4973810/14059645/6c4b9494-f33f-11e5-8485-de3e6af76eac.png)

**Comment by heyMP** [comment]
Currently there is no way of adding your own font library without custom code. I'll create an issue for that.

Here are links to the two libraries you can currently use.

## Material Design Iconic Font
http://zavoloklom.github.io/material-design-iconic-font/icons.html

## Foundation Access Icons 
https://cdn.rawgit.com/elmsln/elmsln/master/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/icons/faccess-icons/output/preview.html

**Comment by heyMP** [comment]
Related to #608

**Comment by rickhumphries** [comment]
Thanks @heyMP those libraries are excellent for now

**Comment by btopro** [comment]
this was related to documentation / question. now #1287 is its successor.
