### ISSUE TITLE
serverpilot or similar suggestion 

### ISSUE THREAD

**Issue by jairana** [elmsln/elmsln#780]
Can ELMSLN work with serverpilot.
I want to install ELMSLN on digitalocean with serverpilot. Is it possible. If not can you suggest me alternative of serverpilot that can work with Elmsln. Are digitalocean's LAMP/LEMP installation   alternative of serverpilot.

**Comment by btopro** [comment]
what's server pilot? Never heard of it. We do installs on digital ocean all the time via http://elmsln.readthedocs.org/en/latest/INSTALL/

**Comment by jairana** [comment]
Ok, Thank you sir
