### ISSUE TITLE
Add more tables / clean up templates available

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#785]
Not exactly this but something like it
http://codepen.io/alimudassar111/pen/idyIq
and
http://codepen.io/ldesanto/pen/pEftw

Also look through the template buttons and make sure we have screenshots for all of them (we don't now) and re-export the associated feature with all the templates in the MOOC distro

**Comment by mmilutinovic1313** [comment]
This sounds good to me. was there a site that we had this updated on last time? I.e. ELMSLN docs. I can't quite remember where we had this stuff stored.

**Comment by btopro** [comment]
@heyMP has a style guide but we aren't including these templates there currently so no just the templates in mooc distro so that the wysiwyg editor has some table options. Also if you know of a better wysiwyg template browser that'd be good ;)

**Comment by mmilutinovic1313** [comment]
This is where my codepen will live. http://codepen.io/mmilutinovic1313/pen/NNYmRy I'm working on it currently while trying to remember how to CSS. I took out the buttons from the second one because I figured editing would be done through the drupal backend itself? If you think we should use the buttons I can readd them and find some images

**Comment by btopro** [comment]
yea the buttons aren't needed;

**Comment by mmilutinovic1313** [comment]
http://codepen.io/mmilutinovic1313/pen/grjxga

New pen here

**Comment by heyMP** [comment]
Nice start.  Can you try another color scheme where the background is white, since the ELMS course content is set on a white background?

**Comment by mmilutinovic1313** [comment]
Updated the background to be white and added a more interesting table color than the previous one!

**Comment by heyMP** [comment]
Lets make it resonsive too.  Can you remove the `width` property or set it to 100%?

Also, can you look into the materialize responsive table plugin? http://materializecss.com/table.html
It looks really simple.  you can use the  materialize javascript library.  https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js

**Comment by btopro** [comment]
getting there

**Comment by mmilutinovic1313** [comment]
@heyMP Would I add that plugin to the JS category on codepen then?

**Comment by heyMP** [comment]
Yeah in the JS settings you can add custom libraries like jQuery.

**Comment by mmilutinovic1313** [comment]
I've made two tables based off the materialize library. Both are responsive. One has stripes, where the other one has a hover feature. Let me know what you guys think of these designs / if you'd like me to design some other ones for MOOC.

**Comment by mmilutinovic1313** [comment]
Whoops! Here are the links: 

http://codepen.io/mmilutinovic1313/pen/grjxga
http://codepen.io/mmilutinovic1313/pen/grZgwm

**Comment by mmilutinovic1313** [comment]
Left to do:
- [ ] Add Tables
- [ ] Screenshots
- [ ] Re-export

**Comment by mmilutinovic1313** [comment]
Running into the error mentioned at: https://github.com/elmsln/elmsln/issues/885

**Comment by mmilutinovic1313** [comment]
Error fixed in https://github.com/elmsln/elmsln/pull/904
