### ISSUE TITLE
Guidelines For Reverse Committing

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#787]
Many people have been struggling (myself very much included) with backing out of commits when a PR is denied. Perhaps documentation can be written to ensure a streamlined development process. @proconnor15, @IBGregory, and I can work on writing this documentation, but may need some guidance in the proper configuration process.

**Comment by btopro** [comment]
@heyMP can help with that

**Comment by btopro** [comment]
good idea @mmilutinovic1313 you kick that off
