### ISSUE TITLE
Document drush usage in elmsln

### ISSUE THREAD

**Issue by jairana** [elmsln/elmsln#790]
[1]    I am able to download modules using drush commands. But if i try to enable that module it gives following error message .....
drush en super_login

Command pm-enable needs a higher bootstrap level to run - you will                    [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'en super_login' could not be executed.                                 [error]
A Drupal installation directory could not be found                                                    [error]

I download in this directory .....  cd /var/www/elmsln/config/shared/drupal-7.x/modules

[2]   i tried cc  command on drush but it shows  cache-clear for  drush only. 

[3]   drush commands do not work if i change user from root@....  to other user@...

I have installed latest elmsln on digitalocean using one line command

**Comment by btopro** [comment]
when you download the module where are you putting it / what command are are executing? drush by itself won't do anything without knowing where to put the module. If your doing it to test things thats fine but new modules should go in /var/www/elmsln/config/shared/drupal-7.x/modules . anything in there will appear in scope of all sites for adding new modules beyond the base we support. We manage this config directory via version control / sftp access while the core elmsln package is kept in version control

**Comment by jairana** [comment]
Yes, i download module in ....." /var/www/elmsln/config/shared/drupal-7.x/modules "....

My command was ......."drush dl super_login --select"
this command downloaded the module. 

But when i use command ......"drush en -y super login"
                                               " drush cc -all"
These command do not work      
 
ERROR message is .......
 
"......Command pm-enable needs a higher bootstrap level to run - you will [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'en super_login' could not be executed. [error]
A Drupal installation directory could not be found [error] "

**Comment by bradallenfisher** [comment]
There are multiple drupal installations in ELMSLN. So if you are running drush against one of them you will need to target the right one. That is why you got the "Command pm-enable needs a higher bootstrap level to run" since you probably aren't in a working drupal directory. 

Run ```drush sa``` to get a list of all the aliases then run ```drush @online en modulename``` to install the module.

**Comment by jairana** [comment]
WOW!!!  Mr. bradallenfisher. Thanks a lot. You saved a lot of my time and energy.
it works ....[drush sa   .....drush @online en modulename]
Please, i want learn little more

I found these aliases on drush sa, some of them i wrote down below
will i ever need to use these aliases. then what should be command for these aliases

elmsln.discuss.quant
elmsln.grades.la
service.studio-all
stacks
stacks.interact
stacks.lq

**Comment by btopro** [comment]
here's some popular examples.

`drush @elmsln cc all --y` - run command against every site found in elmsln
`drush @courses-all cc all --y` - run command against every site found JUST in the courses domain
`drush @network.sing100 cc all --y` - run command against every site in the sing100 network (this is the equivalent of `@courses.sing100,@studio.sing100,@discuss.sing100,@blog.sing100`)
`drush @stacks cc all --y` - run command against all authority systems (online, people, interact, media, comply, inbox, assessment, lq, etc)

**Comment by btopro** [comment]
@mmilutinovic1313 as you've used these aliases this would be a good thing to add to our docs; all the different varients of aliases and what they enable you to do.

**Comment by btopro** [comment]
@jairana you should also look at https://www.drupal.org/project/drush_recipes which was written to help administer / bulk automate tasks in elmsln. this allows us to utilize these alias targets in conjunction with chained drush commands

**Comment by jairana** [comment]
@btopro thank you https://www.drupal.org/project/drush_recipes  this is really very usefull

**Comment by btopro** [comment]
keep the questions coming, you're giving us lots of action items for our docs section :)

**Comment by mmilutinovic1313** [comment]
I'll add documentation for this.

**Comment by mmilutinovic1313** [comment]
Currently creating the .md file for this! Would you like documentation just for how to use the different aliases? Or also documentation for all the drush commands that exist? Or should that be a separate issue?

**Comment by btopro** [comment]
Alias groups and some common examples of uage like enable a module on all courses or cc all

Wp8
________________________________
