### ISSUE TITLE
Service Instances

### ISSUE THREAD

**Issue by jairana** [elmsln/elmsln#791]
When i create new course service instances stuck at "Almost there....."
I got one error message An AJAX HTTP error occurred. I am attaching screen shot of error 
I am attaching two pictures  
I have installed latest Elmsln on digitalocean with one line command
![20160328_225627-1](https://cloud.githubusercontent.com/assets/17768338/14097178/34662a54-f58c-11e5-8824-7acaad235cde.jpg)
![elmsln](https://cloud.githubusercontent.com/assets/17768338/14097204/6ded6c56-f58c-11e5-8a7f-e3d9274f14cb.png)

**Comment by btopro** [comment]
interesting. What specs are on the digital ocean box? 2 gigs of memory is the min

**Comment by jairana** [comment]
Right now i am using 1 gigs of memory, next month i will go for as you are suggesting 2 gigs of memory

But i am got AJAX HTTP error I attached this error in pic. 
How can i solve this.

Is improper memory creating this  "AJAX HTTP error"

**Comment by btopro** [comment]
Yes

Wp8
________________________________

**Comment by btopro** [comment]
BC of MySQL there is no guarantee it installed correctly without 2gigs

Wp8
________________________________

**Comment by jairana** [comment]
WOW!!!! 2GB worked for me. Now it is showing** service available** instead Almost there....
But now i am facing new problem. When i click Access Service under Service Instances It ask me username and password. But which user name password. i login in CIS using admin admin and this pair does not work on Access Service.

**Comment by btopro** [comment]
it may have failed to build correctly as a result of the lack of memory; bc of mysql upgrades we apply we require 2 gigs. So it may have appeared to have been working but really it was limping along. To delete those spaces you made which may be borked (install happens without that 2 gig requirement and then upgrades mysql after the fact on most instances... it's confusing I know. lol). if you log into the server and type `leafy` this will give you options for administering elms from the command line. One of the options is for removing courses / systems. Then you can walk through this guided prompt answering the questions which will kill off these drupal sites.

Then go into CIS and delete the service instances for the course (it's a node which basically just stitches together courses and services). After deleting these, you can now remake them and they should work this time w/ the added ram. After that it'll run the correct install routine fully which hooks in the bakery / account management stuff automatically.

You may need to clear caches / logout prior to accessing these bc the local cookie may already be set indicating you don't have access to courses.whatever/coursename

**Comment by jairana** [comment]
Thank you

On leafy point no. 11) remove a drupal site from ELMSLN (can not be undone)
i press 11
then followed the steps
but now i  am unable to create new courses
No response while creating new course

**Comment by btopro** [comment]
unable to create new courses? Did you delete the services associated with the quant course and then try to recreate them?

**Comment by jairana** [comment]
Yes, i deleted course using leafy then all related course nodes in CIS 
Now if i try to recreate service instances it again give screen to create new course 
I am unable to recreate.

**Comment by btopro** [comment]
hmm.. could you shoot a video of that or something? I haven't been able to replicate / experience that before. Also may want to do a `ls` of the `/var/www/elmsln/config/jobs` directory and see if there's any failed builds in there. Shouldn't be but it's possible from the memory issue. If there are anything in there that has error- in the name that'd be a sign of a failed build. Other thing to try; wipe all the job files out of this directory (they look like sing100.courses.processed and similar patterns).

**Comment by jairana** [comment]
When we create new course we receive this message. Where are these mail?
![elmslncourse](https://cloud.githubusercontent.com/assets/17768338/14204771/106dffb0-f824-11e5-84fc-3acbbd1b8f33.png)

**Comment by btopro** [comment]
the admin that setup the system should get emailed but the server needs to be allowed to send mail in order for that to happen

**Comment by jairana** [comment]
![studio account creation](https://cloud.githubusercontent.com/assets/17768338/14224982/e110a9be-f8cf-11e5-9817-e55984479fbe.png)
![studio account creation 2](https://cloud.githubusercontent.com/assets/17768338/14224990/1c3880b6-f8d0-11e5-93c1-c8f718a0df34.png)

**Comment by btopro** [comment]
Account needs to be mae in people then role assignment in something like studio. We are working on more automated methods for this as we have them inhouse

Wp8
________________________________

**Comment by jairana** [comment]
When i create new course this mail is delivered to my mail-ID. 

There are security updates available for one or more of your modules or
themes. To ensure the security of your server, you should update immediately!

See the available updates page for more information:
"http://reasoning/admin/reports/updates"

Your site is currently configured to send these emails when any updates are
available. To get notified only for security updates,
"http://reasoning/admin/reports/updates"
both these address do not work "http://reasoning/admin/reports/updates" and "http://reasoning/admin/reports/updates" Error shown

**Comment by btopro** [comment]
original issue resolved; this one you've brought up is also marked for working on in the future #735
