### ISSUE TITLE
Media: views for different roles

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#795]
Is there any way I can restrict an instructor (or any custom role) from being able to view and access the entire course list / all media assets in the system, so that they only see specific courses?

**Comment by btopro** [comment]
#298 should make this possible. right now no cause we haven't attached people to groups in those systems yet

**Comment by btopro** [comment]
#853 realized this is related

**Comment by btopro** [comment]
Longer answer. Yes, the authority section and user syncing stuff being worked on will allow for this. Then its a matter of propagating permissions correctly via the og roles work left to be added. Still up in the air how people see media if associated to a course or not. Was talking about a custom permission check that sees if you are in a section of the course and grants you access to view the listing if so, something like that.

Tricky but if we do it the right way you'd be able to see all the media associated to a course in a listing which could be pretty powerful for a media index type approach.

**Comment by btopro** [comment]
#824 will allow for this as we start to work it in
