### ISSUE TITLE
Confusing Course Outline Overlay

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#796]
Not a big deal but thought it was a bit confusing in terms of authoring experience.

So I have two different course outlines set up (A and B) for two different sections (A and B) on a course. Course outline A is associated with Section A and ...well, you can guess the rest.

'A' is the default for both section and course outline.

If I'm viewing section B and edit the course outline from the operations dropdown - to view outline designer for course outline B - so I'm looking at this page:
![image](https://cloud.githubusercontent.com/assets/4973810/14212601/a1285472-f82b-11e5-8558-6efb4a9163bd.png)

If I then click the 'Outline' button:
![image](https://cloud.githubusercontent.com/assets/4973810/14212698/009f56f8-f82c-11e5-91fe-2c47d2ef2411.png)
from here - it'll show course outline A instead of B

**Comment by btopro** [comment]
we place a notice now when working against a content outline that's not the active section

**Comment by rickhumphries** [comment]
Both sections are active though - and I'm working on a content outline whilst in section B still?

**Comment by btopro** [comment]
correct but ur on 0.2.0 and we've made a bunch of notices and things when the active section is different / not included in the content currently viewed. a message is shown to say "hey, ur viewing section A but this content isn't part of section A"
