### ISSUE TITLE
People domain

### ISSUE THREAD

**Issue by jairana** [elmsln/elmsln#798]
What is use of 'people.xyz.com' domain
If user account created in people account will be work on all other domain, Is this??
people.xyz.com/user works
online.xyz.com/user works but
blog.xyz.com/user do not work
studio.xyz.com/user do not work

when other domain will be active blog, studio

**Comment by btopro** [comment]
BC the role is local to each site. So you have an account but we largely treat auth only as anon.

Also blog/studio services are only produced if a course is produced. So courses pick and choose during setup if they use those. The top level domains for them currently so nothing by default.

Wp8
________________________________

**Comment by jairana** [comment]
Thank you
