### ISSUE TITLE
Course List Sync from CIS to authorities

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#799]
Previously all the courses we set up in the CIS were then being automatically created as content types in Media (which was ace). However, I created a new course a few days ago but this isn't being created automatically in Media now. Not sure whether anything changed recently that would affect this?

I've tried running the crons, syncing Media settings etc. but can't seem to pull it across

**Comment by btopro** [comment]
It's related to some things in the queue for version 3 though cron should pull it across. I believe this was in 2 but resolved in 2.1

**Comment by rickhumphries** [comment]
yeh we're on 0.2.1 currently. Media status report:

![image](https://cloud.githubusercontent.com/assets/4973810/14226707/bc78d9ca-f8e1-11e5-828b-3968bd0c1e05.png)

And CIS status report:

![image](https://cloud.githubusercontent.com/assets/4973810/14226708/cce7e15c-f8e1-11e5-9205-7e1a5e3858d7.png)

**Comment by btopro** [comment]
Hmm ok. I'll have to look at when I committed that then, thought it was 2.1 but may have misses that update. Probably going to roll a 2.2 after shooting a video of comply... Well.. And when there's a cool date /name for the release. We just missed April fools so now I'm lost as to good names ;)

**Comment by rickhumphries** [comment]
Cool, looks like you've got it covered anyway. 7th April is National Beer Day for you. Name it after your favourite brew!

**Comment by btopro** [comment]
Lol fantastic suggestion

**Comment by btopro** [comment]
#755 currently has this
