### ISSUE TITLE
Create a ELMSLN system level user during install

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#80]
provide bash script to do this as a stand alone as well. Then, installation would tap that user instead of root on the crontab (for instance). This is similar to what AEgir does for added security in that the elmsln user would have ownership of just the elmsln directory and write access on the files its supposed to. Again, getting more OS-like with this component.

**Comment by btopro** [comment]
marking security in that it is security related, not a security bug by any means.

**Comment by bradallenfisher** [comment]
assign me

**Comment by btopro** [comment]
We'll talk today but please work on this via fork and PR

**Comment by bradallenfisher** [comment]
do you still want the root user to run https://github.com/btopro/elmsln/blob/master/scripts/install/root/elmsln-preinstall.sh

**Comment by btopro** [comment]
This script to create the elmsln user for later use in running calls would be the thing that's called and established as part of elmsln-preinstall so, basically yes, root would need to run to initially kick off the entire process but then after taht I want elmsln being the account that handles the rest of the calls / anyone in the elmsln group.

**Comment by bradallenfisher** [comment]
Gotcha. What are the commands you want elmnsln  to run without passwd using sudo.

**Comment by btopro** [comment]
which ones are worth doing it for? lol, never fully understood that cause it seems like if you had chown / chmod you could just modify something to be your ownership and do whatever you want

**Comment by bradallenfisher** [comment]
Thinking more like restarting services like httpd mysql etc. Any other system level operation. I will come up with a list and go from there.

**Comment by btopro** [comment]
technically would be nice if it could update php / apache / mysql settings (so would need to be able to reboot them).

There's also some bash scripts in the scripts folder it would be good to be able to run (basically anything that's not specifically the root system installer). Can it get that granular as to individual scripts?

**Comment by bradallenfisher** [comment]
yeah on install we could just set the perms to be 700 and make the owner elmsln for any scripts that can only be run by the elmnsln user.

There is a lot going on in the scripts directory. I have forked the project here https://github.com/bradallenfisher/elmsln and will add the script...

How can i test this in an environment? 
Should i follow https://github.com/btopro/elmsln/blob/master/INSTALL.txt
What script(s) in order do I run to set this up in a completely blank centos env?

**Comment by btopro** [comment]
https://drupal.psu.edu/blog/post/install-elmsln-digital-ocean-one-line or https://github.com/btopro/elmsln-vagrant

**Comment by bradallenfisher** [comment]
Thanks. I am trying vagrant. I will most likely just submit a patch for this. Since when I try to run vagrant up against my fork i keep getting white screen at any of the urls in the /etc/hosts file. I assume this is because I am now (after 3 days) more than 10 commits behind. :) Not a deal breaker to get this done, but I am finding the testing "setup" difficult.

**Comment by btopro** [comment]
vagrant destroy; vagrant up there was something from friday that I resolved that would cause what you are describing. After getting vagrant up go to online.elmsln.local and login with admin/admin

**Comment by btopro** [comment]
or don't considering the task you are engaged in doesn't actually have anything to do with the drupal side of the application :)

**Comment by bradallenfisher** [comment]
The easiest way for me to get you this is a gist. 
https://gist.github.com/bradallenfisher/354c3fcf7e180dc4ef11

I don't know where you want it in the install process. But this should do what you want it to do.

**Comment by btopro** [comment]
loving it, it's a great start; I'll get it in soon in scripts / installer

**Comment by btopro** [comment]
@bradallenfisher you mentioned https://gist.github.com/bradallenfisher/354c3fcf7e180dc4ef11 which appears to give sudo w/o password rights to this account (though I might be misreading). What I'm thinking instead is this:

The elmsln user can do things that apache can't but that it has a pretty limited scope of what it can accomplish. You tell me what'd make this possible
- run drush commands
- ssh to other servers (technically there are drush commands / alias targets that could have ssh creds built into them)

ulmus user can
- do mysql, apache and php configuration management with password-less sudo
- drush as well

group for elmsln
group for ulmus

ulmus is the more privledged user, elmsln can basically just run drush. This way I can construct commits liek the one referenced which write files into a specific location, and then drush is invoked from there by a command processing job. This job would be kicked off in cron and be done as the elmsln user so that we know the script will ONLY be able to process drush commands.

**Comment by bradallenfisher** [comment]
So basically you just need to split up the sudoers privileges and edit the file you have in place already. 
Create the 2 groups
add the users to the groups
Edit elmsln file from /etc/sudoers.d -- see below
Create a new file in /etc/sudoers.d/ulmus

```bash
groupadd elmsln
usermod -a -G elmsln elmsln
cat /dev/null > /etc/sudoers.d/elmsln
#add any commands to that roles ... since they only need drush you really just need to edit the 
#.bashrc file so they can use composer. but if you needed any elevated sudo less commands 
#you would put this line or similar into the elmsln sudo file.
echo "%elmsln ALL=(ALL) NOPASSWD: /usr/bin/yum" > /etc/sudoers.d/elmsln
```
You would then simply run the keygen command for the elmsln user and put it on whatever server you want so it can ssh in and execute commands. 

The you would create the ulmus user and add them to the ulmus group.
```bash
groupadd ulmus
useradd -a -G ulmus ulmus
```

The ulmus user gets it's own file in sudoers.d with the list of commands it needs to run without password.

```bash
echo "%ulmus ALL=(ALL) NOPASSWD: /sbin/service httpd restart" > /etc/sudoers.d/ulmus
echo "%admin ALL=(ALL) NOPASSWD: /sbin/service httpd stop" > /etc/sudoers.d/elmsln
echo "%admin ALL=(ALL) NOPASSWD: /sbin/service httpd start" > /etc/sudoers.d/elmsln
echo "%admin ALL=(ALL) NOPASSWD: /sbin/service mysqld restart" > /etc/sudoers.d/elmsln
echo "%admin ALL=(ALL) NOPASSWD: /sbin/service mysqld stop" > /etc/sudoers.d/elmsln
echo "%admin ALL=(ALL) NOPASSWD: /sbin/service httpd start" > /etc/sudoers.d/elmsln
echo "%admin ALL=(ALL) NOPASSWD: /usr/bin/yum" > /etc/sudoers.d/elmsln
```


If i missed anything let me know.

**Comment by btopro** [comment]
Yes, this is looking good; and I assume this is specific for RHEL / CentOS

**Comment by bradallenfisher** [comment]
syntactically, but the logic would work on any system that has sudo and an included .d directory
I think they all do now? instead of editing the sudoers file directly...

**Comment by bradallenfisher** [comment]
also i updated the echos they were wrong ... c + p :)

**Comment by btopro** [comment]
you call yum which is what I was referencing :)

**Comment by bradallenfisher** [comment]
yeah true... I guess you could try to find out which package manager you need based on os. 
I can look into that. 
essentially the pattern above is for any command... for instance
echo "%elmsln ALL=(ALL) NOPASSWD: /usr/bin/yum" > /etc/sudoers.d/elmsln
could be
echo "%elmsln ALL=(ALL) NOPASSWD: /usr/bin/apt-get" > /etc/sudoers.d/elmsln

maybe something like 
```bash
if [[ ! -z "which apt-get" ]]
echo "%elmsln ALL=(ALL) NOPASSWD: /usr/bin/apt-get" > /etc/sudoers.d/elmsln
elif [[ ! -z "which yum" ]] 
echo "%elmsln ALL=(ALL) NOPASSWD: /usr/bin/yum" > /etc/sudoers.d/elmsln
fi
```
didn't check that though.
etc ...

**Comment by btopro** [comment]
@bradallenfisher could I do this to add elmsln to the admin user group? I want to try and establish the things it would need to do without actually having it be something people can log in as
```
useradd elmsln
usermod -a -G elmsln elmsln
usermod -a -G admin elmsln
```

it keeps asking for the elmsln user's password to do anything. I made one up but would rather not do this as we're looking for an account that can run basic commands, establish its own

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/commit/945975869298d20ede5d3bfb39574b99f62aaf15 trying this atm. I know it doesn't work though so not playing with it further yet

**Comment by bradallenfisher** [comment]
that's weird... it shouldn't ask for the user password when creating a new user account unless you type passwd then the user name

**Comment by btopro** [comment]
i mean i ended up doing that to try and get around it. you can try it out in vagrant and see what it does.

**Comment by btopro** [comment]
both accounts created at run time, just debugging though they aren't hooked up as the default method of operating or roped into the upgrade routines yet.

@bradallenfisher any idea if when I run the `sudo -i -u ulmus bash /var/www/elmsln/scripts/install/user/elmsln-admin-user.sh` command that it would do EVERYTHING right EXCEPT the composer part that actually installs drush. This remains in the local account and is not actually installed in the /home/ulmus/.composer directory; this happens on the root account instead.

Maybe I should just know where home is and forcibly copy those files over and chown correctly cause I'm getting a bit sick of this ;)

**Comment by bradallenfisher** [comment]
run  as root: 
ln -s /usr/local/bin/composer /usr/bin/composer
Earlier in script.

**Comment by btopro** [comment]
composer's not the issue in deeper digging; it's running composer but not respecting that I've told it to run the command as someone else. As a result, it's applying the composer packages (drush) to the user kicking off the command, not the one told its kicking it off as.

Only way around this is to copy the root user's .composer file into both user accounts and then rechown as the user in question. Trying this currently but doesn't seem to work, @bradallenfisher if you could glance at why this might not being working

https://github.com/elmsln/elmsln/blob/master/scripts/install/root/elmsln-create-accounts.sh#L46-L47

**Comment by bradallenfisher** [comment]
Change $HOME/.composer   to /root/.composer

**Comment by bradallenfisher** [comment]
I can look deeper into this though.  Should work.  Not sure what's up.

**Comment by btopro** [comment]
thought about that yeah im not sure why it doesnt do what I want; looks correct

**Comment by btopro** [comment]
made during install; just need cron stuff reviewed to actually implement them
