### ISSUE TITLE
original domain

### ISSUE THREAD

**Issue by jairana** [elmsln/elmsln#809]
How my original domain will work

right now only  people.xyz.com and                        online.xyz.com  works. But i want user approach my website using xyz.com
right now when i use my original domain it shows me apache screen and not connect to my website
Is it possible through DNS management???

**Comment by btopro** [comment]
Yeah, we don't make assumptions about how you want to handle that or other sub-domains root. For example you'll (by default) get this page if someone were to just go to courses.xyz.com without a course name.

You can add apache host entries (put them in their own files) and restart apache to take affect.

@bradallenfisher could possibly suggest a decent default file (that we might want to include but not enable by default).

**Comment by btopro** [comment]
Question hopefully answers, custom apache entry so that its flexible based on needs of the person implementing
