### ISSUE TITLE
PDOException: SQLSTATE[HY000] [2002] 

### ISSUE THREAD

**Issue by jairana** [elmsln/elmsln#810]
How to solve this...... suddnly i got this error 
![pdo](https://cloud.githubusercontent.com/assets/17768338/14311685/3ccd65e2-fc06-11e5-9f55-d5ad53661a62.png)

**Comment by btopro** [comment]
you got this where and doing what?

SSH in and restart mysql
`sudo /etc/init.d/mysqld restart`
or `service mysql restart`

May need more resources but dono

**Comment by jairana** [comment]
I got this when i was creating  course
But now i remove the droplet
Thanks for your reply
