### ISSUE TITLE
Switch Sections Option Isn't Appearing

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#811]
I noticed we had a a MOOC for a course that was created a while ago, so I've just switched the theme and settings (features etc.) over so that they match a recently created MOOC (following upgrade to 0.2.1). The only thing which isn't working properly is that the 'switch section' options isn't appearing under the user account menu:

![image](https://cloud.githubusercontent.com/assets/4973810/14321071/9f2dc412-fc0f-11e5-8dcc-3401338a8829.png)

Not sure why that would be. Is there a particular feature I should be looking at that controls this? 

The sections list also isn't appearing under the service tools menu:

![image](https://cloud.githubusercontent.com/assets/4973810/14321136/da02478e-fc0f-11e5-9be8-f19bec74e91e.png)

But I can still reach this anyway by going to `/cis/section-list`

**Comment by btopro** [comment]
see if anything needs reverted on the features page / dbupdate

**Comment by rickhumphries** [comment]
I've reverted everything I can in features. Only two things say 'overridden' now which is CIS Tokens and 'MOOC Textbook'. These don't revert to default when I try, but other courses have these as overridden too. What's the dbupdate?

**Comment by rickhumphries** [comment]
The sections list is appearing under the service tools menu now though after I reverted the 'CIS Section' feature.

**Comment by btopro** [comment]
status page see if it has any database updates to run

**Comment by rickhumphries** [comment]
Ah yeh, it all seems to be alright:

![image](https://cloud.githubusercontent.com/assets/4973810/14326027/050d695e-fc24-11e5-876b-533d38ecebf2.png)

**Comment by btopro** [comment]
hmm... see if elmsln_core and elmsln_api are enabled

**Comment by btopro** [comment]
I'll look into this this weekend after running through upgrades

**Comment by rickhumphries** [comment]
I'll DM the course link this is occurring on

**Comment by btopro** [comment]
can confirm something screwy here

**Comment by btopro** [comment]
think we agreed this was a misnomer / you'd rebuild the space. nothing suggested this was systemic / should be happening lol

**Comment by btopro** [comment]
Finally experienced this. When transitioning from an authority to a service it was possible for the section scope to get set to something invalid (master_art010 instead of just master). This is to maintain the notion of "master" while in the authority systems. There's a check now to dynamically switch this
