### ISSUE TITLE
Breadcrumb showing in iframe

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#813]
![screen shot 2016-04-07 at 3 59 14 pm](https://cloud.githubusercontent.com/assets/3428964/14365077/c85fba00-fcd9-11e5-8781-af765cf151ba.png)

**Comment by btopro** [comment]
hmm... did u request default or iframe mode and is the foundation_access_iframe theme the one that's being told to be used in the media system?

**Comment by heyMP** [comment]
I'm actually running an update via leafy now.  It's possible that it's due to the fact that my previous update failed halfway through.

**Comment by btopro** [comment]
this still there?

**Comment by heyMP** [comment]
Yeah it's still there.  I'm going to tackle it tomorrow.

**Comment by heyMP** [comment]
entity_iframe theme switched to Adminimal for some reason.  I switched it back to foundation_access_iframe and it was fixed.
