### ISSUE TITLE
Fatal error when adding H5P nodes

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#815]
After running the last ELMSLN update, I'm getting a PDOException when attempting to create a new interactive_content node.  I've updated my H5P libraries as well as ran all database updates.

currently on commit: 19b9e17, Merge pull request #806 from heyMP/master

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'library_id' cannot be null: INSERT INTO {h5p_nodes_libraries} (content_id, library_id, dependency_type, drop_css, weight) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => 1509 [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => preloaded [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => 1 ) in H5PDrupal->saveLibraryUsage() (line 490 of /var/www/elmsln/core/dslmcode/stacks/media/sites/all/modules/local_contrib/h5p/h5p.classes.inc).
```

**Comment by btopro** [comment]
hmm.. sounds like something to bring up in their queues or try wiping the known libraries to the builder and then reimporting them

**Comment by heyMP** [comment]
Reported to H5P drupal module. https://www.drupal.org/node/2703015

**Comment by heyMP** [comment]
Hmmm.... very confusing... I'm not sure what the issue is.  Tested it on a fresh Drupal install and it worked.

**Comment by btopro** [comment]
I'll take a look next week
