### ISSUE TITLE
Elmsln demo site or kickstart website.

### ISSUE THREAD

**Issue by aryavart** [elmsln/elmsln#816]
Hello sir 
I have installed Elmsln on digitalocean(2GB/40GB) following your video tutorial on youtube. But i stucked on the first step that is course creation.  When i create course, i get message either 'Access Denied' or course creation process is stucked on "Almost there....."  just show this message for all course created. So dont know what to do. I have stucked at starting point then how i will be able to make it. 

I want to know, is there any Demo/kickstart website of ELMSLN,  i can install that and just change the name of course and content. 
Is it possible??
 I want to create QUIZ website. Multichoice questions, solutions,discussion forums and youtube videos link. 

I have tried many drupal distribution but not faced this type of situation. 
Please help me out.

**Comment by btopro** [comment]
What specs did you use? It requires at least 2 gigs of ram to get going bc of mysql

**Comment by aryavart** [comment]
Yes sir i have 2 gigs of RAM

**Comment by btopro** [comment]
do you have real web addresses for it / what domains are you using? deployments need real domain names OR need them faked on the VM itself in /etc/hosts in order to function.

If your just looking to play there's a demo linked off the elmsln.org site -- http://online.do1.demos.elmsln.org/

**Comment by btopro** [comment]
original question was about demo which we already have off of https://elmsln.org for playing

**Comment by aryavart** [comment]
I have my domain name. I want to deploy real ELMSLN website. I am facing problem huge problem to use ELMSLN. So i think if there is Kickstart website having demo course and content created  then it will be easy for me to start my website. 

Thank you sir i have gone through these web address https://elmsln.org , http://online.do1.demos.elmsln.org/ 

I am not saying this type of demo website. This for i can cheque how ELMSLN work. I am talking about Real Website which we install on digitalocean

**Comment by btopro** [comment]
I'm not sure what a Kickstart website is, the directions for instal on digital ocean and multiple videos for doing it both on Digital ocean and Amazon EC2 should get things there. If this isn't the case then we need details about what version your on, what steps you took, the name of the domain, etc.  Bare in mind this is marked 0.2.1 for a reason as we're still in a alpha phase relative to overall plans for the network and bug fixing its complexity.
