### ISSUE TITLE
Facing huge problems in course creation

### ISSUE THREAD

**Issue by aryavart** [elmsln/elmsln#818]
Hello sir 

On digitalocean I have 2 GB Ram / 40 Gb 
I have purchased my domain name. 
Installed on digitalocean using oneline installation. 

I am facing problem  in course creation again and again. And Installation Environment   is Same for All. Installation Line is Same and Automated. So these is no question i am doing something wrong or   i am missing something. SIR WHEN WHY ONLY I AM FACING UNUSUAL thing in course creation. 
[1]   In "STUDIO" it always show "Almost there...." But other show Service Available
![studio1](https://cloud.githubusercontent.com/assets/18336403/14405657/4f55ffd2-feb1-11e5-8e44-41c585b1f74c.png)
![studio2](https://cloud.githubusercontent.com/assets/18336403/14405660/5c9ac876-feb1-11e5-9520-1d09a4c6377c.png)

I DELETE AND INSTALL DROPLET 4-5 Times but Still "STUDIO"  always show "Almost there....."

[2] In your "YOUTUBE Video" when you click on "ACCESS SERVICE" YOU GOT THIS "HOME" and Lesson, table of contents etc. Picture BELOW:
![studio4](https://cloud.githubusercontent.com/assets/18336403/14405662/6a7d6afc-feb1-11e5-9757-4a37eeb80be6.png)

But when i click on  "ACCESS SERVICE" i get this "USER ACCOUNT"  Picture BELOW:
![studio3](https://cloud.githubusercontent.com/assets/18336403/14405669/79cc6c74-feb1-11e5-9565-da13746dfbf8.png)

ALL things are same for all then why i am facing this situation.

Please HELP ME OUT I AM STUCK ON FIRST STEP....CANT MOVE AHEAD......

**Comment by btopro** [comment]
1. there was an issue that I closed out today about the studio.
2. Type the same username and password again and you'll be logged in. If you made a course that doesn't require a login to access then right now not everything will auto log you in.
3. this is working from the screenshots your
