### ISSUE TITLE
Suggestions in earlier issue did not work. 

### ISSUE THREAD

**Issue by aryavart** [elmsln/elmsln#819]
Hello sir

On digitalocean I have 2 GB Ram / 40 Gb 
I have purchased my domain name. 
Installed on digitalocean using oneline installation.

I am facing problem in course creation again and again. And Installation Environment is Same for All. Installation Line is Same and Automated. So these is no question i am doing something wrong or i am missing something. SIR WHEN WHY ONLY I AM FACING UNUSUAL thing in course creation. 
[1] In "STUDIO" it always show "Almost there...." But other show Service Available
studio1
studio2

I DELETE AND INSTALL DROPLET 4-5 Times but Still "STUDIO" always show "Almost there....."

[2] In your "YOUTUBE Video" when you click on "ACCESS SERVICE" YOU GOT THIS "HOME" and Lesson, table of contents etc. Picture BELOW:
studio4

But when i click on "ACCESS SERVICE" i get this "USER ACCOUNT" Picture BELOW:
studio3

ALL things are same for all then why i am facing this situation.

Please HELP ME OUT I AM STUCK ON FIRST STEP....CANT MOVE AHEAD......

**Comment by btopro** [comment]
Duplicate
