### ISSUE TITLE
Test patch from Replicate UI

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#823]
Here's a good step forward to build on top of what you've been playing with in Innovate @proconnor15 .
https://www.drupal.org/node/2704773

This patch resolves an issue in Replicate UI (a project I wrote for elms) that involves paths being wrong for certain entities that are created.
- [ ] navigate to the replicate folder on your file system and then do `wget ` followed by the url to the patch
- [ ] look up how to apply patches, then apply this patch to replicate and sftp it into vagrant
- [ ] Create a new innovate space or reuse one and go to the Modules area of drupal and enable replicate ui and entityforms (if its in there, I think it might be)
- [ ] Verify the steps the user has mentioned to replicate the issue
- [ ] after it's confirmed working, issue a pull request against the elmsln repo and comment in that queue that it's working (if it indeed is)

Once this is into elmsln I'll go and roll it into replicate_ui on drupal.org and credit you there (make sure you have a drupal.org account if you don't already)

**Comment by mmilutinovic1313** [comment]
So I rerolled his patch through (as his line numbers were off for the patch) and I ran through the steps and got this error message. 

![replicate error](https://cloud.githubusercontent.com/assets/7243665/15219297/3aa3396c-1831-11e6-903b-8cc62df4a77f.png)

**Comment by mmilutinovic1313** [comment]
Verified this error is occurring on the ELMSLN install as well. I posted the error to him in the issue queue asking if he had any other steps he was using when he tested his patch.

**Comment by mmilutinovic1313** [comment]
Pending merge this should be good to go
