### ISSUE TITLE
Add simplify

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#826]
replace jammer with simplify if we can. will have to decouple the strongarm'ed variables.

**Comment by btopro** [comment]
https://www.drupal.org/project/simplify

**Comment by btopro** [comment]
@proconnor15 adding the module into the stack; play with it in a course outline tool by enabling this and disabling jammer. They should do similar things but see if you can clean up node forms and things with it and see how well it works

**Comment by mmilutinovic1313** [comment]
@btopro I see that you added the simplify module to the stack in that commit, do I have to en it via drush? I searched simplify on the module page and nothing came up.

**Comment by mmilutinovic1313** [comment]
Redownloaded it via drush. Let me know if we need to re-add the module into the stack in this issues PR!

**Comment by mmilutinovic1313** [comment]
Cleaning up forms with this module is doable, however certain edit menu items are not able to be hidden:

- Visual Identifiers
- Navigation Block
- Tags
- Hide Content

I'm not sure if we want these items to be hide-able, or if this configuration would be fine. I think Hide Content and even Visual identifiers are important to have, but I am not certain we really need to see Navigation Block or Tags. Let me know what you think and if everything is in order, I will do a PR adding simplify and removing jammer.

**Comment by mmilutinovic1313** [comment]
So with @btopro 's comments on the PR, there are still several things that need to be done
- [ ] Design feature / module that keeps jammer's settings while we implement Simplify
- [ ] Gather Requirements for what we want Simplify to have hidden
- [ ] Decide what to do with system setup for hiding things. (i.e. install and upgrades)

**Comment by btopro** [comment]
recommended steps to accomplish:
- Spin up courses sing100
- Screenshot of the content entry form
- enable simplify / disable jammer at same time
- investigate settings for simplify that clean up interface to similar degree as jammer (screenshot / vid)
- see what module currently has the jammer settings included (I believe it's either foundation_access_ux or elmsln_core)
- propose a PR that converts this feature to use simplify instead of jammer

**Comment by mmilutinovic1313** [comment]
![simplifiedmenu](https://cloud.githubusercontent.com/assets/7243665/15321656/de15a08a-1c05-11e6-8fcb-f66f9ea60cba.png)
![simplifiedmenusettings](https://cloud.githubusercontent.com/assets/7243665/15321657/de20465c-1c05-11e6-92c9-29a31267e659.png)

I believe that these settings would be simplified enough for instructors / content creators to not be overwhelmed with options.

**Comment by mmilutinovic1313** [comment]
These options allow the user to adjust location, tag content, hide content, and or mark it as published / unpublished.

**Comment by btopro** [comment]
looks reasonable. probably don't need menu either as far as defaults go. Jammer right now is pretty aggressively applied to remove basically all of these settings as they are admin who knows why the hell they'd care about them type of settings. We have better interfaces for handling all of these (or should)

**Comment by mmilutinovic1313** [comment]
Sounds good - I'll get rid of menu as well. For the next step, I was wondering what I should be looking for in the "foundation_access_ux or elmsln_core" areas. I looked at those features, but couldn't find mention of "jammer" anywhere.

**Comment by btopro** [comment]
at a glance the jammer settings are in each install profile

**Comment by mmilutinovic1313** [comment]
Hmmm gotcha - so I'll do a re-export of each install profile with simplify instead of jammer.

**Comment by btopro** [comment]
just do one and issue PR so we can test. this isnt a simple switch

**Comment by mmilutinovic1313** [comment]
Okay that works

**Comment by btopro** [comment]
another way to find jammer --
`drush @courses.sing100 dis jammer`
see what else has a dependency then needing disabled

**Comment by mmilutinovic1313** [comment]
Got settings switched out for mooc_ux_defaults feature. If this PR looks good then the migration process shouldn't be too bad - however may take some time to ensure all instances of jammer are removed.

**Comment by btopro** [comment]
added an upgrade hook in to support this, good work mark.
