### ISSUE TITLE
Gist integration

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#83]
Review https://www.drupal.org/project/gist_filter and see if it would work for embedding gists into elmsln content areas.

**Comment by michael-collins** [comment]
Can we auto generate a book outline based on gist naming conventions?

**Comment by btopro** [comment]
like process and ingest markdown and convert it into an outline of content?

**Comment by michael-collins** [comment]
Grab the multifile gist, based on naming of files, generate an outline navigation. Then embed the gists on each node of the outline.

**Comment by michael-collins** [comment]
The module supports embedding of specific files in a multifile gist.

**Comment by btopro** [comment]
correct it does, if it works, I didn't test it. Also your use-case is a smidge on the obscure side but I like the idea.

**Comment by btopro** [comment]
@mmilutinovic1313 please play with this locally in the courses.elmsln.local/sing100 space you setup via vagrant. Need to try this out and haven't had time. To test, make a gist and see if you can embed it via input filter.

**Comment by btopro** [comment]
@michael-collins check how read the docs is built. it's something that would be amazing to mirror in this type of a request. Instead of using gists, use an actual git repo.

https://github.com/elmsln/elmsln/tree/master/docs is the "pages" of the course, they are in here however you want

You then point to them / structure them however you want in https://github.com/elmsln/elmsln/blob/master/mkdocs.yml

**Comment by btopro** [comment]
this is basically a crappier version of #302 so we'll continue it there
