### ISSUE TITLE
Enable collapse.js available everywhere

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#834]
If the textbook module is not enabled, collapse.js is not aggrigated and therefore breaks the dropdowns, located in the CIS Shortcodes sharing widget.  This should probably be enabled everywhere.

**Comment by btopro** [comment]
This already should be... though you've run the update hooks so maybe this isn't picked up and needs one. hmm.. We DID just pick an arbitrary update hook date to do the #523 so maybe it got missed in a much earlier one cause that's the only site I've seen w/o textbook

**Comment by heyMP** [comment]
I probably disable textbook from media without thinking about it.
