### ISSUE TITLE
increase the number of advagg bundles in elmsln_advagg

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#836]
We right now have 2 of each but really since LMSs have a captive audience we probably should set this higher. Mike Carper recommended 15 or something high. This way it bundles it all up in a way that makes sense but has a higher chance of hitting the same thing

**Comment by mmilutinovic1313** [comment]
Set bundles to 15 because high numbers

**Comment by mmilutinovic1313** [comment]
update hooks: .install file (look in cire fir sexample). Do variable set to equal 15 for each of the names.

**Comment by btopro** [comment]
`elmsln_advagg.install`

**Comment by mmilutinovic1313** [comment]
Should be good to go pending merge
