### ISSUE TITLE
Auto grant roles to instructors and admins on authorities

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#837]
We should have the ability to add an instructor to a course and have that instructor role propagate to the authorities, such as media and interact.  Right now, if you want to add an instructor to a course. You need to add them in courses, media, and interact.

**Comment by btopro** [comment]
#298

**Comment by btopro** [comment]
#824

**Comment by btopro** [comment]
need better granularity in permissions in the section level and sections to be synced w/ the correct data model. How about we tackle these next week (mostly talking about it needed). From there it'll be easier to make this happen automatically as it'll pave the way for user / roster data coming from `people`

**Comment by btopro** [comment]
admins this now works, instructors I believe this will happen on-demand but need roster data to suggest that's actually the case which my VM currently doesn't have :)

**Comment by btopro** [comment]
Admins / staff do, so that means it works with rosters (previous test showed this). If it's not propagating then we can review that at that time
