### ISSUE TITLE
Ability to add custom HTML banner for courses.

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#840]
We have a complex banner that we are trying to make for a course.  This banner has a background, and three svg logos.  Right now, you can only upload an image for a banner.
### Solution 1

We could simply add a new `banner` region to the foundation_access theme and subthemes.  This would allow someone to create a custom block with the necessary html and place that block in the banner region using context.  The downside with this is that the block is only local to the course service.  This block would need to be replicated on all of the different services such as "blog" and "studio".
### Solution 2

We could create a new setting in `/cis/course-settings` that would allow the user to save custom html as a Drupal variable.  This variable could easily be synced across services with the new ELMS pinprick API. (what's the name of it again?)

**Comment by btopro** [comment]
hmm... sounds ultra specific / something that would have a module driven use-case and then that module ties into the sync'ing system. shoot for solution 1 for now and we'll table solution 2 for now / see what patterns emerge. I currently know no1 that uses SVGs to the levels of awesome you do :)

**Comment by heyMP** [comment]
The use case isn't really svg's it's more of having a banner that is more than just an image that can be synced between systems.  So like having a banner that meets PSU standards of "you must have a the pennstate logo that links to the psu.edu site at the top of your website."

But yeah I agree. solution one for now.

**Comment by btopro** [comment]
#2293

**Comment by btopro** [comment]
HAXcms skips this
