### ISSUE TITLE
Look into ghostinspector

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#844]
ghostinspector.com lets you make tests via browser plugin, explore usage and how we could leverage this with a public site / demo perhaps.

**Comment by mmilutinovic1313** [comment]
On it!

**Comment by mmilutinovic1313** [comment]
Some initial thoughts: 

1. Plugin is very simple to use. Simply press record and it will record the various clicks in your browser. You can add notes to these clicks. 
2. 100 tests per month may be a low quota as that is their free tier. 
3. The application seems to be having issues operating in the vagrant. I'm going to try and run a test against a production / other type of website (outside of elms) to see if it will validate steps.
4. The steps it records are pretty much just the markup classes and such. 

I'll try this with a site with a valid URL to see if it can produce more useful feedback. I like the recording feature as it's super easy to record and accurate in targeting the proper elements.

**Comment by mmilutinovic1313** [comment]
Production works. You need to login to the site every time you record as the application tries to run the tests without authentication and fails. But when it does work / has authentication it produces a nice video output and allows you to repeat the test with a click of a button. I sent them an email asking if they had a solution for testing in vagrant environments. I'll let you know if I hear back from them

**Comment by btopro** [comment]
can you record one and post it here that sounds really interesting

**Comment by mmilutinovic1313** [comment]
Yessir! I will post the video of my last test here in a few minutes. I also got an email back from someone who works there who pointed me to their local dev and firewalled dev tutorials. https://ghostinspector.com/docs/test-local-and-firewalled-websites/ . I'm going to work on trying to get that setup today and I'll make a new issue to add documentation on how to use the tool.

**Comment by mmilutinovic1313** [comment]
Here is the video once it uploads: https://www.youtube.com/watch?v=u9hKqbW6pk0&feature=youtu.be

**Comment by btopro** [comment]
@mmilutinovic1313 really impressive. We need to make this a blog post on https://elmsln.org/ (maybe even https://drupal.psu.edu/ as a planet post). After you get it working in local development showing end to end how to get it working for doing local testing would be great visibility for all.

**Comment by mmilutinovic1313** [comment]
Sounds good to me! I'll let you know once I get local testing working. I'll add some tasks for this stuff now

**Comment by btopro** [comment]
this can close out, spun off into action items at #872
