### ISSUE TITLE
On duplicate check for internal links and rewrite them

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#849]
When replicating an outline we need to look for the old links and update them to potentially new ones when they reference internal `node/123` thing

**Comment by btopro** [comment]
This is a pretty complicated one @mmilutinovic1313 but you want to take an initial stab? Basically we'd want to see when an outline is being duplicated and build a big ass array of what it was and what it became (as far as duplication). From there we'll have to rewrite all content internally to make sure it now points to what it's been mapped to.

**Comment by mmilutinovic1313** [comment]
Sure, I'll take a look and stab at it this afternoon!

**Comment by mmilutinovic1313** [comment]
Is the code for this in the outline designer module?

**Comment by btopro** [comment]
`book_copy_copy` in book_copy performs the batch API process of looping through. So it knows all the nodes to be copied and (technically tho without storing it) what they become. We need to capture what it was and what it became as a map in book_copy_copy, then do something like _book_copy_rewrite or some other function that then looks in the content and rewrites any internally pointing links ( node/{old} to node/{new} ). This would be a new function added to `book_copy_process_copy` which is invoking the batch api (drupal api in core, very confusing).

I THINK context will remain populated between functions, if this is the case then it shouldn't be too difficult. If it's not well then it might get a lot more difficult

**Comment by btopro** [comment]
blah, context variable doesn't carry over... will need something more complicated..

**Comment by btopro** [comment]
@mmilutinovic1313 going to jump this over to @bradallenfisher since he actually has experience working with book_copy and might be a good way to get him in on the module dev level

**Comment by bradallenfisher** [comment]
how i found the module in question. 
```
grep -nr 'book_copy_copy*' .
```

**Comment by btopro** [comment]
you'll get the structure down, it's not hard just different

**Comment by bradallenfisher** [comment]
Does the issue happen when you create a link in a body field inside outline A that points to another node in outline A?
Then when you copy outline A to outline B the new body field in outline B still points to the node in outline A but should point to the node in outline B.

Is that what we are talking about?

**Comment by heyMP** [comment]
Yeah that's the correct scenario.

**Comment by btopro** [comment]
yup

**Comment by btopro** [comment]
This isn't a blocking issue for 0.4.x though it'll be nice to get done soon

**Comment by bradallenfisher** [comment]
agreed. I have a handle on it. once i have a stretch I will get it done. Basically initial_nid will replace clone->body values with str_replace either during or after cloning.
