### ISSUE TITLE
Micro-Feedback: Collecting in-context feedback on design elements 

### ISSUE THREAD

**Issue by kmiffitt** [elmsln/elmsln#850]
I'm interested in working on a way to collect "micro-feedback" on basic course design criteria in-context, in lieu of or in addition to summative evaluations. For example, you could deliver a question regarding a video's level of engagement, rigor, production quality, etc. after students view in the course. 

A quick list of areas to evaluate include: clarity of information, ease of use, level of engagement, level of rigor. Most questions could use some sort of likert scale. 

Bryan and I discussed an easy way to pilot this would be to use h5p questions and A/B testing to see if we get meaningfully different data in-context. If so, we could build a more robust tool that would also include a dashboard to set targeting criteria, such as % complete for validity (deliver question until 10% completion rate), student demographics/info (target students with B & C average in class).

**Comment by btopro** [comment]
#906 we've started on this and it's awesome :)
