### ISSUE TITLE
Make callback to return form as JSON

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#870]
Be great to pass a path and form id and get back the form as JSON. This will include tokens and what not to do it securely.

`form-as-json/{form_id}` with a session token (obviously).

**Comment by bradallenfisher** [comment]
Can you give me an example of a form to develop this against?

**Comment by btopro** [comment]
any form. idea being we could query this and go form-as-json (or whatever the name is)
`http://media.elmsln.local/form-as-json/elmsmedia_image_node_form`

and return the image form as a json array. This way we could pass this to angular for the #848 to use the exact structure and settings and order of Drupal (so security, config changes in the system as expected) but modify the angular application. This would let us build a more generic angular based node creation widget among other things
