### ISSUE TITLE
Creating a discussion board for students with reputations and rewards

### ISSUE THREAD

**Issue by gpruim** [elmsln/elmsln#871]
## Introduction

Following a quote from the introduction of a paper describing the effects of gamification on student learning through the use of reputation and rewards within community moderated discussion boards. See also [University of Queensland](http://espace.library.uq.edu.au/view/UQ:326086). 

> Online discussion as a means of collaborative learning within a course is a key aspect of
> education as it promotes deeper thinking. Providing effective tools that support student
> discussions in the virtual space is an important area of investigation and development for
> student learning Most Learning Management Systems (LMSs), (the applications that
> underpin e-learning), have some type of discussion forum integrated into the software. These
> programs range from traditional forums such as newsgroups to real time chat programs.
> Over the past few years it has become apparent, based on the results seen in anonymous
> student course evaluations that traditional discussion forums are proving to be ineffective for
> question and answer style discussion. Important information is often lost in the chronological
> ordering of content, there is no reward for active participation and students seem to be
> frustrated with the format and the lack of prevalent ‘experts’ and rewards for participation.
> Kelly and Cernerud (2002) showed that students’ impressions of online learning systems
> are strongly influenced by their implementation a n d co n se q u e n t l y t h i s poor
> implementation can lead to an overall negative opinion of the course. Student participation
> has been shown to decrease, as class sizes grow (Jones et al., 2004) and as classes grow
> the amount of interaction time between staff members and students decreases. Therefore it
> is important to develop new and innovative means to provide improved participation that
> includes some element of reward to students regardless of class size.
> To explore the relationship between rewards given to users and participation levels, a new
> independent discussion tool ‘Casper’ was developed to provide a forum for student
> questions and answers. The tool was designed to provide merit points and badges as a
> form of rewarding students and encouraging participation and in-depth discussion.
> The Casper system included a points or ‘reputation’ system in order to reward positive
> contribution (i.e. a well written question or answer) and highlight to users who within the
> community, may be considered an expert. Voting on content was the main form of
> reputation change with additional points awarded when the author of a question or
> any staff member marked an answer as the best answer. Badges were also added to
> give clear feedback on user participation. Both reputation and badges were visible by the
> entire community as a means of identifying which users could be considered
> knowledgeable. This design was based on the concept of Gamification which is the
> process of adding game-style elements such as points and badges to otherwise ordinary
> tasks. This process has been shown to improve engagement in many contexts (Kapp,
> 2012; Reeves & Reed 2009). Kapp (2012) has extensively researched the effects of
> gamification in learning and has shown that proper implementation can positively affect the
> learning outcomes of students.
> 
> Many successful online forums use elements of gamification to enhance discussion; these
> include the popular sites “stackoverflow.com” and “reddit.com”. Both sites provide users with
> a points system to indicate positive interaction within the community. Pal et al. (2012) have
> shown that in such situations a group of users may develop who are considered ‘experts’
> by their peers and these expert users often nurture and help shape the community in a
> positive way. These users are identified by a publicised display of their reputation using
> points and badges. This was mimicked in Casper to help discover whether the same
> development of expert users occurred and helped to build the community and learning
> environment.

The demo can be seen on this [video](https://www.youtube.com/watch?v=jc6l9OYYbCI). Casper is based on Drupal. I could not find any distribution that was open sourced. Also I have not been able to get in touch with someone from the University of Queensland (yet).
## Discussion board in ELMSLN

In my recent contact I had with @rickhumphries I mentioned this tool. I stated that a similar solution could be a great addition to ELMSLN because of the reputation and rewards. Especially if they are combined with Open Badges by using [Open digital badging](https://www.drupal.org/project/openbadging) and xAPI to register these [Drupal achievements](https://www.drupal.org/project/achievements) in a learning locker like shown in this [video](https://www.youtube.com/watch?v=_r1gJb6K9A0) from Rick. Also [Drupal Goals](https://www.drupal.org/project/goals) can be used in this.

Rick replied that there is already a discussion board/forum service based on [Harmony core](https://www.drupal.org/project/harmony_core). I am not aware of the status and the current functionalities of this module in ELMSLN.
## Gamification in a discussion board for ELMSLN

In my opinion, given the introduction it would be great to integrate these gamification elements (reputation and rewards) in a learning environment like ELMSLN and share it with the community. Especially if they can be connected to xAPI. In this way e.g. a student who has helped fellow students and in this way has shown his or her talents, could get an open badge and use it in his career. 
## My question

Are there people involved in the ELMSLN project who are interested in this and maybe want to discuss this subject? And if there are more people interested we could see how this could be a new feature to develop? I am not a developer, but I have good contacts with the maintainer of some of the modules I mentioned, like Answers: Pierre Vriens.

I can be of help in providing user stories, examples, mockups and discuss requirements. Also I can involve Pierre in this, if needed.

Thanks for reading all this and hope to hear from someone from the ELMSLN community!

**Comment by btopro** [comment]
@kat-wehr @kmiffitt something to check out --^

@gerardpruim thanks for the post, this is a fantastic idea. There's lots of concepts surrounding badges, discussion boards, XAPI and the like. We have some undocumented "gamification" elements in the Studio currently via the achievements module. These are localized and not tied to badges (so doesn't scale as a concept, yet) which is why we haven't talk about it. It uses the achievements module which gives an Xbox Live style "leaderboard" and achievement granting which does a little pop up of a trophy thing. Cool idea, currently we only really use it for like "hey you've commented 10x that's awesome!" sort of "achievements".

We do have a tool called Discuss which is built on top of the Harmony Drupal Distro. I picked harmony because it uses entity structure (and does so really well). From there we can make it whatever we need in my mind. The Queensland video is fantastic and looks a lot like a Reddit style forum system almost. Maybe @heyMP we could have @gerardpruim on our next ELMSLN Google Hangout that we do weekly to discuss this idea / answer some questions? (I also think we should start doing these on air though I know I'll have to swear less)

**Comment by kat-wehr** [comment]
I love the idea of upvoting discussion responses and building up students' reputations in classes. (This is actually the topic of a research paper I did for my masters, why online communities like reddit are successful and educational ones tend to struggle so I'm really interested in exploring this) 

One challenge I foresee is how does the reputation carry over from one class to another? Is it by semester? how do we account for courses that don't utilize discussions? Would it be a formula kind of like "This person has contributed this many posts out of this many opportunities to post" where opportunities = discussion forums available to them over the course of their time as a student? 

Don't get me wrong, I LOVE the idea. I have a feeling that this is one of those things we're planning for down the line but isn't a huge need yet (at least not in my area of influence). Right now most of the faculty I work work see discussions as an assignment to be completed rather than as an opportunity to assess engagement/participation in a course - it's very much a "post X times in this discussion and reply to X classmates in order to get full credit" type of implementation. I would love to see the pedagogy around online discussions change to better reflect how discussions impact a small face to face class and ideas like this move us closer to that.

**Comment by gerardpruim** [comment]
Thanks for the feedback, I really appreciate it! There are still many challenges, both technically and in creating a successful environment for this. If I can join a meeting and discuss it with you that would be great.

**Comment by gerardpruim** [comment]
There is a distinction between discussion and q&a sites to be noticed. While the term discussion board is used, the examples that have been used, like stackexchange. Reddit serves a different purpose. In my opinion a q&a solution like Casper is helping students in finding answers. It would be interesting to talk about this further with you.

**Comment by terryjack821** [comment]
registered IELTS & TOEFL, ESOL certificates without taking the Exams for sale 

For any inquiry send an email at:(peterpeddy3@outlook.com)
We offer our exclusive clients the ability to gain IELTS,TOEFL,ESOL
AUTODESK certificates without taking the exams. The regions we cover
are Asia ,UAE, Qatar,For any inquiry send an email at:(peterpeddy6@outlook.com)
Oman, Saudi Arabia, Jordan, Kuwait ,Australia ,Canada and Europe and The exams are taken for them
by writers who are paid to do it using the names of our clients. Our
organization is well connected with various invigilators and test
centers to allow our
writers to take the exam on your behalf. We also create ID cards with
the names of our clients to
allow the writers do the exam without problems. All our certificates
are original and British Council certified. We do not make fake
certificates! If you want to make IELTS,TOEFL,ESOL AUTODESK
CERTIFICATES Without Attending Exam.
buy ielts books
buy ielts certificate in dubai
buy ielts score
buy ielts self-study books and materials
buy ielts practice tests
buy ielts book online


if interested contact below
peterpeddy3@outlook.com
Contact us by email peterpeddy8@outlook.com

Skype:::::::::::::::::::::::::::::::::::::::::::::::::::::: online.service75


we provide the below documents and certificates 
passport
Ielts certificate
Canada Cards
United States Cards
Student Cards
International Cards
Private Cards
Adoption Certificates
Baptism Certificates
Birth Certificates
Death Certificates
Divorce Certificates
Marriage Certificates
Custom Certificates
High School Diplomas
G.E.D. Diplomas
Home School Diplomas
College Degrees
University Degrees
Trade Skill Certificates
Social Security
Validate SSN Number

mail if you need any documents

if interested contact below
peterpeddy9@outlook.com
Contact us by email peterpeddy8@outlook.com

**Comment by terryjack821** [comment]
registered IELTS & TOEFL, ESOL certificates without taking the Exams for sale 

For any inquiry send an email at:(peterpeddy3@outlook.com)
We offer our exclusive clients the ability to gain IELTS,TOEFL,ESOL
AUTODESK certificates without taking the exams. The regions we cover
are Asia ,UAE, Qatar,For any inquiry send an email at:(peterpeddy6@outlook.com)
Oman, Saudi Arabia, Jordan, Kuwait ,Australia ,Canada and Europe and The exams are taken for them
by writers who are paid to do it using the names of our clients. Our
organization is well connected with various invigilators and test
centers to allow our
writers to take the exam on your behalf. We also create ID cards with
the names of our clients to
allow the writers do the exam without problems. All our certificates
are original and British Council certified. We do not make fake
certificates! If you want to make IELTS,TOEFL,ESOL AUTODESK
CERTIFICATES Without Attending Exam.
buy ielts books
buy ielts certificate in dubai
buy ielts score
buy ielts self-study books and materials
buy ielts practice tests
buy ielts book online


if interested contact below
peterpeddy3@outlook.com
Contact us by email peterpeddy8@outlook.com

Skype:::::::::::::::::::::::::::::::::::::::::::::::::::::: online.service75


we provide the below documents and certificates 
passport
Ielts certificate
Canada Cards
United States Cards
Student Cards
International Cards
Private Cards
Adoption Certificates
Baptism Certificates
Birth Certificates
Death Certificates
Divorce Certificates
Marriage Certificates
Custom Certificates
High School Diplomas
G.E.D. Diplomas
Home School Diplomas
College Degrees
University Degrees
Trade Skill Certificates
Social Security
Validate SSN Number

mail if you need any documents

if interested contact below
peterpeddy9@outlook.com
Contact us by email peterpeddy8@outlook.com
