### ISSUE TITLE
Ghost Inspector for Local Testing Documentation

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#872]
Ghost inspector is working for non-authenticated live testing sites. It's a really cool suite of tools (ghostinspector.com). I'm going to work on getting this product up and running for Vagrant testing and document the steps needed to get it up and running. Here are the steps: 

- [ ] Setup install
- [ ] Demo video for ELMSLN testing
- [ ] Document steps

**Comment by mmilutinovic1313** [comment]
Updates: Local testing is possible, however ngrok (the "address spoofing" system) seems to try to redirect to our online.elmsln.local addresses. I talked to someone at Ghost Inspector and they recommended using the 'private firewall address protocol': `./ngrok http -host-header=rewrite private.mycompany.com:80`. I tried this out and it does redirect to our local ELMSLN instance, however when it tries to run the tests it tries to access online.elmsln.local as an address on the web. There seems to be a way to point it away from trying to access this URL on the live web, which is done with the following command `./ngrok http foo.dev:80`. This however hits into our Apache page and we get the same Apache error page you get when you access the vagrantfile's address of `http://10.0.18.55/`.

**Comment by btopro** [comment]
that's cause they share ip addresses and the default when it doesn't know what to do is to serve online.elmsln.local from apache

**Comment by mmilutinovic1313** [comment]
Ah okay - I was thinking it might be because it didn't have the vagrant credentials piped through. Do you know of a way (or at least a direction to research) that I might be able get it to know where to serve the address from?

**Comment by btopro** [comment]
might need like a 'test-this.sh' router or something that points at like testing.elmsln.local and then actually delivers the right place. dono we'll have to look deeper most likely.

cdn1.elmsln.local should be able to hit every stack and serve it up (technically) if you go to paths like cdn1.elmsln.local/courses/sing100 and see what happens

**Comment by btopro** [comment]
Documentation on how to use this (with a real server we'll say) would be nice to know and you can use online.do1.demos.elmsln.org/user (institute sponsored public demo) as a space to run the tests against since it's public
