### ISSUE TITLE
Drush Can't Find New Drecipes in Innovations (Wildwest)

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#874]
Running a `drush @site cook innovation.drecipe` is unable to find the recipe that is within the wildwest folder. It seems like we would need to specify the target every time we want to run the recipe. Could / Should we include something in Wildwest that allows for the drecipes in each innovation to be added to the ones that the system knows about? i.e. make anything under the `/home/vagrant/elmsln/config/shared/drupal-7.x/modules/`directory accessible via drush recipes?

**Comment by btopro** [comment]
so the module needs enabled for drush to be able to find it without a force fed path `--dr-locations` is a property you can pass in.

**Comment by mmilutinovic1313** [comment]
Ah okay so this relates to the https://github.com/elmsln/elmsln/issues/845 issue.

**Comment by btopro** [comment]
yeah; it'll look something like `drush @site cook innovation --dr-locations=` whatever path

**Comment by btopro** [comment]
documentation related so closing
