### ISSUE TITLE
HAXCMS for student portfolios and micro-sites

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#878]
Would it make sense to have a workflow in place where we can include student's repos into a structured and controlled repo via git modules?

The way I'm picturing it is that we'd just include their git repo inside the equivalent of a "posts" folder within a grav site as a submodule. I can build this fairly quickly on git myself with a Jekyll site, but I don't know how it would work with grav since grav uses php. This is somewhat inline with how ELMSLN isolates parts of drupal and symlinks things into place.

Might be a good balance of control over display of content and allowing students to change their content without the need for a cms?

**Comment by btopro** [comment]
To clarify for others, Grav is a CMS; just a database-less one that's a hell of a lot easier to manage at a code level and could easily be pealed off / scaled as it's database-less

https://getgrav.org

**Comment by btopro** [comment]
There is no timeline for adding this currently but it's definitely an exciting possibility. Maybe I could show how I've been playing around with Grav on our Wed hangout. It's extremely promising and I think a wordpress killer potentially (for the bulk of wordpress use cases which is simply, single user blog)

**Comment by paulhibbitts** [comment]
A couple of thoughts to start things off with...

One of the nice things about Grav is the range of granularity you have when it comes to Git repositories sync (i.e. site/user/pages/etc.). I've been experimenting with just syncing the 'pages' folder, so on GitHub there is almost a pure content (i.e. book) presentation:
/grav-course-hub-starter-kit
http://hibbittsdesign.org/coursehubstarterkit/

Is this somewhat similar to what you were thinking of @michael-collins? Multiple user 'pages' folders could be also synced to one repo, etc.

I would also be interested in hearing a bit more about the goals of this possible approach, i.e. system agnostic content, use of industry tools, open content, etc.

In terms of workflows, this is a very interesting question. Are you thinking of exposing the workings of Git/GitHub to the students or entirely keeping it in the background? Thinking about the latter, I wonder if a student could work on their Grav site on a single server, but have the ability to 'push' updates to a public GitHub repo? This is not that great from a development standpoint but could be a nice way to gather students work in one larger repo for example, and make open content re-use more likely, etc. Might this plugin also be helpful? https://github.com/getgrav/grav-plugin-github

Conversely, if we went for a full staging ->GitHub -> development server approach I wonder if a 100% online IDE + GitHub + Auto Deployment could be fully automated @btopro? As you have seen me tweet about, SourceLair + GitHub + Deployment Service is the closest I've been able to piecemeal together myself but that relies on external services, etc.

Looking forward to hearing everyone's comments.

**Comment by michael-collins** [comment]
@paulhibbitts Yup, that's pretty much what I was trying to describe. I'd like to see us eliminate git from the workflow for students while enabling them to take advantage of github's benefits. I think building on github from day one will make it easier to enable students to take over ownership of their portfolio sites when they graduate as @btopro has described. There is a winning combination of tools in there somewhere...

**Comment by paulhibbitts** [comment]
So @michael-collins, the preferred scenario might be working with Grav on a single server, with automatic 'mirroring' of the site on GitHub as a first-phase type of thing? I'd dig that, but with one additional wishlist item: automatic syncing of GitHub changes (when approved only) to the server - ok @btopro is that just a dream or not?

**Comment by btopro** [comment]
@paulhibbitts single server that we control because @michael-collins concern (and mine) is support if someone takes too great an ownership of their site prior to really understanding then you don't want to be debugging 300+ people's git files in order to generate their submission of work website :).

As for the auto syncing thing that's really not that hard. Push to github, setup a webhook which then pushes a notification elsewhere, notification validates it and then does git pull origin {whatever}. We have this workflow a few places

**Comment by paulhibbitts** [comment]
@btopro So that sounds really good, but does that also include syncing (on pull request approval) GitHub changes back to single server?

**Comment by btopro** [comment]
ya that's what I'm describing (poorly). You make change push to git (or PR). Github then sends a webhook notification to the single server which then validates that a change was made and does a pull of that part of the repo overtop of itself.

**Comment by paulhibbitts** [comment]
Ah, ok then very good! What type of tech stack would be required? I've tried to piece together some sort of GitHub -> server sync myself but it was requiring Ruby and other things way beyond my PHP hacking abilities :-) Could what you describe be done with Grav plugins + GitHub repo + Webhooks?

**Comment by btopro** [comment]
@paulhibbitts in another thread, yes

**Comment by btopro** [comment]
@paulhibbitts aaannnnd the death of a cool idea -- slivers of paid on top of 99% free will only incentivize the keeping of really great capability in that 1% which eliminates incentive for others to participate in it ;)

**Comment by paulhibbitts** [comment]
If that aligns well with your own needs then that would also be a fantastic deployment tool for many other Grav users, including me and the audience for my Grav Course Hub project 🙂 My plan is to keep requirements for all my Grav work to free open source versions, but also take advantage of for-fee plugins as users may decide.

**Comment by michael-collins** [comment]
Here is a harder question. What will be around 4-8 years from now? Potentially, students going through the online degree program may not graduate until 8 years from now. Will whatever version of grav we start with be viable to deploy in 8 years? I ask because Jekyll made breaking changes in 3.0, so if I try to regenerate my Jekyll 2.0 git pages course site after a certain date, it will fail without a lot of content revamping. So, abstracting things in a sustainable way so students never have to deal with all the technology changes is a major goal. I'm assuming github will be around in 8 years. Jekyll and Grav may not.

**Comment by btopro** [comment]
Jekyll / Grav will be around / still work. I agree w/ the git abstraction aspect. Maybe Grav is the way people can edit stuff in a grav multi-site and you have them hook stuff up to a repo but they can't push anything back / the only thing synced is the pages section. If they modify on github they could push back (again, just the pages section) but we could allow more of a export button for snagging their whole site as a Grav package. We'd also have "Here's a site in Grab XyZ" and maybe XyZ isn't the latest but hell, it all still works and they have ownership and control over it which were the ideals intended.

Also @michael-collins you still need to see the guts of grav to know why I'm pushing it suddenly ;)

**Comment by paulhibbitts** [comment]
I'd actually say Grav is more likely to be around than GitHub, as GitHub is actually a private space/company but we view it as public 😉

To me the key here is the flat-file nature of Grav. Content remains external, and in formats that are widespread, so if Grav actually left the scene tomorrow moving over to another similar system would be pretty feasible. Counter-example to me would be if WordPress left the scene tomorrow I tend to think migration would not be so simple... I look at Grav as being pretty content agnostic.

**Comment by paulhibbitts** [comment]
@btopro Are you leaning towards a Grav multi-site architecture? Right now the main elements are there but lots of issues remain and I've decided to stay away from it for now. With very reasonable server requirements would a Grav install per-student be something that is feasible?

**Comment by btopro** [comment]
@paulhibbitts yes on the multisite but because of file space more so then actual management. current package on my test site is 34 megs. multiply that by ~1200 students and that's 40 gigs. Quite a big payload and also a strain on APC / opcache systems (blog post about this when I optimized our code base in elmsln to a clustered multi-site setup https://drupal.psu.edu/blog/post/dslm-multi-sites-steroids )

This is why students would be given access to manage their pages via git / something not requiring Grav but then could hit export or something and we could basically peel off their part of the multisite, zip it up and ship it off to them. If done the right way we wouldn't even need to do that, could just say "copy this part here" and let them clone the actual system itself minus the multi-site'ed content similar to your skeleton thing

**Comment by paulhibbitts** [comment]
@btopro Multi-site is still a work in progress with Grav, not so much at the core level but at the Admin Panel (re: installing components, editing pages, etc.). I could not get it going myself but I know others have (again, in the core but not Admin Panel). Grav 1.1 is in beta right now, perhaps once that gets out the door the state of multi-site and the Admin Panel could be re-assessed. Sounds like this could be a blocker issue for your plans though...

**Comment by btopro** [comment]
@paulhibbitts no I think it's in our timeline just fine, we're not talking about doing this tomorrow, we're looking to align with communities that take us in the right direction and are well written. This is a system that needs to last 10+ years on auto pilot if needed and we'll start approaching that target in the next year or so (as it sounds grav will as well). Or we'll just contribute to Grav to make it happen when we need it.

**Comment by paulhibbitts** [comment]
More time would be excellent, as that also gives me to a chance to try out multi-site myself as things get further developed with the Admin Panel, etc.

**Comment by btopro** [comment]
kbjr.github.io/Git.php/ on system file permissions, making a simple callhome.php type of file that looks for a token passed via URL (meaning the repo is safe to pull) and then running the git.php stuff to issue the pull. Then setting up in github webhooks that per commit send a message to your path with the token in place

**Comment by paulhibbitts** [comment]
Thanks for sharing that. Maybe a future how-to post for you 😜 ? I'd love to see a working example to learn from at some point.

BTW, I followed up on the status of Grav multi-site and it looks like improved support in Grav core re: Streams in 1.1, but additional Admin Panel support not likely until 1.2, 1.3 etc.

**Comment by btopro** [comment]
https://github.com/hibbitts-design/grav-skeleton-eportfolio-blog

**Comment by btopro** [comment]
exists. We just need more and better themes which are things in haxcms queue
