### ISSUE TITLE
Accessing Vagrant Install

### ISSUE THREAD

**Issue by kfurst** [elmsln/elmsln#89]
I'm unable to access my local/vagrant install of ELMS LN at online.elmsln.local. After @btopro helped my access it the last time (issue 75?? I think), came back the next day and get at "ERR CONNECTION REFUSED" message in my browser. Virtual Box shows elmsln-vagrant as Running normally. Tried retracing my steps in terminal with no luck. 

Since I'm not familiar with Vagrant, I don't have an idea of what services to check/restart as I would in my normal lamp installs.

**Comment by btopro** [comment]
try to ssh into it; go to the directory its located in and do `vagrant ssh` to see if you can get in. What environment are you running? Win or Mac?

Also did you modify your local /etc/hosts file?
try to issue `vagrant up` from the directory its installed in, this can help debug / get it turned back on; at a high level this doesn't sound like an elms issue but more a vagrant issue (again at a glance of the details)

Also, are you running other vagrant / virtualbox VMs? This can cause issues some times w/ networking in general in vagrant since it's provisioning (fake) IPs from the VM and then your /etc/hosts is repointing browsers to look in this location. Chrome/Firefox is also generally better at reading this file then other browsers from anecdotal testing.

**Comment by kfurst** [comment]
1. Running OSX 10.9
2. Modified hosts file. Screenshot below. 
3. Running a single VM just for this project. Attached results in screenshot below. 


![screen shot 2015-06-03 at 9 07 23 am](https://cloud.githubusercontent.com/assets/10422744/7961926/18ac890a-09d0-11e5-84f6-771c84741f09.png)
![screen shot 2015-06-03 at 9 05 39 am](https://cloud.githubusercontent.com/assets/10422744/7961928/18aeedb2-09d0-11e5-97c7-89ab73c86d27.png)
![screen shot 2015-06-03 at 9 04 08 am](https://cloud.githubusercontent.com/assets/10422744/7961927/18ad32c4-09d0-11e5-9264-c4266ee20068.png)

**Comment by btopro** [comment]
Two things to try (cause our UX lead is also experiencing this and I can't replicate). Are you able to ssh in? if you are try restarting apache from in there: `sudo /etc/init.d/httpd restart`

**Comment by kfurst** [comment]
Restarted Apache and then received error for accessing MySQL. Do I need to restart the sql service too? 


![screen shot 2015-06-03 at 9 19 35 am](https://cloud.githubusercontent.com/assets/10422744/7962944/edd43a10-09d5-11e5-88d4-578c2a292e35.png)
![screen shot 2015-06-03 at 9 52 19 am](https://cloud.githubusercontent.com/assets/10422744/7963011/3b3a5cbc-09d6-11e5-8ae9-15dccfa7f1c2.png)

**Comment by btopro** [comment]
`sudo /etc/init.d/mysqld restart`

What kind of specs do you have on your mac? I haven't experienced this issue myself but might be something for me to put in the vagrant routine to ensure mysql/apache reboot at the end just to be sure.

**Comment by kfurst** [comment]
Yeah.... that sql restart did it. Any idea why those service restarts were needed?? (i.e. I'm wondering about how I should managing/closing the Virtual Box install when I'm not working on this.) Here's the specs. I said earlier I was on 10.9. I forgot I updated this laptop to 10.10 recently. I only mention that b/c 10.10 has occasionally been buggy on a couple of things. 

![screen shot 2015-06-03 at 10 17 08 am](https://cloud.githubusercontent.com/assets/10422744/7964356/eefd80d4-09dc-11e5-9101-b927571529bd.png)

**Comment by btopro** [comment]
ooooooo I wonder if this is something w/ 10.10. @michael-collins what version are you running of OSX?

I added mysql / apache reboots into the end of the vagrant install routine though this might be a vagrant / server rebooting issue. I wonder if when OSX 10.10 suspends the VM and you go to bring it back up if it does something where it's shut off its services or something.

Anyway, glad you were able to get it up and you've got the two commands in the event there's an issue like this :)

**Comment by michael-collins** [comment]
@btopro Running OSX 10.9.5, 16 gigs of ram, SSD, discreet video card...

**Comment by btopro** [comment]
was able to reproduce; we might need something that when you ssh into the VM that it restarts apache / mysql. What can happen is that if the networking bridge fails (meaning the sharing of your VM's "internet" with the host machine) it appears to halt at that point in time during the spin up. Core services running on the server don't all start and you get the issues shown here.

**Comment by btopro** [comment]
@bradallenfisher can you make a thing that when you ssh into vagrant it restarts mysql and apache? You did it for nittany-vagrant w/ the wizard script but i forget how (and it gets u a commit :))

**Comment by bradallenfisher** [comment]
Nice.  Like every time or on first ssh?

**Comment by btopro** [comment]
@bradallenfisher I think every time; it's not really going to hurt anything and could resolve confusion associated w/ networking issues. I was able to replicate this when the local internet connection crapped out during a vagrant up that was restarting the box. In this instance it seems to scrap part of the reboot routine which involved apache resuming so it would resolve the issues that both @kfurst and @michael-collins experienced as well as have fixed it for me too :). It would add all of 5 seconds to vagrant ssh process and ensure an extremely confusing / "hands up I quit" style issue was removed from the project

**Comment by bradallenfisher** [comment]
Gotcha.  One more question.  Up or ssh?

**Comment by btopro** [comment]
how about this; it would make sense for on provision / up BUT; this problem happens DURING UP sooo.... don't think that'll help :). How about testing if apache or mysql are running during ssh, if they aren't, THEN restarting them. This way it's only restarting them if they've stopped running and there's never a reason for them to stop running.

**Comment by bradallenfisher** [comment]
https://gist.github.com/bradallenfisher/e605c355a03ec27f8ca7
