### ISSUE TITLE
Visuals for #500

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#897]
@mmilutinovic1313 docs look good for describing the parts of the edit UI, might be nice to have a few screenshots especially just for like clicking into edit mode. Something a bit easier to kind of glance at with the text. Not TOO many visuals though since we always end up updating things

#500

**Comment by mmilutinovic1313** [comment]
Sounds good to me. Will this go in the .md file? Or somewhere else?

**Comment by mmilutinovic1313** [comment]
I found this: http://stackoverflow.com/questions/14494747/add-images-to-readme-md-on-github

I'm going to post the screenshots in this issue then and link them to the .md file (as recommended in the 'best answer' here. We can then add these images to the docs site if desired.

**Comment by mmilutinovic1313** [comment]
![authoringinformation](https://cloud.githubusercontent.com/assets/7243665/15226542/1ef44a7e-1851-11e6-9c54-b19dd8375300.png)
![bookoutline](https://cloud.githubusercontent.com/assets/7243665/15226544/1efab454-1851-11e6-941b-5404d0f40a32.png)
![hidecontent](https://cloud.githubusercontent.com/assets/7243665/15226543/1ef9ddb8-1851-11e6-8361-19846f60aee8.png)
![navblock](https://cloud.githubusercontent.com/assets/7243665/15226546/1effe686-1851-11e6-8f33-bff7d77a52ea.png)
![publishinginformation](https://cloud.githubusercontent.com/assets/7243665/15226549/1f026a14-1851-11e6-8a33-19eee1a7efff.png)
![revisioninformation](https://cloud.githubusercontent.com/assets/7243665/15226545/1efdda9e-1851-11e6-9822-241debd3a3f2.png)
![tags](https://cloud.githubusercontent.com/assets/7243665/15226548/1f027cd4-1851-11e6-9571-15757de5235f.png)
![visualidentifiers](https://cloud.githubusercontent.com/assets/7243665/15226547/1f01d57c-1851-11e6-87a9-592150e08ac8.png)

**Comment by mmilutinovic1313** [comment]
![editbutton](https://cloud.githubusercontent.com/assets/7243665/15226622/7d6ba5fc-1851-11e6-8498-6f7d8b3747d1.png)

Edit Button one
