### ISSUE TITLE
visualize LRS data in CIS

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#900]
Work plan:
- [x] Make a boilerplate materializecss .php page http://materializecss.com/getting-started.html
- [x] Connect this static file from a VM to our learning locker instance on the Vagrant data bucket (credentials given once we have the prototype)
- [x] Query data and print the result (to suggest it's possible, I know it is)
- [x] Filter a query based on a role being student (which we've got put in via our custom metadata)
- [x] Filter a query based on a section being master (which we've got put in via our custom metadata)
- [x] Query for the responses left on a specific h5p activity
- [x] Filter a query based on a course (which we've got put in via our custom metadata)
- [x] Filter by date range 
- [x] Filter by user / users (manual selection beyond just role filter)
- [x] Filter by program if in cis
- [x] Filter by last x results only

- [ ] CIS data slice for Offering centric (so multiple sections)
- [ ] CIS data slice of any url / item specifically
- [ ] Query for the last page they went to in the course
- [ ] Query for the last video they watched (which title / link is in our custom metadata for where it was)
- [ ] Query for the latest data point, visualizing what they did, when, and where (w/ link back to it)
- [ ] Query for the amount of time spent in the course (duration values most likely for page view, newer data value only)
- [ ] Query for the amount of time spent but only in a subset of pages (course specific)
- [ ] Make debug mode available on the interface
- [ ] Make a mode that exports the current dataset as csv
- [ ] Make a mode that exports the current data set as a php query array for future dashboards

**Comment by btopro** [comment]
http://docs.learninglocker.net/statements_api/

Need to use the aggregate command and it would be nice to provide some kind of cleaned up filters

**Comment by btopro** [comment]
Look at https://www.drupal.org/project/views_json_query to do the JSON parsing

**Comment by btopro** [comment]
@proconnor15 I made some checkbox stuff above; make this it's own repo on your own github profile, this is entirely for prototype purposes

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/issues/871
https://github.com/elmsln/elmsln/issues/421

**Comment by btopro** [comment]
@proconnor15 next time we get together let's talk about a slight change in scope. I think it'll make things more manable. Basically instead of mining specific queries, I want you to think of what your working on more as a raw query builder / viewer. Target audience would be someone like @rickhumphries / @kat-wehr / @kmiffitt / ID audience who could be given a consol to click through and as they click through what they are looking for it displays the data for them (so simple query engine for reports / things we don't have automated) but also could present the query needed to accomplish this output. This would be something that could be sent tot he development team as is and be immediately useful.

**Comment by proconnor15** [comment]
Sounds good. I can come in Monday, unless you are in the office tomorrow, that would work too

**Comment by btopro** [comment]
Sooooo many things working now in here!

**Comment by btopro** [comment]
https://www.elmsln.org/blog/post/data-visualization-sneak-peak

**Comment by btopro** [comment]
https://www.webcomponents.org/element/Collaborne/d3-progress-meter
https://www.webcomponents.org/element/PolymerEl/multi-verse?code=ac88b178e5871e0a8f8e
https://www.webcomponents.org/element/saeidzebardast/nvd3-elements/elements/nvd3-multi-bar

Dumping some elements to explore for this. Would like to talk to @kat-wehr and @kmiffitt about how we could possible use the multi-verse element (2nd link) to make better meaning of data. Basically it lets you see multiple charts at once and then isolate in one which updates the others. I could see having the big list of all statements that exist, a pie chart of verbs be another, histogram of dates of when statements showed up etc. Some form of allowing people to isolate the data they are looking at which could help us in making better meaning of what's there.
