### ISSUE TITLE
Test php 7

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#901]
It's still a bit early for this but it would be great to get more testing of the system while running php 7. This is mostly getting vagrant up and going, then upgrading php to 7, then start screwing around and see if anything happens that shouldn't.

This patch provides support for php 7:
- https://www.drupal.org/files/issues/drupal-2656548-21-php7.patch
- https://webtatic.com/packages/php70/

I've played with this in vagrant and it works but we need additional testing for sure since this is a major leap in php. it's pretty insanely fast.

**Comment by btopro** [comment]
https://www.drupal.org/node/2656548#comment-11148293

**Comment by btopro** [comment]
/var/www/elmsln/core/cores/drupal-7

**Comment by mmilutinovic1313** [comment]
(y)

**Comment by mmilutinovic1313** [comment]
don't update to php-7 but apply patch

**Comment by mmilutinovic1313** [comment]
Applied the patch and ran a few tests to see if the patch broke anything. I did not notice anything breaking - so I issued a PR.

**Comment by btopro** [comment]
Cool, as this is going to get into drupal core at some point and we won't be implementing PHP 7 support natively for some time I'm going to close this and not accept the PR but let it finish it's travis build to see what travis says. This was the point though so good work :)
