### ISSUE TITLE
Pages showing hidden in course outline

### ISSUE THREAD

**Issue by juststormy** [elmsln/elmsln#908]
In Chem 202, page is showing as hidden, even though it was unhidden in both the page controls and outline designer. https://courses.ed.science.psu.edu/chem202/admin/content/book/2
![2016-05-18_1015](https://cloud.githubusercontent.com/assets/1186260/15361931/8ef5280e-1ce1-11e6-9819-57efc487cd3e.png)

**Comment by btopro** [comment]
menu caching issue. Resaving the page gets rid of the icon

**Comment by btopro** [comment]
reviewing this course I'm not seeing this issue anymore. we did correct menu link generation at one point, let me know if it pops up again
