### ISSUE TITLE
data visualizer for http traffic

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#909]
look for data visualizations for http requests. Something like http://logstalgia.io/ but not (or http://logstalgia.io/ if you can get it working on an ubuntu server if you have one). It needs a graphics card to run so we're looking for something that can visualize traffic, in real time would be even more ideal.

**Comment by mmilutinovic1313** [comment]
I think we still have that server somewhere where we were doing some initial testing. I'll try to find the creds. for that and maybe we can test it out on that site. I also might be able to use my webspace for it as well.

**Comment by mmilutinovic1313** [comment]
Additionally -- I have found this http://gource.io/. Which is by the same group that made the logstalga software. It's for visualizing git. Although I don't know if that's something we need, it could be cool to have and maybe useful down the road.

**Comment by btopro** [comment]
killed it due to budget but the issue is that it needs a graphics card whatever it is
