### ISSUE TITLE
Creating or Editing Roles 

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#910]
I'd like to change the scope of the staff role for our instance, or create a new role perhaps, since for us the staff role is probably below 'teaching assistant' in terms of escalation and should be able to get access to all courses but not be able to change content (which would instead be the job of a 'staff editor' or something). 

I've read the docs but I'm still not sure on the best way to go about doing this. And wouldn't be massively confident using features to capture it. I'm happy enough creating a new user role in CIS and setting permissions, but should I be doing anything special for courses/services so that the role and permissions are set on course creation and are applied to all services of that course etc.?

**Comment by btopro** [comment]
hmmm... so the best way (thinking out-loud):
- Make a new role in one course site
- Set some baseline permissions like being able to access content
- Make a feature that's like buttercups_tweaks
- Export the role and JUST the permissions tweaks for that role (I think this is possible)

Don't know if this would do exactly what you need gets you in the neighborhood to ask questions off of.
Another thing you could do is use the guest role. Guest currently just has access to places but can't do anything in them.

**Comment by rickhumphries** [comment]
Ok thanks, will look into this and report back

**Comment by btopro** [comment]
re-open if issues
