### ISSUE TITLE
Forward caching

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#919]
When someone starts a lesson, we should kick off a request to populate the local browser cache with a json blob of the subsequent body of content areas. We could easily do this via web-services w/ display modes.

Idea. You start lesson 1, we give you the page. After page is loaded, we ask the system for the rest of the pages in the lesson (since most likely you are going to them) or at least the next and previous page. Then you click next and it just swaps out the content of that page and scrolls to the top. This would drastically reduce TTFB. Could also do this as you scroll to the bottom to kick off the message to get it in the background, think of infinite views type of stuff but it's not rendering what it grabbed

**Comment by btopro** [comment]
@mmilutinovic1313 tagging you to see if you can find any JS libraries or blog posts or anything that explores this type of concept. There's a good chance just based on our entity load / menu structure that we're loading the nodes for the lesson anyway (even if they aren't visible) and then caching the crap out of them. ask @heyMP about what the D8 thing we could steal ideas from is

**Comment by mmilutinovic1313** [comment]
So I did a cursory look for some things that could help us out with this. I've found a bunch of articles on BFCaching (Back-Forward Caching) which is similar to the idea you mentioned I believe. There is a library / extension for firefox that handles these kinds of interactions. Here are some links to this.

Overall: https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Using_Firefox_1.5_caching
Precaution with Angular: http://stackoverflow.com/questions/29635443/how-to-force-firefox-to-bypass-bfcache-for-angular-js-partials

I'll keep looking into this and ask @heyMP what that D8 thing is / was.

**Comment by btopro** [comment]
wow. that pwa thing is pretty remarkable and seems like a drop in.  Check out a demo here:

https://pwa.theodoreb.net/

Go to a bunch of pages, then open chrome network tools and simulate no internet connection (or disable wifi). You'll still be able to get to every page that you just had previously. This could be an epic win for performance both actual and perceived as it starts loading assets locally like a web-app would. @heyMP @mmilutinovic1313

**Comment by btopro** [comment]
https://www.drupal.org/project/pwa requires HTTPS to work so this wouldn't be possible in local VM until we get auto / fake certs in there

**Comment by btopro** [comment]
While fun to do and interesting, I've heard a bunch of blog posts to suggest these methods aren't as happy go-lucky as they may sound for the bulk of sysems
