### ISSUE TITLE
Automated QA / Dev servers

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#92]
The pull-down script written to so that any instance can be migrated into another would allow us to use the PSU jenkins instance to automatically pull down to staging at an interval. This would allow us to work on staging without ever needing to touch production instances (for the purposes of testing changes that bubble up from "Dev" or vagrant images).

This would also (w/ slight modification to the drush alias spider) allow us to merge _all distributed deployments back into a single deployment_. Making the management of 1 staging mirror yet everything in production be distributed possible. This would pull-down against all images and instead of blowing away the config directory, a merge would have to be executed. Then in the "college" variable which is used to target things, it would have to just look at what's available.

generate_aliases.php in the server drush group would need to have the `$group` value replaced w/ a DirectoryIterator. In doing so, we could "discover" any number of aliases _across deployments_. This would allow review and testing of _real_ (fake) instances prior to pushing code up without having to test each one manually (via pull down or pulling single DBs).  If all the theory behind the grouping operator is correct we could pull all the configs together and their local modules would be in-tact (aside from the occasional name / version conflict that is almost improbably / wouldn't matter for the purposes of staging).

_giddy_

**Comment by btopro** [comment]
- [ ] make a jenkins bash routine that can loop through and pull each into staging
- [ ] make generate_aliases.php NOT require the $group value in order to work (really nothing outside of install should)
- [ ] make pull-down have a mode where it merges as opposed to overwrites

**Comment by bradallenfisher** [comment]
Do we have a server for this? If not can we request one?

Should we start with one that is a clone of ELMSLN-AANDA with less specs?

**Comment by btopro** [comment]
ELMSLN-Staging exists and is kind of just hanging out. @heyMP can chime in if he's used it for anything but I'm pretty sure it just needs some stuff wiped out since it's got a much older version of elmsln / apache / mysql / php needing completely reinstalled so we know the settings.

**Comment by btopro** [comment]
if there's a priority of some kind, this should be higher then ohter things imo so we can test more rapidly and move towards migration for spring

**Comment by bradallenfisher** [comment]
Agreed. I started looking into to this over the weekend. Hardest part will be mysql compatibility. We may have to do some scripting to pull usernames for dbs since an all database dump won't match the tables between mariadb and mysql 5.1

**Comment by btopro** [comment]
#1454 successor issue to this one
