### ISSUE TITLE
Dockerized git / markdown production workflow

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#922]
we've been kicking around decentralized knowledge production a lot lately and I think @heyMP has stumbled on something that might make it a reality. If we make (basically) an automated / docker based method of getting things like Hibbits Course Hub, refine the build experience a bit and the shared folders / commit workflow, we could easily have a full server that ppl think is just an application.

The goals of the Application
- make it easy to develop course content / materials offline
- do it in markdown
- automate setup
- automate commit / PR / associated workflows

Then on the other side our git book / git schema ingestion stuff could be hooked up to this workflow so that the faculty member is effectively sharing / directly participating in the process w/ tools that empower instead of force workflows like Word Docs and copying and pasting into crappy next editors.

Thoughts?

**Comment by paulhibbitts** [comment]
Are you thinking this would include staging and production server type of setup too, or just one server? Sounds like you are thinking two, with one local, but wanted to check that!

**Comment by btopro** [comment]
I'm thinking stand alone that you could click and get a fully setup grav space w/ nothing else to do. The workflow w/ us involves faculty making things in a separate space. The workflow for what you are describing I think we're talking all the initial development work which you would push to a remote location via VC at some point or hook up via a little built in UI

**Comment by paulhibbitts** [comment]
Sounds good, looking forward to seeing where this might go!

I am still exploring other deployment options myself, to make it easier (given my current toolset) to help other instructors get going with Grav.

**Comment by btopro** [comment]
gitbook thus far seems the better option for this, especially as we have the import workflows at least starting to refine
