### ISSUE TITLE
hide admin menu causes goofiness w/ backticks

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#93]
granted we don't type them frequently but this is a pretty funny example of how annoying this is if you needed to:

https://github.com/backdrop/backdrop-issues/issues/970#issuecomment-109307508

While not a huge issue today, @michael-collins wants to support markdown which uses the ` convention for the code off-set style which is nice to use even when not specifically for traditional code.

**Comment by btopro** [comment]
This bug is with admin_menu_dropdown module; will be curious to see how backdrop approaches this issue because it's possible they provide a better solution to it that we could backport (well... sorta sideport I guess..) into foundation_access outright; especially since we've talked about having a hot key that collapses the contextual awareness bar

**Comment by btopro** [comment]
@mmilutinovic1313 if you could look into how to resolve this; it's not specific to elmsln, it's related to admin_menu -- drupal.org/project/admin_menu

**Comment by mmilutinovic1313** [comment]
Issue is fixed. Submitting patch to d.o.

**Comment by btopro** [comment]
@mmilutinovic1313 reroll the patch instead of adding in the diff of the other patch. Reset repo, make change, then create a patch from it

**Comment by btopro** [comment]
closing out since it's fixed on our side but please follow up w/ that project still
