### ISSUE TITLE
minor bugs to track down

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#931]
viewing a node in mooc after applying simplify (dono if that's the cause tho) node/169
Message	Notice: Undefined index: format in wysiwyg_pre_render_text_format() (line 222 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/wysiwyg/wysiwyg.module).

`admin/structure/features/mooc_ux_defaults` path in mooc
Message	Warning: Invalid argument supplied for foreach() in features_override_module_component_overrides() (line 230 of /var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/features_override/features_override.export.inc).

very low priority but worth noting when we get in squashing mode

**Comment by mmilutinovic1313** [comment]
Gonna check this out today as I'm in bug squashing mode

**Comment by mmilutinovic1313** [comment]
Hmmm I'm not seeing this error when I try and view a node. Checked to see that simplify was enabled. Any other modules that should be enabled or disabled you think?

**Comment by btopro** [comment]
neither one? there's 2

**Comment by mmilutinovic1313** [comment]
Yeah for whatever reason — when I got to the path `http://courses.elmsln.local/sing100/node/(nid)` I don’t get either of those errors

**Comment by btopro** [comment]
and simplify is applied?

Also the other path is `admin/structure/features/mooc_ux_defaults`

**Comment by mmilutinovic1313** [comment]
Yep yep -- I am going to clear caches and such to make sure. Maybe I can mess with the settings and in simplify and see if that's why you saw something?

**Comment by mmilutinovic1313** [comment]
Ah I got the second one after clearing caches and going into the `Review Overrides` section. Still can't seem to find the issue with `/node/(nid)`

**Comment by mmilutinovic1313** [comment]
Should this line:
 `if (!isset($normal_copy[$name])) {`
be:
 'if (!isset($default_copy[$name])) {'
instead?

**Comment by mmilutinovic1313** [comment]
Oh I see! It's if the normal_copy is not set for the $name (i.e. it doesn't exist in that prior foreach) we add it.

**Comment by btopro** [comment]
Sounds like a Good thing :)

Maybe submit that patch to the features_override module if it resolves that 1 notice on cache clear

Wp8
________________________________

**Comment by mmilutinovic1313** [comment]
I'll add this to their issue queue then! Shall I put the patch in our folder for the module as well?

**Comment by btopro** [comment]
nice work @mmilutinovic1313
