### ISSUE TITLE
`field_section_number` not auto-populated in Course JSON data 

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#932]
When creating a new section a `field_section_number` is not generated and does not appear in the JSON that is being called by the Angular

**Comment by btopro** [comment]
if u don't include a section number then it wont be there, are you saying we should require it in some way?

**Comment by mmilutinovic1313** [comment]
Yeah I'd say it should be required as we pull data that uses this field to populate the cis-dashboard Sections content pane. Also I was having a hard time finding where you can add section number. But I'll look again.

**Comment by btopro** [comment]
is this an issue or a misunderstanding about where that property came from?

**Comment by mmilutinovic1313** [comment]
I think this is more of a misunderstanding of where the property came from.

**Comment by btopro** [comment]
ok, I'll close out then as I think you've got this stuff squared away now
