### ISSUE TITLE
Support for Non-Latin Characters in Text Fields

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#933]
We likely will need non-latin character support. Especially for those instructors teaching language courses.

**Comment by btopro** [comment]
where's an example that this isn't the case?

**Comment by mmilutinovic1313** [comment]
Actually this isn't true. The Textbook editor says that it doens't have latin-character support in the description. Perhaps we could remove that notice or something son that designers don't worry about this message.

**Comment by mmilutinovic1313** [comment]
This can be closed
