### ISSUE TITLE
document patch to quiz_ddlines

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#939]
https://www.drupal.org/node/2743551

**Comment by btopro** [comment]
@mmilutinovic1313 clone the version from drupal.org. Overwrite their js file with ours from master branch. Submit as a patch (it's a 1 line change and then it supports better versions of jquery)

**Comment by mmilutinovic1313** [comment]
Should be good to go pending they merge my patch. PR is in in our system .
