### ISSUE TITLE
Angular components codepen starter

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#940]
Hey @mmilutinovic1313 is there a way to have a code pen template that people can fork for making UI components? I don't know enough about Angular, but we've got one for foundation that works pretty well. @heyMP Thoughts?

**Comment by mmilutinovic1313** [comment]
Hey @michael-collins can you send me the example for foundation? I'll do some research to see if we can do this. I've been using your template visually (http://codepen.io/michael-collins/pen/JYWBvP) to build out everything I've done via angular.

**Comment by michael-collins** [comment]
http://codepen.io/heyMP/pen/KdyKgK

**Comment by mmilutinovic1313** [comment]
Here is a start with the components we have thus far...The big issue we have with Angular stuff will be populating the content with fake data. i.e we would need JSON data for the angular to interpret in order to display certain components.

http://codepen.io/mmilutinovic1313/pen/pbjgwY

**Comment by mmilutinovic1313** [comment]
I added some more of the external libraries we had for Foundation Access and got it looking a little bit better. I can't seem to figure out why some of the button images load while others don't load...

**Comment by michael-collins** [comment]
It looks like @heyMP is using material icons. Those are the ones not loading. The fi icons are working,

**Comment by michael-collins** [comment]
There are a lot of these in there:   <i class="material-icons">refresh</i>

**Comment by michael-collins** [comment]
Added some icon classes back, and added aria labels. Don't have the entire thing working because I don't know how angular works: http://codepen.io/michael-collins/pen/ZObdNM

**Comment by mmilutinovic1313** [comment]
@michael-collins Do we need to change the way its set up in our angular stuff? i.e. change the tags around to match this kind of icon-class labeling?

**Comment by michael-collins** [comment]
Maybe we should talk on slack/gchat and discuss. I have a codepen that I forked, will paste the link when back at my computer. Basically, there were no icon classes assigned to the icon items. If you are adding or replacing the classes dynamicallly, that's another story.

**Comment by btopro** [comment]
@michael-collins if this is in a state we can add to the documentation for themers let me know and we can point to the code pen / add it as a repo on this github group so we can point to it / upgrade it in the future

**Comment by btopro** [comment]
is this still active? I don't really understand the goal here

**Comment by mmilutinovic1313** [comment]
It's related to the goal in #978 and #405. I think it can be closed as we have made angular progress. I'll let @michael-collins confirm that though.
