### ISSUE TITLE
Revisit XAPI statement structure

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#946]
continuation of #306

Now that we've got a good structure for H5P statements going thanks to the recent patch to make it poitn the right place, let's see what other data we'd like to cram in there before my mind wanders elsewhere. Current thoughts:
- section context
- course context
- situational context (what link its embedded in when the person is taking it)

Anything else we could ship along that would be good to know so we can query after the fact? @rickhumphries @heyMP

**Comment by btopro** [comment]
easiest way to get these in via frame -- frame has properties passed down via get address (or we drill down to send them forward which is more difficult). May also want to send via # as that might not invoke a browser cache miss for URL but is still something we could read off of. Dono, we'll see.

**Comment by btopro** [comment]
proposed placement: $data['object']['context']

**Comment by btopro** [comment]
worked through https://github.com/adlnet/xAPI-Spec/blob/1.0.0/xAPI.md#miscext and came up with the following extension definitions to start.

https://www.elmsln.org/x-api/elmsln-url
https://www.elmsln.org/x-api/elmsln-section
https://www.elmsln.org/x-api/elmsln-course

screenshot showing it flowing over to learning locker though I need to make it bring along / calculate the scope properties correctly.
![2016-06-08_18-27-37](https://cloud.githubusercontent.com/assets/329735/15913280/fcfe3b62-2da6-11e6-8fd1-5b0ed172d0bc.png)

**Comment by rickhumphries** [comment]
Bryan this is awesome. I think you've covered the main extensions. One other possibility I can think of under `"object"` could include:
* elmsln-url-name - this is kind of an extension of an extension! But the page title of the url the activity is being taken in. This might not necessarily be required for querying, but could be useful for making things a bit more human readable from within learning locker nonetheless.

Also trying to think of anything else to add under "actor" that might be useful. The unique ID of the user in CIS or People maybe? Or an option within the site to specify a Drupal field that holds an internal company user ID. That might be something for me to look at later though :)

**Comment by btopro** [comment]
ha, glad you came up with that one cause as I was putting it in it came to mind too. Not super needed and not unique but useful to know especially if we are to build dashboards that don't have to keep asking elmsln for more data to populate

**Comment by btopro** [comment]
how about https://www.elmsln.org/x-api/elmsln-url-title ?

**Comment by rickhumphries** [comment]
Perfect

**Comment by btopro** [comment]
title present now; it should be noted that there's nothing to send it currently AND that these currently are only going to be reflected in H5P items that live in the media system (it is possible to have XAPI emitted from elsewhere so we'll need to shift this association in the future.

**Comment by btopro** [comment]
@heyMP you should get Glenn in on this thread before my mindlessness moves onto something else ;)

**Comment by btopro** [comment]
Kate suggested we capture the tags data field from the media system in the XAPI statement. This could be like: `elmsln-tags` or whatever. This way we could build interfaces that query and filter the data out when it's recieved without asking elsewhere.

For example the #850

**Comment by btopro** [comment]
AAAHHHHHH!!!!!!! Successfully implemented #964 and #954 so that the content is aware of frames embedded in them, passes the user's context down into the frame, the frame accepts it and resigns the XAPI request that goes out the door to include course context, section context, url and title of where the frame was embedded. As you'll see in the screenshot, we also know what media asset was used and the title of it meaning we know everything we'd possibly need to recall data in a meaningful way! This also means we can repurpose assets across courses and know where they were taken!

![2016-06-21_15-45-30](https://cloud.githubusercontent.com/assets/329735/16243866/4059535e-37c7-11e6-9371-de90370ed93e.png)

**Comment by btopro** [comment]
![2016-06-21_15-51-19](https://cloud.githubusercontent.com/assets/329735/16244027/0ef12d18-37c8-11e6-80a0-a70861e1146a.png)

looks pretty sick in production as well!

**Comment by btopro** [comment]
Add an extension for roles the user has

**Comment by btopro** [comment]
need to test role but it should be shipped along now (within reason). student, staff, teacher, other, currently based on the role groupings.

**Comment by btopro** [comment]
work. in. production.
