### ISSUE TITLE
Service "Almost there" in CIS

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#955]
So, this is pretty minor to say the least. It's not really causing any problems and the service still works (or it seems to be!) but I've set up a new course site and the status of the service is stuck on "almost there" rather than "service ready" 

![screenshot_20160610-074902 2](https://cloud.githubusercontent.com/assets/4973810/15956620/a0869eec-2ee1-11e6-998b-505ea1e04ef4.png)

Currently on v0.2.1

**Comment by btopro** [comment]
means the cronkey never shipped home (most likely) click run cron and you'll probably see that there's no key in the field

**Comment by btopro** [comment]
marking as minor tho we'll want to change this behavior (obviously). Cron key going forward is increasingly less important as we've switched (I think) all calls to run in the background (or almost all calls) instead of our old school brute force cron running via keys

**Comment by rickhumphries** [comment]
Ah yeh - the url query string is this after clicking to run cron: `/mooc/book-toc?cron_key=&force_roster_sync=`

**Comment by btopro** [comment]
steps to resolve this manually:
- goto that page that says almost there, click the title that says rsph... - courses then click edit
- in another window goto the service in question courses.whatever /{coursename}/admin/reports/status and find Cron maintenance tasks, copy the string after cron_key=
- paste this cron_key into the field that says cron_key. save it should stop saying almost there
