### ISSUE TITLE
Text and Voice Commands and on-demand interfaces

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#958]
In a complex application, typing in a command, or saying things verbally can often be much faster than navigating the interface – even a really good interface. In Rhino3D, they make it really easy to select a tool or perform an action by just typing whenever you want something, and the command console comes up and autocompletes for available commands. Can we make the equivalent of a command prompt that pops up when you hit some key, then when you start typing, auto-suggests ELMSLN commands? So instead of searching, which is lame, you issue commands, and elmsln will fetch nodes for you and filter/display them in an appropriate way on demand. Essentially, an on-demand or semi-on-demand visual interface.

If I wanted to see all the videos for the first 3 lessons and their associated assignments, I could start typing "show lesson 3 videos and assignments." Then a page of those things appears. Magically. What if I could type a command into a command prompt or ask verbally via voicecommander to do things that aren't in the primary navigation?
- **"What is the next module/lesson/whatever?"**
  - Fetches information on the next lesson, and pops up a modal window with a picture and info.
    - May require short descriptions to be written about the module
- **"What is the teacher's/instructor's/professor's email?"**
  - Pop-up with email
- "I need help [with something]" will bring up a help chat window and autofill with the thing they need help with.
- **"Show all the videos in [module]"** will generate a page with all the videos
- **"Show all videos and assignments"** will generate a page with a combination of those items
- **"let me see [student x's] and [student y's] grades"**
- **"Submit [assignment name]"**
- **"Sync the roster"**
- Etc.

**Comment by btopro** [comment]
#684 #952 #953 related as this is kind of the "xbox one" voice navigation / console mentioned in some past threads. good idea, now just do it ;)

**Comment by btopro** [comment]
OOOOOoo and if we used Aria landmarks to drive what can be spoken / trigger words we'd be making a conversational interface / console that works better for non-sighted users by default.

**Comment by michael-collins** [comment]
Is it possible to generate these on-demand remixed views of select content?

**Comment by btopro** [comment]
With effort anything is possible

Wp8
________________________________

**Comment by btopro** [comment]
consolidating this w/ the other threads so we have less ridiculous voice ideas floating around :) #956 #959 #961

**Comment by btopro** [comment]
merging into #1296 as it has conversational enhancements expressed as a concept for it
