### ISSUE TITLE
Authority: Interact

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#97]
Interact is a catch all for interactive and engaging forms of multimedia and experiences. This is envisioned as the place for h5p.org interactions among other things. This is fundamentally different from the media system in that the media system is for passive consumption of media.

Interact has a timeline component, support for H5P (which in itself is very remixable) and can be opened up to house quiz (modules) and other materials without too much of a leap.

Things that you'd like to see in an interactive multimedia system please post here.

**Comment by rickhumphries** [comment]
One tool that springs to mind are launchers for both SCORM and TinCan (xAPI) content that might be built in a rapid e-learning authoring tool like Captivate and Articulate. Not necessarily advocating their use in general (that's a whole different discussion! :)) but we have a series of branching 'Virtual Pharmacy' scenarios that are built and it'd be good to be able to report on them. I know it'd be a popular addition too.

I think there's SCORM launchers out there already for Drupal - not for TinCan yet, although there's one on github for Moodle - https://github.com/garemoko/moodle-mod_tincanlaunch
And there's a launcher that uses LTI here, which looks like it's useable, but the code and stuff isn't open source http://launcher.saltbox.com/

**Comment by rickhumphries** [comment]
I'd also like to put a case forward for Interact being an authority tool. Simply because I see interactions as being another form of media in the sense that they can be used (and possibly shared for use between instructors) over multiple courses. 

The H5P activities that we've put in Media (for now) are embedded within a course and then when the activity is complete, it sends an xAPI statement to our Learning Record Store. The activity URL that is included in the statement is the course URL, not the URL from Media - so the course that the activity was taken on is still abstracted from that.

**Comment by btopro** [comment]
@rickhumphries we use a tool called smartbuilder which is like Captivate for some learning exercises. While not using tincan (right now) they talk to drupal via a basic webservice api. So launchers would definitely be in scope there. Part of the reason to silo these interactions from the rest of the world is the eventual SCORM inclusion. I think it's possible now but I don't have a need to test it yet so we haven't gotten to it.

I'm curious as to if you have stuff in Media why you'd want to move them to a different system? @michael-collins and I have gone back and forth on the Media being a service vs an authority, only to arrive at the "well media used across would be a pain" kind of scenario. It's possible that based on some of the media considerations of interact that interact and media house some overlapping parts, media being things used everywhere and interact being course specific as a Service.

I could also see Interact being an authority, but we've had some interesting proposals for usage of it around timelines where it would really have to be a Service in order to be useful. We've had courses mentioned at MW and my local unit where the instructor would make a timeline and then students could make timelines that are like remixes of the original, or show-casing what they felt the order of events was, that sorta thing.

As you can get things to the LRS from anywhere and the anywhere will still be Drupal and you'll still know who the student is, I don't think it'll matter :) which is an awesome selling point for having automated ways of getting LearningLocker setup on install of everything (someday) :)

**Comment by rickhumphries** [comment]
@btopro yeh that's a good point. I don't really have a need to move them to a different system other than to try and stay in sync with the overall elmsln direction. I guess I just need to consider the need to hook new content types up to anything that should maybe be *required* by Media - such as the ability to associate to a course. 

I couldn't necessarily see the reason for interact to be a service before but I see what you mean in terms of those use cases though so that makes sense :) I feel convinced!

**Comment by btopro** [comment]
interact is still kinda hanging in the wings intentionally. We're allowing some of this stuff to be emergent as far as direction. Much like the CIS 1.x vs 2.x that came out of our usage, your usage and others. We position things a certain way, get reaction, build from there, but the overall structure of the network is what keeps us all sane. We could "bork" interact royally (from your perspective or someone else) and still not goof up someone's overall reason for utilizing the tool :)

Anyway, I think this is a good discussion thread but one that won't be able to push much further till Interact is a bit more pushed in a direction / actually used. At that time we could resume a "well it should be more like.." style conversation :).  Your LRS thing I think is critical though as it can change my original connotation of Interact which was "students engaging with interactive content, and we store their interactions". It could be more like the "Lab" system that @michael-collins has vaguely mentioned a need for in the past.  This would be a space for students to create but is beyond the scope of the Studio (or maybe it isn't).

This is fun :)

**Comment by kfurst** [comment]
Having not seen any of the mockups for interact, here's my three cents. 

@rickhumphries has some interesting points that totally make sense through lens of authoring for adults. If I put my ID hat on, I can understand where you're coming from. Interact seems somewhat nebulous at this point, so it is somewhat difficult for me to envision that separation (or overlap?) between what I would use media for and what would be interact. 

In the K-12 realm, I share as much excitement for LearningLocker-type integration (even if it isn't that exact tool) as he does. As we look for ways to shift out of outdated modes of assessment and evaluation and the arbitrary/meaningless data we historically rely on for student feedback, I would love to have a tool that could act as a strong lever in my organization, that integrates easily and perhaps most importantly (in the case of LearningLocker) provides the robust analytics necessary. So many K12 environments are forced to rely on disparate closed-source tools for those analytics which we then haphazardly cobble together to gain a clearer picture of student understanding. (Which then we're forced to continue to purchase at exorbitant rates). 

@btopro Here's a really dumb question: Aside from your introductory videos on the ELMS modules (and the twitpic flowchart) is there a document somewhere that I could access to better understand the some of the "satellite" modules like Interact and Studio (haven't found any info on this one). 

My big thing is that whether it is in Interact or Studio, I really need something where content/information flows dynamically both formally and informally with minimal lateral or exterior navigation. While I can throw together something in Captivate that is interactive for my staff, they aren't going to do that for their students. Instead they're going to default to what they know and what's easiest. Thus, I end up with tons of courses that are digitized versions of lecture based lockstep education. That's just not cool for a 5th grade class. So, I would like to see something that makes it easy to create spaces for interactive content that includes students creating/housing different types of media in the space. 

While they may not actually create the media in the space, I want to get teachers to have students interacting with content beyond 1. Reading text or 2. Watching a video. I would rather see ways to facilitate "application" or "creation" activities. Basically, I have secondary teachers now that upload tutorials or pdf worksheets and open a dropbox for grading. This approach does not work at all for the primary level (for obvious reasons).  I would love to see Interact offering an easy to use space + tools for creating interactives from scratch or housing mods from elsewhere. 

One question, if I were a teacher and wanted to import a mod into Interact, would it have to be SCORM compliant? Right now 100% of my teachers have no idea what SCORM is and have various interactive animations grabbed from God knows where.

**Comment by btopro** [comment]
@kfurst I tend to avoid mentioning SCORM because I don't want crappy page turned legacy material put in yet another system. People need to teach to today's learners, not the way people did in the 90s (which was just repurposing old methods of that time anyway) *end rant.

As far as the what and how methodology wise there's a lot of writings on btopro.com over the years. There's a few basic diagrams in here -- https://github.com/elmsln/elmsln/tree/master/docs/diagrams

The video on http://elmsln.org is probably the best series of diagrams / description of what these things are, why they are being positioned the way they are etc. https://www.elmsln.org/documents has two white papers on aspects of the system. Some other blog posts

https://btopro.wordpress.com/2011/03/21/structured-anarchy/
https://btopro.wordpress.com/2012/11/29/getting-out-of-the-lms/
https://btopro.wordpress.com/2013/08/18/elms-learning-network-design-philosophy-theory/

**Comment by btopro** [comment]
H5p has been moved to the ELMSMedia distribution and is currently being tested internally by IDs. This change was based on @rickhumphries 's implementing it there and overall it making more sense to do so. Interact still has some prototype work towards the creation of timelines but increasingly it might make more sense for interact to be an authority rather then a service; we'll see as things start to take more shape and evolve based on the way the community perceives and adopts these tools.

**Comment by btopro** [comment]
This is now an authority, testing the overall build process with this as a single system now instead of multiple. If it spins up the whole network correctly the nice thing is that it actually works usability wise now too :)

**Comment by btopro** [comment]
The point of these threads was to get the tools in position so that we have a set number of them for initial released version numbers. Interact builds and does provide timeline / file upload support OOTB. We'll start new threads in the future to add functionality to whats now there
