### ISSUE TITLE
cis-dashboard & JSDelivr CDN bug -- wrong CDN responding

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#971]
The new ELMSLN_CDN additions are working well in most places, however when JSDelivr is set and a user is on the cis-dashboard page the angularjs files are being loaded by CDNJS even though CDNJS is not currently set as the active CDN.

**Comment by mmilutinovic1313** [comment]
![cdnjs_wrong](https://cloud.githubusercontent.com/assets/7243665/16229842/881ec2ea-378c-11e6-8066-7456a8e18322.png)
![js_delivr_set](https://cloud.githubusercontent.com/assets/7243665/16229845/8f094602-378c-11e6-9347-88ef52f69c3b.png)

**Comment by btopro** [comment]
Guessing here but isn't that js library included direct from the cdn mentioned in the code? I believe this would be why your sites all libraries detection would fail cause u don't believe we actually have angular able to load locally at the moment

Wp8
________________________________

**Comment by mmilutinovic1313** [comment]
That makes sense lol. Found it in our code

`drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js', 'external');
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-resource.js', 'external');
  drupal_add_js(drupal_get_path('module', 'cis_dashboard') . '/js/app.js');
}`

I'll close this out then but I'll also add a step that we should have angular able to load locally (If that is something that we want it to do. This would be benificial since CDNJS (The CDN we tell it to use in the JS code) isn't supported in China.
