### ISSUE TITLE
replace entity_iframe drilldown with postMessage

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#975]
follow up to #954 

parent.postMessage('{"subject":"lti.frameResize", "height":' + wrapper_height + '}', '*');

global capabilities
refresh
Resize

It would be nice to replace the entity_iframe drill down resize method with the postMessage method. This is currently how we send xAPI data context from spaces down to

**Comment by btopro** [comment]
well this is miles faster and more accurate. i975 also supports real time resizing of the frame based on changes to the DOM! @heyMP !

**Comment by btopro** [comment]
#1040

**Comment by heyMP** [comment]
😀😍🤑. You're a beautiful human.👹
