### ISSUE TITLE
Angular Local Integration

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#978]
So I've been playing with a few modules that say that they support some form of Angular integration. The ones I've looked at all load angular via a CDN however (#977), which is not necessarily what we want to happen in case a CDN is / gets blocked in a certain region (i.e. China). 

My big question is how could I structure a folder in our libraries directory on drupal -- in order to be readable by the Libraries API? Would I need to create a module to do this? Could I do it manually by adding certain files?

**Comment by btopro** [comment]
`core/dslmcode/drupal-7.x/libraries/angular` or something. module to implement it yes. hook_libraries_api or whatever it is

**Comment by mmilutinovic1313** [comment]
I've set up the library in `core/dslmcode/drupal-7.x/libraries/angular` and Libraries API can detect it, but Drupal is yelling at me that I don't have it included in the `@online` specific libraries folder. Do I need to symlink it or something so it gets sent to all the systems to be fully readable?

**Comment by mmilutinovic1313** [comment]
Double checking that the libraries are loading correctly locally. Will make a PR after these checks go through. @btopro: you may have to run the elmsln-sync-lib command after the PR goes through to make sure the library gets picked up properly. 

Eventually we want to write an API for loading the angular libraries instead of just loading it in the cis_dashboard module.

**Comment by mmilutinovic1313** [comment]
This is fixed in #996
