### ISSUE TITLE
Virtual Box/Vagrant 32bit Linux issue

### ISSUE THREAD

**Issue by kfurst** [elmsln/elmsln#98]
In testing on another machine, I ran into an issue using the Vagrant method. Ubunutu 14.04 32bit. Couldn't get VirtualBox to start during/after the install. Went back and looked and if I'm reading it correctly on the VirtualBox downloads page, 32-bit isn't an option and one would need to configure a 64-bit environment (which I don't feel comfortable doing). Switched to a laptop (my go-to) with Mint that I thought was 64 and turned out to be another 32-bit install. Luckily, I dual-boot Windows 7 and tried installing that way (worked by the way).Was bummed though I could get it working on any of my Debian-based machines which is my OS of choice. 

Any ideas for how to approach this? (I can test on my laptop by using the Windows install but would still like to spin up another local on my Ubuntu machine).

**Comment by btopro** [comment]
I haven't tried this (we used to run off an ubuntu 32 bit box) but give this a shot:
Go to line 9
`config.vm.box = "chef/centos-6.5"`

Swap out centos-6.5 with centos-6.5-i386

Vagrant's cloud service where these are pulled from claims that this is a 32bit version of the same box. Our vagrant installer just takes the base environment and installs on top of it. We actually have installed successfully on Ubuntu 12 and 14 but as many colleges run RHEL we're shooting for something similar.

Let me know if it works and we can add it in (commented out) :)

**Comment by btopro** [comment]
I can confirm that this does in-fact appear to work :)

**Comment by btopro** [comment]
commit has the line needed, comment it in and the default one out and it should work
