### ISSUE TITLE
Ubuntu 14 Install doesn't seem to work.

### ISSUE THREAD

**Issue by vrracing** [elmsln/elmsln#987]
Fired up a virgin Ubuntu 14.04 instance at DigitalOcean, a 512mb instance.

Copied and ran the [U1404 instructions](https://github.com/elmsln/elmsln/blob/master/scripts/install/handsfree/ubuntu14/example-deploy) as root.

Note that line 2 says there are 3 lines to be run but there appear to be only 2.

Enhanced the host file with the outputted lines as instructed.

If I go to http://lor.elmsln.dev/   I get what appears to be a drupal installation page with this at the top...

![image](https://cloud.githubusercontent.com/assets/2730237/16353238/1b2c7ce6-3a3d-11e6-9c02-765c17bad6ab.png)

Any suggestions?

I apologize if this is the wrong place but I could see no links to a Google Group or mailing list for the project only "Community/Discussions" which brought me here.

Thanks,
Jim

**Comment by btopro** [comment]
Need 2 gigs to install and go to online.elmsln.dev after setup. Right place to ask :)

Wp8
________________________________

**Comment by vrracing** [comment]
Ah cool.  Thx.  I'd watched one of the YouTubes and noticed the minimal config was selected so just followed along.  Thx, I'll give it another go tomorrow.

**Comment by vrracing** [comment]
RAM isn't the issue.  I tried it again with a new DigitalOcean droplet with 2 GB Memory / 40 GB Disk / NYC2 - Ubuntu 14.04.4 x64 but got the same results.  I followed the directions and copy and pasted the two commands into the terminal as root with no edits.  Here are some error highlights in case there are clues...

No obvious errors until MySQL install then...

```
You can test the MySQL daemon with mysql-test-run.pl
cd /usr/mysql-test ; perl mysql-test-run.pl

Please report any problems at http://bugs.mysql.com/

ERROR 1396 (HY000) at line 1: Operation DROP USER failed for ''@'localhost'
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for ''@'elmsln1'
ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist
Cloning into 'config'...
```

Not a MySQL admin by night so don't know if these are critical.

Next git seems to go and there are some warnings...

```
Checking connectivity... done.
Initialized empty Git repository in /var/www/elmsln/config/.git/

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@elmsln1.(none)')
Enter the git repo you want to keep config in sync with: (ex: {user}@{YOURPRIVATEREPO}:YOU/elmsln-config-YOURUNIT.git)
You did not enter a repo so this is in local version control but not tracked remotely. It is highly recommended that you hook this up to a remote repository in the future!
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
The above should list information about the system this is being installed on. We currently support semi-automated install routines for RHEL, CentOS and Ubuntu. Please verify the above and select one of the following options:
1. RHEL 6.x / CentOS 6.x
2. Ubuntu / Debian
3. RHEL 7.x / CentOS 7.x
4. other / manual
treating this like ubuntu
```

Then it looks like composer runs and everything seems to go pear-shaped...

```
Changed current directory to /root/.config/composer
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing drush/drush (6.7.0)
    Downloading: 100%         

Writing lock file
Generating autoload files
/var/www/elmsln/scripts/install/root/elmsln-preinstall.sh: line 400: drush: command not found
groupadd: group 'elmsln' already exists
cp: cannot stat ‘/root/.composer’: No such file or directory

                                                                                                                     
  [Composer\Downloader\FilesystemException]                                                                          
  Filesystem exception:                                                                                              
  Composer update failed: the "/root/.composer/cache" directory used to download the temp file could not be written  
                                                                                                                     

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--] [<version>]


                                         
  [ErrorException]                       
  chdir(): Permission denied (errno 13)  
                                         

global <command-name> [<args>]...
```

More red error blocks follow.

Appreciate any tips!

**Comment by btopro** [comment]
Hmm did you try going to the online.elmsln.dev at the end? The vagrant based installer works but it will be a little bit til I can get someone on this.

**Comment by btopro** [comment]
@mmilutinovic1313 an you check this out. Follow the steps to reproduce and see if you find anything obvious. We develop on cent so Ubuntu falls out of sync now and then, always something minor

**Comment by bradallenfisher** [comment]
Just to pop in here. If you pasted the install line EXACTLY as is, it probably will fail. You need to change the parameters at the end to match your domain name. I didn't test this and don't know if this is the only issue. Just pointing it out.

**Comment by vrracing** [comment]
@bradallenfisher - My understanding is that you need to change the params IF you are pointing at the server with a custom domain.  I am not as we are just trying to compare ELMSLN with edX for our use cases.  So I was following the instructions at the end of the install script that tell you to update your local hosts file with the output generated at the end of the install.

@btopro - I'd spun up a CentOS droplet at DigitalOcean but yum and what-not are not configured and I don't want to spend hours googling basic CentOS admin tasks to get ready to try installing ELMSLN.

I was excited to see somes [images on hub.docker.com](https://hub.docker.com/r/elmsln/elmsln/) but they didn't look done given they had no description or other info so figure they could just as likely be DDoS bots as legitimate ELMSLN images.

I was going to try the vagrant install but the [link to the instructions](http://docs.elmsln.org/en/latest/development/Vagrant-Step-by-Step-setup/ ) is a dead end (well, a maze!)

Thanks!
Jim

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/blob/master/scripts/install/handsfree/centos7/example-deploy

**Comment by btopro** [comment]
@heyMP has put some initial effort into the docker image but we hope to get more into that in the future.

**Comment by btopro** [comment]
@vrracing can u tell me where that bad link is so I can fix it in our docs? here's the correct location for vagrant docs http://elmsln.readthedocs.io/en/latest/development/Vagrant-Step-by-Step-setup/

**Comment by btopro** [comment]
ok, can confirm an issue w/ drush trying to get installed, looking into it.

**Comment by btopro** [comment]
@bradallenfisher any idea why composer wouldn't be installing drush in `/root/.composer/vendor/drush/drush` as root but as other user accounts it does just fine w/ same command?

`php /usr/local/bin/composer global require drush/drush:6.*`

**Comment by vrracing** [comment]
@btopro Sure, Brian.  It's in the Vagrant section of the Install doc at 

https://elmsln.readthedocs.io/en/latest/INSTALL/

It's not a link, just a url in text.

**Comment by btopro** [comment]
@vrracing thx for the link, pushed up the change so this wont happen in the future.

**Comment by btopro** [comment]
@bradallenfisher we talked the other day and you seemed to know EXACTLY where the root user running composer would install drush since it's not `/root/.composer/` as one would expect based on other user accounts install location.

**Comment by bradallenfisher** [comment]
jumping on this now

**Comment by bradallenfisher** [comment]
how should i test this?
i think i figured it out... 

should i fork then change the hands free to point to my fork

**Comment by btopro** [comment]
@bradallenfisher nice fix
