### ISSUE TITLE
Figure Out Why Angular won't load in CDN Module

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#991]
This is related to #942 and #405. We have angular loading locally properly but for whatever reason the CDN is trying to load .js.map files for angular which is preventing angular from loading at all. Got to find the reason behind this. Attaching screenshot for reference.

**Comment by mmilutinovic1313** [comment]
I'm going to double check that this is still occurring. This may have been fixed in #996

**Comment by mmilutinovic1313** [comment]
@heyMP what was the command that you used to fake the system that the angular library was readable by Libraries API? When I blew away my last vagrant, the link went away

**Comment by heyMP** [comment]
I don't remember the exact command.  You need to create a symlink from the angular library into your stack's libraries directory.  So it would be something like:

`ln -s ~/elmsln/core/dslmcode/shared/drupal-7.x/libraries/angularjs ~/elmsln/domains/online/sites/all/libraries/angularjs

**Comment by btopro** [comment]
Oh come over tomorrow and we can run the developer command to merge this in w. Have the script run it

**Comment by mmilutinovic1313** [comment]
Sounds good - I'm currently in and I can come over whenever you get in!

**Comment by btopro** [comment]
this got fixed by the previous commit
