### ISSUE TITLE
Account Registration Defaults on New Sites

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#993]
Not sure if this is just on our instance, but when creating a new course service, the account registration defaults allow visitors to register accounts - and it does not require email validation:

![image](https://cloud.githubusercontent.com/assets/4973810/16421681/ae389f0c-3d4d-11e6-9252-393aa8f89843.png)

Should the default setup be to only allow admins to create accounts, so that accounts aren't maliciously created by bots?

**Comment by btopro** [comment]
yes but what option are you picking when creating the course space from the creation page? the require account to access / roster sync or whatever it is will automatically set this (or should)

**Comment by rickhumphries** [comment]
Ahhh right that makes sense. So in my initial meetings with OB they told me just to set this as 'open access' and I don't think I properly thought about the implications of that because I still thought 'well, it's not open cause you need an account to view it'. But that makes a lot of sense now. Glad I don't have like 100 courses setup like this! Thanks

**Comment by btopro** [comment]
Np. If you did then id give you the drush command to fix it everywhere automatically. Now, even with the sites that way I don't know if anyone could make an account BC bakery is doing the login. I'd check with them first about if there ws a reason for this / try and make an account on a site and see if you can login regardless of bakery

**Comment by btopro** [comment]
going to close out. Reopen if this isn't what the issue was
