### ISSUE TITLE
Build easyCDN Module to handle CDN and Library Loading

### ISSUE THREAD

**Issue by mmilutinovic1313** [elmsln/elmsln#994]
@heyMP and I talked a lot today about a more efficient way to add new libraries to ELMS and any Drupal site for that matter. I will be writing a custom module that will handle loading libraries and will allow us to choose where / how it is loaded, what version it will load, and if we want to free up library disk space. Attached is an initial drawup of @heyMP 's sketches of how we will structure the module. I will attach a TODO list as well in a further comment laying out my development plan and explaining the issue further.

![img_7730](https://cloud.githubusercontent.com/assets/7243665/16426314/760caa72-3d36-11e6-8acc-c40524136bb6.JPG)

**Comment by btopro** [comment]
Interesting idea. Does seem like you should be able to use the libraries API info to snag / install libraries automatically, though that's file system permission dependent. I like the idea of remote loading them off a CDN by toggling on a big page.

**Comment by mmilutinovic1313** [comment]
Description of what we want this module to do: 

The current implementation of implementing CDNs and Libraries API together on a system requires every component of the library to be set up properly. It needs to be detectable by `libraries_detect, proper versioning etc. 

The idea behind the easyCDN module is to have a remote system be able to allow developers to download new libraries, use old and new versions of libraries, and use CDN functionalities for libraries without having to rely on downloading libraries and modules that may or may not work properly with the Libraries API module. 

The modules will be checked out based on their searchable name on the JSDelivr CDN website. This is done by querying a search and getting a returned JSON object (http://api.jsdelivr.com/v1/jsdelivr/libraries?name=jquery). This object can then be searched for versions and all files contained within that version. This information will be the source of the info.json file that will be included in the easyCDN libraries directory allowing the user to have the ability to use different versions and search CDN's / local storage for files. If the user chooses to have this library downloaded locally - a new folder will be created in the easyCDN directory (either located in sites/all/libraries or another location that will allow for write access) with the version that was selected and the files that are contained in this version.

Doing it this way allows for multiple versions to be installed locally, but also allows users to remove old versions from the file system if they so choose. Developers can also just use the CDN to load the libraries which will free up space on the server. 

This module can make it easier for developers to test out new modules without needing to setup Libraries API friendly library structures manually.

**Comment by mmilutinovic1313** [comment]
- [ ] Build App (will be broken into other tasks).
- [ ] Test easyCDN works on all ELMS:LN systems
- [ ] Verify that working on vanilla Drupal
- [ ] Get Header add Access-Control-Allow-Origin "*" support if needed based on remote jquery making ajax calls" section.
- [ ] Submit to d.o.

**Comment by mmilutinovic1313** [comment]
https://github.com/mmilutinovic1313/easycdn/issues

**Comment by btopro** [comment]
@mmilutinovic1313 I updated the check list above after taking a glance at the progress you've made on this. If we get fallback support (aka page loads, ensures jQuery loaded, then checks that all other assets have loaded) as well as core support for serving up from rawgit we could effectively serve every correct copy of our "local" versions of files direct from rawgit with minimal effort. css_alter hook that would rewrite everything to use rawgit version of the same files.

**Comment by mmilutinovic1313** [comment]
Awesome! I have a few more features that I can check off too. I'm making fallback the priority in this issue for now. I'll have to figure out a way to make this fail for testing (probably just no internet connection).

**Comment by mmilutinovic1313** [comment]
Throwing this here: related to #1234 -- Do we want any China-specific CDNs? I have been reading that many of the CDNs get throttled even if they are approved. As of now, I think JsDelivr is adequate, but depending on where most of our students are logging in from, it may be something to consider.

**Comment by btopro** [comment]
@mmilutinovic1313 can you review abvove to see how much more of the original list you have done? this is really coming along!

**Comment by mmilutinovic1313** [comment]
Have done - the defaults aren't explicitly written in for it defaulting when the local version isn't available or warning that it's not on a CDN, but those will be some of the next steps. I should be able to add the JQueryCDN soon as that is a similar elseif case (unless it's syntax is really weird)

**Comment by btopro** [comment]
next step is also to get it to rewrite non-libraries as well. Like drupal core assets which could be delivered via rawgit. This would be a stand alone like "deliver as many assets as possible from CDN:" which starts w/ rawgit but then eventually would have our ELMSLN:CDN were we to build one

**Comment by mmilutinovic1313** [comment]
Sounds good to me. Would this be a part of the easycdn module too then? Or a seperate one?

**Comment by btopro** [comment]
umm.... hooked into it via add ons? Rawgit w/ elmsln support should basically do that already

**Comment by btopro** [comment]
Webcomponents make this almost irrelevant
