### ISSUE TITLE
Fix PHP 7 bombs in contrib

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#998]
So this doesn't cover ALL PHP 7 conformance BUT its the big obvious one. You can't do returns like this anymore:
`return;` which was a popular / lazy way of typically doing `return FALSE;`

@mmilutinovic1313 consider this your on going, when you have a few minutes here and there patch a contrib module kinda thing. We'll need to do this across all of our contrib base and in a quick search there's quite a bit.

**Comment by btopro** [comment]
`2465 matches across 681 files` BUT many of these are javascript which this doesn't need to be changed in so a decent enough search excluding .js files should widdle this down quick. THen the task is creating an issue on the different contrib projects we use and ensuring that there's a patch for their module which treats this issue so all of contrib can benefit.

**Comment by mmilutinovic1313** [comment]
Sounds good to me! Would you like me to commit into PRs early and often in case this does take a while? That way things would never get too far behind master.

**Comment by btopro** [comment]
yeah, these should go as PRs against master as well as patches against their associated contrib projects on drupal.org. Big patch bingo kind of task. PHP7 support in D7 has gotten a big push this weekend and now all but works (sans one weird thing w/ core sort ordering that's being backported from D8 still)

**Comment by mmilutinovic1313** [comment]
These files are in more than just `elmsln_contrib` correct? I.e. the whole file system?

**Comment by btopro** [comment]
all profiles and shared and stacks areas need verified. enjoy lol

**Comment by btopro** [comment]
@bradallenfisher since we were talking php7 today, any quick command we could throw into a VM so Mark could upgrade his cent7 VM to php 7 after spin up? There's bound to be contrib bombs

**Comment by bradallenfisher** [comment]
yep for bleeding edge latest rc1 run
```shell
yum install --enablerepo=remi-php71 php php-cli php-common php-fpm php-gd php-mbstring php-mcrypt php-mysqlnd php-opcache php-pdo php-pdo php-pecl-apcu php-pecl-jsonc php-pecl-zip php-xml
service httpd restart
service php-fpm restart
```

for the latest stable run

```shell
yum install --enablerepo=remi-php70 php php-cli php-common php-fpm php-gd php-mbstring php-mcrypt php-mysqlnd php-opcache php-pdo php-pdo php-pecl-apcu php-pecl-jsonc php-pecl-zip php-xml
service httpd restart
service php-fpm restart
```

i did both and both worked... had same errors. :)

<img width="1440" alt="screen shot 2016-10-11 at 7 37 16 pm" src="https://cloud.githubusercontent.com/assets/2347525/19292450/2ab3cb44-8fea-11e6-8f92-1a0e110704e8.png">

<img width="1440" alt="screen shot 2016-10-11 at 7 39 00 pm" src="https://cloud.githubusercontent.com/assets/2347525/19292477/647ddcd4-8fea-11e6-8158-a4fdf79f8fc3.png">

**Comment by bradallenfisher** [comment]
there's bombs allright. mainly around mcrypt

**Comment by btopro** [comment]
ha, ok, well, gives @mmilutinovic1313 a starting point for exploration / building spaces and looking for errors

**Comment by bradallenfisher** [comment]
yup
./core/dslmcode/shared/drupal-7.x/modules/ulmus/aes/aes.module:      $td = mcrypt_module_open($cipher, "", MCRYPT_MODE_CBC, "");
./core/dslmcode/shared/drupal-7.x/modules/ulmus/aes/aes.module:      $td = mcrypt_module_open($cipher, "", MCRYPT_MODE_CBC, "");
./core/dslmcode/shared/drupal-7.x/modules/ulmus/bakery/bakery.module:  $td = mcrypt_module_open('rijndael-128', '', 'ecb', '');
./core/dslmcode/shared/drupal-7.x/modules/ulmus/bakery/bakery.module:  $td = mcrypt_module_open('rijndael-128', '', 'ecb', '');

**Comment by btopro** [comment]
@mmilutinovic1313 Brad has a box working and we're very close to a state where we'd have a legit testbed / system that you could run through some test plans with to see if there are contrib bombs w/ minimal effort; Though from playing with it this honestly might have some deprecated library support to avoid issuesentirely which would be amazing

**Comment by btopro** [comment]
So brad just did a ton of this and we're not seeing bombs on PHP7 in Ubuntu 16 thus far / what ones there were he cleaned up. Any bug beyond this closing out should be related to specific issues that crop up / notices that we witness on PHP7 / any version in general.
