### ISSUE TITLE
review hook_set_cis_service_data

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#999]
see if it's still needed given the snake paradigm.

**Comment by mmilutinovic1313** [comment]
Found the function and am removing it to test. I'm planning on creating a course to test. Are there other specific tests you would like done to test that this does not break?

**Comment by btopro** [comment]
need to look around for things that implement the hook. I know it happens some places like in the mooc distro but that might be the only one

**Comment by mmilutinovic1313** [comment]
Okay sounds good -- I'll search for its implementation then and remove those as well before testing.

**Comment by mmilutinovic1313** [comment]
Tested to see if anything broke and removed the calls to this hook in the `cis_service_connection.module` file. Nothing broke so it looks like we are good to go. I'm making a PR now for this. If you'd like me to run any other specific tests before accepting the PR, let me know!

**Comment by btopro** [comment]
did u find where the hook is implemented elsewhere in the code? It has to exist somewhere

**Comment by mmilutinovic1313** [comment]
Did a search both on all my local files and with what is on github. Only place I can find that hook being referenced is at `core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_service_connection/cis_service_connection.module`
